package com.iortatechnxt.brokerverse.storage.service;

import com.iortatechnxt.brokerverse.storage.domain.FileOrigin;

/**
 * A module table whose file content is still kept in a {@code bytea} column (before build step
 * ST1), declared as a bean by the owning module so that {@code FILE_BYTEA_MIGRATION} can copy the
 * content to the file store without the storage module depending on the module.
 *
 * <p>{@code selectSql} returns the rows still to copy (content present, no {@code stored_file_id}),
 * in ascending key order after a key, at most a number of rows (parameters: key, limit), with the
 * columns {@code file_key} (bigint), {@code company_id}, {@code owner_id}, {@code record_class},
 * {@code document_type}, {@code file_name}, {@code content_type}, {@code recorded_sha256} (the
 * checksum the module recorded, may be null) and {@code content}. {@code attachSql} sets the stored
 * file of one row only while it is still unset (parameters: stored file id, key). {@code countSql}
 * returns {@code total} (rows with content) and {@code moved} (of which copied).
 *
 * @param table table name, e.g. {@code doc_attachment_content}
 * @param ownerType owner entity type of the stored files
 * @param origin generated by the application or supplied from outside (malware scan)
 * @param selectSql rows to copy
 * @param attachSql records the stored file of a row
 * @param countSql totals of the reconciliation report
 */
public record LegacyFileTable(
    String table,
    String ownerType,
    FileOrigin origin,
    String selectSql,
    String attachSql,
    String countSql) {}
