import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { attachmentsApi } from '@/api/attachments';
import { PLACEMENT_STATUS, renewalPlacementApi, transmissionLabel } from '@/api/renewalPlacement';
import type { AdviceView, PlacementView } from '@/api/renewalPlacement';
import type { CandidateDetail } from '@/api/renewal';
import { useAuth } from '@/auth/authContext';
import { useInsurerName } from '@/components/broking/useLabels';
import { useFileDownload } from '@/components/broking/useFileDownload';
import { Amount } from '@/components/ui/Amount';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import { DateInput } from '@/components/ui/DateInput';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { RowActionMenu } from '@/components/ui/RowActionMenu';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { useToast } from '@/components/ui/toastContext';
import { useCompanyId } from '@/context/workspaceContext';
import { formatDate, formatDateTime } from '@/utils/format';
import { RespondDialog } from './RespondDialog';
import { SaveAsDialog } from './SaveAsDialog';

function IssueEditor({ p, renewalRef }: Readonly<{ p: PlacementView; renewalRef: string }>) {
  const companyId = useCompanyId();
  const queryClient = useQueryClient();
  const save = useMutation({
    mutationFn: (body: { withIssue: boolean; resolutionDate: string | null }) =>
      renewalPlacementApi.issue(companyId, renewalRef, p.id, body),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['renewal', 'placements'] }),
  });
  if (p.submitted === null) {
    return <span className="muted">Not sent</span>;
  }
  return (
    <span className="rnw-actions">
      <label className="checkbox">
        <input
          type="checkbox"
          aria-label={`With Issue ${p.insurerCode}`}
          checked={p.withIssue}
          onChange={(e) => save.mutate({ withIssue: e.target.checked, resolutionDate: null })}
        />{' '}
        With Issue
      </label>
      {p.withIssue && (
        <DateInput
          aria-label={`Resolution Date ${p.insurerCode}`}
          value={p.resolutionDate ?? ''}
          min={p.submitted}
          onChange={(e) => save.mutate({ withIssue: true, resolutionDate: e.target.value || null })}
        />
      )}
      <ErrorAlert error={save.error} />
    </span>
  );
}

function AdviceCard({ renewalRef }: Readonly<{ renewalRef: string }>) {
  const companyId = useCompanyId();
  const { can } = useAuth();
  const download = useFileDownload();
  const queryClient = useQueryClient();
  const advices = useQuery({
    queryKey: ['renewal', 'advices', companyId, renewalRef],
    queryFn: () => renewalPlacementApi.advices(companyId, renewalRef),
  });
  const generate = useMutation({
    mutationFn: () => renewalPlacementApi.generateAdvice(companyId, renewalRef),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['renewal', 'advices'] }),
  });
  return (
    <Card
      title="Insurance Advice"
      flush
      actions={
        can('RNW_PROCESS') && (
          <Button
            size="sm"
            variant="secondary"
            busy={generate.isPending}
            onClick={() => generate.mutate()}
          >
            Generate Insurance Advice
          </Button>
        )
      }
    >
      <ErrorAlert error={advices.error ?? generate.error} />
      <DataTable<AdviceView>
        loading={advices.isLoading}
        rows={advices.data ?? []}
        rowKey={(a) => String(a.versionNo)}
        emptyMessage="No Insurance Advice (mortgaged accounts only)"
        columns={[
          { key: 'version', header: 'Version', render: (a) => a.versionNo },
          { key: 'file', header: 'File Name', render: (a) => a.fileName },
          { key: 'by', header: 'Generated By', render: (a) => a.generatedBy },
          {
            key: 'at',
            header: 'Generated On',
            kind: 'date',
            render: (a) => formatDateTime(a.generatedAt),
          },
          { key: 'ccm', header: 'CCM Message', render: (a) => a.messageNo ?? '' },
          {
            key: 'actions',
            header: 'Actions',
            render: (a) =>
              a.attachmentId !== null && (
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() =>
                    download.mutate(() => attachmentsApi.download(a.attachmentId ?? 0))
                  }
                >
                  Download
                </Button>
              ),
          },
        ]}
      />
    </Card>
  );
}

function usePlacementColumns(
  renewalRef: string,
  onSaveAs: (id: number, name: string) => void,
  onRespond: (p: PlacementView) => void,
) {
  const insurerName = useInsurerName();
  const { can } = useAuth();
  const download = useFileDownload();
  return [
    { key: 'insurer', header: 'Insurer', render: (p: PlacementView) => insurerName(p.insurerCode) },
    {
      key: 'share',
      header: 'Share (%)',
      kind: 'amount' as const,
      render: (p: PlacementView) => p.share,
    },
    {
      key: 'premium',
      header: 'Premium',
      kind: 'amount' as const,
      render: (p: PlacementView) => <Amount value={p.premium} />,
    },
    { key: 'slip', header: 'Placement Slip', render: (p: PlacementView) => p.docs.slipFileName },
    {
      key: 'status',
      header: 'Status',
      kind: 'status' as const,
      render: (p: PlacementView) => (
        <StatusBadge
          status={PLACEMENT_STATUS[p.status] ?? p.status}
          label={PLACEMENT_STATUS[p.status] ?? p.status}
          full
        />
      ),
    },
    {
      key: 'sent',
      header: 'Transmission',
      render: (p: PlacementView) => transmissionLabel(p.sending.channel, p.sending.status),
    },
    {
      key: 'submitted',
      header: 'Submitted',
      kind: 'date' as const,
      render: (p: PlacementView) => formatDate(p.submitted),
    },
    {
      key: 'tat',
      header: 'TAT (business days)',
      render: (p: PlacementView) =>
        p.tat === null ? '' : `${String(p.tat.days)} of ${String(p.tat.target)}`,
    },
    {
      key: 'sla',
      header: 'SLA',
      render: (p: PlacementView) =>
        p.tat === null ? '' : <StatusBadge status={p.tat.status} label={p.tat.status} full />,
    },
    {
      key: 'issue',
      header: 'With Issue',
      render: (p: PlacementView) => <IssueEditor p={p} renewalRef={renewalRef} />,
    },
    {
      key: 'response',
      header: 'Insurer Response',
      render: (p: PlacementView) =>
        [
          p.response.response === null ? '' : PLACEMENT_STATUS[p.response.response],
          p.response.reason,
        ]
          .filter(Boolean)
          .join(' - '),
    },
    {
      key: 'actions',
      header: 'Actions',
      render: (p: PlacementView) => (
        <RowActionMenu
          label={p.docs.slipFileName}
          actions={[
            ...(p.docs.slipAttachmentId === null
              ? []
              : [
                  {
                    label: 'Download Slip',
                    onSelect: () =>
                      download.mutate(() => attachmentsApi.download(p.docs.slipAttachmentId ?? 0)),
                  },
                  {
                    label: 'Download Slip As',
                    onSelect: () => onSaveAs(p.docs.slipAttachmentId ?? 0, p.docs.slipFileName),
                  },
                ]),
            ...(p.docs.fileAttachmentId === null
              ? []
              : [
                  {
                    label: 'Download Placement File',
                    onSelect: () =>
                      download.mutate(() => attachmentsApi.download(p.docs.fileAttachmentId ?? 0)),
                  },
                ]),
            ...(can('RNW_PROCESS') && p.status === 'SENT'
              ? [{ label: 'Record Insurer Response', onSelect: () => onRespond(p) }]
              : []),
          ]}
        />
      ),
    },
  ];
}

/**
 * The Placement tab of a renewal account (FRRN.029 to FRRN.032): the slip of each insurer with its
 * transmission status, turnaround time and SLA status, the With Issue tag and resolution date, the
 * insurer's response, the cancellation of a rejected placement and the Insurance Advice versions.
 */
export function PlacementTab({ detail }: Readonly<{ detail: CandidateDetail }>) {
  const ref = detail.row.renewalRef;
  const companyId = useCompanyId();
  const toast = useToast();
  const { can } = useAuth();
  const queryClient = useQueryClient();
  const [saveAs, setSaveAs] = useState<{ id: number; name: string } | null>(null);
  const [respond, setRespond] = useState<PlacementView | null>(null);
  const placements = useQuery({
    queryKey: ['renewal', 'placements', companyId, ref],
    queryFn: () => renewalPlacementApi.of(companyId, ref),
  });
  const cancel = useMutation({
    mutationFn: () =>
      renewalPlacementApi.cancel(companyId, ref, 'Placement cancelled after the insurer rejection'),
    onSuccess: async () => {
      toast.success('Placement cancelled');
      await queryClient.invalidateQueries({ queryKey: ['renewal'] });
    },
  });
  const columns = usePlacementColumns(ref, (id, name) => setSaveAs({ id, name }), setRespond);
  const rejected = (placements.data ?? []).some((p) => p.status === 'REJECTED');
  return (
    <div className="stack">
      <Card
        title="Placement"
        flush
        actions={
          can('RNW_PROCESS') &&
          rejected && (
            <Button
              size="sm"
              variant="secondary"
              busy={cancel.isPending}
              onClick={() => cancel.mutate()}
            >
              Cancel Placement
            </Button>
          )
        }
      >
        <ErrorAlert error={placements.error ?? cancel.error} />
        <DataTable<PlacementView>
          loading={placements.isLoading}
          rows={placements.data ?? []}
          rowKey={(p) => String(p.id)}
          emptyMessage="No placement generated"
          columns={columns}
        />
      </Card>
      <AdviceCard renewalRef={ref} />
      {saveAs !== null && (
        <SaveAsDialog
          attachmentId={saveAs.id}
          fileName={saveAs.name}
          onClose={() => setSaveAs(null)}
        />
      )}
      {respond !== null && (
        <RespondDialog renewalRef={ref} placement={respond} onClose={() => setRespond(null)} />
      )}
    </div>
  );
}
