package com.iortatechnxt.brokerverse.config;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.iortatechnxt.brokerverse.support.IntegrationTest;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * The application's runtime role (V1190) reads and writes rows only: no DDL, no TRUNCATE, no way to
 * disable the immutability triggers, no write to the migration history; and every insert-only table
 * refuses UPDATE, DELETE and TRUNCATE (V1191). The test database has one superuser login, so each
 * check runs in its own transaction under {@code SET LOCAL ROLE brokerverse_runtime} and is rolled
 * back.
 */
@IntegrationTest
class DatabaseRuntimeRoleIT {

  private static final String RUNTIME_ROLE = "brokerverse_runtime";

  /** Insert-only tables with row guards (UPDATE and DELETE) and a TRUNCATE guard. */
  private static final List<String> INSERT_ONLY =
      List.of(
          "audit_log",
          "gl_ledger_entry",
          "sec_access_change_log",
          "nba_access_request_event",
          "scr_client_risk_profile",
          "scr_case_event",
          "scr_committee_vote",
          "scr_watchlist_change",
          "mig_access_log",
          "bcl_insurer_update",
          "bcl_reserve_change",
          "bcl_status_history",
          "csf_activity",
          "crm_client_note_history",
          "ops_invoice_origin_snapshot");

  @Autowired private DataSource dataSource;
  @Autowired private JdbcTemplate jdbc;

  @Test
  void theRuntimeRoleIsNeitherSuperuserNorOwnerOfAnything() {
    assertThat(
            jdbc.queryForObject(
                "select rolsuper or rolcreaterole or rolcreatedb or rolbypassrls or rolreplication"
                    + " from pg_roles where rolname = ?",
                Boolean.class,
                RUNTIME_ROLE))
        .isFalse();
    assertThat(
            jdbc.queryForObject(
                "select count(*) from pg_class c join pg_roles r on r.oid = c.relowner"
                    + " where r.rolname = ?",
                Long.class,
                RUNTIME_ROLE))
        .isZero();
  }

  @Test
  void theRuntimeRoleReadsAndWritesRows() {
    assertThatCode(
            () ->
                asRuntime(
                    "select count(*) from audit_log",
                    "insert into csf_activity (company_id, agent, action, occurred_at, created_at,"
                        + " created_by) values (1, 'runtime-check', 'SEARCH', now(), now(),"
                        + " 'runtime-check')",
                    "update gl_ledger_entry set id = id where false",
                    "delete from audit_log where false",
                    "select version, description from flyway_schema_history limit 1"))
        .doesNotThrowAnyException();
  }

  @Test
  void theRuntimeRoleCannotChangeTheSchema() {
    assertRefused("create table runtime_check (id int)", "permission denied for schema");
    assertRefused("alter table audit_log add column runtime_check int", "must be owner");
    assertRefused("drop table audit_log", "must be owner");
    assertRefused("create index ix_runtime_check on audit_log (id)", "must be owner");
  }

  @Test
  void theRuntimeRoleCannotDisableTheImmutabilityTriggers() {
    assertRefused("alter table gl_ledger_entry disable trigger all", "must be owner");
    assertRefused("alter table audit_log disable trigger trg_audit_log_immutable", "must be owner");
    assertRefused("set session_replication_role = replica", "permission denied");
  }

  @Test
  void theRuntimeRoleCannotTruncateOrRewriteTheMigrationHistory() {
    assertRefused("truncate csf_activity", "permission denied for table");
    assertRefused("truncate audit_log", "permission denied for table");
    assertRefused("delete from flyway_schema_history where false", "permission denied for table");
    assertRefused(
        "update flyway_schema_history set checksum = 0 where false", "permission denied for table");
  }

  @Test
  void tablesCreatedByLaterMigrationsGetTheRuntimeGrants() throws SQLException {
    try (Connection connection = dataSource.getConnection()) {
      connection.setAutoCommit(false);
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            "create table runtime_default_check (id bigint generated by default as identity, v"
                + " int)");
        statement.execute("set local role " + RUNTIME_ROLE);
        statement.execute("insert into runtime_default_check (v) values (1)");
        statement.execute("update runtime_default_check set v = 2");
        statement.execute("delete from runtime_default_check");
      } finally {
        connection.rollback();
        connection.setAutoCommit(true);
      }
    }
  }

  @Test
  void everyInsertOnlyTableRefusesUpdateDeleteAndTruncate() {
    for (String table : INSERT_ONLY) {
      assertThat(triggerCount(table, "before update or delete row"))
          .as("row guard of %s", table)
          .isPositive();
      assertThat(triggerCount(table, "truncate")).as("truncate guard of %s", table).isPositive();
    }
    assertThat(triggerCount("wf_case_history", "truncate")).isPositive();
    assertThat(triggerCount("clx_unapplied_disposition", "truncate")).isPositive();
  }

  @Test
  void theGuardsRefuseTheChangeEvenForTheOwner() throws SQLException {
    assertOwnerRefused("truncate gl_ledger_entry cascade", "immutable");
    assertOwnerRefused("truncate wf_case_history cascade", "cannot be truncated");
    assertOwnerRefused(
        "insert into csf_activity (company_id, agent, action, occurred_at, created_at, created_by)"
            + " values (1, 'guard-check', 'VIEW', now(), now(), 'guard-check');"
            + " update csf_activity set detail = 'changed' where agent = 'guard-check'",
        "csf_activity rows are immutable");
    assertOwnerRefused(
        "insert into csf_activity (company_id, agent, action, occurred_at, created_at, created_by)"
            + " values (1, 'guard-check', 'VIEW', now(), now(), 'guard-check');"
            + " delete from csf_activity where agent = 'guard-check'",
        "csf_activity rows are immutable");
  }

  private long triggerCount(String table, String kind) {
    // tgtype bits: 1 row, 2 before, 8 delete, 16 update, 32 truncate.
    String condition =
        "truncate".equals(kind)
            ? "(t.tgtype & 32) <> 0"
            : "(t.tgtype & 1) <> 0 and (t.tgtype & 2) <> 0 and (t.tgtype & 8) <> 0"
                + " and (t.tgtype & 16) <> 0";
    Long count =
        jdbc.queryForObject(
            "select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid"
                + " where not t.tgisinternal and t.tgenabled <> 'D' and c.relname = ? and "
                + condition,
            Long.class,
            table);
    return count == null ? 0 : count;
  }

  private void assertRefused(String sql, String message) {
    assertThatThrownBy(() -> asRuntime(sql))
        .as(sql)
        .isInstanceOf(SQLException.class)
        .hasMessageContaining(message);
  }

  private void assertOwnerRefused(String sql, String message) throws SQLException {
    try (Connection connection = dataSource.getConnection()) {
      connection.setAutoCommit(false);
      try (Statement statement = connection.createStatement()) {
        assertThatThrownBy(() -> statement.execute(sql))
            .as(sql)
            .isInstanceOf(SQLException.class)
            .hasMessageContaining(message);
      } finally {
        connection.rollback();
        connection.setAutoCommit(true);
      }
    }
  }

  private void asRuntime(String... statements) throws SQLException {
    try (Connection connection = dataSource.getConnection()) {
      connection.setAutoCommit(false);
      try (Statement statement = connection.createStatement()) {
        statement.execute("set local role " + RUNTIME_ROLE);
        for (String sql : statements) {
          statement.execute(sql);
        }
      } finally {
        connection.rollback();
        connection.setAutoCommit(true);
      }
    }
  }
}
