package com.iortatechnxt.brokerverse.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.util.Base64;
import java.util.concurrent.TimeUnit;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManagerFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration;
import org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration;
import org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration;
import org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * HTTPS of the backend from a mounted PEM certificate and key, configured only through the
 * variables of application.yml ({@code BROKERVERSE_SERVER_SSL_*}) as the Kubernetes deployments set
 * them. The key pair is generated by the JDK keytool for the test; nothing is stored.
 */
class ServerTlsTest {

  private static final String PASSWORD = "changeit-test";

  @Test
  void theBackendServesHttpsFromTheMountedCertificate(@TempDir Path dir) throws Exception {
    KeyStore keyStore = generateKeyStore(dir);
    Path certificate = dir.resolve("tls.crt");
    Path key = dir.resolve("tls.key");
    Certificate cert = keyStore.getCertificate("server");
    Files.writeString(certificate, pem("CERTIFICATE", cert.getEncoded()));
    PrivateKey privateKey = (PrivateKey) keyStore.getKey("server", PASSWORD.toCharArray());
    Files.writeString(key, pem("PRIVATE KEY", privateKey.getEncoded()));

    try (ConfigurableApplicationContext context =
        new SpringApplicationBuilder(TlsServer.class)
            .web(WebApplicationType.SERVLET)
            .properties(
                "server.port=0",
                "BROKERVERSE_SERVER_SSL_ENABLED=true",
                "BROKERVERSE_SERVER_SSL_CERTIFICATE=file:" + certificate,
                "BROKERVERSE_SERVER_SSL_PRIVATE_KEY=file:" + key)
            .run()) {
      int port = ((ServletWebServerApplicationContext) context).getWebServer().getPort();
      TrustManagerFactory trust =
          TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
      KeyStore trusted = KeyStore.getInstance("PKCS12");
      trusted.load(null, null);
      trusted.setCertificateEntry("server", cert);
      trust.init(trusted);
      SSLContext ssl = SSLContext.getInstance("TLS");
      ssl.init(null, trust.getTrustManagers(), null);
      HttpClient client = HttpClient.newBuilder().sslContext(ssl).build();

      HttpResponse<String> response =
          client.send(
              HttpRequest.newBuilder(URI.create("https://localhost:" + port + "/tls-check"))
                  .build(),
              HttpResponse.BodyHandlers.ofString());

      assertThat(response.statusCode()).isEqualTo(200);
      assertThat(response.body()).isEqualTo("secure");
      assertThat(response.sslSession()).isPresent();
      assertThat(response.sslSession().orElseThrow().getProtocol()).isIn("TLSv1.3", "TLSv1.2");
    }
  }

  private static KeyStore generateKeyStore(Path dir)
      throws IOException, InterruptedException, GeneralSecurityException {
    Path store = dir.resolve("server.p12");
    Process keytool =
        new ProcessBuilder(
                Path.of(System.getProperty("java.home"), "bin", "keytool").toString(),
                "-genkeypair",
                "-alias",
                "server",
                "-keyalg",
                "RSA",
                "-keysize",
                "2048",
                "-validity",
                "2",
                "-dname",
                "CN=localhost",
                "-ext",
                "SAN=dns:localhost,ip:127.0.0.1",
                "-storetype",
                "PKCS12",
                "-keystore",
                store.toString(),
                "-storepass",
                PASSWORD,
                "-keypass",
                PASSWORD)
            .redirectErrorStream(true)
            .start();
    keytool.getInputStream().transferTo(OutputStream.nullOutputStream());
    assertThat(keytool.waitFor(60, TimeUnit.SECONDS)).isTrue();
    assertThat(keytool.exitValue()).isZero();
    KeyStore keyStore = KeyStore.getInstance("PKCS12");
    try (InputStream in = Files.newInputStream(store)) {
      keyStore.load(in, PASSWORD.toCharArray());
    }
    return keyStore;
  }

  private static String pem(String type, byte[] der) {
    return "-----BEGIN "
        + type
        + "-----\n"
        + Base64.getMimeEncoder(64, "\n".getBytes(StandardCharsets.US_ASCII)).encodeToString(der)
        + "\n-----END "
        + type
        + "-----\n";
  }

  /** A web server with the SSL settings of application.yml and one endpoint. */
  @Configuration(proxyBeanMethods = false)
  @ImportAutoConfiguration({
    SslAutoConfiguration.class,
    ServletWebServerFactoryAutoConfiguration.class,
    DispatcherServletAutoConfiguration.class,
    WebMvcAutoConfiguration.class
  })
  @RestController
  static class TlsServer {

    @GetMapping("/tls-check")
    String check() {
      return "secure";
    }
  }
}
