package com.iortatechnxt.brokerverse.renewal.domain;

import com.iortatechnxt.brokerverse.common.domain.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import java.time.LocalDate;

/**
 * A CLPC billing file (FRRN.027): the Built-in (amortized) or Non-Built-in accounts of a product
 * line For Billing Generation, generated by the daily CBG Home job, the FFY job or by hand, with
 * its delivery to the nominated recipients and its upload to the shared LMS directory.
 */
@Entity
@Table(name = "rnw_billing_file")
public class BillingFile extends BaseEntity {

  @Column(name = "company_id", nullable = false, updatable = false)
  private Long companyId;

  @Column(name = "file_name", nullable = false, length = 200, updatable = false)
  private String fileName;

  @Column(name = "line_code", length = 30, updatable = false)
  private String lineCode;

  @Column(name = "built_in", nullable = false, updatable = false)
  private boolean builtIn;

  @Column(name = "run_kind", nullable = false, length = 20, updatable = false)
  private String runKind;

  @Column(name = "from_date", updatable = false)
  private LocalDate fromDate;

  @Column(name = "to_date", updatable = false)
  private LocalDate toDate;

  @Column(nullable = false, updatable = false)
  private int accounts;

  @Column(name = "attachment_id")
  private Long attachmentId;

  @Column(name = "delivery_status", length = 20)
  private String deliveryStatus;

  @Column(name = "message_no", length = 30)
  private String messageNo;

  @Column(name = "delivery_error", length = 1000)
  private String deliveryError;

  @Column(name = "lms_status", length = 20)
  private String lmsStatus;

  /** For JPA. */
  protected BillingFile() {}

  /**
   * A generated file.
   *
   * @param companyId company
   * @param fileName file name
   * @param group product line and built-in
   * @param run kind of run and period
   * @param accounts number of accounts
   */
  public BillingFile(Long companyId, String fileName, Group group, Run run, int accounts) {
    this.companyId = companyId;
    this.fileName = fileName;
    this.lineCode = group.lineCode();
    this.builtIn = group.builtIn();
    this.runKind = run.kind();
    this.fromDate = run.from();
    this.toDate = run.to();
    this.accounts = accounts;
  }

  /**
   * Records the stored file.
   *
   * @param id attachment
   */
  public void stored(Long id) {
    this.attachmentId = id;
  }

  /**
   * Records the delivery.
   *
   * @param status delivery status
   * @param message channel message
   * @param error error, may be null
   */
  public void delivered(String status, String message, String error) {
    this.deliveryStatus = status;
    this.messageNo = message;
    this.deliveryError = error;
  }

  /**
   * Records the upload to the LMS directory.
   *
   * @param status UPLOADED, FAILED or OFF
   */
  public void lms(String status) {
    this.lmsStatus = status;
  }

  public Long getCompanyId() {
    return companyId;
  }

  public String getFileName() {
    return fileName;
  }

  public String getLineCode() {
    return lineCode;
  }

  public boolean isBuiltIn() {
    return builtIn;
  }

  public String getRunKind() {
    return runKind;
  }

  public LocalDate getFromDate() {
    return fromDate;
  }

  public LocalDate getToDate() {
    return toDate;
  }

  public int getAccounts() {
    return accounts;
  }

  public Long getAttachmentId() {
    return attachmentId;
  }

  public String getDeliveryStatus() {
    return deliveryStatus;
  }

  public String getMessageNo() {
    return messageNo;
  }

  public String getDeliveryError() {
    return deliveryError;
  }

  public String getLmsStatus() {
    return lmsStatus;
  }

  /**
   * The accounts of a file.
   *
   * @param lineCode product line
   * @param builtIn amortized accounts
   */
  public record Group(String lineCode, boolean builtIn) {}

  /**
   * The run that made a file.
   *
   * @param kind CBG_HOME, FFY or MANUAL
   * @param from first day of a manual run
   * @param to last day of a manual run
   */
  public record Run(String kind, LocalDate from, LocalDate to) {}
}
