package com.iortatechnxt.brokerverse.coa.domain;

import com.iortatechnxt.brokerverse.common.domain.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Numbering scheme of the children of a parent account (FRBS 2.3.2): a child's number is the parent
 * code, an optional separator and the next sequence of a fixed width, e.g. parent {@code 1210},
 * separator {@code .}, width 2 gives {@code 1210.01}, {@code 1210.02}...
 */
@Entity
@Table(name = "coa_numbering")
public class CoaNumbering extends BaseEntity {

  @Column(name = "company_id", nullable = false)
  private Long companyId;

  @Column(name = "parent_code", nullable = false, length = 30)
  private String parentCode;

  @Column(nullable = false, length = 1)
  private String separator;

  @Column(nullable = false)
  private int width;

  @Column(nullable = false)
  private boolean active = true;

  protected CoaNumbering() {}

  /**
   * Creates a scheme.
   *
   * @param companyId company
   * @param parentCode parent account code
   * @param separator separator between the parent code and the sequence ("" / "." / "-")
   * @param width digits of the sequence
   */
  public CoaNumbering(Long companyId, String parentCode, String separator, int width) {
    this.companyId = companyId;
    this.parentCode = parentCode;
    this.separator = separator;
    this.width = width;
  }

  /**
   * Changes the scheme.
   *
   * @param separator separator
   * @param width digits
   * @param active whether codes are proposed
   */
  public void change(String separator, int width, boolean active) {
    this.separator = separator;
    this.width = width;
    this.active = active;
  }

  /**
   * The code of the n-th child.
   *
   * @param sequence child sequence (1 based)
   * @return code
   */
  public String codeOf(int sequence) {
    String digits = String.valueOf(sequence);
    return parentCode + separator + "0".repeat(Math.max(0, width - digits.length())) + digits;
  }

  /**
   * The sequence of a child code generated by this scheme.
   *
   * @param code child code
   * @return sequence, or -1 when the code does not follow the scheme
   */
  public int sequenceOf(String code) {
    String prefix = parentCode + separator;
    if (!code.startsWith(prefix) || code.length() != prefix.length() + width) {
      return -1;
    }
    String tail = code.substring(prefix.length());
    return tail.chars().allMatch(Character::isDigit) ? Integer.parseInt(tail) : -1;
  }

  public Long getCompanyId() {
    return companyId;
  }

  public String getParentCode() {
    return parentCode;
  }

  public String getSeparator() {
    return separator;
  }

  public int getWidth() {
    return width;
  }

  public boolean isActive() {
    return active;
  }
}
