import {
  CheckCheck,
  Receipt,
  FileCheck2,
  Send,
  ArrowLeftRight,
  ChartColumn,
  Gauge,
  PiggyBank,
  CalendarClock,
  ClipboardCheck,
  FileText,
  Headset,
  Landmark,
  Layers,
  ListChecks,
  Mails,
  RefreshCcw,
  ScrollText,
  Settings2,
  RadioTower,
  ShieldAlert,
  UserCheck,
  Workflow,
} from 'lucide-react';
import { lazy } from 'react';
import type { FeatureModule } from '@/navigation/types';

/**
 * Renewal (BRD-6; docs/architecture/RENEWAL_DESIGN.md section 12): the expiring accounts from
 * extraction and sanitation to the disposition, the Team Leader review, processing with the
 * insurer, the Renewal Advice, the acceptance and the booking of the renewal, in Client & Policy
 * after Placement & Booking. Renewal reports are in the Report Centre under Renewal.
 */
export const renewalModule: FeatureModule = {
  id: 'renewal',
  section: 'Renewal',
  screens: [
    {
      path: '/renewal',
      label: 'Renewal Home',
      icon: RefreshCcw,
      permission: 'RNW_VIEW',
      component: lazy(() => import('./home/RenewalHomePage')),
    },
    {
      path: '/renewal/dashboard',
      label: 'Renewal Dashboard',
      icon: ChartColumn,
      permission: 'RNW_REPORT_VIEW',
      alsoPermissions: ['RNW_DISPOSE', 'RNW_REVIEW', 'RNW_PROCESS'],
      component: lazy(() => import('./dashboard/RenewalDashboardPage')),
    },
    {
      path: '/renewal/accounts',
      label: 'Renewal Accounts',
      icon: Layers,
      permission: 'RNW_REPORT_VIEW',
      alsoPermissions: ['RNW_DISPOSE', 'RNW_REVIEW', 'RNW_PROCESS'],
      component: lazy(() => import('./accounts/RenewalAccountsPage')),
    },
    {
      path: '/renewal/processing-dashboard',
      label: 'Processing Dashboard',
      icon: Gauge,
      permission: 'RNW_PROCESS',
      alsoPermissions: ['RNW_PROCESS_ASSIGN'],
      component: lazy(() => import('./dashboard/ProcessingDashboardPage')),
    },
    {
      path: '/renewal/expiry',
      label: 'Expiry List',
      icon: CalendarClock,
      permission: 'RNW_VIEW',
      component: lazy(() => import('./expiry/ExpiryListPage')),
    },
    {
      path: '/renewal/mine',
      label: 'My Dispositions',
      icon: UserCheck,
      permission: 'RNW_DISPOSE',
      component: lazy(() => import('./mine/MyDispositionsPage')),
    },
    {
      path: '/renewal/review',
      label: 'TL Review',
      icon: ClipboardCheck,
      permission: 'RNW_REVIEW',
      component: lazy(() => import('./review/ReviewPage')),
    },
    {
      path: '/renewal/transfers',
      label: 'Transfers',
      icon: ArrowLeftRight,
      permission: 'RNW_ASSIGN',
      component: lazy(() => import('./transfers/TransfersPage')),
    },
    {
      path: '/renewal/referrals',
      label: 'Transfer Requests',
      icon: ArrowLeftRight,
      permission: 'RNW_ASSIGN',
      alsoPermissions: ['RNW_DISPOSE'],
      component: lazy(() => import('./referrals/ReferralsPage')),
    },
    {
      path: '/renewal/processing',
      label: 'Processing Worklist',
      icon: Workflow,
      permission: 'RNW_PROCESS',
      component: lazy(() => import('./processing/ProcessingPage')),
    },
    {
      path: '/renewal/approvals',
      label: 'Submitted for Approval',
      icon: CheckCheck,
      permission: 'RNW_REVIEW',
      alsoPermissions: ['RNW_DISPOSE', 'RNW_PROCESS_ASSIGN'],
      component: lazy(() => import('./approval/ApprovalsPage')),
    },
    {
      path: '/renewal/placement',
      label: 'Submitted for Placement',
      icon: Send,
      permission: 'RNW_PROCESS',
      component: lazy(() => import('./placement/PlacementPage')),
    },
    {
      path: '/renewal/tsu-requests',
      label: 'TSU Requests',
      icon: FileText,
      permission: 'RNW_REVIEW',
      component: lazy(() => import('./proposal/TsuQueuePage')),
    },
    {
      path: '/renewal/tsu-queue',
      label: 'Renewal TSU Requests',
      icon: FileText,
      permission: 'TSU_PROCESS',
      alsoPermissions: ['TSU_APPROVE'],
      hidden: true,
      component: lazy(() => import('./proposal/TsuQueuePage')),
    },
    {
      path: '/renewal/kyc',
      label: 'KYC Monitoring',
      icon: ShieldAlert,
      permission: 'RNW_DISPOSE',
      alsoPermissions: ['RNW_PROCESS', 'RNW_REVIEW'],
      component: lazy(() => import('./kyc/KycDashboardPage')),
    },
    {
      path: '/renewal/risk-codes',
      label: 'Risk Code Maintenance',
      icon: ListChecks,
      permission: 'RNW_SETUP',
      alsoPermissions: ['RNW_REVIEW', 'RNW_PROCESS_ASSIGN'],
      component: lazy(() => import('./riskcodes/RiskCodesPage')),
    },
    {
      path: '/renewal/billing',
      label: 'CLPC Billing Files',
      icon: Receipt,
      permission: 'RNW_PROCESS',
      component: lazy(() => import('./billing/BillingFilesPage')),
    },
    {
      path: '/renewal/epolicies',
      label: 'E-Policies',
      icon: FileCheck2,
      permission: 'RNW_PROCESS',
      component: lazy(() => import('./epolicy/EpolicyPage')),
    },
    {
      path: '/renewal/insurer',
      label: 'Insurer Batches',
      icon: Landmark,
      permission: 'RNW_INSURER',
      component: lazy(() => import('./insurer/InsurerBatchesPage')),
    },
    {
      path: '/renewal/letters',
      label: 'Letters',
      icon: Mails,
      permission: 'RNW_RA_GENERATE',
      component: lazy(() => import('./letters/LettersPage')),
    },
    {
      path: '/renewal/followups',
      label: 'Follow-ups',
      icon: Headset,
      permission: 'RNW_FOLLOWUP',
      component: lazy(() => import('./followups/FollowupsPage')),
    },
    {
      path: '/renewal/lamd',
      label: 'LAMD Reports',
      icon: ListChecks,
      permission: 'RNW_LAMD_UPLOAD',
      component: lazy(() => import('./lamd/LamdPage')),
    },
    {
      path: '/renewal/rmu-officers',
      label: 'RMU Account Maintenance',
      icon: ShieldAlert,
      permission: 'RNW_RMU_MAINTAIN',
      alsoPermissions: ['RNW_LAMD_UPLOAD'],
      component: lazy(() => import('./uploads/RmuOfficersPage')),
    },
    {
      path: '/renewal/channels',
      label: 'Channel Monitor',
      icon: RadioTower,
      permission: 'RNW_CHANNEL_MONITOR',
      component: lazy(() => import('./channels/ChannelMonitorPage')),
    },
    {
      path: '/renewal/audit-logs',
      label: 'Audit Logs',
      icon: ScrollText,
      permission: 'RNW_AUDIT_VIEW',
      component: lazy(() => import('./audit/AuditLogsPage')),
    },
    {
      path: '/renewal/budget',
      label: 'Renewal Annual Budget',
      icon: PiggyBank,
      permission: 'RNW_BUDGET',
      component: lazy(() => import('./budget/BudgetPage')),
    },
    {
      path: '/renewal/setup',
      label: 'Renewal Setup',
      icon: Settings2,
      permission: 'RNW_SETUP',
      alsoPermissions: ['RNW_PACKAGE_REMAP'],
      component: lazy(() => import('./setup/RenewalSetupPage')),
    },
    {
      path: '/renewal/candidates/:ref',
      label: 'Renewal',
      icon: FileText,
      permission: 'RNW_VIEW',
      component: lazy(() => import('./record/CandidatePage')),
      hidden: true,
    },
  ],
};
