import type { CandidateDetail, CandidateRow } from '@/api/renewal';

/** A renewal row of the tests. */
export function row(overrides: Partial<CandidateRow> = {}): CandidateRow {
  return {
    renewalRef: 'RNW-2026-000001',
    stage: 'FOR_DISPOSITION',
    stageLabel: 'For Disposition',
    bucket: 'REVIEW',
    disposition: null,
    reason: null,
    remarks: null,
    policy: {
      source: 'BOOKING',
      sourceRef: 'INV-1',
      expiringInvoiceNo: 'INV-1',
      expiringArn: 'ARN-1',
      policyNo: 'POL-1',
      coverNo: null,
      versionNo: 1,
      productCode: 'MTR12',
      productName: 'Motor',
      lineCode: 'MOTOR',
      insurerCode: 'INS1',
      inception: '2025-10-01',
      pnNos: 'PN-9',
      mortgaged: true,
      mortgageeBank: 'Bank',
    },
    parties: {
      clientId: 1,
      clientCode: 'C001',
      clientName: 'Santos Trading',
      assuredName: null,
      segment: 'INSTITUTIONAL',
      businessOrigin: 'BANK',
      accountType: 'CORPORATE',
      branchCode: 'MKT',
      regionCode: 'NCR',
      departmentCode: 'D1',
      salesUnit: 'T-CORP1',
      ownerUnit: 'T-CORP1',
      unitHead: 'mkttl',
      accountOfficer: 'ao',
      assignedAo: 'ao',
      assignedPo: null,
    },
    money: {
      currency: 'PHP',
      basicPremium: 1000,
      grossPremium: 1200,
      sumInsured: 500000,
      premiumRate: 0.2,
      commissionRate: 10,
      outstanding: 50,
      claimCount: 0,
      claimStatus: 'None',
    },
    flags: {
      urgent: true,
      returned: false,
      transferred: false,
      endorsed: false,
      claims: false,
      outstanding: true,
      kycDue: false,
      kycFlaggedAt: null,
      nrns: false,
      stp: false,
      locked: false,
      nfrSent: false,
    },
    expiry: '2026-10-01',
    daysToExpiry: 4,
    ...overrides,
  };
}

/** A renewal record of the tests. */
export function detail(overrides: Partial<CandidateRow> = {}): CandidateDetail {
  return {
    row: row(overrides),
    lifecycle: {
      id: 7,
      policyYear: 2,
      initiatedBy: 'mkttl',
      initiatedAt: '2026-09-01T00:00:00Z',
      evaluatedAt: '2026-09-01T00:00:00Z',
      bucketRuleVersion: 1,
      proposal: { disposition: 'FOR_RENEWAL', automation: 'MANUAL', matrixVersion: 1, ruleId: 3 },
      raNotice: 'FIRST',
      path: 'RENEWAL',
      links: {
        renewalArn: null,
        quotationRef: null,
        proposalRef: null,
        renewedInvoiceNo: null,
        closedAs: null,
        closedAt: null,
      },
      legacyPackage: { legacyCode: null, legacyVersion: null, productCode: null, versionNo: null },
    },
    blocking: ['Premium outstanding on the expiring invoice'],
    historyViewed: false,
  };
}
