import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarClock, Download, FileText, Layers, Send, UserRound, Wallet } from 'lucide-react';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '@/auth/authContext';
import { RecordSummary } from '@/components/broking/RecordSummary';
import { ReferenceChip } from '@/components/broking/ReferenceChip';
import { SendEmailDialog } from '@/components/broking/SendEmailDialog';
import { SentMessages } from '@/components/broking/SentMessages';
import { useFileDownload } from '@/components/broking/useFileDownload';
import { Amount } from '@/components/ui/Amount';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import type { Column } from '@/components/ui/DataTable';
import { DataTable } from '@/components/ui/DataTable';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { useToast } from '@/components/ui/toastContext';
import { formatAmount, formatDate, formatDateTime, humanize } from '@/utils/format';
import { ReasonDialog, RecordLoading } from '../plans/Parts';
import type { SendStatement, Statement, StatementLine } from './api';
import { billingApi } from './api';
import { cycleText, statementEmail } from './labels';

const ENTITY = 'BillingStatement';

const LINE_COLUMNS: Column<StatementLine>[] = [
  {
    key: 'kind',
    header: 'Line',
    render: (l) => (l.kind === 'ARREARS' ? 'Arrears' : 'Current Cycle'),
  },
  { key: 'inv', header: 'Invoice No.', render: (l) => l.invoiceNo ?? 'Scheduled' },
  { key: 'year', header: 'Policy Year', render: (l) => l.policyYear },
  {
    key: 'cover',
    header: 'Coverage',
    render: (l) => `${formatDate(l.coverageFrom)} – ${formatDate(l.coverageTo)}`,
  },
  { key: 'due', header: 'Due Date', render: (l) => formatDate(l.dueDate) },
  { key: 'amount', header: 'Amount', numeric: true, render: (l) => <Amount value={l.amount} /> },
  { key: 'paid', header: 'Paid', numeric: true, render: (l) => <Amount value={l.paid} /> },
  { key: 'bal', header: 'Balance', numeric: true, render: (l) => <Amount value={l.balance} /> },
];

function Summary({ s }: Readonly<{ s: Statement }>) {
  return (
    <RecordSummary
      title={s.assuredName}
      chips={
        <>
          <ReferenceChip label="SOA" value={s.soaNo} />
          <ReferenceChip label="ARN" value={s.arn} />
          <StatusBadge status={s.status} />
        </>
      }
      flags={<span className="tag">{humanize(s.frequency)} Billing</span>}
      facts={[
        { icon: Layers, label: 'Billing Cycle', value: `${s.cycleSeq}: ${cycleText(s)}` },
        { icon: CalendarClock, label: 'Due Date', value: formatDate(s.dueDate) },
        {
          icon: Wallet,
          label: `Amount Due (${s.currency})`,
          value: `${formatAmount(s.balance)} of ${formatAmount(s.total)}`,
        },
        {
          icon: FileText,
          label: 'Plan',
          value: <Link to={`/collections/plans/${s.planId}`}>Open Installment Plan</Link>,
        },
        {
          icon: UserRound,
          label: 'Generated By',
          value: `${s.generatedBy}, ${formatDateTime(s.createdAt)}`,
        },
      ]}
    />
  );
}

/** Page actions: download the PDF; for a live statement, cancel it or send it by e-mail. */
function StatementActions({
  live,
  downloading,
  onDownload,
  onCancel,
  onSend,
}: Readonly<{
  live: boolean;
  downloading: boolean;
  onDownload: () => void;
  onCancel: () => void;
  onSend: () => void;
}>) {
  return (
    <>
      <Button
        variant="secondary"
        icon={<Download size={16} />}
        busy={downloading}
        onClick={onDownload}
      >
        Download PDF
      </Button>
      {live && (
        <>
          <Button variant="danger" onClick={onCancel}>
            Cancel Statement
          </Button>
          <Button variant="accent" icon={<Send size={16} />} onClick={onSend}>
            Send via Email
          </Button>
        </>
      )}
    </>
  );
}

/**
 * Statement of account (BRCLXN.058/060): the billing cycle, the installments billed (the cycle's
 * and any arrears), the PDF from the template CLX_SOA, sending by e-mail and cancellation.
 */
export default function StatementDetailPage() {
  const id = Number(useParams().id);
  const { can } = useAuth();
  const toast = useToast();
  const queryClient = useQueryClient();
  const download = useFileDownload();
  const [sending, setSending] = useState(false);
  const [cancelling, setCancelling] = useState(false);
  const statement = useQuery({
    queryKey: ['collections', 'statement', id],
    queryFn: () => billingApi.statement(id),
  });
  const recipient = useQuery({
    queryKey: ['collections', 'statement', id, 'recipient'],
    queryFn: () => billingApi.recipient(id),
    enabled: sending,
  });
  const done = async (s: Statement, message: string) => {
    queryClient.setQueryData(['collections', 'statement', id], s);
    await queryClient.invalidateQueries({ queryKey: ['collections', 'statements'] });
    await queryClient.invalidateQueries({ queryKey: ['messages', ENTITY, String(id)] });
    toast.success(message);
  };
  const send = useMutation({
    mutationFn: (mail: SendStatement) => billingApi.send(id, mail),
    onSuccess: async (s) => {
      setSending(false);
      await done(s, `${s.soaNo} sent to ${s.sentTo ?? ''}`);
    },
  });
  const cancel = useMutation({
    mutationFn: (reason: string) => billingApi.cancel(id, reason),
    onSuccess: async (s) => {
      setCancelling(false);
      await done(s, `${s.soaNo} cancelled; the cycle can be billed again`);
    },
  });
  if (statement.data === undefined) {
    return <RecordLoading error={statement.error} />;
  }
  const s = statement.data;
  const live = s.status !== 'CANCELLED' && can('CLX_BILLING');
  return (
    <div className="stack">
      <PageHeader
        section="Finance · Collections · Billing Statements"
        backTo="/collections/billing"
        title={s.soaNo}
        description={`Statement of account for billing cycle ${cycleText(s)} of ${s.arn}`}
        actions={
          <StatementActions
            live={live}
            downloading={download.isPending}
            onDownload={() => download.mutate(() => billingApi.document(id))}
            onCancel={() => setCancelling(true)}
            onSend={() => setSending(true)}
          />
        }
      />
      <ErrorAlert error={download.error} />
      <Summary s={s} />
      {s.cancelReason !== undefined && (
        <div className="alert warning">Cancelled: {s.cancelReason}</div>
      )}
      <Card title="Installments Billed">
        <DataTable
          caption="Installments billed"
          columns={LINE_COLUMNS}
          rows={s.lines}
          rowKey={(l) => l.lineNo}
        />
        <p className="muted">
          Template {s.templateVersion ?? '–'}. Billing is for monitoring only: this statement
          creates no receivable and no commission billing.
        </p>
      </Card>
      <Card title="E-mails Sent">
        <SentMessages entityType={ENTITY} entityId={id} />
      </Card>
      {sending && !recipient.isLoading && (
        <SendEmailDialog
          title="Send Statement of Account"
          initial={{ ...statementEmail(s), to: recipient.data?.email ?? '', protect: true }}
          attachmentNames={[`${s.soaNo}.pdf`]}
          busy={send.isPending}
          error={send.error ?? recipient.error}
          onClose={() => setSending(false)}
          onSend={(draft) =>
            send.mutate({
              to: draft.to,
              cc: draft.cc,
              subject: draft.subject,
              body: draft.body,
              passwordHint: draft.passwordHint,
            })
          }
        />
      )}
      {cancelling && (
        <ReasonDialog
          title="Cancel Statement of Account"
          confirmLabel="Cancel Statement"
          busy={cancel.isPending}
          error={cancel.error}
          onClose={() => setCancelling(false)}
          onConfirm={(reason) => cancel.mutate(reason)}
        />
      )}
    </div>
  );
}
