import { useMutation } from '@tanstack/react-query';
import type { ReactNode } from 'react';
import { attachmentsApi } from '@/api/attachments';
import { saveFile } from '@/api/client';
import type { ProposalFile } from '@/api/pmTerms';
import { Card } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import type { Column } from '@/components/ui/DataTable';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { RowActionMenu } from '@/components/ui/RowActionMenu';
import { formatDateTime } from '@/utils/format';

/**
 * The proposal slips generated, one per selected insurer and version (BDOI FRS FRPM.009.02,
 * FRPM.013.01), newest first, each downloadable.
 */
export function ProposalFilesCard({
  files,
  loading,
  actions,
}: Readonly<{ files: ProposalFile[]; loading: boolean; actions?: ReactNode }>) {
  const download = useMutation({
    mutationFn: (attachmentId: number) => attachmentsApi.download(attachmentId),
    onSuccess: (file) => saveFile(file.blob, file.fileName),
  });
  const columns: Column<ProposalFile>[] = [
    { key: 'insurer', header: 'Insurer', render: (f) => f.insurerName },
    { key: 'version', header: 'Version', numeric: true, render: (f) => f.versionNo },
    { key: 'file', header: 'File Name', render: (f) => f.fileName },
    { key: 'by', header: 'Generated By', render: (f) => f.generatedBy },
    { key: 'at', header: 'Generated On', render: (f) => formatDateTime(f.generatedAt) },
    {
      key: 'actions',
      header: 'Actions',
      render: (f) =>
        f.attachmentId === null ? null : (
          <RowActionMenu
            label={f.fileName}
            actions={[
              {
                label: 'Download',
                onSelect: () => {
                  if (f.attachmentId !== null) {
                    download.mutate(f.attachmentId);
                  }
                },
              },
            ]}
          />
        ),
    },
  ];
  return (
    <Card title="Proposal Slips" actions={actions} flush>
      <ErrorAlert error={download.error} />
      <DataTable
        columns={columns}
        rows={files}
        rowKey={(f) => f.id}
        loading={loading}
        emptyMessage="No proposal has been generated yet"
      />
    </Card>
  );
}
