package com.iortatechnxt.brokerverse.issuance.domain;

/** What generates an Insurance Advice (BRNB.095, parameter IA_TRIGGER, Q30). */
public enum AdviceTrigger {
  /** Generated by a user. */
  MANUAL,
  /** Generated when the placement is sent to the insurer. */
  ON_PLACEMENT,
  /** Generated when the policy is issued (default). */
  ON_POLICY_ISSUE
}
