package com.iortatechnxt.brokerverse.report.domain;

/** What an archived report run was (CSHID.017/018). */
public enum ReportRunAction {
  /** Run on screen. */
  VIEW,
  /** Exported (downloaded or printed); the file is kept. */
  EXPORT,
  /**
   * Generated by a scheduled job (daily, weekly or monthly files, BRCLXN.024-029, 045); the file is
   * kept and may be downloaded from its availability time on.
   */
  GENERATE
}
