package com.iortatechnxt.brokerverse.report.domain;

import com.iortatechnxt.brokerverse.common.domain.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.Arrays;
import java.util.Objects;

/**
 * One archived run (on-screen view) or export of a report (CSHID.018: generated reports with name,
 * date and creator, downloadable only by users allowed to export). The file of an export is kept
 * apart in {@link ReportRunFile}.
 */
@Entity
@Table(name = "report_run")
public class ReportRun extends BaseEntity {

  private static final int MAX_PARAMETERS = 2000;

  @Column(name = "report_code", nullable = false, length = 40, updatable = false)
  private String reportCode;

  @Column(nullable = false, length = 200, updatable = false)
  private String title;

  @Column(nullable = false, length = 40, updatable = false)
  private String category;

  @Column(length = MAX_PARAMETERS, updatable = false)
  private String parameters;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false, length = 10, updatable = false)
  private ReportRunAction action;

  @Column(length = 10, updatable = false)
  private String format;

  @Column(name = "row_count", nullable = false, updatable = false)
  private int rowCount;

  @Column(name = "file_name", length = 255, updatable = false)
  private String fileName;

  @Column(name = "content_type", length = 100, updatable = false)
  private String contentType;

  @Column(name = "size_bytes", updatable = false)
  private Long sizeBytes;

  @Column(name = "available_from", updatable = false)
  private Instant availableFrom;

  protected ReportRun() {}

  /**
   * An on-screen run.
   *
   * @param facts report code, title, category, parameter echo and row count
   * @return run
   */
  public static ReportRun viewed(RunFacts facts) {
    ReportRun run = new ReportRun();
    run.fill(facts);
    run.action = ReportRunAction.VIEW;
    return run;
  }

  /**
   * An export with its file.
   *
   * @param facts report code, title, category, parameter echo and row count
   * @param file format, name, type and content
   * @return run
   */
  public static ReportRun exported(RunFacts facts, RunFile file) {
    ReportRun run = new ReportRun();
    run.fill(facts);
    run.action = ReportRunAction.EXPORT;
    run.format = file.format();
    run.fileName = file.fileName();
    run.contentType = file.contentType();
    run.sizeBytes = (long) file.content().length;
    return run;
  }

  /**
   * A file generated by a scheduled job, downloadable from a given time (BRCLXN.024-029, 045).
   *
   * @param facts report, parameters and row count
   * @param file generated file
   * @param availableFrom when users may download it; null = at once
   * @return run
   */
  public static ReportRun generated(RunFacts facts, RunFile file, Instant availableFrom) {
    ReportRun run = exported(facts, file);
    run.action = ReportRunAction.GENERATE;
    run.availableFrom = availableFrom;
    return run;
  }

  /**
   * Whether the file of the run may be downloaded at a time.
   *
   * @param now time
   * @return false only for a generated file before its availability time
   */
  public boolean isAvailableAt(Instant now) {
    return availableFrom == null || !now.isBefore(availableFrom);
  }

  private void fill(RunFacts facts) {
    this.reportCode = facts.reportCode();
    this.title = facts.title();
    this.category = facts.category();
    String text = facts.parameters();
    this.parameters =
        text == null || text.length() <= MAX_PARAMETERS ? text : text.substring(0, MAX_PARAMETERS);
    this.rowCount = facts.rowCount();
  }

  public String getReportCode() {
    return reportCode;
  }

  public String getTitle() {
    return title;
  }

  public String getCategory() {
    return category;
  }

  public String getParameters() {
    return parameters;
  }

  public ReportRunAction getAction() {
    return action;
  }

  public String getFormat() {
    return format;
  }

  public int getRowCount() {
    return rowCount;
  }

  public String getFileName() {
    return fileName;
  }

  public String getContentType() {
    return contentType;
  }

  public Long getSizeBytes() {
    return sizeBytes;
  }

  public Instant getAvailableFrom() {
    return availableFrom;
  }

  /**
   * What was run.
   *
   * @param reportCode report code
   * @param title report title
   * @param category category key
   * @param parameters parameter echo
   * @param rowCount rows of the result
   */
  public record RunFacts(
      String reportCode, String title, String category, String parameters, int rowCount) {}

  /**
   * The exported file.
   *
   * @param format export format
   * @param fileName file name
   * @param contentType MIME type
   * @param content bytes
   */
  public record RunFile(String format, String fileName, String contentType, byte[] content) {

    /** Defensive copy. */
    public RunFile {
      content = content.clone();
    }

    @Override
    public byte[] content() {
      return content.clone();
    }

    @Override
    public boolean equals(Object o) {
      return o instanceof RunFile f
          && format.equals(f.format)
          && fileName.equals(f.fileName)
          && Arrays.equals(content, f.content);
    }

    @Override
    public int hashCode() {
      return Objects.hash(format, fileName, Arrays.hashCode(content));
    }

    @Override
    public String toString() {
      return "RunFile[" + fileName + ", " + content.length + " bytes]";
    }
  }
}
