import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FilePlus2 } from 'lucide-react';
import { useState } from 'react';
import { attachmentsApi } from '@/api/attachments';
import { renewalApprovalApi } from '@/api/renewalApproval';
import type { BillingFileView } from '@/api/renewalApproval';
import { transmissionLabel } from '@/api/renewalPlacement';
import { useAuth } from '@/auth/authContext';
import { useFileDownload } from '@/components/broking/useFileDownload';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import { DateInput } from '@/components/ui/DateInput';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { Field } from '@/components/ui/Field';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { RowActionMenu } from '@/components/ui/RowActionMenu';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { useToast } from '@/components/ui/toastContext';
import { useCompanyId } from '@/context/workspaceContext';
import { formatDateTime, today as todayIso } from '@/utils/format';
import { RENEWAL_SECTION } from '../common/renewalCodes';
import { SaveAsDialog } from '../placement/SaveAsDialog';
import '../renewal.css';

const RUNS: Record<string, string> = {
  CBG_HOME: 'CBG Home job',
  FFY: 'FFY Motor job',
  MANUAL: 'Manual',
};
const LMS: Record<string, string> = { UPLOADED: 'Uploaded', FAILED: 'Upload Failed', OFF: 'Off' };

function GenerateDialog({ onClose }: Readonly<{ onClose: () => void }>) {
  const companyId = useCompanyId();
  const toast = useToast();
  const queryClient = useQueryClient();
  const [to, setTo] = useState(todayIso());
  const [from, setFrom] = useState(todayIso());
  const generate = useMutation({
    mutationFn: () => renewalApprovalApi.generateBilling(companyId, from, to),
    onSuccess: async (files) => {
      toast.success(`${String(files.length)} billing file(s) generated`);
      onClose();
      await queryClient.invalidateQueries({ queryKey: ['renewal', 'billing'] });
    },
  });
  return (
    <Modal
      open
      title="Generate Billing File"
      onClose={onClose}
      footer={
        <>
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button busy={generate.isPending} onClick={() => generate.mutate()}>
            Generate
          </Button>
        </>
      }
    >
      <ErrorAlert error={generate.error} />
      <Field label="From Date" required hint="At most 31 calendar days before the To Date">
        {(id) => (
          <DateInput id={id} value={from} max={to} onChange={(e) => setFrom(e.target.value)} />
        )}
      </Field>
      <Field label="To Date" required>
        {(id) => (
          <DateInput id={id} value={to} max={todayIso()} onChange={(e) => setTo(e.target.value)} />
        )}
      </Field>
    </Modal>
  );
}

/**
 * CLPC Billing Files (FRRN.027): the Built-in and Non-Built-in billing files of the CBG Home and FFY
 * Motor accounts For Billing Generation, generated by the jobs or by hand for a period of at most
 * 31 days, with their delivery and LMS upload; preview, download or download under another name.
 */
export default function BillingFilesPage() {
  const companyId = useCompanyId();
  const { can } = useAuth();
  const download = useFileDownload();
  const [open, setOpen] = useState(false);
  const [saveAs, setSaveAs] = useState<BillingFileView | null>(null);
  const files = useQuery({
    queryKey: ['renewal', 'billing', companyId],
    queryFn: () => renewalApprovalApi.billingFiles(companyId),
  });
  return (
    <div className="stack">
      <PageHeader
        section={RENEWAL_SECTION}
        title="CLPC Billing Files"
        description="Billing files of the accounts For Billing Generation."
        actions={
          can('RNW_PROCESS') && (
            <Button icon={<FilePlus2 size={16} />} onClick={() => setOpen(true)}>
              Generate Billing File
            </Button>
          )
        }
      />
      <Card flush>
        <ErrorAlert error={files.error} />
        <DataTable<BillingFileView>
          loading={files.isLoading}
          rows={files.data ?? []}
          rowKey={(f) => String(f.id)}
          emptyMessage="No billing file generated"
          columns={[
            { key: 'name', header: 'File Name', render: (f) => f.fileName },
            {
              key: 'type',
              header: 'File Type',
              render: (f) => (f.builtIn ? 'Built-in' : 'Non-Built-in'),
            },
            { key: 'run', header: 'Generated By', render: (f) => RUNS[f.runKind] ?? f.runKind },
            { key: 'accounts', header: 'Accounts', kind: 'amount', render: (f) => f.accounts },
            {
              key: 'delivery',
              header: 'Delivery Status',
              kind: 'status',
              render: (f) => (
                <StatusBadge
                  status={transmissionLabel('CCM', f.deliveryStatus)}
                  label={transmissionLabel('CCM', f.deliveryStatus)}
                  full
                />
              ),
            },
            { key: 'error', header: 'Error Reason', render: (f) => f.deliveryError ?? '' },
            { key: 'lms', header: 'LMS Upload', render: (f) => LMS[f.lmsStatus ?? ''] ?? '' },
            { key: 'at', header: 'Generated On', render: (f) => formatDateTime(f.generatedAt) },
            {
              key: 'actions',
              header: 'Actions',
              render: (f) =>
                f.attachmentId !== null && (
                  <RowActionMenu
                    label={f.fileName}
                    actions={[
                      {
                        label: 'Download',
                        onSelect: () =>
                          download.mutate(() => attachmentsApi.download(f.attachmentId ?? 0)),
                      },
                      { label: 'Download As', onSelect: () => setSaveAs(f) },
                    ]}
                  />
                ),
            },
          ]}
        />
      </Card>
      {open && <GenerateDialog onClose={() => setOpen(false)} />}
      {typeof saveAs?.attachmentId === 'number' && (
        <SaveAsDialog
          attachmentId={saveAs.attachmentId}
          fileName={saveAs.fileName}
          onClose={() => setSaveAs(null)}
        />
      )}
    </div>
  );
}
