package com.iortatechnxt.brokerverse.issuance.api.dto;

import com.iortatechnxt.brokerverse.issuance.domain.InsuranceAdvice;
import java.time.Instant;

/**
 * An Insurance Advice of the register (BRNB.060).
 *
 * @param id id
 * @param iaNo IA number
 * @param accountId account
 * @param arn Account Reference Number
 * @param clientName insured
 * @param mortgageeBank mortgagee bank
 * @param insurerCode insurer
 * @param policyNumbers policy numbers at generation
 * @param triggerEvent what generated it
 * @param templateVersion template version used
 * @param status GENERATED or SENT
 * @param sendCount sends
 * @param lastSentAt last send
 * @param lastSentTo last recipients
 * @param createdAt generated at
 * @param createdBy generated by
 */
public record AdviceResponse(
    Long id,
    String iaNo,
    Long accountId,
    String arn,
    String clientName,
    String mortgageeBank,
    String insurerCode,
    String policyNumbers,
    String triggerEvent,
    String templateVersion,
    String status,
    int sendCount,
    Instant lastSentAt,
    String lastSentTo,
    Instant createdAt,
    String createdBy) {

  /**
   * Maps an advice.
   *
   * @param a advice
   * @return response
   */
  public static AdviceResponse from(InsuranceAdvice a) {
    return new AdviceResponse(
        a.getId(),
        a.getIaNo(),
        a.getAccountId(),
        a.getArn(),
        a.getClientName(),
        a.getMortgageeBank(),
        a.getInsurerCode(),
        a.getPolicyNumbers(),
        a.getTriggerEvent().name(),
        a.getTemplateVersion(),
        a.getStatus().name(),
        a.getSendCount(),
        a.getLastSentAt(),
        a.getLastSentTo(),
        a.getCreatedAt(),
        a.getCreatedBy());
  }
}
