package com.iortatechnxt.finverse.system;

import static com.iortatechnxt.finverse.support.CsrfRequests.post;
import static com.iortatechnxt.finverse.support.CsrfRequests.put;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.iortatechnxt.finverse.common.exception.ResourceNotFoundException;
import com.iortatechnxt.finverse.support.IntegrationTest;
import com.iortatechnxt.finverse.system.domain.JobTrigger;
import com.iortatechnxt.finverse.system.service.JobRegistry;
import com.iortatechnxt.finverse.system.service.SystemInfoService;
import com.iortatechnxt.finverse.system.service.SystemInfoService.ConfigEntry;
import com.iortatechnxt.finverse.system.service.SystemParameterService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithUserDetails;
import org.springframework.test.web.servlet.MockMvc;

@IntegrationTest
class SystemAdminIT {

  @Autowired private SystemParameterService parameters;
  @Autowired private SystemInfoService info;
  @Autowired private JobRegistry jobs;
  @Autowired private MockMvc mvc;

  @Test
  void parametersAreTypedValidatedAndAudited() {
    assertThat(parameters.list())
        .extracting("key")
        .contains("SESSION_TIMEOUT_MINUTES", "AGEING_BUCKETS");
    assertThat(parameters.items(SystemParameterService.AGEING_BUCKETS))
        .containsExactly("30", "60", "90", "180");
    assertThat(parameters.items("MISSING")).isEmpty();
    assertThat(parameters.text(SystemParameterService.REPORT_FOOTER_TEXT, "x"))
        .contains("FinVerse");
    assertThat(parameters.text("MISSING", "fallback")).isEqualTo("fallback");
    assertThat(parameters.intValue("MISSING", 7)).isEqualTo(7);
    assertThatThrownBy(() -> parameters.update("SESSION_TIMEOUT_MINUTES", "2"))
        .extracting("code")
        .isEqualTo("INVALID_PARAMETER_VALUE");
    assertThatThrownBy(() -> parameters.update("SESSION_TIMEOUT_MINUTES", "x".repeat(1001)))
        .extracting("code")
        .isEqualTo("INVALID_PARAMETER_VALUE");
    assertThatThrownBy(() -> parameters.get("MISSING"))
        .isInstanceOf(ResourceNotFoundException.class);
    assertThat(parameters.update("SESSION_TIMEOUT_MINUTES", " 45 ").getValue()).isEqualTo("45");
    assertThat(parameters.intValue(SystemParameterService.SESSION_TIMEOUT_MINUTES, 30))
        .isEqualTo(45);
    parameters.update("SESSION_TIMEOUT_MINUTES", "30");
  }

  @Test
  void applicationInformation() {
    var about = info.about();
    assertThat(about.product()).isEqualTo("iNXT FinVerse");
    assertThat(about.vendor()).isEqualTo("IortaTechNXT");
    assertThat(about.version()).isNotBlank();
    var details = info.info();
    assertThat(details.migrationVersion()).isNotBlank();
    assertThat(details.migrationsApplied()).isGreaterThanOrEqualTo(8);
    assertThat(details.databaseVersion()).contains("PostgreSQL");
    assertThat(details.health()).isNotBlank();
    assertThat(info.configuration())
        .extracting(ConfigEntry::key)
        .contains("spring.application.name", "java.version")
        .noneMatch(k -> k.contains("secret") || k.contains("password"));
    assertThat(info.configuration())
        .filteredOn(e -> e.key().equals("spring.datasource.url"))
        .allMatch(e -> !e.value().contains("password="));
  }

  @Test
  void jobRegistryListsJobsWithNextRun() {
    assertThat(jobs.statuses())
        .anySatisfy(
            s -> {
              assertThat(s.job().name()).isEqualTo("RECURRING_JOURNALS");
              assertThat(s.nextRun()).isNotNull();
            })
        .anySatisfy(s -> assertThat(s.job().name()).isEqualTo("ALERT_DAILY_CHECKS"));
    assertThat(jobs.nextRun(JobRegistry.DISABLED)).isNull();
    assertThatThrownBy(() -> jobs.run("NO_SUCH_JOB", JobTrigger.MANUAL))
        .isInstanceOf(ResourceNotFoundException.class);
  }

  @Test
  @WithUserDetails("admin")
  void administratorEndpoints() throws Exception {
    mvc.perform(
            put("/api/v1/system/parameters/REPORT_FOOTER_TEXT")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"value\":\"Generated by iNXT FinVerse. Confidential.\"}"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.updatedBy").value("admin"));
    mvc.perform(post("/api/v1/system/jobs/ALERT_DAILY_CHECKS/run"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.trigger").value("MANUAL"))
        .andExpect(jsonPath("$.triggeredBy").value("admin"));
    mvc.perform(get("/api/v1/system/jobs/runs?job=ALERT_DAILY_CHECKS"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.content[0].jobName").value("ALERT_DAILY_CHECKS"));
    mvc.perform(get("/api/v1/system/jobs"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$[?(@.name == 'ALERT_DAILY_CHECKS')].lastRun").exists());
  }

  @Test
  @WithUserDetails("accountant")
  void everyUserGetsAboutAndSessionPolicyButNotAdministration() throws Exception {
    mvc.perform(get("/api/v1/system/about"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.vendor").value("IortaTechNXT"));
    mvc.perform(get("/api/v1/system/session-policy"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.timeoutMinutes").isNumber())
        .andExpect(jsonPath("$.warningSeconds").value(60));
    mvc.perform(get("/api/v1/system/parameters")).andExpect(status().isForbidden());
    mvc.perform(
            put("/api/v1/system/parameters/SESSION_TIMEOUT_MINUTES")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"value\":\"10\"}"))
        .andExpect(status().isForbidden());
  }
}
