package com.iortatechnxt.brokerverse.submitted.service.adapter;

import com.iortatechnxt.brokerverse.common.security.CurrentUser;
import com.iortatechnxt.brokerverse.storage.service.FileOwnerAccess;
import com.iortatechnxt.brokerverse.storage.service.PermissionFileAccess;
import java.util.List;
import java.util.Set;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * The files of Submitted Policies in the file store: the letters (owner {@value #LETTER}, opened
 * by the Submitted Policies users), the print batches and No Touch billing files (owners {@value
 * #PRINT_BATCH} and {@value #NO_TOUCH}, opened by the senders of letters and the handling-fee
 * team). All are generated by the application.
 */
@Configuration(proxyBeanMethods = false)
public class SubmittedFileStorage {

  /** Owner type of a letter PDF. */
  public static final String LETTER = "SubmittedLetter";

  /** Owner type of a print batch file. */
  public static final String PRINT_BATCH = "SubmittedPrintBatch";

  /** Owner type of a No Touch billing file. */
  public static final String NO_TOUCH = "SubmittedNoTouch";

  /**
   * Who may open the letters.
   *
   * @param currentUser current user
   * @return resolver
   */
  @Bean
  FileOwnerAccess submittedLetterFileAccess(CurrentUser currentUser) {
    return new PermissionFileAccess(Set.of(LETTER), List.of("SBM_VIEW"), currentUser);
  }

  /**
   * Who may open the print batches and No Touch files.
   *
   * @param currentUser current user
   * @return resolver
   */
  @Bean
  FileOwnerAccess submittedBatchFileAccess(CurrentUser currentUser) {
    return new PermissionFileAccess(
        Set.of(PRINT_BATCH, NO_TOUCH),
        List.of("SBM_LETTER_SEND", "SBM_HANDLING_FEE", "SBM_REPORT_EXPORT"),
        currentUser);
  }
}
