import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { opsApi } from '@/api/operations';
import type { ReportRun } from '@/api/operations';
import { useFileDownload } from '@/components/broking/useFileDownload';
import { Card } from '@/components/ui/Card';
import type { Column } from '@/components/ui/DataTable';
import { DataTable } from '@/components/ui/DataTable';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { PageHeader } from '@/components/ui/PageHeader';
import { PageFooter } from '@/components/ui/Pager';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { formatDateTime } from '@/utils/format';
import { orUndefined } from './invoiceSearch';
import { fileAvailable, runLabel, runStatus } from './reportRuns';
import './operations.css';
import { reportApi } from '@/api/reports';
import { CellStack } from '@/components/ui/CellStack';
import { Field } from '@/components/ui/Field';
import { RowActions } from '@/components/ui/RowActions';
import { UserName } from '@/components/ui/UserName';

/** Download button of an archived file, or the time from which a scheduled file is available. */
function FileCell({ run, onDownload }: Readonly<{ run: ReportRun; onDownload: () => void }>) {
  if (fileAvailable(run)) {
    return <RowActions record={run.title} actions={[{ label: 'Download', onSelect: onDownload }]} />;
  }
  return (
    <span className="ops-muted">
      {run.availableFrom === undefined ? '' : `Available from ${formatDateTime(run.availableFrom)}`}
    </span>
  );
}

/**
 * Report archive (CSHID.017/018): every run and export of the Operations reports with its
 * parameters, creator and time, and the files generated by scheduled jobs with the time from which
 * they may be downloaded (BRCLXN.024-029, 045). Users allowed to export download an archived file
 * again; view-only users see the list and run the report on screen from the Report Centre.
 */
export default function ReportArchivePage() {
  const download = useFileDownload();
  const [code, setCode] = useState<string>();
  const catalogue = useQuery({ queryKey: ['reports', 'catalogue'], queryFn: reportApi.catalogue });
  const [page, setPage] = useState(0);
  const runs = useQuery({
    queryKey: ['ops', 'report-runs', code, page],
    queryFn: () => opsApi.reportRuns(code, page),
  });
  const columns: Column<ReportRun>[] = [
    {
      key: 'report',
      header: 'Report',
      render: (r) => <strong>{r.title}</strong>,
    },
    { key: 'params', header: 'Parameters', render: (r) => r.parameters ?? '' },
    {
      key: 'action',
      header: 'Action',
      render: (r) => <StatusBadge status={runStatus(r)} label={runLabel(r)} />,
    },
    { key: 'rows', header: 'Rows', numeric: true, render: (r) => r.rowCount },
    {
      key: 'by',
      header: 'Generated',
      render: (r) => (
        <CellStack main={formatDateTime(r.createdAt)} sub={<UserName login={r.createdBy} />} />
      ),
    },
    {
      key: 'file',
      header: 'File',
      render: (r) => (
        <FileCell run={r} onDownload={() => download.mutate(() => opsApi.reportRunFile(r.id))} />
      ),
    },
  ];
  return (
    <div className="stack">
      <PageHeader
        section="Operations"
        title="Report Archive"
        description="Operations reports generated on screen or exported, with their parameters and who generated them."
      />
      <ErrorAlert error={runs.error ?? download.error} />
      <Card>
        <div className="stack">
          <div className="ops-toolbar">
            <Field label="Report">
              {(id) => (
                <select
                  id={id}
                  className="select"
                  value={code ?? ''}
                  onChange={(e) => {
                    setCode(orUndefined(e.target.value));
                    setPage(0);
                  }}
                >
                  <option value="">All reports</option>
                  {[...(catalogue.data ?? [])]
                    .sort((a, b) => a.title.localeCompare(b.title))
                    .map((r) => (
                      <option key={r.code} value={r.code}>
                        {r.title}
                      </option>
                    ))}
                </select>
              )}
            </Field>
          </div>
          <DataTable
            caption="Archived report runs"
            columns={columns}
            rows={runs.data?.content ?? []}
            rowKey={(r) => r.id}
            loading={runs.isLoading}
            emptyMessage="No items to display"
          />
          <PageFooter data={runs.data} noun="runs" onPage={setPage} />
        </div>
      </Card>
    </div>
  );
}
