package com.iortatechnxt.brokerverse.report.core;

import com.iortatechnxt.brokerverse.audit.domain.AuditAction;
import com.iortatechnxt.brokerverse.audit.service.AuditTrailService;
import com.iortatechnxt.brokerverse.common.exception.BusinessRuleException;
import com.iortatechnxt.brokerverse.common.exception.ResourceNotFoundException;
import com.iortatechnxt.brokerverse.report.domain.ReportRun;
import com.iortatechnxt.brokerverse.report.domain.ReportRun.RunFacts;
import com.iortatechnxt.brokerverse.report.domain.ReportRun.RunFile;
import com.iortatechnxt.brokerverse.report.domain.ReportRunFile;
import com.iortatechnxt.brokerverse.report.domain.ReportRunFileRepository;
import com.iortatechnxt.brokerverse.report.domain.ReportRunRepository;
import com.iortatechnxt.brokerverse.storage.domain.FileOrigin;
import com.iortatechnxt.brokerverse.storage.domain.FileOwner;
import com.iortatechnxt.brokerverse.storage.service.FileDownload;
import com.iortatechnxt.brokerverse.storage.service.StoredFileService;
import com.iortatechnxt.brokerverse.storage.service.StoredFileService.StoreRequest;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Archive of generated reports (CSHID.017/018): every on-screen run and export of an archived
 * report is kept with its parameters, creator and time, exports with their file. Users see the runs
 * of the reports they may view; only users allowed to export a report download its files. Files
 * generated by scheduled jobs are archived with the time from which they may be downloaded
 * (BRCLXN.024-029, 045).
 *
 * <p>Files are kept in the file store (owner type {@value #OWNER_TYPE}, the run id; record class
 * {@code REPORT_OUTPUT} unless the caller names another; build step ST1). Files of runs before ST1
 * are read from {@code report_run_file} until {@code FILE_BYTEA_MIGRATION} has copied them.
 */
@Service
@Transactional
public class ReportArchiveService {

  /** Owner entity type of the stored files of archived runs. */
  public static final String OWNER_TYPE = "ReportRun";

  /** Record class of report files. */
  public static final String REPORT_OUTPUT = "REPORT_OUTPUT";

  private static final String ENTITY = OWNER_TYPE;

  private final ReportRunRepository runs;
  private final ReportRunFileRepository files;
  private final ReportRegistry registry;
  private final StoredFileService storedFiles;
  private final AuditTrailService audit;
  private final Clock clock;

  /**
   * Creates the service.
   *
   * @param runs archived runs
   * @param files files of archived exports kept in the database before ST1
   * @param registry report catalogue
   * @param storedFiles file store
   * @param audit audit trail
   * @param clock clock (file availability)
   */
  public ReportArchiveService(
      ReportRunRepository runs,
      ReportRunFileRepository files,
      ReportRegistry registry,
      StoredFileService storedFiles,
      AuditTrailService audit,
      Clock clock) {
    this.runs = runs;
    this.files = files;
    this.registry = registry;
    this.storedFiles = storedFiles;
    this.audit = audit;
    this.clock = clock;
  }

  /**
   * Archives an on-screen run of an archived report.
   *
   * @param metadata report
   * @param echo parameter echo
   * @param result result
   */
  public void viewed(ReportMetadata metadata, List<String> echo, ReportResult result) {
    if (metadata.archived()) {
      runs.save(ReportRun.viewed(facts(metadata, echo, result)));
    }
  }

  /**
   * Archives an export of an archived report with its file.
   *
   * @param metadata report
   * @param echo parameter echo
   * @param result result
   * @param file exported file
   */
  public void exported(
      ReportMetadata metadata, List<String> echo, ReportResult result, RunFile file) {
    if (metadata.archived()) {
      ReportRun run = runs.save(ReportRun.exported(facts(metadata, echo, result), file));
      store(run, file, REPORT_OUTPUT);
    }
  }

  /**
   * Archives a file generated by a scheduled job (daily, weekly and monthly Collections files,
   * BRCLXN.024-029, 041, 045), whatever the report's archive flag. The file may be downloaded, by
   * users allowed to export the report, from {@code availableFrom} on.
   *
   * @param code report code (a registered report)
   * @param echo parameter echo (e.g. period, unit, branch)
   * @param rowCount rows in the file
   * @param file generated file
   * @param availableFrom when users may download it; null = at once
   * @return the archived run
   */
  public ReportRun archiveGenerated(
      String code, List<String> echo, int rowCount, RunFile file, Instant availableFrom) {
    return archiveGenerated(code, echo, rowCount, file, availableFrom, REPORT_OUTPUT);
  }

  /**
   * Archives a file generated by a scheduled job or an extraction, kept under a record class of its
   * own (for example {@code STR} for suspicious transaction reports as filed).
   *
   * @param code report code (a registered report)
   * @param echo parameter echo
   * @param rowCount rows in the file
   * @param file generated file
   * @param availableFrom when users may download it; null = at once
   * @param recordClass record class of the stored file
   * @return the archived run
   */
  public ReportRun archiveGenerated(
      String code,
      List<String> echo,
      int rowCount,
      RunFile file,
      Instant availableFrom,
      String recordClass) {
    ReportMetadata m = registry.get(code).metadata();
    ReportRun run =
        runs.save(
            ReportRun.generated(
                new RunFacts(
                    m.code(), m.title(), m.category().name(), String.join("; ", echo), rowCount),
                file,
                availableFrom));
    store(run, file, recordClass);
    audit.record(
        ENTITY,
        run.getId(),
        AuditAction.CREATE,
        "Generated " + file.fileName() + " of " + code + ", available from " + availableFrom);
    return run;
  }

  /**
   * Archived runs of the reports the user may view, newest first.
   *
   * @param code one report, null for all
   * @param pageable page
   * @return runs
   */
  @Transactional(readOnly = true)
  public Page<ReportRun> runs(String code, Pageable pageable) {
    List<String> codes =
        registry.catalogue().stream()
            .filter(ReportMetadata::archived)
            .filter(ReportAccess::mayView)
            .map(ReportMetadata::code)
            .filter(c -> code == null || code.isBlank() || c.equals(code))
            .toList();
    return runs.findByReportCodeInOrderByIdDesc(codes.isEmpty() ? List.of("-") : codes, pageable);
  }

  /**
   * The file of an archived export with its content; only for users allowed to export the report
   * (CSHID.018). Downloads use {@link #download(Long)}.
   *
   * @param id run
   * @return file name, type and content
   */
  public RunFile file(Long id) {
    ReportRun run = downloadableRun(id);
    return new RunFile(run.getFormat(), run.getFileName(), run.getContentType(), content(run));
  }

  /**
   * The file of an archived export for a download endpoint: a presigned link to the stored file, or
   * the bytes of a file kept in the database before ST1; only for users allowed to export the
   * report (CSHID.018).
   *
   * @param id run
   * @return download
   */
  public FileDownload download(Long id) {
    ReportRun run = downloadableRun(id);
    return run.getStoredFileId() == null
        ? FileDownload.inline(run.getFileName(), run.getContentType(), legacyContent(id))
        : FileDownload.stored(run.getStoredFileId());
  }

  /**
   * The content of an archived file for internal use (no permission check: the caller produced it,
   * e.g. the end-of-day reports of disbursement).
   *
   * @param run archived run
   * @return bytes
   */
  public byte[] content(ReportRun run) {
    return run.getStoredFileId() == null
        ? legacyContent(run.getId())
        : storedFiles.read(run.getStoredFileId());
  }

  /**
   * Whether the current user may download the file of a run: the export permission of the report
   * and the availability time (the owner check of the stored files of runs).
   *
   * @param run archived run
   * @return true when allowed
   */
  @Transactional(readOnly = true)
  public boolean mayDownload(ReportRun run) {
    return ReportAccess.mayExport(registry.get(run.getReportCode()).metadata())
        && run.isAvailableAt(clock.instant());
  }

  private ReportRun downloadableRun(Long id) {
    ReportRun run = runs.findById(id).orElseThrow(() -> new ResourceNotFoundException(ENTITY, id));
    ReportMetadata metadata = registry.get(run.getReportCode()).metadata();
    if (!ReportAccess.mayExport(metadata)) {
      throw new AccessDeniedException("Not permitted to download report " + metadata.code());
    }
    if (!run.isAvailableAt(clock.instant())) {
      throw new BusinessRuleException(
          "REPORT_FILE_NOT_AVAILABLE",
          run.getFileName() + " is available from " + run.getAvailableFrom());
    }
    audit.record(
        ENTITY, id, AuditAction.EXPORT, "Downloaded archived " + run.getFileName() + " again");
    return run;
  }

  private byte[] legacyContent(Long id) {
    return files
        .findById(id)
        .map(ReportRunFile::getContent)
        .orElseThrow(() -> new ResourceNotFoundException("Report file", id));
  }

  private void store(ReportRun run, RunFile file, String recordClass) {
    run.storedIn(
        storedFiles
            .storeChecked(
                new StoreRequest(
                    new FileOwner(null, OWNER_TYPE, String.valueOf(run.getId())),
                    run.getReportCode(),
                    recordClass,
                    file.fileName(),
                    file.content(),
                    null),
                file.contentType(),
                FileOrigin.GENERATED)
            .getId());
  }

  private static RunFacts facts(ReportMetadata m, List<String> echo, ReportResult result) {
    return new RunFacts(
        m.code(), m.title(), m.category().name(), String.join("; ", echo), result.rows().size());
  }
}
