-- =====================================================================================
-- iNXT BrokerVerse - V1003 Collections (BRD-4) escalation rules and escalation cases (wave C1-B).
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md
--     BRCLXN.049  configurable escalation rules on aging, commitments and broken promises; the
--                 accounts meeting them are flagged and escalated automatically (CQ14)
--     BRCLXN.050  manual escalation of one or several invoices to the team lead or a designated
--                 authority, with history and notifications
--     BRCLXN.055  broken promises feed the escalation (BROKEN_PROMISES_COUNT)
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 3 (V893 of the design is this
--   V1003), 4.3, 7 (workflow CLX_ESCALATION, seeded in V1000) and 12 (row C1-B).
--   Rules are maker-checker master data (record_status, MASTER_AUTHORIZE). Cases are work cases of
--   the workflow CLX_ESCALATION; status mirrors the stage. Invoices are plain keys.
-- =====================================================================================

-- ---------- Escalation rules (BRCLXN.049) ---------------------------------------------------
-- basis / threshold:
--   AGING_FROM_BOOKING, AGING_FROM_INCEPTION   days since the booking / inception date
--   NO_COMMITMENT_BY_DAY                       days since booking without an open or kept promise
--   BROKEN_PROMISES_COUNT                      number of broken promises on the invoice
--   INSTALLMENT_OVERDUE_DAYS                   days an installment of the invoice is overdue
--   AMOUNT_OVER                                outstanding premium receivable at or above the amount
-- target_level: TL / UH / SECTION_HEAD route the case to the team lead stage (WITH_TL) or to the
-- unit / section head stage (WITH_UH); USER assigns it to target_username. When target_username is
-- empty the case waits in the stage's queue (CLX_ESCALATION_HANDLE).
create table clx_escalation_rule (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    code            varchar(40)    not null,
    name            varchar(200)   not null,
    basis           varchar(30)    not null,
    threshold       numeric(19, 2) not null,
    segment         varchar(40),
    sales_unit      varchar(20),
    product_line    varchar(30),
    amount_from     numeric(19, 2),
    amount_to       numeric(19, 2),
    target_level    varchar(20)    not null,
    target_username varchar(50),
    reason_code     varchar(40)    not null,
    sla_hours       integer        not null,
    notify          boolean        not null default true,
    effective_from  date           not null,
    effective_to    date,
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_clx_escalation_rule unique (company_id, code),
    constraint ck_clx_rule_basis check (basis in ('AGING_FROM_BOOKING', 'AGING_FROM_INCEPTION',
        'NO_COMMITMENT_BY_DAY', 'BROKEN_PROMISES_COUNT', 'INSTALLMENT_OVERDUE_DAYS', 'AMOUNT_OVER')),
    constraint ck_clx_rule_level check (target_level in ('TL', 'UH', 'SECTION_HEAD', 'USER')),
    constraint ck_clx_rule_user check (target_level <> 'USER' or target_username is not null),
    constraint ck_clx_rule_threshold check (threshold > 0),
    constraint ck_clx_rule_sla check (sla_hours > 0),
    constraint ck_clx_rule_amounts check (amount_to is null or amount_from is null or amount_to >= amount_from),
    constraint ck_clx_rule_dates check (effective_to is null or effective_to >= effective_from),
    constraint ck_clx_rule_status check (record_status in ('PENDING_AUTHORIZATION', 'ACTIVE', 'INACTIVE'))
);

-- ---------- Escalation cases (BRCLXN.049/050) ------------------------------------------------
create table clx_escalation (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    escalation_no   varchar(40)    not null unique,
    kind            varchar(10)    not null,
    rule_code       varchar(40),
    arn             varchar(30)    not null,
    client_code     varchar(30)    not null,
    assured_name    varchar(250)   not null,
    target_level    varchar(20)    not null,
    target_username varchar(50),
    reason_code     varchar(40)    not null,
    remarks         varchar(1000),
    total_balance   numeric(19, 2) not null,
    currency        varchar(3)     not null,
    sla_hours       integer        not null,
    status          varchar(20)    not null,
    stage_since     timestamptz    not null,
    dedup_key       varchar(120),
    bulk_ref        varchar(40),
    resolved_at     timestamptz,
    resolution      varchar(1000),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_clx_escalation_kind check (kind in ('AUTO', 'MANUAL')),
    constraint ck_clx_escalation_level check (target_level in ('TL', 'UH', 'SECTION_HEAD', 'USER')),
    constraint ck_clx_escalation_status check (status in ('RAISED', 'WITH_TL', 'WITH_UH', 'IN_ACTION',
        'RETURNED', 'RESOLVED')),
    constraint ck_clx_escalation_rule check (kind = 'MANUAL' or rule_code is not null)
);
create index ix_clx_escalation_company_status on clx_escalation (company_id, status);
create index ix_clx_escalation_target on clx_escalation (target_username, status);
create index ix_clx_escalation_arn on clx_escalation (arn);
-- Idempotency of the automatic escalation: one case per rule, invoice and month.
create unique index uq_clx_escalation_dedup on clx_escalation (dedup_key) where dedup_key is not null;

-- One row per invoice of the escalation (BRCLXN.050 AC 1).
create table clx_escalation_item (
    id            bigint generated by default as identity primary key,
    escalation_id bigint         not null references clx_escalation (id),
    invoice_no    varchar(40)    not null,
    policy_no     varchar(60),
    balance       numeric(19, 2) not null,
    aging_days    integer        not null,
    constraint uq_clx_escalation_item unique (escalation_id, invoice_no)
);
create index ix_clx_escalation_item_invoice on clx_escalation_item (invoice_no);
