-- =====================================================================================
-- iNXT BrokerVerse - V1006 Cashiering adapters of the Collections and ACSL ports (wave C1-C).
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md BRCLXN.030-036, 040 (execution side)
--                 docs/requirements/BDOI_ACCT_BRD_SPEC.md MKT 1.11.0 (refund validation),
--                 ACSL 2.6.0-2.6.1 (payment reversal)
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 9 and 14 (C1-C as built),
--           docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md section 2.2.
--   Cashiering implements UnappliedDirectory, UnappliedDispositionRequests,
--   RefundValidationSource (validator CASHIERING) and PaymentReversalRequester. The requests of the
--   other modules are queued here; the cashiers act on them in the Cashiering screens with the
--   existing disposition workflow (OPS_DISPOSITION) and application engine. Additive only: no
--   existing cashiering table changes. Collections' range (V1006 of V1000-V1009) is used because
--   the adapters are the Collections wave's contract (COLLECTIONS_DESIGN 12, row C1-C).
-- =====================================================================================

-- ---------- Collector disposition requests (BRCLXN.030-033; port UnappliedDispositionRequests) --
-- status: QUEUED = waiting for a cashier; ACCEPTED = a cashiering disposition was assigned from it;
--         REJECTED = refused by a cashier (or its disposition withdrawn); APPLIED = the disposition
--         was executed (applied, refunded, reclassified or transferred).
create table csh_collector_request (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    request_no       varchar(30)    not null unique,
    unapplied_id     bigint         not null references csh_unapplied (id),
    action           varchar(20)    not null,
    invoice_no       varchar(40),
    amount           numeric(19, 2) check (amount > 0),
    requested_by     varchar(50)    not null,
    source           varchar(30)    not null,
    source_ref       varchar(80)    not null,
    remarks          varchar(1000),
    status           varchar(12)    not null,
    disposition_id   bigint         references csh_disposition (id),
    decided_by       varchar(50),
    decided_at       timestamptz,
    decision_note    varchar(1000),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_csh_collector_request_source unique (source, source_ref),
    constraint ck_csh_collector_request_action check (action in ('APPLY_TO_INVOICE', 'REFUND', 'RECLASS', 'TRANSFER')),
    constraint ck_csh_collector_request_status check (status in ('QUEUED', 'ACCEPTED', 'REJECTED', 'APPLIED'))
);
create index ix_csh_collector_request_status on csh_collector_request (company_id, status, id);
create index ix_csh_collector_request_item on csh_collector_request (unapplied_id, id);
create index ix_csh_collector_request_disposition on csh_collector_request (disposition_id);

-- ---------- Refund validations answered by Cashiering (MKT 1.11.0; RefundValidationSource) -------
-- Cashiering confirms that the premium of a cancelled account is back in the unapplied list with a
-- new AR number, or rejects the validation. status: OPEN, CONFIRMED, REJECTED.
create table csh_refund_validation (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    task_no          varchar(30)    not null unique,
    source_module    varchar(30)    not null,
    source_ref       varchar(80)    not null,
    invoice_no       varchar(40),
    ar_no            varchar(40),
    client_code      varchar(30),
    currency         varchar(3)     not null,
    amount           numeric(19, 2) not null,
    requested_by     varchar(50)    not null,
    request_remarks  varchar(1000),
    status           varchar(12)    not null,
    unapplied_id     bigint         references csh_unapplied (id),
    new_ar_no        varchar(40),
    decided_by       varchar(50),
    decided_at       timestamptz,
    result_remarks   varchar(1000),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_csh_refund_validation_source unique (source_module, source_ref),
    constraint ck_csh_refund_validation_status check (status in ('OPEN', 'CONFIRMED', 'REJECTED'))
);
create index ix_csh_refund_validation_status on csh_refund_validation (company_id, status, id);

-- ---------- Payment reversals requested by ACSL (ACSL 2.6.0-2.6.1; PaymentReversalRequester) ----
-- A cashiering approver (CASH_APPROVE, four eyes) reverses the receipt's applications on the
-- invoice with the application engine (Dr PR / Cr unapplied collections) and puts the money back
-- in the unapplied list. status: SUBMITTED, APPROVED, REJECTED.
create table csh_payment_reversal (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    request_no       varchar(30)    not null unique,
    source_module    varchar(30)    not null,
    source_ref       varchar(80)    not null,
    invoice_no       varchar(40)    not null,
    receipt_no       varchar(40)    not null,
    currency         varchar(3),
    amount           numeric(19, 2) check (amount > 0),
    value_date       date           not null,
    reason           varchar(1000),
    requested_by     varchar(50)    not null,
    status           varchar(12)    not null,
    reversed_amount  numeric(19, 2),
    unapplied_id     bigint         references csh_unapplied (id),
    decided_by       varchar(50),
    decided_at       timestamptz,
    decision_note    varchar(1000),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_csh_payment_reversal_source unique (source_module, source_ref),
    constraint ck_csh_payment_reversal_status check (status in ('SUBMITTED', 'APPROVED', 'REJECTED'))
);
create index ix_csh_payment_reversal_status on csh_payment_reversal (company_id, status, id);
