-- =====================================================================================
-- iNXT BrokerVerse - V1002 Collections (BRD-4) promises to pay, installment plans and billing
-- statements (wave C1-B).
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md
--     BRCLXN.053  installment schedule per account, overdue installments flagged (CQ15, Q35)
--     BRCLXN.054  payments allocated to the installments, oldest due first
--     BRCLXN.055  promises to pay per account or installment, kept / partially kept / broken (CQ16)
--     BRCLXN.058  statement of account (SOA) per billing cycle of a multi-year or installment
--                 policy, through the docgen template CLX_SOA (CQ18)
--     BRCLXN.060  billing is monitoring only: an SOA creates no receivable and no CR billing
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 3 (V892 of the design is this
--   V1002), 4.2 and 12 (row C1-B).
--   The worklist item (clx_item, wave C1-A) is referenced by its plain keys (invoice no., ARN,
--   client code), as Operations does; money is read from the invoice ledger (ops_invoice) and
--   never copied except as the allocation snapshot of an installment.
-- =====================================================================================

-- ---------- Installment plans (BRCLXN.053/054/058) --------------------------------------------
-- source: POLICY_YEARS = one installment per billing cycle of each policy-year invoice of a
--         multi-year account (booked or still scheduled in booking);
--         GENERATED = the outstanding premium of one invoice split by the billing frequency;
--         MANUAL = installments entered by the collector for one invoice.
create table clx_installment_plan (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    plan_no           varchar(40)    not null unique,
    arn               varchar(30)    not null,
    invoice_no        varchar(40),
    client_code       varchar(30)    not null,
    assured_name      varchar(250)   not null,
    currency          varchar(3)     not null,
    frequency         varchar(40)    not null,
    source            varchar(20)    not null,
    first_due         date           not null,
    installment_count integer        not null,
    total             numeric(19, 2) not null,
    paid_total        numeric(19, 2) not null default 0,
    status            varchar(20)    not null,
    remarks           varchar(500),
    cancel_reason     varchar(500),
    refreshed_at      timestamptz,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_clx_plan_source check (source in ('POLICY_YEARS', 'GENERATED', 'MANUAL')),
    constraint ck_clx_plan_status check (status in ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    constraint ck_clx_plan_invoice check (source = 'POLICY_YEARS' or invoice_no is not null),
    constraint ck_clx_plan_count check (installment_count > 0),
    constraint ck_clx_plan_total check (total >= 0 and paid_total >= 0)
);
create index ix_clx_plan_company_status on clx_installment_plan (company_id, status);
create index ix_clx_plan_arn on clx_installment_plan (arn);
create index ix_clx_plan_client on clx_installment_plan (company_id, client_code);
-- One live plan per invoice, and one live policy-year plan per account.
create unique index uq_clx_plan_live_invoice on clx_installment_plan (company_id, invoice_no)
    where status = 'ACTIVE' and invoice_no is not null;
create unique index uq_clx_plan_live_arn on clx_installment_plan (company_id, arn)
    where status = 'ACTIVE' and source = 'POLICY_YEARS';

-- One installment = one billing cycle (cycle_from .. cycle_to, the coverage period it bills).
create table clx_installment (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    plan_id       bigint         not null references clx_installment_plan (id),
    seq           integer        not null,
    policy_year   integer        not null default 1,
    invoice_no    varchar(40),
    due_date      date           not null,
    cycle_from    date           not null,
    cycle_to      date           not null,
    amount        numeric(19, 2) not null,
    paid_amount   numeric(19, 2) not null default 0,
    status        varchar(20)    not null,
    overdue_since date,
    paid_on       date,
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_clx_installment unique (plan_id, seq),
    constraint ck_clx_installment_status check (status in ('NOT_DUE', 'DUE', 'OVERDUE', 'PARTIAL', 'PAID')),
    constraint ck_clx_installment_amount check (amount >= 0 and paid_amount >= 0),
    constraint ck_clx_installment_cycle check (cycle_to >= cycle_from)
);
create index ix_clx_installment_due on clx_installment (status, due_date);
create index ix_clx_installment_invoice on clx_installment (invoice_no);

-- ---------- Promises to pay (BRCLXN.055, CQ16) ------------------------------------------------
-- promised_on is the day the client made the promise (the call or visit), promised_date the day
-- the payment is due. The job CLX_PROMISE_CHECK compares the payments applied in the ledger
-- between the two dates (plus CLX_PROMISE_GRACE_DAYS) with the promised amount.
create table clx_promise (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    invoice_no      varchar(40)    not null,
    arn             varchar(30)    not null,
    client_code     varchar(30)    not null,
    assured_name    varchar(250)   not null,
    installment_id  bigint         references clx_installment (id),
    promised_on     date           not null,
    promised_date   date           not null,
    promised_amount numeric(19, 2) not null,
    currency        varchar(3)     not null,
    remarks         varchar(500),
    status          varchar(20)    not null,
    evaluated_at    timestamptz,
    actual_paid     numeric(19, 2),
    actual_date     date,
    closing_note    varchar(500),
    bulk_ref        varchar(40),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_clx_promise_status check (status in ('OPEN', 'KEPT', 'PARTIALLY_KEPT', 'BROKEN', 'CANCELLED')),
    constraint ck_clx_promise_amount check (promised_amount > 0),
    constraint ck_clx_promise_dates check (promised_date >= promised_on)
);
create index ix_clx_promise_status_date on clx_promise (status, promised_date);
create index ix_clx_promise_invoice on clx_promise (invoice_no, status);
create index ix_clx_promise_company on clx_promise (company_id, status);

-- ---------- Billing statements (BRCLXN.058/060, CQ18) ------------------------------------------
create table clx_billing_statement (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    soa_no           varchar(40)    not null unique,
    plan_id          bigint         not null references clx_installment_plan (id),
    cycle_seq        integer        not null,
    arn              varchar(30)    not null,
    client_code      varchar(30)    not null,
    assured_name     varchar(250)   not null,
    currency         varchar(3)     not null,
    frequency        varchar(40)    not null,
    cycle_from       date           not null,
    cycle_to         date           not null,
    due_date         date           not null,
    total            numeric(19, 2) not null,
    paid             numeric(19, 2) not null,
    balance          numeric(19, 2) not null,
    status           varchar(20)    not null,
    template_code    varchar(40),
    template_version integer,
    sent_at          timestamptz,
    sent_to          varchar(500),
    message_id       bigint,
    cancel_reason    varchar(500),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_clx_soa_status check (status in ('GENERATED', 'SENT', 'CANCELLED')),
    constraint ck_clx_soa_cycle check (cycle_to >= cycle_from)
);
create index ix_clx_soa_company on clx_billing_statement (company_id, status);
create index ix_clx_soa_client on clx_billing_statement (company_id, client_code);
create index ix_clx_soa_arn on clx_billing_statement (arn);
-- One live SOA per plan and billing cycle.
create unique index uq_clx_soa_cycle on clx_billing_statement (plan_id, cycle_seq)
    where status <> 'CANCELLED';

create table clx_billing_statement_line (
    id              bigint generated by default as identity primary key,
    statement_id    bigint         not null references clx_billing_statement (id),
    line_no         integer        not null,
    kind            varchar(20)    not null,
    invoice_no      varchar(40),
    policy_year     integer        not null,
    installment_seq integer        not null,
    coverage_from   date           not null,
    coverage_to     date           not null,
    due_date        date           not null,
    amount          numeric(19, 2) not null,
    paid            numeric(19, 2) not null,
    balance         numeric(19, 2) not null,
    constraint uq_clx_soa_line unique (statement_id, line_no),
    constraint ck_clx_soa_line_kind check (kind in ('CURRENT', 'ARREARS'))
);

-- The rendered SOA (PDF), kept apart so that lists never load the file.
create table clx_billing_document (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    statement_id  bigint         not null unique references clx_billing_statement (id),
    file_name     varchar(255)   not null,
    content_type  varchar(100)   not null,
    content       bytea          not null,
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);

-- ---------- SOA document template (BRCLXN.058; layout, recipient and wording to confirm, CQ18) -
insert into doc_template (code, version_no, title, body, effective_from, created_at, created_by)
select 'CLX_SOA', 1, 'Statement of account',
       'This statement shows the premium due for the billing cycle {{cycleFrom}} to {{cycleTo}} of account '
       || '{{arn}} ({{frequency}} billing), and any earlier installment still unpaid. Please settle '
       || '{{currency}} {{balance}} on or before {{dueDate}}. Disregard this statement if payment has been made. '
       || 'This statement is issued for monitoring only and does not create a new receivable.',
       date '2020-01-01', now(), 'SYSTEM'
where not exists (select 1 from doc_template where code = 'CLX_SOA');
