-- =====================================================================================
-- iNXT BrokerVerse - V1007 Legacy invoices in the Collections worklist (Data Migration BRD-13,
-- wave DM2-A; docs/architecture/DATA_MIGRATION_DESIGN.md sections 14.4 J and 14.5; the designed
-- CLX_LEGACY_ITEMS of the Collections design).
--   clx_item.origin, source_system,
--   legacy_ref, migration_batch        BIBS or MIGRATED, copied from the ledger invoice by the
--                                      refresh: the worklist shows a LEGACY badge and an Origin
--                                      filter; legacy_ref is the legacy invoice number
--   clx_legacy_state                   the open collection follow-up carried from legacy (object
--                                      F03): latest disposition, promises to pay, installment
--                                      plan and collector per legacy invoice, shown on the
--                                      account and applied to the item (collector assignment,
--                                      disposition and promise status); rollback per batch
-- =====================================================================================

alter table clx_item add column origin varchar(10) not null default 'BIBS';
alter table clx_item add column source_system varchar(10);
alter table clx_item add column legacy_ref varchar(80);
alter table clx_item add column migration_batch varchar(20);
alter table clx_item add constraint ck_clx_item_origin check (origin in ('BIBS', 'MIGRATED'));
create index ix_clx_item_origin on clx_item (company_id, origin);

create table clx_legacy_state (
    id                  bigint generated by default as identity primary key,
    company_id          bigint         not null references org_company (id),
    invoice_no          varchar(40)    not null,
    legacy_invoice_no   varchar(40)    not null,
    source_system       varchar(10)    not null,
    record_type         varchar(12)    not null,
    seq_no              integer        not null,
    disposition_code    varchar(40),
    disposition_date    date,
    promise_date        date,
    promise_amount      numeric(19, 2),
    installment_no      integer,
    installment_due     date,
    installment_amount  numeric(19, 2),
    collector           varchar(50),
    remarks             varchar(1000),
    migration_batch     varchar(20)    not null,
    rolled_back_at      timestamptz,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    constraint ck_clx_legacy_state_type check (record_type in ('DISPOSITION', 'PROMISE', 'INSTALLMENT',
        'ASSIGNMENT'))
);
create index ix_clx_legacy_state_invoice on clx_legacy_state (company_id, invoice_no);
create index ix_clx_legacy_state_batch on clx_legacy_state (migration_batch);
