-- =====================================================================================
-- iNXT BrokerVerse - V1005 Collections (BRD-4) scheduled files: the daily, weekly and monthly
-- files published by the Collections jobs, each an archived GENERATE run of a registered report
-- with the time from which users may download it.
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md
--     BRCLXN.024/025  monthly "DP PR for reversal", first working day, previous month
--     BRCLXN.026/027  monthly "PR 2307 for reversal", first working day, previous month
--     BRCLXN.028/029  weekly files per unit per branch (Saturday-Friday), Monday 08:00
--     BRCLXN.045      daily Outstanding PR List and Full Production Report after the EOD
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 8 and 11 (the V895 of the design is
--   this V1005). The statement of account template belongs to wave C1-B (billing).
-- =====================================================================================

create table clx_scheduled_file (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    frequency      varchar(10)   not null,
    report_code    varchar(40)   not null,
    period_key     varchar(20)   not null,
    period_from    date          not null,
    period_to      date          not null,
    scope          varchar(80)   not null default '',
    report_run_id  bigint        references report_run (id),
    row_count      integer       not null default 0,
    available_from timestamptz,
    status         varchar(12)   not null,
    message        varchar(500),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_clx_scheduled_file unique (company_id, report_code, period_key, scope),
    constraint ck_clx_scheduled_file_frequency check (frequency in ('DAILY', 'WEEKLY', 'MONTHLY', 'ON_REQUEST')),
    constraint ck_clx_scheduled_file_status check (status in ('PUBLISHED', 'FAILED'))
);

create index ix_clx_scheduled_file_list on clx_scheduled_file (company_id, id desc);
