-- =====================================================================================
-- iNXT BrokerVerse - V1001 Collections (BRD-4) worklist: collection items per ledger invoice
-- with their balance snapshot, assignment and assignment rules, PR collector dispositions,
-- collection efforts, the field-level change log and the in-app outbox / inbox of the
-- CollectionFeed port.
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md
--     BRCLXN.001-012, 046  worklist per invoice, threshold, exclusions, filters, net PR breakdown
--     BRCLXN.013-015       daily refresh from the invoice ledger (CLX_DAILY_REFRESH)
--     BRCLXN.016-023       collector dispositions (append-only), user tracking, history kept
--     BRCLXN.043           audit log of field changes with from / to, user and source IP
--     BRCLXN.052           reassignment (temporary / permanent) and default assignment rules
--     NFR (UI/UX)          record lock "<user> is editing" (editing_by / editing_since)
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 2.2, 4.1 (the V891 of the design is
--   this V1001) and 14. Invoice numbers, ARN, client codes and user names are plain values, as in
--   Operations: foreign keys go to platform tables only.
-- =====================================================================================

-- ---------- Collection items (BRCLXN.001-015, 022) -------------------------------------------
create table clx_item (
    id                     bigint generated by default as identity primary key,
    version                bigint         not null default 0,
    company_id             bigint         not null references org_company (id),
    invoice_no             varchar(40)    not null,
    arn                    varchar(30)    not null,
    root_invoice_no        varchar(40),
    invoice_kind           varchar(20)    not null,
    policy_no              varchar(60),
    policy_year            integer        not null default 1,
    client_code            varchar(30)    not null,
    assured_name           varchar(250)   not null,
    insurer_code           varchar(30)    not null,
    branch_id              bigint         references org_branch (id),
    segment                varchar(40),
    sales_unit             varchar(20),
    unit_head_username     varchar(50),
    ao_username            varchar(50),
    product_line           varchar(30),
    currency               varchar(3)     not null,
    booking_date           date           not null,
    inception_date         date           not null,
    expiry_date            date           not null,
    dp_flag                boolean        not null default false,
    cwt_flag               boolean        not null default false,
    invoice_category       varchar(12)    not null,
    gross_premium          numeric(19, 2) not null,
    net_outstanding        numeric(19, 2) not null,
    outstanding_pr2307     numeric(19, 2) not null,
    aging_days             integer        not null,
    aging_bracket          varchar(20),
    payment_status         varchar(20)    not null,
    status                 varchar(20)    not null,
    listed_on              date           not null,
    completed_on           date,
    last_refreshed_at      timestamptz    not null,
    current_handler        varchar(50),
    current_disposition_id bigint,
    disposition_code       varchar(40),
    category               varchar(1),
    tagging_owner          varchar(12),
    last_effort_at         timestamptz,
    last_effort_code       varchar(40),
    remarks                varchar(1000),
    promise_status         varchar(20),
    escalation_level       varchar(20),
    installment_overdue    boolean        not null default false,
    editing_by             varchar(50),
    editing_since          timestamptz,
    created_at             timestamptz    not null,
    created_by             varchar(50)    not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_clx_item_invoice unique (company_id, invoice_no),
    constraint ck_clx_item_status check (status in ('OPEN', 'COMPLETED', 'EXCLUDED_CANCELLED', 'CREDIT')),
    constraint ck_clx_item_category check (category is null or category in ('A', 'B', 'C')),
    constraint ck_clx_item_owner check (tagging_owner is null or tagging_owner in ('MARKETING', 'OPERATIONS')),
    constraint ck_clx_item_invoice_category check (invoice_category in ('REGULAR', 'DIRECT_BILL'))
);

create index ix_clx_item_scope on clx_item (company_id, status, segment, sales_unit);
create index ix_clx_item_handler on clx_item (company_id, current_handler, status);
create index ix_clx_item_client on clx_item (company_id, client_code);
create index ix_clx_item_arn on clx_item (arn);
create index ix_clx_item_aging on clx_item (aging_days);

-- Snapshot of the net PR breakdown per component at the last refresh (BRCLXN.046); the account
-- page reads the live figures from the ledger.
create table clx_item_balance (
    item_id      bigint         not null references clx_item (id),
    component    varchar(20)    not null,
    booked       numeric(19, 2) not null,
    adjusted     numeric(19, 2) not null,
    applied      numeric(19, 2) not null,
    written_off  numeric(19, 2) not null,
    outstanding  numeric(19, 2) not null,
    primary key (item_id, component)
);

-- ---------- Assignment (BRCLXN.052) -----------------------------------------------------------
create table clx_assignment (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    item_id          bigint        not null references clx_item (id),
    handler_username varchar(50)   not null,
    previous_handler varchar(50),
    kind             varchar(12)   not null,
    valid_from       date          not null,
    valid_to         date,
    reason           varchar(500)  not null,
    assigned_by      varchar(50)   not null,
    reverted_at      timestamptz,
    bulk_ref         varchar(40),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_clx_assignment_kind check (kind in ('PERMANENT', 'TEMPORARY', 'RULE', 'REVERT')),
    constraint ck_clx_assignment_temporary check (kind <> 'TEMPORARY' or valid_to is not null)
);

create index ix_clx_assignment_item on clx_assignment (item_id, id);
create index ix_clx_assignment_revert on clx_assignment (company_id, kind, valid_to) where reverted_at is null;

create table clx_assignment_rule (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    priority         integer        not null,
    name             varchar(120)   not null,
    segment          varchar(40),
    sales_unit       varchar(20),
    client_code      varchar(30),
    amount_from      numeric(19, 2),
    amount_to        numeric(19, 2),
    aging_from       integer,
    aging_to         integer,
    handler_username varchar(50)    not null,
    active           boolean        not null default true,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_clx_rule_amount check (amount_from is null or amount_to is null or amount_from <= amount_to),
    constraint ck_clx_rule_aging check (aging_from is null or aging_to is null or aging_from <= aging_to)
);

create index ix_clx_assignment_rule on clx_assignment_rule (company_id, active, priority);

-- ---------- PR collector dispositions (append-only) and efforts (BRCLXN.016-023) ------------
create table clx_disposition (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    item_id          bigint        not null references clx_item (id),
    disposition_code varchar(40)   not null,
    category         varchar(1),
    tagging_owner    varchar(12),
    ops_action       varchar(20)   not null,
    remarks          varchar(1000),
    effective_on     date          not null,
    payload          varchar(4000),
    source           varchar(12)   not null,
    outbox_id        bigint,
    superseded_by    bigint,
    bulk_ref         varchar(40),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_clx_disposition_action check (ops_action in ('NONE', 'CWT2307_REVERSAL', 'DP_REVERSAL',
        'CHECK_PICKUP', 'CANCEL_REQUEST')),
    constraint ck_clx_disposition_source check (source in ('USER', 'BULK', 'INBOX'))
);

create index ix_clx_disposition_item on clx_disposition (item_id, id);
create index ix_clx_disposition_tagged on clx_disposition (company_id, ops_action, created_at);

create table clx_effort (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    item_id        bigint        not null references clx_item (id),
    effort_code    varchar(40)   not null,
    effort_at      timestamptz   not null,
    channel        varchar(30),
    contact_person varchar(120),
    remarks        varchar(1000),
    bulk_ref       varchar(40),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);

create index ix_clx_effort_item on clx_effort (item_id, effort_at);

-- ---------- Field-level change log (BRCLXN.043, NFR audit) -----------------------------------
create table clx_field_change (
    id          bigint generated by default as identity primary key,
    company_id  bigint        not null references org_company (id),
    entity      varchar(40)   not null,
    entity_id   varchar(60)   not null,
    item_id     bigint        references clx_item (id),
    field       varchar(60)   not null,
    old_value   varchar(1000),
    new_value   varchar(1000),
    username    varchar(50)   not null,
    changed_at  timestamptz   not null,
    source_ip   varchar(45),
    bulk_ref    varchar(40)
);

create index ix_clx_field_change_item on clx_field_change (item_id, id);
create index ix_clx_field_change_time on clx_field_change (company_id, changed_at);

-- ---------- In-app CollectionFeed: outbox to Operations, inbox from Operations (design 2.2) --
create table clx_outbox (
    id                    bigint generated by default as identity primary key,
    version               bigint        not null default 0,
    company_id            bigint        not null references org_company (id),
    feed_code             varchar(40)   not null,
    idempotency_key       varchar(120)  not null,
    invoice_no            varchar(40)   not null,
    fields                varchar(4000) not null,
    status                varchar(12)   not null,
    taken_at              timestamptz,
    source_disposition_id bigint        references clx_disposition (id),
    created_at            timestamptz   not null,
    created_by            varchar(50)   not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_clx_outbox_key unique (feed_code, idempotency_key),
    constraint ck_clx_outbox_status check (status in ('PENDING', 'TAKEN', 'CANCELLED'))
);

create index ix_clx_outbox_pending on clx_outbox (company_id, feed_code, status);

create table clx_inbox (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    feed_code       varchar(40)   not null,
    idempotency_key varchar(120)  not null,
    invoice_no      varchar(40),
    fields          varchar(4000) not null,
    received_at     timestamptz   not null,
    run_no          varchar(40),
    item_id         bigint        references clx_item (id),
    processed_at    timestamptz,
    message         varchar(500),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_clx_inbox_key unique (feed_code, idempotency_key)
);

create index ix_clx_inbox_feed on clx_inbox (company_id, feed_code, received_at);
