-- =====================================================================================
-- iNXT BrokerVerse - V1004 Collections (BRD-4) unapplied payments, collector side (wave C1-C).
--   Requirements: docs/requirements/BDOI_CLXN_BRD_SPEC.md
--     BRCLXN.030/032  request application of an unapplied payment (Collection Handler, Unapplied
--                     Payment Handler) through the port UnappliedDispositionRequests
--     BRCLXN.031/033  document the collector disposition (append-only, with history)
--     BRCLXN.034-036  list of unapplied payments as of today (read from Cashiering through
--                     UnappliedDirectory; never copied)
--     BRCLXN.037-039  LOV CLX_UPP_DISPOSITION (V1000) with attributes requires_invoice and
--                     cashiering_action (clx_lov_attribute)
--     BRCLXN.040      history kept after the payment is applied or refunded
--     BRCLXN.041/042  daily "For Application To Invoice" text file (job CLX_APPLICATION_FILE)
--     BRCLXN.047/048  invoice number mandatory for "for application to invoice", validated by
--                     CLX_INVOICE_NO_PATTERN and the invoice ledger
--   Design: docs/architecture/COLLECTIONS_DESIGN.md sections 3 (V894 of the design is this V1004),
--   4.4 and 12 (row C1-C).
--   Cashiering's unapplied items are referenced by their plain reference (UNP-...), as the design
--   rules for Operations keys; the request table also keeps the p.60 payment fields of the file as
--   a snapshot taken at request time.
-- =====================================================================================

-- ---------- Requests sent to Cashiering (BRCLXN.030/032, 041) --------------------------------
-- status: SENT (queued in Cashiering), DEFERRED (no Cashiering adapter: hand-off), ACCEPTED,
--         REJECTED, APPLIED (executed; UnappliedDispositionChanged).
create table clx_application_request (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    unapplied_ref     varchar(30)    not null,
    action            varchar(20)    not null,
    invoice_no        varchar(40),
    amount            numeric(19, 2) check (amount > 0),
    requested_by      varchar(50)    not null,
    requested_at      timestamptz    not null,
    source_ref        varchar(80)    not null unique,
    status            varchar(12)    not null,
    cashiering_ref    varchar(40),
    status_message    varchar(1000),
    status_at         timestamptz,
    payment_date      date,
    payment_file_name varchar(120),
    transaction_no    varchar(40),
    paid_amount       numeric(19, 2),
    currency          varchar(3),
    payment_type      varchar(20),
    payor_name        varchar(250),
    reference_no      varchar(80),
    assured_name      varchar(250),
    file_run_no       varchar(80),
    filed_at          timestamptz,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_clx_application_request_action check (action in ('APPLY_TO_INVOICE', 'REFUND', 'RECLASS',
        'TRANSFER')),
    constraint ck_clx_application_request_status check (status in ('SENT', 'DEFERRED', 'ACCEPTED', 'REJECTED',
        'APPLIED'))
);
create index ix_clx_application_request_ref on clx_application_request (company_id, unapplied_ref, id);
create index ix_clx_application_request_status on clx_application_request (company_id, status, id);
create index ix_clx_application_request_file on clx_application_request (company_id, action, file_run_no,
    requested_at);

-- ---------- Collector dispositions (BRCLXN.031/033, 040; append-only) -------------------------
create table clx_unapplied_disposition (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    unapplied_ref     varchar(30)    not null,
    disposition_code  varchar(40)    not null,
    cashiering_action varchar(20)    not null,
    invoice_no        varchar(40),
    amount            numeric(19, 2) check (amount > 0),
    remarks           varchar(1000),
    request_id        bigint         references clx_application_request (id),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_clx_unapplied_disposition_action check (cashiering_action in ('APPLY_TO_INVOICE', 'REFUND',
        'RECLASS', 'TRANSFER', 'NONE'))
);
create index ix_clx_unapplied_disposition_ref on clx_unapplied_disposition (company_id, unapplied_ref, id);
create index ix_clx_unapplied_disposition_code on clx_unapplied_disposition (company_id, disposition_code);
