-- =====================================================================================
-- iNXT BrokerVerse - V1016 Renewal (BRD-6) letters and acceptance: the Renewal Advices and other
-- renewal letters, letter batches, client acceptances and the maker-checker corrections of the
-- Renewal Advices already sent before go-live.
--   BRRN.001/009/010/025/037   RA (first and second notice), NAL, NFR, NRNS reminder and
--                              non-acceptance letters, generated from versioned templates, stored as
--                              documents and sent protected
--   BRRN.038/040               acceptance by e-mail, signed RA or payment, with the evidence
--   DMQ37, DMQ38               RAs already sent by hand before go-live are recorded (source
--                              LEGACY_MANUAL) and never sent again; rejected tracker rows are applied
--                              after a second member of the Renewal processing team approves them
--   Design: docs/architecture/RENEWAL_DESIGN.md sections 4.5 and 13.1.
-- =====================================================================================

create table rnw_letter_batch (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    batch_no        varchar(30)  not null,
    action          varchar(20)  not null,
    letter_type     varchar(20)  not null,
    notice          varchar(10),
    selected_count  integer      not null default 0,
    done_count      integer      not null default 0,
    failed_count    integer      not null default 0,
    status          varchar(20)  not null,
    message         varchar(2000),
    started_at      timestamptz  not null,
    ended_at        timestamptz,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_letter_batch unique (company_id, batch_no),
    constraint ck_rnw_letter_batch_action check (action in ('GENERATE', 'SEND')),
    constraint ck_rnw_letter_batch_status check (status in ('RUNNING', 'COMPLETED', 'FAILED'))
);

create table rnw_letter (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    letter_no       varchar(30)  not null,
    candidate_id    bigint       not null references rnw_candidate (id),
    letter_type     varchar(20)  not null,
    notice          varchar(10),
    template_code   varchar(40),
    template_version integer,
    attachment_id   bigint,
    source          varchar(20)  not null,
    status          varchar(20)  not null,
    message_id      bigint,
    recipients      varchar(500),
    protected       boolean      not null default false,
    batch_id        bigint,
    generated_at    timestamptz  not null,
    sent_at         timestamptz,
    failure         varchar(500),
    min_notice_confirmed_by varchar(50),
    legacy_ref      varchar(60),
    legacy_date     date,
    channel         varchar(20),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_letter unique (company_id, letter_no),
    constraint ck_rnw_letter_type check (letter_type in ('RA', 'NAL', 'NFR', 'NRNS_REMINDER', 'NON_ACCEPTANCE')),
    constraint ck_rnw_letter_notice check (notice is null or notice in ('FIRST', 'SECOND')),
    constraint ck_rnw_letter_source check (source in ('SYSTEM', 'USER', 'LEGACY_MANUAL')),
    constraint ck_rnw_letter_status check (status in ('GENERATED', 'QUEUED', 'SENT', 'FAILED', 'CANCELLED'))
);
create index ix_rnw_letter_candidate on rnw_letter (candidate_id, letter_type);
create index ix_rnw_letter_status on rnw_letter (company_id, letter_type, status);
create unique index uq_rnw_letter_reminder on rnw_letter (candidate_id, letter_type)
    where letter_type in ('NRNS_REMINDER', 'NON_ACCEPTANCE') and status <> 'CANCELLED';

create table rnw_acceptance (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    method          varchar(20)  not null,
    attachment_id   bigint,
    evidence_ref    varchar(120),
    accepted_on     date         not null,
    source          varchar(20)  not null,
    financial_impact_ack boolean not null default false,
    remarks         varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_acceptance_method check (method in ('EMAIL', 'SIGNED_RA', 'PAYMENT')),
    constraint ck_rnw_acceptance_source check (source in ('USER', 'SYSTEM', 'UPLOAD'))
);
create index ix_rnw_acceptance_candidate on rnw_acceptance (candidate_id);

create table rnw_ra_sent_request (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    legacy_ref      varchar(60)  not null,
    ra_date         date         not null,
    ra_ref          varchar(60),
    channel         varchar(20),
    recipient       varchar(200),
    job_no          varchar(40),
    row_no          integer,
    correction      varchar(200) not null,
    status          varchar(20)  not null,
    candidate_id    bigint       references rnw_candidate (id),
    decided_by      varchar(50),
    decided_at      timestamptz,
    decision_remarks varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_ra_sent_request_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);
create index ix_rnw_ra_sent_request_status on rnw_ra_sent_request (company_id, status);
