-- =====================================================================================
-- iNXT BrokerVerse - V1017 Renewal wave R3: hand-off of submitted policies (RENEWAL_DESIGN sections
--   2.3, 13 and 17; SUBMITTED_POLICIES_DESIGN section 3.5).
--   * rnw_submitted_handoff: the terms a submitted policy was handed over with (one per candidate,
--     keyed by the masterlist number): RA template, insurer assigned by the insurer rules,
--     handler, Account Officer, mailing address for printed letters and whether it was renewed
--     by hand (Renew with BDOI).
--   * Templates RNW_RA_FFY (Renewal Advice of a Free First Year policy) and RNW_SFU (follow-up
--     of a mortgaged account), drafts until BDOI supplies the layouts.
-- =====================================================================================

create table rnw_submitted_handoff (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    candidate_id      bigint        not null unique references rnw_candidate (id),
    sbm_no            varchar(30)   not null,
    ra_template       varchar(20)   not null check (ra_template in ('GENERIC', 'FFY')),
    assigned_insurer  varchar(30),
    handler_username  varchar(50),
    ao_username       varchar(50),
    mailing_address   varchar(500),
    manual            boolean       not null default false,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_rnw_submitted_handoff unique (company_id, sbm_no)
);

insert into doc_template (code, version_no, title, body, effective_from, created_at, created_by)
values
('RNW_RA_FFY', 1, 'Renewal Advice (first year free) - {{assuredName}} - policy {{policyNo}}',
 'Dear {{clientName}},

The first year of your policy {{policyNo}} with {{insurerName}} was free of charge and ends on {{expiryDate}}. To keep your cover, we offer its renewal for the period {{renewalFrom}} to {{renewalTo}}:

Sum insured: {{currency}} {{sumInsured}}
Renewal premium: {{currency}} {{grossPremium}}

To renew, please sign and return this Renewal Advice, or pay the renewal premium on or before {{expiryDate}}.

Renewal reference: {{renewalRef}}
Account officer: {{aoName}}

Thank you for your trust,
BDO Insurance and Reinsurance Brokers, Inc.', date '2020-01-01', now(), 'SYSTEM'),
('RNW_SFU', 1, 'Follow-up on the renewal of your mortgaged property - policy {{policyNo}}',
 'Dear {{clientName}},

Your property is mortgaged to the bank and must stay insured. Your policy {{policyNo}} expires on {{expiryDate}} and we have not received your answer to our Renewal Advice.

Please sign and return the Renewal Advice, or pay the renewal premium, on or before {{expiryDate}}.

Renewal reference: {{renewalRef}}
Account officer: {{aoName}}

Thank you,
BDO Insurance and Reinsurance Brokers, Inc.', date '2020-01-01', now(), 'SYSTEM')
on conflict do nothing;
