-- =====================================================================================
-- iNXT BrokerVerse - V1019 Renewal: the sanitation criteria of the Walkthrough addendum
-- (Annex BRRN.020 SC-01 to SC-13, R23-02, R24-02; FR-RN-020, 022, 112).
--   rnw_insurer_renewable_risk  the risk codes each insurer renews (insurer renewable list,
--                               SC-10), effective-dated, maker-checker
--   rnw_check_setting           three more checks: TSI_THRESHOLD (total sum insured above the
--                               threshold, default PHP 250,000,000, goes to TSU or proposal
--                               handling), RISK_CODE_DEFINED (risk code not in the product
--                               catalogue: manual review), INSURER_RENEWABLE_LIST (risk not on the
--                               insurer's renewable list), all Review
--   RNW_EXCEPTION_AGEING_DAYS   5 working days (R29-05), where the delivered 7 days is unchanged
-- =====================================================================================
create table rnw_insurer_renewable_risk (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    insurer_code   varchar(30)  not null,
    risk_code      varchar(20)  not null,
    remarks        varchar(200),
    effective_from date         not null,
    effective_to   date,
    record_status  varchar(30)  not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_rnw_insurer_renewable_dates
        check (effective_to is null or effective_to >= effective_from)
);
create index ix_rnw_insurer_renewable on rnw_insurer_renewable_risk (company_id, insurer_code);

insert into rnw_check_setting (check_code, active, severity, parameters, record_status, authorized_by,
    authorized_at, created_at, created_by)
values ('TSI_THRESHOLD', true, 'FAIL_REVIEW', '250000000', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('RISK_CODE_DEFINED', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('INSURER_RENEWABLE_LIST', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(),
        'SYSTEM');

update sys_parameter
set param_value = '5',
    description = 'Working days a renewal may stay in the Exception bucket before its stage owner is alerted'
where param_key = 'RNW_EXCEPTION_AGEING_DAYS' and param_value = '7';
