-- =====================================================================================
-- iNXT BrokerVerse - V1013 Renewal (BRD-6) rules: non-renewable risk codes, check settings,
-- versioned bucket rule sets and decision matrices, the package code map of migrated policies and
-- the package choices of the Renewal processing team.
--   BRRN.009       non-renewable risk codes (maker-checker, end-dated, never deleted)
--   BRRN.020/023   check settings and bucket rules; a failed check never gives CLEAN (database check
--                  here and a service guard)
--   BRRN.031/034   decision matrix: priority, criteria, disposition, AUTO / MANUAL
--   DMQ36          package remapping at sanitation: the PACKAGE code map loaded by the migration and
--                  maintained in Renewal; choices of the processing team with maker and checker
--   Design: docs/architecture/RENEWAL_DESIGN.md sections 4.2, 8 and 13.1. The rule sets and the
--   matrix ship without content (RQ01, RQ24); seed content is in V1910. The check settings carry the
--   default severities of the design.
-- =====================================================================================

create table rnw_non_renewable_risk_code (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    risk_code       varchar(20)  not null,
    line_code       varchar(30),
    reason          varchar(200) not null,
    effective_from  date         not null,
    effective_to    date,
    record_status   varchar(30)  not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_nrr_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_rnw_nrr_code on rnw_non_renewable_risk_code (company_id, risk_code);

create table rnw_check_setting (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    check_code      varchar(40)  not null,
    active          boolean      not null default true,
    severity        varchar(20)  not null,
    parameters      varchar(1000),
    record_status   varchar(30)  not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_check_setting unique (check_code),
    constraint ck_rnw_check_setting_severity check (severity in ('FAIL_EXCEPTION', 'FAIL_REVIEW', 'WARN', 'INFO', 'SYSTEM'))
);

insert into rnw_check_setting (check_code, active, severity, parameters, record_status, authorized_by,
    authorized_at, created_at, created_by)
values ('REFERENCE_MATCH', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('PN_PRESENT', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('RISK_CODE_RENEWABLE', true, 'SYSTEM', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('LAMD_STATUS', true, 'SYSTEM', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('CLAIMS', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('ENDORSEMENT_PENDING', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('OUTSTANDING_PREMIUM', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('FINANCIAL_IMPACT', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('INSURER_RESPONSE_MATCH', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('MANDATORY_FIELDS', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('PRODUCT_RENEWABLE', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('INSURER_USABLE', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('DUPLICATE_CANDIDATE', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('KYC_DUE', true, 'INFO', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('PACKAGE_REMAP', true, 'FAIL_EXCEPTION', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM');

create table rnw_bucket_rule_set (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    version_no      integer      not null,
    status          varchar(20)  not null,
    effective_from  date         not null,
    description     varchar(200),
    submitted_by    varchar(50),
    submitted_at    timestamptz,
    approved_by     varchar(50),
    approved_at     timestamptz,
    decision_remarks varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_bucket_rule_set unique (company_id, version_no),
    constraint ck_rnw_bucket_rule_set_status check (status in ('DRAFT', 'SUBMITTED', 'ACTIVE', 'RETIRED', 'REJECTED'))
);
create unique index uq_rnw_bucket_rule_set_active on rnw_bucket_rule_set (company_id) where status = 'ACTIVE';

create table rnw_bucket_rule (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    rule_set_id     bigint       not null references rnw_bucket_rule_set (id),
    priority        integer      not null,
    check_code      varchar(40),
    severity        varchar(20),
    outcome         varchar(20)  not null,
    result_bucket   varchar(20)  not null,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_bucket_rule unique (rule_set_id, priority),
    constraint ck_rnw_bucket_rule_outcome check (outcome in ('FAIL', 'WARN')),
    constraint ck_rnw_bucket_rule_bucket check (result_bucket in ('CLEAN', 'REVIEW', 'EXCEPTION')),
    -- A failed check never gives CLEAN (BRRN.023 negative scenario).
    constraint ck_rnw_bucket_rule_no_clean_fail check (not (outcome = 'FAIL' and result_bucket = 'CLEAN'))
);

create table rnw_decision_matrix (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    version_no      integer      not null,
    status          varchar(20)  not null,
    effective_from  date         not null,
    description     varchar(200),
    submitted_by    varchar(50),
    submitted_at    timestamptz,
    approved_by     varchar(50),
    approved_at     timestamptz,
    decision_remarks varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_decision_matrix unique (company_id, version_no),
    constraint ck_rnw_decision_matrix_status check (status in ('DRAFT', 'SUBMITTED', 'ACTIVE', 'RETIRED', 'REJECTED'))
);
create unique index uq_rnw_decision_matrix_active on rnw_decision_matrix (company_id) where status = 'ACTIVE';

create table rnw_decision_rule (
    id                    bigint generated by default as identity primary key,
    version               bigint       not null default 0,
    matrix_id             bigint       not null references rnw_decision_matrix (id),
    priority              integer      not null,
    segment               varchar(40),
    line_code             varchar(30),
    product_code          varchar(20),
    mortgaged             boolean,
    bucket                varchar(20),
    claims_condition      varchar(20),
    endorsement_condition varchar(20),
    payment_condition     varchar(20),
    days_from             integer,
    days_to               integer,
    outcome_disposition   varchar(20)  not null,
    automation            varchar(10)  not null,
    letter_hint           varchar(10),
    created_at            timestamptz  not null,
    created_by            varchar(50)  not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_rnw_decision_rule unique (matrix_id, priority),
    constraint ck_rnw_decision_rule_bucket check (bucket is null or bucket in ('CLEAN', 'REVIEW')),
    constraint ck_rnw_decision_rule_claims check (claims_condition is null or claims_condition in ('NONE', 'OPEN', 'PAID', 'TOTAL_LOSS')),
    constraint ck_rnw_decision_rule_endorsement check (endorsement_condition is null or endorsement_condition in ('NONE', 'POSTED_IN_TERM', 'PENDING')),
    constraint ck_rnw_decision_rule_payment check (payment_condition is null or payment_condition in ('PAID', 'OUTSTANDING', 'DP')),
    constraint ck_rnw_decision_rule_days check (days_from is null or days_to is null or days_from <= days_to),
    constraint ck_rnw_decision_rule_outcome check (outcome_disposition in ('FOR_RENEWAL', 'NOT_FOR_RENEWAL',
        'FOR_QUOTATION', 'FOR_PROPOSAL', 'LOST_BUSINESS')),
    constraint ck_rnw_decision_rule_automation check (automation in ('AUTO', 'MANUAL')),
    constraint ck_rnw_decision_rule_letter check (letter_hint is null or letter_hint in ('RA', 'NFR', 'NAL'))
);

create table rnw_package_map (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    legacy_package_code    varchar(40)   not null,
    legacy_package_version varchar(20),
    risk_code              varchar(20),
    insurer_code           varchar(30),
    si_from                numeric(19, 2),
    si_to                  numeric(19, 2),
    action                 varchar(10)   not null,
    product_code           varchar(20),
    product_version_no     integer,
    map_version            integer       not null default 1,
    source                 varchar(20)   not null,
    remarks                varchar(200),
    record_status          varchar(30)   not null,
    authorized_by          varchar(50),
    authorized_at          timestamptz,
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint ck_rnw_package_map_action check (action in ('MAP', 'REJECT')),
    constraint ck_rnw_package_map_target check (action = 'REJECT' or (product_code is not null and product_version_no is not null)),
    constraint ck_rnw_package_map_source check (source in ('MIGRATION', 'SETUP', 'CHOICE')),
    constraint ck_rnw_package_map_band check (si_from is null or si_to is null or si_from <= si_to)
);
create index ix_rnw_package_map_code on rnw_package_map (company_id, legacy_package_code);

create table rnw_package_choice (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    candidate_id           bigint        not null references rnw_candidate (id),
    legacy_package_code    varchar(40),
    legacy_package_version varchar(20),
    product_code           varchar(20)   not null,
    product_version_no     integer       not null,
    reason                 varchar(200)  not null,
    status                 varchar(20)   not null,
    decided_by             varchar(50),
    decided_at             timestamptz,
    decision_remarks       varchar(200),
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint ck_rnw_package_choice_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);
create index ix_rnw_package_choice_candidate on rnw_package_choice (candidate_id, status);
