-- =====================================================================================
-- iNXT BrokerVerse - V1012 Renewal (BRD-6) candidates: extraction runs, renewal candidates with
-- their listing snapshot, lifecycle and flags, check runs and results, bucket history, remarks,
-- Contact Center follow-ups, controlled overrides, history views and assignments.
--   BRRN.005/022   one candidate per expiring root invoice and policy year, with a renewal reference
--   BRRN.020/023   check runs, results and bucket changes with rule version and cause
--   BRRN.021       extraction and initiation are separate events
--   BRRN.026/027   follow-ups; the account history is viewed before the disposition
--   BRD 1.011      overrides with mandatory remarks
--   DMQ37          candidates of migrated policies (source LEGACY), urgent flag of the go-live window
--   Design: docs/architecture/RENEWAL_DESIGN.md sections 4.1 and 13.1. ARN and invoice numbers are
--   plain values, as in Operations. Money is numeric(19,2).
-- =====================================================================================

create table rnw_extraction_run (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    run_no          varchar(30)  not null,
    trigger_kind    varchar(20)  not null,
    expiry_from     date,
    expiry_to       date,
    requested_by    varchar(50)  not null,
    read_count      integer      not null default 0,
    new_count       integer      not null default 0,
    existing_count  integer      not null default 0,
    skipped_count   integer      not null default 0,
    urgent_count    integer      not null default 0,
    started_at      timestamptz  not null,
    ended_at        timestamptz,
    status          varchar(20)  not null,
    message         varchar(1000),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_extraction_run unique (company_id, run_no),
    constraint ck_rnw_extraction_trigger check (trigger_kind in ('SCHEDULED', 'MANUAL_RANGE', 'UPLOAD', 'LEGACY', 'GOLIVE')),
    constraint ck_rnw_extraction_status check (status in ('RUNNING', 'COMPLETED', 'FAILED')),
    constraint ck_rnw_extraction_range check (expiry_to is null or expiry_from is null or expiry_to >= expiry_from)
);
create index ix_rnw_extraction_run_company on rnw_extraction_run (company_id, started_at);

create table rnw_candidate (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    renewal_ref            varchar(30)   not null,
    source                 varchar(20)   not null,
    source_ref             varchar(60),
    extraction_run_id      bigint        references rnw_extraction_run (id),
    expiring_invoice_no    varchar(40),
    expiring_arn           varchar(40),
    expiring_policy_no     varchar(60),
    policy_year            integer,
    cover_no               varchar(40),
    version_no             integer,
    pn_nos                 varchar(500),
    -- listing snapshot (refreshed at each evaluation)
    client_id              bigint,
    client_code            varchar(30),
    client_name            varchar(250)  not null,
    assured_name           varchar(250),
    client_email           varchar(120),
    product_code           varchar(20),
    product_name           varchar(200),
    line_code              varchar(30),
    segment                varchar(40),
    business_origin        varchar(40),
    account_type           varchar(40),
    branch_code            varchar(20),
    region_code            varchar(20),
    department_code        varchar(20),
    sales_unit             varchar(20),
    unit_head              varchar(50),
    account_officer        varchar(50),
    insurer_code           varchar(30),
    mortgaged              boolean       not null default false,
    mortgagee_bank         varchar(120),
    packaged               boolean       not null default false,
    inception_date         date,
    expiry_date            date          not null,
    basic_premium          numeric(19, 2),
    gross_premium          numeric(19, 2),
    total_sum_insured      numeric(19, 2),
    premium_rate           numeric(19, 8),
    commission_rate        numeric(19, 8),
    currency               varchar(3),
    legacy_package_code    varchar(40),
    legacy_package_version varchar(20),
    -- lifecycle
    stage                  varchar(30)   not null,
    bucket                 varchar(20),
    bucket_rule_version    integer,
    evaluated_at           timestamptz,
    last_check_run_id      bigint,
    disposition            varchar(20),
    nonrenewal_reason      varchar(40),
    disposition_source     varchar(20),
    disposition_remarks    varchar(200),
    new_invoice_no         varchar(40),
    proposed_disposition   varchar(20),
    proposed_automation    varchar(10),
    proposed_matrix_version integer,
    proposed_rule_id       bigint,
    initiated_by           varchar(50),
    initiated_at           timestamptz,
    assigned_ao            varchar(50),
    assigned_po            varchar(50),
    owner_unit             varchar(20),
    marketing_locked_at    timestamptz,
    history_viewed         boolean       not null default false,
    -- flags
    stp                    boolean       not null default false,
    nrns                   boolean       not null default false,
    kyc_due                boolean       not null default false,
    kyc_flagged_at         timestamptz,
    claims_flag            boolean       not null default false,
    endorsement_pending    boolean       not null default false,
    outstanding_flag       boolean       not null default false,
    transferred            boolean       not null default false,
    returned               boolean       not null default false,
    urgent                 boolean       not null default false,
    nfr_sent               boolean       not null default false,
    ra_notice              varchar(10)   not null default 'NONE',
    path                   varchar(10)   not null default 'STANDARD',
    resolved_product_code  varchar(20),
    resolved_version_no    integer,
    -- links and closure
    renewal_arn            varchar(40),
    quotation_ref          varchar(30),
    proposal_ref           varchar(30),
    renewed_invoice_no     varchar(40),
    closed_as              varchar(30),
    closed_at              timestamptz,
    search_text            varchar(2000),
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_rnw_candidate_ref unique (company_id, renewal_ref),
    constraint ck_rnw_candidate_source check (source in ('BIBS_INVOICE', 'SUBMITTED_POLICY', 'LEGACY')),
    constraint ck_rnw_candidate_stage check (stage in ('EXTRACTED', 'EVALUATING', 'UNASSIGNED', 'TRANSFER_PENDING',
        'FOR_DISPOSITION', 'FOR_TL_REVIEW', 'NB_PATH', 'FOR_PROCESSING', 'IN_PROCESSING', 'WITH_INSURER',
        'RA_READY', 'RA_GENERATED', 'RA_SENT', 'ACCEPTED', 'FOR_PLACEMENT_BOOKING', 'LETTER_PENDING', 'RENEWED',
        'CLOSED')),
    constraint ck_rnw_candidate_bucket check (bucket is null or bucket in ('CLEAN', 'REVIEW', 'EXCEPTION')),
    constraint ck_rnw_candidate_disposition check (disposition is null or disposition in ('FOR_RENEWAL',
        'NOT_FOR_RENEWAL', 'FOR_QUOTATION', 'FOR_PROPOSAL', 'LOST_BUSINESS')),
    constraint ck_rnw_candidate_proposed check (proposed_disposition is null or proposed_disposition in
        ('FOR_RENEWAL', 'NOT_FOR_RENEWAL', 'FOR_QUOTATION', 'FOR_PROPOSAL', 'LOST_BUSINESS')),
    constraint ck_rnw_candidate_automation check (proposed_automation is null or proposed_automation in ('AUTO', 'MANUAL')),
    constraint ck_rnw_candidate_disp_source check (disposition_source is null or disposition_source in ('USER',
        'SYSTEM_CHECK', 'MATRIX', 'UPLOAD', 'INSURER', 'LAMD')),
    constraint ck_rnw_candidate_ra_notice check (ra_notice in ('NONE', 'FIRST', 'SECOND')),
    constraint ck_rnw_candidate_path check (path in ('STANDARD', 'NB_PATH', 'STP')),
    constraint ck_rnw_candidate_closed check (closed_as is null or closed_as in ('RENEWED', 'NOT_RENEWED', 'LOST',
        'EXPIRED_UNRENEWED', 'BOOKED_OTHER_INVOICE')),
    constraint ck_rnw_candidate_nfr_reason check (disposition = 'NOT_FOR_RENEWAL' or nonrenewal_reason is null)
);
create unique index uq_rnw_candidate_source on rnw_candidate (company_id, source, source_ref) where source_ref is not null;
create unique index uq_rnw_candidate_invoice on rnw_candidate (company_id, expiring_invoice_no)
    where expiring_invoice_no is not null;
create index ix_rnw_candidate_stage on rnw_candidate (company_id, stage);
create index ix_rnw_candidate_expiry on rnw_candidate (company_id, expiry_date);
create index ix_rnw_candidate_ao on rnw_candidate (company_id, assigned_ao, stage);
create index ix_rnw_candidate_po on rnw_candidate (company_id, assigned_po, stage);
create index ix_rnw_candidate_bucket on rnw_candidate (company_id, bucket);
create index ix_rnw_candidate_unit on rnw_candidate (company_id, owner_unit);
create index ix_rnw_candidate_arn on rnw_candidate (expiring_arn);
create index ix_rnw_candidate_renewal_arn on rnw_candidate (renewal_arn);
create index ix_rnw_candidate_pn on rnw_candidate (pn_nos);
create index ix_rnw_candidate_client on rnw_candidate (client_id);

create table rnw_check_run (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    candidate_id    bigint       not null references rnw_candidate (id),
    trigger_kind    varchar(20)  not null,
    run_at          timestamptz  not null,
    bucket_before   varchar(20),
    bucket_after    varchar(20)  not null,
    rule_set_version integer,
    failed_count    integer      not null default 0,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_check_run_trigger check (trigger_kind in ('EXTRACTION', 'INITIATION', 'UPLOAD', 'EVENT',
        'NIGHTLY', 'MANUAL', 'OVERRIDE'))
);
create index ix_rnw_check_run_candidate on rnw_check_run (candidate_id, run_at);

create table rnw_check_result (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    run_id          bigint       not null references rnw_check_run (id),
    candidate_id    bigint       not null references rnw_candidate (id),
    check_code      varchar(40)  not null,
    outcome         varchar(20)  not null,
    severity        varchar(20)  not null,
    message         varchar(500),
    detail          varchar(2000),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_check_result_outcome check (outcome in ('PASS', 'WARN', 'FAIL', 'INFO', 'NOT_APPLICABLE')),
    constraint ck_rnw_check_result_severity check (severity in ('FAIL_EXCEPTION', 'FAIL_REVIEW', 'WARN', 'INFO', 'SYSTEM'))
);
create index ix_rnw_check_result_run on rnw_check_result (run_id);
create index ix_rnw_check_result_candidate on rnw_check_result (candidate_id, check_code);

create table rnw_bucket_history (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    from_bucket     varchar(20),
    to_bucket       varchar(20)  not null,
    rule_set_version integer,
    rule_id         bigint,
    check_run_id    bigint,
    cause           varchar(20)  not null,
    remarks         varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_bucket_history_cause check (cause in ('RULE', 'OVERRIDE'))
);
create index ix_rnw_bucket_history_candidate on rnw_bucket_history (candidate_id, created_at);

create table rnw_remark (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    stage           varchar(30)  not null,
    remark_text     varchar(200) not null,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_rnw_remark_candidate on rnw_remark (candidate_id, created_at);

create table rnw_followup (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    candidate_id     bigint       not null references rnw_candidate (id),
    channel          varchar(20)  not null,
    outcome          varchar(40)  not null,
    remarks          varchar(200) not null,
    next_action_date date,
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_rnw_followup_candidate on rnw_followup (candidate_id, created_at);

create table rnw_override (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    kind            varchar(30)  not null,
    check_code      varchar(40),
    from_value      varchar(60),
    to_value        varchar(60),
    reason_code     varchar(40)  not null,
    remarks         varchar(200) not null,
    active          boolean      not null default true,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_override_kind check (kind in ('BUCKET', 'DISPOSITION', 'OUTSTANDING_BALANCE',
        'INSURER_MISMATCH', 'RA_UNLOCK', 'CHECK'))
);
create index ix_rnw_override_candidate on rnw_override (candidate_id, kind);

create table rnw_history_view (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    sections        varchar(200) not null,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_rnw_history_view_candidate on rnw_history_view (candidate_id, created_by);

create table rnw_assignment (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    role            varchar(10)  not null,
    username        varchar(50)  not null,
    previous        varchar(50),
    reason_code     varchar(40),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_assignment_role check (role in ('AO', 'PO'))
);
create index ix_rnw_assignment_candidate on rnw_assignment (candidate_id);
create index ix_rnw_assignment_user on rnw_assignment (username, role);
