-- =====================================================================================
-- iNXT BrokerVerse - V1015 Renewal (BRD-6) processing and insurer: insurer batches with their
-- lines, insurer responses, LAMD reports and lines, and the declared scope of uploads.
--   BRD 3.009 / 4.007   extract per insurer with the 28 columns, sent protected
--   BRRN.035            insurer responses: append-only, the latest valid response drives the renewal;
--                       mismatched, late or conflicting responses never progress it
--   BRRN.029/039        LAMD paid-off and RMU reports matched by PN
--   BRD 3.004.4         "not in the file" tag of a complete dispositioned file (declared scope)
--   Design: docs/architecture/RENEWAL_DESIGN.md section 4.4. Files are attachments in the file store.
-- =====================================================================================

create table rnw_insurer_batch (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    batch_no        varchar(30)  not null,
    insurer_code    varchar(30)  not null,
    expiry_from     date         not null,
    expiry_to       date         not null,
    status          varchar(30)  not null,
    line_count      integer      not null default 0,
    attachment_id   bigint,
    message_id      bigint,
    recipients      varchar(500),
    sent_at         timestamptz,
    sent_by         varchar(50),
    reply_due       date,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_insurer_batch unique (company_id, batch_no),
    constraint ck_rnw_insurer_batch_status check (status in ('DRAFT', 'SENT', 'PARTIALLY_RESPONDED', 'CLOSED')),
    constraint ck_rnw_insurer_batch_range check (expiry_to >= expiry_from)
);
create index ix_rnw_insurer_batch_insurer on rnw_insurer_batch (company_id, insurer_code, status);

create table rnw_insurer_batch_line (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    batch_id        bigint       not null references rnw_insurer_batch (id),
    candidate_id    bigint       not null references rnw_candidate (id),
    snapshot        varchar(4000) not null,
    responded       boolean      not null default false,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_insurer_batch_line unique (batch_id, candidate_id)
);
create index ix_rnw_insurer_batch_line_candidate on rnw_insurer_batch_line (candidate_id);

create table rnw_insurer_response (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    batch_id        bigint,
    response        varchar(20)  not null,
    insurer_ref     varchar(60),
    revised_premium numeric(19, 2),
    revised_sum_insured numeric(19, 2),
    revised_rate    numeric(19, 8),
    terms           varchar(1000),
    received_on     date         not null,
    source          varchar(20)  not null,
    match_outcome   varchar(20)  not null,
    latest_valid    boolean      not null default false,
    late            boolean      not null default false,
    conflicting     boolean      not null default false,
    job_no          varchar(40),
    row_no          integer,
    remarks         varchar(200),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_insurer_response_code check (response in ('RENEW_AS_IS', 'REVISE', 'REJECT')),
    constraint ck_rnw_insurer_response_source check (source in ('UPLOAD', 'MANUAL')),
    constraint ck_rnw_insurer_response_match check (match_outcome in ('MATCHED', 'REF_MISMATCH', 'POLICY_MISMATCH',
        'AMBIGUOUS'))
);
create index ix_rnw_insurer_response_candidate on rnw_insurer_response (candidate_id, created_at);

create table rnw_lamd_report (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    report_no       varchar(30)  not null,
    report_type     varchar(20)  not null,
    period          varchar(7)   not null,
    job_no          varchar(40)  not null,
    line_count      integer      not null default 0,
    matched_count   integer      not null default 0,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_lamd_report unique (company_id, report_no),
    constraint uq_rnw_lamd_report_job unique (job_no),
    constraint ck_rnw_lamd_report_type check (report_type in ('PAID_OFF', 'RMU'))
);

create table rnw_lamd_line (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    report_id       bigint       not null references rnw_lamd_report (id),
    row_no          integer      not null,
    pn_no           varchar(40)  not null,
    loan_status     varchar(20)  not null,
    status_date     date,
    borrower        varchar(250),
    candidate_id    bigint       references rnw_candidate (id),
    match_outcome   varchar(20)  not null,
    routing         varchar(40),
    message         varchar(300),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_lamd_line_match check (match_outcome in ('MATCHED', 'UNMATCHED', 'AMBIGUOUS'))
);
create index ix_rnw_lamd_line_report on rnw_lamd_line (report_id);
create index ix_rnw_lamd_line_pn on rnw_lamd_line (pn_no);
create index ix_rnw_lamd_line_candidate on rnw_lamd_line (candidate_id);

create table rnw_upload_scope (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    job_no          varchar(40)  not null,
    kind            varchar(20)  not null,
    expiry_from     date,
    expiry_to       date,
    unit_code       varchar(20),
    complete_file   boolean      not null default false,
    applied_at      timestamptz,
    tagged_count    integer      not null default 0,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_upload_scope unique (job_no),
    constraint ck_rnw_upload_scope_kind check (kind in ('DISPOSITION', 'INSURER_RESPONSE', 'LAMD', 'LEGACY')),
    constraint ck_rnw_upload_scope_complete check (not complete_file or (expiry_from is not null and expiry_to is not null
        and unit_code is not null))
);
