-- =====================================================================================
-- iNXT BrokerVerse - V1014 Renewal (BRD-6) disposition: the append-only disposition history, the
-- transfers between Marketing units and the endorsements linked to a renewal.
--   BRD 2.004, BRRN.018/031/034   every disposition is a row (user, matrix, upload, insurer, LAMD,
--                                 system check), earlier rows are superseded, never changed
--   BRD 1.006/1.007/2.005         transfer requests, acceptance and decline with remarks
--   BRRN.032                      endorsements of the expiring invoice family linked to the renewal
--   Design: docs/architecture/RENEWAL_DESIGN.md section 4.3.
-- =====================================================================================

create table rnw_disposition (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    code            varchar(20)  not null,
    reason_code     varchar(40),
    remarks         varchar(200),
    new_invoice_no  varchar(40),
    source          varchar(20)  not null,
    matrix_version  integer,
    rule_id         bigint,
    superseded_by   bigint,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_disposition_code check (code in ('FOR_RENEWAL', 'NOT_FOR_RENEWAL', 'FOR_QUOTATION',
        'FOR_PROPOSAL', 'LOST_BUSINESS')),
    constraint ck_rnw_disposition_source check (source in ('USER', 'SYSTEM_CHECK', 'MATRIX', 'UPLOAD', 'INSURER', 'LAMD')),
    constraint ck_rnw_disposition_reason check (code = 'NOT_FOR_RENEWAL' or reason_code is null)
);
create index ix_rnw_disposition_candidate on rnw_disposition (candidate_id, created_at);

create table rnw_transfer (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    candidate_id     bigint       not null references rnw_candidate (id),
    from_unit        varchar(20),
    to_unit          varchar(20)  not null,
    from_stage       varchar(30)  not null,
    reason_code      varchar(40),
    remarks          varchar(200) not null,
    status           varchar(20)  not null,
    decided_by       varchar(50),
    decided_at       timestamptz,
    decision_remarks varchar(200),
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_rnw_transfer_status check (status in ('REQUESTED', 'ACCEPTED', 'DECLINED', 'CANCELLED')),
    constraint ck_rnw_transfer_units check (from_unit is null or from_unit <> to_unit)
);
create index ix_rnw_transfer_candidate on rnw_transfer (candidate_id);
create index ix_rnw_transfer_to on rnw_transfer (to_unit, status);
create unique index uq_rnw_transfer_open on rnw_transfer (candidate_id) where status = 'REQUESTED';

create table rnw_candidate_endorsement (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    candidate_id    bigint       not null references rnw_candidate (id),
    reference       varchar(40)  not null,
    source          varchar(20)  not null,
    status_at_link  varchar(30)  not null,
    effective_date  date,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_rnw_candidate_endorsement unique (candidate_id, reference),
    constraint ck_rnw_candidate_endorsement_source check (source in ('BOOKING', 'ADJUSTMENT'))
);
