-- =====================================================================================
-- iNXT BrokerVerse - V1023 Claims Handling (BRD-7) activity: the diary of a claim, the field-change
-- timeline of a claim and the maker-checker changes of the status and settlement attributes.
--   Requirements: docs/requirements/BDOI_CLM_BRD_SPEC.md
--     BRCLM.022/034    diary entries per claim and handler, due dates, assignee, done (NFR 15.08)
--     BRCLM.004/006/018/019/021  history of the reported date, claimant, adjuster, follow-up date
--                      and action plan (every version kept)
--     BRCLM.015/029    history of the requested type of settlement, amount and date
--     BRCLM.039        history of the cover version and the authorization code (CL1-A writes them)
--     BRCLM.010/014    status and settlement attributes maintained by the Unit Head under
--                      maker-checker (FR-CL-040 / FR-CL-043: a change takes effect after another
--                      user authorizes it)
--     NFR p.37         reassignment of a claim between handlers (old and new handler)
--   Design: docs/architecture/CLAIMS_BROKING_DESIGN.md sections 4, 5.2 and 5.3 (wave CL1-B).
--   Rows are insert-only except the completion of a diary entry; nothing is ever deleted.
-- =====================================================================================

-- ---------- Diary (BRCLM.022; design 5.2) ----------------------------------------------------
create table bcl_diary_entry (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    claim_id      bigint         not null references bcl_claim (id),
    entry_type    varchar(40)    not null,
    entry_date    date           not null,
    due_date      date,
    assignee      varchar(50),
    text          varchar(2000)  not null,
    done_at       timestamptz,
    done_by       varchar(50),
    done_remark   varchar(500),
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_bcl_diary_due check (due_date is null or due_date >= entry_date),
    constraint ck_bcl_diary_done check ((done_at is null) = (done_by is null))
);
create index ix_bcl_diary_claim on bcl_diary_entry (claim_id, entry_date);
-- My Diary and the follow-up job read the open entries of an assignee by due date (BRCLM.034).
create index ix_bcl_diary_open on bcl_diary_entry (assignee, due_date) where done_at is null;

-- ---------- Field-change timeline of a claim (design 5.2) ------------------------------------
create table bcl_claim_event (
    id          bigint generated by default as identity primary key,
    version     bigint         not null default 0,
    claim_id    bigint         not null references bcl_claim (id),
    field       varchar(30)    not null,
    old_value   varchar(2000),
    new_value   varchar(2000),
    reason      varchar(500),
    changed_by  varchar(50)    not null,
    changed_at  timestamptz    not null,
    created_at  timestamptz    not null,
    created_by  varchar(50)    not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_bcl_claim_event_field check (field in ('REPORTED_DATE', 'CLAIMANT', 'ADJUSTER',
        'FOLLOW_UP', 'ACTION_PLAN', 'SETTLEMENT', 'COVER_VERSION', 'AUTHORIZATION', 'HANDLER'))
);
create index ix_bcl_claim_event_claim on bcl_claim_event (claim_id, changed_at);
create index ix_bcl_claim_event_time on bcl_claim_event (changed_at);

-- ---------- Attribute changes waiting for authorization (BRCLM.010/014; FR-CL-040/043) -------
-- One row per proposed attribute value of a status or settlement type; new_value null removes
-- the attribute (e.g. blank follow-up days = parameter BCL_FOLLOW_UP_DAYS). Authorizing the
-- pending rows of a value (another BCL_SETUP holder, or MASTER_AUTHORIZE) applies them to
-- bcl_lov_attribute; a newer proposal supersedes the pending one (INACTIVE).
create table bcl_attribute_change (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    type_code      varchar(40)   not null references lov_type (code),
    code           varchar(40)   not null,
    attribute      varchar(40)   not null,
    new_value      varchar(200),
    record_status  varchar(30)   not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint fk_bcl_attribute_change_value foreign key (type_code, code) references lov_value (type_code, code),
    constraint ck_bcl_attribute_change_type check (type_code in ('BCL_CLAIM_STATUS', 'BCL_SETTLEMENT_TYPE')),
    constraint ck_bcl_attribute_change_name check (attribute in ('phase', 'waiting_on', 'follow_up_days',
        'awaiting_premium_remittance', 'outcome', 'closes_claim', 'requires_settlement_amount')),
    constraint ck_bcl_attribute_change_record check (record_status in ('PENDING_AUTHORIZATION', 'ACTIVE', 'INACTIVE'))
);
create index ix_bcl_attribute_change_value on bcl_attribute_change (type_code, code, record_status);
