-- =====================================================================================
-- iNXT BrokerVerse - V1021 Claims Handling (BRD-7) claim tables: the claim case file with its
-- cover snapshot, premium check, loss details, claimant and progress (every column of design
-- section 5.1, so that waves CL1-A and CL1-B work on a fixed schema), its locations, its insurer
-- claim lines and its status history.
--   Requirements: docs/requirements/BDOI_CLM_BRD_SPEC.md
--     BRCLM.001        premium status and claims authorization code
--     BRCLM.003/007/009/016/039  cover snapshot: ARN, policy year, policy number, cover version,
--                      sales stamp, currency (policy data never re-keyed, never edited)
--     BRCLM.004/036    loss details, reported date, catastrophe code
--     BRCLM.005/010-015/017-021/029/035  status, phase, closure, settlement, adjuster, follow-up,
--                      action plan
--     BRCLM.006        claimant name and override
--     BRCLM.011/027/028  status history with the days spent in the previous status
--     BRCLM.023/029/043  insurer claim numbers, share, reserve and settled amount per insurer
--     BRCLM.037        several locations of the cover under one claim
--     BRCLM.041        claim number, source and legacy reference (CLQ13, CLQ14)
--   Design: docs/architecture/CLAIMS_BROKING_DESIGN.md sections 4 and 5.1-5.2. ARN, account id,
--   item no., insurer codes, invoice numbers and usernames are plain values, as in Operations and
--   Collections: foreign keys go only to org_*, lov_* and bcl_* tables. Money numeric(19,2).
--   Entity brokerclaims.domain.Claim with the embeddables CoverSnapshot (CL1-A), LossDetails
--   (CL1-A) and ClaimProgress (CL1-B).
-- =====================================================================================

-- ---------- Claim (design 5.1; number BCL-<yyyy>-nnnnnn, CLQ13) ------------------------------
create table bcl_claim (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    -- Identity
    claim_no                  varchar(30)    not null,
    branch_id                 bigint         references org_branch (id),
    unit_code                 varchar(40),
    handler                   varchar(50)    not null,
    source                    varchar(20)    not null,
    legacy_ref                varchar(60),
    -- Cover snapshot (CoverSnapshot, CL1-A)
    arn                       varchar(30)    not null,
    account_id                bigint,
    policy_year               integer        not null,
    policy_no                 varchar(60),
    cover_version_no          integer,
    cover_version_ref         varchar(40),
    cover_version_at          date,
    product_code              varchar(30),
    line_code                 varchar(30),
    client_code               varchar(30),
    assured_name              varchar(250),
    lead_insurer_code         varchar(30),
    period_from               date,
    period_to                 date,
    sum_insured               numeric(19, 2),
    sales_region              varchar(40),
    sales_department          varchar(40),
    sales_team                varchar(40),
    account_officer           varchar(50),
    cost_center               varchar(40),
    invoicing_branch_id       bigint         references org_branch (id),
    currency                  varchar(3)     not null,
    -- Premium check and authorization code (CL1-A)
    premium_status            varchar(20),
    premium_checked_at        timestamptz,
    authorization_code        varchar(30),
    authorized_by             varchar(50),
    authorized_at             timestamptz,
    dp_evidence_attachment_id bigint,
    -- Loss (LossDetails, CL1-A)
    loss_date                 date           not null,
    reported_date             date           not null,
    loss_nature               varchar(40),
    claim_type                varchar(40),
    loss_description          varchar(2000),
    loss_place                varchar(500),
    catastrophe_code          varchar(40),
    catastrophe_event         varchar(200),
    claim_amount              numeric(19, 2),
    deductible                numeric(19, 2),
    initial_reserve           numeric(19, 2),
    -- Claimant (CL1-A)
    claimant_name             varchar(250),
    claimant_overridden       boolean        not null default false,
    claimant_reason           varchar(500),
    -- Progress (ClaimProgress, CL1-B)
    status_code               varchar(40),
    status_since              timestamptz,
    phase                     varchar(20)    not null default 'NEW',
    closure_kind              varchar(12),
    settlement_type_code      varchar(40),
    settlement_amount         numeric(19, 2),
    date_settled              date,
    closed_on                 date,
    adjuster_code             varchar(40),
    next_follow_up_date       date,
    follow_up_overridden      boolean        not null default false,
    next_action_plan          varchar(2000),
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_bcl_claim_no unique (company_id, claim_no),
    constraint ck_bcl_claim_source check (source in ('BDOI_NOTICE', 'INSURER_REPORTED', 'MIGRATED')),
    constraint ck_bcl_claim_phase check (phase in ('NEW', 'IN_PROGRESS', 'TEMP_CLOSED', 'CLOSED')),
    constraint ck_bcl_claim_closure check (closure_kind is null or closure_kind in ('TEMPORARY', 'PERMANENT')),
    constraint ck_bcl_claim_premium check (premium_status is null or premium_status in
        ('PAID', 'UNPAID', 'PARTIALLY_PAID', 'DIRECT_PAYMENT', 'NO_INVOICE')),
    constraint ck_bcl_claim_dates check (reported_date >= loss_date),
    constraint uq_bcl_claim_authorization unique (authorization_code)
);

create index ix_bcl_claim_arn on bcl_claim (company_id, arn, policy_year);
create index ix_bcl_claim_policy on bcl_claim (company_id, policy_no);
create index ix_bcl_claim_handler on bcl_claim (company_id, handler, phase);
create index ix_bcl_claim_phase on bcl_claim (company_id, phase, status_code);
create index ix_bcl_claim_follow_up on bcl_claim (company_id, next_follow_up_date)
    where phase <> 'CLOSED';
create index ix_bcl_claim_assured on bcl_claim (company_id, lower(assured_name));

-- ---------- Locations of the cover under the claim (BRCLM.037) --------------------------------
-- Only risk items of kind LOCATION of the claim's cover (account item no.); address snapshot.
create table bcl_claim_location (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    claim_id         bigint        not null references bcl_claim (id),
    account_item_no  integer       not null,
    address          varchar(500),
    city             varchar(100),
    province         varchar(100),
    location_key     varchar(400),
    description      varchar(500),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_bcl_claim_location unique (claim_id, account_item_no)
);
create index ix_bcl_claim_location_key on bcl_claim_location (location_key);

-- ---------- Insurer claim lines (BRCLM.023/029/043) -------------------------------------------
create table bcl_insurer_claim (
    id                     bigint generated by default as identity primary key,
    version                bigint         not null default 0,
    company_id             bigint         not null references org_company (id),
    claim_id               bigint         not null references bcl_claim (id),
    insurer_code           varchar(30)    not null,
    share_pct              numeric(9, 4),
    insurer_claim_no       varchar(60),
    reported_to_insurer_on date,
    reserve_amount         numeric(19, 2),
    settled_amount         numeric(19, 2),
    adjuster_code          varchar(40),
    created_at             timestamptz    not null,
    created_by             varchar(50)    not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint ck_bcl_insurer_claim_share check (share_pct is null or (share_pct > 0 and share_pct <= 100))
);
-- One line per insurer and insurer claim number of a claim (043 AC3); a line may wait for its number.
create unique index uq_bcl_insurer_claim on bcl_insurer_claim (claim_id, insurer_code, coalesce(insurer_claim_no, ''));
-- Search and the cross-claim duplicate warning BCL_INSURER_CLAIM_NO_REUSED (043 AC5).
create index ix_bcl_insurer_claim_no on bcl_insurer_claim (company_id, insurer_code, insurer_claim_no);

-- ---------- Status history (BRCLM.011/027/028; insert-only) -----------------------------------
create table bcl_status_history (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    claim_id         bigint        not null references bcl_claim (id),
    from_status      varchar(40),
    to_status        varchar(40)   not null,
    from_phase       varchar(20),
    to_phase         varchar(20)   not null,
    changed_at       timestamptz   not null,
    changed_by       varchar(50)   not null,
    remark           varchar(1000),
    days_in_previous integer,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_bcl_status_history_phase check (to_phase in ('NEW', 'IN_PROGRESS', 'TEMP_CLOSED', 'CLOSED')
        and (from_phase is null or from_phase in ('NEW', 'IN_PROGRESS', 'TEMP_CLOSED', 'CLOSED')))
);
create index ix_bcl_status_history_claim on bcl_status_history (claim_id, changed_at);
