-- =====================================================================================
-- iNXT BrokerVerse - V1022 Claims Handling (BRD-7) insurer side of a claim, wave CL1-A:
-- insurer updates, insurer reserve history and insurer location references.
--   Requirements: docs/requirements/BDOI_CLM_BRD_SPEC.md
--     BRCLM.023/024    insurer reserve per insurer claim line and its amendment history
--     BRCLM.041        insurer updates (date, source, reference, remarks, attachments), insert-only
--     BRCLM.042        insurer location references per location of a cover, with effective dates;
--                      a change closes the current reference and opens a new one
--     BRCLM.043        search of insurer claim numbers (043 AC5, case-insensitive)
--   Design: docs/architecture/CLAIMS_BROKING_DESIGN.md sections 4 and 5.2. ARN, account id, item
--   no. and insurer codes are plain values (no foreign key to acc_* or cat_*), as in V1021.
--   Entities: brokerclaims.insurer.domain.InsurerUpdate / ReserveChange,
--   brokerclaims.location.domain.LocationRef.
-- =====================================================================================

-- ---------- Insurer updates (BRCLM.041; insert-only, a correction refers to the update) ------
create table bcl_insurer_update (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    claim_id            bigint         not null references bcl_claim (id),
    insurer_claim_id    bigint         references bcl_insurer_claim (id),
    update_date         date           not null,
    source              varchar(40)    not null,
    reference           varchar(100),
    remarks             varchar(2000)  not null,
    attachment_ids      varchar(500),
    corrects_update_id  bigint         references bcl_insurer_update (id),
    upload_ref          varchar(40),
    recorded_by         varchar(50)    not null,
    recorded_at         timestamptz    not null,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);
create index ix_bcl_insurer_update_claim on bcl_insurer_update (claim_id, update_date);

-- ---------- Insurer reserve history (BRCLM.023/024; insert-only, information only) -----------
create table bcl_reserve_change (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    insurer_claim_id  bigint         not null references bcl_insurer_claim (id),
    previous_amount   numeric(19, 2),
    new_amount        numeric(19, 2) not null,
    reason            varchar(500)   not null,
    changed_by        varchar(50)    not null,
    changed_at        timestamptz    not null,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_bcl_reserve_change_amount check (new_amount >= 0)
);
create index ix_bcl_reserve_change_line on bcl_reserve_change (insurer_claim_id, changed_at);

-- ---------- Insurer location references (BRCLM.042) -----------------------------------------
create table bcl_location_ref (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    account_id            bigint,
    arn                   varchar(30)    not null,
    account_item_no       integer        not null,
    location_key          varchar(400),
    insurer_code          varchar(30)    not null,
    insurer_location_ref  varchar(60)    not null,
    effective_from        date           not null,
    effective_to          date,
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint ck_bcl_location_ref_dates check (effective_to is null or effective_to >= effective_from)
);
-- One open reference per location and insurer (R1); older ones are end-dated, never deleted (R2).
create unique index uq_bcl_location_ref_open on bcl_location_ref (company_id, arn, account_item_no, insurer_code)
    where effective_to is null;
create index ix_bcl_location_ref_location on bcl_location_ref (company_id, arn, account_item_no);
create index ix_bcl_location_ref_key on bcl_location_ref (location_key);

-- ---------- Search of insurer claim numbers (043 AC5) ------------------------------------------
create index ix_bcl_insurer_claim_no_lower on bcl_insurer_claim (company_id, lower(insurer_claim_no));
