-- =====================================================================================
-- iNXT BrokerVerse - V1034 Employee Benefits (BRD-8) wave E1-B: renewal advice, client feedback
-- and Broker on Record of a cycle.
--   BRID-001          renewal advice sent before expiry (job EB_RENEWAL_ADVICE or the AO), with the
--                     recipients, the outbox message and the stored RENEWAL_ADVICE document
--   BRID-002          reminders while no feedback is recorded (EB_RA_REMINDER_DAYS)
--   BRID-002/003      client feedback: channel, date received, text and / or files
--   BRID-008          Broker on Record: versions, checklist of the validator, validity dates
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 4.2 and 16.4 (E1-B puts eb_renewal_advice,
--   eb_feedback and eb_bor into its V1034). BDOI Drop 2 has no partner portal: feedback arrives by
--   e-mail, telephone or meeting and is recorded by the AO (channel PORTAL is not offered). The
--   marketing tables of section 3 (franchise, TOR, insurer requests, proposals, comparative,
--   confirmation, submissions) are not part of this wave; they take a later free version
--   (V1037-V1039). Files stay in the file store through doc_attachment (no file content here).
-- =====================================================================================

create table eb_renewal_advice (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint        not null references eb_cycle (id),
    expiry_date       date          not null,
    sent_at           timestamptz   not null,
    sent_by           varchar(60)   not null,
    trigger_kind      varchar(10)   not null,
    recipients        varchar(1000) not null,
    message_id        bigint,
    attachment_id     bigint references doc_attachment (id),
    reminders_sent    integer       not null default 0,
    last_reminder_at  timestamptz,
    feedback_at       timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_eb_renewal_advice_cycle unique (cycle_id),
    constraint ck_eb_renewal_advice_trigger check (trigger_kind in ('JOB', 'MANUAL')),
    constraint ck_eb_renewal_advice_reminders check (reminders_sent >= 0)
);
create index ix_eb_renewal_advice_open on eb_renewal_advice (company_id) where feedback_at is null;
create index ix_eb_renewal_advice_programme on eb_renewal_advice (programme_id);

create table eb_feedback (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint        not null references eb_cycle (id),
    channel           varchar(20)   not null,
    received_on       date          not null,
    feedback_text     varchar(4000),
    file_count        integer       not null default 0,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_feedback_channel check (channel in ('AO', 'EMAIL', 'PHONE', 'MEETING', 'LETTER')),
    -- Feedback needs text or at least one file (FR-EB-023 R1).
    constraint ck_eb_feedback_content check (feedback_text is not null or file_count > 0),
    constraint ck_eb_feedback_files check (file_count >= 0)
);
create index ix_eb_feedback_cycle on eb_feedback (cycle_id);

create table eb_bor (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint        not null references eb_cycle (id),
    version_no        integer       not null,
    attachment_id     bigint        not null references doc_attachment (id),
    status            varchar(20)   not null,
    signed_by_signatory boolean,
    not_blank         boolean,
    client_name_matches boolean,
    valid_from        date,
    valid_to          date,
    decided_by        varchar(50),
    decided_at        timestamptz,
    reject_reason     varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_eb_bor_version unique (cycle_id, version_no),
    constraint ck_eb_bor_status check (status in ('UPLOADED', 'VALIDATED', 'REJECTED', 'SUPERSEDED')),
    constraint ck_eb_bor_version check (version_no >= 1),
    constraint ck_eb_bor_validity check (valid_to is null or valid_from is null or valid_to > valid_from),
    -- A validated BOR carries the full checklist and its validity (FR-EB-031).
    constraint ck_eb_bor_validated check (status <> 'VALIDATED' or (signed_by_signatory and not_blank
        and client_name_matches and valid_from is not null and valid_to is not null))
);
create index ix_eb_bor_programme on eb_bor (programme_id, status);
