-- =====================================================================================
-- iNXT BrokerVerse - V1038 Employee Benefits (BRD-8) wave E1-C: member servicing and the insurer
-- statements of account.
--   Roster versions per programme and policy year, loaded from the master list (bulk handler
--   EB_MASTERLIST) as STAGED and accepted or rejected by the AO; the members of each version with
--   the minimal fields until the master list fields are confirmed (no health data)
--   Member changes (workflow EB_MEMBER_CHANGE) with their lines, the insurer billing and the
--   endorsement request raised in Operations for a change with a premium effect
--   Insurer SOAs (workflow EB_SOA) with their duplicate checks and the invoices they bill
--   Tracked items gain their member and member change (the plain references stay for items
--   opened before the roster)
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 4.4 and 16.8.
-- =====================================================================================

create table eb_roster_version (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    programme_id   bigint        not null references eb_programme (id),
    policy_year    integer       not null,
    version_no     integer       not null,
    source_ref     varchar(40)   not null,
    status         varchar(20)   not null,
    headcount      integer       not null default 0,
    decided_by     varchar(50),
    decided_at     timestamptz,
    reject_reason  varchar(500),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_roster_version unique (programme_id, policy_year, version_no),
    constraint uq_eb_roster_source unique (source_ref),
    constraint ck_eb_roster_status check (status in ('STAGED', 'ACCEPTED', 'REJECTED', 'SUPERSEDED')),
    constraint ck_eb_roster_headcount check (headcount >= 0)
);
create unique index uq_eb_roster_accepted on eb_roster_version (programme_id, policy_year)
    where status = 'ACCEPTED';

create table eb_member (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    roster_version_id bigint        not null references eb_roster_version (id),
    programme_id      bigint        not null references eb_programme (id),
    policy_year       integer       not null,
    employee_no       varchar(30)   not null,
    last_name         varchar(100)  not null,
    first_name        varchar(100)  not null,
    birth_date        date          not null,
    gender            varchar(10),
    civil_status      varchar(20),
    plan_code         varchar(30)   not null,
    dependants        integer       not null default 0,
    effective_from    date          not null,
    effective_to      date,
    status            varchar(20)   not null,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_member_status check (status in ('ACTIVE', 'DELETED')),
    constraint ck_eb_member_dependants check (dependants >= 0),
    constraint ck_eb_member_dates check (effective_to is null or effective_to >= effective_from)
);
-- One employee number per roster version (and so per programme and policy year when accepted).
create unique index uq_eb_member_employee on eb_member (roster_version_id, lower(employee_no));
create index ix_eb_member_programme on eb_member (programme_id, policy_year);
create index ix_eb_member_name on eb_member (lower(last_name), lower(first_name));

create table eb_member_change (
    id                     bigint generated by default as identity primary key,
    version                bigint         not null default 0,
    company_id             bigint         not null references org_company (id),
    change_no              varchar(30)    not null,
    programme_id           bigint         not null references eb_programme (id),
    line_no                integer        not null,
    benefit_line           varchar(30)    not null,
    policy_year            integer        not null,
    source                 varchar(10)    not null,
    financial              boolean        not null default false,
    direct_billed          boolean        not null default false,
    status                 varchar(20)    not null,
    description            varchar(1000),
    relayed_at             timestamptz,
    message_id             bigint,
    billed_on              date,
    billing_ref            varchar(60),
    billed_amount          numeric(19, 2),
    validated_at           timestamptz,
    validated_by           varchar(50),
    endorsement_request_id bigint,
    endorsement_request_no varchar(40),
    closed_at              timestamptz,
    created_at             timestamptz    not null,
    created_by             varchar(50)    not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_eb_member_change_no unique (company_id, change_no),
    constraint ck_eb_member_change_source check (source in ('AO', 'CLIENT')),
    constraint ck_eb_member_change_status check (status in ('CAPTURED', 'RELAYED', 'BILLED', 'VALIDATED',
        'CLOSED', 'CANCELLED'))
);
create index ix_eb_member_change_programme on eb_member_change (programme_id, status);
create index ix_eb_member_change_open on eb_member_change (company_id, status)
    where status not in ('CLOSED', 'CANCELLED');

create table eb_member_change_line (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    member_change_id bigint        not null references eb_member_change (id),
    sort_order       integer       not null,
    action           varchar(20)   not null,
    employee_no      varchar(30)   not null,
    member_id        bigint references eb_member (id),
    last_name        varchar(100),
    first_name       varchar(100),
    birth_date       date,
    gender           varchar(10),
    civil_status     varchar(20),
    plan_code        varchar(30),
    dependants       integer,
    effective_date   date          not null,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_eb_member_change_action check (action in ('ADD', 'DELETE', 'CHANGE_PLAN', 'CHANGE_DATA'))
);
create index ix_eb_member_change_line on eb_member_change_line (member_change_id, sort_order);

alter table eb_submission add constraint fk_eb_submission_member_change
    foreign key (member_change_id) references eb_member_change (id);

alter table eb_tracked_item add column member_id bigint references eb_member (id);
alter table eb_tracked_item add column member_change_id bigint references eb_member_change (id);
create index ix_eb_tracked_item_member_change on eb_tracked_item (member_change_id);

create table eb_soa (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    soa_no           varchar(30)    not null,
    programme_id     bigint         not null references eb_programme (id),
    insurer_code     varchar(30)    not null,
    insurer_soa_no   varchar(60)    not null,
    period_from      date           not null,
    period_to        date           not null,
    amount           numeric(19, 2) not null,
    currency         varchar(3)     not null,
    attachment_id    bigint         not null references doc_attachment (id),
    file_hash        varchar(64)    not null,
    status           varchar(20)    not null,
    received_on      date           not null,
    validated_at     timestamptz,
    validated_by     varchar(50),
    released_at      timestamptz,
    released_by      varchar(50),
    reject_reason    varchar(40),
    remarks          varchar(1000),
    paid_notified_at timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_eb_soa_no unique (company_id, soa_no),
    constraint ck_eb_soa_status check (status in ('RECEIVED', 'VALIDATED', 'RELEASED', 'REJECTED')),
    constraint ck_eb_soa_amount check (amount >= 0),
    constraint ck_eb_soa_period check (period_to >= period_from)
);
-- A duplicate SOA (same insurer and SOA number, or the same file) is refused unless rejected.
create unique index uq_eb_soa_insurer_no on eb_soa (company_id, insurer_code, lower(insurer_soa_no))
    where status <> 'REJECTED';
create unique index uq_eb_soa_file on eb_soa (company_id, file_hash) where status <> 'REJECTED';
create index ix_eb_soa_open on eb_soa (company_id, received_on) where status = 'RECEIVED';

create table eb_soa_invoice (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    soa_id      bigint        not null references eb_soa (id),
    invoice_no  varchar(40)   not null,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_eb_soa_invoice unique (soa_id, invoice_no)
);
create index ix_eb_soa_invoice_no on eb_soa_invoice (invoice_no);
