-- =====================================================================================
-- iNXT BrokerVerse - V1037 Employee Benefits (BRD-8) wave E1-B: the marketing records of a cycle
-- after the requirements.
--   Franchise requests to insurers and their decisions, advised to the client
--   Terms of Reference (versions and items) and the insurer requests for proposal
--   Insurer proposals (per benefit line and plan, per TOR item, per capability factor), revision
--   requests relayed to insurers, the comparative with its sign-offs, threshold approval and
--   comments, the client confirmation per line, the submissions of documents to insurers, and the
--   business masters threshold rules and required documents (maker-checker)
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 4.3 and 16.8. BDOI Drop 2 has no partner portal: the
--   insurers and the client answer by e-mail and the EB users record their answers with the
--   evidence. Files stay in the file store through doc_attachment (no file content here). Insurer,
--   client and ARN are plain values like Operations; foreign keys only to platform and EB tables.
-- =====================================================================================

-- ---------- Business masters (maker-checker) -------------------------------------------------
create table eb_threshold_rule (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    benefit_line        varchar(30),
    measure             varchar(20)    not null,
    amount              numeric(19, 2) not null,
    currency            varchar(3)     not null,
    approver_permission varchar(60)    not null,
    approval_level      integer        not null default 1,
    effective_from      date           not null,
    effective_to        date,
    description         varchar(300),
    record_status       varchar(30)    not null,
    authorized_by       varchar(50),
    authorized_at       timestamptz,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint ck_eb_threshold_measure check (measure in ('TSI', 'ANNUAL_PREMIUM')),
    constraint ck_eb_threshold_amount check (amount > 0),
    constraint ck_eb_threshold_level check (approval_level between 1 and 9),
    constraint ck_eb_threshold_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_eb_threshold_rule_company on eb_threshold_rule (company_id, record_status);

create table eb_required_document (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    process_type    varchar(30)  not null,
    benefit_line    varchar(30),
    document_type   varchar(40)  not null,
    mandatory       boolean      not null default true,
    record_status   varchar(30)  not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create unique index uq_eb_required_document on eb_required_document
    (company_id, process_type, coalesce(benefit_line, '*'), document_type);

-- ---------- Franchise requests (workflow EB_FRANCHISE) ---------------------------------------
create table eb_franchise_request (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    franchise_no           varchar(30)   not null,
    programme_id           bigint        not null references eb_programme (id),
    cycle_id               bigint        not null references eb_cycle (id),
    insurer_code           varchar(30)   not null,
    status                 varchar(20)   not null,
    decision               varchar(20),
    submitted_at           timestamptz,
    due_date               date,
    message_id             bigint,
    decided_on             date,
    decided_by             varchar(50),
    reason_code            varchar(40),
    remarks                varchar(1000),
    evidence_attachment_id bigint references doc_attachment (id),
    advice_due_date        date,
    advised_at             timestamptz,
    advised_by             varchar(50),
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_eb_franchise_no unique (company_id, franchise_no),
    constraint ck_eb_franchise_status check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED',
        'EXPIRED', 'ADVISED')),
    constraint ck_eb_franchise_decision check (decision is null or decision in ('APPROVED', 'REJECTED')),
    -- A decision recorded by the AO carries the insurer's reply as evidence.
    constraint ck_eb_franchise_evidence check (decision is null or evidence_attachment_id is not null)
);
-- One live request per insurer and cycle: waiting, or approved.
create unique index uq_eb_franchise_live on eb_franchise_request (cycle_id, insurer_code)
    where status in ('DRAFT', 'SUBMITTED') or decision = 'APPROVED';
create index ix_eb_franchise_due on eb_franchise_request (company_id, due_date) where status = 'SUBMITTED';

-- ---------- Terms of Reference and insurer requests ------------------------------------------
create table eb_tor (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    programme_id   bigint        not null references eb_programme (id),
    cycle_id       bigint        not null references eb_cycle (id),
    version_no     integer       not null,
    status         varchar(20)   not null,
    released_at    timestamptz,
    released_by    varchar(50),
    attachment_id  bigint references doc_attachment (id),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_tor_version unique (cycle_id, version_no),
    constraint ck_eb_tor_status check (status in ('DRAFT', 'RELEASED', 'SUPERSEDED'))
);
create unique index uq_eb_tor_draft on eb_tor (cycle_id) where status = 'DRAFT';

create table eb_tor_item (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    tor_id        bigint        not null references eb_tor (id),
    sort_order    integer       not null,
    benefit_line  varchar(30)   not null,
    plan_code     varchar(30),
    description   varchar(300)  not null,
    requirement   varchar(1000) not null,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create index ix_eb_tor_item_tor on eb_tor_item (tor_id, sort_order);

create table eb_insurer_request (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    request_no    varchar(30)   not null,
    programme_id  bigint        not null references eb_programme (id),
    cycle_id      bigint        not null references eb_cycle (id),
    insurer_code  varchar(30)   not null,
    tor_id        bigint        not null references eb_tor (id),
    tor_version   integer       not null,
    sent_at       timestamptz   not null,
    sent_by       varchar(50)   not null,
    due_date      date          not null,
    channel       varchar(10)   not null default 'EMAIL',
    message_id    bigint,
    status        varchar(20)   not null,
    closed_reason varchar(500),
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_eb_insurer_request_no unique (company_id, request_no),
    constraint ck_eb_insurer_request_status check (status in ('OPEN', 'RESPONDED', 'DECLINED', 'CLOSED'))
);
create unique index uq_eb_insurer_request_open on eb_insurer_request (cycle_id, insurer_code)
    where status = 'OPEN';
create index ix_eb_insurer_request_due on eb_insurer_request (company_id, due_date) where status = 'OPEN';

-- ---------- Revision requests (client changes relayed to insurers) ---------------------------
create table eb_revision_request (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    programme_id  bigint        not null references eb_programme (id),
    cycle_id      bigint        not null references eb_cycle (id),
    revision_no   integer       not null,
    description   varchar(1000),
    relayed_at    timestamptz   not null,
    relayed_by    varchar(50)   not null,
    due_date      date          not null,
    status        varchar(20)   not null,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_eb_revision_no unique (cycle_id, revision_no),
    constraint ck_eb_revision_status check (status in ('OPEN', 'ANSWERED'))
);

create table eb_revision_item (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    revision_id      bigint        not null references eb_revision_request (id),
    sort_order       integer       not null,
    tor_item_id      bigint references eb_tor_item (id),
    requested_change varchar(1000) not null,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);

create table eb_revision_target (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    revision_id          bigint        not null references eb_revision_request (id),
    insurer_code         varchar(30)   not null,
    status               varchar(20)   not null,
    message_id           bigint,
    answered_proposal_id bigint,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_eb_revision_target unique (revision_id, insurer_code),
    constraint ck_eb_revision_target_status check (status in ('OPEN', 'ANSWERED'))
);

-- ---------- Proposals ------------------------------------------------------------------------
create table eb_proposal (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    proposal_no    varchar(30)    not null,
    programme_id   bigint         not null references eb_programme (id),
    cycle_id       bigint         not null references eb_cycle (id),
    request_id     bigint references eb_insurer_request (id),
    revision_id    bigint references eb_revision_request (id),
    insurer_code   varchar(30)    not null,
    kind           varchar(30)    not null,
    version_no     integer        not null,
    status         varchar(20)    not null,
    source         varchar(20)    not null,
    received_on    date           not null,
    valid_until    date,
    currency       varchar(3)     not null,
    terms          varchar(4000),
    exclusions     varchar(4000),
    attachment_id  bigint         not null references doc_attachment (id),
    decided_by     varchar(50),
    decided_at     timestamptz,
    reject_reason  varchar(500),
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_proposal_no unique (company_id, proposal_no),
    constraint uq_eb_proposal_version unique (cycle_id, insurer_code, version_no),
    constraint ck_eb_proposal_kind check (kind in ('INCUMBENT_INDICATIVE', 'PROPOSAL', 'REVISED')),
    constraint ck_eb_proposal_status check (status in ('SUBMITTED', 'VALIDATED', 'REJECTED', 'SUPERSEDED')),
    constraint ck_eb_proposal_source check (source in ('AO', 'INSURER'))
);
create index ix_eb_proposal_cycle on eb_proposal (cycle_id, status);

alter table eb_revision_target add constraint fk_eb_revision_target_proposal
    foreign key (answered_proposal_id) references eb_proposal (id);

-- Premium per benefit line and plan (annual premium, TSI of GLI / GPA, members and rate per plan).
create table eb_proposal_line (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    proposal_id    bigint         not null references eb_proposal (id),
    sort_order     integer        not null,
    benefit_line   varchar(30)    not null,
    plan_code      varchar(30)    not null,
    plan_name      varchar(200),
    members        integer,
    premium_rate   numeric(19, 4),
    annual_premium numeric(19, 2) not null,
    sum_insured    numeric(19, 2),
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_eb_proposal_line_amounts check (annual_premium >= 0
        and (sum_insured is null or sum_insured >= 0) and (members is null or members >= 0))
);
create index ix_eb_proposal_line on eb_proposal_line (proposal_id, sort_order);

-- Answer per TOR item: offered value, deviation, remark.
create table eb_proposal_item (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    proposal_id    bigint        not null references eb_proposal (id),
    tor_item_id    bigint        not null references eb_tor_item (id),
    offered_value  varchar(1000) not null,
    deviation      boolean       not null default false,
    remark         varchar(500),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_proposal_item unique (proposal_id, tor_item_id)
);

-- Capability factors (list EB_CAPABILITY_FACTOR): value and a rating from 1 to 5 (EBQ10).
create table eb_proposal_factor (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    proposal_id    bigint        not null references eb_proposal (id),
    factor_code    varchar(40)   not null,
    factor_value   varchar(500),
    rating         integer,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_proposal_factor unique (proposal_id, factor_code),
    constraint ck_eb_proposal_factor_rating check (rating is null or rating between 1 and 5)
);

-- ---------- Comparative, sign-offs, comments -------------------------------------------------
create table eb_comparative (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    comparative_no      varchar(30)    not null,
    programme_id        bigint         not null references eb_programme (id),
    cycle_id            bigint         not null references eb_cycle (id),
    version_no          integer        not null,
    status              varchar(20)    not null,
    snapshot            text           not null,
    due_date            date,
    summary             varchar(2000),
    submitted_at        timestamptz,
    submitted_by        varchar(50),
    threshold_rules     varchar(500),
    approver_permission varchar(60),
    presented_at        timestamptz,
    presented_by        varchar(50),
    attachment_id       bigint references doc_attachment (id),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_eb_comparative_no unique (company_id, comparative_no),
    constraint uq_eb_comparative_version unique (cycle_id, version_no),
    constraint ck_eb_comparative_status check (status in ('DRAFT', 'FOR_APPROVAL', 'THRESHOLD_APPROVAL',
        'APPROVED', 'PRESENTED', 'SUPERSEDED'))
);
create index ix_eb_comparative_cycle on eb_comparative (cycle_id, status);

-- Recommended proposal per benefit line.
create table eb_comparative_line (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    comparative_id          bigint         not null references eb_comparative (id),
    benefit_line            varchar(30)    not null,
    recommended_proposal_id bigint references eb_proposal (id),
    lowest_premium          numeric(19, 2),
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50),
    constraint uq_eb_comparative_line unique (comparative_id, benefit_line)
);

create table eb_comparative_signoff (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    comparative_id  bigint        not null references eb_comparative (id),
    role            varchar(20)   not null,
    signatory       varchar(50)   not null,
    decision        varchar(20)   not null,
    remarks         varchar(1000),
    decided_at      timestamptz   not null,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_eb_signoff_role check (role in ('SIGNOFF', 'THRESHOLD')),
    constraint ck_eb_signoff_decision check (decision in ('APPROVED', 'RETURNED'))
);
create index ix_eb_signoff_comparative on eb_comparative_signoff (comparative_id);

-- Comment thread of a comparative: internal notes and the client's comments received by e-mail,
-- entered by the AO.
create table eb_comment (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    comparative_id  bigint        not null references eb_comparative (id),
    author_kind     varchar(10)   not null,
    comment_text    varchar(4000) not null,
    reply_to_id     bigint references eb_comment (id),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_eb_comment_author check (author_kind in ('INTERNAL', 'CLIENT'))
);
create index ix_eb_comment_comparative on eb_comment (comparative_id, id);

-- ---------- Client confirmation --------------------------------------------------------------
create table eb_client_confirmation (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    programme_id           bigint        not null references eb_programme (id),
    cycle_id               bigint        not null references eb_cycle (id),
    comparative_id         bigint references eb_comparative (id),
    channel                varchar(20)   not null,
    confirmed_on           date          not null,
    evidence_attachment_id bigint        not null references doc_attachment (id),
    status                 varchar(20)   not null,
    void_reason            varchar(500),
    remarks                varchar(1000),
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint ck_eb_confirmation_channel check (channel in ('EMAIL', 'SIGNED_DOCUMENT')),
    constraint ck_eb_confirmation_status check (status in ('ACTIVE', 'VOIDED'))
);
create unique index uq_eb_confirmation_active on eb_client_confirmation (cycle_id) where status = 'ACTIVE';

create table eb_confirmation_line (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    confirmation_id  bigint         not null references eb_client_confirmation (id),
    line_no          integer        not null,
    benefit_line     varchar(30)    not null,
    proposal_id      bigint         not null references eb_proposal (id),
    insurer_code     varchar(30)    not null,
    annual_premium   numeric(19, 2) not null,
    sum_insured      numeric(19, 2),
    account_arn      varchar(30),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_eb_confirmation_line unique (confirmation_id, line_no)
);

-- ---------- Submissions of documents to insurers ---------------------------------------------
create table eb_submission (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    programme_id     bigint        not null references eb_programme (id),
    cycle_id         bigint references eb_cycle (id),
    member_change_id bigint,
    process_type     varchar(30)   not null,
    insurer_code     varchar(30)   not null,
    sent_at          timestamptz   not null,
    sent_by          varchar(50)   not null,
    message_id       bigint,
    recipients       varchar(1000) not null,
    acknowledged_on  date,
    remarks          varchar(1000),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_eb_submission_programme on eb_submission (programme_id, sent_at desc);

create table eb_submission_document (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    submission_id  bigint        not null references eb_submission (id),
    attachment_id  bigint        not null references doc_attachment (id),
    document_type  varchar(40)   not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_eb_submission_document unique (submission_id, attachment_id)
);
