-- =====================================================================================
-- iNXT BrokerVerse - V1035 Employee Benefits (BRD-8) wave E1-C: tracked (pending) items and their
-- follow-ups.
--   BRID-030          contracts, HMO cards, card replacements and billings expected from the
--                     insurer, the client or BDOI, with due date, status and the follow-ups sent by
--                     job EB_ITEM_FOLLOWUP (EB_FOLLOWUP_DAYS working days apart, escalation after
--                     EB_FOLLOWUP_MAX: alert EB_ITEM_OVERDUE and event EB_ITEM_ESCALATED)
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 4.4, 8.1 and 16. The roster, member change and SOA
--   tables of section 3 are not part of this wave; a tracked item names its member and member
--   change as plain references until they exist. Created automatically for the contract of each
--   account at placement, and by the EB users for the other deliverables.
-- =====================================================================================

create table eb_tracked_item (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint references eb_cycle (id),
    item_type         varchar(30)   not null,
    subject           varchar(200)  not null,
    member_ref        varchar(60),
    member_change_ref varchar(30),
    account_arn       varchar(30),
    responsible       varchar(10)   not null,
    party_code        varchar(30),
    recipient_email   varchar(500),
    status            varchar(20)   not null,
    due_date          date          not null,
    follow_ups_sent   integer       not null default 0,
    last_follow_up_at timestamptz,
    escalated_at      timestamptz,
    received_on       date,
    released_on       date,
    closed_on         date,
    remarks           varchar(1000),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_tracked_item_responsible check (responsible in ('INSURER', 'CLIENT', 'BDOI')),
    constraint ck_eb_tracked_item_status check (status in ('PENDING', 'RECEIVED', 'RELEASED', 'CLOSED')),
    constraint ck_eb_tracked_item_follow_ups check (follow_ups_sent >= 0),
    -- A received item has its date received (FR-EB-057: "Enter the date received").
    constraint ck_eb_tracked_item_received check (status = 'PENDING' or received_on is not null
        or status = 'CLOSED')
);
create index ix_eb_tracked_item_programme on eb_tracked_item (programme_id, status);
create index ix_eb_tracked_item_due on eb_tracked_item (company_id, due_date) where status = 'PENDING';
create index ix_eb_tracked_item_member on eb_tracked_item (lower(member_ref));
create index ix_eb_tracked_item_arn on eb_tracked_item (account_arn);
