-- =====================================================================================
-- iNXT BrokerVerse - V1031 Employee Benefits (BRD-8) platform extensions: document access classes,
-- the process tag of documents and links, the cross-BRD document types RENEWAL_ADVICE and
-- CLAIM_REPORT with their access rows, and the insurer billing number of booked invoices.
--   BRID-025         documents restricted by department (Marketing / Processing / Collection) and
--                    linked to their transaction type (process tag, LOV EB_PROCESS_TYPE)
--   BRID-020         insurer billing number at booking, unique per company and insurer
--   Decision D3      RENEWAL_ADVICE and CLAIM_REPORT are shared document types (cross-BRD work item
--                    P3); seeded with "on conflict do nothing", so the order against V1010
--                    (Renewal) and V1020 (Claims) does not matter. Final matrix: XQ04 (CSQ07, EBQ15).
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 3 and 11; BDOI_CROSS_BRD_DECISIONS section 6.1 (P3).
-- att_document_access  document type -> permissions that may list and download documents of the
--                      type. A type without a row keeps today's behaviour (ATTACHMENT_VIEW only).
--                      access_class names the department of the row (MARKETING, PROCESSING,
--                      COLLECTION, CLAIMS, SERVICING, AUDIT). Maintained by the System
--                      Administrator (FRS BRD-8 configuration items). Permission names of modules
--                      not yet built (RNW_VIEW, CSF_VIEW) are plain values and take effect once the
--                      module grants them.
-- process_tag          on the attachment (the uploading record) and on each link (the records it
--                      is linked to); free code of the owning module (EB: EB_PROCESS_TYPE).
-- =====================================================================================

create table att_document_access (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    document_type  varchar(40)  not null,
    permission     varchar(50)  not null,
    access_class   varchar(20)  not null,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_att_document_access unique (document_type, permission),
    constraint ck_att_document_access_class check (access_class in ('MARKETING', 'PROCESSING',
        'COLLECTION', 'CLAIMS', 'SERVICING', 'AUDIT'))
);
create index ix_att_document_access_type on att_document_access (document_type);

alter table doc_attachment add column process_tag varchar(40);
alter table doc_attachment_link add column process_tag varchar(40);

-- Cross-BRD document types (decision D3).
insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
values ('DOCUMENT_TYPE', 'RENEWAL_ADVICE', 'Renewal advice', 77, null, date '2020-01-01', 'ACTIVE', 'SYSTEM',
        now(), now(), 'SYSTEM'),
       ('DOCUMENT_TYPE', 'CLAIM_REPORT', 'Claims report', 78, null, date '2020-01-01', 'ACTIVE', 'SYSTEM',
        now(), now(), 'SYSTEM')
on conflict (type_code, code) do nothing;

-- Access classes of the EB document types (spec 6.1). The department permissions:
--   MARKETING  = EB_MARKET, EB_COMPARATIVE_APPROVE, EB_THRESHOLD_APPROVE
--   PROCESSING = EB_PROCESS
--   COLLECTION = EB_COLLECT
--   AUDIT      = AUDIT_VIEW (every EB type: auditors read the whole file)
insert into att_document_access (document_type, permission, access_class, created_at, created_by)
select t.document_type, p.permission, p.access_class, now(), 'SYSTEM'
from (values
    ('EB_CLIENT_FEEDBACK', 'M'),
    ('EB_BOR', 'MP'),
    ('EB_TOR', 'MP'),
    ('EB_MASTERLIST', 'MP'),
    ('EB_MASTERLIST_UNNAMED', 'M'),
    ('EB_UTILIZATION', 'M'),
    ('EB_INDICATIVE_PROPOSAL', 'M'),
    ('EB_PROPOSAL', 'M'),
    ('EB_COMPARATIVE', 'M'),
    ('EB_FRANCHISE_FORM', 'M'),
    ('EB_CLIENT_CONFIRMATION', 'MP'),
    ('EB_POLICY_FORM', 'MPC'),
    ('EB_DIRECT_BILLING', 'MPC'),
    ('EB_SOA', 'PC'),
    ('EB_MEMBER_CHANGE', 'MP'),
    ('EB_ISACOM_APPROVAL', 'M')
) as t(document_type, classes)
join (values
    ('M', 'EB_MARKET', 'MARKETING'),
    ('M', 'EB_COMPARATIVE_APPROVE', 'MARKETING'),
    ('M', 'EB_THRESHOLD_APPROVE', 'MARKETING'),
    ('P', 'EB_PROCESS', 'PROCESSING'),
    ('C', 'EB_COLLECT', 'COLLECTION')
) as p(class_key, permission, access_class) on position(p.class_key in t.classes) > 0
union all
select t.code, 'AUDIT_VIEW', 'AUDIT', now(), 'SYSTEM'
from lov_value t
where t.type_code = 'DOCUMENT_TYPE' and t.code like 'EB\_%';

-- RENEWAL_ADVICE: Marketing and Processing (spec 6.1) of EB, Renewal and BRD-1, the Customer
-- Servicing agents who resend it (CSQ07), auditors.
insert into att_document_access (document_type, permission, access_class, created_at, created_by)
values ('RENEWAL_ADVICE', 'EB_MARKET', 'MARKETING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'EB_COMPARATIVE_APPROVE', 'MARKETING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'RNW_VIEW', 'MARKETING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'ACCOUNT_MAINTAIN', 'MARKETING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'EB_PROCESS', 'PROCESSING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'ACCOUNT_PROCESS', 'PROCESSING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'CSF_VIEW', 'SERVICING', now(), 'SYSTEM'),
       ('RENEWAL_ADVICE', 'AUDIT_VIEW', 'AUDIT', now(), 'SYSTEM'),
-- CLAIM_REPORT: Claims Handling users and report viewers, Customer Servicing agents, auditors.
       ('CLAIM_REPORT', 'BCL_VIEW', 'CLAIMS', now(), 'SYSTEM'),
       ('CLAIM_REPORT', 'BCL_REPORT_VIEW', 'CLAIMS', now(), 'SYSTEM'),
       ('CLAIM_REPORT', 'CSF_VIEW', 'SERVICING', now(), 'SYSTEM'),
       ('CLAIM_REPORT', 'AUDIT_VIEW', 'AUDIT', now(), 'SYSTEM')
on conflict (document_type, permission) do nothing;

-- ---------- Insurer billing number (BRID-020; EBQ18) --------------------------------------------
alter table bkg_invoice add column insurer_billing_no varchar(60);
create unique index uq_bkg_invoice_billing_no on bkg_invoice (company_id, insurer_code, insurer_billing_no)
    where insurer_billing_no is not null;
