-- =====================================================================================
-- iNXT BrokerVerse - V1033 Employee Benefits (BRD-8) core records shared by the build waves:
-- programmes with their benefit lines and HR contacts, cycles (one per policy year, mirroring the
-- EB_CYCLE work case), the EB document register and the activity log (TAT stamps).
--   BRID-006          client capture: programme of a client (prospect or confirmed)
--   BRID-001-004      renewal cycle opened by the RA job; new-business cycle opened by the AO
--   BRID-022.01       business type NEW_BUSINESS / RENEWAL required on every cycle (BT0, V822)
--   BRID-007/008/025  document register: type, process tag, version, source, status
--   BRID-022, 024     activity log: received / released stamps per activity of the TAT annex
--   Design: EMPLOYEE_BENEFITS_DESIGN sections 3 and 4.2. Built by the foundation (E0) so that the
--   marketing (E1-B) and servicing (E1-C) waves share them from the start; E1-B adds the renewal
--   advice, feedback and BOR tables to its V1034 with the marketing tables (design section 16).
--   Plain values for client code, insurer code, product code and ARN (as Operations); foreign keys
--   only to platform tables and to EB's own tables.
-- =====================================================================================

create table eb_programme (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_no      varchar(30)   not null,
    client_id         bigint        not null,
    client_code       varchar(30)   not null,
    client_name       varchar(250)  not null,
    name              varchar(200)  not null,
    team_code         varchar(40)   not null,
    funding           varchar(20)   not null,
    account_officer   varchar(50)   not null,
    sales_unit        varchar(20),
    renewal_eligible  boolean       not null default true,
    status            varchar(20)   not null,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_eb_programme_no unique (programme_no),
    constraint ck_eb_programme_funding check (funding in ('EMPLOYER', 'VOLUNTARY')),
    constraint ck_eb_programme_status check (status in ('PROSPECT', 'ACTIVE', 'LAPSED', 'LOST', 'INACTIVE'))
);
create index ix_eb_programme_company on eb_programme (company_id, status);
create index ix_eb_programme_client on eb_programme (client_id);
create index ix_eb_programme_ao on eb_programme (company_id, lower(account_officer), status);

create table eb_programme_line (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    programme_id      bigint        not null references eb_programme (id),
    line_no           integer       not null,
    benefit_line      varchar(20)   not null,
    product_code      varchar(20),
    incumbent_insurer varchar(30),
    current_policy_no varchar(60),
    current_arn       varchar(30),
    period_from       date,
    period_to         date,
    headcount         integer,
    active            boolean       not null default true,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_eb_programme_line unique (programme_id, line_no),
    constraint ck_eb_programme_line_period check (period_to is null or period_from is null or period_to > period_from),
    constraint ck_eb_programme_line_headcount check (headcount is null or headcount >= 0)
);
create index ix_eb_programme_line_arn on eb_programme_line (current_arn);
create index ix_eb_programme_line_expiry on eb_programme_line (period_to, active);

create table eb_programme_contact (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    programme_id      bigint        not null references eb_programme (id),
    name              varchar(200)  not null,
    email             varchar(120)  not null,
    mobile            varchar(30),
    role              varchar(20)   not null,
    receives_ra       boolean       not null default true,
    receives_soa      boolean       not null default false,
    active            boolean       not null default true,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_programme_contact_role check (role in ('HR_HEAD', 'HR_OFFICER', 'FINANCE'))
);
create index ix_eb_programme_contact on eb_programme_contact (programme_id);

create table eb_cycle (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    cycle_no          varchar(30)   not null,
    programme_id      bigint        not null references eb_programme (id),
    business_type     varchar(20)   not null,
    policy_year       integer       not null,
    target_inception  date,
    remarketing       boolean       not null default false,
    stage             varchar(30)   not null,
    outcome           varchar(30),
    outcome_reason    varchar(40),
    outcome_remarks   varchar(500),
    closed_at         timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_eb_cycle_no unique (cycle_no),
    constraint ck_eb_cycle_business_type check (business_type in ('NEW_BUSINESS', 'RENEWAL')),
    constraint ck_eb_cycle_outcome check (outcome is null or outcome in ('RENEWED_INCUMBENT', 'MOVED',
        'NEW_PLACED', 'NOT_RENEWED', 'LOST')),
    constraint ck_eb_cycle_year check (policy_year between 2000 and 2999)
);
-- One open cycle per programme and policy year (FR-EB-021 "already has an open cycle").
create unique index uq_eb_cycle_open on eb_cycle (programme_id, policy_year) where closed_at is null;
create index ix_eb_cycle_company on eb_cycle (company_id, stage);

-- ARNs created for a cycle at placement (one account per benefit line, BRID-017).
create table eb_cycle_account (
    cycle_id          bigint        not null references eb_cycle (id),
    account_index     integer       not null,
    arn               varchar(30)   not null,
    primary key (cycle_id, account_index)
);
create index ix_eb_cycle_account_arn on eb_cycle_account (arn);

create table eb_document (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint references eb_cycle (id),
    document_type     varchar(40)   not null,
    process_type      varchar(40)   not null,
    version_no        integer       not null default 1,
    attachment_id     bigint        not null references doc_attachment (id),
    source            varchar(20)   not null,
    status            varchar(20)   not null,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_document_version check (version_no >= 1),
    constraint ck_eb_document_source check (source in ('AO', 'PROCESSING', 'CLIENT', 'INSURER', 'SYSTEM')),
    constraint ck_eb_document_status check (status in ('ACTIVE', 'SUPERSEDED', 'REJECTED'))
);
create index ix_eb_document_programme on eb_document (programme_id, document_type, status);
create index ix_eb_document_cycle on eb_document (cycle_id);

create table eb_activity_log (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    programme_id      bigint        not null references eb_programme (id),
    cycle_id          bigint references eb_cycle (id),
    activity_code     varchar(40)   not null,
    reference         varchar(40),
    received_at       timestamptz   not null,
    released_at       timestamptz,
    actor             varchar(60)   not null,
    remarks           varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_eb_activity_released check (released_at is null or released_at >= received_at)
);
create index ix_eb_activity_programme on eb_activity_log (programme_id, activity_code);
create index ix_eb_activity_open on eb_activity_log (company_id, activity_code) where released_at is null;
