-- =====================================================================================
-- iNXT BrokerVerse - V1041 Customer Servicing Facility (BRD-9) tables: caller verifications,
-- contact changes with their field rows, the legacy contact sync outbox and the agent activity
-- log; search indexes on the loan application numbers.
--   Requirements: FRS BRD-9 v1.0 FR-CSF-010, 020, 021, 022, 040, 042.
--   Design: docs/architecture/CUSTOMER_SERVICING_DESIGN.md sections 3 and 4. The csf tables keep
--   client codes, ARNs and references as plain values; the only foreign keys are between csf
--   tables. The indexes on plc_billing_item (V850) and acc_account (V820) change no column.
-- =====================================================================================

-- Verification of a caller before a contact change (FR-CSF-020; e-mail topic 5).
create table csf_verification (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    company_id   bigint       not null,
    client_id    bigint       not null,
    client_code  varchar(30)  not null,
    channel      varchar(20)  not null,
    matches      integer      not null,
    required     integer      not null,
    result       varchar(10)  not null,
    verified_at  timestamptz  not null,
    valid_until  timestamptz  not null,
    agent        varchar(50)  not null,
    remarks      varchar(500),
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_csf_verification_result check (result in ('PASSED', 'FAILED')),
    constraint ck_csf_verification_matches check (matches >= 0 and required >= 1)
);
create index ix_csf_verification_client on csf_verification (client_id, verified_at);
create index ix_csf_verification_agent on csf_verification (agent, verified_at);

create table csf_verification_check (
    verification_id bigint      not null references csf_verification (id),
    check_index     integer     not null,
    check_code      varchar(40) not null,
    matched         boolean     not null,
    primary key (verification_id, check_index)
);

-- Contact change, refused change or referral to the fulfilment unit (FR-CSF-021, 022).
create table csf_contact_change (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null,
    change_no       varchar(30)  not null unique,
    client_id       bigint       not null,
    client_code     varchar(30)  not null,
    client_name     varchar(250) not null,
    verification_id bigint       references csf_verification (id),
    channel         varchar(20),
    reason_code     varchar(40),
    remarks         varchar(500),
    status          varchar(20)  not null,
    applied_at      timestamptz  not null,
    agent           varchar(50)  not null,
    sync_status     varchar(20)  not null,
    handoff_id      bigint,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_csf_change_status check (status in ('APPLIED', 'REFUSED', 'REFERRED')),
    constraint ck_csf_change_sync check (sync_status in ('NOT_REQUIRED', 'QUEUED', 'NOT_CONFIGURED', 'SENT', 'FAILED'))
);
create index ix_csf_change_client on csf_contact_change (client_id, applied_at);
create index ix_csf_change_company on csf_contact_change (company_id, applied_at);
create index ix_csf_change_agent on csf_contact_change (agent, applied_at);

create table csf_contact_change_field (
    change_id   bigint       not null references csf_contact_change (id),
    field_index integer      not null,
    field       varchar(40)  not null,
    old_value   varchar(300),
    new_value   varchar(300),
    primary key (change_id, field_index)
);

-- Write-back of the applied changes to QPS / EBIX while they coexist (FR-CSF-022, CSQ01).
create table csf_sync_outbox (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    change_id      bigint        not null references csf_contact_change (id),
    target_system  varchar(10)   not null,
    payload        text          not null,
    status         varchar(20)   not null,
    attempts       integer       not null default 0,
    last_error     varchar(500),
    last_attempt_at timestamptz,
    sent_at        timestamptz,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_csf_sync_outbox unique (change_id, target_system),
    constraint ck_csf_sync_target check (target_system in ('QPS', 'EBIX')),
    constraint ck_csf_sync_status check (status in ('NOT_CONFIGURED', 'QUEUED', 'SENT', 'FAILED'))
);
create index ix_csf_sync_outbox_status on csf_sync_outbox (status, id);

-- Agent activity log (FR-CSF-042): append-only.
create table csf_activity (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    company_id  bigint       not null,
    agent       varchar(50)  not null,
    action      varchar(30)  not null,
    client_id   bigint,
    client_code varchar(30),
    reference   varchar(120),
    detail      varchar(500),
    occurred_at timestamptz  not null,
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_csf_activity_action check (action in ('SEARCH', 'VIEW', 'DOWNLOAD', 'RESEND_RA',
        'RESEND_EPOLICY', 'UPLOAD', 'VERIFY', 'CONTACT_CHANGE', 'REFERRAL'))
);
create index ix_csf_activity_company on csf_activity (company_id, occurred_at);
create index ix_csf_activity_agent on csf_activity (agent, occurred_at);
create index ix_csf_activity_client on csf_activity (client_id, occurred_at);

-- Search keys (FR-CSF-010): loan application numbers of the accounts and billing items.
create index if not exists ix_plc_billing_item_loan_app on plc_billing_item (upper(loan_application_no))
    where loan_application_no is not null;
create index if not exists ix_acc_account_loan_app on acc_account (upper(loan_application_no))
    where loan_application_no is not null;
