-- =====================================================================================
-- iNXT BrokerVerse - V1053 Sanction Screening (BRD-10) matching and risk profiling (wave S1-B).
--   Requirements: docs/requirements/BDOI_SANC_BRD_SPEC.md
--     SNSRP-301  match results of the matching engine (scr_screening_run, scr_match)
--     SNSRP-302  automatic risk tagging; the history of every change (scr_client_risk_profile)
--     SNSRP-304  manual risk-tag update with justification and evidence; false-positive
--                suppression per client, entry and entry version (scr_match_suppression, SQ12)
--     SNSRP-602  screening triggers (client registered / changed, account submitted, list change,
--                batch window); every run is logged with its counts (scr_screening_run)
--   Design: docs/architecture/SANCTION_SCREENING_DESIGN.md section 4.3. Client, account and case
--   references are ids without foreign keys (as in Operations and Collections); the case wave
--   (V1054) stamps scr_match.case_id. The name keys (scr_name_key) are created by V1052 and written
--   only by screening.matching.
-- =====================================================================================

create table scr_screening_run (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    run_no            varchar(30)   not null unique,
    company_id        bigint        not null references org_company (id),
    trigger_code      varchar(30)   not null,
    reference         varchar(100),
    scope             varchar(200)  not null,
    full_rescreen     boolean       not null default false,
    match_version_id  bigint        not null references scr_config_version (id),
    risk_version_id   bigint        references scr_config_version (id),
    clients_screened  integer       not null default 0,
    entries_screened  integer       not null default 0,
    matches           integer       not null default 0,
    risk_changes      integer       not null default 0,
    cases_opened      integer       not null default 0,
    status            varchar(20)   not null,
    error             varchar(2000),
    job_run_id        bigint,
    started_at        timestamptz   not null,
    ended_at          timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_scr_screening_run_trigger check (trigger_code in ('CLIENT_REGISTERED', 'CLIENT_CHANGED',
        'ACCOUNT_SUBMITTED', 'LIST_CHANGE', 'PERIODIC', 'MANUAL')),
    constraint ck_scr_screening_run_status check (status in ('RUNNING', 'SUCCESS', 'FAILED'))
);
create index ix_scr_screening_run_company on scr_screening_run (company_id, started_at desc);
create index ix_scr_screening_run_trigger on scr_screening_run (company_id, trigger_code, started_at desc);

create table scr_match (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    run_id             bigint        not null references scr_screening_run (id),
    client_id          bigint        not null,
    client_code        varchar(30)   not null,
    client_name        varchar(300)  not null,
    entry_id           bigint        not null references scr_watchlist_entry (id),
    entry_version      integer       not null,
    entry_name         varchar(300)  not null,
    source_code        varchar(30)   not null,
    list_type          varchar(30)   not null,
    subject_type       varchar(20)   not null,
    match_version_id   bigint        not null references scr_config_version (id),
    match_rule_id      bigint,
    score              numeric(5, 4) not null,
    algorithm          varchar(10)   not null,
    matched_fields     varchar(100)  not null,
    case_threshold     boolean       not null default false,
    status             varchar(20)   not null,
    case_id            bigint,
    decided_by         varchar(50),
    decided_at         timestamptz,
    decision_remarks   varchar(2000),
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    -- FR-SS-030 R1 / FR-SS-031 R2: one match per client, entry version and configuration version.
    constraint uq_scr_match unique (client_id, entry_id, entry_version, match_version_id),
    constraint ck_scr_match_status check (status in ('POTENTIAL', 'TRUE_MATCH', 'FALSE_POSITIVE')),
    constraint ck_scr_match_algorithm check (algorithm in ('EXACT', 'PHONETIC', 'FUZZY')),
    constraint ck_scr_match_score check (score between 0 and 1)
);
create index ix_scr_match_company_status on scr_match (company_id, status, created_at desc);
create index ix_scr_match_client on scr_match (client_id);
create index ix_scr_match_run on scr_match (run_id);
create index ix_scr_match_case on scr_match (case_id) where case_id is not null;

create table scr_match_suppression (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    client_id          bigint        not null,
    entry_id           bigint        not null references scr_watchlist_entry (id),
    entry_version      integer       not null,
    match_id           bigint        not null references scr_match (id),
    reason             varchar(2000) not null,
    evidence           varchar(500)  not null,
    evidence_case_id   bigint,
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    -- SNSRP-304 / SQ12: suppressed until the entry changes (a new entry version is matched again).
    constraint uq_scr_match_suppression unique (client_id, entry_id, entry_version)
);

create table scr_client_risk_profile (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    client_id          bigint        not null,
    client_code        varchar(30)   not null,
    category_code      varchar(30),
    previous_rating    varchar(30),
    kyc_risk_rating    varchar(30),
    tags_added         varchar(200)  not null default '',
    tags_removed       varchar(200)  not null default '',
    active_tags        varchar(200)  not null default '',
    source             varchar(10)   not null,
    risk_version_id    bigint        references scr_config_version (id),
    rule_id            bigint,
    match_id           bigint        references scr_match (id),
    run_id             bigint        references scr_screening_run (id),
    justification      varchar(2000),
    evidence           varchar(500),
    evidence_case_id   bigint,
    kyc_review_due     date,
    effective_at       timestamptz   not null,
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_scr_client_risk_profile_source check (source in ('RULE', 'MANUAL')),
    constraint ck_scr_client_risk_profile_manual check (source = 'RULE'
        or (justification is not null and evidence is not null))
);
create index ix_scr_client_risk_profile_client on scr_client_risk_profile (client_id, effective_at desc);

-- SNSRP-302 / FR-SS-033 audit: the risk-profile history is insert-only.
create function scr_client_risk_profile_insert_only() returns trigger language plpgsql as $$
begin
    raise exception 'scr_client_risk_profile rows are insert-only';
end;
$$;

create trigger trg_scr_client_risk_profile_insert_only
    before update or delete on scr_client_risk_profile
    for each row execute function scr_client_risk_profile_insert_only();
