-- =====================================================================================
-- iNXT BrokerVerse - V1054 Sanction Screening (BRD-10) screening cases (wave S1-C).
--   Requirements: docs/requirements/BDOI_SANC_BRD_SPEC.md
--     SNSRP-303  cases opened for matches, risk categories and account applications (scr_case;
--                one open case per client and case type; active-policy flag, SQ10)
--     SNSRP-401  case lifecycle mirrored from workflow SCR_CASE; every step on the insert-only
--                case timeline (scr_case_event)
--     SNSRP-404  re-assignment with a reason (timeline REASSIGNED)
--     SNSRP-405  SLA due time, reminder and breach flags per stage entry (SNSRP-108, 802)
--     SNSRP-501  review template answers, version kept (scr_case_review, scr_case_answer)
--     SNSRP-601  case documents with form type, document type, date received, source and the
--                nominated name of the BRD naming convention (scr_case_document)
--     SNSRP-701  validation results on the timeline (VALIDATED / VALIDATION_FAILED)
--     SNSRP-704  AML Committee votes, one per member and round (scr_committee_vote, insert-only)
--     SNSRP-902  the timeline and the votes cannot be changed or deleted (triggers, as V26)
--   Design: docs/architecture/SANCTION_SCREENING_DESIGN.md sections 4.4 and 7. Client, account,
--   match and attachment references are ids without foreign keys (as in Operations and
--   Collections); the configuration versions in force at creation are kept per type (FR-SS-034 R4).
-- =====================================================================================

create table scr_case (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    case_no                varchar(30)   not null unique,
    client_id              bigint        not null,
    client_code            varchar(30)   not null,
    client_name            varchar(300)  not null,
    client_type            varchar(20)   not null,
    trigger_code           varchar(30)   not null,
    trigger_reference      varchar(100),
    case_type              varchar(30)   not null,
    risk_category          varchar(30),
    template_type          varchar(30)   not null,
    active_policy          boolean       not null default false,
    marketing_unit         varchar(20),
    unit_head              varchar(50),
    account_officer        varchar(50),
    team_code              varchar(20),
    stage                  varchar(30)   not null,
    status                 varchar(10)   not null,
    stage_entered_at       timestamptz   not null,
    assignee               varchar(50),
    investigator           varchar(50),
    returned_from          varchar(30),
    returned_by            varchar(50),
    round_no               integer       not null default 1,
    committee_round        integer       not null default 0,
    disposition            varchar(40),
    recommendation         varchar(4000),
    str_required           boolean       not null default false,
    committee_decision     varchar(40),
    committee_decided_at   timestamptz,
    due_at                 timestamptz,
    reminder_lead_hours    integer,
    remind_at              timestamptz,
    escalate_to_role       varchar(40),
    reminded_at            timestamptz,
    breached               boolean       not null default false,
    breached_at            timestamptz,
    escalated_to           varchar(200),
    document_reminded_on   date,
    match_version_id       bigint        references scr_config_version (id),
    risk_version_id        bigint        references scr_config_version (id),
    approval_version_id    bigint        references scr_config_version (id),
    assignment_version_id  bigint        references scr_config_version (id),
    sla_version_id         bigint        references scr_config_version (id),
    validation_version_id  bigint        references scr_config_version (id),
    work_case_id           bigint        references wf_case (id),
    closed_at              timestamptz,
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint ck_scr_case_type check (case_type in ('NAME_MATCH', 'PEP', 'HIGH_RISK', 'EDD', 'MONITOR',
        'ACCOUNT_APPLICATION')),
    constraint ck_scr_case_status check (status in ('OPEN', 'CLOSED')),
    constraint ck_scr_case_stage check (stage in ('NEW', 'INVESTIGATION', 'RETURNED', 'UNIT_HEAD_APPROVAL',
        'COMPLIANCE_REVIEW', 'AML_COMMITTEE', 'STR_PREPARATION', 'STR_EXTRACTION', 'CLOSED')),
    constraint ck_scr_case_template check (template_type in ('KYC_REVIEW', 'TRANSACTION_REVIEW', 'EDD')),
    constraint ck_scr_case_closed check ((status = 'CLOSED') = (stage = 'CLOSED'))
);
-- FR-SS-034 R1: one open case per client and case type.
create unique index uq_scr_case_open on scr_case (client_id, case_type) where status = 'OPEN';
create index ix_scr_case_company_stage on scr_case (company_id, status, stage, created_at desc);
create index ix_scr_case_assignee on scr_case (lower(assignee)) where status = 'OPEN';
create index ix_scr_case_client on scr_case (client_id, created_at desc);
create index ix_scr_case_due on scr_case (due_at) where status = 'OPEN';

create table scr_case_event (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    case_id      bigint        not null references scr_case (id),
    event        varchar(30)   not null,
    round_no     integer       not null default 1,
    from_stage   varchar(30),
    to_stage     varchar(30),
    from_value   varchar(300),
    to_value     varchar(300),
    reason_code  varchar(40),
    remarks      varchar(4000),
    actor        varchar(50)   not null,
    occurred_at  timestamptz   not null,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_scr_case_event check (event in ('CREATED', 'ASSIGNED', 'REASSIGNED', 'MATCH_ADDED',
        'MATCH_DECIDED', 'REVIEW_SAVED', 'INFO_REQUESTED', 'SUBMITTED', 'VALIDATED', 'VALIDATION_FAILED',
        'APPROVED', 'DISAPPROVED', 'RETURNED', 'RESUBMITTED', 'ESCALATED', 'COMMITTEE_VOTE',
        'COMMITTEE_DECISION', 'STR_PREPARED', 'STR_READY', 'STR_EXTRACTED', 'FILED', 'CLOSED', 'REOPENED',
        'REMINDER', 'DOCUMENT_REMINDER', 'BREACH', 'DOCUMENT_ADDED', 'RISK_TAG_CHANGED'))
);
create index ix_scr_case_event_case on scr_case_event (case_id, id);
create index ix_scr_case_event_time on scr_case_event (occurred_at);

create table scr_case_review (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    case_id              bigint        not null references scr_case (id),
    template_version_id  bigint        not null references scr_config_version (id),
    template_type        varchar(30)   not null,
    status               varchar(20)   not null,
    submitted_by         varchar(50),
    submitted_at         timestamptz,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_scr_case_review unique (case_id),
    constraint ck_scr_case_review_status check (status in ('DRAFT', 'SUBMITTED'))
);

create table scr_case_answer (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    review_id      bigint         not null references scr_case_review (id),
    field_code     varchar(40)    not null,
    value_text     varchar(4000),
    value_number   numeric(19, 4),
    value_date     date,
    attachment_id  bigint,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_scr_case_answer unique (review_id, field_code)
);

create table scr_case_document (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    case_id         bigint        not null references scr_case (id),
    attachment_id   bigint        not null,
    form_type       varchar(30)   not null,
    document_type   varchar(40)   not null,
    date_received   date          not null,
    source          varchar(100)  not null,
    sequence_no     integer       not null,
    nominated_name  varchar(300)  not null,
    kyc_registered  boolean       not null default false,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_scr_case_document_case on scr_case_document (case_id, document_type);

create table scr_committee_vote (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    case_id     bigint        not null references scr_case (id),
    round_no    integer       not null,
    member      varchar(50)   not null,
    decision    varchar(40)   not null,
    remarks     varchar(4000) not null,
    voted_at    timestamptz   not null,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    -- FR-SS-064 R1: one vote per member per case round.
    constraint uq_scr_committee_vote unique (case_id, round_no, member)
);

-- SNSRP-902 / FR-SS-091: the case timeline and the committee votes are insert-only.
create function scr_case_insert_only() returns trigger language plpgsql as $$
begin
    raise exception '% rows are insert-only', tg_table_name;
end;
$$;

create trigger trg_scr_case_event_insert_only
    before update or delete on scr_case_event
    for each row execute function scr_case_insert_only();

create trigger trg_scr_committee_vote_insert_only
    before update or delete on scr_committee_vote
    for each row execute function scr_case_insert_only();
