-- =====================================================================================
-- iNXT BrokerVerse - V1052 Sanction Screening (BRD-10) watchlists and ingestion (wave S1-A).
--   Requirements: docs/requirements/BDOI_SANC_BRD_SPEC.md
--     SNSRP-201  list sources, scheduled / uploaded ingestion and the run log (scr_watchlist_source,
--                scr_ingestion_run)
--     SNSRP-202  records that failed ingestion (scr_ingestion_error; digest job
--                SCR_INGEST_ERROR_DIGEST)
--     SNSRP-203  manual add / change / deactivation as a pending change with before / after values
--                (scr_watchlist_entry, scr_watchlist_alias, scr_watchlist_change)
--     SNSRP-204  checker approval / rejection; a decided change is read only (insert-only trigger)
--     SNSRP-301  blocking keys of the matching engine (scr_name_key, written by screening.matching)
--   Design: docs/architecture/SANCTION_SCREENING_DESIGN.md section 4.2. Watchlists are reference
--   data shared by all companies (no company_id). Screening reads ACTIVE entries only. Transports
--   other than file upload / file drop are parked (SQ01). The three sources of the BRD are seeded
--   here (they are configuration, not demo data); the demo entries come with db/demo/V1951.
-- =====================================================================================

create table scr_watchlist_source (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    code         varchar(30)   not null unique,
    name         varchar(100)  not null,
    list_type    varchar(30)   not null,
    transport    varchar(10)   not null,
    schedule     varchar(100),
    file_layout  varchar(10),
    full_file    boolean       not null default false,
    drop_file    varchar(100),
    ref_prefix   varchar(10)   not null,
    active       boolean       not null default true,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_scr_watchlist_source_transport check (transport in ('FILE', 'API', 'MANUAL')),
    constraint ck_scr_watchlist_source_layout check (file_layout in ('CSV', 'XLSX'))
);

create table scr_watchlist_entry (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    source_id       bigint        not null references scr_watchlist_source (id),
    external_ref    varchar(60)   not null,
    list_type       varchar(30)   not null,
    entity_type     varchar(20)   not null,
    primary_name    varchar(300)  not null,
    first_name      varchar(100),
    last_name       varchar(100),
    birth_date      date,
    nationality     varchar(60),
    id_numbers      varchar(300),
    listed_on       date,
    delisted_on     date,
    status          varchar(20)   not null,
    effective_from  date,
    entry_version   integer       not null default 0,
    remarks         varchar(2000),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_scr_watchlist_entry unique (source_id, external_ref),
    constraint ck_scr_watchlist_entry_type check (entity_type in ('INDIVIDUAL', 'ENTITY')),
    constraint ck_scr_watchlist_entry_status check (status in ('DRAFT', 'PENDING', 'ACTIVE', 'INACTIVE')),
    constraint ck_scr_watchlist_entry_dates check (delisted_on is null or listed_on is null
        or delisted_on >= listed_on)
);
create index ix_scr_watchlist_entry_status on scr_watchlist_entry (status, list_type);
create index ix_scr_watchlist_entry_name on scr_watchlist_entry (lower(primary_name));

create table scr_watchlist_alias (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    entry_id    bigint        not null references scr_watchlist_entry (id),
    alias_name  varchar(300)  not null,
    alias_type  varchar(20)   not null,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_scr_watchlist_alias_type check (alias_type in ('AKA', 'FKA', 'SPELLING'))
);
create index ix_scr_watchlist_alias_entry on scr_watchlist_alias (entry_id);

create table scr_ingestion_run (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    run_no              varchar(30)   not null unique,
    source_id           bigint        not null references scr_watchlist_source (id),
    trigger_code        varchar(20)   not null,
    file_name           varchar(255),
    file_attachment_id  bigint,
    received            integer       not null default 0,
    added               integer       not null default 0,
    updated             integer       not null default 0,
    delisted            integer       not null default 0,
    unchanged           integer       not null default 0,
    failed              integer       not null default 0,
    pending_approval    boolean       not null default false,
    status              varchar(20)   not null,
    error               varchar(2000),
    job_run_id          bigint,
    started_at          timestamptz   not null,
    ended_at            timestamptz,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint ck_scr_ingestion_run_trigger check (trigger_code in ('SCHEDULED', 'MANUAL_UPLOAD', 'API')),
    constraint ck_scr_ingestion_run_status check (status in ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED'))
);
create index ix_scr_ingestion_run_source on scr_ingestion_run (source_id, started_at desc);

create table scr_ingestion_error (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    run_id       bigint        not null references scr_ingestion_run (id),
    line_no      integer       not null,
    raw_record   varchar(4000),
    reason       varchar(1000) not null,
    digested_at  timestamptz,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);
create index ix_scr_ingestion_error_run on scr_ingestion_error (run_id);
create index ix_scr_ingestion_error_digest on scr_ingestion_error (digested_at) where digested_at is null;

create table scr_watchlist_change (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    entry_id          bigint        not null references scr_watchlist_entry (id),
    run_id            bigint        references scr_ingestion_run (id),
    change_type       varchar(20)   not null,
    before_values     text,
    after_values      text          not null,
    maker_remarks     varchar(2000) not null,
    status            varchar(20)   not null,
    decided_by        varchar(50),
    decided_at        timestamptz,
    decision_remarks  varchar(2000),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_scr_watchlist_change_type check (change_type in ('ADD', 'UPDATE', 'DEACTIVATE')),
    constraint ck_scr_watchlist_change_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);
create index ix_scr_watchlist_change_entry on scr_watchlist_change (entry_id);
create index ix_scr_watchlist_change_status on scr_watchlist_change (status);
-- SNSRP-204 / FR-SS-023 R2: at most one pending change per entry; a decided change is read only.
create unique index uq_scr_watchlist_change_pending on scr_watchlist_change (entry_id) where status = 'PENDING';

create function scr_watchlist_change_decided() returns trigger language plpgsql as $$
begin
    if tg_op = 'DELETE' or old.status <> 'PENDING' then
        raise exception 'scr_watchlist_change rows are read only once decided';
    end if;
    return new;
end;
$$;

create trigger trg_scr_watchlist_change_decided
    before update or delete on scr_watchlist_change
    for each row execute function scr_watchlist_change_decided();

-- Blocking keys of the matching engine (design 4.2; written and read by screening.matching, S1-B).
create table scr_name_key (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    subject_kind  varchar(10)   not null,
    subject_id    bigint        not null,
    key_type      varchar(10)   not null,
    key_value     varchar(200)  not null,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_scr_name_key_kind check (subject_kind in ('CLIENT', 'ENTRY', 'ALIAS')),
    constraint ck_scr_name_key_type check (key_type in ('TOKEN', 'PHONETIC', 'EXACT'))
);
create index ix_scr_name_key_lookup on scr_name_key (key_type, key_value);
create index ix_scr_name_key_subject on scr_name_key (subject_kind, subject_id);

-- ---------- List sources of the BRD (pp.6-8, SNSRP-201; transports to confirm, SQ01) ----------
insert into scr_watchlist_source (code, name, list_type, transport, schedule, file_layout, full_file,
    drop_file, ref_prefix, active, created_at, created_by)
values ('AML_ADVISORY', 'AML advisory (sanctions list)', 'SANCTION', 'FILE', 'Daily 01:00', 'CSV', true,
        'aml_advisory.csv', 'AML', true, now(), 'SYSTEM'),
       ('NLDS_PEP', 'NLDS politically exposed persons', 'PEP', 'FILE', 'Daily 01:00', 'CSV', false,
        'nlds_pep.csv', 'PEP', true, now(), 'SYSTEM'),
       ('INTERNAL', 'Internal watchlist', 'INTERNAL', 'MANUAL', null, null, false, null, 'INT', true,
        now(), 'SYSTEM');
