-- =====================================================================================
-- iNXT BrokerVerse - V1055 Sanction Screening (BRD-10) suspicious transaction reports (wave S1-C).
--   Requirements: docs/requirements/BDOI_SANC_BRD_SPEC.md
--     SNSRP-705  STR prefilled from the case (subject snapshot, narrative, transactions) and kept
--                editable until it is marked ready; completeness against the STR template (scr_str,
--                scr_str_field, scr_str_transaction)
--     SNSRP-706  extraction of the AML Committee-approved STRs in the active STR layout, saved in
--                the report archive (StrFileSink, SQ16); the AMLC filing reference (unique) is
--                recorded afterwards (scr_str_extraction, scr_str_extraction_item)
--   Design: docs/architecture/SANCTION_SCREENING_DESIGN.md section 4.4. The AMLC layout itself is
--   parked (SQ09): extraction uses the STR_LAYOUT version in force (placeholder in the seed).
-- =====================================================================================

create table scr_str_extraction (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    batch_no           varchar(30)   not null unique,
    period_from        date          not null,
    period_to          date          not null,
    layout_version_id  bigint        not null references scr_config_version (id),
    str_count          integer       not null,
    file_name          varchar(200)  not null,
    sha256             varchar(64)   not null,
    report_run_id      bigint,
    re_extraction      boolean       not null default false,
    reason             varchar(1000),
    extracted_by       varchar(50)   not null,
    extracted_at       timestamptz   not null,
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_scr_str_extraction_period check (period_to >= period_from),
    constraint ck_scr_str_extraction_reason check (not re_extraction or reason is not null)
);
create index ix_scr_str_extraction_company on scr_str_extraction (company_id, extracted_at desc);

create table scr_str (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    case_id              bigint        not null unique references scr_case (id),
    str_no               varchar(30)   not null unique,
    template_version_id  bigint        references scr_config_version (id),
    subject_code         varchar(30)   not null,
    subject_name         varchar(300)  not null,
    subject_snapshot     varchar(4000) not null,
    reason_codes         varchar(500)  not null default '',
    status               varchar(20)   not null,
    committee_decided_at timestamptz,
    ready_by             varchar(50),
    ready_at             timestamptz,
    extraction_id        bigint        references scr_str_extraction (id),
    extracted_at         timestamptz,
    amlc_reference       varchar(60)   unique,
    filed_on             date,
    filed_by             varchar(50),
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_scr_str_status check (status in ('DRAFT', 'FOR_APPROVAL', 'APPROVED', 'EXTRACTED', 'FILED')),
    constraint ck_scr_str_filed check (status <> 'FILED' or (amlc_reference is not null and filed_on is not null))
);
create index ix_scr_str_company_status on scr_str (company_id, status, committee_decided_at);

create table scr_str_field (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    str_id      bigint        not null references scr_str (id),
    field_code  varchar(40)   not null,
    value_text  varchar(8000),
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_scr_str_field unique (str_id, field_code)
);

create table scr_str_transaction (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    str_id       bigint         not null references scr_str (id),
    reference    varchar(60)    not null,
    txn_date     date           not null,
    amount       numeric(19, 2) not null,
    currency     varchar(3)     not null,
    txn_type     varchar(30)    not null,
    description  varchar(500),
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_scr_str_transaction_amount check (amount > 0)
);
create index ix_scr_str_transaction_str on scr_str_transaction (str_id);

create table scr_str_extraction_item (
    extraction_id  bigint not null references scr_str_extraction (id),
    str_id         bigint not null references scr_str (id),
    primary key (extraction_id, str_id)
);
