-- =====================================================================================
-- iNXT BrokerVerse - V1051 Sanction Screening (BRD-10) versioned configuration (wave S1-A).
--   Requirements: docs/requirements/BDOI_SANC_BRD_SPEC.md
--     SNSRP-101  matching criteria (scr_match_rule)
--     SNSRP-102  risk categories and tagging rules (scr_risk_category, scr_risk_rule)
--     SNSRP-103  approval / escalation matrix (scr_approval_route; SNSRP-703)
--     SNSRP-104  review templates (scr_template, scr_template_field)
--     SNSRP-105  STR template and extraction layout (scr_str_layout, scr_str_layout_column; SQ09)
--     SNSRP-106  case assignment matrix (scr_assignment_rule)
--     SNSRP-108  SLA matrix (scr_sla_rule)
--     SNSRP-109  maker-checker: DRAFT -> PENDING -> ACTIVE / REJECTED, SUPERSEDED on the date of
--                the next version (scr_config_version)
--     SNSRP-701  validation rules (scr_validation_rule)
--   Design: docs/architecture/SANCTION_SCREENING_DESIGN.md section 4.1. Every rule row belongs to
--   one version; an ACTIVE version is never edited (the service refuses it), a change is a new
--   version. TEMPLATE versions are kept per template type (scope); the other types have scope ''.
--   No seed data here: the seed versions come with db/seed/V1950.
-- =====================================================================================

create table scr_config_version (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    config_type      varchar(30)   not null,
    scope            varchar(30)   not null default '',
    version_no       integer       not null,
    status           varchar(20)   not null,
    effective_from   date          not null,
    change_note      varchar(1000),
    base_version_id  bigint        references scr_config_version (id),
    submitted_by     varchar(50),
    submitted_at     timestamptz,
    decided_by       varchar(50),
    decided_at       timestamptz,
    decision_reason  varchar(1000),
    diff             text,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_scr_config_version unique (company_id, config_type, scope, version_no),
    constraint ck_scr_config_version_type check (config_type in ('MATCH_CRITERIA', 'RISK_RULES',
        'APPROVAL_MATRIX', 'ASSIGNMENT_MATRIX', 'SLA_MATRIX', 'VALIDATION_RULES', 'TEMPLATE', 'STR_LAYOUT')),
    constraint ck_scr_config_version_status check (status in ('DRAFT', 'PENDING', 'ACTIVE', 'SUPERSEDED',
        'REJECTED')),
    constraint ck_scr_config_version_scope check ((config_type = 'TEMPLATE') = (scope <> ''))
);
-- FR-SS-010 R1: at most one DRAFT or PENDING version per type, one ACTIVE version per type and date.
create unique index uq_scr_config_version_open on scr_config_version (company_id, config_type, scope)
    where status in ('DRAFT', 'PENDING');
create unique index uq_scr_config_version_active on scr_config_version (company_id, config_type, scope,
    effective_from) where status = 'ACTIVE';
create index ix_scr_config_version_status on scr_config_version (status);

create table scr_match_rule (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    version_id          bigint        not null references scr_config_version (id) on delete cascade,
    sort_order          integer       not null,
    list_type           varchar(30)   not null,
    subject_type        varchar(20)   not null,
    algorithm           varchar(20)   not null,
    threshold           numeric(5,4)  not null,
    match_fields        varchar(200)  not null,
    min_score_for_case  numeric(5,4)  not null,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_scr_match_rule unique (version_id, list_type, subject_type, algorithm),
    constraint ck_scr_match_rule_subject check (subject_type in ('INDIVIDUAL', 'ENTITY')),
    constraint ck_scr_match_rule_algorithm check (algorithm in ('EXACT', 'PHONETIC', 'FUZZY')),
    constraint ck_scr_match_rule_threshold check (threshold between 0 and 1
        and min_score_for_case between threshold and 1)
);
create index ix_scr_match_rule_version on scr_match_rule (version_id);

create table scr_risk_category (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    version_id       bigint        not null references scr_config_version (id) on delete cascade,
    code             varchar(30)   not null,
    name             varchar(100)  not null,
    tier             integer       not null,
    kyc_risk_rating  varchar(30)   not null,
    tags             varchar(200)  not null default '',
    case_type        varchar(30),
    requires_edd     boolean       not null default false,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_scr_risk_category unique (version_id, code),
    constraint ck_scr_risk_category_tier check (tier > 0)
);
create index ix_scr_risk_category_version on scr_risk_category (version_id);

create table scr_risk_rule (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    version_id      bigint        not null references scr_config_version (id) on delete cascade,
    priority        integer       not null,
    category_code   varchar(30)   not null,
    condition_attr  varchar(30)   not null,
    operator        varchar(10)   not null,
    rule_values     varchar(500)  not null,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_scr_risk_rule unique (version_id, priority),
    constraint ck_scr_risk_rule_attr check (condition_attr in ('MATCH_LIST_TYPE', 'MATCH_STATUS', 'PEP',
        'NATIONALITY', 'OCCUPATION', 'SOURCE_OF_FUNDS', 'CLIENT_TYPE', 'MARKET_SEGMENT')),
    constraint ck_scr_risk_rule_operator check (operator in ('EQ', 'IN', 'NOT_IN'))
);
create index ix_scr_risk_rule_version on scr_risk_rule (version_id);

create table scr_approval_route (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    version_id      bigint        not null references scr_config_version (id) on delete cascade,
    sort_order      integer       not null,
    from_stage      varchar(30)   not null,
    case_type       varchar(30),
    risk_category   varchar(30),
    marketing_unit  varchar(30),
    disposition     varchar(40),
    to_stage        varchar(30)   not null,
    approver_kind   varchar(20),
    approver_value  varchar(50),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_scr_approval_route unique (version_id, sort_order),
    constraint ck_scr_approval_route_kind check (approver_kind in ('UNIT_HEAD', 'ROLE', 'USER'))
);
create index ix_scr_approval_route_version on scr_approval_route (version_id);

create table scr_assignment_rule (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    version_id      bigint        not null references scr_config_version (id) on delete cascade,
    sort_order      integer       not null,
    case_type       varchar(30),
    trigger_code    varchar(30),
    risk_category   varchar(30),
    marketing_unit  varchar(30),
    client_type     varchar(20),
    team_role       varchar(50),
    user_name       varchar(50),
    balancing       varchar(20)   not null,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_scr_assignment_rule unique (version_id, sort_order),
    constraint ck_scr_assignment_rule_target check (team_role is not null or user_name is not null),
    constraint ck_scr_assignment_rule_balancing check (balancing in ('ROUND_ROBIN', 'LEAST_OPEN', 'NONE'))
);
create index ix_scr_assignment_rule_version on scr_assignment_rule (version_id);

create table scr_sla_rule (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    version_id           bigint        not null references scr_config_version (id) on delete cascade,
    stage                varchar(30)   not null,
    case_type            varchar(30),
    risk_category        varchar(30),
    sla_hours            integer       not null,
    reminder_lead_hours  integer       not null default 0,
    escalate_to_role     varchar(50)   not null,
    calendar             varchar(20)   not null,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_scr_sla_rule_hours check (sla_hours > 0 and reminder_lead_hours >= 0
        and reminder_lead_hours < sla_hours),
    constraint ck_scr_sla_rule_calendar check (calendar in ('CALENDAR', 'WORKING'))
);
create unique index uq_scr_sla_rule on scr_sla_rule (version_id, stage, coalesce(case_type, ''),
    coalesce(risk_category, ''));

create table scr_validation_rule (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    version_id  bigint        not null references scr_config_version (id) on delete cascade,
    stage       varchar(30),
    case_type   varchar(30),
    rule_kind   varchar(40)   not null,
    parameters  varchar(500),
    blocking    boolean       not null default true,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_scr_validation_rule_kind check (rule_kind in ('TEMPLATE_COMPLETE', 'DOCUMENT_TYPES_PRESENT',
        'DISPOSITION_ALLOWED', 'RECOMMENDATION_PRESENT', 'STR_FLAG_CONSISTENT'))
);
create index ix_scr_validation_rule_version on scr_validation_rule (version_id);

create table scr_template (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    version_id     bigint        not null unique references scr_config_version (id) on delete cascade,
    template_type  varchar(30)   not null,
    name           varchar(100)  not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_scr_template_type check (template_type in ('KYC_REVIEW', 'TRANSACTION_REVIEW', 'EDD', 'STR'))
);

create table scr_template_field (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    template_id     bigint        not null references scr_template (id) on delete cascade,
    section         varchar(100)  not null,
    code            varchar(40)   not null,
    label           varchar(200)  not null,
    data_type       varchar(20)   not null,
    lov_type        varchar(40),
    mandatory       boolean       not null default false,
    help_text       varchar(500),
    sort_order      integer       not null,
    prefill_source  varchar(60),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_scr_template_field unique (template_id, code),
    constraint ck_scr_template_field_type check (data_type in ('TEXT', 'LONG_TEXT', 'NUMBER', 'AMOUNT', 'DATE',
        'LOV', 'CHECKBOX', 'ATTACHMENT')),
    constraint ck_scr_template_field_lov check (data_type <> 'LOV' or lov_type is not null)
);
create index ix_scr_template_field_template on scr_template_field (template_id);

create table scr_str_layout (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    version_id  bigint        not null unique references scr_config_version (id) on delete cascade,
    format      varchar(10)   not null,
    delimiter   varchar(5),
    encoding    varchar(20)   not null default 'UTF-8',
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_scr_str_layout_format check (format in ('CSV', 'FIXED', 'XLSX', 'XML'))
);

create table scr_str_layout_column (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    layout_id    bigint        not null references scr_str_layout (id) on delete cascade,
    sort_order   integer       not null,
    field_code   varchar(40),
    fixed_value  varchar(200),
    header       varchar(100),
    length       integer,
    pad          varchar(10),
    code_map     varchar(1000) not null default '',
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_scr_str_layout_column unique (layout_id, sort_order),
    constraint ck_scr_str_layout_column_source check (field_code is not null or fixed_value is not null),
    constraint ck_scr_str_layout_column_pad check (pad in ('LEFT', 'RIGHT'))
);
create index ix_scr_str_layout_column_layout on scr_str_layout_column (layout_id);
