-- =====================================================================================
-- iNXT BrokerVerse - V1063 User Access Maintenance (BRD-11), wave U1-B: sign-in, passwords,
-- sessions and the user access reports.
--   sec_user                  + mobile number, maintained by the user on My Profile (UQ17)
--   sec_password_reset_token  single-use "Forgot password?" links, valid 30 minutes; only the
--                             SHA-256 of the token is kept (UAM-NFR-37; FR-UA-005 R3)
--   msg_notification_event    PASSWORD_EXPIRY_NOTICE (job PASSWORD_EXPIRY_NOTICE; UAM-NFR-36)
--   sec_role_permission       REPORT_VIEW for every role holding UAM_REPORT_VIEW, so the holders
--                             reach the report runner of the five user access reports (BRD 3.003,
--                             4.003.1; FR-UA-060 to 063)
--   Design: docs/architecture/USER_ACCESS_DESIGN.md sections 3, 4.1, 8 and 18 (U1-B as built).
-- =====================================================================================

alter table sec_user add column mobile_no varchar(30);

create table sec_password_reset_token (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    token_hash   varchar(64)  not null,
    username     varchar(50)  not null,
    requested_at timestamptz  not null,
    expires_at   timestamptz  not null,
    used_at      timestamptz,
    constraint uq_sec_password_reset_token unique (token_hash),
    constraint ck_sec_password_reset_expiry check (expires_at > requested_at)
);
create index ix_sec_password_reset_user on sec_password_reset_token (lower(username), requested_at desc);

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PASSWORD_EXPIRY_NOTICE', 'Password expires soon', 'USER_ACCESS',
     'Your BrokerVerse password expires within 7 days; change it on My Profile (UAM-NFR-36)', true, true, 670);

insert into sec_role_permission (role_id, permission)
select distinct holder.role_id, 'REPORT_VIEW'
from sec_role_permission holder
where holder.permission = 'UAM_REPORT_VIEW'
  and not exists (select 1 from sec_role_permission x where x.role_id = holder.role_id and x.permission = 'REPORT_VIEW');
