-- =====================================================================================
-- iNXT BrokerVerse - V1062 User Access Maintenance (BRD-11) request lifecycle (wave U1-A).
--   Requirements: docs/requirements/BDOI_UAM_BRD_SPEC.md
--     BRD 1.002-1.005    enrol / modify / deactivate / reactivate a user: drafts, user data
--                        (Windows ID, business unit, user level), reason, unlock
--     BRD 1.002.1.1.3    the requester chooses the approver (assigned_approver, approver rows)
--     BRD 1.006-1.008    correction of a returned request, cancellation with a reason, history
--     BRD 1.009          bulk requests: a batch of line requests (nba_access_request_batch)
--     BRD 2.002          approve, reject, return; four eyes (requester and subject user excluded)
--     BRD 3.002.1-4      group-profile requests CREATE_ROLE / MODIFY_ROLE_PERMISSIONS /
--                        DEACTIVATE_ROLE / REACTIVATE_ROLE with approvers in order, then the
--                        System Administrator implements them (FOR_IMPLEMENTATION -> IMPLEMENTED)
--     UAM-NFR-14         effective date: approved requests SCHEDULED until the daily job applies them
--     UAM-NFR-40         risk flags (PRIVILEGE_INCREASE, OUTSIDE_HOURS) and second approval
--     Decision D7        user type EXTERNAL (portal users of insurers and clients) through the
--                        port ExternalUserProvisioner; change log subject type EXTERNAL_USER
--   Design: docs/architecture/USER_ACCESS_DESIGN.md sections 3, 4.2-4.4 and 9.
--   Behaviour switches (the implement-request flow is live with this wave):
--     UAM_DIRECT_ROLE_EDIT       = false: roles change only by implementing an approved request
--                                  (PQ17); the emergency path stays audited and alerted.
--     UAM_ROLE_APPLY_ON_APPROVAL = false: approved group-profile and role-permission requests
--                                  wait for the System Administrator (BRD-11 p.6; UQ03).
-- =====================================================================================

-- ---------- Bulk batches (BRD 1.009) ---------------------------------------------------------
create table nba_access_request_batch (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    batch_no    varchar(30)   not null unique,
    file_name   varchar(255),
    lines       integer       not null default 0,
    status      varchar(20)   not null default 'DRAFT',
    remarks     varchar(1000),
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_nba_access_batch_status check (status in ('DRAFT', 'PENDING', 'RETURNED',
        'CANCELLED', 'REJECTED', 'APPROVED', 'PARTIAL'))
);

-- ---------- Access requests: new types, statuses and fields ------------------------------------
alter table nba_access_request alter column justification drop not null;

alter table nba_access_request add column user_type varchar(10) not null default 'INTERNAL';
alter table nba_access_request add column party_kind varchar(10);
alter table nba_access_request add column party_code varchar(40);
alter table nba_access_request add column portal_role varchar(40);
alter table nba_access_request add column windows_id varchar(50);
alter table nba_access_request add column business_unit_code varchar(40);
alter table nba_access_request add column user_level varchar(40);
alter table nba_access_request add column reason_code varchar(40);
alter table nba_access_request add column unlock_account boolean not null default false;
alter table nba_access_request add column effective_from date;
alter table nba_access_request add column assigned_approver varchar(50);
alter table nba_access_request add column batch_id bigint references nba_access_request_batch (id);
alter table nba_access_request add column role_name varchar(120);
alter table nba_access_request add column role_description varchar(500);
alter table nba_access_request add column privilege_level varchar(10);
alter table nba_access_request add column submitted_by varchar(50);
alter table nba_access_request add column submitted_at timestamptz;
alter table nba_access_request add column cancel_reason varchar(1000);
alter table nba_access_request add column cancelled_by varchar(50);
alter table nba_access_request add column cancelled_at timestamptz;
alter table nba_access_request add column applied_at timestamptz;
alter table nba_access_request add column implemented_by varchar(50);
alter table nba_access_request add column implemented_at timestamptz;
alter table nba_access_request add column second_approval_required boolean not null default false;
alter table nba_access_request add column risk_flags varchar(100);
alter table nba_access_request add column apply_error varchar(1000);

-- Requests created before this release were submitted when they were created.
update nba_access_request set submitted_by = created_by, submitted_at = created_at;
update nba_access_request set applied_at = decided_at where status = 'APPROVED';

alter table nba_access_request drop constraint ck_nba_access_type;
alter table nba_access_request add constraint ck_nba_access_type
    check (request_type in ('CREATE_USER', 'MODIFY_ROLES', 'MODIFY_USER', 'DISABLE_USER', 'ENABLE_USER',
                            'MODIFY_ROLE_PERMISSIONS', 'CREATE_ROLE', 'DEACTIVATE_ROLE', 'REACTIVATE_ROLE'));

alter table nba_access_request drop constraint ck_nba_access_status;
alter table nba_access_request add constraint ck_nba_access_status
    check (status in ('DRAFT', 'PENDING', 'PENDING_SECOND', 'RETURNED', 'CANCELLED', 'REJECTED',
                      'APPROVED', 'SCHEDULED', 'FOR_IMPLEMENTATION', 'IMPLEMENTED'));

-- A decided request names its (last) decider.
alter table nba_access_request drop constraint ck_nba_access_decided;
alter table nba_access_request add constraint ck_nba_access_decided
    check (status in ('DRAFT', 'PENDING', 'PENDING_SECOND', 'CANCELLED')
        or (decided_by is not null and decided_at is not null));

-- A user request names the user; a group-profile request names the role (the permissions of a
-- change are checked on submission, a draft may still be incomplete).
alter table nba_access_request drop constraint ck_nba_access_subject;
alter table nba_access_request add constraint ck_nba_access_subject
    check ((request_type in ('MODIFY_ROLE_PERMISSIONS', 'CREATE_ROLE', 'DEACTIVATE_ROLE', 'REACTIVATE_ROLE')
            and role_code is not null)
        or (request_type not in ('MODIFY_ROLE_PERMISSIONS', 'CREATE_ROLE', 'DEACTIVATE_ROLE', 'REACTIVATE_ROLE')
            and username is not null));

-- External (portal) users: create, disable and enable only, with the party (decision D7).
alter table nba_access_request add constraint ck_nba_access_user_type
    check (user_type = 'INTERNAL'
        or (user_type = 'EXTERNAL'
            and request_type in ('CREATE_USER', 'DISABLE_USER', 'ENABLE_USER')
            and party_kind in ('INSURER', 'CLIENT') and party_code is not null));
alter table nba_access_request add constraint ck_nba_access_privilege
    check (privilege_level is null or privilege_level in ('LOW', 'STANDARD', 'HIGH', 'ADMIN'));
alter table nba_access_request add constraint ck_nba_access_cancelled
    check (status <> 'CANCELLED' or (cancel_reason is not null and cancelled_by is not null));

create index ix_nba_access_assigned on nba_access_request (lower(assigned_approver), status)
    where assigned_approver is not null;
create index ix_nba_access_creator on nba_access_request (lower(created_by), status);
create index ix_nba_access_batch on nba_access_request (batch_id) where batch_id is not null;
create index ix_nba_access_scheduled on nba_access_request (effective_from) where status = 'SCHEDULED';

-- ---------- Approvers in order (BRD 3.002.x "approver/s"; user requests have one) -------------
create table nba_access_request_approver (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    request_id  bigint        not null references nba_access_request (id),
    sequence    integer       not null,
    approver    varchar(50)   not null,
    decision    varchar(10)   not null default 'PENDING',
    remarks     varchar(1000),
    decided_at  timestamptz,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    -- Deferred: a resubmission replaces the approver list in one transaction. An approver appears
    -- once per request (checked by the service, message "<user> is already an approver").
    constraint uq_nba_access_approver_seq unique (request_id, sequence) deferrable initially deferred,
    constraint ck_nba_access_approver_decision check (decision in ('PENDING', 'APPROVED', 'REJECTED', 'RETURNED')),
    constraint ck_nba_access_approver_seq check (sequence > 0)
);
create index ix_nba_access_approver_user on nba_access_request_approver (lower(approver), decision);

-- ---------- Request history (insert-only; every remark of the BRD) ----------------------------
create table nba_access_request_event (
    id           bigint generated by default as identity primary key,
    request_id   bigint        not null references nba_access_request (id),
    action       varchar(20)   not null,
    from_status  varchar(20),
    to_status    varchar(20)   not null,
    remarks      varchar(1000),
    actor        varchar(50)   not null,
    occurred_at  timestamptz   not null,
    constraint ck_nba_access_event_action check (action in ('SAVE', 'EDIT', 'SUBMIT', 'RESUBMIT', 'RETURN',
        'CANCEL', 'APPROVE', 'SECOND_APPROVE', 'REJECT', 'SCHEDULE', 'APPLY', 'APPLY_FAILED',
        'FOR_IMPLEMENTATION', 'IMPLEMENT'))
);
create index ix_nba_access_event_request on nba_access_request_event (request_id, occurred_at);

create function nba_access_request_event_immutable() returns trigger language plpgsql as $$
begin
    raise exception 'nba_access_request_event rows are immutable; the request history is insert-only';
end;
$$;

create trigger trg_nba_access_request_event_immutable
    before update or delete on nba_access_request_event
    for each row execute function nba_access_request_event_immutable();

create trigger trg_nba_access_request_event_no_truncate
    before truncate on nba_access_request_event
    for each statement execute function nba_access_request_event_immutable();

-- History of the requests created before this release: their submission and decision.
insert into nba_access_request_event (request_id, action, from_status, to_status, remarks, actor, occurred_at)
select id, 'SUBMIT', null, 'PENDING', justification, created_by, created_at from nba_access_request;
insert into nba_access_request_event (request_id, action, from_status, to_status, remarks, actor, occurred_at)
select id, case status when 'APPROVED' then 'APPROVE' when 'REJECTED' then 'REJECT' else 'RETURN' end,
       'PENDING', status, decision_comment, decided_by, decided_at
from nba_access_request where status in ('APPROVED', 'REJECTED', 'RETURNED');

-- ---------- Access change log: external (portal) users (decision D7) --------------------------
alter table sec_access_change_log drop constraint ck_sec_access_change_subject;
alter table sec_access_change_log add constraint ck_sec_access_change_subject
    check (subject_type in ('USER', 'ROLE', 'EXTERNAL_USER'));

-- ---------- Grants ---------------------------------------------------------------------------
-- The Requestor attaches bulk request files (BRD 1.009) through the bulk upload framework.
insert into sec_role_permission (role_id, permission)
select r.id, 'BULK_PROCESS' from sec_role r
where r.code = 'UAM_REQUESTOR'
  and not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = 'BULK_PROCESS');

-- ---------- Behaviour switches: the implement-request flow is live -----------------------------
update sys_parameter
set param_value = 'false',
    description = 'Emergency path: when true, the System Administrator may create and edit roles directly on the Roles screen (audited, alert UAM_DIRECT_ROLE_EDIT); when false, a role changes only by implementing an approved group-profile request (PQ17)',
    updated_at = now(), updated_by = 'SYSTEM'
where param_key = 'UAM_DIRECT_ROLE_EDIT';

update sys_parameter
set param_value = 'false',
    description = 'When true, an approved group-profile or role-permission request applies at its last approval; when false it waits for the System Administrator to implement it (BRD-11 p.6; UQ03)',
    updated_at = now(), updated_by = 'SYSTEM'
where param_key = 'UAM_ROLE_APPLY_ON_APPROVAL';

-- ---------- Retention (design section 12): closed requests are reviewed, never deleted --------
insert into nba_retention_rule (record_type, statuses, years_online, years_archive, action, active,
                                description, created_at, created_by)
select 'ACCESS_REQUEST', 'CANCELLED,REJECTED', 5, 15, 'REVIEW', true,
       'User access requests cancelled or rejected (kept with the access change log)', now(), 'SYSTEM'
where not exists (select 1 from nba_retention_rule where record_type = 'ACCESS_REQUEST');
