-- =====================================================================================
-- iNXT BrokerVerse - V1061 User Access Maintenance (BRD-11): security schema extensions.
--   sec_user   + Windows ID, business unit, user level, password dates, forced change, last logout
--                (BRD 1.002.1.1.1, 1.003.1.1.2; UAM-NFR-13 to 15, 35, 36)
--   sec_role   + active flag, description, privilege level, deactivation stamp
--                (BRD 3.002.3 / 3.002.4; UAM-NFR-40). A deactivated role grants nothing.
--   sec_access_change_log  one row per changed attribute of a user or role, insert-only
--                (BRD 4.003.1, reports A-D "added / modified / deactivated by"; UAM-NFR-41)
--   sec_user_session       sign-in sessions by token id (jti): issued, last seen, ended, reason
--                (UAM-NFR-35 logout logging, "online" status UQ13, single session UQ09)
--   sec_password_history   previous password hashes (UAM-NFR-36, PASSWORD_HISTORY_COUNT)
--   Design: docs/architecture/USER_ACCESS_DESIGN.md sections 3 and 4.1. Subjects and actors are
--   user names or role codes by value (no foreign key), like audit_log, so the evidence survives
--   any later change of the user or role. V1062 (U1-A) widens the subject types (EXTERNAL_USER).
-- =====================================================================================

alter table sec_user add column windows_id varchar(50);
alter table sec_user add column business_unit_code varchar(40);
alter table sec_user add column user_level varchar(40);
alter table sec_user add column password_changed_at timestamptz;
alter table sec_user add column must_change_password boolean not null default false;
alter table sec_user add column last_logout_at timestamptz;
create unique index uq_sec_user_windows_id on sec_user (lower(windows_id)) where windows_id is not null;

alter table sec_role add column active boolean not null default true;
alter table sec_role add column description varchar(500);
alter table sec_role add column privilege_level varchar(10) not null default 'STANDARD';
alter table sec_role add column deactivated_at timestamptz;
alter table sec_role add column deactivated_by varchar(50);
alter table sec_role add constraint ck_sec_role_privilege_level
    check (privilege_level in ('LOW', 'STANDARD', 'HIGH', 'ADMIN'));
update sec_role set privilege_level = 'ADMIN' where code = 'SYSADMIN';

-- ---------- Access change log (insert-only, as audit_log in V26) -------------------------------
create table sec_access_change_log (
    id           bigint generated by default as identity primary key,
    occurred_at  timestamptz  not null,
    subject_type varchar(20)  not null,
    subject      varchar(50)  not null,
    activity     varchar(30)  not null,
    attribute    varchar(40)  not null,
    from_value   varchar(2000),
    to_value     varchar(2000),
    request_no   varchar(40),
    done_by      varchar(50)  not null,
    approved_by  varchar(50),
    constraint ck_sec_access_change_subject check (subject_type in ('USER', 'ROLE')),
    constraint ck_sec_access_change_activity check (activity in ('CREATE_USER', 'MODIFY_USER',
        'ROLES_CHANGED', 'DISABLE_USER', 'ENABLE_USER', 'UNLOCK', 'PASSWORD_RESET', 'CREATE_ROLE',
        'ROLE_PERMISSIONS', 'DEACTIVATE_ROLE', 'REACTIVATE_ROLE'))
);
create index ix_sec_access_change_subject on sec_access_change_log (subject_type, lower(subject), occurred_at);
create index ix_sec_access_change_time on sec_access_change_log (occurred_at);
create index ix_sec_access_change_request on sec_access_change_log (request_no) where request_no is not null;

create function sec_access_change_log_immutable() returns trigger language plpgsql as $$
begin
    raise exception 'sec_access_change_log rows are immutable; the access change log is insert-only';
end;
$$;

create trigger trg_sec_access_change_log_immutable
    before update or delete on sec_access_change_log
    for each row execute function sec_access_change_log_immutable();

create trigger trg_sec_access_change_log_no_truncate
    before truncate on sec_access_change_log
    for each statement execute function sec_access_change_log_immutable();

-- ---------- Sign-in sessions --------------------------------------------------------------------
create table sec_user_session (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    session_id   varchar(64)  not null,
    username     varchar(50)  not null,
    issued_at    timestamptz  not null,
    expires_at   timestamptz  not null,
    last_seen_at timestamptz  not null,
    ended_at     timestamptz,
    end_reason   varchar(20),
    constraint uq_sec_user_session unique (session_id),
    constraint ck_sec_user_session_reason check (end_reason is null or end_reason in
        ('LOGOUT', 'IDLE_TIMEOUT', 'EXPIRED', 'ADMIN_ENDED', 'LOCKED')),
    constraint ck_sec_user_session_ended check ((ended_at is null) = (end_reason is null))
);
create index ix_sec_user_session_user on sec_user_session (lower(username), issued_at desc);
create index ix_sec_user_session_open on sec_user_session (expires_at) where ended_at is null;

-- ---------- Password history --------------------------------------------------------------------
create table sec_password_history (
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null,
    password_hash varchar(100) not null,
    changed_at    timestamptz  not null
);
create index ix_sec_password_history_user on sec_password_history (lower(username), changed_at desc);
