-- =====================================================================================
-- iNXT BrokerVerse - V1065 User Access Maintenance (BRD-11): the controls of the business sign-off.
--   1. Authorisation limit on user access requests (the limit is changed only through a request).
--   2. Separation-of-duties rules: pairs of group profiles one user may not hold, maintained under
--      maker-checker and checked on every user request and bulk line.
--   3. Second approval of the security parameters: a change of a SECURITY parameter waits for an
--      approver other than the user who asked for it (the emergency path UAM_DIRECT_ROLE_EDIT too).
--   4. Dormant users: parameters of the daily deactivation job and its notices; deactivation reason.
--   5. External (portal) user requests are switched off by a parameter while no portal exists.
--   6. The user ID format in words, shown with the format check.
--   7. Grants: the Business Administrator maintains the rules; the holders of the enrolment right
--      (Business and System Administrator) upload bulk requests. The grants of the Information Security
--      Officer are in V1066 (applied when V1101 creates the role).
-- =====================================================================================

-- ---------- 1. Authorisation limit on requests -------------------------------------------------
alter table nba_access_request add column authorization_limit numeric(18, 2);

-- ---------- 2. Separation-of-duties rules ------------------------------------------------------
create table nba_sod_rule (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    rule_code       varchar(30)   not null unique,
    profile_a       varchar(40)   not null,
    profile_b       varchar(40)   not null,
    description     varchar(500)  not null,
    record_status   varchar(30)   not null default 'PENDING_AUTHORIZATION',
    pending_action  varchar(20)   not null default 'CREATE',
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_nba_sod_rule_status check (record_status in ('PENDING_AUTHORIZATION', 'ACTIVE', 'INACTIVE')),
    constraint ck_nba_sod_rule_action check (pending_action in ('CREATE', 'DEACTIVATE', 'NONE')),
    constraint ck_nba_sod_rule_pair check (profile_a <> profile_b)
);
create index ix_nba_sod_rule_status on nba_sod_rule (record_status);

-- ---------- 3. Pending change of a security parameter ------------------------------------------
alter table sys_parameter add column pending_value varchar(1000);
alter table sys_parameter add column pending_by varchar(50);
alter table sys_parameter add column pending_at timestamptz;

-- ---------- 4-6. Parameters ------------------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('UAM_DORMANT_DAYS', '90', 'INTEGER', 'SECURITY',
     'Days without a sign-in after which a user is deactivated by the daily dormant-user job; 0 = never', 0, 730,
     now(), 'SYSTEM'),
    ('UAM_DORMANT_NOTICE_DAYS', '7', 'INTEGER', 'SECURITY',
     'Days before the dormant-user deactivation on which the user is told to sign in; 0 = no notice', 0, 60,
     now(), 'SYSTEM'),
    ('UAM_EXTERNAL_USERS', 'false', 'BOOLEAN', 'SECURITY',
     'When true, access requests may be raised for external (portal) users; stays false while no portal is installed',
     null, null, now(), 'SYSTEM'),
    ('USER_ID_FORMAT_TEXT', 'a letter followed by nine digits, for example a013000196', 'STRING', 'SECURITY',
     'The user ID format in words, shown to the requester with the format check of USER_ID_PATTERN', null, null,
     now(), 'SYSTEM')
on conflict (param_key) do nothing;

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'UAM_DEACTIVATION_REASON', 'DORMANT', 'No sign-in for the dormancy period', 50, null, date '2020-01-01',
       'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
where not exists (select 1 from lov_value where type_code = 'UAM_DEACTIVATION_REASON' and code = 'DORMANT');

-- ---------- Notification events --------------------------------------------------------------
insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('UAM_DORMANT_WARNING', 'Account deactivation soon', 'USER_ACCESS',
     'You have not signed in for a long time; sign in before the date given or your account is deactivated', true, true, 680),
    ('UAM_DORMANT_DEACTIVATED', 'Dormant users deactivated', 'USER_ACCESS',
     'Users who had not signed in for the dormancy period were deactivated', true, false, 690),
    ('UAM_PARAMETER_TO_APPROVE', 'Security setting to approve', 'USER_ACCESS',
     'A change of a sign-in, password, session or access setting waits for your approval', true, true, 700),
    ('UAM_SOD_TO_AUTHORIZE', 'Separation-of-duties rule to authorise', 'USER_ACCESS',
     'A new or deactivated separation-of-duties rule waits for your authorisation', true, false, 710)
on conflict (code) do nothing;

-- ---------- Permissions (area and action class) and grants ------------------------------------
insert into sec_permission_action (permission, area, action)
values
    ('UAM_SOD_MAINTAIN', 'USER_ACCESS', 'AMEND'),
    ('UAM_SOD_AUTHORIZE', 'USER_ACCESS', 'APPROVE'),
    ('SECURITY_PARAMETER_APPROVE', 'ADMINISTRATION', 'APPROVE')
on conflict (permission, action) do nothing;

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values
    ('BUSINESS_ADMIN', 'UAM_SOD_MAINTAIN'), ('BUSINESS_ADMIN', 'BULK_PROCESS'),
    ('SYSADMIN', 'BULK_PROCESS')
) as g(role_code, permission) on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);
