-- =====================================================================================
-- iNXT BrokerVerse - V1071 Submitted Policies: sources, intake runs, the Submitted Masterlist and
-- its history, document extractions, the LAMD loan snapshot, the legacy status map and the user
-- scope (wave S1-A).
--   Requirements: docs/requirements/BDOI_SP_BRD_SPEC.md
--     BRIDSP-01 source register and intake runs (file hash blocks a second load)
--     BRIDSP-02 extraction proposals, saved to the masterlist only after confirmation
--     BRIDSP-03 manual entry and renewal tag with its source (rule or manual)
--     BRIDSP-04 one masterlist record per policy, segment and business type
--     BRIDSP-13 LAMD loan snapshot by PN
--     BRIDSP-28 user scope (segments, own records only)
--     BRIDSP-29 field history with its source
--     BRIDSP-33 migrated records with legacy reference and date received; legacy status map
--   Design: docs/architecture/SUBMITTED_POLICIES_DESIGN.md section 4.1. No foreign key to the
--   broking tables (insurer, client and account are plain codes and ARNs).
--   The source register and the legacy status map are shared by the companies.
-- =====================================================================================

create table sbm_source (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    code             varchar(30)   not null unique,
    name             varchar(120)  not null,
    segment          varchar(30),
    business_type    varchar(2)    check (business_type in ('NB', 'RB')),
    bulk_handler     varchar(40),
    format           varchar(20)   not null check (format in ('XLSX', 'CSV', 'DOCUMENT', 'MANUAL', 'FEED')),
    mandatory_fields varchar(500),
    active           boolean       not null default true,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);

create table sbm_intake_run (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    run_no         varchar(30)   not null unique,
    source_code    varchar(30)   not null,
    bulk_job_no    varchar(30),
    file_name      varchar(255),
    file_sha256    varchar(64),
    received       integer       not null default 0,
    created        integer       not null default 0,
    updated        integer       not null default 0,
    duplicate      integer       not null default 0,
    failed         integer       not null default 0,
    status         varchar(20)   not null check (status in ('OPEN', 'COMPLETED')),
    started_at     timestamptz   not null,
    finished_at    timestamptz,
    processing_run_no varchar(30),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_sbm_intake_run_job unique (company_id, bulk_job_no)
);
create index ix_sbm_intake_run_source on sbm_intake_run (company_id, source_code, started_at);

create table sbm_policy (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    sbm_no                    varchar(30)    not null unique,
    segment                   varchar(30)    not null,
    business_type             varchar(2)     not null check (business_type in ('NB', 'RB')),
    natural_key               varchar(80)    not null,
    source_code               varchar(30)    not null,
    intake_run_id             bigint         references sbm_intake_run (id),
    date_received             date           not null,
    renewal_month             varchar(7),
    -- loan
    pn_no                     varchar(40),
    loan_application_no       varchar(40),
    cif                       varchar(40),
    value_date                date,
    maturity_date             date,
    referring_branch          varchar(60),
    originating_unit          varchar(60),
    borrower_name             varchar(250),
    loan_status               varchar(20),
    amortised                 boolean        not null default false,
    -- assured
    assured_name              varchar(250)   not null,
    mailing_address           varchar(500),
    telephone                 varchar(40),
    mobile                    varchar(40),
    email                     varchar(150),
    bank_counterpart_email    varchar(150),
    -- policy
    insurer_code              varchar(30),
    policy_no                 varchar(60),
    inception_date            date,
    expiry_date               date           not null,
    coverage_days             integer,
    sum_insured               numeric(19, 2) check (sum_insured is null or sum_insured >= 0),
    total_premium             numeric(19, 2) check (total_premium is null or total_premium >= 0),
    currency                  varchar(3)     not null default 'PHP',
    -- risk
    unit_description          varchar(250),
    serial_no                 varchar(60),
    motor_no                  varchar(60),
    colour                    varchar(40),
    plate_no                  varchar(20),
    vehicle_type              varchar(40),
    vehicle_year              integer,
    property_location         varchar(500),
    occupancy                 varchar(120),
    mortgagee                 varchar(250),
    -- lists and flags
    ffy                       boolean        not null default false,
    employee_account          boolean        not null default false,
    no_touch                  boolean        not null default false,
    migrated                  boolean        not null default false,
    legacy_ref                varchar(60),
    has_documents             boolean        not null default false,
    -- outcome of the processing run
    classification            varchar(20)    check (classification in ('INFORCED', 'SUBMITTED')),
    bucket                    varchar(40),
    bucket_reason             varchar(40),
    ra_template               varchar(20)    check (ra_template in ('GENERIC', 'FFY')),
    renewal_tag               varchar(20)    check (renewal_tag in ('RENEWABLE', 'NON_RENEWABLE')),
    renewal_tag_source        varchar(10)    check (renewal_tag_source in ('RULE', 'MANUAL')),
    renewal_tag_reason        varchar(40),
    renewal_tagged_by         varchar(50),
    renewal_tagged_at         timestamptz,
    insurer_approval_required boolean        not null default false,
    fallout                   boolean        not null default false,
    fallout_reason            varchar(40),
    last_run_no               varchar(30),
    -- tracking
    handler_username          varchar(50),
    ao_username               varchar(50),
    conversion_status         varchar(40),
    opportunity_tag           varchar(40),
    adequacy_status           varchar(20),
    remarks                   varchar(1000),
    status                    varchar(30)    not null check (status in ('RECEIVED', 'VALIDATED', 'CLASSIFIED',
        'IN_REVIEW', 'FOR_RENEWAL', 'FOR_MANUAL_DISPOSITION', 'EXCLUDED', 'RENEWAL_IN_PROGRESS', 'PLACED',
        'BOOKED', 'NOT_RENEWED', 'CLOSED')),
    status_reason             varchar(250),
    -- renewal followed from the Renewal module and booking
    renewal_ref               varchar(40),
    renewal_arn               varchar(30),
    booked_invoice_no         varchar(40),
    booked_on                 date,
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_sbm_policy_key unique (company_id, segment, business_type, natural_key, expiry_date),
    constraint ck_sbm_policy_period check (inception_date is null or expiry_date > inception_date)
);
create index ix_sbm_policy_pn on sbm_policy (company_id, pn_no);
create index ix_sbm_policy_policy_no on sbm_policy (company_id, policy_no);
create index ix_sbm_policy_expiry on sbm_policy (company_id, expiry_date);
create index ix_sbm_policy_bucket on sbm_policy (company_id, bucket);
create index ix_sbm_policy_status on sbm_policy (company_id, status);
create index ix_sbm_policy_handler on sbm_policy (company_id, handler_username);
create index ix_sbm_policy_segment on sbm_policy (company_id, segment, status);
create index ix_sbm_policy_serial on sbm_policy (company_id, serial_no);
create index ix_sbm_policy_motor on sbm_policy (company_id, motor_no);
create index ix_sbm_policy_legacy on sbm_policy (company_id, legacy_ref);
create index ix_sbm_policy_arn on sbm_policy (renewal_arn);

create table sbm_policy_history (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    policy_id   bigint        not null references sbm_policy (id),
    field       varchar(40)   not null,
    old_value   varchar(1000),
    new_value   varchar(1000),
    source      varchar(20)   not null check (source in ('INTAKE', 'EXTRACTION', 'MANUAL', 'RUN', 'RENEWAL',
        'BOOKING', 'MIGRATION')),
    reference   varchar(40),
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create index ix_sbm_policy_history_policy on sbm_policy_history (policy_id, id);
create index ix_sbm_policy_history_time on sbm_policy_history (created_at);

create table sbm_extraction (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    extraction_no  varchar(30)   not null unique,
    policy_id      bigint        references sbm_policy (id),
    segment        varchar(30)   not null,
    business_type  varchar(2)    not null check (business_type in ('NB', 'RB')),
    attachment_id  bigint        not null,
    file_name      varchar(255)  not null,
    extractor      varchar(60)   not null,
    status         varchar(20)   not null check (status in ('PROPOSED', 'CONFIRMED', 'REJECTED', 'FAILED')),
    readable       boolean       not null,
    note           varchar(500),
    confirmed_by   varchar(50),
    confirmed_at   timestamptz,
    reject_reason  varchar(500),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_sbm_extraction_status on sbm_extraction (company_id, status, id);
create index ix_sbm_extraction_policy on sbm_extraction (policy_id);

create table sbm_extraction_field (
    extraction_id bigint        not null references sbm_extraction (id),
    field         varchar(30)   not null,
    value         varchar(500),
    confidence    numeric(5, 2),
    primary key (extraction_id, field)
);

create table sbm_lamd_loan (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    snapshot_date    date           not null,
    pn_no            varchar(40)    not null,
    borrower_name    varchar(250),
    loan_status      varchar(20)    not null,
    amortised        boolean        not null default false,
    maturity_date    date,
    originating_unit varchar(60),
    balance          numeric(19, 2),
    serial_no        varchar(60),
    motor_no         varchar(60),
    bulk_job_no      varchar(30),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_lamd_loan unique (company_id, snapshot_date, pn_no)
);
create index ix_sbm_lamd_loan_pn on sbm_lamd_loan (company_id, pn_no, snapshot_date);

create table sbm_status_map (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    legacy_status  varchar(60)   not null unique,
    status         varchar(30)   not null,
    bucket         varchar(40),
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);

create table sbm_user_scope (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    username          varchar(50)   not null,
    segments          varchar(200),
    own_records_only  boolean       not null default false,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_sbm_user_scope unique (company_id, username)
);

-- ---------- Source register (FRS section 9.3; layouts to be supplied by BDOI) --------------------
insert into sbm_source (code, name, segment, business_type, bulk_handler, format, mandatory_fields,
    created_at, created_by)
select s.code, s.name, s.segment, s.business_type, s.handler, s.format, s.mandatory, now(), 'SYSTEM'
from (values
    ('LFS_INSURANCE', 'LFS insurance report', 'CBG_MOTOR', 'NB', 'SBM_LFS_INSURANCE', 'XLSX', null),
    ('HLS_INSURANCE', 'HLS daily insurance report', 'CBG_FIRE', 'NB', 'SBM_HLS_INSURANCE', 'XLSX', null),
    ('CIU', 'CIU report', 'CBG_MOTOR', 'NB', 'SBM_CIU', 'XLSX', null),
    ('SPI', 'SPI consolidated list', null, null, 'SBM_SPI', 'XLSX', null),
    ('LOAN_BOOKING', 'Loan Booking Report', 'CBG_MOTOR', null, 'SBM_LOAN_BOOKING', 'XLSX', null),
    ('LAMD', 'LAMD loan report', null, null, 'SBM_LAMD', 'XLSX', null),
    ('IBG_LEASING_DOC', 'IBG / Leasing policy documents', 'NONCBG_CORPORATE', 'NB', null, 'DOCUMENT', null),
    ('IA_MASTERLIST', 'IA masterlist', 'CBG_MOTOR', null, 'SBM_IA_MASTERLIST', 'XLSX', null),
    ('MANUAL', 'Manual entry', null, null, null, 'MANUAL',
     'assuredName,insurerCode,policyNo,inceptionDate,expiryDate,sumInsured'),
    ('MIGRATION', 'Excel masterlist migration', null, null, 'SBM_MIGRATION', 'XLSX', null)
) as s(code, name, segment, business_type, handler, format, mandatory);

-- ---------- Legacy status map (FRS section 9.3; statuses of the Excel masterlists, SP SQ16) -----
insert into sbm_status_map (legacy_status, status, bucket, created_at, created_by)
values ('FOR RENEWAL', 'FOR_RENEWAL', 'FOR_RENEWAL', now(), 'SYSTEM'),
       ('RENEWED', 'CLOSED', null, now(), 'SYSTEM'),
       ('NOT FOR RENEWAL', 'EXCLUDED', 'NON_RENEWAL', now(), 'SYSTEM'),
       ('NO TOUCH', 'EXCLUDED', 'NO_TOUCH', now(), 'SYSTEM'),
       ('FFY', 'EXCLUDED', 'FFY', now(), 'SYSTEM'),
       ('RMU', 'EXCLUDED', 'RMU', now(), 'SYSTEM'),
       ('PENDING', 'VALIDATED', null, now(), 'SYSTEM'),
       ('FOR DISPOSITION', 'FOR_MANUAL_DISPOSITION', 'FOR_MANUAL_DISPOSITION', now(), 'SYSTEM'),
       ('SUBMITTED', 'VALIDATED', null, now(), 'SYSTEM');

-- ---------- Default data scope (BRIDSP-28) ------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('SBM_OWN_RECORDS_ROLES', 'MKT_AO', 'CODE_LIST', 'SUBMITTED',
     'Roles whose users see only the submitted policies they handle or whose renewal they own, unless a user scope says otherwise', null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
