-- =====================================================================================
-- iNXT BrokerVerse - V1072 Submitted Policies: rule sets and rules, processing runs and their
-- results, limit rules and limit checks (wave S1-B).
--   Requirements: docs/requirements/BDOI_SP_BRD_SPEC.md
--     BRIDSP-08     configurable sanitation, matching, classification and disposition criteria,
--                   versioned with maker and checker
--     BRIDSP-09     processing runs after intake, on schedule and on demand
--     BRIDSP-10     fallout with reason codes
--     BRIDSP-11..15 classification, buckets, RA template, non-renewal and inforced buckets
--     BRIDSP-16     limit rules and checks
--   Design: docs/architecture/SUBMITTED_POLICIES_DESIGN.md sections 3.2 and 4.2. The rule sets are
--   seeded per company by the seed data (V1970) until BDOI confirms their content (SP SQ04-SQ06).
-- =====================================================================================

create table sbm_rule_set (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    code             varchar(40)   not null,
    step             varchar(20)   not null check (step in ('SANITATION', 'MATCHING', 'CLASSIFICATION', 'DISPOSITION')),
    segment          varchar(30),
    business_type    varchar(2)    check (business_type in ('NB', 'RB')),
    version_no       integer       not null,
    status           varchar(20)   not null check (status in ('DRAFT', 'SUBMITTED', 'ACTIVE', 'RETIRED', 'REJECTED')),
    effective_from   date          not null,
    description      varchar(200),
    submitted_by     varchar(50),
    submitted_at     timestamptz,
    approved_by      varchar(50),
    approved_at      timestamptz,
    decision_remarks varchar(200),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_rule_set unique (company_id, code, version_no)
);
create index ix_sbm_rule_set_step on sbm_rule_set (company_id, step, status);

create table sbm_rule (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    rule_set_id            bigint        not null references sbm_rule_set (id),
    priority               integer       not null,
    name                   varchar(120)  not null,
    outcome_bucket         varchar(40),
    outcome_tag            varchar(20)   check (outcome_tag in ('RENEWABLE', 'NON_RENEWABLE')),
    outcome_classification varchar(20)   check (outcome_classification in ('INFORCED', 'SUBMITTED')),
    outcome_ra_template    varchar(20)   check (outcome_ra_template in ('GENERIC', 'FFY')),
    outcome_flag           varchar(20)   check (outcome_flag in ('FALLOUT', 'REVIEW')),
    reason_code            varchar(40),
    stop                   boolean       not null default true,
    active                 boolean       not null default true,
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_sbm_rule_priority unique (rule_set_id, priority)
);

create table sbm_rule_condition (
    rule_id   bigint        not null references sbm_rule (id),
    seq       integer       not null,
    field     varchar(40)   not null,
    operator  varchar(10)   not null check (operator in ('EQ', 'NE', 'IN', 'NOT_IN', 'GT', 'GTE', 'LT', 'LTE',
        'EMPTY', 'NOT_EMPTY')),
    value     varchar(500),
    primary key (rule_id, seq)
);

create table sbm_run (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    run_no        varchar(30)   not null unique,
    trigger_type  varchar(20)   not null check (trigger_type in ('INTAKE', 'SCHEDULED', 'MANUAL')),
    scope         varchar(250)  not null,
    started_at    timestamptz   not null,
    finished_at   timestamptz,
    total         integer       not null default 0,
    passed        integer       not null default 0,
    bucketed      integer       not null default 0,
    fallout       integer       not null default 0,
    overridden    integer       not null default 0,
    breaches      integer       not null default 0,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create index ix_sbm_run_company on sbm_run (company_id, started_at);

create table sbm_run_result (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    run_id           bigint        not null references sbm_run (id),
    policy_id        bigint        not null references sbm_policy (id),
    step             varchar(20)   not null check (step in ('SANITATION', 'MATCHING', 'CLASSIFICATION', 'DISPOSITION', 'LIMITS')),
    outcome          varchar(20)   not null check (outcome in ('PASSED', 'BUCKETED', 'FALLOUT', 'OVERRIDDEN')),
    bucket           varchar(40),
    reason_code      varchar(40),
    rule_id          bigint,
    rule_name        varchar(120),
    rule_set_code    varchar(40),
    rule_set_version integer,
    message          varchar(500),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_sbm_run_result_run on sbm_run_result (run_id, outcome);
create index ix_sbm_run_result_policy on sbm_run_result (policy_id, id);

create table sbm_limit_rule (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    insurer_code     varchar(30)    not null,
    segment          varchar(30),
    line             varchar(40),
    max_sum_insured  numeric(19, 2) check (max_sum_insured is null or max_sum_insured > 0),
    max_vehicle_age  integer        check (max_vehicle_age is null or max_vehicle_age >= 0),
    attribute        varchar(40),
    attribute_limit  varchar(120),
    description      varchar(250),
    record_status    varchar(30)    not null,
    authorized_by    varchar(50),
    authorized_at    timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_sbm_limit_rule_insurer on sbm_limit_rule (company_id, insurer_code);

create table sbm_limit_check (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    run_id         bigint        references sbm_run (id),
    policy_id      bigint        not null references sbm_policy (id),
    limit_rule_id  bigint        not null references sbm_limit_rule (id),
    attribute      varchar(40)   not null,
    limit_value    varchar(120)  not null,
    actual_value   varchar(120),
    breached       boolean       not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_sbm_limit_check_policy on sbm_limit_check (policy_id, id);
create index ix_sbm_limit_check_run on sbm_limit_check (run_id);
