-- =====================================================================================
-- iNXT BrokerVerse - V1075 Submitted Policies: handling-fee records and the No Touch billing
-- (wave S1-D).
--   Requirements: docs/requirements/BDOI_SP_BRD_SPEC.md BRIDSP-31 (handling-fee payments tagged in
--                 the Unapplied Payment List); Report List #164 (No Touch billing to insurers).
--   Design: docs/architecture/SUBMITTED_POLICIES_DESIGN.md sections 3.6, 3.7 and 4.4. The service
--   invoice type SERVICE_FEE_NO_TOUCH is a data row of the booking table of service invoice types
--   (no change to the booking tables).
-- =====================================================================================

create table sbm_handling_fee (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    fee_no            varchar(30)    not null unique,
    policy_id         bigint         references sbm_policy (id),
    pn_no             varchar(40),
    location_ref      varchar(60),
    amount            numeric(19, 2) not null check (amount > 0),
    currency          varchar(3)     not null default 'PHP',
    billing_date      date           not null,
    status            varchar(20)    not null check (status in ('BILLED', 'TAGGED', 'APPLIED', 'CANCELLED')),
    unapplied_ref     varchar(30),
    channel           varchar(20),
    ticket_ref        varchar(40),
    ticket_message    varchar(500),
    or_no             varchar(30),
    tagged_by         varchar(50),
    tagged_at         timestamptz,
    applied_at        timestamptz,
    cancel_reason     varchar(250),
    bulk_job_no       varchar(30),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_sbm_handling_fee_key check (pn_no is not null or location_ref is not null)
);
create index ix_sbm_handling_fee_pn on sbm_handling_fee (company_id, pn_no, status);
create index ix_sbm_handling_fee_location on sbm_handling_fee (company_id, location_ref, status);
create index ix_sbm_handling_fee_unapplied on sbm_handling_fee (unapplied_ref);

create table sbm_no_touch_batch (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    batch_no         varchar(30)    not null unique,
    insurer_code     varchar(30)    not null,
    period           varchar(7)     not null,
    status           varchar(20)    not null check (status in ('EXPORTED', 'RETURNED', 'BILLED')),
    line_count       integer        not null default 0,
    gross_fee        numeric(19, 2),
    vat              numeric(19, 2),
    wtax             numeric(19, 2),
    exported_file_id bigint,
    statement_file_id bigint,
    si_no            varchar(40),
    journal_batch_no varchar(40),
    returned_at      timestamptz,
    billed_at        timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_no_touch_batch unique (company_id, insurer_code, period)
);

create table sbm_no_touch_line (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    batch_id         bigint         not null references sbm_no_touch_batch (id),
    policy_id        bigint         not null references sbm_policy (id),
    sbm_no           varchar(30)    not null,
    pn_no            varchar(40),
    assured_name     varchar(250)   not null,
    policy_no        varchar(60),
    plate_no         varchar(20),
    sum_insured      numeric(19, 2),
    basic_premium    numeric(19, 2),
    gross_fee        numeric(19, 2),
    vat              numeric(19, 2),
    wtax             numeric(19, 2),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_no_touch_line unique (batch_id, policy_id)
);

-- Service invoice type of the No Touch service fee billed to the insurers (Report List #164).
insert into bkg_si_type (code, name, recipient, trigger_type, owner_permission, template_code, created_at, created_by)
select 'SERVICE_FEE_NO_TOUCH', 'Service fee of No Touch accounts', 'INSURER', 'MANUAL', 'SBM_HANDLING_FEE',
       'SERVICE_INVOICE_NOTE', now(), 'SYSTEM'
where not exists (select 1 from bkg_si_type where code = 'SERVICE_FEE_NO_TOUCH');
