-- =====================================================================================
-- iNXT BrokerVerse - V1074 Submitted Policies: renewal hand-offs, insurer rules, letter rules,
-- letters and print batches (wave S1-D).
--   Requirements: docs/requirements/BDOI_SP_BRD_SPEC.md
--     BRIDSP-22     letters by rule, e-mail, bank counterpart or print batch for the mail house
--     BRIDSP-23/25  expiry scan, hand-off to Renewal with the assigned insurer
--     BRIDSP-24/32  insurer acceptance watch, hold covers of unbooked accounts, re-assignment
--   Design: docs/architecture/SUBMITTED_POLICIES_DESIGN.md sections 3.5 and 4.4. The renewal of a
--   handed-over record belongs to the Renewal module (cross-BRD decision D2): sbm_renewal keeps
--   the hand-off and what Submitted Policies follows of it; sbm_letter keeps only the letters that
--   are not renewal letters.
-- =====================================================================================

create table sbm_renewal (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    company_id          bigint        not null references org_company (id),
    policy_id           bigint        not null unique references sbm_policy (id),
    handoff_status      varchar(20)   not null check (handoff_status in ('PENDING', 'HANDED_OFF', 'REFUSED')),
    manual              boolean       not null default false,
    renewal_ref         varchar(40),
    insurer_assigned    varchar(30),
    ra_template         varchar(20),
    arn                 varchar(30),
    hold_cover_on       date,
    insurer_accepted_on date,
    reassign_count      integer       not null default 0,
    outcome             varchar(20)   not null check (outcome in ('IN_PROGRESS', 'RENEWED', 'DECLINED', 'EXPIRED',
        'LOST')),
    decline_reason      varchar(250),
    handed_off_at       timestamptz   not null,
    message             varchar(500),
    alerted_on          date,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);
create index ix_sbm_renewal_status on sbm_renewal (company_id, handoff_status, outcome);
create index ix_sbm_renewal_arn on sbm_renewal (arn);

create table sbm_insurer_rule (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    segment           varchar(30)   not null,
    vehicle_type      varchar(40),
    occupancy         varchar(120),
    insurer_code      varchar(30)   not null,
    priority          integer       not null default 10,
    exclude_expiring  boolean       not null default false,
    description       varchar(250),
    record_status     varchar(30)   not null,
    authorized_by     varchar(50),
    authorized_at     timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create index ix_sbm_insurer_rule_segment on sbm_insurer_rule (company_id, segment, priority);

create table sbm_letter_rule (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    letter_type        varchar(30)   not null,
    segment            varchar(30),
    bucket             varchar(40),
    status             varchar(30),
    days_from_expiry   integer       not null,
    channel            varchar(20)   not null check (channel in ('EMAIL', 'PRINT', 'BANK_COUNTERPART')),
    template_code      varchar(40)   not null,
    description        varchar(250),
    record_status      varchar(30)   not null,
    authorized_by      varchar(50),
    authorized_at      timestamptz,
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50)
);

create table sbm_print_batch (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    company_id          bigint        not null references org_company (id),
    batch_no            varchar(30)   not null unique,
    source              varchar(20)   not null,
    letter_type         varchar(30)   not null,
    batch_date          date          not null,
    letter_count        integer       not null,
    merged_file_id      bigint,
    control_file_id     bigint,
    handed_to           varchar(120),
    handed_at           timestamptz,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);
create index ix_sbm_print_batch_date on sbm_print_batch (company_id, batch_date);

create table sbm_letter (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    letter_no        varchar(30)   not null unique,
    policy_id        bigint        not null references sbm_policy (id),
    rule_id          bigint        references sbm_letter_rule (id),
    letter_type      varchar(30)   not null,
    channel          varchar(20)   not null check (channel in ('EMAIL', 'PRINT', 'BANK_COUNTERPART')),
    status           varchar(20)   not null check (status in ('QUEUED', 'GENERATED', 'SENT', 'PRINTED', 'FAILED')),
    recipient        varchar(300),
    template_code    varchar(40)   not null,
    template_version integer,
    attachment_id    bigint,
    stored_file_id   bigint,
    message_id       bigint,
    print_batch_id   bigint        references sbm_print_batch (id),
    error            varchar(500),
    sent_at          timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_letter_rule unique (policy_id, rule_id)
);
create index ix_sbm_letter_status on sbm_letter (company_id, status, id);
create index ix_sbm_letter_policy on sbm_letter (policy_id);

-- ---------- Parameters of the hand-off (design 8) ------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('SBM_MANUAL_RENEWAL_SEGMENTS', 'NONCBG_RETAIL', 'CODE_LIST', 'SUBMITTED',
     'Segments whose renewal the Account Officer starts by hand with Renew with BDOI; the expiry scan leaves them out', null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
