-- =====================================================================================
-- iNXT BrokerVerse - V1073 Submitted Policies: policy reviews, IAAF with its links, Terms of
-- Reference, the IAAF and TOR approval matrices and the signatures of the approval levels
-- (wave S1-C).
--   Requirements: docs/requirements/BDOI_SP_BRD_SPEC.md
--     BRIDSP-05/06 reviews with number, date, adequacy and findings; one IAAF per policy with links
--     BRIDSP-07     IAAF approval matrix and signatures
--     BRIDSP-17..19 TOR, TSU approval matrix, hand-over to the Account Officer
--   Design: docs/architecture/SUBMITTED_POLICIES_DESIGN.md sections 3.3, 3.4 and 4.3. The matrices
--   are seed data (V1970) until BDOI supplies the levels and signatories (SP SQ07, SQ08).
-- =====================================================================================

create table sbm_iaaf (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    iaaf_no          varchar(30)   not null unique,
    policy_id        bigint        not null unique references sbm_policy (id),
    status           varchar(20)   not null check (status in ('DRAFT', 'FOR_APPROVAL', 'RETURNED', 'APPROVED',
        'ISSUED', 'CANCELLED')),
    current_level    integer       not null default 0,
    total_levels     integer       not null default 0,
    submitted_at     timestamptz,
    template_version integer,
    attachment_id    bigint,
    sent_to          varchar(300),
    sent_at          timestamptz,
    return_reason    varchar(500),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_sbm_iaaf_status on sbm_iaaf (company_id, status);

create table sbm_iaaf_link (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    iaaf_id            bigint        not null references sbm_iaaf (id),
    related_policy_id  bigint        not null references sbm_policy (id),
    relation           varchar(20)   not null check (relation in ('PREVIOUS_TERM', 'SAME_BORROWER', 'OTHER')),
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_sbm_iaaf_link unique (iaaf_id, related_policy_id)
);

create table sbm_iaaf_review (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    policy_id        bigint        not null references sbm_policy (id),
    iaaf_id          bigint        references sbm_iaaf (id),
    review_no        integer       not null,
    review_date      date          not null,
    reviewer         varchar(50)   not null,
    adequacy         varchar(20)   not null check (adequacy in ('ADEQUATE', 'WITH_FINDINGS')),
    findings         varchar(500),
    remarks          varchar(1000),
    sent_to          varchar(300),
    sent_at          timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_iaaf_review unique (policy_id, review_no)
);

create table sbm_tor (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    tor_no           varchar(30)   not null unique,
    policy_id        bigint        references sbm_policy (id),
    arn              varchar(30),
    breaches         varchar(2000) not null,
    proposed_terms   varchar(4000) not null,
    status           varchar(20)   not null check (status in ('DRAFT', 'FOR_APPROVAL', 'RETURNED', 'APPROVED',
        'RELEASED', 'CANCELLED')),
    current_level    integer       not null default 0,
    total_levels     integer       not null default 0,
    submitted_at     timestamptz,
    ao_username      varchar(50)   not null,
    attachment_id    bigint,
    approved_at      timestamptz,
    released_at      timestamptz,
    return_reason    varchar(500),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_sbm_tor_account check (policy_id is not null or arn is not null)
);
create index ix_sbm_tor_status on sbm_tor (company_id, status);
create index ix_sbm_tor_policy on sbm_tor (policy_id);

create table sbm_approval_matrix (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    document           varchar(10)    not null check (document in ('IAAF', 'TOR')),
    segment            varchar(30),
    tsi_from           numeric(19, 2) not null default 0,
    tsi_to             numeric(19, 2),
    level              integer        not null check (level between 1 and 9),
    permission         varchar(50)    not null,
    approver_username  varchar(50),
    signatory_title    varchar(120)   not null,
    record_status      varchar(30)    not null,
    authorized_by      varchar(50),
    authorized_at      timestamptz,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_sbm_approval_matrix_band check (tsi_to is null or tsi_to >= tsi_from)
);
create index ix_sbm_approval_matrix_doc on sbm_approval_matrix (company_id, document, level);

create table sbm_signature (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    document_type  varchar(10)   not null check (document_type in ('IAAF', 'TOR')),
    document_id    bigint        not null,
    level          integer       not null,
    signer         varchar(50)   not null,
    signer_name    varchar(150)  not null,
    position       varchar(120)  not null,
    signed_at      timestamptz   not null,
    method         varchar(10)   not null check (method in ('STAMPED', 'ESIG')),
    hash           varchar(64)   not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_sbm_signature_document on sbm_signature (document_type, document_id, level);
