-- =====================================================================================
-- iNXT BrokerVerse - V1077 Submitted Policies: loan files of the bank and the matching log
-- (FR-SP-035; BRIDSP-02).
--   SBM_LOAN_REPORT   the loan reports loaded as loan files - LAMD, LMS, LAD - in their order
--                     of precedence when two reports of the same day hold the same loan
--   sbm_lamd_loan     now a row of any loan file: the loan report, the loan application number
--                     (a row has a PN number or a loan application number), the branch and the
--                     segment of the loan
--   sbm_loan_match    one row per record processed: the loan file used (report, date, upload),
--                     the key that matched (PN number or loan application number) or the reason
--                     the record is unmatched, with the run and the time stamp
-- =====================================================================================
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('SBM_LOAN_REPORT', 'Loan report', 'Loan report of the bank loaded as a loan file, in its order of precedence', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM',
       now(), now(), 'SYSTEM'
from (values
    ('SBM_LOAN_REPORT', 'LAMD', 'LAMD', 10),
    ('SBM_LOAN_REPORT', 'LMS', 'LMS', 20),
    ('SBM_LOAN_REPORT', 'LAD', 'LAD', 30)
) as v(type_code, code, label, sort_order);

alter table sbm_lamd_loan add column loan_report varchar(10) not null default 'LAMD';
alter table sbm_lamd_loan add column loan_application_no varchar(40);
alter table sbm_lamd_loan add column branch varchar(60);
alter table sbm_lamd_loan add column segment varchar(30);
alter table sbm_lamd_loan alter column pn_no drop not null;
alter table sbm_lamd_loan add constraint ck_sbm_loan_key
    check (pn_no is not null or loan_application_no is not null);
alter table sbm_lamd_loan drop constraint uq_sbm_lamd_loan;
create unique index uq_sbm_loan_row on sbm_lamd_loan (company_id, loan_report, snapshot_date,
    coalesce(pn_no, ''), coalesce(loan_application_no, ''));
create index ix_sbm_loan_application on sbm_lamd_loan (company_id, loan_application_no, snapshot_date);

create table sbm_loan_match (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    run_id          bigint        not null references sbm_run (id),
    policy_id       bigint        not null references sbm_policy (id),
    matched_at      timestamptz   not null,
    outcome         varchar(10)   not null
        constraint ck_sbm_loan_match_outcome check (outcome in ('MATCHED', 'UNMATCHED')),
    key_used        varchar(20)
        constraint ck_sbm_loan_match_key check (key_used in ('PN', 'LOAN_APPLICATION')),
    loan_id         bigint references sbm_lamd_loan (id),
    loan_report     varchar(10),
    snapshot_date   date,
    bulk_job_no     varchar(30),
    reason          varchar(200),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_sbm_loan_match_run on sbm_loan_match (run_id, id);
create index ix_sbm_loan_match_policy on sbm_loan_match (policy_id, id);
