-- =====================================================================================
-- iNXT BrokerVerse - V1078 Submitted Policies: nominated package rates and renewal proposals
-- (FR-SP-066, 067; BRIDSP-18, 19).
--   SBM_PROPOSAL          creates the renewal proposals, edits the nominated rate with a reason
--                         and assigns the preferred insurer; the Team Lead releases or returns
--                         them (a proposal is released by someone other than its maker)
--   sbm_nominated_rate    rate per segment, vehicle classification (blank: every
--                         classification) and insurer, effective-dated, maker-checker
--   sbm_proposal_batch    a batch of proposals SBP-yyyy-nnnnnn
--   sbm_proposal          one proposal per record and version: default and chosen insurer, the
--                         nominated and the applied rate with the reason of a change, the
--                         premium, For Review / Released / Returned / Superseded
-- =====================================================================================
insert into sec_permission_action (permission, area, action)
values ('SBM_PROPOSAL', 'SUBMITTED_POLICIES', 'CREATE');

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values ('SBM_SANITATION', 'SBM_PROPOSAL'), ('SBM_TL', 'SBM_PROPOSAL'), ('MKT_AO', 'SBM_PROPOSAL'))
    as g(role_code, permission) on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);

create table sbm_nominated_rate (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    segment         varchar(30)    not null,
    vehicle_type    varchar(40),
    insurer_code    varchar(30)    not null,
    rate            numeric(9, 6)  not null
        constraint ck_sbm_nominated_rate check (rate > 0 and rate <= 100),
    effective_from  date           not null,
    effective_to    date,
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_sbm_nominated_rate_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_sbm_nominated_rate on sbm_nominated_rate (company_id, segment, insurer_code);

create table sbm_proposal_batch (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    company_id  bigint        not null references org_company (id),
    batch_no    varchar(30)   not null unique,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create index ix_sbm_proposal_batch on sbm_proposal_batch (company_id, id);

create table sbm_proposal (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    batch_id         bigint         not null references sbm_proposal_batch (id),
    policy_id        bigint         not null references sbm_policy (id),
    version_no       integer        not null,
    default_insurer  varchar(30),
    insurer_code     varchar(30)    not null,
    nominated_rate   numeric(9, 6),
    applied_rate     numeric(9, 6)  not null,
    rate_reason      varchar(250),
    sum_insured      numeric(19, 2),
    premium          numeric(19, 2),
    status           varchar(20)    not null
        constraint ck_sbm_proposal_status check (status in ('FOR_REVIEW', 'RELEASED', 'RETURNED',
            'SUPERSEDED')),
    return_reason    varchar(250),
    released_by      varchar(50),
    released_at      timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_sbm_proposal_version unique (policy_id, version_no)
);
create index ix_sbm_proposal_batch_id on sbm_proposal (batch_id, id);
