-- =====================================================================================
-- iNXT BrokerVerse - V1085 Data Migration: the legacy archive (records and their documents) and
-- the append-only access log of the Legacy Inquiry (DATA_MIGRATION_DESIGN section 16; BRID 11.1),
-- with their retention rules (5 years online, 15 years archive).
--   Documents of an archive record are attachments of type LEGACY_DOCUMENT (V1080) linked to the
--   record (entity type MigArchiveRecord); their SHA-256 is kept on the attachment.
-- =====================================================================================

create table mig_archive_record (
    id               bigint generated by default as identity primary key,
    company_id       bigint         not null references org_company (id),
    source_system    varchar(10)    not null,
    record_type      varchar(20)    not null,
    legacy_key       varchar(80)    not null,
    client_key       varchar(30),
    client_name      varchar(250),
    policy_no        varchar(60),
    invoice_no       varchar(40),
    receipt_no       varchar(40),
    claim_no         varchar(40),
    document_date    date           not null,
    period_from      date,
    period_to        date,
    currency         varchar(3),
    amount           numeric(19, 2),
    status           varchar(40),
    summary          jsonb,
    batch_id         bigint         not null references mig_batch (id),
    row_hash         varchar(64)    not null,
    document_count   integer        not null default 0,
    rolled_back      boolean        not null default false,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    constraint uq_mig_archive_record unique (company_id, source_system, record_type, legacy_key),
    constraint ck_mig_archive_record_type check (record_type in ('CLIENT', 'POLICY', 'INVOICE', 'RECEIPT',
        'REMITTANCE', 'ENDORSEMENT', 'CLAIM', 'GL_JOURNAL', 'RENEWAL_ADVICE', 'LETTER', 'OTHER'))
);
create index ix_mig_archive_client on mig_archive_record (company_id, client_key);
create index ix_mig_archive_client_name on mig_archive_record (company_id, lower(client_name));
create index ix_mig_archive_policy on mig_archive_record (company_id, policy_no);
create index ix_mig_archive_invoice on mig_archive_record (company_id, invoice_no);
create index ix_mig_archive_receipt on mig_archive_record (company_id, receipt_no);
create index ix_mig_archive_claim on mig_archive_record (company_id, claim_no);
create index ix_mig_archive_date on mig_archive_record (company_id, document_date);

create table mig_access_log (
    id              bigint generated by default as identity primary key,
    company_id      bigint         not null references org_company (id),
    username        varchar(50)    not null,
    accessed_at     timestamptz    not null,
    source_address  varchar(60),
    action          varchar(10)    not null,
    criteria        varchar(1000),
    record_keys     varchar(2000),
    result_count    integer        not null default 0,
    reason_code     varchar(40),
    reason_text     varchar(500),
    constraint ck_mig_access_log_action check (action in ('SEARCH', 'VIEW', 'DOWNLOAD', 'EXPORT'))
);
create index ix_mig_access_log_user on mig_access_log (username, accessed_at);
create index ix_mig_access_log_time on mig_access_log (company_id, accessed_at);

-- The access log is append-only: no update and no delete, even through the application.
create or replace function mig_access_log_append_only() returns trigger as $$
begin
    raise exception 'The legacy access log cannot be changed or deleted';
end;
$$ language plpgsql;

create trigger trg_mig_access_log_append_only
    before update or delete on mig_access_log
    for each row execute function mig_access_log_append_only();

-- Retention (umbrella requirement: 5 years online, 15 years archive).
insert into nba_retention_rule (record_type, statuses, years_online, years_archive, action, active,
                                description, created_at, created_by)
values ('LEGACY_ARCHIVE', 'ALL', 5, 15, 'REVIEW', true,
        'Legacy records and documents kept in the BIBS archive after decommissioning', now(), 'SYSTEM'),
       ('LEGACY_ACCESS_LOG', 'ALL', 5, 15, 'REVIEW', true,
        'Access log of the legacy archive', now(), 'SYSTEM')
on conflict (record_type, statuses) do nothing;
