-- =====================================================================================
-- iNXT BrokerVerse - V1083 Data Migration: batches, run log, map versions used, the legacy key
-- cross-reference, client matching, the renewal advices already sent and their resubmissions
-- (DATA_MIGRATION_DESIGN sections 9, 10, 11 and 15.1; BRID 1.1b, 2.1, 12.1).
-- =====================================================================================

create table mig_batch (
    id                    bigint generated by default as identity primary key,
    version               bigint        not null default 0,
    company_id            bigint        not null references org_company (id),
    batch_no              varchar(20)   not null unique,
    object_code           varchar(10)   not null references mig_data_object (code),
    environment_class     varchar(20)   not null,
    cutover_plan_id       bigint,
    mode                  varchar(10)   not null,
    parent_batch_id       bigint        references mig_batch (id),
    status                varchar(24)   not null,
    staged_count          integer       not null default 0,
    valid_count           integer       not null default 0,
    warning_count         integer       not null default 0,
    invalid_count         integer       not null default 0,
    loaded_count          integer       not null default 0,
    skipped_count         integer       not null default 0,
    rejected_count        integer       not null default 0,
    excluded_count        integer       not null default 0,
    waived_count          integer       not null default 0,
    error_rate            numeric(9, 4),
    unmapped_count        integer       not null default 0,
    review_count          integer       not null default 0,
    validated_by          varchar(50),
    validated_at          timestamptz,
    load_approved_by      varchar(50),
    load_approved_at      timestamptz,
    loaded_by             varchar(50),
    started_at            timestamptz,
    ended_at              timestamptz,
    signed_off_at         timestamptz,
    rollback_reason       varchar(1000),
    rollback_requested_by varchar(50),
    rollback_requested_at timestamptz,
    rollback_decided_by   varchar(50),
    rollback_decided_at   timestamptz,
    rollback_round        integer       not null default 0,
    purge_due_on          date,
    purged_at             timestamptz,
    created_at            timestamptz   not null,
    created_by            varchar(50)   not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint ck_mig_batch_mode check (mode in ('FULL', 'DELTA', 'RERUN')),
    constraint ck_mig_batch_status check (status in ('PLANNED', 'VALIDATED', 'APPROVED', 'LOADING', 'LOADED',
        'LOADED_WITH_REJECTS', 'FAILED', 'RECONCILED', 'SIGNED_OFF', 'ROLLBACK_REQUESTED', 'ROLLING_BACK', 'ROLLED_BACK'))
);
create index ix_mig_batch_object on mig_batch (company_id, object_code, status);

create table mig_batch_extract (
    batch_id    bigint not null references mig_batch (id),
    extract_id  bigint not null references mig_extract (id),
    primary key (batch_id, extract_id)
);

create table mig_batch_log (
    id          bigint generated by default as identity primary key,
    batch_id    bigint        not null references mig_batch (id),
    step        varchar(12)   not null,
    level       varchar(8)    not null,
    message     varchar(2000) not null,
    counts      varchar(500),
    logged_by   varchar(50)   not null,
    logged_at   timestamptz   not null,
    constraint ck_mig_batch_log_step check (step in ('PLAN', 'VALIDATE', 'MATCH', 'APPROVE', 'LOAD', 'RECONCILE',
        'SIGNOFF', 'ROLLBACK', 'PURGE', 'RERUN')),
    constraint ck_mig_batch_log_level check (level in ('INFO', 'WARN', 'ERROR'))
);
create index ix_mig_batch_log_batch on mig_batch_log (batch_id, id);

create table mig_batch_map_version (
    batch_id    bigint       not null references mig_batch (id),
    set_code    varchar(60)  not null,
    version_no  integer      not null,
    primary key (batch_id, set_code)
);

create table mig_key_xref (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    source_system  varchar(10)   not null,
    object_code    varchar(10)   not null,
    legacy_key     varchar(200)  not null,
    target_entity  varchar(60)   not null,
    target_id      bigint,
    target_code    varchar(80),
    target_version bigint,
    batch_id       bigint        not null references mig_batch (id),
    row_hash       varchar(64)   not null,
    loaded_at      timestamptz   not null,
    rolled_back_at timestamptz,
    constraint uq_mig_key_xref unique (company_id, source_system, object_code, legacy_key)
);
create index ix_mig_key_xref_target on mig_key_xref (target_entity, target_code);
create index ix_mig_key_xref_batch on mig_key_xref (batch_id);

create table mig_client_match (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    batch_id        bigint        not null references mig_batch (id),
    cluster_no      integer       not null,
    left_row_id     bigint        not null,
    left_key        varchar(200)  not null,
    right_row_id    bigint,
    right_key       varchar(200),
    right_client_code varchar(30),
    score           integer       not null,
    matched_keys    varchar(200)  not null,
    decision        varchar(20)   not null,
    survivor_key    varchar(200),
    lost_values     text,
    decided_by      varchar(50),
    decided_at      timestamptz,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_mig_client_match_decision check (decision in ('AUTO_MERGE', 'REVIEW', 'MERGE', 'KEEP_SEPARATE'))
);
create index ix_mig_client_match_batch on mig_client_match (batch_id, decision);

create table mig_ra_sent (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    legacy_policy_ref varchar(60)   not null,
    account_arn       varchar(30),
    cover_no          varchar(40)   not null,
    expiry_date       date          not null,
    ra_sent_date      date          not null,
    ra_ref            varchar(30),
    ra_channel        varchar(10)   not null,
    sent_to           varchar(250),
    proposed_insurer  varchar(30),
    currency          varchar(3),
    proposed_premium  numeric(19, 2),
    sent_by           varchar(50),
    tracker_name      varchar(120)  not null,
    remarks           varchar(500),
    batch_id          bigint        not null references mig_batch (id),
    stage_row_id      bigint,
    rolled_back       boolean       not null default false,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_mig_ra_sent_channel check (ra_channel in ('EMAIL', 'COURIER', 'HAND', 'OTHER'))
);
create unique index uq_mig_ra_sent_live on mig_ra_sent (company_id, legacy_policy_ref) where not rolled_back;

create table mig_resubmission (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    resubmission_no varchar(20)   not null unique,
    object_code     varchar(10)   not null references mig_data_object (code),
    parent_batch_id bigint        not null references mig_batch (id),
    extract_id      bigint        not null references mig_extract (id),
    rerun_batch_id  bigint        references mig_batch (id),
    status          varchar(12)   not null,
    corrected_rows  integer       not null default 0,
    prepared_by     varchar(50)   not null,
    prepared_at     timestamptz   not null,
    decided_by      varchar(50),
    decided_at      timestamptz,
    decision_note   varchar(1000),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_mig_resubmission_status check (status in ('PREPARED', 'APPROVED', 'RETURNED'))
);
