-- =====================================================================================
-- iNXT BrokerVerse - V1084 Data Migration: reconciliation runs and lines, sign-offs of the gates
-- G1-G7, cutover plans, tasks, go / no-go criteria and decisions, the run-off tracker, the
-- decommissioning checklists and the FY2027 true-ups (DATA_MIGRATION_DESIGN sections 12, 13, 15.2,
-- 17; BRID 1.1a, 1.1b, 12.1). None of these tables is purged with the staging data.
-- =====================================================================================

create table mig_recon_run (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    run_no        varchar(20)   not null unique,
    batch_id      bigint        references mig_batch (id),
    trueup_id     bigint,
    object_code   varchar(10)   not null,
    as_of         date          not null,
    status        varchar(12)   not null,
    break_count   integer       not null default 0,
    run_by        varchar(50)   not null,
    run_at        timestamptz   not null,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_mig_recon_run_status check (status in ('MATCHED', 'BREAKS', 'EXPLAINED', 'SIGNED'))
);
create index ix_mig_recon_run_batch on mig_recon_run (batch_id, id);

create table mig_recon_line (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    run_id           bigint         not null references mig_recon_run (id),
    level            varchar(4)     not null,
    measure          varchar(200)   not null,
    currency         varchar(3),
    source_value     numeric(21, 2),
    staged_value     numeric(21, 2),
    target_value     numeric(21, 2),
    difference       numeric(21, 2),
    tolerance        numeric(21, 2)  not null default 0,
    status           varchar(12)    not null,
    detail           varchar(1000),
    break_reason     varchar(40),
    explanation      varchar(1000),
    explained_by     varchar(50),
    explained_at     timestamptz,
    approved_by      varchar(50),
    approved_at      timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_mig_recon_line_level check (level in ('L1', 'L2', 'L3', 'L4', 'L5', 'TU')),
    constraint ck_mig_recon_line_status check (status in ('MATCHED', 'BREAK', 'EXPLAINED'))
);
create index ix_mig_recon_line_run on mig_recon_line (run_id, level);

create table mig_signoff (
    id              bigint generated by default as identity primary key,
    company_id      bigint        not null references org_company (id),
    object_code     varchar(10)   not null,
    batch_id        bigint        references mig_batch (id),
    cutover_plan_id bigint,
    gate            varchar(4)    not null,
    role_code       varchar(40)   not null,
    username        varchar(50)   not null,
    decision        varchar(10)   not null,
    comment         varchar(2000),
    evidence_file_id bigint,
    evidence_name   varchar(255),
    signed_at       timestamptz   not null,
    constraint ck_mig_signoff_gate check (gate in ('G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7')),
    constraint ck_mig_signoff_decision check (decision in ('APPROVED', 'REJECTED'))
);
create index ix_mig_signoff_object on mig_signoff (company_id, object_code, gate);
create index ix_mig_signoff_batch on mig_signoff (batch_id, gate);

create table mig_cutover_plan (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    plan_no         varchar(20)   not null unique,
    name            varchar(120)  not null,
    kind            varchar(20)   not null,
    mock_no         integer,
    environment     varchar(20)   not null,
    go_live_date    date          not null,
    freeze_start    timestamp,
    freeze_end      timestamp,
    status          varchar(12)   not null,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_mig_cutover_plan_kind check (kind in ('MOCK', 'DRESS_REHEARSAL', 'PRODUCTION')),
    constraint ck_mig_cutover_plan_status check (status in ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'GO', 'NO_GO'))
);

create table mig_cutover_task (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    plan_id         bigint        not null references mig_cutover_plan (id),
    seq             integer       not null,
    phase           varchar(40)   not null,
    task            varchar(300)  not null,
    owner_role      varchar(60)   not null,
    object_code     varchar(10),
    depends_on      varchar(100),
    planned_start   timestamp,
    planned_end     timestamp,
    actual_start    timestamp,
    actual_end      timestamp,
    status          varchar(12)   not null,
    remarks         varchar(1000),
    evidence_file_id bigint,
    evidence_name   varchar(255),
    updated_at      timestamptz,
    updated_by      varchar(50),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    constraint uq_mig_cutover_task unique (plan_id, seq),
    constraint ck_mig_cutover_task_status check (status in ('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'BLOCKED', 'SKIPPED'))
);

create table mig_gonogo_criterion (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    plan_id         bigint        not null references mig_cutover_plan (id),
    criterion_no    integer       not null,
    name            varchar(200)  not null,
    threshold       varchar(200)  not null,
    measure         varchar(30)   not null,
    measured_value  varchar(200),
    met             boolean,
    manual_note     varchar(1000),
    measured_by     varchar(50),
    measured_at     timestamptz,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_mig_gonogo_criterion unique (plan_id, criterion_no)
);

create table mig_gonogo_decision (
    id              bigint generated by default as identity primary key,
    plan_id         bigint        not null references mig_cutover_plan (id),
    decision        varchar(6)    not null,
    comment         varchar(2000),
    criteria_met    integer       not null,
    criteria_total  integer       not null,
    decided_by      varchar(50)   not null,
    decided_at      timestamptz   not null,
    constraint ck_mig_gonogo_decision check (decision in ('GO', 'NO_GO'))
);

create table mig_runoff_cohort (
    id               bigint generated by default as identity primary key,
    company_id       bigint         not null references org_company (id),
    snapshot_date    date           not null,
    expiry_month     date           not null,
    source_system    varchar(10)    not null,
    headers_in_force integer        not null,
    premium_in_force numeric(19, 2) not null,
    renewed          integer        not null,
    not_renewed      integer        not null,
    lapsed           integer        not null,
    still_open       integer        not null,
    created_at       timestamptz    not null,
    constraint uq_mig_runoff_cohort unique (company_id, snapshot_date, expiry_month, source_system)
);

create table mig_decommission_item (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    system_code     varchar(10)   not null,
    milestone       varchar(10)   not null,
    criterion       varchar(40)   not null,
    name            varchar(120)  not null,
    description     varchar(500)  not null,
    evidence        varchar(1000),
    status          varchar(12)   not null,
    signed_by       varchar(50),
    signed_at       timestamptz,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_mig_decommission_item unique (company_id, system_code, milestone, criterion),
    constraint ck_mig_decommission_milestone check (milestone in ('SYSTEM', 'CONTEXT')),
    constraint ck_mig_decommission_status check (status in ('OPEN', 'MET', 'SIGNED', 'NOT_APPLICABLE'))
);

create table mig_trueup (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    trueup_no        varchar(2)    not null,
    reference        varchar(20)   not null unique,
    as_of            date          not null,
    status           varchar(12)   not null,
    batch_id         bigint        references mig_batch (id),
    tb_batch_id      bigint        references mig_batch (id),
    journals_posted  integer       not null default 0,
    items_adjusted   integer       not null default 0,
    prepared_by      varchar(50)   not null,
    prepared_at      timestamptz   not null,
    approved_by      varchar(50),
    approved_at      timestamptz,
    posted_at        timestamptz,
    recon_run_id     bigint,
    signed_by        varchar(50),
    signed_at        timestamptz,
    period_reopen_log varchar(2000),
    remarks          varchar(1000),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_mig_trueup unique (company_id, trueup_no),
    constraint ck_mig_trueup_status check (status in ('PREPARED', 'FOR_APPROVAL', 'APPROVED', 'POSTED', 'RECONCILED', 'SIGNED'))
);
