-- =====================================================================================
-- iNXT BrokerVerse - V1086 Legacy invoices in the Operations ledger (Data Migration BRD-13,
-- wave DM1-A; docs/architecture/DATA_MIGRATION_DESIGN.md sections 14.1, 14.2 and 14.5).
-- The opsledger range V760-V763 is full, hence the Data Migration number.
--   ops_invoice.origin             BIBS (booked in BIBS) or MIGRATED (open legacy invoice, F01)
--   ops_invoice.source_system      legacy source system (EBIX, QPS)
--   ops_invoice.legacy_ref         legacy policy reference (cover no. and version)
--   ops_invoice.migration_batch    batch that loaded the invoice (rollback per batch)
--   ops_invoice.ledger_context     NEW, or LEGACY for a legacy invoice and every invoice whose
--                                  family root is a legacy invoice (postings go to the legacy
--                                  control accounts with the LG_ components)
--   ops_invoice.legacy_invoice_no  the invoice number in the source system (always kept)
--   feed_source MIGRATION          invoices created by the legacy invoice intake
--   movements LEGACY_PAID, LEGACY_REMITTED, LEGACY_ADJUSTED and LEGACY_WRITTEN_OFF bring the
--   component balances to the open position at cut-over
--   ops_invoice_origin_snapshot    the frozen original values of a legacy invoice (never updated)
-- =====================================================================================

alter table ops_invoice add column origin varchar(10) not null default 'BIBS';
alter table ops_invoice add column source_system varchar(10);
alter table ops_invoice add column legacy_ref varchar(80);
alter table ops_invoice add column migration_batch varchar(20);
alter table ops_invoice add column ledger_context varchar(10) not null default 'NEW';
alter table ops_invoice add column legacy_invoice_no varchar(40);
alter table ops_invoice add constraint ck_ops_invoice_origin check (origin in ('BIBS', 'MIGRATED'));
alter table ops_invoice add constraint ck_ops_invoice_ledger_context check (ledger_context in ('NEW', 'LEGACY'));
alter table ops_invoice add constraint ck_ops_invoice_origin_ref
    check (origin = 'BIBS' or (source_system is not null and legacy_invoice_no is not null
                               and ledger_context = 'LEGACY'));
alter table ops_invoice add constraint ck_ops_invoice_feed_source
    check (feed_source in ('EVENT', 'REPLAY', 'MIGRATION'));
create index ix_ops_invoice_origin on ops_invoice (company_id, origin);
create index ix_ops_invoice_legacy_no on ops_invoice (legacy_invoice_no) where legacy_invoice_no is not null;

alter table ops_invoice_movement drop constraint ck_ops_invoice_movement_type;
alter table ops_invoice_movement add constraint ck_ops_invoice_movement_type check (movement_type in (
    'BOOKED', 'APPLIED', 'UNAPPLIED', 'REMITTED', 'ADJUSTED', 'WRITE_OFF', 'DP_REVERSAL',
    'CWT_RECLASS', 'MIN_BAL', 'CORRECTION', 'LEGACY_PAID', 'LEGACY_REMITTED', 'LEGACY_ADJUSTED',
    'LEGACY_WRITTEN_OFF'));

create table ops_invoice_origin_snapshot (
    id                        bigint generated by default as identity primary key,
    invoice_id                bigint         not null unique references ops_invoice (id),
    company_id                bigint         not null references org_company (id),
    source_system             varchar(10)    not null,
    legacy_invoice_no         varchar(40)    not null,
    legacy_ref                varchar(80),
    legacy_service_invoice_no varchar(40),
    invoice_date              date           not null,
    due_date                  date,
    currency                  varchar(3)     not null,
    gross_premium             numeric(19, 2) not null,
    commission                numeric(19, 2) not null,
    vat_on_commission         numeric(19, 2) not null,
    commission_realised       numeric(19, 2) not null default 0,
    deferred_vat_open         numeric(19, 2) not null default 0,
    open_balance_mode         boolean        not null default false,
    shares                    varchar(500)   not null,
    migration_batch           varchar(20)    not null,
    taken_at                  timestamptz    not null,
    taken_by                  varchar(50)    not null
);

create table ops_invoice_origin_line (
    snapshot_id   bigint         not null references ops_invoice_origin_snapshot (id),
    line_index    integer        not null,
    component     varchar(20)    not null,
    booked        numeric(19, 2) not null,
    adjusted      numeric(19, 2) not null,
    paid          numeric(19, 2) not null,
    remitted      numeric(19, 2) not null,
    written_off   numeric(19, 2) not null,
    open_balance  numeric(19, 2) not null,
    primary key (snapshot_id, line_index)
);
