-- =====================================================================================
-- iNXT BrokerVerse - V1087 Legacy ledger context of the GL-SL reconciliation and the legacy
-- trial balances (Data Migration BRD-13, wave DM1-A; docs/architecture/DATA_MIGRATION_DESIGN.md
-- sections 14.2 and 17.7). The acsl range V890-V899 is full, hence the Data Migration number.
--   acsl_glsl_control.ledger_context  ANY (default), NEW or LEGACY: an OPS_LEDGER control account
--                                     reconciles to the invoices of that ledger context, so the
--                                     legacy control accounts (1215.x) reconcile to the open legacy
--                                     invoices and the new ones (1210.x) to the invoices of BIBS
--   mig_tb_line                       the legacy trial balances loaded by object G01: the
--                                     provisional opening and each true-up version (TU1-TU3, FINAL),
--                                     mapped to the BIBS accounts, for the true-up reconciliation
-- =====================================================================================

alter table acsl_glsl_control add column ledger_context varchar(10) not null default 'ANY';
alter table acsl_glsl_control add constraint ck_acsl_glsl_ledger_context
    check (ledger_context in ('ANY', 'NEW', 'LEGACY'));

create table mig_tb_line (
    id                  bigint generated by default as identity primary key,
    company_id          bigint         not null references org_company (id),
    batch_id            bigint         not null references mig_batch (id),
    tb_version          varchar(12)    not null,
    as_of               date           not null,
    branch_id           bigint         not null references org_branch (id),
    currency            varchar(3)     not null,
    legacy_account_code varchar(30)    not null,
    account_code        varchar(30)    not null,
    cost_center         varchar(20),
    debit_fc            numeric(19, 2) not null,
    credit_fc           numeric(19, 2) not null,
    debit_php           numeric(19, 2) not null,
    credit_php          numeric(19, 2) not null,
    rolled_back_at      timestamptz,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    constraint ck_mig_tb_version check (tb_version in ('PROVISIONAL', 'TU1', 'TU2', 'TU3', 'FINAL'))
);
create index ix_mig_tb_line_version on mig_tb_line (company_id, tb_version, branch_id, currency);
