-- =====================================================================================
-- iNXT BrokerVerse - V1082 Data Migration: source extracts with their control totals, staged
-- rows and data-quality issues (DATA_MIGRATION_DESIGN sections 5, 6 and 8; BRID 1.1b).
--   The payload columns are purged within MIG_STAGING_RETENTION_DAYS of the batch sign-off; the
--   counts, hashes and control totals of mig_extract stay as reconciliation evidence. The extract
--   files are kept in the file store (record class MIGRATION_EXTRACT, 5-day lifecycle).
-- =====================================================================================

create table mig_extract (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    extract_no       varchar(20)   not null unique,
    object_code      varchar(10)   not null references mig_data_object (code),
    layout_code      varchar(10)   not null,
    layout_version   integer       not null,
    source_system    varchar(10)   not null,
    as_of            timestamp     not null,
    sequence_no      integer       not null,
    mode             varchar(10)   not null,
    file_name        varchar(255)  not null,
    control_file_name varchar(255),
    stored_file_id   bigint,
    control_file_id  bigint,
    sha256           varchar(64)   not null,
    extracted_at     timestamp,
    extracted_by     varchar(60),
    declared_rows    integer,
    parsed_rows      integer       not null default 0,
    staged_rows      integer       not null default 0,
    control_totals   text,
    hash_total       varchar(40),
    masked           boolean       not null default false,
    status           varchar(12)   not null,
    reject_code      varchar(40),
    reject_message   varchar(2000),
    received_by      varchar(50)   not null,
    received_at      timestamptz   not null,
    checked_at       timestamptz,
    purged_at        timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_mig_extract_status check (status in ('RECEIVED', 'CHECKED', 'REJECTED', 'STAGED', 'PURGED')),
    constraint ck_mig_extract_mode check (mode in ('FULL', 'DELTA'))
);
create index ix_mig_extract_object on mig_extract (company_id, object_code, status);
create index ix_mig_extract_sha on mig_extract (object_code, sha256);

create table mig_stage_row (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    extract_id       bigint        not null references mig_extract (id),
    object_code      varchar(10)   not null,
    layout_code      varchar(10)   not null,
    row_no           integer       not null,
    legacy_key       varchar(200)  not null,
    raw_payload      jsonb,
    mapped_payload   jsonb,
    row_hash         varchar(64)   not null,
    status           varchar(12)   not null,
    batch_id         bigint,
    target_entity    varchar(60),
    target_id        bigint,
    target_code      varchar(80),
    message          varchar(1000),
    loaded_at        timestamptz,
    constraint ck_mig_stage_row_status check (status in ('STAGED', 'VALID', 'WARNING', 'INVALID', 'LOADED',
        'REJECTED', 'SKIPPED', 'ROLLED_BACK', 'EXCLUDED'))
);
create index ix_mig_stage_row_extract on mig_stage_row (extract_id, status);
create index ix_mig_stage_row_key on mig_stage_row (object_code, legacy_key);
create index ix_mig_stage_row_batch on mig_stage_row (batch_id, status);

create table mig_issue (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    stage_row_id     bigint        not null references mig_stage_row (id),
    batch_id         bigint,
    rule_code        varchar(20)   not null,
    severity         varchar(10)   not null,
    field            varchar(60),
    value            varchar(300),
    message          varchar(1000) not null,
    resolution       varchar(20)   not null default 'OPEN',
    resolution_note  varchar(1000),
    waiver_reason    varchar(40),
    resolved_by      varchar(50),
    resolved_at      timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_mig_issue_severity check (severity in ('ERROR', 'WARNING')),
    constraint ck_mig_issue_resolution check (resolution in ('OPEN', 'FIXED_AT_SOURCE', 'MAPPED', 'WAIVED', 'EXCLUDED'))
);
create index ix_mig_issue_row on mig_issue (stage_row_id);
create index ix_mig_issue_batch on mig_issue (batch_id, severity, resolution);
