-- =====================================================================================
-- iNXT BrokerVerse - V1090 Data Migration: business wording of the catalogue texts that the Migration Console shows
-- and exports (object register, the title of layout R06, an allowed-values text of layout R08). The texts follow the
-- catalogue of the BRD-13 business sign-off set (docs/deliverables/src/BRD-13_Data_Migration/pack/catalogue.yaml,
-- read with the V1081 seed by build_dm_pack.py, which applies these updates). V1081 keeps its original header, which
-- still names the retired dm_layouts.yaml; the catalogue source is now the sign-off set.
-- =====================================================================================

update mig_data_object set name = 'Package code map (legacy package and version to BIBS package version)', target = 'Renewal package map, used by the package check of the Renewal sanitation', rationale = 'Packages are remapped at sanitation in Renewal, not at migration intake. The migration loads the package code map as reference data only; the package check of the Renewal sanitation uses it and sends unmapped packages to the Exception bucket, worked by the Renewal processing team. The BIBS packages themselves are maintained by TSU in Product Maintenance and are not migrated.' where code = 'R06';
update mig_data_object set target = 'GL account code map to the BIBS chart of accounts (chart configured by Comptrollership)' where code = 'R08';
update mig_data_object set target = 'Payees (party and payee records, loaded by the payee migration of Disbursement)', condition_text = 'Loaded through the payee registration of Disbursement if BDOI confirms (DMQ30).', rationale = 'Payees are loaded through the payee registration of Disbursement; in scope if BDOI confirms (DMQ30).' where code = 'R09';
update mig_data_object set target = 'Submitted Policies masterlist (policy registration of Submitted Policies)', condition_text = 'Loaded through the policy registration of Submitted Policies if BDOI confirms (DMQ30); the layout is issued with the Submitted Policies set.', rationale = 'Loaded through the policy registration of Submitted Policies if BDOI confirms (DMQ30); the layout is issued with the Submitted Policies set.' where code = 'P04';
update mig_data_object set target = 'Employee Benefits programmes (programme set-up of Employee Benefits)', condition_text = 'Loaded through the programme set-up of Employee Benefits if BDOI confirms (DMQ30); the layout is issued with the Employee Benefits set.', rationale = 'Loaded through the programme set-up of Employee Benefits if BDOI confirms (DMQ30); the layout is issued with the Employee Benefits set.' where code = 'P05';
update mig_data_object set target = 'Claims (claim registration of Claims)', condition_text = 'Loaded through the claim registration of Claims if BDOI decides (DMQ30); closed claims are archived.', rationale = 'Loaded through the claim registration of Claims if BDOI decides (DMQ30); closed claims are archived.' where code = 'F07';
update mig_layout set title = 'Package code map (legacy package to BIBS package version)' where code = 'R06' and version_no = 1;
update mig_layout_column set allowed_values = 'Account codes of the BIBS chart of accounts' where seq = 6 and layout_id = (select id from mig_layout where code = 'R08' and version_no = 1);
