-- =====================================================================================
-- iNXT BrokerVerse - V1100 Document storage foundation (build step ST0).
--   Decision: docs/architecture/DOCUMENT_STORAGE_DECISION.md (option C approved by BDOI,
--   26-Sep-2026): file content in S3, metadata in PostgreSQL, short-lived presigned links.
--     stored_file              metadata of every stored object (section 3 "Metadata") with the
--                              malware scan status (decision 2), the legal hold (decision 3) and
--                              the ECM reference (decision 5)
--     sto_record_class         parameterised record classes: bucket class, retention (mapped to
--                              the retention rules nba_retention_rule), under legal hold, archive
--                              to ECM
--     sto_legal_hold_request   place / release of a legal hold as a controlled action with
--                              requester, approver and reason (decision 3, DOA)
--   Module tables keep their bytea columns until ST1 moves them (per-table plan in the decision
--   document, "As built").
--   Runs after V790 (nba_retention_rule) and V1 (org_company) on a fresh database.
-- =====================================================================================

create table sto_record_class (
    id                    bigint generated by default as identity primary key,
    version               bigint       not null default 0,
    code                  varchar(40)  not null,
    name                  varchar(120) not null,
    bucket_class          varchar(20)  not null,
    retention_record_type varchar(40),
    retention_period      varchar(10)  not null,
    legal_hold            boolean      not null default false,
    archive_to_ecm        boolean      not null default false,
    active                boolean      not null default true,
    description           varchar(300) not null,
    created_at            timestamptz  not null,
    created_by            varchar(50)  not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_sto_record_class unique (code),
    constraint ck_sto_record_class_bucket
        check (bucket_class in ('DOCUMENTS', 'REPORTS', 'INBOUND', 'MIGRATION')),
    constraint ck_sto_record_class_period check (retention_period ~ '^P[0-9]+[YMD]$')
);

comment on column sto_record_class.retention_record_type is
    'Record type of nba_retention_rule whose active rules (years online + years in archive, the longest) set the retention; retention_period applies when none is active';

create table stored_file (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    company_id             bigint        references org_company (id),
    owner_entity_type      varchar(60)   not null,
    owner_entity_id        varchar(60)   not null,
    document_type          varchar(40),
    record_class           varchar(40)   not null references sto_record_class (code),
    file_name              varchar(255)  not null,
    content_type           varchar(150)  not null,
    size_bytes             bigint        not null,
    sha256                 varchar(64)   not null,
    bucket_class           varchar(20)   not null,
    bucket                 varchar(63)   not null,
    object_key             varchar(512)  not null,
    version_id             varchar(1024),
    scan_status            varchar(20)   not null,
    scan_result            varchar(40),
    scanned_at             timestamptz,
    retention_until        date          not null,
    legal_hold             boolean       not null default false,
    legal_hold_reason      varchar(500),
    legal_hold_placed_by   varchar(50),
    legal_hold_approved_by varchar(50),
    legal_hold_at          timestamptz,
    final_at               timestamptz,
    ecm_status             varchar(20)   not null default 'NOT_REQUIRED',
    ecm_reference          varchar(200),
    ecm_requested_at       timestamptz,
    ecm_archived_at        timestamptz,
    deleted_at             timestamptz,
    deleted_by             varchar(50),
    purged_at              timestamptz,
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_stored_file_object unique (bucket, object_key),
    constraint ck_stored_file_size check (size_bytes >= 0),
    constraint ck_stored_file_sha256 check (sha256 ~ '^[0-9a-f]{64}$'),
    constraint ck_stored_file_bucket
        check (bucket_class in ('DOCUMENTS', 'REPORTS', 'INBOUND', 'MIGRATION')),
    constraint ck_stored_file_scan
        check (scan_status in ('AWAITING_UPLOAD', 'PENDING', 'CLEAN', 'QUARANTINED')),
    constraint ck_stored_file_ecm
        check (ecm_status in ('NOT_REQUIRED', 'AWAITING_FINAL', 'PENDING', 'REQUESTED', 'ARCHIVED')),
    constraint ck_stored_file_hold check (not legal_hold or legal_hold_reason is not null)
);

create index ix_stored_file_owner on stored_file (owner_entity_type, owner_entity_id);
create index ix_stored_file_company on stored_file (company_id);
create index ix_stored_file_scan on stored_file (scan_status, created_at)
    where scan_status in ('AWAITING_UPLOAD', 'PENDING');
create index ix_stored_file_retention on stored_file (retention_until) where purged_at is null;
create index ix_stored_file_deleted on stored_file (deleted_at)
    where deleted_at is not null and purged_at is null;
create index ix_stored_file_ecm on stored_file (ecm_status) where ecm_status = 'PENDING';

create table sto_legal_hold_request (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    stored_file_id bigint       not null references stored_file (id),
    action         varchar(10)  not null,
    reason         varchar(500) not null,
    status         varchar(10)  not null,
    requested_by   varchar(50)  not null,
    requested_at   timestamptz  not null,
    decided_by     varchar(50),
    decided_at     timestamptz,
    decision_note  varchar(500),
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_sto_legal_hold_action check (action in ('PLACE', 'RELEASE')),
    constraint ck_sto_legal_hold_status check (status in ('PENDING', 'APPROVED', 'REJECTED')),
    constraint ck_sto_legal_hold_four_eyes check (decided_by is null or decided_by <> requested_by)
);

create unique index uq_sto_legal_hold_pending on sto_legal_hold_request (stored_file_id)
    where status = 'PENDING';
create index ix_sto_legal_hold_file on sto_legal_hold_request (stored_file_id, id desc);
