-- User-facing reference texts without internal references (work item MSG0).
--
-- The descriptions and labels of lists of values, business parameters, notification events,
-- exception codes, accounting events, feeds, file layouts and rules were written with the
-- requirement and open-question references of the project (BRNB.nnn, CSHID.nnn, OQnn, AQnn, BRD
-- page numbers, "to confirm"). The screens show these texts, so they now carry the business
-- meaning only. Each text is replaced only where it still holds the delivered value: a text an
-- administrator has since changed is kept.

create temporary table msg0_text (tbl varchar(63) not null, old_text text not null, new_text text not null);

insert into msg0_text (tbl, old_text, new_text) values
 ('acc_event_type',
  'A printed or released check reached DISB_STALE_DAYS (DIS 3.26.2, 3.27.1): checks outstanding moved to Miscellaneous Liability - stale checks of the payee.',
  'A printed or released check reached DISB_STALE_DAYS: checks outstanding moved to Miscellaneous Liability - stale checks of the payee.'),
 ('acc_event_type',
  'A released check was negotiated (deposited-checks file, DIS 3.26.1): checks outstanding cleared against the bank when DISB_CHECK_CLEARING = ON.',
  'A released check was negotiated (deposited-checks file): checks outstanding cleared against the bank when DISB_CHECK_CLEARING = ON.'),
 ('acc_event_type',
  'An AR insurer''s refund confirmed by the insurer is deducted from the next remittance batch of that insurer (ACSL 2.9.2): due to insurer for disbursement against AR insurer''s refund.',
  'An AR insurer''s refund confirmed by the insurer is deducted from the next remittance batch of that insurer: due to insurer for disbursement against AR insurer''s refund.'),
 ('acc_event_type',
  'An insurer creditable withholding tax certificate was tagged as received (DIS 2.11): AR-BIR on commission or on incentives moved to AR-BIR on hand.',
  'An insurer creditable withholding tax certificate was tagged as received: AR-BIR on commission or on incentives moved to AR-BIR on hand.'),
 ('acc_event_type',
  'Approved DV (DIS 2.7.6, 2.18.0): the gross is supplied in the component of the DV type (the payable settled), PAID is credited to @PAY_ACCOUNT (paying bank, or the checks-outstanding clearing for checks) and EWT to withholding tax payable. An approved DV that is cancelled re-posts with negative amounts (DV:<no>:CANCEL, DIS 2.20.0). Rows 1-7, 10 and 11 of the design.',
  'Approved DV: the gross is supplied in the component of the DV type (the payable settled), PAID is credited to @PAY_ACCOUNT (paying bank, or the checks-outstanding clearing for checks) and EWT to withholding tax payable. An approved DV that is cancelled re-posts with negative amounts (DV:<no>:CANCEL).'),
 ('acc_event_type',
  'Booked invoice, endorsement or cancellation of a placed account (BRNB.027/076/081). Premium receivable by component from the client (party of the PR_ components) and due to the insurer; commission receivable from the insurer, unrealized (ON_COLLECTION) or realized (ON_BOOKING). Negative amounts reverse (return premium, cancellation).',
  'Booked invoice, endorsement or cancellation of a placed account. Premium receivable by component from the client (party of the PR_ components) and due to the insurer; commission receivable from the insurer, unrealized (ON_COLLECTION) or realized (ON_BOOKING). Negative amounts reverse (return premium, cancellation).'),
 ('acc_event_type',
  'CMRID.005: target incentive earned - Dr incentive receivable (insurer) / Cr incentive income',
  'Target incentive earned - Dr incentive receivable (insurer) / Cr incentive income'),
 ('acc_event_type',
  'CMRID.006: Motor Mania incentive passed on to branches - Dr incentive income / Cr due to branches, then Disbursement',
  'Motor Mania incentive passed on to branches - Dr incentive income / Cr due to branches, then Disbursement'),
 ('acc_event_type',
  'CPC2 incentive earned on packaged Fire and Motor products, computed per remittance batch line from the incentive criteria (DIS 3.29.2): deducted from the amount due to the insurer as Other Income with output VAT.',
  'CPC2 incentive earned on packaged Fire and Motor products, computed per remittance batch line from the incentive criteria: deducted from the amount due to the insurer as Other Income with output VAT.'),
 ('acc_event_type',
  'CSHID.004 b: reverse of OPS_DP_PR_REVERSAL (negative amounts)',
  'Reverse of OPS_DP_PR_REVERSAL (negative amounts)'),
 ('acc_event_type',
  'Early remittance incentive of a With Incentives batch (RMTID.023): deducted from the amount due to the insurer for disbursement as incentive income and its output VAT; the incentive OR is issued through ReceiptIssuer. Source RMB:<batch>:INC.',
  'Early remittance incentive of a With Incentives batch: deducted from the amount due to the insurer for disbursement as incentive income and its output VAT; the incentive OR is issued through ReceiptIssuer. Source RMB:<batch>:INC.'),
 ('acc_event_type',
  'Full or partial reinstatement of a cancelled receipt (CSHID.013): cash or bank in to unapplied collections; the reinstated amount is then applied again.',
  'Full or partial reinstatement of a cancelled receipt: cash or bank in to unapplied collections; the reinstated amount is then applied again.'),
 ('acc_event_type',
  'Funding of the main BDOIR account through BDO Business Online Banking (DIS 2.17): target bank (@TARGET_BANK) against source bank (@SOURCE_BANK).',
  'Funding of the main BDOIR account through BDO Business Online Banking: target bank (@TARGET_BANK) against source bank (@SOURCE_BANK).'),
 ('acc_event_type',
  'Head Office official receipt for BDOI income (CSHID.002/007/014): cash and creditable withholding tax against income by OR type and output VAT; commission ORs of settlement batches make the deferred VAT due.',
  'Head Office official receipt for BDOI income: cash and creditable withholding tax against income by OR type and output VAT; commission ORs of settlement batches make the deferred VAT due.'),
 ('acc_event_type',
  'Increase or decrease of the commission of a booked invoice without premium change (ADJID.014): commission receivable against unrealized commission and deferred output VAT; negative amounts reverse.',
  'Increase or decrease of the commission of a booked invoice without premium change: commission receivable against unrealized commission and deferred output VAT; negative amounts reverse.'),
 ('acc_event_type',
  'Liquidation of an employee cash advance (Appendix D, AQ18): expenses by category against advances to employees; excess returned (CASH_RETURNED) or shortage payable to the employee (SHORTAGE).',
  'Liquidation of an employee cash advance: expenses by category against advances to employees; excess returned (CASH_RETURNED) or shortage payable to the employee (SHORTAGE).'),
 ('acc_event_type',
  'MKTID.012: premium the client paid directly to the insurer - Dr due to insurer (DTIP) / Cr premium receivable by component. Posted only when DP_PR_REVERSAL_POSTING is on (booking posts no PR for direct payment invoices).',
  'Premium the client paid directly to the insurer - Dr due to insurer (DTIP) / Cr premium receivable by component. Posted only when DP_PR_REVERSAL_POSTING is on (booking posts no PR for direct payment invoices).'),
 ('acc_event_type',
  'Minimal balance file 10.00-100.00 (row 21, ADJID.026): a debit balance written off by premium receivable component, or a credit balance taken to income.',
  'Minimal balance file 10.00-100.00: a debit balance written off by premium receivable component, or a credit balance taken to income.'),
 ('acc_event_type',
  'Non-premium payment of an insurer (refund, other expenses, AR Insurance) credited to AR Insurer, segregated from premium (CSHID.021, OQ14).',
  'Non-premium payment of an insurer (refund, other expenses, AR Insurance) credited to AR Insurer, segregated from premium.'),
 ('acc_event_type',
  'Payment applied per premium receivable component in the hierarchy DST, premium tax / VAT, LGT, FST, other, basic (CSHID.020/022); commission realized pro rata when OPS_COMMISSION_REALIZATION = ON_COLLECTION. Negative amounts reverse an application (cancellation, re-application).',
  'Payment applied per premium receivable component in the hierarchy DST, premium tax / VAT, LGT, FST, other, basic; commission realized pro rata when OPS_COMMISSION_REALIZATION = ON_COLLECTION. Negative amounts reverse an application (cancellation, re-application).'),
 ('acc_event_type',
  'Premium collected on behalf of an insurer (CSHID.001/014): cash or bank in, credited to unapplied collections of the client until applied. A cancellation re-posts it with a negative amount (CSHID.012).',
  'Premium collected on behalf of an insurer: cash or bank in, credited to unapplied collections of the client until applied. A cancellation re-posts it with a negative amount.'),
 ('acc_event_type',
  'Premium receivable balances at or below the minimal amount reversed (CSHID.016, OQ11 target account).',
  'Premium receivable balances at or below the minimal amount reversed.'),
 ('acc_event_type',
  'Reclass or transfer disposition (CSHID.024): unapplied collections moved from one client or marketing unit to another.',
  'Reclass or transfer disposition: unapplied collections moved from one client or marketing unit to another.'),
 ('acc_event_type',
  'Refund disposition of an unapplied payment (CSHID.024): unapplied collections to refund payable, then paid by Disbursement.',
  'Refund disposition of an unapplied payment: unapplied collections to refund payable, then paid by Disbursement.'),
 ('acc_event_type',
  'Remittance batch approved and pushed to Disbursement, per invoice line (RMTID.010/011): the paid AR part of the DTIP and the withholding tax the insurer withholds on the commission, against the commission receivable (commission and VAT) and the net due to the insurer for disbursement. Source RMB:<batch>:<invoice>.',
  'Remittance batch approved and pushed to Disbursement, per invoice line: the paid AR part of the DTIP and the withholding tax the insurer withholds on the commission, against the commission receivable (commission and VAT) and the net due to the insurer for disbursement. Source RMB:<batch>:<invoice>.'),
 ('acc_event_type',
  'Service fee of the units and referrers on fully paid commission (FRBS 2.10): expense (cost centre) against service fee payable.',
  'Service fee of the units and referrers on fully paid commission: expense (cost centre) against service fee payable.'),
 ('acc_event_type',
  'The 2% creditable withholding tax portion of the premium receivable moved to PR2307 when the certificate is validated (CSHID.027): Dr PR2307 / Cr PR by component.',
  'The 2% creditable withholding tax portion of the premium receivable moved to PR2307 when the certificate is validated: Dr PR2307 / Cr PR by component.'),
 ('acc_event_type',
  'The 2307 certificate forwarded to the insurer settles the PR2307 against the premium due to the insurer (DBMID.001): Dr DTIP / Cr PR2307.',
  'The 2307 certificate forwarded to the insurer settles the PR2307 against the premium due to the insurer: Dr DTIP / Cr PR2307.'),
 ('alt_exception_code',
  'A cheque book of a paying bank account reached its warning threshold of remaining checks (DIS 2.24.2).',
  'A cheque book of a paying bank account reached its warning threshold of remaining checks.'),
 ('alt_exception_code',
  'A claim is recorded on, or stays on, a cover with unpaid or partly paid premium (BRCLM.001).',
  'A claim is recorded on, or stays on, a cover with unpaid or partly paid premium.'),
 ('alt_exception_code',
  'A contract, HMO card or billing is past its due date after the follow-ups (BRID-030).',
  'A contract, HMO card or billing is past its due date after the follow-ups.'),
 ('alt_exception_code',
  'A franchise request has no insurer decision after EB_FRANCHISE_TAT_DAYS (BRID-027).',
  'A franchise request has no insurer decision after EB_FRANCHISE_TAT_DAYS.'),
 ('alt_exception_code',
  'A payment matched to a pre-booked account is still waiting for the booking after the threshold days (CSHID.020).',
  'A payment matched to a pre-booked account is still waiting for the booking after the threshold days.'),
 ('alt_exception_code',
  'A posting to an account that requires a cost centre found no cost-centre rule (FRBS 3.1.1, DIS 3.30.0).',
  'A posting to an account that requires a cost centre found no cost-centre rule.'),
 ('alt_exception_code',
  'A printed or released check reached DISB_STALE_DAYS and was moved to Miscellaneous Liability (DIS 3.26.2).',
  'A printed or released check reached DISB_STALE_DAYS and was moved to Miscellaneous Liability.'),
 ('alt_exception_code',
  'A programme is inside the RA lead time and no renewal advice was sent (no contact, no renewal flag) (BRID-001).',
  'A programme is inside the RA lead time and no renewal advice was sent (no contact, no renewal flag).'),
 ('alt_exception_code',
  'A released package reaches its package end date within the notice period (PACKAGE_EXPIRY_NOTICE_DAYS, then 30 and 7 days) and has no renewal released yet (BRPM.017).',
  'A released package reaches its package end date within the notice period (PACKAGE_EXPIRY_NOTICE_DAYS, then 30 and 7 days) and has no renewal released yet.'),
 ('alt_exception_code',
  'A role was created or changed directly on the Roles screen through the emergency path UAM_DIRECT_ROLE_EDIT (PQ17).',
  'A role was created or changed directly on the Roles screen through the emergency path UAM_DIRECT_ROLE_EDIT.'),
 ('alt_exception_code',
  'A run of an inbound or outbound Operations feed failed or had failed records (BRQID.005).',
  'A run of an inbound or outbound Operations feed failed or had failed records.'),
 ('alt_exception_code',
  'A scheduled Collections file (daily, weekly, monthly or application file) was not generated on time (BRCLXN.024-029, 041, 045).',
  'A scheduled Collections file (daily, weekly, monthly or application file) was not generated on time.'),
 ('alt_exception_code',
  'A scheduled month-end or broking books close did not complete; the checklist lists the blocking items (FRBS 2.6.0, 3.4.0).',
  'A scheduled month-end or broking books close did not complete; the checklist lists the blocking items.'),
 ('alt_exception_code',
  'A scheduled or manual remittance extraction failed (RMTID.001/005).',
  'A scheduled or manual remittance extraction failed.'),
 ('alt_exception_code',
  'A screening case stayed in a stage beyond the SLA of its matrix (SNSRP-108, 405).',
  'A screening case stayed in a stage beyond the SLA of its matrix.'),
 ('alt_exception_code',
  'A screening trigger fired while no matching configuration version was active (SNSRP-101, 109).',
  'A screening trigger fired while no matching configuration version was active.'),
 ('alt_exception_code',
  'A source module has not restored its records after the cancellation of an approved DV (DIS 2.20.0).',
  'A source module has not restored its records after the cancellation of an approved DV.'),
 ('alt_exception_code',
  'A system-triggered payment request names a payee that is not maintained; it was returned to its source (DIS 3.25.0).',
  'A system-triggered payment request names a payee that is not maintained; it was returned to its source.'),
 ('alt_exception_code',
  'A true or potential match has had no closed case for more than the threshold days (SNSRP-302, 405).',
  'A true or potential match has had no closed case for more than the threshold days.'),
 ('alt_exception_code',
  'A watchlist ingestion run failed or loaded only part of the file (SNSRP-201, 202).',
  'A watchlist ingestion run failed or loaded only part of the file.'),
 ('alt_exception_code',
  'An AR or OR series reached its warning threshold of remaining numbers (CSHID.015).',
  'An AR or OR series reached its warning threshold of remaining numbers.'),
 ('alt_exception_code',
  'An access request raises a privilege level or was submitted outside working hours (UAM-NFR-40).',
  'An access request raises a privilege level or was submitted outside working hours.'),
 ('alt_exception_code',
  'An active incentive criterion applies to a package that expired or was retired: review or deactivate it (PMADD08).',
  'An active incentive criterion applies to a package that expired or was retired: review or deactivate it.'),
 ('alt_exception_code',
  'An approved access request could not be applied on its effective date (UAM-NFR-14).',
  'An approved access request could not be applied on its effective date.'),
 ('alt_exception_code',
  'An escalation stayed in a stage beyond the SLA of its rule (BRCLXN.049).',
  'An escalation stayed in a stage beyond the SLA of its rule.'),
 ('alt_exception_code',
  'An insurer SOA is not validated within EB_TAT_SOA_VALIDATION working days (BRID-021).',
  'An insurer SOA is not validated within EB_TAT_SOA_VALIDATION working days.'),
 ('alt_exception_code',
  'An insurer claim number already exists on another claim for the same insurer (BRCLM.043).',
  'An insurer claim number already exists on another claim for the same insurer.'),
 ('alt_exception_code',
  'An insurer has not answered a direct payment commission billing within the working days allowed (CMRID.011).',
  'An insurer has not answered a direct payment commission billing within the working days allowed.'),
 ('alt_exception_code',
  'An insurer production report identical to an earlier upload was refused (PRCID.010).',
  'An insurer production report identical to an earlier upload was refused.'),
 ('alt_exception_code',
  'An insurer request for proposal is past its due date without an answer (BRID-009).',
  'An insurer request for proposal is past its due date without an answer.'),
 ('alt_exception_code',
  'An invoice has more paid AR than the premium due to the insurer (RMTID.014, OQ19).',
  'An invoice has more paid AR than the premium due to the insurer.'),
 ('alt_exception_code',
  'An outstanding claim is older than BCL_PAST_DUE_DAYS (BRCLM.031, p.43).',
  'An outstanding claim is older than BCL_PAST_DUE_DAYS.'),
 ('alt_exception_code',
  'Cumulative adjustments of an invoice exceed its original premium or DTIP (ADJID.028).',
  'Cumulative adjustments of an invoice exceed its original premium or DTIP.'),
 ('alt_exception_code',
  'No comparative was sent EB_COMPARATIVE_DAYS after the last proposal (BRID-010, TAT p.42).',
  'No comparative was sent EB_COMPARATIVE_DAYS after the last proposal.'),
 ('alt_exception_code',
  'Production lines were excluded from an incentive run by an exclusion rule (CMRID.003).',
  'Production lines were excluded from an incentive run by an exclusion rule.'),
 ('alt_exception_code',
  'The daily GL-SL reconciliation found a difference between a control account and its sub-ledger (ACSL 2.13.2).',
  'The daily GL-SL reconciliation found a difference between a control account and its sub-ledger.'),
 ('alt_exception_code',
  'The daily refresh of the collection worklist from the invoice ledger failed (BRCLXN.001-015).',
  'The daily refresh of the collection worklist from the invoice ledger failed.'),
 ('alt_exception_code',
  'The next follow-up date or a diary due date of a claim has passed (BRCLM.019/022/034).',
  'The next follow-up date or a diary due date of a claim has passed.'),
 ('alt_exception_code',
  'The previous year is not closed and YEAR_END_CLOSE_DEADLINE is near (FRBS 2.7.x).',
  'The previous year is not closed and YEAR_END_CLOSE_DEADLINE is near.'),
 ('csh_minimal_balance_rule',
  'Commission receivable minimal balances: rule and target account to confirm (OQ11), inactive',
  'Commission receivable minimal balances; inactive until the rule and the target account are set'),
 ('csh_minimal_balance_rule',
  'Premium receivable balances up to the amount are reversed unless they equal the 2% CWT, the DST or the whole premium (CSHID.016)',
  'Premium receivable balances up to the amount are reversed unless they equal the 2% CWT, the DST or the whole premium'),
 ('csh_payment_file_layout',
  'BIR 2307 tags from Marketing Collection (MKTID.013)',
  'BIR 2307 tags from Marketing Collection'),
 ('csh_payment_file_layout',
  'Bills Payment FS01 (IT-DCO): pipe-delimited TXT with the BRD field names until the FS01 layout is supplied (OQ03)',
  'Bills Payment FS01 (IT-DCO): pipe-delimited TXT with the standard field names'),
 ('csh_payment_file_layout',
  'CLPC payment: Excel or CSV with the BRD field names',
  'CLPC payment: Excel or CSV with the standard field names'),
 ('csh_payment_file_layout',
  'Commission payment details from Collection (CSHID.007)',
  'Commission payment details from Collection'),
 ('csh_payment_file_layout',
  'Direct Credit FS01/04: pipe-delimited TXT with the BRD field names until the layout is supplied (OQ03)',
  'Direct Credit FS01/04: pipe-delimited TXT with the standard field names'),
 ('csh_payment_file_layout',
  'PDC list from PMS: Excel or CSV (layout not given in the BRD, OQ03)',
  'PDC list from PMS: Excel or CSV with the standard field names'),
 ('csh_payment_file_layout',
  'Trade payment (CIB): pipe-delimited TXT with the BRD field names until the layout is supplied (OQ03)',
  'Trade payment (CIB): pipe-delimited TXT with the standard field names'),
 ('fin_schedule_def',
  'Draft definition seeded from the BDOI report pack; layout to confirm with FRBS (AQ05).',
  'Schedule definition from the BDOI report pack; review the layout before first use.'),
 ('frbs_service_fee_rule',
  'Consumer banking referrals: 2.5% of fully paid commission net of taxes (AQ20)',
  'Consumer banking referrals: 2.5% of fully paid commission net of taxes'),
 ('frbs_service_fee_rule',
  'Institutional banking referrals: 1% of fully paid commission net of taxes (AQ20)',
  'Institutional banking referrals: 1% of fully paid commission net of taxes'),
 ('lov_type',
  'Action of a member change line (BRID-013; EBQ16)',
  'Action of a member change line'),
 ('lov_type',
  'Adjusters and appraisers of claims and insurer lines (BRCLM.017/018, spec 6.3; CLQ11)',
  'Adjusters and appraisers of claims and insurer lines'),
 ('lov_type',
  'BDOI claim status; phase and other attributes in bcl_lov_attribute (BRCLM.010, spec 6.1; CLQ04)',
  'BDOI claim status; phase and other attributes in bcl_lov_attribute'),
 ('lov_type',
  'BIR official receipt types of BDOI income (CSHID.002)',
  'BIR official receipt types of BDOI income'),
 ('lov_type',
  'Billing frequency of an installment plan or a billing statement cycle (BRCLXN.053/058, CQ15)',
  'Billing frequency of an installment plan or a billing statement cycle'),
 ('lov_type',
  'Branch mailboxes for ATD, MC / DD and credit ticket forms; label = e-mail address (DIS 2.7.7-2.7.9, AQ09)',
  'Branch mailboxes for ATD, MC / DD and credit ticket forms; label = e-mail address'),
 ('lov_type',
  'Business unit group of a user (BRD 1.002.1.1.1; values from BDOI, UQ05)',
  'Business unit group of a user (values from BDOI)'),
 ('lov_type',
  'Catastrophe event type of a loss (BRCLM.036, spec 6.4)',
  'Catastrophe event type of a loss'),
 ('lov_type',
  'Category A of a refund line (Appendix D, AQ18)',
  'Category A of a refund line'),
 ('lov_type',
  'Category B of a refund line (Appendix D, AQ18)',
  'Category B of a refund line'),
 ('lov_type',
  'Channel of an update received from an insurer (BRCLM.041, CLQ17)',
  'Channel of an update received from an insurer'),
 ('lov_type',
  'Claims handling unit of a handler and a claim; used by the status access matrix (BRCLM.012, CLQ04)',
  'Claims handling unit of a handler and a claim; used by the status access matrix'),
 ('lov_type',
  'Classification of a Disbursement payee (DIS 2.2.2)',
  'Classification of a Disbursement payee'),
 ('lov_type',
  'Client risk rating; drives the periodic KYC review cycle (BRNB.110)',
  'Client risk rating; drives the periodic KYC review cycle'),
 ('lov_type',
  'Collector disposition of an outstanding premium receivable; attributes in clx_lov_attribute (BRCLXN.016-023, CQ08)',
  'Collector disposition of an outstanding premium receivable; attributes in clx_lov_attribute'),
 ('lov_type',
  'Collector disposition of an unapplied payment; attributes in clx_lov_attribute (BRCLXN.031-033, 037-038, 047/048, CQ08)',
  'Collector disposition of an unapplied payment; attributes in clx_lov_attribute'),
 ('lov_type',
  'Condition of a special remittance request (MKTID.009)',
  'Condition of a special remittance request'),
 ('lov_type',
  'Controlled client tags shown as banners (BRNB.091)',
  'Controlled client tags shown as banners'),
 ('lov_type',
  'Disposition of a screening case; parent = case stage (SNSRP-107, SQ06)',
  'Disposition of a screening case; parent = case stage'),
 ('lov_type',
  'Disposition of an unapplied or excess payment (CSHID.024)',
  'Disposition of an unapplied or excess payment'),
 ('lov_type',
  'Disposition of an unmatched or discrepant production line (PRCID.038/039, OQ31)',
  'Disposition of an unmatched or discrepant production line'),
 ('lov_type',
  'Document type of a claim; parent = DOCUMENT_TYPE code (p.24-25, CLQ26)',
  'Document type of a claim; parent = DOCUMENT_TYPE code'),
 ('lov_type',
  'Document type of a screening case; parent = DOCUMENT_TYPE code (SNSRP-601)',
  'Document type of a screening case; parent = DOCUMENT_TYPE code'),
 ('lov_type',
  'Employee Benefits line of a programme (HMO, GLI, GPA; EBQ01)',
  'Employee Benefits line of a programme (HMO, GLI, GPA)'),
 ('lov_type',
  'Employee Benefits team of a programme (BRD volumes p.36; EBQ22)',
  'Employee Benefits team of a programme'),
 ('lov_type',
  'Financial, non-financial and internal endorsement types; parent = class (ADJID.002/004)',
  'Financial, non-financial and internal endorsement types; parent = class'),
 ('lov_type',
  'Form of a screening review or document (SNSRP-501, 601)',
  'Form of a screening review or document'),
 ('lov_type',
  'How the client confirmed the placement of an Other Lines account (payment gate, BRD 2.3.1)',
  'How the client confirmed the placement of an Other Lines account (payment gate)'),
 ('lov_type',
  'Insurer capability factor rated on the comparative (BRID-010; EBQ10)',
  'Insurer capability factor rated on the comparative'),
 ('lov_type',
  'Insurer feedback on a direct payment commission billing (CMRID.008, OQ40)',
  'Insurer feedback on a direct payment commission billing'),
 ('lov_type',
  'Integrated applications shown on the Operations home; label "Name|https://url" (BRQID.003, OQ01)',
  'Integrated applications shown on the Operations home; label "Name|https://url"'),
 ('lov_type',
  'Kind of a claim diary entry (BRCLM.022)',
  'Kind of a claim diary entry'),
 ('lov_type',
  'Kind of a clause library entry (PMADD02)',
  'Kind of a clause library entry'),
 ('lov_type',
  'Kind of a collection effort (p.43-46, p.59; CQ08)',
  'Kind of a collection effort'),
 ('lov_type',
  'Kind of a correction entry (ACSL 2.7-2.15, 2.9.1)',
  'Kind of a correction entry'),
 ('lov_type',
  'Kind of a screening case (SNSRP-102, 303)',
  'Kind of a screening case'),
 ('lov_type',
  'Kind of a watchlist source (SNSRP-201, SQ01, SQ20)',
  'Kind of a watchlist source'),
 ('lov_type',
  'Level of a coverage in the product hierarchy (PMADD01)',
  'Level of a coverage in the product hierarchy'),
 ('lov_type',
  'Level of a user in the organisation (BRD 1.002.1.1.1; values from BDOI, UQ05)',
  'Level of a user in the organisation (values from BDOI)'),
 ('lov_type',
  'Mandatory KYC documents of a corporate client; codes are DOCUMENT_TYPE codes (BRNB.090, parked Q16)',
  'Mandatory KYC documents of a corporate client; codes are DOCUMENT_TYPE codes'),
 ('lov_type',
  'Mandatory KYC documents of an individual client; codes are DOCUMENT_TYPE codes (BRNB.090, parked Q16)',
  'Mandatory KYC documents of an individual client; codes are DOCUMENT_TYPE codes'),
 ('lov_type',
  'Mode of payment on a refund or payment request (Appendix D: credit to CA / SA, check, ATD, inter-office, manager''s check, demand draft)',
  'Mode of payment on a refund or payment request: credit to CA / SA, check, ATD, inter-office, manager''s check, demand draft'),
 ('lov_type',
  'Nature of loss / accident of a claim (BRCLM.004, p.42; provisional, CLQ12)',
  'Nature of loss / accident of a claim'),
 ('lov_type',
  'Outcome of an insurer response in a negotiation round, including exception states (PMADD04, PQ05)',
  'Outcome of an insurer response in a negotiation round, including exception states'),
 ('lov_type',
  'Party concerned by a reconciliation discrepancy (PRCID.016, OQ31)',
  'Party concerned by a reconciliation discrepancy'),
 ('lov_type',
  'Pending item followed up per programme or member (BRID-030; EBQ20)',
  'Pending item followed up per programme or member'),
 ('lov_type',
  'Premium and non-premium payment classes and channels of an AR (CSHID.001)',
  'Premium and non-premium payment classes and channels of an AR'),
 ('lov_type',
  'Process tag of an EB document and of the required documents (BRID-025)',
  'Process tag of an EB document and of the required documents'),
 ('lov_type',
  'Production excluded from incentive eligibility (CMRID.003, OQ39)',
  'Production excluded from incentive eligibility'),
 ('lov_type',
  'Reason code of a suspicious transaction report; values from the AMLC layout (SNSRP-705, SQ09)',
  'Reason code of a suspicious transaction report; values from the AMLC layout'),
 ('lov_type',
  'Reason of a client refund on the Refund Request Form (MKT 1.10.0, Appendix D)',
  'Reason of a client refund on the Refund Request Form'),
 ('lov_type',
  'Remittance extraction type (RMTID.001)',
  'Remittance extraction type'),
 ('lov_type',
  'Request types of the endorsement slip (Annex V)',
  'Request types of the endorsement slip'),
 ('lov_type',
  'Segment of a service-fee rule (FRBS 2.10, AQ20)',
  'Segment of a service-fee rule'),
 ('lov_type',
  'Settlement type of a claim; outcome and closure attributes in bcl_lov_attribute (BRCLM.014, spec 6.2; CLQ05)',
  'Settlement type of a claim; outcome and closure attributes in bcl_lov_attribute'),
 ('lov_type',
  'Supporting document of an endorsement request (ADJID.025, OQ32)',
  'Supporting document of an endorsement request'),
 ('lov_type',
  'Type of a client or account special instruction (BRNB.091)',
  'Type of a client or account special instruction'),
 ('lov_type',
  'Type of a payment request or DV (DIS 2.6.1, 3.25.1)',
  'Type of a payment request or DV'),
 ('lov_type',
  'Type of a request for payment (Appendix D RFP; cash advance is the type in scope, AQ18)',
  'Type of a request for payment (cash advance is the type in scope)'),
 ('lov_type',
  'Type of an ACSL case (ACSL 2.5.x-2.9.x)',
  'Type of an ACSL case'),
 ('lov_type',
  'Type of an incentive criterion on the products matrix (PMADD07/08, PQ04)',
  'Type of an incentive criterion on the products matrix'),
 ('lov_type',
  'Type of claim (p.42; provisional, CLQ12)',
  'Type of claim'),
 ('lov_type',
  'Units that receive package advisories (BRPM.016, PQ12)',
  'Units that receive package advisories'),
 ('lov_type',
  'What a package request asks for (BRPM.011, PQ13)',
  'What a package request asks for'),
 ('lov_type',
  'What an insurer-confirmed remittance deduction settles (ACSL 2.9.2, AQ23)',
  'What an insurer-confirmed remittance deduction settles'),
 ('lov_type',
  'Why Marketing holds an account from remittance (MKTID.003, OQ24)',
  'Why Marketing holds an account from remittance'),
 ('lov_type',
  'Why Processing rejects an insurer SOA (BRID-021)',
  'Why Processing rejects an insurer SOA'),
 ('lov_type',
  'Why a DV is returned to the processor or rejected, or a request returned to its source (DIS 2.18.0-2.19.0, 3.25.0)',
  'Why a DV is returned to the processor or rejected, or a request returned to its source'),
 ('lov_type',
  'Why a claimant, follow-up date or reported date is overridden (BRCLM.004/006/019)',
  'Why a claimant, follow-up date or reported date is overridden'),
 ('lov_type',
  'Why a cycle is lost or not renewed (BRID-003)',
  'Why a cycle is lost or not renewed'),
 ('lov_type',
  'Why a package is created, changed, renewed or retired (BRPM.008/011)',
  'Why a package is created, changed, renewed or retired'),
 ('lov_type',
  'Why a package request is closed without a package (BRPM.010/013)',
  'Why a package request is closed without a package'),
 ('lov_type',
  'Why a permanently closed claim is reopened (BRCLM.035, CLQ06)',
  'Why a permanently closed claim is reopened'),
 ('lov_type',
  'Why a receipt is reinstated; parent = PREMIUM or DIRECT_PAYMENT (CSHID.004)',
  'Why a receipt is reinstated; parent = PREMIUM or DIRECT_PAYMENT'),
 ('lov_type',
  'Why a received e-policy is rejected at extraction review (BRNB.104)',
  'Why a received e-policy is rejected at extraction review'),
 ('lov_type',
  'Why a remittance batch or line is returned (RMTID.029)',
  'Why a remittance batch or line is returned'),
 ('lov_type',
  'Why a request or DV is cancelled (DIS 2.20.0-2.21.0, AQ15)',
  'Why a request or DV is cancelled'),
 ('lov_type',
  'Why a screening case is re-assigned (SNSRP-404)',
  'Why a screening case is re-assigned'),
 ('lov_type',
  'Why a user is deactivated (BRD 1.005)',
  'Why a user is deactivated'),
 ('lov_type',
  'Why an AR or OR is cancelled; parent = reason group (CSHID.003)',
  'Why an AR or OR is cancelled; parent = reason group'),
 ('lov_type',
  'Why an account is escalated (BRCLXN.049/050)',
  'Why an account is escalated'),
 ('lov_type',
  'Why an endorsement request is returned to the requester or taken out of a posting batch (ADJID.005/007)',
  'Why an endorsement request is returned to the requester or taken out of a posting batch'),
 ('lov_type',
  'Why an insurer rejects a franchise request (BRID-027)',
  'Why an insurer rejects a franchise request'),
 ('lov_type',
  'Why an invoice is excluded from a remittance batch (RMTID.002 addendum, RMTID.020)',
  'Why an invoice is excluded from a remittance batch'),
 ('lov_value',
  'Approve STR filing (to confirm)',
  'Approve STR filing'),
 ('lov_value',
  'Cancel account (to confirm)',
  'Cancel account'),
 ('lov_value',
  'Client visit (to confirm)',
  'Client visit'),
 ('lov_value',
  'Close - no further action (to confirm)',
  'Close - no further action'),
 ('lov_value',
  'Concur (to confirm)',
  'Concur'),
 ('lov_value',
  'Coordinate further (to confirm)',
  'Coordinate further'),
 ('lov_value',
  'DP PR for reversal (to confirm)',
  'DP PR for reversal'),
 ('lov_value',
  'DP returned by insurer (to confirm)',
  'DP returned by insurer'),
 ('lov_value',
  'Do not concur (to confirm)',
  'Do not concur'),
 ('lov_value',
  'E-mail (to confirm)',
  'E-mail'),
 ('lov_value',
  'Engineering (to confirm)',
  'Engineering'),
 ('lov_value',
  'Escalate to the AML Committee (to confirm)',
  'Escalate to the AML Committee'),
 ('lov_value',
  'False positive (to confirm)',
  'False positive'),
 ('lov_value',
  'Fire (to confirm)',
  'Fire'),
 ('lov_value',
  'For STR filing (to confirm)',
  'For STR filing'),
 ('lov_value',
  'For application to invoice (to confirm)',
  'For application to invoice'),
 ('lov_value',
  'For check pick-up (to confirm)',
  'For check pick-up'),
 ('lov_value',
  'For reclass (to confirm)',
  'For reclass'),
 ('lov_value',
  'For refund (to confirm)',
  'For refund'),
 ('lov_value',
  'For transfer to other unit (to confirm)',
  'For transfer to other unit'),
 ('lov_value',
  'Liability (to confirm)',
  'Liability'),
 ('lov_value',
  'Long leave (to confirm)',
  'Long leave'),
 ('lov_value',
  'Marine (to confirm)',
  'Marine'),
 ('lov_value',
  'Motor own damage (to confirm)',
  'Motor own damage'),
 ('lov_value',
  'Motor theft (to confirm)',
  'Motor theft'),
 ('lov_value',
  'Motor third party (to confirm)',
  'Motor third party'),
 ('lov_value',
  'Need more information (to confirm)',
  'Need more information'),
 ('lov_value',
  'No / missing policy number (to confirm)',
  'No / missing policy number'),
 ('lov_value',
  'No STR (to confirm)',
  'No STR'),
 ('lov_value',
  'Others (to confirm, AQ18)',
  'Others'),
 ('lov_value',
  'Others (to confirm, AQ20)',
  'Others'),
 ('lov_value',
  'PR 2307 for reversal (to confirm)',
  'PR 2307 for reversal'),
 ('lov_value',
  'Payee not maintained (DIS 3.25.0)',
  'Payee not maintained'),
 ('lov_value',
  'Personal accident (to confirm)',
  'Personal accident'),
 ('lov_value',
  'Petty cash replenishment (to confirm, AQ18)',
  'Petty cash replenishment'),
 ('lov_value',
  'Phone call (to confirm)',
  'Phone call'),
 ('lov_value',
  'Possible match - enhanced due diligence (to confirm)',
  'Possible match - enhanced due diligence'),
 ('lov_value',
  'Proof of source of funds (to confirm)',
  'Proof of source of funds'),
 ('lov_value',
  'Property (to confirm)',
  'Property'),
 ('lov_value',
  'Request bank AO assistance (to confirm)',
  'Request bank AO assistance'),
 ('lov_value',
  'Resigned (to confirm)',
  'Resigned'),
 ('lov_value',
  'Return for rework (to confirm)',
  'Return for rework'),
 ('lov_value',
  'Return to Compliance (to confirm)',
  'Return to Compliance'),
 ('lov_value',
  'Screening evidence / list extract (to confirm)',
  'Screening evidence / list extract'),
 ('lov_value',
  'Security reason (to confirm)',
  'Security reason'),
 ('lov_value',
  'Statement of account sent (to confirm)',
  'Statement of account sent'),
 ('lov_value',
  'Transferred to another unit (to confirm)',
  'Transferred to another unit'),
 ('lov_value',
  'True match - for review (to confirm)',
  'True match - for review'),
 ('msg_notification_event',
  'A booking was refused because the insurer billing number is already on an invoice (BRID-020)',
  'A booking was refused because the insurer billing number is already on an invoice'),
 ('msg_notification_event',
  'A claim of yours has its next follow-up or a diary entry due today (BRCLM.019/022/034)',
  'A claim of yours has its next follow-up or a diary entry due today'),
 ('msg_notification_event',
  'A client confirmed the chosen proposals of your programme (BRID-017)',
  'A client confirmed the chosen proposals of your programme'),
 ('msg_notification_event',
  'A client gave feedback on the renewal advice of your programme (BRID-003)',
  'A client gave feedback on the renewal advice of your programme'),
 ('msg_notification_event',
  'A collection account was escalated to you or by your team (BRCLXN.049/050)',
  'A collection account was escalated to you or by your team'),
 ('msg_notification_event',
  'A comparative above the value threshold waits for your approval (BRID-016)',
  'A comparative above the value threshold waits for your approval'),
 ('msg_notification_event',
  'A comparative waits for your sign-off (BRID-010)',
  'A comparative waits for your sign-off'),
 ('msg_notification_event',
  'A flow-in or flow-out run failed or had failed records (BRQID.005)',
  'A flow-in or flow-out run failed or had failed records'),
 ('msg_notification_event',
  'A high-risk or PEP client without an active policy was found (SNSRP-303)',
  'A high-risk or PEP client without an active policy was found'),
 ('msg_notification_event',
  'A negative adjustment was requested on an invoice in remittance (RMTID.020/035)',
  'A negative adjustment was requested on an invoice in remittance'),
 ('msg_notification_event',
  'A payment request was acknowledged, received its DV number, was paid or returned (RMTID.019)',
  'A payment request was acknowledged, received its DV number, was paid or returned'),
 ('msg_notification_event',
  'A privileged or out-of-hours access request waits for your second approval (UAM-NFR-40)',
  'A privileged or out-of-hours access request waits for your second approval'),
 ('msg_notification_event',
  'A promise to pay of one of your accounts was not kept (BRCLXN.055)',
  'A promise to pay of one of your accounts was not kept'),
 ('msg_notification_event',
  'A receipt cancellation, reinstatement or disposition waits for approval (CSHID.001-005/024)',
  'A receipt cancellation, reinstatement or disposition waits for approval'),
 ('msg_notification_event',
  'A remittance batch was submitted for approval (RMTID.034)',
  'A remittance batch was submitted for approval'),
 ('msg_notification_event',
  'A remittance batch you prepared was approved or returned (RMTID.034)',
  'A remittance batch you prepared was approved or returned'),
 ('msg_notification_event',
  'A remittance hold reaches its hold date (RMTID.021)',
  'A remittance hold reaches its hold date'),
 ('msg_notification_event',
  'A scheduled Collections file is available for download (BRCLXN.024-029, 045)',
  'A scheduled Collections file is available for download'),
 ('msg_notification_event',
  'A scheduled or manual remittance extraction finished (RMTID.001/034)',
  'A scheduled or manual remittance extraction finished'),
 ('msg_notification_event',
  'A screening case of yours is about to pass its SLA (SNSRP-405)',
  'A screening case of yours is about to pass its SLA'),
 ('msg_notification_event',
  'A screening case passed its SLA and is escalated to you (SNSRP-108, 405)',
  'A screening case passed its SLA and is escalated to you'),
 ('msg_notification_event',
  'A screening case waits for the vote of the AML Committee (SNSRP-704)',
  'A screening case waits for the vote of the AML Committee'),
 ('msg_notification_event',
  'A screening case waits for your approval (SNSRP-702, 703)',
  'A screening case waits for your approval'),
 ('msg_notification_event',
  'A screening case was assigned or re-assigned to you (SNSRP-106, 404)',
  'A screening case was assigned or re-assigned to you'),
 ('msg_notification_event',
  'A screening case was returned to you with a rationale (SNSRP-702, 703)',
  'A screening case was returned to you with a rationale'),
 ('msg_notification_event',
  'A screening configuration version waits for your approval (SNSRP-109)',
  'A screening configuration version waits for your approval'),
 ('msg_notification_event',
  'A tracked item passed its follow-ups without being received (BRID-030)',
  'A tracked item passed its follow-ups without being received'),
 ('msg_notification_event',
  'A watchlist change waits for your approval (SNSRP-204)',
  'A watchlist change waits for your approval'),
 ('msg_notification_event',
  'An ACSL case you requested has a result, or a correction entry you prepared was returned, approved or posted (ACSL 2.5.4, 2.10-2.12)',
  'An ACSL case you requested has a result, or a correction entry you prepared was returned, approved or posted'),
 ('msg_notification_event',
  'An access request assigned to you was cancelled (BRD 1.007)',
  'An access request assigned to you was cancelled'),
 ('msg_notification_event',
  'An access request waits for your approval (BRD 2.002)',
  'An access request waits for your approval'),
 ('msg_notification_event',
  'An account was booked with its insurer billing number (BRID-020)',
  'An account was booked with its insurer billing number'),
 ('msg_notification_event',
  'An approved group-profile request waits for the System Administrator (BRD 3.002; UQ03)',
  'An approved group-profile request waits for the System Administrator'),
 ('msg_notification_event',
  'An endorsement request you raised was returned, approved or posted (ADJID.005/007)',
  'An endorsement request you raised was returned, approved or posted'),
 ('msg_notification_event',
  'An endorsement was booked on the cover of an open claim of yours (BRCLM.039)',
  'An endorsement was booked on the cover of an open claim of yours'),
 ('msg_notification_event',
  'An insurer SOA was validated and released to Collection and the client (BRID-021)',
  'An insurer SOA was validated and released to Collection and the client'),
 ('msg_notification_event',
  'An insurer approved or rejected a franchise request of yours (BRID-027)',
  'An insurer approved or rejected a franchise request of yours'),
 ('msg_notification_event',
  'An insurer billed a member change to validate (BRID-013, 025)',
  'An insurer billed a member change to validate'),
 ('msg_notification_event',
  'An insurer has not answered a direct payment billing in time (CMRID.011)',
  'An insurer has not answered a direct payment billing in time'),
 ('msg_notification_event',
  'An insurer production feedback was uploaded and matched (PRCID.009/022)',
  'An insurer production feedback was uploaded and matched'),
 ('msg_notification_event',
  'An insurer returned a direct payment account; it is back in your worklist (CMRID.009)',
  'An insurer returned a direct payment account; it is back in your worklist'),
 ('msg_notification_event',
  'An insurer submitted a proposal to validate (BRID-009)',
  'An insurer submitted a proposal to validate'),
 ('msg_notification_event',
  'An invoice of an EB programme became paid (BRID-021)',
  'An invoice of an EB programme became paid'),
 ('msg_notification_event',
  'An invoice you work on was locked by another team or released (RMTID.040)',
  'An invoice you work on was locked by another team or released'),
 ('msg_notification_event',
  'Collection accounts were assigned to you or taken from you (BRCLXN.052)',
  'Collection accounts were assigned to you or taken from you'),
 ('msg_notification_event',
  'Documents of a screening case are still missing (SNSRP-802)',
  'Documents of a screening case are still missing'),
 ('msg_notification_event',
  'The GL-SL reconciliation found a control account whose sub-ledger differs from the general ledger (ACSL 2.13.2)',
  'The GL-SL reconciliation found a control account whose sub-ledger differs from the general ledger'),
 ('msg_notification_event',
  'The accounts of an EB cycle were created for placement (BRID-017, 019)',
  'The accounts of an EB cycle were created for placement'),
 ('msg_notification_event',
  'The premium of a claim awaiting premium remittance was fully remitted to the insurer (BRCLM.001, OQ46)',
  'The premium of a claim awaiting premium remittance was fully remitted to the insurer'),
 ('msg_notification_event',
  'The status of a claim of one of your accounts changed (BRCLM.011; NFR 15.14)',
  'The status of a claim of one of your accounts changed'),
 ('msg_notification_event',
  'Your BrokerVerse password expires within 7 days; change it on My Profile (UAM-NFR-36)',
  'Your BrokerVerse password expires within 7 days; change it on My Profile'),
 ('msg_notification_event',
  'Your access request was approved or rejected (BRD 2.002)',
  'Your access request was approved or rejected'),
 ('msg_notification_event',
  'Your access request was returned with remarks (BRD 2.002.7)',
  'Your access request was returned with remarks'),
 ('msg_notification_event',
  'Your user data or group profiles were changed (BRD 1.002-1.006)',
  'Your user data or group profiles were changed'),
 ('nba_retention_rule',
  'Closed broking claims with their insurer lines, updates, diary and documents: 10 years online, purge after 15 years (BRD-7 p.41)',
  'Closed broking claims with their insurer lines, updates, diary and documents: 10 years online, purge after 15 years'),
 ('nba_retention_rule',
  'Closed screening cases with their reviews, documents and STRs (BRD-10 p.25)',
  'Closed screening cases with their reviews, documents and STRs'),
 ('nba_retention_rule',
  'Inactive (delisted) watchlist entries (BRD-10 p.25)',
  'Inactive (delisted) watchlist entries'),
 ('ops_flow_in_feed',
  'BIR 2307 reversal tags and certificates from Marketing Collection (CSHID.026, MKTID.013)',
  'BIR 2307 reversal tags and certificates from Marketing Collection'),
 ('ops_flow_in_feed',
  'Checks tagged for pick-up by Collection (CSHID.009, OQ01/OQ13)',
  'Checks tagged for pick-up by Collection'),
 ('ops_flow_in_feed',
  'Commission payment details for commission ORs (CSHID.007)',
  'Commission payment details for commission ORs'),
 ('ops_flow_in_feed',
  'DV number and payment status of the requests (RMTID.019, OQ02)',
  'DV number and payment status of the requests'),
 ('ops_flow_in_feed',
  'Direct payment accounts rejected by the insurer, returned to Collection (CMRID.009)',
  'Direct payment accounts rejected by the insurer, returned to Collection'),
 ('ops_flow_in_feed',
  'Direct payment lists of HO and branches (CMRID.001, OQ38)',
  'Direct payment lists of HO and branches'),
 ('ops_flow_in_feed',
  'Hold information from Marketing / Collection (RMTID.021, MKTID.003)',
  'Hold information from Marketing / Collection'),
 ('ops_flow_in_feed',
  'Insurer approval or rejection of direct payment commission billings (CMRID.009)',
  'Insurer approval or rejection of direct payment commission billings'),
 ('ops_flow_in_feed',
  'Insurer production reports and feedback (PRCID.009/010)',
  'Insurer production reports and feedback'),
 ('ops_flow_in_feed',
  'Insurer-populated remittance schedules with OR numbers (RMTID.012/013)',
  'Insurer-populated remittance schedules with OR numbers'),
 ('ops_flow_in_feed',
  'Refund dispositions handed to Collection / Disbursement (CSHID.024)',
  'Refund dispositions handed to Collection / Disbursement'),
 ('ops_flow_in_feed',
  'Remittance payment requests, refunds, 2307 reports and pass-on (RMTID.011, DBMID.001, OQ02)',
  'Remittance payment requests, refunds, 2307 reports and pass-on'),
 ('ops_flow_in_feed',
  'Special remittance requests (RMTID.030, MKTID.009)',
  'Special remittance requests'),
 ('sys_parameter',
  'Age in days above which an outstanding claim is past due: report and alert BCL_CLAIM_PAST_DUE (BRCLM.031, p.43)',
  'Age in days above which an outstanding claim is past due: report and alert BCL_CLAIM_PAST_DUE'),
 ('sys_parameter',
  'Aging brackets of the worklist, the home chart and the reports, in days (BRCLXN.001-012)',
  'Aging brackets of the worklist, the home chart and the reports, in days'),
 ('sys_parameter',
  'An open New Business account with no stage movement for this many days is reported as stalled (BRNB.115)',
  'An open New Business account with no stage movement for this many days is reported as stalled'),
 ('sys_parameter',
  'Balance range of the minimal balance write-off file (ADJID.026)',
  'Balance range of the minimal balance write-off file'),
 ('sys_parameter',
  'Banking days a check must be held (and cleared) before its payment is remitted (RMTID.017)',
  'Banking days a check must be held (and cleared) before its payment is remitted'),
 ('sys_parameter',
  'Checks outstanding clearing account credited for issued checks while DISB_CHECK_CLEARING = ON (@PAY_ACCOUNT of DISB_VOUCHER, DIS 3.27.1; real account AQ02)',
  'Checks outstanding clearing account credited for issued checks while DISB_CHECK_CLEARING = ON (@PAY_ACCOUNT of DISB_VOUCHER)'),
 ('sys_parameter',
  'Claims at one location that make it claims-prone (BRCLM.038; CLQ16)',
  'Claims at one location that make it claims-prone'),
 ('sys_parameter',
  'Claims authorization code on a direct-payment cover: ALLOW, CONFIRM (insurer payment evidence attached) or BLOCK (BRCLM.001; CLQ01)',
  'Claims authorization code on a direct-payment cover: ALLOW, CONFIRM (insurer payment evidence attached) or BLOCK'),
 ('sys_parameter',
  'Client statuses screened by the periodic run (SNSRP-301-303; to confirm, SQ11)',
  'Client statuses screened by the periodic run'),
 ('sys_parameter',
  'Comma separated e-mail addresses that receive the digest of failed watchlist records (SNSRP-202; to confirm, SQ01)',
  'Comma separated e-mail addresses that receive the digest of failed watchlist records'),
 ('sys_parameter',
  'Comma separated e-mail addresses told of every failed batch job (UAM-NFR-25)',
  'Comma separated e-mail addresses told of every failed batch job'),
 ('sys_parameter',
  'Consecutive failed logins that lock a user account (BDOI NFR 1-2; scope to confirm, CQ23)',
  'Consecutive failed logins that lock a user account'),
 ('sys_parameter',
  'Consecutive failed logins that lock a user account; applies to all users (BDOI NFR 1-2, UAM-NFR-19; CQ23 answered by BRD-11)',
  'Consecutive failed logins that lock a user account; applies to all users'),
 ('sys_parameter',
  'Currency of a claim whose cover has none (BRCLM.009)',
  'Currency of a claim whose cover has none'),
 ('sys_parameter',
  'Date the aging of a collection item counts from: BOOKING or INCEPTION (BRCLXN.049)',
  'Date the aging of a collection item counts from: BOOKING or INCEPTION'),
 ('sys_parameter',
  'Day of the month of the full rescreen of the in-scope clients; other days screen the list changes only (SNSRP-301)',
  'Day of the month of the full rescreen of the in-scope clients; other days screen the list changes only'),
 ('sys_parameter',
  'Days after the print date at which a printed or released check becomes stale (DIS 3.26.2)',
  'Days after the print date at which a printed or released check becomes stale'),
 ('sys_parameter',
  'Days after the promised date before an unpaid promise to pay is broken (BRCLXN.055)',
  'Days after the promised date before an unpaid promise to pay is broken'),
 ('sys_parameter',
  'Days after which a password must be changed, LOCAL mode; 0 = never (UAM-NFR-36; to confirm, UQ08)',
  'Days after which a password must be changed, LOCAL mode; 0 = never'),
 ('sys_parameter',
  'Days ahead in which a KYC review is listed as coming due (BRNB.110)',
  'Days ahead in which a KYC review is listed as coming due'),
 ('sys_parameter',
  'Days before a changed password may be changed again, LOCAL mode (UAM-NFR-36; to confirm, UQ08)',
  'Days before a changed password may be changed again, LOCAL mode'),
 ('sys_parameter',
  'Days before a hold cover expires when Processing is alerted (HOLD_COVER_EXPIRY job, BRNB.103)',
  'Days before a hold cover expires when Processing is alerted by the hold cover expiry monitor'),
 ('sys_parameter',
  'Days before expiry of the RA reminders while no feedback is recorded (BRID-002; EBQ02)',
  'Days before expiry of the RA reminders while no feedback is recorded'),
 ('sys_parameter',
  'Days before expiry the renewal advice is sent and the renewal cycle opened (BRID-001; EBQ02)',
  'Days before expiry the renewal advice is sent and the renewal cycle opened'),
 ('sys_parameter',
  'Days before the package end date at which PACKAGE_EXPIRING is first raised; again at 30 and 7 days (BRPM.017, PQ11)',
  'Days before the package end date at which PACKAGE_EXPIRING is first raised; again at 30 and 7 days'),
 ('sys_parameter',
  'Days before the package end date at which PACKAGE_EXPIRING is raised again after the first notice (BRPM.017, PQ11)',
  'Days before the package end date at which PACKAGE_EXPIRING is raised again after the first notice'),
 ('sys_parameter',
  'Days from a status change to the next follow-up date when the status has no follow_up_days attribute (BRCLM.019; CLQ07)',
  'Days from a status change to the next follow-up date when the status has no follow_up_days attribute'),
 ('sys_parameter',
  'Days given to insurers to reply to a quotation slip (BRNB.008)',
  'Days given to insurers to reply to a quotation slip'),
 ('sys_parameter',
  'Days insurers have to reply to a package quotation slip (reply due date, BRPM.012)',
  'Days insurers have to reply to a package quotation slip (reply due date)'),
 ('sys_parameter',
  'Days of hold cover requested from the insurer while the placement completes (BRNB.072)',
  'Days of hold cover requested from the insurer while the placement completes'),
 ('sys_parameter',
  'Default validity of a quotation in days from its creation (BRNB.043)',
  'Default validity of a quotation in days from its creation'),
 ('sys_parameter',
  'Emergency path: when true, the System Administrator may create and edit roles directly on the Roles screen (audited, alert UAM_DIRECT_ROLE_EDIT); when false, a role changes only by implementing an approved group-profile request (PQ17)',
  'Emergency path: when true, the System Administrator may create and edit roles directly on the Roles screen (audited, alert UAM_DIRECT_ROLE_EDIT); when false, a role changes only by implementing an approved group-profile request'),
 ('sys_parameter',
  'Emergency path: when true, the System Administrator may create and edit roles directly on the Roles screen (audited, alert UAM_DIRECT_ROLE_EDIT); when false, only an approved group-profile request number allows it (PQ17). True until the implement-request flow is live',
  'Emergency path: when true, the System Administrator may create and edit roles directly on the Roles screen (audited, alert UAM_DIRECT_ROLE_EDIT); when false, only an approved group-profile request number allows it. True until the implement-request flow is live'),
 ('sys_parameter',
  'Exchange rate type of Operations postings: the Comptrollership BOOK rate, 2 decimals (CSHID.012-014, OQ08)',
  'Exchange rate type of Operations postings: the Comptrollership BOOK rate, 2 decimals'),
 ('sys_parameter',
  'Fields a corporate client needs to be complete (BRNB.029). Codes: TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, SOURCE_OF_FUNDS',
  'Fields a corporate client needs to be complete. Codes: TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, SOURCE_OF_FUNDS'),
 ('sys_parameter',
  'Fields an individual client needs to be complete (BRNB.029). Codes: BIRTH_DATE, TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, NATIONALITY, SOURCE_OF_FUNDS, OCCUPATION',
  'Fields an individual client needs to be complete. Codes: BIRTH_DATE, TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, NATIONALITY, SOURCE_OF_FUNDS, OCCUPATION'),
 ('sys_parameter',
  'File naming convention of the production register sent to insurers (PRCID.006, OQ29)',
  'File naming convention of the production register sent to insurers'),
 ('sys_parameter',
  'File naming convention of the remittance extracts (RMTID.001, OQ18)',
  'File naming convention of the remittance extracts'),
 ('sys_parameter',
  'Follow-ups sent before a tracked item is escalated (BRID-030; EBQ20)',
  'Follow-ups sent before a tracked item is escalated'),
 ('sys_parameter',
  'GL account (@BANK role) debited for payments received by check, bank or electronic channels (CSHID.014, OQ07)',
  'GL account (@BANK role) debited for payments received by check, bank or electronic channels'),
 ('sys_parameter',
  'GL account (@BANK role) debited for payments received in cash over the counter (CSHID.014, OQ07)',
  'GL account (@BANK role) debited for payments received in cash over the counter'),
 ('sys_parameter',
  'Gateway request types whose DV is built automatically and routed straight to the approver (DIS 3.25.0)',
  'Gateway request types whose DV is built automatically and routed straight to the approver'),
 ('sys_parameter',
  'Gateway request whose payee is not maintained (DIS 3.25.0, AQ11/AQ12): HOLD keeps it as NO_PAYEE, raises DISB_PAYEE_NO_MATCH and a payee request and resumes it once the payee is authorised; RETURN returns it at once to its source',
  'Gateway request whose payee is not maintained: HOLD keeps it as NO_PAYEE, raises DISB_PAYEE_NO_MATCH and a payee request and resumes it once the payee is authorised; RETURN returns it at once to its source'),
 ('sys_parameter',
  'How the AML Committee decides: ANY, MAJORITY or ALL of SCR_COMMITTEE_SIZE members (SNSRP-704; to confirm, SQ15)',
  'How the AML Committee decides: ANY, MAJORITY or ALL of SCR_COMMITTEE_SIZE members'),
 ('sys_parameter',
  'Keys pairing an insurer production line with a booked invoice, tried in order: INVOICE_NO, POLICY_NO, PN_NO (PRCID.022/027, OQ30)',
  'Keys pairing an insurer production line with a booked invoice, tried in order: INVOICE_NO, POLICY_NO, PN_NO'),
 ('sys_parameter',
  'Largest number of rows of one insurer statement of account upload (ACSL 2.4.0)',
  'Largest number of rows of one insurer statement of account upload'),
 ('sys_parameter',
  'Look-back years of the claims-prone location analysis (BRCLM.038; CLQ16)',
  'Look-back years of the claims-prone location analysis'),
 ('sys_parameter',
  'Members of the AML Committee counted by the MAJORITY / ALL rule (SNSRP-704)',
  'Members of the AML Committee counted by the MAJORITY / ALL rule'),
 ('sys_parameter',
  'Minimal balances up to this amount are reversed automatically (CSHID.016, OQ11)',
  'Minimal balances up to this amount are reversed automatically'),
 ('sys_parameter',
  'Minimum age in years of an individual policyholder (BRNB.030)',
  'Minimum age in years of an individual policyholder'),
 ('sys_parameter',
  'Minutes before the system-triggered (absolute) sign-out at which the web client warns the user (BRNB.040)',
  'Minutes before the system-triggered (absolute) sign-out at which the web client warns the user'),
 ('sys_parameter',
  'Minutes of inactivity after which the web client warns that the session will sign out (BRNB.040)',
  'Minutes of inactivity after which the web client warns that the session will sign out'),
 ('sys_parameter',
  'Month and day (MM-DD) by which the previous year must be closed; YEAR_END_CLOSE_DUE is raised before (FRBS 2.7.x)',
  'Month and day (MM-DD) by which the previous year must be closed; YEAR_END_CLOSE_DUE is raised before'),
 ('sys_parameter',
  'Month-end close only for the previous month and year (FRBS 2.6.1, AQ04)',
  'Month-end close only for the previous month and year'),
 ('sys_parameter',
  'Months between periodic KYC reviews of high risk clients (BRNB.110)',
  'Months between periodic KYC reviews of high risk clients'),
 ('sys_parameter',
  'Months between periodic KYC reviews of standard and low risk clients (BRNB.110)',
  'Months between periodic KYC reviews of standard and low risk clients'),
 ('sys_parameter',
  'Net outstanding PR above which an invoice enters the collection worklist (BRCLXN.005-007; value to confirm, CQ03)',
  'Net outstanding PR above which an invoice enters the collection worklist'),
 ('sys_parameter',
  'ON: issued checks are credited to checks outstanding until negotiated; OFF: to the bank at approval (DIS 3.26.1, 3.27.1)',
  'ON: issued checks are credited to checks outstanding until negotiated; OFF: to the bank at approval'),
 ('sys_parameter',
  'Over-adjustment baseline: cumulative adjustments of an invoice above this percent of its original premium need an override reason and raise ADJ_OVER_BASELINE (ADJID.028, OQ37)',
  'Over-adjustment baseline: cumulative adjustments of an invoice above this percent of its original premium need an override reason and raise ADJ_OVER_BASELINE'),
 ('sys_parameter',
  'Paid AR greater than DTIP: EXCLUDE the invoice from extraction or CAP the remittance at the DTIP (RMTID.014, OQ19)',
  'Paid AR greater than DTIP: EXCLUDE the invoice from extraction or CAP the remittance at the DTIP'),
 ('sys_parameter',
  'Post the GL entry of the direct payment PR reversal and reinstatement (OPS_DP_PR_REVERSAL / OPS_DP_REINSTATE). Off while booking posts no premium receivable for direct payment invoices; the ledger reversal is always recorded (MKTID.012, OQ07/OQ38)',
  'Post the GL entry of the direct payment PR reversal and reinstatement (OPS_DP_PR_REVERSAL / OPS_DP_REINSTATE). Off while booking posts no premium receivable for direct payment invoices; the ledger reversal is always recorded'),
 ('sys_parameter',
  'Prefix of package quotation slip numbers; the year is appended (PQS-<yyyy>-n, BRPM.012)',
  'Prefix of package quotation slip numbers; the year is appended (PQS-<yyyy>-n)'),
 ('sys_parameter',
  'Prefix of package request numbers; the year is appended (PKR-<yyyy>-n, BRPM.008)',
  'Prefix of package request numbers; the year is appended (PKR-<yyyy>-n)'),
 ('sys_parameter',
  'Prefix of proposal slip numbers (<prefix>-<yyyy>-nnnnnn), BRNB.017',
  'Prefix of proposal slip numbers (<prefix>-<yyyy>-nnnnnn)'),
 ('sys_parameter',
  'Prefix of quotation request numbers (<prefix>-<yyyy>-nnnnnn), BRNB.041',
  'Prefix of quotation request numbers (<prefix>-<yyyy>-nnnnnn)'),
 ('sys_parameter',
  'Prefix of quotation slip numbers (<prefix>-<yyyy>-nnnnnn), BRNB.008',
  'Prefix of quotation slip numbers (<prefix>-<yyyy>-nnnnnn)'),
 ('sys_parameter',
  'Prefix of the PRF marketing reference (<prefix>-<yyyy>-nnnnnn), BRNB.006 (UX-1)',
  'Prefix of the PRF marketing reference (<prefix>-<yyyy>-nnnnnn)'),
 ('sys_parameter',
  'Prefix of the screening case number <prefix>-yyyy-nnnnnn (SNSRP-401)',
  'Prefix of the screening case number <prefix>-yyyy-nnnnnn'),
 ('sys_parameter',
  'Previous passwords a user may not reuse, LOCAL mode (UAM-NFR-36; to confirm, UQ08)',
  'Previous passwords a user may not reuse, LOCAL mode'),
 ('sys_parameter',
  'Product lines whose bookings need the insurer billing number, unique per insurer (BRID-020; EBQ18)',
  'Product lines whose bookings need the insurer billing number, unique per insurer'),
 ('sys_parameter',
  'Production reconciliation tolerance: differences up to this amount are matched (PRCID.026)',
  'Production reconciliation tolerance: differences up to this amount are matched'),
 ('sys_parameter',
  'Raise the endorsement request of a member change only after its billing is paid (p.3; EBQ16)',
  'Raise the endorsement request of a member change only after its billing is paid'),
 ('sys_parameter',
  'Recipient groups (list PKG_ADVISORY_GROUP) proposed on a new package advisory (BRPM.016, PQ12)',
  'Recipient groups (list PKG_ADVISORY_GROUP) proposed on a new package advisory'),
 ('sys_parameter',
  'Regular corporate income tax rate in percent used by the 1702-Q / 1702 worksheets (AQ07)',
  'Regular corporate income tax rate in percent used by the 1702-Q / 1702 worksheets'),
 ('sys_parameter',
  'Regular expression of a new user ID on enrolment requests (UAM-NFR-13; to confirm, UQ05)',
  'Regular expression of a new user ID on enrolment requests'),
 ('sys_parameter',
  'Regular expression of the invoice number of "For application to invoice": EBIX I######## or BrokerVerse BI-... (BRCLXN.047, CQ13)',
  'Regular expression of the invoice number of "For application to invoice": EBIX I######## or BrokerVerse BI-...'),
 ('sys_parameter',
  'Remaining check leaves of a paying account at which CHECK_SERIES_LOW is raised (DIS 2.23.x)',
  'Remaining check leaves of a paying account at which CHECK_SERIES_LOW is raised'),
 ('sys_parameter',
  'SLA hours of the MBS package set-up (BRPM.015, PQ08)',
  'SLA hours of the MBS package set-up'),
 ('sys_parameter',
  'SLA hours of the ManCom sign-off (BRPM.015, PQ07/PQ08)',
  'SLA hours of the ManCom sign-off'),
 ('sys_parameter',
  'SLA hours of the Marketing approval of a package request (BRPM.008/021, PQ08)',
  'SLA hours of the Marketing approval of a package request'),
 ('sys_parameter',
  'SLA hours of the TSU Team Head approval (BRPM.009, PQ08)',
  'SLA hours of the TSU Team Head approval'),
 ('sys_parameter',
  'SLA hours of the TSU Team Lead review and recommendation (BRPM.009, PQ08)',
  'SLA hours of the TSU Team Lead review and recommendation'),
 ('sys_parameter',
  'SLA hours of the insurer negotiation stage (BRPM.010, PQ08)',
  'SLA hours of the insurer negotiation stage'),
 ('sys_parameter',
  'Share of the premium applied for accounts of clients withholding 2% creditable tax (CSHID.020)',
  'Share of the premium applied for accounts of clients withholding 2% creditable tax'),
 ('sys_parameter',
  'Sign-in mode: LOCAL (BrokerVerse passwords) or DIRECTORY (BDO EUA / AD by Windows ID, once the adapter exists) (UAM-NFR-11, 17; Q42, UQ04)',
  'Sign-in mode: LOCAL (BrokerVerse passwords) or DIRECTORY (BDO EUA / AD by Windows ID, once the adapter exists)'),
 ('sys_parameter',
  'Source modules of the broking books: their postings are refused once the BROKING books of the period are closed (FRBS 3.4.0)',
  'Source modules of the broking books: their postings are refused once the BROKING books of the period are closed'),
 ('sys_parameter',
  'Source of the Operations BOOK rate: CLOSING_PREV_MONTH copies the revaluation rate of the previous month end, MANUAL keeps it by hand (FRBS 2.2.0, OQ08, AQ03)',
  'Source of the Operations BOOK rate: CLOSING_PREV_MONTH copies the revaluation rate of the previous month end, MANUAL keeps it by hand'),
 ('sys_parameter',
  'TAT: days for Processing to submit the placement slip (p.42)',
  'TAT: days for Processing to submit the placement slip'),
 ('sys_parameter',
  'TAT: working days for Processing to validate the final SOA (p.42; alert EB_SOA_VALIDATION_LATE)',
  'TAT: working days for Processing to validate the final SOA (alert EB_SOA_VALIDATION_LATE)'),
 ('sys_parameter',
  'TAT: working days for the insurer certificate of cover (p.42)',
  'TAT: working days for the insurer certificate of cover'),
 ('sys_parameter',
  'TAT: working days for the insurer policy / contract and billing / SOA (p.42)',
  'TAT: working days for the insurer policy / contract and billing / SOA'),
 ('sys_parameter',
  'TAT: working days per step of an inclusion / deletion (p.42)',
  'TAT: working days per step of an inclusion / deletion'),
 ('sys_parameter',
  'TAT: working days to book once billing is validated (p.42)',
  'TAT: working days to book once billing is validated'),
 ('sys_parameter',
  'TAT: working days to check the policy / contract against the proposal (p.42)',
  'TAT: working days to check the policy / contract against the proposal'),
 ('sys_parameter',
  'TAT: working days to collect the premium upon SOA / billing receipt (p.42)',
  'TAT: working days to collect the premium upon SOA / billing receipt'),
 ('sys_parameter',
  'TAT: working days to release the SOA to Collection and the policy to the client (p.42)',
  'TAT: working days to release the SOA to Collection and the policy to the client'),
 ('sys_parameter',
  'TAT: working days to request placement and booking upon client confirmation (p.42)',
  'TAT: working days to request placement and booking upon client confirmation'),
 ('sys_parameter',
  'TAT: working days to send the client confirmation to the insurer (p.42)',
  'TAT: working days to send the client confirmation to the insurer'),
 ('sys_parameter',
  'TAT: working days to send the request for quotation upon franchise approval (p.42)',
  'TAT: working days to send the request for quotation upon franchise approval'),
 ('sys_parameter',
  'TAT: working days to submit a franchise request upon complete documents (p.42)',
  'TAT: working days to submit a franchise request upon complete documents'),
 ('sys_parameter',
  'TAT: working days to submit, validate and release member cards (p.42)',
  'TAT: working days to submit, validate and release member cards'),
 ('sys_parameter',
  'Text telling the client how the e-policy password is built (BRNB.077; the BDOI convention is parked, Q07)',
  'Text telling the client how the e-policy password is built'),
 ('sys_parameter',
  'The expiry monitor drafts a RENEW package request for packages reaching the notice period (BRPM.017, PQ11)',
  'The expiry monitor drafts a RENEW package request for packages reaching the notice period'),
 ('sys_parameter',
  'Time (PHT, HH:MM) at which the broking books are closed on the last day of the month (FRBS 3.4.0/3.4.1, AQ04)',
  'Time (PHT, HH:MM) at which the broking books are closed on the last day of the month'),
 ('sys_parameter',
  'Upper bounds in days of the claims ageing buckets: 0-30, 31-60, 61-90, 91-180, 181+ (BRCLM.025/026)',
  'Upper bounds in days of the claims ageing buckets: 0-30, 31-60, 61-90, 91-180, 181+'),
 ('sys_parameter',
  'When the Insurance Advice of a mortgaged account is generated automatically: ON_POLICY_ISSUE, ON_PLACEMENT or MANUAL (BRNB.095, Q30)',
  'When the Insurance Advice of a mortgaged account is generated automatically: ON_POLICY_ISSUE, ON_PLACEMENT or MANUAL'),
 ('sys_parameter',
  'When true, account submission and placement are refused while the client has an open true or potential match (optional gate, SQ07; off: screening informs, it does not block)',
  'When true, account submission and placement are refused while the client has an open true or potential match (optional gate; off: screening informs, it does not block)'),
 ('sys_parameter',
  'When true, an approved group-profile or role-permission request applies at its last approval; when false it waits for the System Administrator to implement it (BRD-11 p.6; UQ03)',
  'When true, an approved group-profile or role-permission request applies at its last approval; when false it waits for the System Administrator to implement it'),
 ('sys_parameter',
  'When true, an approved group-profile or role-permission request applies at once (today''s behaviour); when false it waits for the System Administrator to implement it (BRD-11 p.6; UQ03)',
  'When true, an approved group-profile or role-permission request applies at once (today''s behaviour); when false it waits for the System Administrator to implement it'),
 ('sys_parameter',
  'When true, any holder of ACCESS_APPROVE may decide a request, not only the approver chosen by the requester (UQ02)',
  'When true, any holder of ACCESS_APPROVE may decide a request, not only the approver chosen by the requester'),
 ('sys_parameter',
  'Withholding tax rate (percent) of the early-incentive service invoice (DIS 3.29.1, AQ25)',
  'Withholding tax rate (percent) of the early-incentive service invoice'),
 ('sys_parameter',
  'Working days an insurer has to answer a direct payment commission billing (CMRID.011)',
  'Working days an insurer has to answer a direct payment commission billing'),
 ('sys_parameter',
  'Working days between follow-ups of a pending tracked item (BRID-030; EBQ20)',
  'Working days between follow-ups of a pending tracked item'),
 ('sys_parameter',
  'Working days for the insurer franchise decision (BRID-027; EBQ07)',
  'Working days for the insurer franchise decision'),
 ('sys_parameter',
  'Working days to advise the client of the franchise outcome (BRID-029)',
  'Working days to advise the client of the franchise outcome'),
 ('sys_parameter',
  'Working hours; an access request submitted outside them needs a second approval (UAM-NFR-40; to confirm, UQ07)',
  'Working hours; an access request submitted outside them needs a second approval');

do $$
declare
  c record;
begin
  for c in
    select distinct m.tbl, col.column_name
    from msg0_text m
    join information_schema.columns col
      on col.table_schema = current_schema()
     and col.table_name = m.tbl
     and col.data_type in ('text', 'character varying')
  loop
    execute format(
        'update %I t set %I = m.new_text from msg0_text m where m.tbl = %L and t.%I = m.old_text',
        c.tbl, c.column_name, c.tbl, c.column_name);
  end loop;
end
$$;

drop table msg0_text;
