-- =====================================================================================
-- iNXT BrokerVerse - V1123 Product Maintenance: other charges billed with the premium and the tax
-- status of the insurers (BDOI inputs v1.1, questions TX-Q02 and TX-Q04; templates PM-04 and R04).
--   cat_other_charge  charges billed with the premium besides the taxes (CTPL COCAF / LTO
--                     authentication fee, notarial fee, policy or documentation fee): per line
--                     or product, a fixed amount or a rate of the net premium, the VAT treatment
--                     and the GL account; effective-dated, maker-checker. The premium calculator
--                     adds them only while OTHER_CHARGES_ENABLED is true (delivered off until
--                     BDOI confirms that BIBS bills them).
--   cat_insurer       tax_status: VAT_REGISTERED (VAT on premium) or NON_VAT (premium tax);
--                     blank keeps the tax of the product line.
-- =====================================================================================
create table cat_other_charge (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    charge_code     varchar(30)    not null,
    name            varchar(100)   not null,
    line_code       varchar(30)    references cat_product_line (code),
    product_code    varchar(30)    references cat_product (code),
    basis           varchar(10)    not null
        constraint ck_cat_other_charge_basis check (basis in ('AMOUNT', 'RATE')),
    value           numeric(19, 8) not null
        constraint ck_cat_other_charge_value check (value >= 0),
    vat_treatment   varchar(12)    not null default 'VATABLE'
        constraint ck_cat_other_charge_vat check (vat_treatment in ('VATABLE', 'EXEMPT',
            'ZERO_RATED')),
    gl_account_code varchar(30)    not null,
    effective_from  date           not null,
    effective_to    date,
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_cat_other_charge_rate check (basis <> 'RATE' or value <= 100),
    constraint ck_cat_other_charge_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_cat_other_charge_code on cat_other_charge (charge_code, effective_from);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by)
values ('OTHER_CHARGES_ENABLED', 'false', 'BOOLEAN', 'PRODUCT_MAINTENANCE',
    'Bill the other charges of the products (documentation, notarial and authentication fees) with the premium',
    null, null, now(), 'SYSTEM');

alter table cat_insurer add column tax_status varchar(15)
    constraint ck_cat_insurer_tax_status check (tax_status in ('VAT_REGISTERED', 'NON_VAT'));
