-- =====================================================================================
-- iNXT BrokerVerse - V1160 Platform consistency: product module switches.
--   sys_product_module          one switch per product module (code of system.domain.ProductModule);
--                               a change is requested with a reason and applied when another user
--                               approves it (pending_* columns), the last change is kept (changed_*).
--   sys_module_profile          named sets of switches; applying one requests every differing change.
--   sys_module_profile_module   the modules a profile switches off (a module not listed is on).
-- Menus, APIs, permissions, the Report Centre, dashboard widgets and scheduled jobs follow the switches.
-- Initial state: the insurance broker profile, the modules of the insurer suite (underwriting, insurer
-- claims, reinsurance, actuarial reserves, consolidation, insurer tax schedules) are off; this is the
-- state V1064 set up by withdrawing their permissions.
-- Permissions: MODULE_SWITCH_MANAGE (system administrator, requests), MODULE_SWITCH_APPROVE
-- (information security officer, approves).
-- =====================================================================================

create table sys_product_module (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    code            varchar(40)  not null,
    enabled         boolean      not null,
    sort_order      integer      not null,
    pending_enabled boolean,
    pending_reason  varchar(500),
    pending_by      varchar(50),
    pending_at      timestamptz,
    changed_reason  varchar(500),
    changed_by      varchar(50),
    changed_at      timestamptz,
    approved_by     varchar(50),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_sys_product_module_code unique (code),
    constraint ck_sys_product_module_pending check (
        (pending_enabled is null and pending_by is null and pending_at is null)
        or (pending_enabled is not null and pending_by is not null and pending_at is not null
            and pending_reason is not null))
);

create table sys_module_profile (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    code        varchar(40)  not null,
    name        varchar(100) not null,
    description varchar(400) not null,
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_sys_module_profile_code unique (code)
);

create table sys_module_profile_module (
    profile_id  bigint      not null references sys_module_profile (id),
    module_code varchar(40) not null references sys_product_module (code),
    enabled     boolean     not null,
    primary key (profile_id, module_code)
);

insert into sys_product_module (code, enabled, sort_order, created_at, created_by)
values ('NEW_BUSINESS', true, 10, now(), 'SYSTEM'),
       ('PRODUCT_MAINTENANCE', true, 20, now(), 'SYSTEM'),
       ('OPERATIONS', true, 30, now(), 'SYSTEM'),
       ('COLLECTIONS', true, 40, now(), 'SYSTEM'),
       ('ACCOUNTING_DISBURSEMENT', true, 50, now(), 'SYSTEM'),
       ('RENEWAL', true, 60, now(), 'SYSTEM'),
       ('CLAIMS_HANDLING', true, 70, now(), 'SYSTEM'),
       ('EMPLOYEE_BENEFITS', true, 80, now(), 'SYSTEM'),
       ('CUSTOMER_SERVICING', true, 90, now(), 'SYSTEM'),
       ('SANCTION_SCREENING', true, 100, now(), 'SYSTEM'),
       ('SUBMITTED_POLICIES', true, 110, now(), 'SYSTEM'),
       ('DATA_MIGRATION', true, 120, now(), 'SYSTEM'),
       ('PAYABLES', true, 130, now(), 'SYSTEM'),
       ('RECEIVABLES', true, 140, now(), 'SYSTEM'),
       ('ASSETS_INVESTMENTS', true, 150, now(), 'SYSTEM'),
       ('BUDGET', true, 160, now(), 'SYSTEM'),
       ('TAX_STATUTORY', true, 170, now(), 'SYSTEM'),
       ('UNDERWRITING', false, 180, now(), 'SYSTEM'),
       ('INSURER_CLAIMS', false, 190, now(), 'SYSTEM'),
       ('REINSURANCE', false, 200, now(), 'SYSTEM'),
       ('ACTUARIAL_RESERVES', false, 210, now(), 'SYSTEM'),
       ('CONSOLIDATION', false, 220, now(), 'SYSTEM'),
       ('INSURER_TAX', false, 230, now(), 'SYSTEM');

insert into sys_module_profile (code, name, description, created_at, created_by)
values ('INSURANCE_BROKER', 'Insurance broker',
        'Broking, operations, finance and servicing modules on; the insurer suite (underwriting, insurer claims, reinsurance, actuarial reserves, consolidation, insurer tax schedules) off',
        now(), 'SYSTEM'),
       ('COMPLETE_SUITE', 'Complete suite',
        'Every product module on, the insurer suite included (testing and training of the insurer stories)',
        now(), 'SYSTEM');

insert into sys_module_profile_module (profile_id, module_code, enabled)
select p.id, m.code, false
from sys_module_profile p
cross join (values ('UNDERWRITING'), ('INSURER_CLAIMS'), ('REINSURANCE'), ('ACTUARIAL_RESERVES'),
                   ('CONSOLIDATION'), ('INSURER_TAX')) as m(code)
where p.code = 'INSURANCE_BROKER';

-- ---------- Permissions (area and action class) and grants ------------------------------------
insert into sec_permission_action (permission, area, action)
values ('MODULE_SWITCH_MANAGE', 'ADMINISTRATION', 'AMEND'),
       ('MODULE_SWITCH_APPROVE', 'ADMINISTRATION', 'APPROVE')
on conflict (permission, action) do nothing;

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values ('SYSADMIN', 'MODULE_SWITCH_MANAGE'), ('FIN_ADMIN', 'MODULE_SWITCH_MANAGE'),
             ('INFOSEC_OFFICER', 'MODULE_SWITCH_APPROVE')) as g(role_code, permission)
  on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);
