-- =====================================================================================
-- iNXT BrokerVerse - V1182 Platform authentication: single sign-on (AUTH_MODE OIDC or SAML).
--   sec_sso_request  a sign-in sent to the identity provider: the SHA-256 of its state (the OIDC
--                    state or the SAML RelayState), the PKCE verifier and nonce (OIDC) or the
--                    request ID (SAML); used once, valid 10 minutes
--   sec_sso_ticket   the one-time ticket the web client redeems for the session after the provider
--                    answered (SHA-256 only; valid 2 minutes, used once)
--   AUTH_MODE        now also OIDC and SAML (the provider itself is configured per deployment)
-- =====================================================================================

create table sec_sso_request (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    state_hash    varchar(64)   not null,
    protocol      varchar(10)   not null,
    code_verifier varchar(128),
    nonce         varchar(128),
    request_id    varchar(80),
    created_at    timestamptz   not null,
    expires_at    timestamptz   not null,
    used_at       timestamptz,
    constraint uq_sec_sso_request_state unique (state_hash),
    constraint ck_sec_sso_request_protocol check (protocol in ('OIDC', 'SAML'))
);
create index ix_sec_sso_request_request_id on sec_sso_request (request_id) where request_id is not null;
create index ix_sec_sso_request_expiry on sec_sso_request (expires_at);

create table sec_sso_ticket (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    ticket_hash varchar(64)   not null,
    username    varchar(50)   not null,
    method      varchar(10)   not null,
    created_at  timestamptz   not null,
    expires_at  timestamptz   not null,
    used_at     timestamptz,
    constraint uq_sec_sso_ticket unique (ticket_hash),
    constraint ck_sec_sso_ticket_method check (method in ('OIDC', 'SAML'))
);
create index ix_sec_sso_ticket_expiry on sec_sso_ticket (expires_at);

update sys_parameter
   set description = 'Sign-in mode: LOCAL (passwords held by the system), DIRECTORY (the client''s directory), OIDC or SAML (the client''s identity provider; local passwords only for the break-glass administrators)'
 where param_key = 'AUTH_MODE';
