-- =====================================================================================
-- iNXT BrokerVerse - V1181 Platform authentication: the second factor (TOTP, RFC 6238).
--   sec_user_mfa            the authenticator app of a user: the secret encrypted with AES-256-GCM
--                           (key from the environment, never in the database), PENDING until the
--                           first code confirms it, then ACTIVE; the last step used (no code twice)
--   sec_mfa_recovery_code   ten single-use recovery codes per enrolment (SHA-256 only)
--   sec_mfa_trusted_device  devices remembered for the second factor (SHA-256 of the token); only
--                           when MFA_REMEMBER_DEVICE_DAYS > 0 (0, off, as delivered)
--   sec_mfa_reset_request   an administrator's reset of a user's second factor, applied only when a
--                           holder of MFA_RESET_APPROVE other than the requester approves it
--   Parameters (SECURITY: every change needs a second approval): MFA_POLICY ALL, PRIVILEGED (users
--   holding a role of privilege level HIGH or ADMIN) or OFF; MFA_REMEMBER_DEVICE_DAYS;
--   MFA_ISSUER_NAME (the account name shown in the authenticator app).
-- =====================================================================================

create table sec_user_mfa (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    username       varchar(50)  not null,
    secret_cipher  varchar(200) not null,
    status         varchar(10)  not null,
    created_at     timestamptz  not null,
    activated_at   timestamptz,
    last_used_step bigint,
    last_used_at   timestamptz,
    constraint ck_sec_user_mfa_status check (status in ('PENDING', 'ACTIVE')),
    constraint ck_sec_user_mfa_active check ((status = 'ACTIVE') = (activated_at is not null))
);
create unique index uq_sec_user_mfa on sec_user_mfa (lower(username), status);

create table sec_mfa_recovery_code (
    id         bigint generated by default as identity primary key,
    version    bigint       not null default 0,
    username   varchar(50)  not null,
    code_hash  varchar(64)  not null,
    created_at timestamptz  not null,
    used_at    timestamptz
);
create index ix_sec_mfa_recovery_code_user on sec_mfa_recovery_code (lower(username));

create table sec_mfa_trusted_device (
    id         bigint generated by default as identity primary key,
    username   varchar(50)  not null,
    token_hash varchar(64)  not null,
    created_at timestamptz  not null,
    expires_at timestamptz  not null,
    constraint uq_sec_mfa_trusted_device unique (token_hash)
);
create index ix_sec_mfa_trusted_device_user on sec_mfa_trusted_device (lower(username));

create table sec_mfa_reset_request (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    username      varchar(50)   not null,
    reason        varchar(500)  not null,
    status        varchar(10)   not null default 'PENDING',
    requested_by  varchar(50)   not null,
    requested_at  timestamptz   not null,
    decided_by    varchar(50),
    decided_at    timestamptz,
    decision_note varchar(500),
    constraint ck_sec_mfa_reset_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    constraint ck_sec_mfa_reset_decided check ((status = 'PENDING') = (decided_at is null)),
    constraint ck_sec_mfa_reset_four_eyes check (status <> 'APPROVED' or lower(decided_by) <> lower(requested_by))
);
create unique index uq_sec_mfa_reset_pending on sec_mfa_reset_request (lower(username)) where status = 'PENDING';
create index ix_sec_mfa_reset_status on sec_mfa_reset_request (status, requested_at desc);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('MFA_POLICY', 'PRIVILEGED', 'STRING', 'SECURITY',
     'Who must confirm a sign-in with an authenticator app code: ALL users, PRIVILEGED users (a role of privilege level HIGH or ADMIN) or OFF (only users who enrolled themselves)',
     null, null, now(), 'SYSTEM'),
    ('MFA_REMEMBER_DEVICE_DAYS', '0', 'INTEGER', 'SECURITY',
     'Days a device may be remembered after a code is confirmed, so the code is not asked again on it; 0 = never remembered',
     0, 30, now(), 'SYSTEM'),
    ('MFA_ISSUER_NAME', 'iNXT BrokerVerse', 'STRING', 'SECURITY',
     'Name of the system shown next to the account in the authenticator app', null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('MFA_RESET_TO_APPROVE', 'Second factor reset to approve', 'USER_ACCESS',
     'A reset of a user''s authenticator app waits for your approval', true, true, 720),
    ('MFA_RESET_DONE', 'Second factor reset', 'USER_ACCESS',
     'Your authenticator app was reset by the administrators; enrol it again at your next sign-in', true, true, 730)
on conflict (code) do nothing;

insert into sec_permission_action (permission, area, action)
values
    ('MFA_RESET', 'ADMINISTRATION', 'AMEND'),
    ('MFA_RESET_APPROVE', 'ADMINISTRATION', 'APPROVE')
on conflict (permission, action) do nothing;

-- The system administrators request resets; the approvers of the security settings approve them.
insert into sec_role_permission (role_id, permission)
select r.id, 'MFA_RESET'
from sec_role r
where r.code = 'SYSADMIN'
  and not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = 'MFA_RESET');

insert into sec_role_permission (role_id, permission)
select distinct holder.role_id, 'MFA_RESET_APPROVE'
from sec_role_permission holder
where holder.permission = 'SECURITY_PARAMETER_APPROVE'
  and not exists (select 1 from sec_role_permission x where x.role_id = holder.role_id and x.permission = 'MFA_RESET_APPROVE');
