-- =====================================================================================
-- iNXT BrokerVerse - V1240 Platform data scope (range V1240-V1249): the companies and branches each
-- user may act for (docs/architecture/DATA_SCOPE_DESIGN.md).
--   sec_user.all_companies  true = every company and branch, present and future. The default
--                           backfills every existing user and applies to every user created later,
--                           so a deployment keeps its behaviour until an administrator narrows a
--                           user's scope.
--   sec_user_data_scope     the granted companies of a user whose all_companies is false: one row
--                           per company with all its branches (branch_id null) or one row per
--                           granted branch of the company. A company is granted either with all
--                           its branches or with a list of branches (service rule).
--   sec_access_change_log   new activity DATA_SCOPE_CHANGED (attribute dataScope, from / to in the
--                           text form ALL or company:*;company:branch,branch).
-- =====================================================================================

alter table sec_user add column all_companies boolean not null default true;

create table sec_user_data_scope (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null references sec_user (id) on delete cascade,
    company_id  bigint      not null references org_company (id),
    branch_id   bigint      references org_branch (id),
    created_at  timestamptz not null,
    created_by  varchar(50) not null
);
create unique index uq_sec_user_data_scope_company on sec_user_data_scope (user_id, company_id)
    where branch_id is null;
create unique index uq_sec_user_data_scope_branch on sec_user_data_scope (user_id, company_id, branch_id)
    where branch_id is not null;
create index ix_sec_user_data_scope_user on sec_user_data_scope (user_id);

alter table sec_access_change_log drop constraint ck_sec_access_change_activity;
alter table sec_access_change_log add constraint ck_sec_access_change_activity check (activity in (
    'CREATE_USER', 'MODIFY_USER', 'ROLES_CHANGED', 'DISABLE_USER', 'ENABLE_USER', 'UNLOCK',
    'PASSWORD_RESET', 'CREATE_ROLE', 'ROLE_PERMISSIONS', 'DEACTIVATE_ROLE', 'REACTIVATE_ROLE',
    'DATA_SCOPE_CHANGED'));

-- A user access request may carry the data scope it asks for (text form; null = unchanged).
alter table nba_access_request add column data_scope varchar(2000);
