-- =====================================================================================
-- iNXT BrokerVerse - V1260 Texts to users name the system of the deployment, not the platform.
-- E-mails, notifications, report footers and the authenticator app take the system name from the
-- theme pack of the deployment (system.name of brand.properties). The delivered texts below named
-- the platform; they now read without it, or leave the name to the theme pack. Each text is
-- replaced only where it still holds the delivered value: a text an administrator has since
-- changed is kept.
-- =====================================================================================
update msg_notification_event
set description = 'Your password expires within 7 days; change it on My Profile'
where code = 'PASSWORD_EXPIRY_NOTICE'
  and description = 'Your BrokerVerse password expires within 7 days; change it on My Profile';

update sys_parameter
set description = 'Regular expression of the invoice number of "For application to invoice": EBIX I######## or BI-... of this system'
where param_key = 'CLX_INVOICE_NO_PATTERN'
  and description = 'Regular expression of the invoice number of "For application to invoice": EBIX I######## or BrokerVerse BI-...';

update sys_parameter
set description = replace(description, 'LOCAL (BrokerVerse passwords)', 'LOCAL (passwords held by this system)')
where param_key = 'AUTH_MODE'
  and description like 'Sign-in mode: LOCAL (BrokerVerse passwords)%';

update sys_parameter
set description = 'From address of e-mails sent by this system (quotations, slips, e-policies, invoices)'
where param_key = 'MAIL_FROM_ADDRESS'
  and description = 'From address of e-mails sent by BrokerVerse (quotations, slips, e-policies, invoices)';

-- Blank issuer: the authenticator app shows the system name of the theme pack.
update sys_parameter
set param_value = '',
    description = 'Name of the system shown next to the account in the authenticator app (blank = the system name of the deployment)'
where param_key = 'MFA_ISSUER_NAME'
  and param_value = 'iNXT BrokerVerse';

-- The system name and the report code are printed at the foot of every page already.
update sys_parameter
set param_value = 'Confidential - for internal use only.'
where param_key = 'REPORT_FOOTER_TEXT'
  and param_value = 'Generated by iNXT BrokerVerse. Confidential - for internal use only.';
