-- =====================================================================================
-- iNXT BrokerVerse - V1320 Configuration Promotion (platform module configpromo): move the set-up of
-- the platform (masters, configuration, rules, validations) from one environment to another without
-- transactions (client decision of 8 October 2026; docs/modules/CONFIG_PROMOTION.md).
--   cfp_package          exported, uploaded and snapshot packages (the file is in the file store)
--   cfp_import           an import: options, dry run summary, maker-checker, apply, reconciliation
--   cfp_import_dataset   the difference and the reconciliation of each dataset of an import
--   cfp_baseline         a package marked as the configuration baseline of the environment
--   Permissions CONFIG_EXPORT, CONFIG_IMPORT_PREPARE, CONFIG_BASELINE_MANAGE (System Administrator)
--   and CONFIG_IMPORT_APPROVE (new group profile Configuration Release Approver); the two profiles are
--   kept apart by a separation-of-duties rule.
--   Parameters of the change window of production, the notified groups, the largest package and the
--   pipeline apply outside production; record class CONFIG_PACKAGE; notification events.
-- =====================================================================================

create table cfp_package (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    package_no          varchar(30)   not null,
    kind                varchar(20)   not null,
    package_uuid        varchar(36)   not null,
    mode                varchar(20)   not null,
    source_environment  varchar(40)   not null,
    platform_version    varchar(60),
    schema_version      varchar(40),
    include_users       boolean       not null default false,
    dataset_count       integer       not null,
    row_count           integer       not null,
    sha256              varchar(64)   not null,
    key_id              varchar(20)   not null,
    stored_file_id      bigint        not null references stored_file (id),
    file_name           varchar(200)  not null,
    file_size           bigint        not null,
    description         varchar(500),
    manifest            text          not null,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_cfp_package_no unique (package_no),
    constraint ck_cfp_package_kind check (kind in ('EXPORT', 'UPLOAD', 'SNAPSHOT')),
    constraint ck_cfp_package_mode check (mode in ('FULL', 'INCREMENTAL'))
);
create index ix_cfp_package_kind on cfp_package (kind, created_at desc);
create index ix_cfp_package_uuid on cfp_package (package_uuid);
create index ix_cfp_package_file on cfp_package (stored_file_id);

create table cfp_import (
    id                     bigint generated by default as identity primary key,
    version                bigint        not null default 0,
    import_no              varchar(30)   not null,
    package_id             bigint        not null references cfp_package (id),
    status                 varchar(20)   not null,
    options                text          not null,
    production             boolean       not null,
    pipeline               boolean       not null default false,
    change_reference       varchar(60),
    reason                 varchar(1000),
    compatible             boolean       not null,
    messages               text          not null,
    blocker_count          integer       not null default 0,
    warning_count          integer       not null default 0,
    added_count            integer       not null default 0,
    changed_count          integer       not null default 0,
    unchanged_count        integer       not null default 0,
    only_in_target_count   integer       not null default 0,
    prepared_by            varchar(50)   not null,
    prepared_at            timestamptz   not null,
    submitted_by           varchar(50),
    submitted_at           timestamptz,
    decided_by             varchar(50),
    decided_at             timestamptz,
    decision_note          varchar(1000),
    applied_at             timestamptz,
    snapshot_package_id    bigint        references cfp_package (id),
    rollback_of_id         bigint        references cfp_import (id),
    error_message          varchar(2000),
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_cfp_import_no unique (import_no),
    constraint ck_cfp_import_status
        check (status in ('CHECKED', 'SUBMITTED', 'APPLIED', 'REJECTED', 'FAILED', 'CANCELLED'))
);
create index ix_cfp_import_status on cfp_import (status, prepared_at desc);
create index ix_cfp_import_package on cfp_import (package_id);
create index ix_cfp_import_snapshot on cfp_import (snapshot_package_id);
create index ix_cfp_import_rollback on cfp_import (rollback_of_id);

create table cfp_import_dataset (
    id               bigint generated by default as identity primary key,
    import_id        bigint        not null references cfp_import (id),
    dataset_code     varchar(60)   not null,
    seq              integer       not null,
    added            integer       not null default 0,
    changed          integer       not null default 0,
    unchanged        integer       not null default 0,
    only_in_target   integer       not null default 0,
    blockers         integer       not null default 0,
    inserted         integer,
    updated          integer,
    deactivated      integer,
    removed          integer,
    package_rows     integer,
    target_rows      integer,
    target_total     integer,
    package_sha256   varchar(64),
    target_sha256    varchar(64),
    reconciled       boolean,
    details          text          not null,
    constraint uq_cfp_import_dataset unique (import_id, dataset_code)
);

create table cfp_baseline (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    name         varchar(120)  not null,
    package_id   bigint        not null references cfp_package (id),
    environment  varchar(40)   not null,
    remarks      varchar(500),
    active       boolean       not null default true,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_cfp_baseline_name unique (name)
);
create index ix_cfp_baseline_package on cfp_baseline (package_id);

-- ---------- Group profile, grants and separation of duties --------------------------------------
insert into sec_role (code, name, description, privilege_level, created_at, created_by)
select 'CONFIG_APPROVER', 'Configuration Release Approver',
       'Second user who approves the import of a configuration package prepared by the System Administrator',
       'ADMIN', now(), 'SYSTEM'
where not exists (select 1 from sec_role where code = 'CONFIG_APPROVER');

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values ('SYSADMIN', 'CONFIG_EXPORT'),
             ('SYSADMIN', 'CONFIG_IMPORT_PREPARE'),
             ('SYSADMIN', 'CONFIG_BASELINE_MANAGE'),
             ('CONFIG_APPROVER', 'CONFIG_IMPORT_APPROVE')) as g(role_code, permission)
  on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);

insert into sec_permission_action (permission, area, action)
select v.permission, 'ADMINISTRATION', v.action
from (values ('CONFIG_EXPORT', 'VIEW'),
             ('CONFIG_IMPORT_PREPARE', 'CREATE'),
             ('CONFIG_IMPORT_APPROVE', 'APPROVE'),
             ('CONFIG_BASELINE_MANAGE', 'AMEND')) as v(permission, action)
where not exists (select 1 from sec_permission_action x where x.permission = v.permission and x.action = v.action);

insert into nba_sod_rule (rule_code, profile_a, profile_b, description, record_status, pending_action,
                          authorized_by, authorized_at, created_at, created_by)
select 'SOD-CFG-01', 'SYSADMIN', 'CONFIG_APPROVER',
       'The user who prepares the import of a configuration package may not also approve it',
       'ACTIVE', 'NONE', 'SYSTEM', now(), now(), 'SYSTEM'
where not exists (select 1 from nba_sod_rule where rule_code = 'SOD-CFG-01');

-- ---------- Parameters ---------------------------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('CONFIG_PROMOTION_PRODUCTION_WINDOW', '', 'STRING', 'CONFIG_PROMOTION',
     'Change window in which a configuration package may be applied in production, for example SAT-SUN 20:00-06:00 (days, then the hours; an end before the start runs into the next day); empty = no window, production imports are refused',
     null, null, now(), 'SYSTEM'),
    ('CONFIG_PROMOTION_NOTIFY', 'CONFIG_IMPORT_APPROVE,CONFIG_BASELINE_MANAGE', 'CODE_LIST', 'CONFIG_PROMOTION',
     'Permissions whose holders are told when a configuration import waits for approval, is applied, rejected or fails',
     null, null, now(), 'SYSTEM'),
    ('CONFIG_PROMOTION_MAX_PACKAGE_MB', '50', 'INTEGER', 'CONFIG_PROMOTION',
     'Largest configuration package accepted, in megabytes once unpacked', 1, 500, now(), 'SYSTEM'),
    ('CONFIG_PROMOTION_PIPELINE_APPLY', 'false', 'BOOLEAN', 'CONFIG_PROMOTION',
     'Outside production only: when true, the deployment pipeline may apply its own dry-run import without a second user; production always needs the approval of a second user',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

-- ---------- Record class of the packages -------------------------------------------------------
insert into sto_record_class (code, name, bucket_class, retention_record_type, retention_period,
                              legal_hold, archive_to_ecm, description, created_at, created_by)
select 'CONFIG_PACKAGE', 'Configuration package', 'DOCUMENTS', null, 'P10Y', false, false,
       'Exported, imported and snapshot configuration packages of Configuration Promotion', now(), 'SYSTEM'
where not exists (select 1 from sto_record_class where code = 'CONFIG_PACKAGE');

-- ---------- Notification events --------------------------------------------------------------
insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('CONFIG_IMPORT_TO_APPROVE', 'Configuration import to approve', 'CONFIG_PROMOTION',
     'A configuration package was checked and waits for the approval of a second user', true, true, 720),
    ('CONFIG_IMPORT_APPLIED', 'Configuration import applied', 'CONFIG_PROMOTION',
     'A configuration package was applied to this environment; the reconciliation is on the import', true, true, 730),
    ('CONFIG_IMPORT_REJECTED', 'Configuration import rejected', 'CONFIG_PROMOTION',
     'The approver rejected a configuration import; the reason is on the import', true, false, 740),
    ('CONFIG_IMPORT_FAILED', 'Configuration import failed', 'CONFIG_PROMOTION',
     'A configuration import could not be applied; nothing of it was kept', true, true, 750)
on conflict (code) do nothing;
