-- =====================================================================================
-- iNXT BrokerVerse - V1340 Booking: history of the incentive evaluations (BRNB.107, BRRN.041;
-- FR-NB-118, FR-RN-087). Every evaluation of the incentive indicator with its trigger (booking,
-- full payment, endorsement, cancellation), the criteria matched, the endorsements considered and
-- the result; insert-only. The functional gaps of the BRD versions of 8-Oct-2026 use V1330-V1349
-- (V1330-V1339 renewal, V1340-V1349 the other modules).
-- =====================================================================================
create table bkg_incentive_evaluation (
    id               bigint generated by default as identity primary key,
    company_id       bigint       not null references org_company (id),
    invoice_no       varchar(40)  not null,
    trigger_type     varchar(20)  not null
        constraint ck_bkg_incentive_eval_trigger check (trigger_type in ('BOOKING', 'FULL_PAYMENT',
            'ENDORSEMENT', 'CANCELLATION')),
    result           varchar(20)  not null
        constraint ck_bkg_incentive_eval_result check (result in ('PENDING', 'ELIGIBLE',
            'NOT_ELIGIBLE')),
    criteria         varchar(500),
    endorsements     varchar(1000),
    reason           varchar(300) not null,
    evaluated_at     timestamptz  not null,
    evaluated_by     varchar(50)  not null
);
create index ix_bkg_incentive_eval_invoice on bkg_incentive_evaluation (invoice_no, id);
create trigger bkg_incentive_evaluation_immutable
    before update or delete on bkg_incentive_evaluation
    for each row execute function platform_row_immutable();
create trigger bkg_incentive_evaluation_no_truncate
    before truncate on bkg_incentive_evaluation
    for each statement execute function platform_refuse_truncate();
