-- =====================================================================================
-- iNXT BrokerVerse - V1 Foundation schema
-- Security, audit, organisation, currency, chart of accounts, dimensions, periods,
-- journals, ledger and document sequences.
-- Conventions: snake_case, surrogate BIGINT identity keys, NUMERIC(19,2) money,
-- NUMERIC(19,8) rates, audit columns on every master/transaction table.
-- =====================================================================================

-- ---------- Security ----------------------------------------------------------------
create table sec_role (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    code        varchar(40)  not null unique,
    name        varchar(120) not null,
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);

create table sec_role_permission (
    role_id    bigint      not null references sec_role (id),
    permission varchar(50) not null,
    primary key (role_id, permission)
);

create table sec_user (
    id                  bigint generated by default as identity primary key,
    version             bigint       not null default 0,
    username            varchar(50)  not null unique,
    full_name           varchar(120) not null,
    email               varchar(120),
    password_hash       varchar(100) not null,
    enabled             boolean      not null default true,
    locked              boolean      not null default false,
    failed_attempts     integer      not null default 0,
    last_login_at       timestamptz,
    home_branch_id      bigint,
    authorization_limit numeric(19, 2),
    created_at          timestamptz  not null,
    created_by          varchar(50)  not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);

create table sec_user_role (
    user_id bigint not null references sec_user (id),
    role_id bigint not null references sec_role (id),
    primary key (user_id, role_id)
);

-- ---------- Audit trail (insert only) -------------------------------------------------
create table audit_log (
    id          bigint generated by default as identity primary key,
    occurred_at timestamptz  not null,
    username    varchar(50)  not null,
    entity_type varchar(60)  not null,
    entity_id   varchar(60),
    action      varchar(30)  not null,
    summary     varchar(500) not null
);
create index ix_audit_time on audit_log (occurred_at);
create index ix_audit_entity on audit_log (entity_type, entity_id);
create index ix_audit_user on audit_log (lower(username), occurred_at);

-- ---------- Document numbering ------------------------------------------------------
create table document_sequence (
    sequence_key varchar(60) primary key,
    next_value   bigint      not null
);

-- ---------- Organisation --------------------------------------------------------------
create table org_company (
    id                        bigint generated by default as identity primary key,
    version                   bigint       not null default 0,
    code                      varchar(10)  not null unique,
    name                      varchar(150) not null,
    base_currency             varchar(3)    not null,
    tax_id                    varchar(30),
    address                   varchar(300),
    fiscal_year_start_month   integer      not null default 1 check (fiscal_year_start_month between 1 and 12),
    back_value_days           integer      not null default 0,
    forward_value_days        integer      not null default 0,
    retained_earnings_account varchar(30),
    record_status             varchar(30)  not null,
    authorized_by             varchar(50),
    authorized_at             timestamptz,
    created_at                timestamptz  not null,
    created_by                varchar(50)  not null,
    updated_at                timestamptz,
    updated_by                varchar(50)
);

create table org_branch (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    company_id       bigint       not null references org_company (id),
    code             varchar(10)  not null,
    name             varchar(150) not null,
    region           varchar(60),
    address          varchar(300),
    opening_date     date         not null,
    head_office      boolean      not null default false,
    forex_authorized boolean      not null default false,
    contact_phone    varchar(40),
    contact_email    varchar(120),
    manager_name     varchar(120),
    weekly_holidays  varchar(20),
    record_status    varchar(30)  not null,
    authorized_by    varchar(50),
    authorized_at    timestamptz,
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_branch_code unique (company_id, code)
);

create table org_holiday (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    company_id   bigint       not null references org_company (id),
    branch_id    bigint references org_branch (id),
    holiday_date date         not null,
    description  varchar(120) not null,
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);
create index ix_holiday_date on org_holiday (company_id, holiday_date);

-- ---------- Currency --------------------------------------------------------------------
create table cur_currency (
    code           varchar(3)   primary key,
    name           varchar(60) not null,
    symbol         varchar(5),
    decimal_places integer     not null default 2,
    active         boolean     not null default true
);

create table cur_exchange_rate (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    currency_code  varchar(3)      not null references cur_currency (code),
    rate_type      varchar(20)    not null,
    effective_date date           not null,
    rate           numeric(19, 8) not null check (rate > 0),
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_rate unique (currency_code, rate_type, effective_date)
);

-- ---------- Chart of accounts -------------------------------------------------------------
create table coa_category (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    code          varchar(10)  not null unique,
    name          varchar(120) not null,
    account_class varchar(20)  not null,
    bank_category boolean      not null default false,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);

create table coa_account (
    id                     bigint generated by default as identity primary key,
    version                bigint       not null default 0,
    company_id             bigint       not null references org_company (id),
    code                   varchar(30)  not null,
    name                   varchar(150) not null,
    short_name             varchar(40),
    account_class          varchar(20)  not null,
    level                  varchar(10)  not null,
    parent_id              bigint references coa_account (id),
    category_id            bigint references coa_category (id),
    postable               boolean      not null,
    control_account        boolean      not null default false,
    sub_ledger_type        varchar(20)  not null default 'NONE',
    allow_manual_posting   boolean      not null default true,
    cost_center_required   boolean      not null default false,
    business_line_required boolean      not null default false,
    revaluation_required   boolean      not null default false,
    reconcilable           boolean      not null default false,
    inter_branch           boolean      not null default false,
    contra_account_code    varchar(30),
    report_group           varchar(60),
    frozen                 boolean      not null default false,
    freeze_reason          varchar(200),
    opened_on              date         not null,
    closed_on              date,
    record_status          varchar(30)  not null,
    authorized_by          varchar(50),
    authorized_at          timestamptz,
    created_at             timestamptz  not null,
    created_by             varchar(50)  not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_account_code unique (company_id, code)
);
create index ix_account_parent on coa_account (parent_id);

create table coa_account_currency (
    account_id    bigint  not null references coa_account (id),
    currency_code varchar(3) not null,
    primary key (account_id, currency_code)
);

create table coa_account_branch (
    account_id bigint not null references coa_account (id),
    branch_id  bigint not null references org_branch (id),
    primary key (account_id, branch_id)
);

create table coa_account_role (
    account_id bigint      not null references coa_account (id),
    role_code  varchar(40) not null,
    primary key (account_id, role_code)
);

-- ---------- Dimensions --------------------------------------------------------------------
create table dim_value (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    dimension_type varchar(20)  not null,
    code           varchar(20)  not null,
    name           varchar(120) not null,
    active         boolean      not null default true,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_dimension unique (company_id, dimension_type, code)
);

-- ---------- Financial periods ---------------------------------------------------------
create table per_fiscal_year (
    id         bigint generated by default as identity primary key,
    version    bigint      not null default 0,
    company_id bigint      not null references org_company (id),
    year_code  integer     not null,
    start_date date        not null,
    end_date   date        not null,
    status     varchar(10) not null,
    closed_by  varchar(50),
    closed_at  timestamptz,
    created_at timestamptz not null,
    created_by varchar(50) not null,
    updated_at timestamptz,
    updated_by varchar(50),
    constraint uq_fiscal_year unique (company_id, year_code),
    constraint ck_fy_dates check (end_date > start_date)
);

create table per_period (
    id                bigint generated by default as identity primary key,
    version           bigint       not null default 0,
    fiscal_year_id    bigint       not null references per_fiscal_year (id),
    company_id        bigint       not null references org_company (id),
    period_no         integer      not null,
    name              varchar(20)  not null,
    start_date        date         not null,
    end_date          date         not null,
    status            varchar(10)  not null,
    status_changed_by varchar(50),
    status_changed_at timestamptz,
    status_reason     varchar(200),
    created_at        timestamptz  not null,
    created_by        varchar(50)  not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_period unique (fiscal_year_id, period_no)
);
create index ix_period_dates on per_period (company_id, start_date, end_date);

-- ---------- Journals ------------------------------------------------------------------------
create table jnl_batch (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    branch_id        bigint         not null references org_branch (id),
    batch_no         varchar(40)    not null,
    journal_type     varchar(20)    not null,
    status           varchar(20)    not null,
    transaction_date date           not null,
    value_date       date           not null,
    period_id        bigint references per_period (id),
    currency         varchar(3)      not null,
    narration        varchar(500)   not null,
    reference        varchar(60),
    source_module    varchar(30),
    source_reference varchar(80),
    reversal_of_id   bigint references jnl_batch (id),
    reversed_by_id   bigint references jnl_batch (id),
    total_debit      numeric(19, 2) not null,
    total_credit     numeric(19, 2) not null,
    submitted_by     varchar(50),
    submitted_at     timestamptz,
    authorized_by    varchar(50),
    authorized_at    timestamptz,
    rejected_by      varchar(50),
    rejection_reason varchar(200),
    posted_at        timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_batch_no unique (company_id, batch_no)
);
create index ix_batch_status on jnl_batch (company_id, status, value_date);
create index ix_batch_source on jnl_batch (company_id, source_module, source_reference);

create table jnl_line (
    id            bigint generated by default as identity primary key,
    batch_id      bigint         not null references jnl_batch (id),
    line_no       integer        not null,
    account_id    bigint         not null references coa_account (id),
    branch_id     bigint         not null references org_branch (id),
    side          varchar(6)     not null check (side in ('DEBIT', 'CREDIT')),
    currency      varchar(3)      not null,
    amount        numeric(19, 2) not null check (amount > 0),
    exchange_rate numeric(19, 8) not null,
    base_amount   numeric(19, 2) not null,
    cost_center   varchar(20),
    business_line varchar(20),
    party_code    varchar(30),
    reference     varchar(60),
    narration     varchar(250),
    constraint uq_line unique (batch_id, line_no)
);

-- ---------- General ledger (book of record) ---------------------------------------------
create table gl_ledger_entry (
    id            bigint generated by default as identity primary key,
    company_id    bigint         not null references org_company (id),
    branch_id     bigint         not null references org_branch (id),
    account_id    bigint         not null references coa_account (id),
    period_id     bigint         not null references per_period (id),
    value_date    date           not null,
    batch_id      bigint         not null references jnl_batch (id),
    batch_no      varchar(40)    not null,
    line_no       integer        not null,
    journal_type  varchar(20)    not null,
    currency      varchar(3)      not null,
    debit_fc      numeric(19, 2) not null,
    credit_fc     numeric(19, 2) not null,
    debit_base    numeric(19, 2) not null,
    credit_base   numeric(19, 2) not null,
    cost_center   varchar(20),
    business_line varchar(20),
    party_code    varchar(30),
    reference     varchar(60),
    narration     varchar(250),
    posted_at     timestamptz    not null,
    posted_by     varchar(50)    not null,
    constraint uq_ledger_line unique (batch_id, line_no)
);
create index ix_ledger_account_date on gl_ledger_entry (company_id, account_id, value_date);
create index ix_ledger_party on gl_ledger_entry (company_id, party_code) where party_code is not null;
create index ix_ledger_reference on gl_ledger_entry (company_id, reference) where reference is not null;

-- Posted ledger rows are immutable: block UPDATE and DELETE at database level.
create function gl_ledger_entry_immutable() returns trigger language plpgsql as $$
begin
    raise exception 'gl_ledger_entry rows are immutable; post a reversal instead';
end;
$$;
create trigger trg_ledger_immutable
    before update or delete on gl_ledger_entry
    for each row execute function gl_ledger_entry_immutable();

create table gl_daily_balance (
    company_id   bigint         not null,
    branch_id    bigint         not null,
    account_id   bigint         not null references coa_account (id),
    currency     varchar(3)      not null,
    balance_date date           not null,
    debit_fc     numeric(19, 2) not null,
    credit_fc    numeric(19, 2) not null,
    debit_base   numeric(19, 2) not null,
    credit_base  numeric(19, 2) not null,
    primary key (company_id, branch_id, account_id, currency, balance_date)
);
create index ix_daily_balance_date on gl_daily_balance (company_id, balance_date);
