-- =====================================================================================
-- iNXT BrokerVerse - V200 Claims: claim register (FNOL), involved parties, reserve changes,
-- settlements, salvage / subrogation recoveries, local purchase orders (LPO) and the
-- claim movement ledger (Reports Book estimate / paid lines, company share).
--
-- Amount conventions:
--   *_100 / 100 % columns : amounts at 100 % of the claim (before coinsurance);
--   our_* / amount        : company share (policy share %), the basis of all accounting.
-- =====================================================================================

create table clm_claim (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    company_id           bigint         not null references org_company (id),
    branch_id            bigint         not null references org_branch (id),
    claim_no             varchar(40)    not null,
    -- policy facts at registration (snapshot, so reports need no join to underwriting)
    policy_id            bigint         not null references uw_policy (id),
    policy_no            varchar(40)    not null,
    product_code         varchar(20)    not null,
    product_name         varchar(120)   not null,
    business_line        varchar(20)    not null,
    customer_code        varchar(30)    not null,
    customer_name        varchar(200)   not null,
    insured_name         varchar(200)   not null,
    intermediary_code    varchar(30),
    uw_year              integer        not null,
    share_pct            numeric(19, 8) not null check (share_pct > 0 and share_pct <= 100),
    coinsurance_leader   boolean        not null default false,
    coinsurer_code       varchar(30),
    risk_id              bigint references uw_policy_risk (id),
    risk_description     varchar(300),
    sum_insured          numeric(19, 2) not null default 0 check (sum_insured >= 0),
    -- loss details
    loss_date            date           not null,
    reported_date        date           not null,
    nature_of_loss       varchar(60)    not null,
    cause_of_loss        varchar(120)   not null,
    loss_location        varchar(200)   not null,
    description          varchar(1000)  not null,
    currency             varchar(3)     not null,
    claimant_party_id    bigint         not null references pty_party (id),
    -- lifecycle
    status               varchar(20)    not null
        check (status in ('REGISTERED', 'OPEN', 'PARTIALLY_SETTLED', 'CLOSED', 'REOPENED',
                          'REJECTED', 'WITHDRAWN')),
    status_reason        varchar(200),
    closed_on            date,
    -- running totals at 100 % (company share is derived with the share %)
    estimate_loss        numeric(19, 2) not null default 0 check (estimate_loss >= 0),
    estimate_expense     numeric(19, 2) not null default 0 check (estimate_expense >= 0),
    estimate_recovery    numeric(19, 2) not null default 0 check (estimate_recovery >= 0),
    paid_loss            numeric(19, 2) not null default 0 check (paid_loss >= 0),
    paid_expense         numeric(19, 2) not null default 0 check (paid_expense >= 0),
    recovered            numeric(19, 2) not null default 0 check (recovered >= 0),
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint clm_uq_claim_no unique (company_id, claim_no),
    constraint clm_ck_claim_dates check (reported_date >= loss_date),
    constraint clm_ck_claim_paid check (paid_loss <= estimate_loss and paid_expense <= estimate_expense)
);
create index ix_clm_claim_status on clm_claim (company_id, status);
create index ix_clm_claim_policy on clm_claim (policy_id);
create index ix_clm_claim_loss on clm_claim (company_id, loss_date);
create index ix_clm_claim_claimant on clm_claim (claimant_party_id);

create table clm_claim_party (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    claim_id    bigint       not null references clm_claim (id),
    party_id    bigint       not null references pty_party (id),
    role        varchar(20)  not null
        check (role in ('CLAIMANT', 'THIRD_PARTY', 'GARAGE', 'SURVEYOR', 'ADJUSTER')),
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint clm_uq_claim_party unique (claim_id, party_id, role)
);
create index ix_clm_claim_party_party on clm_claim_party (party_id);

-- Maker-checker columns shared by reserve changes, settlements and recoveries:
-- status PENDING_APPROVAL -> APPROVED | REJECTED; authority_amount = base-currency amount the
-- checker's authorization limit is compared with.
create table clm_reserve_change (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    claim_id           bigint         not null references clm_claim (id),
    change_no          integer        not null check (change_no > 0),
    side               varchar(10)    not null check (side in ('PAYMENT', 'RECOVERY')),
    cost_type          varchar(10)    not null check (cost_type in ('LOSS', 'EXPENSE')),
    new_estimate       numeric(19, 2) not null check (new_estimate >= 0),
    previous_estimate  numeric(19, 2),
    change_amount      numeric(19, 2),
    our_change         numeric(19, 2),
    reason             varchar(200)   not null,
    system_generated   boolean        not null default false,
    status             varchar(20)    not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    submitted_by       varchar(50)    not null,
    submitted_at       timestamptz    not null,
    approved_by        varchar(50),
    approved_at        timestamptz,
    approval_date      date,
    rejection_reason   varchar(200),
    authority_amount   numeric(19, 2) not null default 0,
    journal_batch_no   varchar(40),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint clm_uq_reserve_change unique (claim_id, change_no),
    constraint clm_ck_reserve_recovery check (side = 'PAYMENT' or cost_type = 'LOSS')
);
create index ix_clm_reserve_status on clm_reserve_change (status);

create table clm_settlement (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    claim_id              bigint         not null references clm_claim (id),
    settlement_no         varchar(40)    not null,
    payee_party_id        bigint         not null references pty_party (id),
    cost_type             varchar(10)    not null check (cost_type in ('LOSS', 'EXPENSE')),
    settlement_type       varchar(10)    not null check (settlement_type in ('PARTIAL', 'FINAL')),
    assessed_amount       numeric(19, 2) not null check (assessed_amount > 0),
    deductible            numeric(19, 2) not null default 0 check (deductible >= 0),
    excess_amount         numeric(19, 2) not null default 0 check (excess_amount >= 0),
    net_amount            numeric(19, 2) not null check (net_amount > 0),
    our_amount            numeric(19, 2),
    payable_amount        numeric(19, 2),
    coinsurer_amount      numeric(19, 2),
    exchange_rate         numeric(19, 8),
    narration             varchar(300)   not null,
    status                varchar(20)    not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    submitted_by          varchar(50)    not null,
    submitted_at          timestamptz    not null,
    approved_by           varchar(50),
    approved_at           timestamptz,
    approval_date         date,
    rejection_reason      varchar(200),
    authority_amount      numeric(19, 2) not null default 0,
    journal_batch_no      varchar(40),
    coinsurance_batch_no  varchar(40),
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint clm_uq_settlement_no unique (settlement_no),
    constraint clm_ck_settlement_net check (net_amount = assessed_amount - deductible - excess_amount)
);
create index ix_clm_settlement_claim on clm_settlement (claim_id);
create index ix_clm_settlement_status on clm_settlement (status);

create table clm_recovery (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    claim_id              bigint         not null references clm_claim (id),
    recovery_no           varchar(40)    not null,
    recovery_type         varchar(15)    not null check (recovery_type in ('SALVAGE', 'SUBROGATION')),
    from_party_id         bigint references pty_party (id),
    bank_account_code     varchar(20)    not null,
    amount                numeric(19, 2) not null check (amount > 0),
    our_amount            numeric(19, 2),
    coinsurer_amount      numeric(19, 2),
    narration             varchar(300)   not null,
    status                varchar(20)    not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    submitted_by          varchar(50)    not null,
    submitted_at          timestamptz    not null,
    approved_by           varchar(50),
    approved_at           timestamptz,
    approval_date         date,
    rejection_reason      varchar(200),
    authority_amount      numeric(19, 2) not null default 0,
    journal_batch_no      varchar(40),
    coinsurance_batch_no  varchar(40),
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint clm_uq_recovery_no unique (recovery_no)
);
create index ix_clm_recovery_claim on clm_recovery (claim_id);
create index ix_clm_recovery_status on clm_recovery (status);

create table clm_lpo (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    claim_id         bigint         not null references clm_claim (id),
    lpo_no           varchar(40)    not null,
    garage_party_id  bigint         not null references pty_party (id),
    cover_type       varchar(5)     not null check (cover_type in ('OD', 'TP')),
    issue_date       date           not null,
    gross_amount     numeric(19, 2) not null check (gross_amount > 0),
    discount_amount  numeric(19, 2) not null default 0 check (discount_amount >= 0),
    net_amount       numeric(19, 2) not null,
    description      varchar(300)   not null,
    status           varchar(15)    not null check (status in ('ISSUED', 'CANCELLED')),
    cancel_reason    varchar(200),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint clm_uq_lpo_no unique (lpo_no),
    constraint clm_ck_lpo_net check (net_amount = gross_amount - discount_amount and net_amount > 0)
);
create index ix_clm_lpo_claim on clm_lpo (claim_id);
create index ix_clm_lpo_garage on clm_lpo (garage_party_id);

-- Claim movement ledger: one line per approved estimate change or paid amount, typed with the
-- Reports Book codes (1 Payment, 2 Recovery, 3 Reversal of Payment, 4 Reversal of Recovery).
-- Immutable; reports, the insurance kernel views and listener notifications are derived from it.
create table clm_movement (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    claim_id          bigint         not null references clm_claim (id),
    movement_date     date           not null,
    kind              varchar(10)    not null check (kind in ('ESTIMATE', 'PAID')),
    side              varchar(10)    not null check (side in ('PAYMENT', 'RECOVERY')),
    cost_type         varchar(10)    not null check (cost_type in ('LOSS', 'EXPENSE')),
    estimate_type     integer        not null check (estimate_type between 1 and 4),
    amount_100        numeric(19, 2) not null,
    amount            numeric(19, 2) not null,
    base_amount       numeric(19, 2) not null,
    currency          varchar(3)     not null,
    reference         varchar(80)    not null,
    source_type       varchar(15)    not null check (source_type in ('RESERVE', 'SETTLEMENT', 'RECOVERY')),
    source_id         bigint         not null,
    journal_batch_no  varchar(40),
    narration         varchar(300)   not null,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint clm_uq_movement_reference unique (reference)
);
create index ix_clm_movement_claim on clm_movement (claim_id, movement_date);
create index ix_clm_movement_date on clm_movement (company_id, movement_date);

-- Coinsurance of claims led by the company: coinsurers' share of a settlement (recoverable from
-- them) and of a recovery (payable to them).
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('CLAIM_COINSURANCE', 'Coinsurer share of a claim', 'COINSURANCE', 'CLAIMS',
  'Coinsurers share of a claim settlement (recoverable) or of a salvage / subrogation recovery (payable) when leading; recovery lines use role BANK',
  'COINSURER_SHARE,COINSURER_RECOVERY');

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by) values
    ('LARGE_CLAIM_RESERVE', 'Large claim reserve',
     'An approved claim reserve (company share, base currency) is at or above the threshold amount.',
     'CLAIMS', 'HIGH', 5000000.00, null, now(), 'SYSTEM'),
    ('LATE_CLAIM_NOTIFICATION', 'Late claim notification',
     'A claim was reported more than the threshold days after the date of loss.',
     'CLAIMS', 'MEDIUM', null, 30, now(), 'SYSTEM');
