-- =====================================================================================
-- iNXT FinVerse - V20 System administration: business parameters and job run registry.
-- =====================================================================================

create table sys_parameter (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    param_key   varchar(60)   not null unique,
    param_value varchar(1000) not null,
    value_type  varchar(15)   not null
        check (value_type in ('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'INTEGER_LIST', 'CODE_LIST')),
    category    varchar(30)   not null,
    description varchar(300)  not null,
    min_value   integer,
    max_value   integer,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('SESSION_TIMEOUT_MINUTES', '30', 'INTEGER', 'SECURITY',
     'Minutes of inactivity after which the web session signs out automatically', 5, 480,
     now(), 'SYSTEM'),
    ('AGEING_BUCKETS', '30,60,90,180', 'INTEGER_LIST', 'REPORTING',
     'Default ageing bucket limits in days (ascending) for receivable and payable ageing', 1, 3650,
     now(), 'SYSTEM'),
    ('REPORT_FOOTER_TEXT', 'Generated by iNXT FinVerse. Confidential - for internal use only.',
     'STRING', 'REPORTING', 'Footer text printed on exported reports', null, null, now(), 'SYSTEM'),
    ('SUSPENSE_ACCOUNT_CODES', '', 'CODE_LIST', 'CONTROLS',
     'GL account codes monitored by the SUSPENSE_BALANCE exception (blank = accounts named Suspense)',
     null, null, now(), 'SYSTEM'),
    ('JOB_HISTORY_DAYS', '90', 'INTEGER', 'OPERATIONS',
     'Days of scheduled job history shown in the job monitor', 1, 3650, now(), 'SYSTEM');

create table sys_job_run (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    job_name        varchar(60)   not null,
    trigger_type    varchar(10)   not null check (trigger_type in ('SCHEDULED', 'MANUAL')),
    triggered_by    varchar(50)   not null,
    started_at      timestamptz   not null,
    finished_at     timestamptz,
    status          varchar(10)   not null check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
    items_processed integer       not null default 0,
    message         varchar(1000),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_job_run_name on sys_job_run (job_name, started_at desc);
