-- =====================================================================================
-- iNXT FinVerse - V21 Document attachments on any record (entity type + entity id).
-- Metadata and content are split so listings never load file bytes.
-- =====================================================================================

create table doc_attachment (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    entity_type  varchar(60)  not null,
    entity_id    varchar(60)  not null,
    file_name    varchar(255) not null,
    content_type varchar(100) not null,
    size_bytes   bigint       not null check (size_bytes > 0),
    sha256       varchar(64)  not null,
    description  varchar(200),
    deleted      boolean      not null default false,
    deleted_by   varchar(50),
    deleted_at   timestamptz,
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);
create index ix_attachment_entity on doc_attachment (entity_type, entity_id);

create table doc_attachment_content (
    attachment_id bigint primary key references doc_attachment (id),
    content       bytea  not null
);
