-- =====================================================================================
-- iNXT FinVerse - V22 Recurring / accrual journal templates and their generated occurrences.
-- =====================================================================================

create table jnl_recurring_template (
    id                   bigint generated by default as identity primary key,
    version              bigint       not null default 0,
    company_id           bigint       not null references org_company (id),
    branch_id            bigint       not null references org_branch (id),
    name                 varchar(120) not null,
    journal_type         varchar(20)  not null check (journal_type in ('MANUAL', 'ADJUSTMENT', 'ACCRUAL')),
    currency             varchar(3)   not null,
    narration            varchar(500) not null,
    reference            varchar(60),
    frequency            varchar(10)  not null check (frequency in ('MONTHLY', 'QUARTERLY', 'ANNUALLY')),
    day_of_month         integer      not null check (day_of_month between 1 and 31),
    start_date           date         not null,
    end_date             date,
    auto_reverse         boolean      not null default false,
    auto_submit          boolean      not null default false,
    active               boolean      not null default true,
    last_occurrence_date date,
    created_at           timestamptz  not null,
    created_by           varchar(50)  not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_recurring_name unique (company_id, name),
    constraint ck_recurring_dates check (end_date is null or end_date >= start_date)
);

create table jnl_recurring_line (
    template_id   bigint         not null references jnl_recurring_template (id),
    line_no       integer        not null,
    account_code  varchar(30)    not null,
    side          varchar(6)     not null check (side in ('DEBIT', 'CREDIT')),
    amount        numeric(19, 2) not null check (amount > 0),
    currency      varchar(3),
    exchange_rate numeric(19, 8),
    branch_id     bigint references org_branch (id),
    cost_center   varchar(20),
    business_line varchar(20),
    party_code    varchar(30),
    reference     varchar(60),
    narration     varchar(250),
    primary key (template_id, line_no)
);

create table jnl_recurring_occurrence (
    id                bigint generated by default as identity primary key,
    template_id       bigint      not null references jnl_recurring_template (id),
    occurrence_date   date        not null,
    batch_id          bigint      not null references jnl_batch (id),
    reversal_batch_id bigint references jnl_batch (id),
    generated_at      timestamptz not null,
    generated_by      varchar(50) not null,
    constraint uq_recurring_occurrence unique (template_id, occurrence_date)
);
