-- =====================================================================================
-- iNXT FinVerse - V23 Exception code master and alert (exception log) register.
-- Every module "exception report" is a filtered view of alt_alert.
-- =====================================================================================

create table alt_exception_code (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    code             varchar(40)    not null unique,
    name             varchar(120)   not null,
    description      varchar(500)   not null,
    module           varchar(30)    not null,
    severity         varchar(10)    not null check (severity in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    threshold_amount numeric(19, 2),
    threshold_days   integer,
    active           boolean        not null default true,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by) values
    ('LARGE_JOURNAL', 'Large journal posting',
     'A journal with a base-currency total at or above the threshold amount was posted.',
     'GL', 'HIGH', 1000000.00, null, now(), 'SYSTEM'),
    ('BACK_DATED_POSTING', 'Back-dated posting',
     'A manual journal was posted with a value date more than the threshold days before the posting date.',
     'GL', 'MEDIUM', null, 5, now(), 'SYSTEM'),
    ('WEEKEND_POSTING', 'Posting on a non-working day',
     'A manual journal was posted on, or dated on, a weekend or holiday of its branch.',
     'GL', 'LOW', null, null, now(), 'SYSTEM'),
    ('NEGATIVE_CASH_BALANCE', 'Negative cash balance',
     'A cash or bank account has a credit (negative) balance.',
     'GL', 'CRITICAL', null, null, now(), 'SYSTEM'),
    ('UNBALANCED_TB', 'Unbalanced trial balance',
     'Total debits and credits of the trial balance differ.',
     'GL', 'CRITICAL', null, null, now(), 'SYSTEM'),
    ('PENDING_APPROVAL_AGEING', 'Pending approval ageing',
     'An item has been waiting for approval longer than the threshold days.',
     'WORKFLOW', 'MEDIUM', null, 2, now(), 'SYSTEM'),
    ('SUSPENSE_BALANCE', 'Balance in suspense account',
     'A suspense account carries a balance above the threshold amount and must be cleared.',
     'GL', 'HIGH', 0.00, null, now(), 'SYSTEM'),
    ('JOB_FAILURE', 'Background job failure',
     'A scheduled or manually started background job failed.',
     'SYSTEM', 'HIGH', null, null, now(), 'SYSTEM');

create table alt_alert (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    exception_code  varchar(40)    not null references alt_exception_code (code),
    severity        varchar(10)    not null check (severity in ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    module          varchar(30)    not null,
    company_id      bigint references org_company (id),
    branch_id       bigint references org_branch (id),
    entity_type     varchar(60),
    entity_id       varchar(60),
    message         varchar(500)   not null,
    amount          numeric(19, 2),
    dedup_key       varchar(200)   not null,
    status          varchar(15)    not null check (status in ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    raised_at       timestamptz    not null,
    acknowledged_by varchar(50),
    acknowledged_at timestamptz,
    resolved_by     varchar(50),
    resolved_at     timestamptz,
    status_comment  varchar(500),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
-- One live (open or acknowledged) alert per condition; a resolved condition may be raised again.
create unique index uq_alert_live on alt_alert (dedup_key) where status <> 'RESOLVED';
create index ix_alert_status on alt_alert (status, raised_at);
create index ix_alert_company on alt_alert (company_id, raised_at);
