-- Standard variants of the Report Centre: one to three shared parameter sets per report that a
-- broker uses most (this month, last month, year to date, expiring next, my branch, open only),
-- configuration of every environment. Users cannot delete them; their own variants are listed
-- apart ("My Variants"), and each user may mark one of his variants as the default of a report.
-- Date values are keywords resolved when the variant is applied (TODAY, MONTH_START, MONTH_END,
-- YEAR_START, YEAR_END, PREV_MONTH_START, PREV_MONTH_END, NEXT_MONTH_START, NEXT_MONTH_END,
-- IN_THREE_MONTHS, IN_TWELVE_MONTHS, TWELVE_MONTHS_AGO, PREV_YEAR_START, PREV_YEAR_END,
-- CURRENT_YEAR, PREV_YEAR) and MY_BRANCH is the branch of the user's workspace.

alter table nbr_report_variant
    add column standard        boolean not null default false,
    add column default_variant boolean not null default false;

insert into nbr_report_variant (owner, report_code, name, parameters, shared, standard, created_at, created_by)
values
    ('system', 'ACSL-BOOKED-FIN-DETAILS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ACSL-BOOKED-FIN-DETAILS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ACSL-BOOKED-FIN-DETAILS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ACSL-GL-SL-RECON', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ACSL-GL-SL-RECON', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ACSL-SOA-RECON', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'ACSL-SOA-UPLOAD-LOG', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'ADJ-AGING', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-AGING', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-AGING', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ADJ-DAILY', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-DAILY', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-DAILY', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ADJ-MINBAL-FILE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-MINBAL-FILE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-MINBAL-FILE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ADJ-REGISTER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-REGISTER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-REGISTER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ADJ-VALIDATION-LIST', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-VALIDATION-LIST', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'ADJ-VALIDATION-LIST', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-ACTIVITY-LOG', 'Year to Date', '{"periodFrom":"YEAR_START","periodTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-ACTIVITY-LOG', 'This Month', '{"periodFrom":"MONTH_START","periodTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-ACTIVITY-LOG', 'Last Month', '{"periodFrom":"PREV_MONTH_START","periodTo":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING', 'My Branch - As of Today', '{"asOf":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING-STATUS', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING-STATUS', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-AGEING-STATUS', 'My Branch - As of Today', '{"asOf":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'BCL-INSURER-CLAIMS', 'Year to Date', '{"reportedFrom":"YEAR_START","reportedTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-INSURER-CLAIMS', 'This Month', '{"reportedFrom":"MONTH_START","reportedTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-INSURER-CLAIMS', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","reportedFrom":"YEAR_START","reportedTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-EXPERIENCE', 'Year to Date', '{"lossFrom":"YEAR_START","lossTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-EXPERIENCE', 'This Month', '{"lossFrom":"MONTH_START","lossTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-EXPERIENCE', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","lossFrom":"YEAR_START","lossTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-RATIO', 'By Product Line', '{"grouping":"LINE"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-RATIO', 'By Client', '{"grouping":"CLIENT"}', true, true, now(), 'system'),
    ('system', 'BCL-LOSS-RATIO', 'By Insurer', '{"grouping":"INSURER"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING', 'My Branch - As of Today', '{"asOf":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING-PAST-DUE', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING-PAST-DUE', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-OUTSTANDING-PAST-DUE', 'My Branch - As of Today', '{"asOf":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'BCL-PENDING-ACTIONS', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-PENDING-ACTIONS', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-PENDING-ACTIONS', 'My Branch - As of Today', '{"asOf":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'BCL-PRONE-LOCATIONS', 'Year to Date', '{"periodFrom":"YEAR_START","periodTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-PRONE-LOCATIONS', 'This Month', '{"periodFrom":"MONTH_START","periodTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-PRONE-LOCATIONS', 'Last Month', '{"periodFrom":"PREV_MONTH_START","periodTo":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'BCL-SETTLED', 'Year to Date', '{"settledFrom":"YEAR_START","settledTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-SETTLED', 'This Month', '{"settledFrom":"MONTH_START","settledTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'BCL-SETTLED', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","settledFrom":"YEAR_START","settledTo":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-APPLICATION-TO-INVOICE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-APPLICATION-TO-INVOICE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-APPLICATION-TO-INVOICE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CLX-AUDIT-LOG', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-AUDIT-LOG', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-AUDIT-LOG', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CLX-BROKEN-PROMISES', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-BROKEN-PROMISES', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-BROKEN-PROMISES', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CLX-COMPLETED-COLLECTIONS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-COMPLETED-COLLECTIONS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-COMPLETED-COLLECTIONS', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-DP-FOR-REVERSAL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-DP-FOR-REVERSAL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-DP-FOR-REVERSAL', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-ESCALATIONS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-ESCALATIONS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-ESCALATIONS', 'Open Only - Year to Date', '{"from":"YEAR_START","status":"OPEN","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-FULL-PRODUCTION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-FULL-PRODUCTION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-FULL-PRODUCTION', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-INSTALLMENTS-DUE', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'CLX-INSTALLMENTS-DUE', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'CLX-INSTALLMENTS-DUE', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CLX-INVOICES-WITH-DISPOSITION', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'CLX-INVOICES-WITH-DISPOSITION', 'My Branch - All Records', '{"branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'CLX-OUTSTANDING-PR', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'CLX-OUTSTANDING-PR', 'My Branch - All Records', '{"branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'CLX-PR2307-FOR-REVERSAL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-PR2307-FOR-REVERSAL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-PR2307-FOR-REVERSAL', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-REASSIGNMENTS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-REASSIGNMENTS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-REASSIGNMENTS', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-UNAPPLIED-DISPOSITIONS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-UNAPPLIED-DISPOSITIONS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CLX-UNAPPLIED-DISPOSITIONS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-BIR-CERT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-BIR-CERT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-BIR-CERT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-COMMISSION-RECEIVABLE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-COMMISSION-RECEIVABLE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-COMMISSION-RECEIVABLE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-DP-STATUS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-DP-STATUS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-DP-STATUS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-FEEDBACK-SLA', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-FEEDBACK-SLA', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-FEEDBACK-SLA', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-INCENTIVE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-INCENTIVE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-INCENTIVE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CMR-PRODUCTION-YEARLY', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-PRODUCTION-YEARLY', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CMR-PRODUCTION-YEARLY', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSF-ACTIVITY', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSF-ACTIVITY', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSF-ACTIVITY', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSF-CONTACT-CHANGES', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSF-CONTACT-CHANGES', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSF-CONTACT-CHANGES', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-2307-TXN', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-2307-TXN', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-2307-TXN', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-ADVANCE-PAYMENT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-ADVANCE-PAYMENT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-ADVANCE-PAYMENT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-COMM', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-COMM', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-COMM', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-PREM', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-PREM', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-APPLIED-PREM', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-AR-OUTSTANDING', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-AR-OUTSTANDING', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-AR-OUTSTANDING', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-BATCH-RUN', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-BATCH-RUN', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-BATCH-RUN', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-AR', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-AR', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-AR', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-OR', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-OR', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CANCELLED-OR', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-CERT-OF-PAYMENT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CERT-OF-PAYMENT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CERT-OF-PAYMENT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-CHECK-PICKUP', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CHECK-PICKUP', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CHECK-PICKUP', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-CWT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CWT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-CWT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-DAILY-CASH-REC', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-DAILY-CASH-REC', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-DAILY-CASH-REC', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-DIRECT-PAYMENT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-DIRECT-PAYMENT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-DIRECT-PAYMENT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-COMMISSION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-COMMISSION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-COMMISSION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-EXCESS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-EXCESS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-EXCESS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-PREMIUM', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-PREMIUM', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-MINBAL-PREMIUM', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-PAYMENT-REVERSAL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-PAYMENT-REVERSAL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-PAYMENT-REVERSAL', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-PDC-WAREHOUSE', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'CSH-PDC-WAREHOUSE', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'CSH-PDC-WAREHOUSE', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-PRIORITY-POSTED', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-PRIORITY-POSTED', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-PRIORITY-POSTED', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-REAPPLICATION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REAPPLICATION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REAPPLICATION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT-MON', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT-MON', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-REINSTATEMENT-MON', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-MANCOM', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-MANCOM', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-MANCOM', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-YTD', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-YTD', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UNAPPLIED-COMM-YTD', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-INCOME-RECLASS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-INCOME-RECLASS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-INCOME-RECLASS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-LEGACY', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-LEGACY', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CSH-UPP-LEGACY', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CTL-AUDIT', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CTL-AUDIT', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CTL-AUDIT', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'CTL-EXCEPTIONS', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CTL-EXCEPTIONS', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'CTL-EXCEPTIONS', 'Open Only - Year to Date', '{"fromDate":"YEAR_START","status":"OPEN","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-ATD', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-ATD', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-ATD', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-CASH-FLOW', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-CASH-FLOW', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-CASH-FLOW', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-CWT-COMMISSION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-CWT-COMMISSION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-CWT-COMMISSION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-EMPLOYEE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-EMPLOYEE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-EMPLOYEE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-OTHER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-OTHER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-OTHER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REFUND', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REFUND', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REFUND', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REMIT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REMIT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-REMIT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUMMARY', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUMMARY', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUMMARY', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUPPLIER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUPPLIER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-EOD-SUPPLIER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-MASTERLIST', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-MASTERLIST', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-MASTERLIST', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-ML-STALE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-ML-STALE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-ML-STALE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-PAYEE', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'DSB-PAYEE-NOMATCH', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-PAYEE-NOMATCH', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-PAYEE-NOMATCH', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-UNREGULARIZED', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UNREGULARIZED', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UNREGULARIZED', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-UNRELEASED-CHECKS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UNRELEASED-CHECKS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UNRELEASED-CHECKS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'DSB-UPLOAD-FALLOUT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UPLOAD-FALLOUT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'DSB-UPLOAD-FALLOUT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-FRANCHISE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-FRANCHISE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-FRANCHISE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-NEW-BUSINESS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-NEW-BUSINESS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-NEW-BUSINESS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-PENDING-ITEMS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PENDING-ITEMS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PENDING-ITEMS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-PLACEMENT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PLACEMENT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PLACEMENT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-PRODUCTION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PRODUCTION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-PRODUCTION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-RENEWAL', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'EB-RENEWAL', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'EB-RENEWAL', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'EB-TAT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-TAT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'EB-TAT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-DET', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-DET', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-DET', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-SUM2', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-SUM2', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ACT-SUM2', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-DET', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-DET', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-DET', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-SUM', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-SUM', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-AGE-SUM', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SOP', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SOP', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SOP', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SUPOS', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SUPOS', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-SUPOS', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-VOUCHER', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-VOUCHER', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AP-VOUCHER', 'Waiting for Approval - Year to Date', '{"fromDate":"YEAR_START","status":"PENDING_APPROVAL","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-DET', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-DET', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-DIV', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-DIV', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-SUM', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-AGE-SUM', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-CHQ-RCPT', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-CHQ-RCPT', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-CHQ-RCPT', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-CHQ-UNDEP', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-CHQ-UNDEP', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-SOO', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-SOO', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-SOO-FC', 'US Dollar - As of Today', '{"asOfDate":"TODAY","currency":"USD"}', true, true, now(), 'system'),
    ('system', 'FIN-AR-SOO-FC', 'US Dollar - As of Last Month End', '{"asOfDate":"PREV_MONTH_END","currency":"USD"}', true, true, now(), 'system'),
    ('system', 'FIN-ARAP-SOA-MATCH', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ARAP-SOA-MATCH', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-ARAP-SOA-MATCH', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-PAYNOTIFY', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-PAYNOTIFY', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-STMT', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-STMT', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-UNREC-BANK', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-UNREC-BANK', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-UNREC-BOOK', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-BRS-UNREC-BOOK', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-CB-POSITION', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-CB-POSITION', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-CB-POSITION', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-DEPR', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-DEPR', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-DEPR', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-MOVE', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-MOVE', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-MOVE', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-NBV', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-NBV', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-NBV', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-REG', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-REG', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-FA-REG', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-ALLOCJV', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-ALLOCJV', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-ALLOCJV', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-CONSSUM', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-CONSSUM', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-CONSSUM', 'Unposted Only - Year to Date', '{"fromDate":"YEAR_START","status":"UNPOSTED","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-DAYBOOK', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-DAYBOOK', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-DAYBOOK', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-FC', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-FC', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-FC', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-LC', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-LC', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-LEDGER-LC', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-MISSVCH', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-MISSVCH', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-MISSVCH', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-PROCLIST', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-PROCLIST', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-PROCLIST', 'Unposted Only - Year to Date', '{"fromDate":"YEAR_START","status":"UNPOSTED","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-FC', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-FC', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-FC', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-LC', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-LC', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-SUBLEDGER-LC', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-TXNLIST', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-TXNLIST', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-TXNLIST', 'Unposted Only - Year to Date', '{"fromDate":"YEAR_START","status":"UNPOSTED","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-VOUCHER', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-VOUCHER', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-GL-VOUCHER', 'Unposted Only - Year to Date', '{"fromDate":"YEAR_START","status":"UNPOSTED","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-ACCR', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-ACCR', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-ACCR', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-MAT', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-MAT', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-MAT', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-PORT', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-PORT', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-PORT', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-RGL', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-RGL', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-RGL', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-SECDEP', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-SECDEP', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-INV-SECDEP', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS-SCH', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS-SCH', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-BS-SCH', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE-SCH', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE-SCH', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-MIS-IE-SCH', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PC-PENDING', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PC-PENDING', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PC-REIMB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PC-REIMB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PC-REIMB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-CONF-AUDIT-DDB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-CONF-AUDIT-DDB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-CONF-AUDIT-DDB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-DUEPAY', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-DUEPAY', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-DUEPAY-DDB', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-DUEPAY-DDB', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD-DDB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD-DDB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-ISS-PERIOD-DDB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-DUEBANK', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-DUEBANK', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-DUEBANK-DDB', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-DUEBANK-DDB', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-ONHAND', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-ONHAND', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-ONHAND-DDB', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-ONHAND-DDB', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD-DDB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD-DDB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FIN-PDC-RCV-PERIOD-DDB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-DIVDEPT', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-DIVDEPT', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-DIVDEPT', 'My Branch - This Year', '{"branchId":"MY_BRANCH","year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-MAIN', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-MAIN', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-MAIN', 'My Branch - This Year', '{"branchId":"MY_BRANCH","year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-POSTUNP', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-POSTUNP', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-POSTUNP', 'Unposted Only - This Year', '{"status":"UNPOSTED","year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-SUB', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-SUB', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-SUB', 'My Branch - This Year', '{"branchId":"MY_BRANCH","year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-YTD', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-YTD', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'FIN-TB-YTD', 'My Branch - This Year', '{"branchId":"MY_BRANCH","year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION-SUM', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION-SUM', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-BRANCH-PRODUCTION-SUM', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-CASH-FLOW', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-CASH-FLOW', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-CASH-FLOW', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-EXPENSE-GROUPING', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-EXPENSE-GROUPING', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-EXPENSE-GROUPING', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-GAP', 'As of Today', '{"to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-GAP', 'As of Last Month End', '{"to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-MANCOM-MARKET', 'As of Today', '{"to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-MANCOM-MARKET', 'As of Last Month End', '{"to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE-DETAIL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE-DETAIL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'FRBS-SERVICE-FEE-DETAIL', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'FRBS-SUSTAINABILITY-PROD', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'FRBS-SUSTAINABILITY-PROD', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'GL-BS', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-BS', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-BS', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'GL-BUTIL', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-BUTIL', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-BVA', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-BVA', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-CCY', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-CCY', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-CCY', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'GL-COA', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'GL-DETAIL', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-DETAIL', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-DETAIL', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-FXREV', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-FXREV', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-JRNL', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-JRNL', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-JRNL', 'Waiting for Approval - Year to Date', '{"fromDate":"YEAR_START","status":"PENDING_APPROVAL","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-PL', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-PL', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-PL', 'My Branch - Year to Date', '{"branchId":"MY_BRANCH","fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-SCHEDULE', 'Expenses per Cost Centre - This Month', '{"asOf":"TODAY","schedule":"SCH-EXPENSE-CC"}', true, true, now(), 'system'),
    ('system', 'GL-SCHEDULE', 'Outstanding Checks - This Month', '{"asOf":"TODAY","schedule":"SCH-CHECKS-OUTSTANDING"}', true, true, now(), 'system'),
    ('system', 'GL-SCHEDULE', 'Commission Receivable - This Month', '{"asOf":"TODAY","schedule":"SCH-COMM-RECEIVABLE"}', true, true, now(), 'system'),
    ('system', 'GL-TB', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'GL-TB', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'GL-TB', 'My Branch - As of Today', '{"asOfDate":"TODAY","branchId":"MY_BRANCH"}', true, true, now(), 'system'),
    ('system', 'IC-BROKER-ASBO', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'IC-BROKER-ASBO', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'MIG-BATCH-LOG', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-CLIENT-MATCH', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-CUTOVER-STATUS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-DECISIONS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-DQ-ISSUES', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-GL-CLEARING', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-GONOGO', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-LEGACY-POSITIONS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-MAP-VERSIONS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-OBJECT-REGISTER', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-RECON-DETAIL', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-RECON-SUMMARY', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-REJECTS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-RENEWAL-GOLIVE', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-RUNOFF', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'MIG-RUNOFF', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'MIG-RUNOFF', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'MIG-SIGNOFF-STATUS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-TRUEUP-RECON', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-TRUEUP-REGISTER', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'MIG-UNMAPPED-CODES', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'NB-ACC-STATUS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'NB-ACC-STATUS', 'SLA Breaches Only', '{"exceptions":"SLA_BREACH"}', true, true, now(), 'system'),
    ('system', 'NB-BOOKED-REG', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-BOOKED-REG', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-BOOKED-REG', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'NB-DISPATCH', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-DISPATCH', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-DISPATCH', 'Failed Only - Year to Date', '{"from":"YEAR_START","outcome":"FAILED","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-KYC-DUE', 'As of Today', '{"dueBy":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-KYC-DUE', 'As of Last Month End', '{"dueBy":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'NB-PLC-UPDATE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-PLC-UPDATE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-PLC-UPDATE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'NB-PRODUCTION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-PRODUCTION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-PRODUCTION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'NB-STAGE-OUTCOME', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-STAGE-OUTCOME', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'NB-STAGE-OUTCOME', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'ORG-HEADCOUNT-CC', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'PM-PKG-EXPIRY', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'PM-PKG-STATUS', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'PM-VERSION-HISTORY', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'PRC-DISPOSITION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-DISPOSITION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-DISPOSITION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-EARLY-INCENTIVE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-EARLY-INCENTIVE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-EARLY-INCENTIVE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-EXTRACT-LOG', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-EXTRACT-LOG', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-EXTRACT-LOG', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-LEGACY-CHANGES', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-LEGACY-CHANGES', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-LEGACY-CHANGES', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-REGISTER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-REGISTER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-REGISTER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-SUMMARY', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-SUMMARY', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-SUMMARY', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-UNBOOKED', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNBOOKED', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNBOOKED', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-AO', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-AO', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-AO', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-FEEDBACK', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-FEEDBACK', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-FEEDBACK', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-LOC', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-LOC', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRC-UNMATCHED-LOC', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRQ-REGISTER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRQ-REGISTER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRQ-REGISTER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'PRQ-STATUS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRQ-STATUS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'PRQ-STATUS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-DTIP-DETAIL', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'REM-DTIP-SUMMARY', 'All Records', '{}', true, true, now(), 'system'),
    ('system', 'REM-EXCLUDED', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-EXCLUDED', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-EXCLUDED', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-HOLD', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-HOLD', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-HOLD', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-OR-EXCEPTION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-OR-EXCEPTION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-OR-EXCEPTION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-PAIDAR-OVER-DTIP', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-PAIDAR-OVER-DTIP', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-PAIDAR-OVER-DTIP', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-REMITTED-BATCH', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-REMITTED-BATCH', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-REMITTED-BATCH', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-INCENTIVE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-INCENTIVE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-INCENTIVE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-NORMAL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-NORMAL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-NORMAL', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-SPECIAL', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-SPECIAL', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SCHEDULE-SPECIAL', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-SPECIAL-REGISTER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SPECIAL-REGISTER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-SPECIAL-REGISTER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'REM-TRACKER', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-TRACKER', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'REM-TRACKER', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-DECISIONS', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-DECISIONS', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-DECISIONS', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-EXPIRY-LIST', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-EXPIRY-LIST', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-EXPIRY-LIST', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-GOLIVE', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-GOLIVE', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-GOLIVE', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-INSURER-EXTRACT', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-INSURER-EXTRACT', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-INSURER-EXTRACT', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-LAMD-MATCH', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-LAMD-MATCH', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-LAMD-MATCH', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-LISTING', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-LISTING', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-LISTING', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-PACKAGE-REMAP', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-PACKAGE-REMAP', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-PACKAGE-REMAP', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-RA-DISPATCH', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-RA-DISPATCH', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-RA-DISPATCH', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-SANITATION', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-SANITATION', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-SANITATION', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-STATUS', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-STATUS', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-STATUS', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'RNW-WORKLOAD', 'All Expiries', '{"expiryFrom":"","expiryTo":""}', true, true, now(), 'system'),
    ('system', 'RNW-WORKLOAD', 'Expiring in the Next 3 Months', '{"expiryFrom":"TODAY","expiryTo":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'RNW-WORKLOAD', 'Expiring This Month', '{"expiryFrom":"MONTH_START","expiryTo":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-CLASSIFICATION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-CLASSIFICATION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-CLASSIFICATION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-CONVERSION', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-CONVERSION', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-CONVERSION', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-DISPOSITION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-DISPOSITION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-DISPOSITION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-DOC-FALLOUT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-DOC-FALLOUT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-DOC-FALLOUT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-HANDLING-FEE', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-HANDLING-FEE', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-HANDLING-FEE', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-HOLD-COVER-GAP', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-HOLD-COVER-GAP', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-HOLD-COVER-GAP', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-IAAF', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-IAAF', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-IAAF', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-LETTERS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-LETTERS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-LETTERS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-MASTERLIST', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-MASTERLIST', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-MASTERLIST', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-MIGRATION-ERRORS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-MIGRATION-ERRORS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-MIGRATION-ERRORS', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-NO-TOUCH', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-NO-TOUCH', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-NO-TOUCH', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-NON-RENEWAL', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-NON-RENEWAL', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-NON-RENEWAL', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-PENETRATION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PENETRATION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PENETRATION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-PERSISTENCY', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-PERSISTENCY', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-PERSISTENCY', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-CONVERSION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-CONVERSION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-CONVERSION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-MONITORING', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-MONITORING', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PR-MONITORING', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-PROCESS-FALLOUT', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PROCESS-FALLOUT', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-PROCESS-FALLOUT', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-RENEWABLE', 'Next 12 Months', '{"from":"TODAY","to":"IN_TWELVE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-RENEWABLE', 'Next 3 Months', '{"from":"TODAY","to":"IN_THREE_MONTHS"}', true, true, now(), 'system'),
    ('system', 'SBM-RENEWABLE', 'This Month', '{"from":"MONTH_START","to":"MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-SANITATION', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-SANITATION', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-SANITATION', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SBM-TOR', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-TOR', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SBM-TOR', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-AUDIT-LOG', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-AUDIT-LOG', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-AUDIT-LOG', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-CASE-STATUS', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-CASE-STATUS', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-CASE-STATUS', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-HIGH-RISK-CLIENTS', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-HIGH-RISK-CLIENTS', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-INGEST-ERRORS', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-INGEST-ERRORS', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-INGEST-ERRORS', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-PEP-CLIENTS', 'As of Today', '{"asOfDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-PEP-CLIENTS', 'As of Last Month End', '{"asOfDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-SANCTIONED-NAMES', 'All Listed Names', '{"fromDate":"","toDate":""}', true, true, now(), 'system'),
    ('system', 'SCR-SANCTIONED-NAMES', 'Listed This Year', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-SANCTIONED-NAMES', 'Listed Last Year', '{"fromDate":"PREV_YEAR_START","toDate":"PREV_YEAR_END"}', true, true, now(), 'system'),
    ('system', 'SCR-SLA-BREACHES', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-SLA-BREACHES', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-SLA-BREACHES', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'SCR-STR-REGISTER', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-STR-REGISTER', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'SCR-STR-REGISTER', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-0619F', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-0619F', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1603', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1603', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1604E', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1604E', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1702', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1702', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1702Q', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-1702Q', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-2307-REG', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-2307-REG', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CDB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CDB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CDB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CRB', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CRB', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-CRB', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-GJ', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-GJ', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-GJ', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-PJ', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-PJ', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-PJ', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SJ', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SJ', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SJ', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SL', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SL', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-BOOK-SL', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-EWT-1601EQ', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-EWT-1601EQ', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-EWT-1601EQ', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-MAP', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-MAP', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-QAP', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-QAP', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-REMIT', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-REMIT', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-REMIT', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-SAWT', 'This Year', '{"year":"CURRENT_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-SAWT', 'Last Year', '{"year":"PREV_YEAR"}', true, true, now(), 'system'),
    ('system', 'TAX-SLP', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-SLP', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-SLP', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-SLS', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-SLS', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-SLS', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'TAX-VAT-2550Q', 'Year to Date', '{"fromDate":"YEAR_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-VAT-2550Q', 'This Month', '{"fromDate":"MONTH_START","toDate":"TODAY"}', true, true, now(), 'system'),
    ('system', 'TAX-VAT-2550Q', 'Last Month', '{"fromDate":"PREV_MONTH_START","toDate":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'UAM-AUDIT-LOG', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-AUDIT-LOG', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-AUDIT-LOG', 'Last Month', '{"from":"PREV_MONTH_START","to":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'UAM-GROUP-MEMBERS', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-GROUP-MEMBERS', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system'),
    ('system', 'UAM-GROUP-PROFILE', 'Active Profiles - All Modules', '{"active":"ACTIVE"}', true, true, now(), 'system'),
    ('system', 'UAM-GROUP-PROFILE', 'Inactive Profiles', '{"active":"INACTIVE"}', true, true, now(), 'system'),
    ('system', 'UAM-GROUP-PROFILE', 'All Profiles', '{"active":"ALL"}', true, true, now(), 'system'),
    ('system', 'UAM-REQUESTS', 'Year to Date', '{"from":"YEAR_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-REQUESTS', 'This Month', '{"from":"MONTH_START","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-REQUESTS', 'Pending Only - Year to Date', '{"from":"YEAR_START","status":"PENDING","to":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-USER-ACCESS', 'As of Today', '{"asOf":"TODAY"}', true, true, now(), 'system'),
    ('system', 'UAM-USER-ACCESS', 'As of Last Month End', '{"asOf":"PREV_MONTH_END"}', true, true, now(), 'system')
on conflict (lower(owner), report_code, lower(name)) do nothing;
