-- =====================================================================================
-- Product Maintenance: Product Matrix, effective-dated package deactivation and the expiry and
-- anniversary notices of BDOI's FRS.
--   cat_product.description           Package Description column of the Product Matrix
--   audit_log.remarks                 Remarks column of the audit logs
--   pm_deactivation_request           Deactivation requests with effective date, reason, approver
--                                     and the approval decision; the approved request sets the
--                                     package expiry date to the later of the effective date and
--                                     the approval date
--   PM_DEACTIVATION_ROUTE             EFFECTIVE_DATED (BDOI's FRS, default) or RETIRE_REQUEST (the
--                                     retirement package request kept as an option, conflict C10)
--   PACKAGE_EXPIRY_NOTICE_DAYS        90 (BDOI's FRS)
--   PACKAGE_ANNIVERSARY_NOTICE_DAYS   90 (BDOI's FRS)
--   PACKAGE_EXPIRY_NOTIFY_MBS         false: the notices go to the TSU Officers and TSU Team Leads
--                                     (BDOI's FRS); true also tells MBS (conflict C02)
-- =====================================================================================

alter table cat_product add column description varchar(500);

-- Remarks of an audited action (the comment of an approval, a return or a rejection).
alter table audit_log add column remarks varchar(1000);

create table pm_deactivation_request (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    request_no        varchar(30)   not null,
    product_code      varchar(20)   not null references cat_product (code),
    version_no        integer,
    package_name      varchar(200)  not null,
    effective_date    date          not null,
    reason            varchar(40)   not null,
    remarks           varchar(1000),
    approver          varchar(50)   not null,
    status            varchar(20)   not null,
    package_end_date  date,
    decision_remarks  varchar(1000),
    decided_by        varchar(50),
    decided_at        timestamptz,
    expiry_date       date,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_pm_deactivation_no unique (request_no),
    constraint ck_pm_deactivation_status
        check (status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
create index ix_pm_deactivation_product on pm_deactivation_request (product_code, status);
create index ix_pm_deactivation_company on pm_deactivation_request (company_id, status, created_at);

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('PKG_DEACTIVATION_REASON', 'Package deactivation reason',
        'Why a package is deactivated before or at its expiry date', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(),
       now(), 'SYSTEM'
from (values
    ('PKG_DEACTIVATION_REASON', 'INSURER_WITHDRAWAL', 'Insurer withdrew the terms', 10),
    ('PKG_DEACTIVATION_REASON', 'REPLACED', 'Replaced by another package', 20),
    ('PKG_DEACTIVATION_REASON', 'LOSS_EXPERIENCE', 'Loss experience', 30),
    ('PKG_DEACTIVATION_REASON', 'LOW_UPTAKE', 'Low uptake', 40),
    ('PKG_DEACTIVATION_REASON', 'REGULATORY', 'Regulatory change', 50),
    ('PKG_DEACTIVATION_REASON', 'OTHERS', 'Others (see remarks)', 90)
) as v(type_code, code, label, sort_order);

update sys_parameter set param_value = '90', updated_at = now(), updated_by = 'SYSTEM'
where param_key = 'PACKAGE_EXPIRY_NOTICE_DAYS';

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('PM_DEACTIVATION_ROUTE', 'EFFECTIVE_DATED', 'STRING', 'PRODUCT_MAINTENANCE',
     'EFFECTIVE_DATED: Deactivate Package asks for the effective date, reason and approver (the bank''s process); RETIRE_REQUEST: deactivation through a retirement package request',
     null, null, now(), 'SYSTEM'),
    ('PKG_DEACTIVATION_PREFIX', 'PKD-', 'STRING', 'PRODUCT_MAINTENANCE',
     'Prefix of package deactivation request numbers; the year is appended', null, null, now(), 'SYSTEM'),
    ('PACKAGE_ANNIVERSARY_NOTICE_DAYS', '90', 'INTEGER', 'PRODUCT_MAINTENANCE',
     'Days before the package anniversary date at which the anniversary notice is raised', 1, 365, now(), 'SYSTEM'),
    ('PACKAGE_EXPIRY_NOTIFY_MBS', 'false', 'BOOLEAN', 'PRODUCT_MAINTENANCE',
     'false: the expiry and anniversary notices go to the TSU Officers and TSU Team Leads (the bank''s process); true: MBS is told as well',
     null, null, now(), 'SYSTEM');

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PM_DEACTIVATION_APPROVAL', 'Package deactivation for approval', 'PRODUCT_MAINTENANCE',
     'A package deactivation request names you as its approver', true, true, 900),
    ('PM_DEACTIVATION_DECIDED', 'Package deactivation decided', 'PRODUCT_MAINTENANCE',
     'Your package deactivation request was approved or rejected', true, true, 910),
    ('PM_PACKAGE_EXPIRY', 'Package expiry or anniversary', 'PRODUCT_MAINTENANCE',
     'A package reaches its expiry or anniversary date within the notice period', true, true, 920);

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by)
select 'PACKAGE_ANNIVERSARY', 'Package anniversary',
       'A released package reaches its anniversary date within the anniversary notice period.',
       'PRODUCT_MAINTENANCE', 'MEDIUM', null, 90, now(), 'SYSTEM'
where not exists (select 1 from alt_exception_code x where x.code = 'PACKAGE_ANNIVERSARY');
