-- User creation, update and status from the Enterprise SSO platform / UIDM-ISC (BDOI FRS FRUM.002.01,
-- FRUM.002.02, FRUM.003.01 to FRUM.003.03): the directory details of each user, the provisioning
-- events received with their outcome, and the accounts of the Enterprise SSO simulator used in SIT
-- and UAT. The break-glass sign-in alert to Information Security (FRUM.001.06) and the e-mail copy of
-- the request notices (FRUM.013.01).

-- ---------- Directory details of a user (retrieved from the Enterprise SSO platform) -------------
create table idn_directory_profile (
    id                bigint generated by default as identity primary key,
    username          varchar(50)  not null,
    windows_id        varchar(50)  not null,
    ad_email          varchar(120),
    ad_group          varchar(120),
    ad_status         varchar(20),
    ad_sync_at        timestamptz,
    first_name        varchar(60),
    last_name         varchar(60),
    display_name      varchar(120),
    team_leader_name  varchar(120),
    team_head_name    varchar(120),
    section_head_name varchar(120),
    unit_head_name    varchar(120),
    unit_segment      varchar(120),
    department        varchar(120),
    location          varchar(120),
    uidm_request_no   varchar(40),
    last_event_type   varchar(20),
    last_event_at     timestamptz,
    last_event_source varchar(20),
    sync_status       varchar(20)  not null default 'SYNCED',
    sync_message      varchar(500),
    created_at        timestamptz  not null,
    created_by        varchar(50)  not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_idn_profile_user unique (username),
    constraint ck_idn_profile_sync check (sync_status in ('SYNCED', 'FAILED'))
);
create index ix_idn_profile_windows on idn_directory_profile (lower(windows_id));

-- ---------- Provisioning events received (applied, refused or failed) ---------------------------
create table idn_identity_event (
    id              bigint generated by default as identity primary key,
    received_at     timestamptz  not null,
    source          varchar(20)  not null,
    event_type      varchar(20)  not null,
    windows_id      varchar(50),
    user_id         varchar(50),
    uidm_request_no varchar(40),
    ad_status       varchar(20),
    payload         text         not null,
    status          varchar(20)  not null,
    username        varchar(50),
    message         varchar(500),
    processed_at    timestamptz,
    processed_by    varchar(50),
    attempts        integer      not null default 1,
    constraint ck_idn_event_source check (source in ('UIDM_ISC', 'ENTERPRISE_SSO', 'ON_DEMAND')),
    constraint ck_idn_event_type check (event_type in ('JOINER', 'MOVER', 'LEAVER', 'REHIRE', 'STATUS')),
    constraint ck_idn_event_status check (status in ('APPLIED', 'REFUSED', 'FAILED', 'NO_CHANGE'))
);
create index ix_idn_event_received on idn_identity_event (received_at desc);
create index ix_idn_event_windows on idn_identity_event (lower(windows_id));
create index ix_idn_event_status on idn_identity_event (status, received_at desc);

-- ---------- Accounts of the Enterprise SSO simulator (SIT and UAT only) --------------------------
create table idn_sim_directory_account (
    id                bigint generated by default as identity primary key,
    windows_id        varchar(50)  not null,
    user_id           varchar(50)  not null,
    email             varchar(120) not null,
    first_name        varchar(60)  not null,
    last_name         varchar(60)  not null,
    display_name      varchar(120) not null,
    ad_group          varchar(120),
    status            varchar(20)  not null,
    team_leader_name  varchar(120),
    team_head_name    varchar(120),
    section_head_name varchar(120),
    unit_head_name    varchar(120),
    unit_segment      varchar(120),
    department        varchar(120),
    location          varchar(120),
    uidm_request_no   varchar(40),
    updated_at        timestamptz  not null,
    constraint uq_idn_sim_windows unique (windows_id),
    constraint ck_idn_sim_status check (status in ('ACTIVE', 'INACTIVE', 'LOCKED', 'DISABLED', 'DEACTIVATED'))
);

-- ---------- Settings ---------------------------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('UAM_SSO_PROVISIONING', 'true', 'BOOLEAN', 'SECURITY',
     'true: users are created, updated, deactivated and reactivated from the Enterprise SSO / UIDM-ISC events and from an active Enterprise SSO account (BDOI''s FRS, C01 option a); false: only through approved access requests',
     null, null, now(), 'SYSTEM'),
    ('UAM_PROVISIONING_ROLES', 'false', 'BOOLEAN', 'SECURITY',
     'true: the group profiles named in a UIDM-ISC event are given to the user (C01 option b); false: group profiles only through approved requests in the system (option a)',
     null, null, now(), 'SYSTEM'),
    ('BREAK_GLASS_ALERT_RECIPIENTS', '', 'STRING', 'SECURITY',
     'E-mail addresses of Information Security, separated by commas, alerted at every break-glass sign-in while single sign-on is on (the security-setting approvers are also told in the system)',
     null, null, now(), 'SYSTEM'),
    ('UAM_REQUEST_NOTICE_EMAIL', 'true', 'BOOLEAN', 'SECURITY',
     'true: the notices of access requests are also e-mailed to each user who chose e-mail in the notification preferences (BDOI''s FRS); false: in the system only',
     null, null, now(), 'SYSTEM');

-- ---------- Notification events and alerts ----------------------------------------------------
insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('UAM_IDENTITY_REFUSED', 'Identity event refused', 'USER_ACCESS',
     'An event of the Enterprise SSO platform or UIDM-ISC could not be applied and waits for review', true, true, 670),
    ('UAM_BREAK_GLASS_SIGN_IN', 'Break-glass sign-in', 'USER_ACCESS',
     'A break-glass System Administrator signed in with a local password while single sign-on is on', true, true, 680);

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by) values
    ('UAM_IDENTITY_REFUSED', 'Identity event refused',
     'An event of the Enterprise SSO platform or UIDM-ISC was refused (for example a Windows ID held by another user) or failed.',
     'USER_ACCESS', 'HIGH', null, null, now(), 'SYSTEM'),
    ('UAM_BREAK_GLASS_SIGN_IN', 'Break-glass sign-in',
     'A break-glass System Administrator signed in with a local password and the second factor while single sign-on is on.',
     'USER_ACCESS', 'HIGH', null, null, now(), 'SYSTEM');
