-- =====================================================================================
-- Product Maintenance routing of BDOI's FRS, each kept selectable with the existing behaviour:
--   pm_request.source                 Source of a package request: Marketing, TSU or Insurer
--   pm_request.request_details        The Annex E fields of the request form not held elsewhere
--   pm_request.marketing_level        Marketing approvals given (Team Leader, Team Head, Unit Head)
--   pm_marketing_approval             History of the Marketing approvals of a request
--   pm_mancom_approval                ManCom approvers selected for a request and their decisions
--   MANCOM_APPROVED stage             ManCom approved; the deployment is requested by a button
--   pm_request.deployment_*           Package Deployment Request number, date and requestor
--   cat_product incentive and Annex A Incentive Eligible, Incentive Amount or Commission Rate,
--                                     Policy Type and Insured's Name of a Product Matrix record
--   pm_master_change                  Product master changes for the other BDOI systems, their
--                                     transfer file, status, attempts and errors
--   pm_master_sim_inbox               The receiving system of the product master changes in SIT/UAT
--   Settings: PM_MARKETING_CHAIN (ANY_ONE: one approval by the TL, TH or UH as BRPM.008 states;
--   TL_TH_UH: BDOI's chain, conflict C05), PM_MANCOM_ROUTING (SELECTED_PARALLEL_THEN_PRESIDENT:
--   BDOI's, conflict C17; ANY_MEMBER), PM_MANCOM_PRESIDENT, PM_DEPLOYMENT_REQUEST (AUTO: BRPM.015
--   forwards automatically; MANUAL: BDOI's button, conflict C20), PM_DIRECT_MAINTENANCE (true:
--   BDOI's direct maintenance with approval; false: packages only through package requests, C09).
-- =====================================================================================

alter table pm_request add column source varchar(20) not null default 'MARKETING';
alter table pm_request add constraint ck_pm_request_source
    check (source in ('MARKETING', 'TSU', 'INSURER'));
alter table pm_request add column request_details text;
alter table pm_request add column marketing_level integer not null default 0;
alter table pm_request add column deployment_no varchar(30);
alter table pm_request add column deployment_requested_at timestamptz;
alter table pm_request add column deployment_requested_by varchar(50);
alter table pm_request drop constraint ck_pm_request_status;
alter table pm_request add constraint ck_pm_request_status check (status in ('DRAFT',
    'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'FOR_TSU_APPROVAL', 'NEGOTIATION', 'TERMS_REVIEW',
    'FOR_MKT_REVIEW', 'REQUIREMENTS_PREP', 'FOR_MANCOM', 'MANCOM_APPROVED', 'WITH_MBS',
    'FOR_VALIDATION', 'RELEASED', 'RETIRED', 'NOT_PROCEEDED', 'VOIDED'));

create table pm_marketing_approval (
    id          bigint generated by default as identity primary key,
    request_id  bigint        not null references pm_request (id),
    level_no    integer       not null,
    approver    varchar(50)   not null,
    decision    varchar(20)   not null,
    remarks     varchar(1000),
    decided_at  timestamptz   not null,
    constraint ck_pm_marketing_approval check (decision in ('APPROVED', 'RETURNED', 'REJECTED'))
);
create index ix_pm_marketing_approval on pm_marketing_approval (request_id, id);

create table pm_mancom_approval (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    request_id  bigint        not null references pm_request (id),
    round_no    integer       not null,
    approver    varchar(50)   not null,
    president   boolean       not null default false,
    status      varchar(20)   not null,
    remarks     varchar(1000),
    decided_at  timestamptz,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_pm_mancom_approval check (status in ('WAITING', 'PENDING', 'APPROVED',
        'RETURNED', 'REJECTED', 'CLOSED'))
);
create index ix_pm_mancom_approval on pm_mancom_approval (request_id, round_no);
create index ix_pm_mancom_approver on pm_mancom_approval (lower(approver), status);

insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('PM_PACKAGE_REQUEST', 'MANCOM_APPROVED', 'ManCom approved, deployment to request',
        'PKG_NEGOTIATE', 24, false, false, 95);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('PM_PACKAGE_REQUEST', 'FOR_MANCOM', 'signoff_hold', 'MANCOM_APPROVED',
        'Sign off (deployment requested separately)', 'PKG_MANCOM_SIGNOFF', false, null, 15),
       ('PM_PACKAGE_REQUEST', 'MANCOM_APPROVED', 'request_deployment', 'WITH_MBS',
        'Request for Deployment', 'PKG_NEGOTIATE,PKG_REQUEST', false, null, 10),
       ('PM_PACKAGE_REQUEST', 'DRAFT', 'submit_to_tsu', 'FOR_TSU_REVIEW',
        'Submit to TSU (source TSU or Insurer)', 'PKG_REQUEST', false, null, 15);

alter table cat_product add column incentive_eligible boolean not null default false;
alter table cat_product add column incentive_amount numeric(19, 2);
alter table cat_product add column incentive_rate numeric(9, 4);
alter table cat_product add column policy_type varchar(30);
alter table cat_product add column insured_name varchar(250);
alter table cat_product add constraint ck_cat_product_incentive check (
    (incentive_amount is null or incentive_amount > 0)
    and (incentive_rate is null or (incentive_rate > 0 and incentive_rate <= 100))
    and (not incentive_eligible or incentive_amount is not null or incentive_rate is not null));

create table pm_master_change (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    product_code      varchar(20)   not null,
    version_no        integer,
    change_kind       varchar(20)   not null,
    effective_date    date,
    source_request_no varchar(40),
    status            varchar(20)   not null,
    attempts          integer       not null default 0,
    file_name         varchar(120),
    sent_at           timestamptz,
    error             varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_pm_master_change check (status in ('PENDING', 'SENT', 'FAILED'))
);
create index ix_pm_master_change on pm_master_change (status, created_at);

create table pm_master_sim_inbox (
    id           bigint generated by default as identity primary key,
    file_name    varchar(120) not null,
    content      text         not null,
    record_count integer      not null,
    received_at  timestamptz  not null
);

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('PKG_REQUEST_SOURCE', 'Package request source', 'Who originates a package request', true, now(), 'SYSTEM'),
       ('PKG_POLICY_TYPE', 'Policy type', 'Policy type of a Product Matrix record', true, now(), 'SYSTEM'),
       ('PKG_BUSINESS_ORIGIN', 'Business origin', 'Business source or origin of a package request', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(),
       now(), 'SYSTEM'
from (values
    ('PKG_REQUEST_SOURCE', 'MARKETING', 'Marketing', 10),
    ('PKG_REQUEST_SOURCE', 'TSU', 'TSU', 20),
    ('PKG_REQUEST_SOURCE', 'INSURER', 'Insurer', 30),
    ('PKG_POLICY_TYPE', 'INDIVIDUAL', 'Individual', 10),
    ('PKG_POLICY_TYPE', 'FLEET', 'Fleet', 20),
    ('PKG_POLICY_TYPE', 'GROUP', 'Group', 30),
    ('PKG_POLICY_TYPE', 'SINGLE_LOCATION', 'Single Location', 40),
    ('PKG_POLICY_TYPE', 'VARIOUS_LOCATIONS', 'Various Locations', 50),
    ('PKG_BUSINESS_ORIGIN', 'BANK_REFERRAL', 'Bank referral', 10),
    ('PKG_BUSINESS_ORIGIN', 'DIRECT', 'Direct client', 20),
    ('PKG_BUSINESS_ORIGIN', 'INSURER_OFFER', 'Insurer offer', 30),
    ('PKG_BUSINESS_ORIGIN', 'AFFINITY', 'Affinity or programme', 40),
    ('UAM_USER_LEVEL', 'TEAM_LEAD', 'Team Leader', 10),
    ('UAM_USER_LEVEL', 'TEAM_HEAD', 'Team Head', 20),
    ('UAM_USER_LEVEL', 'UNIT_HEAD', 'Unit Head', 30)
) as v(type_code, code, label, sort_order)
where not exists (select 1 from lov_value x where x.type_code = v.type_code and x.code = v.code);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('PM_MARKETING_CHAIN', 'ANY_ONE', 'STRING', 'PRODUCT_MAINTENANCE',
     'ANY_ONE: one approval by the Marketing Team Leader, Team Head or Unit Head; TL_TH_UH: approval by the Team Leader, then the Team Head, then the Unit Head (the bank''s process)',
     null, null, now(), 'SYSTEM'),
    ('PM_MANCOM_ROUTING', 'SELECTED_PARALLEL_THEN_PRESIDENT', 'STRING', 'PRODUCT_MAINTENANCE',
     'SELECTED_PARALLEL_THEN_PRESIDENT: the selected ManCom approvers approve in parallel, then the President (the bank''s process); ANY_MEMBER: one sign-off',
     null, null, now(), 'SYSTEM'),
    ('PM_MANCOM_PRESIDENT', '', 'STRING', 'PRODUCT_MAINTENANCE',
     'User ID of the President, who approves after every other selected ManCom approver', null, null, now(), 'SYSTEM'),
    ('PM_DEPLOYMENT_REQUEST', 'AUTO', 'STRING', 'PRODUCT_MAINTENANCE',
     'AUTO: the ManCom approval forwards the package to MBS; MANUAL: the Request for Deployment button forwards it (the bank''s process)',
     null, null, now(), 'SYSTEM'),
    ('PKG_DEPLOYMENT_PREFIX', 'PDR-', 'STRING', 'PRODUCT_MAINTENANCE',
     'Prefix of package deployment request numbers; the year is appended', null, null, now(), 'SYSTEM'),
    ('PM_DIRECT_MAINTENANCE', 'true', 'BOOLEAN', 'PRODUCT_MAINTENANCE',
     'true: authorized users add and update Product Matrix records directly with approval (the bank''s process); false: new packages come only from package requests',
     null, null, now(), 'SYSTEM'),
    ('PKG_MIN_POLICIES', '20', 'INTEGER', 'PRODUCT_MAINTENANCE',
     'Least estimated number of policies of a package request', 0, 100000, now(), 'SYSTEM'),
    ('PKG_MIN_PREMIUM', '5000000', 'DECIMAL', 'PRODUCT_MAINTENANCE',
     'Least estimated total basic premium of a package request (base currency)', 0, null, now(), 'SYSTEM');

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PM_TSU_REVIEW', 'Request for TSU review', 'PRODUCT_MAINTENANCE',
     'A package request or a quotation request entered TSU review', true, false, 930),
    ('PM_MANCOM_APPROVAL', 'ManCom approval', 'PRODUCT_MAINTENANCE',
     'A package request waits for your ManCom approval', true, true, 940),
    ('PM_APPROVALS_COMPLETE', 'Package approvals complete', 'PRODUCT_MAINTENANCE',
     'Every required approval of your package request is complete', true, false, 950),
    ('PM_DEPLOYMENT_REQUESTED', 'Package deployment requested', 'PRODUCT_MAINTENANCE',
     'A package deployment request waits for MBS', true, false, 960),
    ('PM_PRODUCT_APPROVAL', 'Product Matrix record for approval', 'PRODUCT_MAINTENANCE',
     'A Product Matrix record names you as its approver', true, true, 970),
    ('PM_MARKETING_APPROVAL', 'Package request for Marketing approval', 'PRODUCT_MAINTENANCE',
     'A package request waits for the next Marketing approval', true, false, 980);

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by)
select 'PM_MASTER_TRANSFER_FAILED', 'Product master transfer failed',
       'A file of product master changes could not be delivered to the receiving system.',
       'PRODUCT_MAINTENANCE', 'HIGH', null, null, now(), 'SYSTEM'
where not exists (select 1 from alt_exception_code x where x.code = 'PM_MASTER_TRANSFER_FAILED');
