-- =====================================================================================
-- The comparative table, insurer selection, Final Terms for Proposal, proposal slips per insurer
-- and the client response of BDOI's FRS, for quotation requests of non-package products and for
-- package requests (record_type ProposalRequest or PackageRequest):
--   pm_terms_option          Quotation options of an insurer (several per insurer) with the
--                            insurer response (Approved, Not Covered, Others with the wording)
--   pm_terms_setting         Fields shown in the comparative table and sent to the client, and the
--                            insurers selected for the proposal
--   pm_final_term            Final Terms for Proposal per field, with pm_final_term_history
--   pm_proposal_file         Proposal slips per insurer and version with their file name
--   pm_client_response       Client response (Accepted, Rejected, Return for Revision)
--   NB_PROPOSAL transitions  proceed_to_proposal (requestor, insurers selected) and client_return
-- =====================================================================================

create table pm_terms_option (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    record_type    varchar(30)   not null,
    record_id      bigint        not null,
    insurer_code   varchar(30)   not null,
    insurer_name   varchar(200)  not null,
    option_no      integer       not null,
    answer         varchar(20)   not null,
    other_answer   varchar(500),
    option_values  text          not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_pm_terms_option unique (record_type, record_id, insurer_code, option_no),
    constraint ck_pm_terms_option_answer check (answer in ('APPROVED', 'NOT_COVERED', 'OTHERS'))
);

create table pm_terms_setting (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    record_type       varchar(30)   not null,
    record_id         bigint        not null,
    display_fields    varchar(500),
    client_fields     varchar(500),
    selected_insurers varchar(500),
    selected_by       varchar(50),
    selected_at       timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_pm_terms_setting unique (record_type, record_id)
);

create table pm_final_term (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    record_type  varchar(30)   not null,
    record_id    bigint        not null,
    field_key    varchar(30)   not null,
    field_value  varchar(1000),
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_pm_final_term unique (record_type, record_id, field_key)
);

create table pm_final_term_history (
    id           bigint generated by default as identity primary key,
    record_type  varchar(30)   not null,
    record_id    bigint        not null,
    field_key    varchar(30)   not null,
    old_value    varchar(1000),
    new_value    varchar(1000),
    changed_by   varchar(50)   not null,
    changed_at   timestamptz   not null
);
create index ix_pm_final_term_history on pm_final_term_history (record_type, record_id, id);

create table pm_proposal_file (
    id            bigint generated by default as identity primary key,
    record_type   varchar(30)   not null,
    record_id     bigint        not null,
    insurer_code  varchar(30)   not null,
    insurer_name  varchar(200)  not null,
    version_no    integer       not null,
    file_name     varchar(200)  not null,
    attachment_id bigint,
    generated_by  varchar(50)   not null,
    generated_at  timestamptz   not null,
    constraint uq_pm_proposal_file unique (record_type, record_id, insurer_code, version_no)
);

create table pm_client_response (
    id            bigint generated by default as identity primary key,
    record_type   varchar(30)   not null,
    record_id     bigint        not null,
    response      varchar(20)   not null,
    response_date date          not null,
    remarks       varchar(1000),
    insurers      varchar(500),
    recorded_by   varchar(50)   not null,
    recorded_at   timestamptz   not null,
    constraint ck_pm_client_response check (response in ('ACCEPTED', 'REJECTED', 'RETURNED'))
);
create index ix_pm_client_response on pm_client_response (record_type, record_id, id);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_PROPOSAL', 'QS_SENT', 'proceed_to_proposal', 'TERMS_RECEIVED', 'Proceed to Proposal',
        'PROPOSAL_REQUEST', false, null, 15),
       ('NB_PROPOSAL', 'SENT_TO_CLIENT', 'client_return', 'TERMS_RECEIVED',
        'Client returned for revision', 'PROPOSAL_REQUEST', false, null, 30);

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PM_TERMS_AGREED', 'Insurers selected for the proposal', 'PRODUCT_MAINTENANCE',
     'The requestor selected the insurers of a quotation request and asks for the proposal', true, false, 990),
    ('PM_PROPOSAL_DECIDED', 'Proposal approved, returned or rejected', 'PRODUCT_MAINTENANCE',
     'The proposal of a quotation request was approved, returned or rejected', true, false, 1000),
    ('PM_CLIENT_RESPONSE', 'Client response recorded', 'PRODUCT_MAINTENANCE',
     'The client accepted, rejected or returned a proposal for revision', true, false, 1010);
