-- =====================================================================================
-- Consolidated Placement Update Report: the weekly run (day and time configurable) and the
-- repository of the generated files with the rows shown in the preview.
--   pm_placement_report       one generated file per company and report date, with the reporting
--                             period, the archived report run (download), the rows and who/when
--   PLACEMENT_UPDATE_DAY      weekday of the run (THURSDAY)
--   PLACEMENT_UPDATE_TIME     time of the run (08:00, business time zone)
--   PLACEMENT_UPDATE_DAYS     length of the reporting period in days (7)
--   PLACEMENT_UPDATE_SCOPE    QUOTATION (quotation requests) or QUOTATION_AND_PACKAGE
-- =====================================================================================

create table pm_placement_report (
    id            bigint generated by default as identity primary key,
    company_id    bigint        not null references org_company (id),
    report_date   date          not null,
    period_from   date          not null,
    period_to     date          not null,
    scope         varchar(30)   not null,
    trigger_type  varchar(20)   not null,
    file_name     varchar(200)  not null,
    run_id        bigint,
    record_count  integer       not null,
    rows_json     text          not null,
    generated_by  varchar(50)   not null,
    generated_at  timestamptz   not null,
    constraint ck_pm_placement_trigger check (trigger_type in ('SCHEDULED', 'ON_REQUEST'))
);
create index ix_pm_placement_report on pm_placement_report (company_id, report_date desc, id desc);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('PLACEMENT_UPDATE_DAY', 'THURSDAY', 'STRING', 'PRODUCT_MAINTENANCE',
     'Weekday of the scheduled Consolidated Placement Update Report (MONDAY to SUNDAY)',
     null, null, now(), 'SYSTEM'),
    ('PLACEMENT_UPDATE_TIME', '08:00', 'STRING', 'PRODUCT_MAINTENANCE',
     'Time of the scheduled Consolidated Placement Update Report (HH:MM, business time zone)',
     null, null, now(), 'SYSTEM'),
    ('PLACEMENT_UPDATE_DAYS', '7', 'INTEGER', 'PRODUCT_MAINTENANCE',
     'Length of the reporting period of the Consolidated Placement Update Report in days, ending on the report date',
     1, 92, now(), 'SYSTEM'),
    ('PLACEMENT_UPDATE_SCOPE', 'QUOTATION', 'STRING', 'PRODUCT_MAINTENANCE',
     'QUOTATION: the report lists the quotation requests (the bank''s process); QUOTATION_AND_PACKAGE: the package requests follow',
     null, null, now(), 'SYSTEM');

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PM_PLACEMENT_UPDATE', 'Placement Update Report generated', 'PRODUCT_MAINTENANCE',
     'The Consolidated Placement Update Report of the week is in the repository', true, false, 1020);
