-- =====================================================================================
-- iNXT BrokerVerse - V2750 Cashiering: BDOI's creation, cancellation and reinstatement records
-- (Operations Cashiering FRS v3.2: FRS.CSH.02.01, 02.02, 02.05, 03.01, 04.01).
--   csh_receipt_record          one record per AR / OR to create, cancel or reinstate, numbered
--                               <Prefix>-<Receipt Type>-<Sequence> (CR-AR, CR-OR, CN-AR, CN-OR,
--                               RE-AR, RE-OR), with the statuses Created, For Posting, Returned,
--                               posted (AR/OR Issued, Cancelled or Reinstated) and Record Cancelled
--   csh_receipt_record_account  the accounts of a record with the amount of each
--   csh_bank_account            the maintained list "Post to Bank Account" with its currency,
--                               default per currency and GL account
--   sys_parameter               the settings that carry the points BDOI decides (Appendix R)
-- =====================================================================================

create table csh_receipt_record (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    record_no          varchar(40)    not null,
    record_kind        varchar(15)    not null
        check (record_kind in ('CREATION', 'CANCELLATION', 'REINSTATEMENT')),
    receipt_kind       varchar(2)     not null check (receipt_kind in ('AR', 'OR')),
    receipt_type       varchar(30)    not null,
    stage              varchar(20)    not null
        check (stage in ('CREATED', 'FOR_POSTING', 'RETURNED', 'POSTED', 'RECORD_CANCELLED')),
    branch_id          bigint         references org_branch (id),
    entry_type         varchar(10)    check (entry_type in ('CLIENT', 'INSURER', 'OTHER')),
    client_code        varchar(30),
    client_name        varchar(250),
    insurer_code       varchar(30),
    insurer_name       varchar(250),
    insurer_bank       varchar(100),
    payor_name         varchar(250),
    tender_type        varchar(20)    check (tender_type in ('CASH', 'CHECK', 'DIRECT_CREDIT')),
    currency           varchar(3),
    bank_account       varchar(40),
    amount             numeric(19, 2),
    vat                numeric(19, 2),
    wtax               numeric(19, 2),
    certificate_ref    varchar(60),
    check_no           varchar(40),
    check_date         date,
    check_bank         varchar(60),
    receipt_date       date,
    remarks            varchar(250),
    other_income_ref   varchar(60),
    receipt_id         bigint         references csh_receipt (id),
    receipt_no         varchar(40),
    reason_code        varchar(40),
    reason_text        varchar(250),
    reinstatement_type varchar(10)    check (reinstatement_type in ('FULL', 'PARTIAL')),
    invoice_no         varchar(40),
    account_officer    varchar(100),
    unit_head          varchar(100),
    team_leader        varchar(100),
    return_reason      varchar(250),
    submitted_by       varchar(50),
    submitted_at       timestamptz,
    posted_by          varchar(50),
    posted_at          timestamptz,
    posting_result     varchar(500),
    journal_batch_no   varchar(40),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_csh_receipt_record unique (company_id, record_no)
);
create index ix_csh_receipt_record_stage on csh_receipt_record (company_id, record_kind, stage);
create index ix_csh_receipt_record_receipt on csh_receipt_record (receipt_id);

create table csh_receipt_record_account (
    record_id   bigint         not null references csh_receipt_record (id),
    line_no     integer        not null,
    reference   varchar(60)    not null,
    amount      numeric(19, 2) not null,
    primary key (record_id, line_no)
);

create table csh_bank_account (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    code                 varchar(40)   not null,
    name                 varchar(120)  not null,
    currency             varchar(3)    not null,
    gl_account_code      varchar(30),
    default_for_currency boolean       not null default false,
    active               boolean       not null default true,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_csh_bank_account unique (company_id, code)
);

-- BDOI's list of FRS.CSH.02.01.02 / 02.02.02 for every company (the GL account is set by
-- Comptrollership; without it the collection account parameter applies).
insert into csh_bank_account (company_id, code, name, currency, default_for_currency, created_at,
                              created_by)
select c.id, v.code, v.name, v.currency, v.dflt, now(), 'SYSTEM'
from org_company c
cross join (values
    ('DFLB_CURRENT_ORTIGAS', 'DFLB - Current (BDO Ortigas)', 'PHP', false),
    ('DFLB_SAVINGS_ORTIGAS', 'DFLB Savings (BDO Ortigas)', 'PHP', true),
    ('DFLB_SAVINGS_MALL', 'DFLB Savings Mall (Peso)', 'PHP', false),
    ('DFLB_SAVINGS_TRADE', 'DFLB Savings Trade (Peso)', 'PHP', false),
    ('DFLB_SAVINGS_FX', 'DFLB Savings FX (BDO Ortigas)', 'USD', true)
) as v(code, name, currency, dflt)
on conflict (company_id, code) do nothing;

-- ---------- Settings for BDOI's decisions (Appendix R) ---------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('CASH_POSTING_STEP_RECEIPTS', 'AR,OR', 'CODE_LIST', 'OPERATIONS',
     'Receipt kinds whose number is issued only when a second user posts the creation record (AR, OR); blank = issue at save (Appendix R, C1)',
     null, null, now(), 'SYSTEM'),
    ('CASH_REINSTATEMENT_SCOPE', 'BOTH', 'STRING', 'OPERATIONS',
     'What Reinstate does: ISSUED = reverse the payment of an issued receipt, CANCELLED = restore a cancelled receipt, BOTH (Appendix R, C2)',
     null, null, now(), 'SYSTEM'),
    ('CASH_RECORD_NO_FORMAT', '{PREFIX}-{TYPE}-{SEQ}', 'STRING', 'OPERATIONS',
     'Number of creation, cancellation and reinstatement records; tokens {PREFIX} (CR, CN, RE), {TYPE} (AR, OR), {YEAR}, {SEQ} (Appendix R, C3)',
     null, null, now(), 'SYSTEM'),
    ('CASH_RECEIPT_NO_FORMAT', '{PREFIX}-{YEAR}-{BRANCH}-{SEQ}', 'STRING', 'OPERATIONS',
     'Number format proposed for a new AR / OR series; tokens {PREFIX}, {YEAR}, {BRANCH} (branch indicator), {SEQ}; blank = prefix and sequence (Appendix R, C4)',
     null, null, now(), 'SYSTEM'),
    ('CASH_CERTIFICATE_NO_FORMAT', 'AC_{BRANCH}_{MMYYYY}_{SEQ}', 'STRING', 'OPERATIONS',
     'Acknowledgement certificate number given per printed receipt; tokens {BRANCH}, {MMYYYY} of the print date, {SEQ} (5 digits) (Appendix R, C4)',
     null, null, now(), 'SYSTEM'),
    ('CASH_CHECK_DATE_RULE', 'ON', 'STRING', 'OPERATIONS',
     'ON = a check payment is refused at receipting when its date is within the holding period; OFF = accepted when presented (Appendix R, C7)',
     null, null, now(), 'SYSTEM'),
    ('CASH_CHECK_HOLDING_DAYS', '4', 'INTEGER', 'OPERATIONS',
     'Working days of the check holding period at receipting (Appendix R, C7)', 0, 30, now(), 'SYSTEM'),
    ('CASH_AR_REMARKS_REQUIRED', 'Y', 'STRING', 'OPERATIONS',
     'Y = Remarks are a required field of the AR and OR creation record (Appendix R, C25)', null, null,
     now(), 'SYSTEM'),
    ('CASH_MAX_PAID_AMOUNT', '1000000000.00', 'DECIMAL', 'OPERATIONS',
     'Highest paid amount of one AR or OR creation record (FRS.CSH.02.01.02)', null, null, now(), 'SYSTEM'),
    ('CASH_CHECK_BEFORE_CASH', 'Y', 'STRING', 'OPERATIONS',
     'Y = check payments are posted and applied before cash payments of the same posting run (Appendix R, C6)',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

-- The bank account a receipt is posted to (FRS.CSH.02.01.02 "Post to Bank Account").
alter table csh_receipt add column if not exists bank_account varchar(40);

-- Notices of the records (Appendix G): for posting to the Approvers/Posters; returned or posted
-- to the creator.
insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('CASH_RECORD_FOR_POSTING', 'Cashiering record for posting', 'CASHIERING',
     'An AR / OR creation, cancellation or reinstatement record was submitted for posting', true, false, 91),
    ('CASH_RECORD_DECIDED', 'Cashiering record returned or posted', 'CASHIERING',
     'An AR / OR record you created was returned with a reason or posted', true, false, 92)
on conflict (code) do nothing;

-- Year of a receipt series and its number format (FRS.CSH.02.03.02 / 02.03.03; Appendix R, C4):
-- the format keeps the prefix, year and branch indicator of the series and the token {SEQ}; a
-- series without a format numbers as before (prefix and zero-filled sequence).
alter table csh_receipt_series add column if not exists series_year integer;
alter table csh_receipt_series add column if not exists number_format varchar(80);

-- Unapplied payment types of BDOI's FRS (FRS.CSH.06.01.03): AR Insurer Refund (cancellation or
-- reinstatement of a remitted AR), AP Unapplied Commission (reinstatement of an OR), Commission
-- Receivable payment (cancellation of an OR) and the unapplied payment of a reinstated AR.
alter table csh_unapplied drop constraint if exists ck_csh_unapplied_origin;
alter table csh_unapplied add constraint ck_csh_unapplied_origin check (origin in ('NO_MATCH', 'EXCESS',
    'CANCELLED_REFERENCE', 'ADJUSTMENT', 'CANCELLATION', 'DP_REINSTATE', 'REMITTANCE_RETURN', 'REAPPLY',
    'PREBOOKED', 'OTHER', 'MIGRATED', 'AR_INSURER_REFUND', 'AP_UNAPPLIED_COMMISSION',
    'COMMISSION_RECEIVABLE', 'REINSTATEMENT'));

-- Accounting events of the cancellation and reinstatement records (FRS.CSH.03.01.09, 04.01.10;
-- Appendix I). The accounts are configured by Comptrollership.
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('OPS_AR_INSURER_REFUND', 'Reversed payment to AR Insurer Refund', 'RECEIPT', 'RECEIPT',
  'Cancellation or reinstatement of an AR whose premium was already remitted: the reversed payment becomes a '
  || 'refund receivable from the insurer of each account (FRS.CSH.03.01.08, 04.01.09).',
  'AMOUNT'),
 ('OPS_COMMISSION_PAYMENT_HELD', 'Cancelled OR payment kept for Commission Receivable', 'RECEIPT', 'RECEIPT',
  'Cancellation of an OR: the payment stays in the bank as a Commission Receivable payment of each account and '
  || 'insurer, for re-application (FRS.CSH.03.01.08).',
  'AMOUNT'),
 ('OPS_AP_UNAPPLIED_COMMISSION', 'Reinstated OR payment to AP Unapplied Commission', 'RECEIPT', 'RECEIPT',
  'Reinstatement of an OR: the commission receivable of each account is outstanding again and the payment is an '
  || 'AP Unapplied Commission of the insurer (FRS.CSH.04.01.09).',
  'AMOUNT')
on conflict (code) do nothing;

-- Settings of the cancellation and reinstatement records (Appendix R).
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('CASH_REMITTED_CANCELLATION', 'AR_INSURER_REFUND', 'STRING', 'OPERATIONS',
     'Cancellation of an AR already remitted: AR_INSURER_REFUND = the payment becomes an AR Insurer Refund; REVERSE_ALL = every application is reversed (Appendix R, C9)',
     null, null, now(), 'SYSTEM'),
    ('CASH_CHECK_CANCEL_REASONS', 'PRM_CHECK_AMOUNT,PRM_NO_SIGNATURE,PRM_INCORRECT_PAYEE,PRM_INCORRECT_CHECK', 'CODE_LIST', 'OPERATIONS',
     'Cancellation reasons allowed for a check payment; blank = every reason (Appendix R, C21)', null, null,
     now(), 'SYSTEM')
on conflict (param_key) do nothing;
