-- =====================================================================================
-- Cashiering: the AR and OR forms and the printing of receipts (FRS.CSH.02.04, 02.06).
--   csh_receipt_form            versions of the AR and OR forms (header, body notes, footer lines),
--                               effective from a date once another authorised user approves them
--   csh_receipt                 certificate number given at the first print (C4)
--   csh_print_batch / _line     copy printed, ZIP of the receipts, reprint mark, skipped receipts
--   csh_certificate_of_payment  series number of the Certification of Payment
-- =====================================================================================

create table csh_receipt_form (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    company_id          bigint        not null references org_company (id),
    form_kind           varchar(2)    not null check (form_kind in ('AR', 'OR')),
    version_no          integer       not null,
    company_name        varchar(150),
    company_description varchar(200),
    company_address     varchar(300),
    company_vat         varchar(40),
    note_line           varchar(500),
    footer_1            varchar(500),
    footer_2            varchar(500),
    footer_3            varchar(500),
    footer_4            varchar(500),
    effective_from      date          not null,
    status              varchar(20)   not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    decided_by          varchar(50),
    decided_at          timestamp with time zone,
    decision_remarks    varchar(250),
    created_at          timestamp with time zone not null default now(),
    created_by          varchar(50)   not null,
    updated_at          timestamp with time zone,
    updated_by          varchar(50),
    constraint uq_csh_receipt_form unique (company_id, form_kind, version_no)
);

insert into csh_receipt_form (company_id, form_kind, version_no, company_description, note_line,
    footer_1, footer_2, footer_3, footer_4, effective_from, status, decided_by, decided_at,
    created_by)
select c.id, 'OR', 1, null, null,
       '{COMPANY_NAME} is a licensed broker of the Insurance Commission of the Philippines.',
       'ACKNOWLEDGEMENT CERTIFICATE NO. {CERTIFICATE_NO} Date issued {PRINT_DATE} Series Range: {SERIES_RANGE}',
       'THIS DOCUMENT IS NOT VALID FOR CLAIM OF INPUT TAX.',
       '{COPY_LABEL}',
       date '2000-01-01', 'APPROVED', 'SYSTEM', now(), 'SYSTEM'
  from org_company c;

insert into csh_receipt_form (company_id, form_kind, version_no, company_description, note_line,
    footer_1, footer_2, footer_3, footer_4, effective_from, status, decided_by, decided_at,
    created_by)
select c.id, 'AR', 1, null,
       'Note: Official receipt to be issued by the insurance company.',
       'THIS IS A SYSTEM GENERATED RECEIPT. NO SIGNATURE IS REQUIRED.',
       '{COMPANY_NAME} is a licensed broker of the Insurance Commission of the Philippines.',
       'ACKNOWLEDGEMENT CERTIFICATE NO. {CERTIFICATE_NO} Date issued {PRINT_DATE} Series Range: {SERIES_RANGE}',
       'THIS DOCUMENT IS NOT VALID FOR CLAIM OF INPUT TAX.',
       date '2000-01-01', 'APPROVED', 'SYSTEM', now(), 'SYSTEM'
  from org_company c;

alter table csh_receipt add column certificate_no varchar(40);
alter table csh_receipt add column certificate_date date;
create unique index uq_csh_receipt_certificate on csh_receipt (certificate_no)
    where certificate_no is not null;

alter table csh_print_batch add column copy_label varchar(10) not null default 'CLIENT'
    check (copy_label in ('CLIENT', 'COMPANY', 'BOTH'));
alter table csh_print_batch add column zip_file_id bigint references stored_file (id);
alter table csh_print_batch add column skipped_count integer not null default 0;

alter table csh_print_line drop constraint if exists csh_print_line_status_check;
alter table csh_print_line add constraint csh_print_line_status_check
    check (status in ('PRINTED', 'FAILED', 'SKIPPED'));
alter table csh_print_line add column reprint boolean not null default false;
alter table csh_print_line add column certificate_no varchar(40);

alter table csh_certificate_of_payment add column series_no varchar(40);

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('CASH_FORM_FOR_APPROVAL', 'Receipt form for approval', 'CASHIERING',
     'A change of the AR or OR form waits for the approval of another authorised user', true, false, 93)
on conflict (code) do nothing;
