-- =====================================================================================
-- Cashiering: the commission and incentive ORs of an insurer settlement issued once
-- Disbursement approves the payment request (FRS.CSH.07.01.01; Appendix R, C12).
--   csh_settlement_or     the OR requests kept until Disbursement approves
--   sys_parameter         CASH_SETTLEMENT_OR_TRIGGER (DISBURSEMENT_APPROVAL, REMITTANCE_APPROVAL)
-- =====================================================================================

create table csh_settlement_or (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    source_module      varchar(30)    not null,
    source_ref         varchar(80)    not null,
    await_ref          varchar(80)    not null,
    or_type            varchar(30)    not null,
    payee_code         varchar(40),
    payee_name         varchar(200),
    currency           varchar(3)     not null,
    amount             numeric(18, 2) not null,
    request_json       text           not null,
    status             varchar(15)    not null
        check (status in ('PENDING', 'ISSUED', 'CANCELLED', 'FAILED')),
    receipt_no         varchar(40),
    message            varchar(500),
    issued_at          timestamp with time zone,
    created_at         timestamp with time zone not null default now(),
    created_by         varchar(100),
    updated_at         timestamp with time zone,
    updated_by         varchar(100),
    constraint uq_csh_settlement_or unique (source_module, source_ref)
);

create index ix_csh_settlement_or_await on csh_settlement_or (company_id, source_module, await_ref);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('CASH_SETTLEMENT_OR_TRIGGER', 'DISBURSEMENT_APPROVAL', 'STRING', 'OPERATIONS',
     'When the commission and incentive ORs of an insurer settlement are issued: DISBURSEMENT_APPROVAL = once Disbursement approves the payment request, REMITTANCE_APPROVAL = at the approval of the remittance batch (Appendix R, C12)',
     null, null, now(), 'SYSTEM');
