-- =====================================================================================
-- iNXT BrokerVerse - V27 Attachments: document type, links to several records.
--   BRNB.026/055 document type (list DOCUMENT_TYPE), multi-file upload, inherited or
--                 nominated file names (<REFERENCE>_<DOCTYPE>_<n>.<ext>), one file linked
--                 to several accounts;
--   BRNB.056      several documents downloaded as one ZIP.
-- A link row makes an uploaded file part of another record's documents without copying it:
-- the file, its checksum and its audit trail stay unique.
-- =====================================================================================
alter table doc_attachment add column document_type varchar(40);
create index ix_attachment_document_type on doc_attachment (entity_type, entity_id, document_type);

create table doc_attachment_link (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    attachment_id bigint       not null references doc_attachment (id),
    entity_type   varchar(60)  not null,
    entity_id     varchar(60)  not null,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_attachment_link unique (attachment_id, entity_type, entity_id)
);
create index ix_attachment_link_entity on doc_attachment_link (entity_type, entity_id);
