-- Renewal dashboards and the Annual Renewal Budget (BDOI Renewal FRS v1.1, FRRN.002.02, FRRN.003,
-- FRRN.042): the renewal budget by fiscal year, segment and hierarchy with its monthly new, renewal
-- and organic amounts and its history; the processing assignment of the placement processor; the
-- parameters of the dashboards; the functions of the budget, KYC, RMU, audit log and billing
-- screens of the Renewal module and their grants.

-- ---------- Annual Renewal Budget (FRRN.042.02) ----------------------------------------------------
create table rnw_budget (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    fiscal_year     integer       not null check (fiscal_year between 2000 and 2100),
    measure         varchar(20)   not null default 'PREMIUM',
    segment         varchar(40)   not null,
    region          varchar(40),
    team            varchar(40),
    sub_team        varchar(40),
    unit_head       varchar(50),
    section_head    varchar(50),
    team_head       varchar(50),
    team_lead       varchar(50),
    account_officer varchar(50),
    natural_key     varchar(400)  not null,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_rnw_budget_measure check (measure in ('PREMIUM', 'COMMISSION')),
    constraint uq_rnw_budget_key unique (company_id, natural_key)
);
create index ix_rnw_budget_year on rnw_budget (company_id, fiscal_year, segment);

create table rnw_budget_month (
    budget_id      bigint         not null references rnw_budget (id),
    month_no       integer        not null check (month_no between 1 and 12),
    new_amount     numeric(19, 2) not null default 0 check (new_amount >= 0),
    renewal_amount numeric(19, 2) not null default 0 check (renewal_amount >= 0),
    organic_amount numeric(19, 2) not null default 0 check (organic_amount >= 0),
    primary key (budget_id, month_no)
);

-- Insert-only history of the budget amounts (FRRN.042.06).
create table rnw_budget_history (
    id          bigint generated by default as identity primary key,
    budget_id   bigint         not null references rnw_budget (id),
    field       varchar(60)    not null,
    previous    numeric(19, 2),
    updated     numeric(19, 2),
    modified_by varchar(50)    not null,
    modified_at timestamptz    not null
);
create index ix_rnw_budget_history on rnw_budget_history (budget_id, id);

-- ---------- Placement processor of an account (FRRN.003.02.01) --------------------------------------
-- New Business and renewal accounts in the processing dashboard: the Placement Processor assigned to
-- an account submitted for placement (Assigned and Unassigned tabs).
create table rnw_processing_assignment (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    company_id  bigint       not null references org_company (id),
    arn         varchar(40)  not null,
    processor   varchar(50)  not null,
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_rnw_processing_assignment unique (company_id, arn)
);

-- Placement and policy tracking of an account (FRRN.003.02.03/.04, FRRN.29.05, FRRN.033.04): the
-- policy status, the placement issue and its resolution date, and the transmittal of the policy to
-- the client with the reason of an unsuccessful sending.
create table rnw_placement_tracking (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    company_id          bigint        not null references org_company (id),
    arn                 varchar(40)   not null,
    policy_status       varchar(20),
    with_issue          boolean       not null default false,
    placement_issue     varchar(500),
    resolution_date     date,
    transmittal_status  varchar(20),
    transmittal_reason  varchar(500),
    transmitted_at      timestamptz,
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_rnw_placement_tracking unique (company_id, arn),
    constraint ck_rnw_placement_tracking_policy check (policy_status is null
        or policy_status in ('PENDING', 'RECEIVED', 'SPOILED', 'CANCELED', 'WITH_ISSUE')),
    constraint ck_rnw_placement_tracking_transmittal check (transmittal_status is null
        or transmittal_status in ('SENT', 'PENDING', 'UNSUCCESSFUL'))
);

-- ---------- Functions (permission action classes) ---------------------------------------------------
insert into sec_permission_action (permission, area, action)
values ('RNW_BUDGET', 'RENEWAL', 'AMEND'),
       ('RNW_KYC', 'RENEWAL', 'AMEND'),
       ('RNW_RMU_MAINTAIN', 'RENEWAL', 'AMEND'),
       ('RNW_AUDIT_VIEW', 'RENEWAL', 'VIEW'),
       ('RNW_BILLING', 'RENEWAL', 'CREATE')
on conflict do nothing;

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values
    ('BUSINESS_ADMIN', 'RNW_BUDGET'), ('BUSINESS_ADMIN', 'RNW_RMU_MAINTAIN'),
    ('BUSINESS_ADMIN', 'RNW_AUDIT_VIEW'),
    ('MKT_TL', 'RNW_KYC'), ('MKT_AO', 'RNW_KYC'), ('MKT_TL', 'RNW_AUDIT_VIEW'),
    ('PROCESSING_TL', 'RNW_BILLING'), ('PROCESSOR', 'RNW_BILLING'), ('PROCESSOR', 'RNW_EXPORT'),
    ('PROCESSING_TL', 'RNW_AUDIT_VIEW'), ('AUDITOR', 'RNW_AUDIT_VIEW')
) as g(role_code, permission) on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);

-- ---------- Parameters of the dashboards (Annex AC) -------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_PIPELINE_STAGES',
     'FOR_SURVEY:EXTRACTED|EVALUATING|UNASSIGNED|TRANSFER_PENDING|FOR_DISPOSITION;'
     || 'FOR_PROPOSAL:FOR_TL_REVIEW|NB_PATH|FOR_PROCESSING|IN_PROCESSING|WITH_INSURER;'
     || 'FOR_CONFIRM:RA_READY|RA_GENERATED|RA_SENT|ACCEPTED;FOR_BOOKING:FOR_PLACEMENT_BOOKING;FOR_DELIVERY:RENEWED',
     'STRING', 'RENEWAL',
     'Pipeline Summary: the renewal statuses counted in each stage (For Survey, For Proposal, For Confirm, For Booking, For Delivery)',
     null, null, now(), 'SYSTEM'),
    ('RNW_PIPELINE_NB_STAGES',
     'FOR_SURVEY:DRAFT|RETURNED_TO_MARKETING;FOR_PROPOSAL:SUBMITTED;FOR_CONFIRM:AWAITING_PAYMENT;'
     || 'FOR_BOOKING:READY_FOR_PLACEMENT|PLACED|RETURNED_BY_INSURER|POLICY_ISSUED;FOR_DELIVERY:BOOKED',
     'STRING', 'RENEWAL',
     'Pipeline Summary: the New Business account statuses counted in each stage',
     null, null, now(), 'SYSTEM'),
    ('RNW_STATUS_NAMES', 'CLIENT', 'STRING', 'RENEWAL',
     'Names of the renewal statuses on the dashboards and lists: CLIENT (In Process Renewal, Submitted for Posting, Posted ...) or SYSTEM (the workflow stage names)',
     null, null, now(), 'SYSTEM'),
    ('RNW_TOP_DEALS_OPTIONS', '50,75,100', 'INTEGER_LIST', 'RENEWAL',
     'Biggest Open Deals: the sizes of the ranking a user can choose', null, null, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_EXPIRING_DAYS', '7', 'INTEGER', 'RENEWAL',
     'KPI card Expiring Hold Cover: confirmed hold covers ending within this number of days', 1, 90, now(), 'SYSTEM'),
    ('RNW_PLACEMENT_TAT_PACKAGED_DAYS', '3', 'INTEGER', 'RENEWAL',
     'Placement turnaround time of packaged accounts in business days', 1, 60, now(), 'SYSTEM'),
    ('RNW_PLACEMENT_TAT_NON_PACKAGE_DAYS', '10', 'INTEGER', 'RENEWAL',
     'Placement turnaround time of non-package accounts in business days', 1, 60, now(), 'SYSTEM'),
    ('RNW_PLACEMENT_CUTOFF_HOUR', '15', 'INTEGER', 'RENEWAL',
     'Placements sent at or after this hour (24-hour clock) count from the next business day', 0, 23, now(), 'SYSTEM'),
    ('RNW_CORPORATE_SEGMENTS', 'CORBANK,COMBANK', 'CODE_LIST', 'RENEWAL',
     'Market segments budgeted by team and sub-team (Corporate); the others are budgeted by region', null, null, now(), 'SYSTEM'),
    ('RNW_KYC_UPCOMING_DAYS', '60', 'INTEGER', 'RENEWAL',
     'KYC monitoring: a client whose KYC review falls within this number of days is KYC Upcoming', 1, 365, now(), 'SYSTEM')
on conflict (param_key) do nothing;
