-- Insurer dispositions of BDOI's Renewal FRS (FRRN.013.02): the nine values of the insurer's
-- approval in the insurer disposition file, each mapped to one of the three insurer responses of
-- the BRD and to BDOI's bucket and renewal disposition.

create table rnw_insurer_disposition_map (
    code          varchar(40)  primary key,
    label         varchar(120) not null,
    outcome       varchar(20)  not null,
    brd_response  varchar(20)  not null,
    bucket        varchar(20)  not null,
    disposition   varchar(30)  not null,
    sort_order    integer      not null,
    active        boolean      not null default true,
    constraint ck_rnw_insurer_disposition_outcome check (outcome in ('RENEW', 'REVIEW', 'NOT_RENEWED')),
    constraint ck_rnw_insurer_disposition_response check (brd_response in ('RENEW_AS_IS', 'REVISE', 'REJECT'))
);

insert into rnw_insurer_disposition_map (code, label, outcome, brd_response, bucket, disposition, sort_order) values
    ('RENEW_AS_IS', 'Renew As Is / Approved', 'RENEW', 'RENEW_AS_IS', 'CLEAN', 'FOR_RENEWAL', 10),
    ('REJECTED', 'Rejected', 'REVIEW', 'REJECT', 'REVIEW', 'FOR_DISPOSITION', 20),
    ('TOTAL_LOSS', 'Total Loss', 'NOT_RENEWED', 'REJECT', 'NON_RENEWABLE', 'NOT_FOR_RENEWAL', 30),
    ('RENEW_WITH_SURCHARGE', 'Renew with surcharge', 'REVIEW', 'REVISE', 'REVIEW', 'FOR_DISPOSITION', 40),
    ('RENEW_ANOTHER_PACKAGE', 'Renew under another package', 'REVIEW', 'REVISE', 'REVIEW', 'FOR_DISPOSITION', 50),
    ('NON_RENEWAL_LOSS_RATIO', 'Non-Renewal due to frequent loss/ high-loss ratio', 'REVIEW', 'REJECT', 'REVIEW', 'FOR_DISPOSITION', 60),
    ('NON_RENEWAL_OLD_UNIT', 'Non-Renewal due to old unit', 'REVIEW', 'REJECT', 'REVIEW', 'FOR_DISPOSITION', 70),
    ('NON_RENEWAL_NON_PAYMENT', 'Non-Renewal due to Non-Payment of Premium', 'REVIEW', 'REJECT', 'REVIEW', 'FOR_DISPOSITION', 80),
    ('APPLY_MINIMUM_PREMIUM', 'Apply minimum premium', 'REVIEW', 'REVISE', 'REVIEW', 'FOR_DISPOSITION', 90);

-- Each record of an insurer disposition file, matched to its renewal account.
create table rnw_insurer_disposition_line (
    id                bigint generated by default as identity primary key,
    company_id        bigint        not null references org_company (id),
    job_no            varchar(40)   not null,
    row_no            integer       not null,
    candidate_id      bigint        references rnw_candidate (id),
    disposition_code  varchar(40),
    insurer_code      varchar(40),
    insurer_branch    varchar(120),
    insurer_remarks   varchar(1000),
    matched_on        varchar(40),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null
);
create index ix_rnw_insurer_disposition_line_candidate on rnw_insurer_disposition_line (candidate_id);

insert into rnw_check_setting (check_code, active, severity, parameters, record_status, authorized_by,
    authorized_at, created_at, created_by)
values ('INSURER_DISPOSITION', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM')
on conflict (check_code) do nothing;
