-- Delivery channels and client letters of BDOI's Renewal FRS (FRRN.017.02, FRRN.022 to FRRN.024,
-- FRRN.032.02, FRRN.033.04, Annex M): the outbound messages to CCM (client documents) and MFT
-- (insurer files) with their delivery status history, the connection settings of each channel
-- (simulator for SIT and UAT until BDOI IT gives the connection details), the automatic Renewal
-- Advice notice, BDOI's file names, the password convention of protected files and the offsets of
-- the closing letters.

create table rnw_channel_message (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    message_no        varchar(30)   not null,
    channel           varchar(10)   not null,
    direction         varchar(10)   not null,
    doc_kind          varchar(30)   not null,
    doc_ref           varchar(60),
    candidate_id      bigint        references rnw_candidate (id),
    renewal_ref       varchar(30),
    file_name         varchar(255),
    attachment_id     bigint,
    recipients_to     varchar(1000),
    recipients_cc     varchar(1000),
    subject           varchar(300),
    body              text,
    client_id         bigint,
    status            varchar(30)   not null,
    external_ref      varchar(80),
    attempts          integer       not null default 0,
    last_error        varchar(1000),
    submitted_at      timestamptz,
    sent_at           timestamptz,
    delivered_at      timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_rnw_channel_message_no unique (company_id, message_no),
    constraint ck_rnw_channel_message_channel check (channel in ('CCM', 'MFT', 'EMAIL')),
    constraint ck_rnw_channel_message_direction check (direction in ('OUTBOUND', 'INBOUND')),
    constraint ck_rnw_channel_message_status check (status in ('PENDING_TRANSMISSION', 'SUBMITTED',
        'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', 'RECEIVED', 'PROCESSED'))
);
create index ix_rnw_channel_message_candidate on rnw_channel_message (candidate_id);
create index ix_rnw_channel_message_status on rnw_channel_message (company_id, channel, status);

create table rnw_channel_event (
    id                bigint generated by default as identity primary key,
    message_id        bigint        not null references rnw_channel_message (id),
    status            varchar(30)   not null,
    detail            varchar(1000),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null
);
create index ix_rnw_channel_event_message on rnw_channel_event (message_id);

insert into sec_permission_action (permission, area, action)
values ('RNW_CHANNEL_MONITOR', 'RENEWAL', 'VIEW'),
       ('RNW_CHANNEL_SETUP', 'RENEWAL', 'AMEND')
on conflict do nothing;

insert into sec_role_permission (role_id, permission)
select r.id, g.permission
from sec_role r
join (values
    ('BUSINESS_ADMIN', 'RNW_CHANNEL_MONITOR'), ('BUSINESS_ADMIN', 'RNW_CHANNEL_SETUP'),
    ('SYSADMIN', 'RNW_CHANNEL_MONITOR'), ('SYSADMIN', 'RNW_CHANNEL_SETUP'),
    ('PROCESSING_TL', 'RNW_CHANNEL_MONITOR'), ('PROCESSOR', 'RNW_CHANNEL_MONITOR'),
    ('MKT_TL', 'RNW_CHANNEL_MONITOR')
) as g(role_code, permission) on g.role_code = r.code
where not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = g.permission);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_DELIVERY_CHANNEL', 'CCM', 'STRING', 'RENEWAL',
     'Channel of the client documents (Renewal Advice, letters, proposals, Insurance Advice, e-policies): CCM, or EMAIL (protected e-mail with the password in a separate e-mail)',
     null, null, now(), 'SYSTEM'),
    ('RNW_CCM_MODE', 'SIMULATOR', 'STRING', 'RENEWAL',
     'Connection of CCM: LIVE (the CCM interface at the endpoint below) or SIMULATOR (the CCM simulator of SIT and UAT)',
     null, null, now(), 'SYSTEM'),
    ('RNW_CCM_ENDPOINT', '', 'STRING', 'RENEWAL',
     'Address of the CCM interface (given by the IT team of the bank)', null, null, now(), 'SYSTEM'),
    ('RNW_CCM_CLIENT_ID', '', 'STRING', 'RENEWAL',
     'Client identifier of the application at CCM', null, null, now(), 'SYSTEM'),
    ('RNW_CCM_KEY_SETTING', 'BROKERVERSE_CCM_API_KEY', 'STRING', 'RENEWAL',
     'Name of the environment setting that holds the CCM access key (never stored in the database)',
     null, null, now(), 'SYSTEM'),
    ('RNW_CCM_TIMEOUT_SECONDS', '30', 'INTEGER', 'RENEWAL', 'Time limit of a CCM call in seconds',
     5, 300, now(), 'SYSTEM'),
    ('RNW_CHANNEL_MAX_ATTEMPTS', '3', 'INTEGER', 'RENEWAL',
     'Attempts of the transmission of a message before it is Failed', 1, 10, now(), 'SYSTEM'),
    ('RNW_MFT_MODE', 'SIMULATOR', 'STRING', 'RENEWAL',
     'Connection of MFT: LIVE (the MFT server below) or SIMULATOR (the MFT simulator of SIT and UAT)',
     null, null, now(), 'SYSTEM'),
    ('RNW_MFT_ENDPOINT', '', 'STRING', 'RENEWAL',
     'Address of the MFT server (given by the IT team of the bank)', null, null, now(), 'SYSTEM'),
    ('RNW_MFT_OUTBOUND_FOLDER', '/outbound', 'STRING', 'RENEWAL',
     'Folder of the files sent to the insurers on MFT', null, null, now(), 'SYSTEM'),
    ('RNW_MFT_INBOUND_FOLDER', '/inbound', 'STRING', 'RENEWAL',
     'Folder of the files received from the insurers on MFT', null, null, now(), 'SYSTEM'),
    ('RNW_MFT_KEY_SETTING', 'BROKERVERSE_MFT_KEY', 'STRING', 'RENEWAL',
     'Name of the environment setting that holds the MFT access key (never stored in the database)',
     null, null, now(), 'SYSTEM'),
    ('RNW_CHANNEL_SIMULATOR_OUTAGE', '', 'CODE_LIST', 'RENEWAL',
     'Channels the simulator reports unavailable (CCM, MFT), to test an outage in SIT and UAT',
     null, null, now(), 'SYSTEM'),
    ('RNW_RA_NOTICE_MODE', 'AUTOMATIC', 'STRING', 'RENEWAL',
     'Renewal Advice notice: AUTOMATIC (First Notice from 75 days, Last Notice from 45 days before expiry) or MANUAL (the user chooses)',
     null, null, now(), 'SYSTEM'),
    ('RNW_RA_FIRST_NOTICE_DAYS', '75', 'INTEGER', 'RENEWAL',
     'Days before expiry of the Renewal Advice First Notice', 1, 365, now(), 'SYSTEM'),
    ('RNW_RA_LAST_NOTICE_DAYS', '45', 'INTEGER', 'RENEWAL',
     'Days before expiry of the Renewal Advice Last Notice', 1, 365, now(), 'SYSTEM'),
    ('RNW_FILE_NAMES', 'CLIENT', 'STRING', 'RENEWAL',
     'Names of the generated files: CLIENT (<Product>_RA_<Notice>_<Reference>_MMDDYYYY.pdf, <Product>_<Letter>_<Reference>_MMDDYYYY.pdf) or SYSTEM (the letter number)',
     null, null, now(), 'SYSTEM'),
    ('RNW_PASSWORD_CONVENTION', 'CLIENT', 'STRING', 'RENEWAL',
     'Password of protected files: CLIENT (individual: first three letters of the first and last names in capitals; corporate: eight random characters) or GENERATED (a random password per file)',
     null, null, now(), 'SYSTEM'),
    ('RNW_NAL_OFFSET_DAYS', '1', 'INTEGER', 'RENEWAL',
     'Days after the effective expiry date of the No Advice Letter', 0, 30, now(), 'SYSTEM'),
    ('RNW_NRL_OFFSET_DAYS_CBG', '1', 'INTEGER', 'RENEWAL',
     'Days after the effective expiry date of the Non-Renewal Letter of a CBG Motor account', 0, 30, now(), 'SYSTEM'),
    ('RNW_NRL_OFFSET_DAYS_NON_CBG', '3', 'INTEGER', 'RENEWAL',
     'Days after the effective expiry date of the Non-Renewal Letter of a Non-CBG account', 0, 30, now(), 'SYSTEM')
on conflict (param_key) do nothing;
