-- LAMD, BDOFC and BDOSOLD uploads and the RMU Account Officer list of BDOI's Renewal FRS
-- (FRRN.012, FRRN.041.01): the details of each loan of the CBG loans and paid-off lists with the
-- loan status derived from it, the cumulative repository of paid-off accounts, the BDOFC and
-- BDOSOLD lines matched on the PN, and the Account Officer codes of the Remedial Management Unit.

create table rnw_lamd_loan (
    id                bigint generated by default as identity primary key,
    company_id        bigint        not null references org_company (id),
    job_no            varchar(40)   not null,
    row_no            integer       not null,
    report_kind       varchar(20)   not null,
    pn_no             varchar(40)   not null,
    ibg_cbg_tag       varchar(20),
    book_date         date,
    maturity_date     date,
    branch            varchar(200),
    product_type      varchar(200),
    ao_code           varchar(40),
    ao_name           varchar(200),
    email             varchar(200),
    mailing_address   varchar(500),
    serial_no         varchar(60),
    motor_no          varchar(60),
    short_name        varchar(250),
    loan_status       varchar(20)   not null,
    candidate_id      bigint        references rnw_candidate (id),
    matching_status   varchar(20)   not null,
    processing_status varchar(20)   not null,
    reason            varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    constraint ck_rnw_lamd_loan_kind check (report_kind in ('CBG_LOANS', 'PAID_OFF')),
    constraint ck_rnw_lamd_loan_status check (loan_status in ('ACTIVE', 'LOAN_FULLY_PAID', 'RMU',
        'UNMATCHED')),
    constraint ck_rnw_lamd_loan_match check (matching_status in ('MATCHED', 'UNMATCHED')),
    constraint ck_rnw_lamd_loan_processing check (processing_status in ('SUCCESS', 'FAILED'))
);
create index ix_rnw_lamd_loan_job on rnw_lamd_loan (job_no);
create index ix_rnw_lamd_loan_candidate on rnw_lamd_loan (candidate_id);

create table rnw_paid_off_account (
    id                bigint generated by default as identity primary key,
    company_id        bigint        not null references org_company (id),
    pn_no             varchar(40)   not null,
    serial_no         varchar(60),
    motor_no          varchar(60),
    ibg_cbg_tag       varchar(20),
    product_type      varchar(200),
    email             varchar(200),
    mailing_address   varchar(500),
    first_job_no      varchar(40)   not null,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null
);
create unique index uq_rnw_paid_off_account on rnw_paid_off_account
    (company_id, pn_no, coalesce(serial_no, ''), coalesce(motor_no, ''));

create table rnw_bdofc_line (
    id                bigint generated by default as identity primary key,
    company_id        bigint        not null references org_company (id),
    job_no            varchar(40)   not null,
    row_no            integer       not null,
    report_kind       varchar(20)   not null,
    location          varchar(200),
    pn_no             varchar(40)   not null,
    assured_name      varchar(250)  not null,
    inception_date    date,
    expiry_date       date,
    remarks           varchar(1000) not null,
    candidate_id      bigint        references rnw_candidate (id),
    matching_status   varchar(20)   not null,
    processing_status varchar(20)   not null,
    reason            varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    constraint ck_rnw_bdofc_line_kind check (report_kind in ('BDOFC', 'BDOSOLD')),
    constraint ck_rnw_bdofc_line_match check (matching_status in ('MATCHED', 'UNMATCHED')),
    constraint ck_rnw_bdofc_line_processing check (processing_status in ('SUCCESS', 'FAILED'))
);
create index ix_rnw_bdofc_line_job on rnw_bdofc_line (job_no);
create index ix_rnw_bdofc_line_candidate on rnw_bdofc_line (candidate_id);

create table rnw_rmu_officer (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    ao_code           varchar(40)   not null,
    ao_name           varchar(200)  not null,
    active            boolean       not null default true,
    remarks           varchar(500),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create unique index uq_rnw_rmu_officer_active on rnw_rmu_officer (company_id, ao_code) where active;

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_LAMD_MOTOR_PRODUCTS', 'AUTO,MOTOR,CAR', 'CODE_LIST', 'RENEWAL',
     'Words of the LAMD product description of a motor loan: its serial and motor numbers are required and matched',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

insert into rnw_check_setting (check_code, active, severity, parameters, record_status, authorized_by,
    authorized_at, created_at, created_by)
values ('BDOFC_SOLD', true, 'FAIL_REVIEW', null, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM')
on conflict (check_code) do nothing;
