-- Hold cover and insurer allocation of BDOI's Renewal FRS (FRRN.014.03, FRRN.036, FRRN.037): the
-- default durations by segment, the extensions, the automatic requests (Non-CBG after the client's
-- confirmation, CBG Clean accounts before expiry, the monthly CBG Home extension), the request per
-- insurer sent by MFT or e-mail and its response, and the allocation of a renewal to several
-- insurers by share or amount.

create table rnw_hold_cover_request (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    request_no        varchar(30)   not null,
    candidate_id      bigint        not null references rnw_candidate (id),
    kind              varchar(20)   not null,
    insurer_code      varchar(30)   not null,
    share_percent     numeric(9, 4),
    days              integer       not null,
    start_date        date          not null,
    end_date          date          not null,
    status            varchar(20)   not null,
    batch_no          varchar(40),
    channel           varchar(10),
    channel_message   varchar(30),
    insurer_ref       varchar(60),
    response_remarks  varchar(1000),
    responded_at      timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_rnw_hold_cover_request_no unique (company_id, request_no),
    constraint ck_rnw_hold_cover_request_kind check (kind in ('REQUEST', 'EXTENSION', 'CBG_BATCH',
        'MONTHLY_EXTENSION')),
    constraint ck_rnw_hold_cover_request_status check (status in ('REQUESTED', 'APPROVED', 'REJECTED',
        'CANCELLED')),
    constraint ck_rnw_hold_cover_request_days check (days > 0 and end_date >= start_date)
);
create index ix_rnw_hold_cover_request_candidate on rnw_hold_cover_request (candidate_id);

create table rnw_insurer_allocation (
    id                bigint generated by default as identity primary key,
    candidate_id      bigint        not null references rnw_candidate (id),
    insurer_code      varchar(30)   not null,
    share_percent     numeric(9, 4) not null,
    coverage_amount   numeric(19, 2),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    constraint uq_rnw_insurer_allocation unique (candidate_id, insurer_code),
    constraint ck_rnw_insurer_allocation_share check (share_percent > 0 and share_percent <= 100)
);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_HOLD_COVER_DAYS_NON_CBG', '30', 'INTEGER', 'RENEWAL',
     'Default duration of the hold cover of a Non-CBG renewal account, in days', 1, 365, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_DAYS_CBG', '90', 'INTEGER', 'RENEWAL',
     'Default duration of the hold cover of a CBG renewal account, in days', 1, 365, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_DAYS_CBG_HOME_TRANSFER', '30', 'INTEGER', 'RENEWAL',
     'Duration of the hold cover of a CBG Home account moved to another insurer after a rejection, in days',
     1, 365, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_DAYS_CBG_MOTOR_TRANSFER', '60', 'INTEGER', 'RENEWAL',
     'Duration of the hold cover of a CBG Motor account moved to another insurer after a rejection, in days',
     1, 365, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_EXTENSION_DAYS', '15,30', 'INTEGER_LIST', 'RENEWAL',
     'Durations offered for the extension of a hold cover, in days', null, null, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_EXTENSION_WINDOW', '7', 'INTEGER', 'RENEWAL',
     'Days before the end of a hold cover from which its extension can be requested', 1, 60, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_AUTO_NON_CBG', 'true', 'BOOLEAN', 'RENEWAL',
     'The hold cover of a Non-CBG renewal account is requested automatically once the client confirms the renewal, one request per insurer',
     null, null, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_CBG_DAYS_BEFORE', '75', 'INTEGER', 'RENEWAL',
     'Days before expiry at which the hold cover of the Clean CBG renewal accounts is requested, one file per insurer',
     1, 365, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_CBG_HOME_EXTENSION_DAY', '15', 'INTEGER', 'RENEWAL',
     'Day of the month on which the expired and unbooked CBG Home accounts receive a hold cover extension',
     1, 28, now(), 'SYSTEM'),
    ('RNW_HOLD_COVER_CBG_HOME_EXTENSION', '30', 'INTEGER', 'RENEWAL',
     'Days of the monthly hold cover extension of the CBG Home accounts', 1, 365, now(), 'SYSTEM'),
    ('RNW_MFT_ENROLLED_INSURERS', '', 'CODE_LIST', 'RENEWAL',
     'Insurers enrolled in MFT: their hold cover requests, placement files and e-policies go through MFT, the others by e-mail',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
