-- Renewal assignment, transfer referrals and submission for posting of BDOI's Renewal FRS
-- (FRRN.010.01, FRRN.011, FRRN.016.01): automatic assignment per market segment and for
-- Processing (round robin and workload balancing), the referral of a renewal account to another
-- Marketing unit as a New Business opportunity (the renewal keeps its owner), and the approver
-- chosen when an account is submitted for posting.

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_AUTO_ASSIGN_SEGMENTS', '', 'CODE_LIST', 'RENEWAL',
     'Market segments whose renewal accounts are assigned automatically to an Account Officer of the team after the classification (* for every segment; none: the Team Leader assigns)',
     null, null, now(), 'SYSTEM'),
    ('RNW_AUTO_ASSIGN_PROCESSING', 'false', 'BOOLEAN', 'RENEWAL',
     'Renewal accounts routed to Processing are assigned automatically to a Processing Officer (fewest open accounts first, then in turn)',
     null, null, now(), 'SYSTEM'),
    ('RNW_TRANSFER_MODE', 'BOTH', 'STRING', 'RENEWAL',
     'Transfer to another Marketing unit: TRANSFER (the renewal account moves to the unit), REFERRAL (the unit opens a New Business account, the renewal keeps its owner) or BOTH',
     null, null, now(), 'SYSTEM'),
    ('RNW_POSTING_APPROVER', 'OPTIONAL', 'STRING', 'RENEWAL',
     'Approver of a submission for posting: REQUIRED (the officer picks the approver), OPTIONAL (the officer may pick one, else every Team Leader of the unit) or NONE',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

create table rnw_referral (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        not null references org_company (id),
    referral_no       varchar(30)   not null,
    candidate_id      bigint        not null references rnw_candidate (id),
    from_unit         varchar(20),
    to_unit           varchar(20)   not null,
    justification     varchar(1000) not null,
    status            varchar(30)   not null,
    decided_by        varchar(50),
    decided_at        timestamptz,
    decision_remarks  varchar(1000),
    nb_arn            varchar(30),
    nb_created_by     varchar(50),
    nb_created_at     timestamptz,
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_rnw_referral_no unique (company_id, referral_no),
    constraint ck_rnw_referral_status check (status in ('DRAFT', 'PENDING_ACCEPTANCE', 'ACCEPTED',
        'REJECTED', 'RETURNED', 'CANCELLED')),
    constraint ck_rnw_referral_units check (from_unit is null or from_unit <> to_unit)
);
create index ix_rnw_referral_candidate on rnw_referral (candidate_id);
create index ix_rnw_referral_to on rnw_referral (company_id, to_unit, status);

-- The approver chosen at the submission for posting (Submitted for Posting).
alter table rnw_candidate add column posting_approver varchar(50);
