-- The client's answer, the second approval, the For Booking Only and Direct-to-Insurer Payment tags
-- and the CLPC billing files of BDOI's Renewal FRS (FRRN.014.02, FRRN.014.04, FRRN.014.05,
-- FRRN.019.01, FRRN.025.01, FRRN.26.01, FRRN.027, FRRN.028).

alter table rnw_candidate add column client_status varchar(20);
alter table rnw_candidate add column client_status_remarks varchar(1000);
alter table rnw_candidate add column client_status_at timestamptz;
alter table rnw_candidate add column client_status_by varchar(50);
alter table rnw_candidate add column approval_status varchar(20);
alter table rnw_candidate add column approval_by varchar(50);
alter table rnw_candidate add column approval_at timestamptz;
alter table rnw_candidate add column approval_remarks varchar(1000);
alter table rnw_candidate add column payment_confirmation varchar(40);
alter table rnw_candidate add column booking_only_policy_no varchar(60);
alter table rnw_candidate add column booking_only_or_no varchar(40);
alter table rnw_candidate add column booking_only_override varchar(20);
alter table rnw_candidate add column booking_only_override_by varchar(50);
alter table rnw_candidate add column booking_only_override_reason varchar(1000);
alter table rnw_candidate add column dti_option varchar(20);
alter table rnw_candidate add column dti_status varchar(20);
alter table rnw_candidate add column dti_decided_by varchar(50);
alter table rnw_candidate add column dti_reason varchar(1000);
alter table rnw_candidate add column amortized boolean not null default false;
alter table rnw_candidate add column billing_file_id bigint;
alter table rnw_candidate add column lock_at_placement boolean not null default false;
alter table rnw_candidate add constraint ck_rnw_candidate_client_status
    check (client_status is null or client_status in ('PENDING', 'ACCEPTED', 'REJECTED', 'REVISION',
        'NOT_APPLICABLE'));
alter table rnw_candidate add constraint ck_rnw_candidate_approval_status
    check (approval_status is null or approval_status in ('SUBMITTED', 'APPROVED', 'RETURNED'));
alter table rnw_candidate add constraint ck_rnw_candidate_booking_override
    check (booking_only_override is null or booking_only_override in ('REQUESTED', 'APPROVED',
        'REJECTED'));
alter table rnw_candidate add constraint ck_rnw_candidate_dti
    check ((dti_option is null or dti_option in ('BLANKET', 'UNIT_HEAD'))
        and (dti_status is null or dti_status in ('PENDING', 'APPROVED', 'REJECTED')));

create table rnw_billing_file (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    file_name            varchar(200)  not null,
    line_code            varchar(30),
    built_in             boolean       not null,
    run_kind             varchar(20)   not null,
    from_date            date,
    to_date              date,
    accounts             integer       not null,
    attachment_id        bigint,
    delivery_status      varchar(20),
    message_no           varchar(30),
    delivery_error       varchar(1000),
    lms_status           varchar(20),
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_rnw_billing_file_kind check (run_kind in ('CBG_HOME', 'FFY', 'MANUAL'))
);
create index ix_rnw_billing_file_company on rnw_billing_file (company_id, created_at);

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'RNW_NONRENEWAL_REASON', v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE',
       'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('ONE_TIME_POLICY', 'One time policy/event', 120),
    ('PROJECT_COMPLETED', 'Project completed', 130),
    ('INVOICE_FOR_CANCELLATION', 'Invoice for cancellation', 140),
    ('EGRESS', 'Egress', 150),
    ('EXPAT_RETURNING', 'Expat returning to home country', 160),
    ('BUSINESS_CLOSED', 'Business/ Store closed', 170),
    ('ENDORSEMENT_ONLY', 'Endorsement Only', 180),
    ('TIME_ON_RISK', 'Time on risk', 190),
    ('SHORT_PERIOD_ONLY', 'Short period only', 200),
    ('PROPERTIES_RETURNED', 'Properties returned to the originating Unit', 210),
    ('NO_RMU_INSTRUCTION', 'No renewal instruction from RMU UH and Team', 220),
    ('LOST_BUSINESS', 'Lost Business', 230)
) as v(code, label, sort_order)
on conflict (type_code, code) do nothing;

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_SECOND_APPROVAL', 'false', 'BOOLEAN', 'RENEWAL',
     'An accepted renewal account is Submitted for Approval and goes to placement only once an approver approves it (true), or goes to the payment gate and placement at once (false)',
     null, null, now(), 'SYSTEM'),
    ('RNW_LOCK_POINT', 'RA_GENERATION', 'STRING', 'RENEWAL',
     'When Marketing can no longer change a renewal account: RA_GENERATION (when the Renewal Advice is generated) or PLACEMENT (once posted and the placement is sent)',
     null, null, now(), 'SYSTEM'),
    ('RNW_DISPOSITION_SET', 'SYSTEM', 'STRING', 'RENEWAL',
     'Dispositions offered to Marketing: SYSTEM (For Renewal, Not for Renewal, For Quotation, For Proposal, Lost Business) or CLIENT (the first four, Lost Business being a reason of Not for Renewal)',
     null, null, now(), 'SYSTEM'),
    ('RNW_CLPC_BILLING_DAYS_BEFORE', '10', 'INTEGER', 'RENEWAL',
     'Days before expiry at which the daily billing job puts a CBG Home account For Billing Generation in the CLPC billing file',
     0, 120, now(), 'SYSTEM'),
    ('RNW_CLPC_FFY_DAYS', '10,25', 'CODE_LIST', 'RENEWAL',
     'Days of the month on which the billing job puts the FFY Motor accounts For Billing Generation in the CLPC billing file',
     null, null, now(), 'SYSTEM'),
    ('RNW_CLPC_BILLING_RECIPIENTS', '', 'STRING', 'RENEWAL',
     'Recipients of the CLPC billing files, separated by commas',
     null, null, now(), 'SYSTEM'),
    ('RNW_LMS_MODE', 'SIMULATOR', 'STRING', 'RENEWAL',
     'Upload of the billing files to the shared LMS directory: LIVE (the directory of the LMS interface), SIMULATOR (test environments) or OFF',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
