-- Placement, Insurance Advice and e-policies of the renewal accounts (FRRN.029 to FRRN.033): the
-- placement slip per insurer and the consolidated placement file per insurer, their sending by MFT
-- or CCM, the placement turnaround time with the With Issue tag, the insurer's placement response,
-- the return to Marketing with its reasons, the versioned Insurance Advice of mortgaged accounts,
-- the e-policy files received by upload or MFT, their sending and the e-policy number upload.

alter table rnw_candidate add column placement_status varchar(30);
alter table rnw_candidate add column for_booking_only boolean not null default false;
alter table rnw_candidate add column epolicy_no varchar(60);
alter table rnw_candidate add column epolicy_batch varchar(40);
alter table rnw_candidate add column epolicy_updated_at timestamptz;
alter table rnw_candidate add column epolicy_updated_by varchar(50);
alter table rnw_candidate add constraint ck_rnw_candidate_placement_status
    check (placement_status is null or placement_status in ('FOR_BOOKING', 'REJECTED_PLACEMENT',
        'BOOKED', 'FOR_EPOLICY_SENDING', 'EPOLICY_SENT'));
create index ix_rnw_candidate_epolicy_no on rnw_candidate (company_id, epolicy_no);

create table rnw_placement_file (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    insurer_code         varchar(30)   not null,
    line_code            varchar(30),
    file_name            varchar(200)  not null,
    attachment_id        bigint,
    accounts             integer       not null,
    channel              varchar(10),
    message_no           varchar(30),
    transmission_status  varchar(30),
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50)
);
create index ix_rnw_placement_file_insurer on rnw_placement_file (company_id, insurer_code);

create table rnw_placement (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    candidate_id         bigint        not null references rnw_candidate (id),
    insurer_code         varchar(30)   not null,
    share_percent        numeric(9, 4) not null,
    premium              numeric(19, 2),
    sum_insured          numeric(19, 2),
    slip_file_name       varchar(200)  not null,
    slip_attachment_id   bigint,
    placement_file_id    bigint references rnw_placement_file (id),
    status               varchar(20)   not null,
    channel              varchar(10),
    message_no           varchar(30),
    transmission_status  varchar(30),
    recipients           varchar(1000),
    cc                   varchar(1000),
    submitted_at         timestamptz,
    tat_start            date,
    sla_days             integer,
    with_issue           boolean       not null default false,
    resolution_date      date,
    response             varchar(20),
    response_date        date,
    response_reason      varchar(60),
    response_remarks     varchar(1000),
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_rnw_placement_status check (status in ('GENERATED', 'SENT', 'APPROVED', 'REJECTED',
        'CANCELLED')),
    constraint ck_rnw_placement_response check (response is null or response in ('APPROVED',
        'REJECTED'))
);
create index ix_rnw_placement_candidate on rnw_placement (candidate_id);

create table rnw_insurance_advice (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    candidate_id         bigint        not null references rnw_candidate (id),
    version_no           integer       not null,
    file_name            varchar(200)  not null,
    attachment_id        bigint,
    fingerprint          varchar(64)   not null,
    trigger_event        varchar(30)   not null,
    message_no           varchar(30),
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_rnw_insurance_advice_version unique (candidate_id, version_no)
);

create table rnw_epolicy_receipt (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    receipt_no           varchar(30)   not null,
    receipt_type         varchar(10)   not null,
    summary_file         varchar(200),
    zip_file             varchar(200),
    status               varchar(20)   not null,
    remarks              varchar(1000),
    records              integer       not null default 0,
    matched              integer       not null default 0,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_rnw_epolicy_receipt_no unique (company_id, receipt_no),
    constraint ck_rnw_epolicy_receipt_type check (receipt_type in ('UPLOAD', 'MFT')),
    constraint ck_rnw_epolicy_receipt_status check (status in ('SUCCESSFUL', 'FAILED'))
);

create table rnw_epolicy_line (
    id                   bigint generated by default as identity primary key,
    receipt_id           bigint        not null references rnw_epolicy_receipt (id),
    seq_no               integer,
    renewal_ref          varchar(40),
    policy_no            varchar(60),
    pdf_file             varchar(200),
    document_tag         varchar(60),
    match_status         varchar(10)   not null,
    remarks              varchar(500),
    candidate_id         bigint references rnw_candidate (id),
    attachment_id        bigint,
    constraint ck_rnw_epolicy_line_match check (match_status in ('MATCHED', 'UNMATCHED'))
);
create index ix_rnw_epolicy_line_receipt on rnw_epolicy_line (receipt_id);

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('RNW_PLACEMENT_REJECT_REASON', 'Placement rejection reason',
        'Why the insurer rejected the placement of a renewal account', true, now(), 'SYSTEM'),
       ('RNW_PLACEMENT_RETURN_REASON', 'Return reason of a placement',
        'Why a renewal account submitted for placement is returned to Marketing', true, now(), 'SYSTEM')
on conflict (code) do nothing;

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM',
       now(), now(), 'SYSTEM'
from (values
    ('RNW_PLACEMENT_REJECT_REASON', 'CLAIMS_LOSSES', 'Claims/Losses', 10),
    ('RNW_PLACEMENT_REJECT_REASON', 'DUPLICATE_REQUEST', 'Duplicate request for policy issuance', 20),
    ('RNW_PLACEMENT_REJECT_REASON', 'OUTSTANDING_PREMIUM', 'Outstanding Premium', 30),
    ('RNW_PLACEMENT_REJECT_REASON', 'OTHER_INTERMEDIARY', 'With Existing Cover under Another Intermediary', 40),
    ('RNW_PLACEMENT_REJECT_REASON', 'CLIENT_INITIATED', 'Client Initiated, will not push through', 50),
    ('RNW_PLACEMENT_REJECT_REASON', 'SPOILAGE', 'Spoilage request', 60),
    ('RNW_PLACEMENT_REJECT_REASON', 'RISK_NOT_ACCEPTED', 'Insurer''s non-acceptance of the risk', 70),
    ('DOCUMENT_TYPE', 'PLACEMENT_SLIP', 'Placement slip', 135),
    ('DOCUMENT_TYPE', 'PLACEMENT_FILE', 'Placement file', 136)
) as v(type_code, code, label, sort_order)
on conflict (type_code, code) do nothing;

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from,
                       record_status, authorized_by, authorized_at, created_at, created_by)
select 'RNW_PLACEMENT_RETURN_REASON', v.code, v.label, v.sort_order, null,
       date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('ACCOUNT_BUSINESS_TYPE', 'Account Type / Business Type', 10),
    ('AO_REQUEST', 'AO Request - For Updating', 20),
    ('CANCELED_REQUEST', 'Canceled Request', 30),
    ('CIF_KYC', 'CIF / KYC', 40),
    ('CLIENT_NAME', 'Client / Assured''s Name', 50),
    ('COMMISSION_RATE', 'Commission Rate', 60),
    ('CONSTRUCTION_OCCUPANCY', 'Construction / Occupancy', 70),
    ('COVERAGE', 'Coverage', 80),
    ('CRM', 'CRM', 90),
    ('DOUBLE_REQUEST', 'Double Request', 100),
    ('DST', 'DST', 110),
    ('EMAIL_ADDRESS', 'Email Address', 120),
    ('EOPT_DETAILS', 'EOPT Details', 130),
    ('EXTENSION_DEDUCTIBLE', 'Extension / Deductible', 140),
    ('FST', 'FST', 150),
    ('HOLD_COVER_DETAILS', 'Hold Cover Details', 160),
    ('INSURER_DETAILS', 'Insurer / Insurer Code / Insurer Branch', 170),
    ('INSURER_DECLINED', 'Insurer Declined the Risk', 180),
    ('INSURER_APPROVAL', 'Insurer''s Approval', 190),
    ('ITEMS_INSURED', 'Items Insured', 200),
    ('LGT', 'LGT', 210),
    ('LOCATION_OF_RISK', 'Location of Risk', 220),
    ('MANDATORY_FIELD', 'Mandatory Field', 230),
    ('MARKETING_DIARY', 'Marketing Diary Details', 240),
    ('MIS_RELATED', 'MIS Related', 250),
    ('MORTGAGEE', 'Mortgagee', 260),
    ('MOTOR_TYPE', 'Motor Type', 270),
    ('NON_BANK_APPROVAL', 'Non-Bank Client Approval', 280),
    ('PACKAGE', 'Package', 290),
    ('PAYMENT_RELATED', 'Payment Undertaking / Payment Related', 300),
    ('PERIOD_OF_INSURANCE', 'Period of Insurance', 310),
    ('DELIVERY_INSTRUCTION', 'Policy Delivery Instruction / Others', 320),
    ('PREMIUM_RATE', 'Premium Rate / Premium Variance', 330),
    ('PRODUCT_CODE', 'Product Code', 340),
    ('REQUIRING_APPROVAL', 'Requiring Approval', 350),
    ('RISK_DETAILS', 'Risk Details', 360),
    ('TSI', 'TSI / Sum Insured', 370),
    ('UNIT_DETAILS', 'Unit Details', 380),
    ('VAT', 'VAT', 390)
) as v(code, label, sort_order)
on conflict (type_code, code) do nothing;

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic,
                           reason_lov, sort_order)
values ('RNW_CASE', 'FOR_PLACEMENT_BOOKING', 'return_placement', 'FOR_DISPOSITION',
        'Return to Marketing', 'RNW_PROCESS', false, 'RNW_PLACEMENT_RETURN_REASON', 10)
on conflict do nothing;

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RNW_PLACEMENT_SLA_PACKAGED', '3', 'INTEGER', 'RENEWAL',
     'Target turnaround of the insurer''s placement response for a packaged account, in business days',
     1, 60, now(), 'SYSTEM'),
    ('RNW_PLACEMENT_SLA_NON_PACKAGE', '10', 'INTEGER', 'RENEWAL',
     'Target turnaround of the insurer''s placement response for a non-package account, in business days',
     1, 60, now(), 'SYSTEM'),
    ('RNW_PLACEMENT_CUTOFF_HOUR', '15', 'INTEGER', 'RENEWAL',
     'Hour of the day after which a placement sent to the insurer counts from the next business day',
     0, 23, now(), 'SYSTEM'),
    ('RNW_BOOK_ON_PLACEMENT_APPROVAL', 'false', 'BOOLEAN', 'RENEWAL',
     'The insurer''s approval of the placement books and locks the renewal account (true), or leaves it For Booking for the Processing Officer to book (false)',
     null, null, now(), 'SYSTEM'),
    ('RNW_INSURANCE_ADVICE_AUTO', 'true', 'BOOLEAN', 'RENEWAL',
     'The Insurance Advice of a mortgaged renewal account is generated when its placement is sent to the insurer, and again when the placement changes',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order)
values ('RNW_PLACEMENT_FAILED', 'Renewal placement not sent', 'RENEWAL',
        'The placement file of an account you process could not be uploaded or sent to the insurer',
        true, true, 800),
       ('RNW_PLACEMENT_RESPONDED', 'Renewal placement response', 'RENEWAL',
        'An insurer approved or rejected the placement of an account you process', true, false, 810)
on conflict (code) do nothing;
