-- =====================================================================================
-- iNXT BrokerVerse - V28 Chart of accounts: upload, numbering, short code, negative balance
-- (BRD-5 FRBS, wave A1-GL).
--   FRBS 2.3.1  chart upload (bulk handler COA_ACCOUNTS; no table needed);
--   FRBS 2.3.2  system-generated child account numbers: coa_numbering (parent code + child
--               sequence of a fixed width), proposed when the code is left blank;
--   FRBS 2.3.3  search by short code: the short code is unique per company (case-insensitive);
--   FRBS 2.5.4 / 2.8.4 / 3.6.0b  negative balance control per account (ALLOW / WARN / BLOCK;
--               natural side from the account class), AQ30.
-- Only V1-V27 tables are referenced (runs before every business module on a fresh database).
-- =====================================================================================
alter table coa_account add column negative_balance_policy varchar(10) not null default 'ALLOW';
alter table coa_account add constraint ck_account_negative_policy
    check (negative_balance_policy in ('ALLOW', 'WARN', 'BLOCK'));

-- Short codes become unique per company: blanks become null, later duplicates are cleared.
update coa_account set short_name = null where short_name is not null and trim(short_name) = '';
update coa_account a set short_name = null
where a.short_name is not null
  and exists (select 1 from coa_account b
              where b.company_id = a.company_id
                and lower(b.short_name) = lower(a.short_name)
                and b.id < a.id);
create unique index uq_account_short_name on coa_account (company_id, lower(short_name))
    where short_name is not null;

create table coa_numbering (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    company_id  bigint       not null references org_company (id),
    parent_code varchar(30)  not null,
    separator   varchar(1)   not null default '',
    width       integer      not null,
    active      boolean      not null default true,
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_coa_numbering unique (company_id, parent_code),
    constraint ck_coa_numbering_width check (width between 1 and 6),
    constraint ck_coa_numbering_separator check (separator in ('', '.', '-'))
);
