-- =====================================================================================
-- iNXT FinVerse - V300 Reinsurance: treaty programme, cessions, facultative placements,
-- reinsurers' share of claims and quarterly statements of account (SOA).
-- Reinsurance accounting is kept in the company base currency; policy-currency amounts
-- are stored next to base amounts where the underwriting registers need them.
-- =====================================================================================

-- ---------------------------------------------------------------- treaty programme --
create table ri_treaty (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    code                  varchar(20)    not null,
    name                  varchar(120)   not null,
    treaty_type           varchar(15)    not null,
    business_line         varchar(20)    not null,
    uw_year               integer        not null check (uw_year between 2000 and 2100),
    period_from           date           not null,
    period_to             date           not null,
    currency              varchar(3)     not null references cur_currency (code),
    quota_share_pct       numeric(19, 8),
    treaty_limit          numeric(19, 2),
    retention_limit       numeric(19, 2),
    lines                 integer,
    levy_pct              numeric(19, 8) not null default 0,
    reserve_interest_pct  numeric(19, 8) not null default 0,
    loss_reserve_pct      numeric(19, 8) not null default 0,
    statement_frequency   varchar(10)    not null default 'QUARTERLY',
    broker_party_id       bigint references pty_party (id),
    record_status         varchar(30)    not null,
    authorized_by         varchar(50),
    authorized_at         timestamptz,
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_ri_treaty_code unique (company_id, code),
    constraint ck_ri_treaty_type check (treaty_type in ('QUOTA_SHARE', 'SURPLUS', 'XOL')),
    constraint ck_ri_treaty_period check (period_to >= period_from),
    constraint ck_ri_treaty_qs check (quota_share_pct is null or quota_share_pct between 0 and 100),
    constraint ck_ri_treaty_limit check (treaty_limit is null or treaty_limit > 0),
    constraint ck_ri_treaty_retention check (retention_limit is null or retention_limit > 0),
    constraint ck_ri_treaty_lines check (lines is null or lines between 1 and 50),
    constraint ck_ri_treaty_levy check (levy_pct between 0 and 100),
    constraint ck_ri_treaty_interest check (reserve_interest_pct between 0 and 100),
    constraint ck_ri_treaty_loss_reserve check (loss_reserve_pct between 0 and 100),
    constraint ck_ri_treaty_frequency check (statement_frequency in ('QUARTERLY'))
);
create index ix_ri_treaty_programme on ri_treaty (company_id, business_line, uw_year);

create table ri_treaty_participant (
    treaty_id              bigint         not null references ri_treaty (id),
    line_no                integer        not null,
    party_id               bigint         not null references pty_party (id),
    share_pct              numeric(19, 8) not null check (share_pct > 0 and share_pct <= 100),
    commission_pct         numeric(19, 8) not null default 0 check (commission_pct between 0 and 100),
    profit_commission_pct  numeric(19, 8) not null default 0
        check (profit_commission_pct between 0 and 100),
    premium_reserve_pct    numeric(19, 8) not null default 0
        check (premium_reserve_pct between 0 and 100),
    constraint pk_ri_treaty_participant primary key (treaty_id, line_no),
    constraint uq_ri_treaty_participant_party unique (treaty_id, party_id)
);
create index ix_ri_treaty_participant_party on ri_treaty_participant (party_id);

create table ri_treaty_layer (
    treaty_id              bigint         not null references ri_treaty (id),
    layer_no               integer        not null check (layer_no > 0),
    priority               numeric(19, 2) not null check (priority >= 0),
    layer_limit            numeric(19, 2) not null check (layer_limit > 0),
    min_deposit_premium    numeric(19, 2) not null default 0 check (min_deposit_premium >= 0),
    reinstatements         integer        not null default 0 check (reinstatements between 0 and 10),
    constraint pk_ri_treaty_layer primary key (treaty_id, layer_no)
);

-- ---------------------------------------------------------------------- cessions --
create table ri_cession (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    branch_id        bigint         not null references org_branch (id),
    cession_no       varchar(40)    not null,
    policy_id        bigint         not null references uw_policy (id),
    policy_no        varchar(40)    not null,
    endorsement_no   integer        not null check (endorsement_no >= 0),
    document_no      varchar(50)    not null,
    kind             varchar(20)    not null,
    basis            varchar(10)    not null check (basis in ('FULL', 'PRO_RATA', 'NONE')),
    business_line    varchar(20)    not null,
    product_code     varchar(20)    not null,
    uw_year          integer        not null,
    treaty_year      integer        not null,
    issue_date       date           not null,
    effective_date   date           not null,
    ri_date          date           not null,
    currency         varchar(3)     not null,
    exchange_rate    numeric(19, 8) not null check (exchange_rate > 0),
    share_pct        numeric(19, 8) not null,
    our_si           numeric(19, 2) not null,
    our_premium      numeric(19, 2) not null,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_ri_cession_no unique (company_id, cession_no),
    constraint uq_ri_cession_transaction unique (company_id, policy_id, endorsement_no)
);
create index ix_ri_cession_date on ri_cession (company_id, ri_date);
create index ix_ri_cession_policy on ri_cession (policy_id, effective_date);

create table ri_fac_placement (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    placement_no      varchar(40)    not null,
    cession_id        bigint         not null references ri_cession (id),
    risk_id           bigint         not null,
    risk_line_no      integer        not null,
    risk_description  varchar(300)   not null,
    risk_si           numeric(19, 2) not null,
    risk_premium      numeric(19, 2) not null,
    fac_pct           numeric(19, 8) not null check (fac_pct >= 0 and fac_pct <= 100),
    fac_si            numeric(19, 2) not null,
    fac_premium       numeric(19, 2) not null,
    placed_si         numeric(19, 2) not null default 0,
    placed_premium    numeric(19, 2) not null default 0,
    status            varchar(20)    not null,
    submitted_by      varchar(50),
    submitted_at      timestamptz,
    placed_by         varchar(50),
    placed_on         date,
    closed_on         date,
    remarks           varchar(300),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_ri_fac_placement_no unique (company_id, placement_no),
    constraint uq_ri_fac_placement_risk unique (cession_id, risk_id),
    constraint ck_ri_fac_placement_status
        check (status in ('PROVISIONAL', 'PENDING_APPROVAL', 'PLACED', 'CLOSED'))
);
create index ix_ri_fac_placement_status on ri_fac_placement (company_id, status);

create table ri_fac_participant (
    placement_id     bigint         not null references ri_fac_placement (id),
    line_no          integer        not null,
    party_id         bigint         not null references pty_party (id),
    share_pct        numeric(19, 8) not null check (share_pct > 0 and share_pct <= 100),
    commission_pct   numeric(19, 8) not null default 0 check (commission_pct between 0 and 100),
    sum_insured      numeric(19, 2) not null default 0,
    premium          numeric(19, 2) not null default 0,
    commission       numeric(19, 2) not null default 0,
    posting_ref      varchar(100),
    constraint pk_ri_fac_participant primary key (placement_id, line_no),
    constraint uq_ri_fac_participant_party unique (placement_id, party_id)
);
create index ix_ri_fac_participant_party on ri_fac_participant (party_id);

create table ri_cession_line (
    id                bigint generated by default as identity primary key,
    cession_id        bigint         not null references ri_cession (id),
    risk_id           bigint         not null,
    risk_line_no      integer        not null,
    risk_description  varchar(300)   not null,
    risk_si           numeric(19, 2) not null,
    risk_premium      numeric(19, 2) not null,
    layer             varchar(12)    not null
        check (layer in ('RETENTION', 'QUOTA_SHARE', 'SURPLUS', 'FAC')),
    treaty_id         bigint references ri_treaty (id),
    placement_id      bigint references ri_fac_placement (id),
    party_id          bigint references pty_party (id),
    party_code        varchar(20),
    share_pct         numeric(19, 8) not null,
    sum_insured       numeric(19, 2) not null,
    premium           numeric(19, 2) not null,
    commission_pct    numeric(19, 8) not null default 0,
    commission        numeric(19, 2) not null default 0,
    base_premium      numeric(19, 2) not null,
    base_commission   numeric(19, 2) not null default 0,
    posting_ref       varchar(100)
);
create index ix_ri_cession_line_cession on ri_cession_line (cession_id);
create index ix_ri_cession_line_treaty on ri_cession_line (treaty_id, party_id);
create index ix_ri_cession_line_placement on ri_cession_line (placement_id);

-- --------------------------------------------------------------- claims side --
create table ri_claim_movement (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    branch_id       bigint         not null references org_branch (id),
    reference       varchar(100)   not null,
    claim_id        bigint         not null,
    claim_no        varchar(40)    not null,
    policy_id       bigint         not null,
    cession_id      bigint references ri_cession (id),
    business_line   varchar(20)    not null,
    loss_date       date           not null,
    movement_date   date           not null,
    movement_type   varchar(20)    not null
        check (movement_type in ('RESERVE_CHANGE', 'PAYMENT', 'RECOVERY')),
    currency        varchar(3)     not null,
    amount          numeric(19, 2) not null,
    base_amount     numeric(19, 2) not null,
    net_retained    numeric(19, 2) not null default 0,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_ri_claim_movement_ref unique (company_id, reference)
);
create index ix_ri_claim_movement_claim on ri_claim_movement (claim_id);
create index ix_ri_claim_movement_date on ri_claim_movement (company_id, movement_date);

create table ri_claim_share (
    id              bigint generated by default as identity primary key,
    movement_id     bigint         not null references ri_claim_movement (id),
    layer           varchar(12)    not null
        check (layer in ('QUOTA_SHARE', 'SURPLUS', 'FAC', 'XOL')),
    treaty_id       bigint references ri_treaty (id),
    layer_no        integer,
    placement_id    bigint references ri_fac_placement (id),
    party_id        bigint         not null references pty_party (id),
    party_code      varchar(20)    not null,
    share_pct       numeric(19, 8) not null,
    base_amount     numeric(19, 2) not null,
    posting_ref     varchar(100)
);
create index ix_ri_claim_share_movement on ri_claim_share (movement_id);
create index ix_ri_claim_share_treaty on ri_claim_share (treaty_id, party_id);

-- ------------------------------------------------------ statements of account --
create table ri_soa (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    soa_no                    varchar(40)    not null,
    treaty_id                 bigint         not null references ri_treaty (id),
    party_id                  bigint         not null references pty_party (id),
    soa_year                  integer        not null,
    quarter                   integer        not null check (quarter between 1 and 4),
    period_from               date           not null,
    period_to                 date           not null,
    statement_date            date           not null,
    currency                  varchar(3)     not null,
    premium                   numeric(19, 2) not null default 0,
    commission                numeric(19, 2) not null default 0,
    levy                      numeric(19, 2) not null default 0,
    losses_paid               numeric(19, 2) not null default 0,
    recoveries                numeric(19, 2) not null default 0,
    premium_reserve_retained  numeric(19, 2) not null default 0,
    premium_reserve_released  numeric(19, 2) not null default 0,
    interest                  numeric(19, 2) not null default 0,
    loss_reserve_retained     numeric(19, 2) not null default 0,
    loss_reserve_released     numeric(19, 2) not null default 0,
    balance                   numeric(19, 2) not null default 0,
    status                    varchar(20)    not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'SETTLED')),
    approved_by               varchar(50),
    approved_at               timestamptz,
    adjustment_batch_no       varchar(40),
    settlement_date           date,
    settlement_batch_no       varchar(40),
    bank_account_code         varchar(20),
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_ri_soa_no unique (company_id, soa_no),
    constraint uq_ri_soa_period unique (treaty_id, party_id, soa_year, quarter)
);
create index ix_ri_soa_status on ri_soa (company_id, status);

-- ------------------------------------------------------ accounting event types --
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('RI_SOA_ADJUSTMENT', 'Reinsurance statement adjustments', 'REINSURANCE', 'REINSURANCE',
  'Levy withheld, premium and loss reserves retained (negative = released) and interest on reserves',
  'LEVY,PREMIUM_RESERVE,LOSS_RESERVE,INTEREST'),
 ('RI_BALANCE_OFFSET', 'Reinsurer balance offset', 'REINSURANCE', 'REINSURANCE',
  'Recoveries due from a reinsurer set off against premium due to it on settlement', 'AMOUNT');

-- ----------------------------------------------------------- exception codes --
insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by) values
    ('RI_FAC_UNPLACED', 'Facultative placement not placed',
     'A facultative requirement is still provisional or pending approval more than the threshold days after the policy was ceded.',
     'REINSURANCE', 'HIGH', null, 30, now(), 'SYSTEM'),
    ('RI_TREATY_CAPACITY', 'Treaty capacity exceeded',
     'A risk sum insured exceeds the treaty capacity (retention + quota share + surplus lines); the excess needs facultative cover.',
     'REINSURANCE', 'MEDIUM', null, null, now(), 'SYSTEM');

-- --------------------------------------------------------------- permissions --
-- Checker permission for treaties, facultative placements and statements of account.
insert into sec_role_permission (role_id, permission)
select r.id, 'REINSURANCE_AUTHORIZE' from sec_role r
where r.code in ('FIN_MANAGER', 'AUTHORIZER')
  and not exists (select 1 from sec_role_permission x
                  where x.role_id = r.id and x.permission = 'REINSURANCE_AUTHORIZE');
