-- =====================================================================================
-- iNXT BrokerVerse - V30 Periods: module cut-off and scheduled close (BRD-5 FRBS, wave A1-GL).
--   FRBS 3.4.0 / 3.4.1  broking books closed automatically at month end: a module lock per period
--               (module BROKING) refuses postings of the broking source modules while the GL
--               stays open for FRBS adjustments (job BROKING_BOOKS_CLOSE);
--   FRBS 2.6.0 / 2.6.1  month-end close of the previous month on a chosen date and time (job
--               GL_PERIOD_CLOSE runs the checklist and closes, or raises GL_CLOSE_FAILED), AQ04.
-- =====================================================================================
create table acc_period_module_lock (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    company_id  bigint       not null references org_company (id),
    period_id   bigint       not null references per_period (id),
    module      varchar(30)  not null,
    locked      boolean      not null,
    locked_by   varchar(50),
    locked_at   timestamptz,
    unlocked_by varchar(50),
    unlocked_at timestamptz,
    note        varchar(300),
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_period_module_lock unique (period_id, module)
);
create index ix_period_module_lock_company on acc_period_module_lock (company_id, module, locked);

create table acc_period_close_schedule (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    company_id   bigint        not null references org_company (id),
    period_id    bigint        not null references per_period (id),
    scheduled_at timestamptz   not null,
    status       varchar(15)   not null,
    executed_at  timestamptz,
    result       varchar(2000),
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_close_schedule_status
        check (status in ('SCHEDULED', 'COMPLETED', 'FAILED', 'CANCELLED'))
);
create unique index uq_close_schedule_active on acc_period_close_schedule (period_id)
    where status = 'SCHEDULED';
create index ix_close_schedule_due on acc_period_close_schedule (status, scheduled_at);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('BROKING_SOURCE_MODULES',
     'BOOKING,OPSLEDGER,CASHIERING,REMITTANCE,ADJUSTMENT,COMMISSION,PRODRECON,DISBURSEMENT',
     'CODE_LIST', 'ACCOUNTING',
     'Source modules of the broking books: their postings are refused once the BROKING books of the period are closed (FRBS 3.4.0)',
     null, null, now(), 'SYSTEM');
