-- =====================================================================================
-- iNXT BrokerVerse - V31 Cost-centre rules and employees (BRD-5, wave A1-GL).
--   FRBS 3.1.1  standard rules to capture the cost / responsibility centre: the accounting
--               engine fills a missing cost centre from the first matching rule (source module,
--               event type, branch, party, account); still missing on an account that requires
--               one -> event FAILED with alert COST_CENTER_MISSING (seeded in V890), AQ26;
--   DIS 3.30.1 / 3.30.2  employee master with cost centre, and the headcount per cost centre.
-- =====================================================================================
create table acc_cost_center_rule (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    company_id    bigint       not null references org_company (id),
    priority      integer      not null,
    source_module varchar(30),
    event_type    varchar(40),
    branch_id     bigint references org_branch (id),
    party_code    varchar(30),
    account_code  varchar(30),
    cost_center   varchar(20)  not null,
    description   varchar(200),
    active        boolean      not null default true,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_cost_center_rule_priority check (priority between 1 and 9999)
);
create index ix_cost_center_rule_company on acc_cost_center_rule (company_id, active, priority);

create table org_employee (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    company_id   bigint       not null references org_company (id),
    employee_no  varchar(20)  not null,
    full_name    varchar(120) not null,
    branch_id    bigint       not null references org_branch (id),
    cost_center  varchar(20)  not null,
    position     varchar(80),
    email        varchar(120),
    party_code   varchar(30),
    hired_on     date,
    separated_on date,
    active       boolean      not null default true,
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_employee_no unique (company_id, employee_no)
);
create index ix_employee_cost_center on org_employee (company_id, cost_center);
