-- =====================================================================================
-- iNXT BrokerVerse - V32 Report batches (BRD-5 FRBS 2.4.5 / 2.4.7 / 2.4.9, wave A1-GL).
-- Several reports run with shared parameters and are downloaded as one ZIP (XLSX / ODS / PDF /
-- CSV) or as one merged PDF. The print options of FRBS 2.4.9 (paper, orientation, fit to
-- width) are chosen per export and kept on the batch and in the parameter echo of each run.
-- Only V1-V27 tables are referenced (report_run is created later, by V762).
-- =====================================================================================
create table report_batch (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    batch_no     varchar(30)   not null unique,
    company_id   bigint references org_company (id),
    format       varchar(10)   not null,
    merged_pdf   boolean       not null default false,
    paper        varchar(10)   not null default 'A4',
    orientation  varchar(10)   not null default 'AUTO',
    fit_to_width boolean       not null default true,
    parameters   varchar(2000),
    status       varchar(15)   not null,
    file_name    varchar(255),
    content_type varchar(100),
    content      bytea,
    size_bytes   bigint,
    completed_at timestamptz,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_report_batch_status check (status in ('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED')),
    constraint ck_report_batch_paper check (paper in ('A4', 'LETTER', 'LEGAL', 'A3')),
    constraint ck_report_batch_orientation check (orientation in ('AUTO', 'PORTRAIT', 'LANDSCAPE'))
);
create index ix_report_batch_creator on report_batch (created_by, created_at);

create table report_batch_item (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    batch_id    bigint        not null references report_batch (id),
    item_no     integer       not null,
    report_code varchar(40)   not null,
    status      varchar(10)   not null,
    row_count   integer       not null default 0,
    error       varchar(1000),
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_report_batch_item unique (batch_id, item_no),
    constraint ck_report_batch_item_status check (status in ('OK', 'FAILED'))
);
