-- ======================================================================================
-- V28 - Platform: shared state (Redis 7 fallbacks) and integration events (Apache Kafka)
-- See docs/architecture/PLATFORM_CACHE_AND_EVENTS.md.
--
--  * sys_job_run.status gains SKIPPED_LOCKED: a run that found the cluster-wide job lock taken.
--  * sys_job_lock_fence_seq: fencing tokens of the PostgreSQL advisory job lock (Redis disabled).
--  * sec_revoked_token / sys_shared_counter: token denylist and shared counters when Redis is
--    disabled (with Redis both stay empty).
--  * evt_outbox: transactional outbox of the integration events (relayed to Kafka after commit).
--  * evt_archive: every integration event consumed from Kafka (support traceability).
--  * evt_dead_letter: events a consumer could not process (dead-letter topics), with retry.
-- ======================================================================================

alter table sys_job_run drop constraint if exists sys_job_run_status_check;
alter table sys_job_run alter column status type varchar(20);
alter table sys_job_run add constraint sys_job_run_status_check
    check (status in ('RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED_LOCKED'));

create sequence sys_job_lock_fence_seq;

create table sec_revoked_token (
    jti         varchar(64)  primary key,
    username    varchar(50)  not null,
    expires_at  timestamptz  not null,
    revoked_at  timestamptz  not null
);
create index ix_sec_revoked_token_expires on sec_revoked_token (expires_at);

create table sys_shared_counter (
    counter_key    varchar(200) primary key,
    counter_value  bigint       not null check (counter_value >= 0),
    expires_at     timestamptz  not null
);
create index ix_sys_shared_counter_expires on sys_shared_counter (expires_at);

create table evt_outbox (
    id               bigint generated by default as identity primary key,
    event_id         uuid          not null unique,
    topic            varchar(120)  not null,
    event_type       varchar(80)   not null,
    event_key        varchar(200)  not null,
    company_id       bigint,
    company_code     varchar(20),
    correlation_id   varchar(64)   not null,
    occurred_at      timestamptz   not null,
    payload          text          not null,
    status           varchar(10)   not null check (status in ('PENDING', 'SENT', 'LOCAL', 'FAILED')),
    attempts         integer       not null default 0,
    next_attempt_at  timestamptz   not null,
    last_error       varchar(1000),
    sent_at          timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null
);
create index ix_evt_outbox_pending on evt_outbox (id) where status = 'PENDING';
create index ix_evt_outbox_status_created on evt_outbox (status, created_at);
create index ix_evt_outbox_key on evt_outbox (topic, event_key);

create table evt_archive (
    id               bigint generated by default as identity primary key,
    event_id         uuid          not null unique,
    topic            varchar(120)  not null,
    event_type       varchar(80)   not null,
    event_key        varchar(200)  not null,
    company_code     varchar(20),
    correlation_id   varchar(64),
    occurred_at      timestamptz   not null,
    kafka_partition  integer       not null,
    kafka_offset     bigint        not null,
    envelope         text          not null,
    archived_at      timestamptz   not null
);
create index ix_evt_archive_topic_time on evt_archive (topic, occurred_at);
create index ix_evt_archive_key on evt_archive (event_key);
create index ix_evt_archive_correlation on evt_archive (correlation_id);

create table evt_dead_letter (
    id               bigint generated by default as identity primary key,
    event_id         uuid,
    original_topic   varchar(120)  not null,
    dlt_topic        varchar(130)  not null,
    kafka_partition  integer       not null,
    kafka_offset     bigint        not null,
    event_key        varchar(200),
    consumer_group   varchar(120),
    error_message    varchar(2000),
    payload          text          not null,
    status           varchar(10)   not null check (status in ('NEW', 'RETRIED', 'DISCARDED')),
    received_at      timestamptz   not null,
    resolved_at      timestamptz,
    resolved_by      varchar(50),
    constraint uq_evt_dead_letter_position unique (dlt_topic, kafka_partition, kafka_offset)
);
create index ix_evt_dead_letter_status on evt_dead_letter (status, received_at);
