-- =====================================================================================
-- iNXT FinVerse - V3 Party master, open-item sub-ledger and event-driven accounting engine
-- =====================================================================================

create table pty_party (
    id                   bigint generated by default as identity primary key,
    version              bigint       not null default 0,
    company_id           bigint       not null references org_company (id),
    code                 varchar(30)  not null,
    name                 varchar(200) not null,
    party_type           varchar(30)  not null,
    tax_id               varchar(30),
    address              varchar(300),
    email                varchar(120),
    phone                varchar(40),
    default_currency     varchar(3)   not null,
    credit_days          integer      not null default 0,
    commission_rate      numeric(7, 4),
    withholding_tax_rate numeric(7, 4),
    licence_no           varchar(40),
    bank_name            varchar(120),
    bank_account_no      varchar(40),
    branch_id            bigint references org_branch (id),
    record_status        varchar(30)  not null,
    authorized_by        varchar(50),
    authorized_at        timestamptz,
    created_at           timestamptz  not null,
    created_by           varchar(50)  not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_party_code unique (company_id, code)
);
create index ix_party_type on pty_party (company_id, party_type);

create table sl_open_item (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    branch_id        bigint         not null references org_branch (id),
    party_id         bigint         not null references pty_party (id),
    party_code       varchar(30)    not null,
    direction        varchar(6)     not null check (direction in ('DEBIT', 'CREDIT')),
    document_type    varchar(30)    not null,
    document_no      varchar(40)    not null,
    document_date    date           not null,
    due_date         date           not null,
    currency         varchar(3)     not null,
    amount           numeric(19, 2) not null check (amount > 0),
    base_amount      numeric(19, 2) not null check (base_amount >= 0),
    settled_amount   numeric(19, 2) not null default 0,
    status           varchar(20)    not null,
    source_module    varchar(30)    not null,
    source_reference varchar(80),
    journal_batch_no varchar(40),
    narration        varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_settled check (settled_amount >= 0 and settled_amount <= amount)
);
create index ix_open_item_party on sl_open_item (company_id, party_id, document_date);
create index ix_open_item_status on sl_open_item (company_id, status, document_date);
create unique index uq_open_item_source on sl_open_item (company_id, source_module, source_reference)
    where source_reference is not null;

create table sl_item_match (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    debit_item_id  bigint         not null references sl_open_item (id),
    credit_item_id bigint         not null references sl_open_item (id),
    amount         numeric(19, 2) not null check (amount > 0),
    match_date     date           not null,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_match_debit on sl_item_match (debit_item_id);
create index ix_match_credit on sl_item_match (credit_item_id);

create table acc_event_type (
    code              varchar(40)  primary key,
    name              varchar(120) not null,
    category          varchar(20)  not null,
    journal_type      varchar(20)  not null,
    description       varchar(500),
    amount_components varchar(500) not null,
    active            boolean      not null default true
);

create table acc_rule (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    event_type     varchar(40)  not null references acc_event_type (code),
    name           varchar(120) not null,
    business_line  varchar(20),
    currency       varchar(3),
    priority       integer      not null default 100,
    effective_from date         not null,
    effective_to   date,
    record_status  varchar(30)  not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_rule_event on acc_rule (company_id, event_type);

create table acc_rule_line (
    id               bigint generated by default as identity primary key,
    rule_id          bigint       not null references acc_rule (id),
    line_no          integer      not null,
    side             varchar(6)   not null check (side in ('DEBIT', 'CREDIT')),
    account_code     varchar(30)  not null,
    amount_component varchar(40)  not null,
    party_line       boolean      not null default false,
    narration        varchar(200),
    constraint uq_rule_line unique (rule_id, line_no)
);

create table acc_event_log (
    id               bigint generated by default as identity primary key,
    company_id       bigint        not null,
    event_type       varchar(40)   not null,
    source_module    varchar(30)   not null,
    source_reference varchar(80)   not null,
    reference        varchar(60),
    value_date       date          not null,
    status           varchar(10)   not null,
    rule_id          bigint,
    batch_no         varchar(40),
    error_message    varchar(1000),
    amounts          varchar(1000) not null,
    processed_at     timestamptz   not null,
    processed_by     varchar(50)   not null
);
create index ix_event_log_search on acc_event_log (company_id, value_date, status);

-- Standard insurance accounting events. Publishing modules supply the listed amount components;
-- rules (configured per company) decide the GL accounts. "@ROLE" accounts come from the event.
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('POLICY_ISSUE', 'Policy issued / renewed', 'POLICY', 'PREMIUM',
  'Premium raised on a new or renewed policy (debit note)', 'GROSS_PREMIUM,DST,VAT,LGT,FST,PREMIUM_TAX,POLICY_FEE,TOTAL_DUE'),
 ('POLICY_ENDORSEMENT', 'Policy endorsement', 'POLICY', 'ENDORSEMENT',
  'Additional (positive) or return (negative) premium on an endorsement', 'GROSS_PREMIUM,DST,VAT,LGT,FST,PREMIUM_TAX,POLICY_FEE,TOTAL_DUE'),
 ('POLICY_CANCELLATION', 'Policy cancellation', 'POLICY', 'ENDORSEMENT',
  'Return premium on cancellation (negative amounts)', 'GROSS_PREMIUM,DST,VAT,LGT,FST,PREMIUM_TAX,POLICY_FEE,TOTAL_DUE'),
 ('COMMISSION_ACCRUAL', 'Commission accrued', 'COMMISSION', 'COMMISSION',
  'Agent / broker commission earned on premium', 'COMMISSION,WITHHOLDING_TAX,NET_COMMISSION'),
 ('COINSURANCE_SHARE', 'Coinsurer share of premium', 'COINSURANCE', 'PREMIUM',
  'Premium share due to coinsurers when leading', 'COINSURER_PREMIUM'),
 ('PREMIUM_RECEIPT', 'Premium collection', 'RECEIPT', 'RECEIPT',
  'Premium received from policyholder or intermediary (role BANK)', 'AMOUNT'),
 ('PREMIUM_DEPOSIT', 'Unapplied collection', 'RECEIPT', 'RECEIPT',
  'Money received but not yet matched to a debit note (role BANK)', 'AMOUNT'),
 ('PREMIUM_REFUND_PAYMENT', 'Premium refund payment', 'PAYMENT', 'PAYMENT',
  'Return premium paid to the policyholder (role BANK)', 'AMOUNT'),
 ('COMMISSION_PAYMENT', 'Commission payment', 'PAYMENT', 'PAYMENT',
  'Commission paid to an intermediary (role BANK)', 'AMOUNT'),
 ('CLAIM_RESERVE', 'Claim reserve change', 'CLAIMS', 'CLAIMS',
  'Increase (positive) or decrease (negative) of outstanding claim estimate', 'RESERVE_CHANGE'),
 ('CLAIM_SETTLEMENT', 'Claim settlement approved', 'CLAIMS', 'CLAIMS',
  'Claim settlement approved for payment, releasing the reserve', 'PAID_AMOUNT,RESERVE_RELEASE'),
 ('CLAIM_PAYMENT', 'Claim payment', 'PAYMENT', 'PAYMENT',
  'Payment of an approved claim settlement (role BANK)', 'AMOUNT'),
 ('CLAIM_RECOVERY', 'Salvage / subrogation recovery', 'CLAIMS', 'RECEIPT',
  'Recovery received on a claim (role BANK)', 'AMOUNT'),
 ('RI_PREMIUM_CEDED', 'Reinsurance premium ceded', 'REINSURANCE', 'REINSURANCE',
  'Treaty or facultative cession with reinsurance commission', 'CEDED_PREMIUM,RI_COMMISSION,NET_DUE'),
 ('RI_CLAIM_RECOVERY', 'Reinsurance claim recovery', 'REINSURANCE', 'REINSURANCE',
  'Reinsurers share of a paid claim', 'RECOVERY'),
 ('RI_RESERVE_SHARE', 'Reinsurers share of claim reserve', 'REINSURANCE', 'REINSURANCE',
  'Change in reinsurers share of outstanding claims', 'RESERVE_CHANGE'),
 ('RI_SETTLEMENT_PAYMENT', 'Payment to reinsurer', 'PAYMENT', 'PAYMENT',
  'Settlement of balance due to a reinsurer (role BANK)', 'AMOUNT'),
 ('RI_SETTLEMENT_RECEIPT', 'Receipt from reinsurer', 'RECEIPT', 'RECEIPT',
  'Settlement received from a reinsurer (role BANK)', 'AMOUNT'),
 ('UPR_PROVISION', 'Unearned premium reserve', 'PROVISION', 'PROVISION',
  'Change in gross UPR and reinsurers share (period end)', 'UPR_CHANGE,RI_UPR_CHANGE'),
 ('DAC_PROVISION', 'Deferred acquisition cost', 'PROVISION', 'PROVISION',
  'Change in DAC and deferred RI commission (period end)', 'DAC_CHANGE,DRC_CHANGE'),
 ('IBNR_PROVISION', 'IBNR reserve', 'PROVISION', 'PROVISION',
  'Change in IBNR reserve and reinsurers share (period end)', 'IBNR_CHANGE,RI_IBNR_CHANGE'),
 ('TAKAFUL_SURPLUS', 'Surplus / Mudharabah distribution', 'PROVISION', 'PROVISION',
  'Surplus payable to participants', 'SURPLUS'),
 ('SUPPLIER_INVOICE', 'Supplier invoice', 'PAYMENT', 'PAYMENT',
  'Expense invoice from a supplier (role EXPENSE)', 'NET_AMOUNT,INPUT_VAT,WITHHOLDING_TAX,PAYABLE'),
 ('SUPPLIER_PAYMENT', 'Supplier payment', 'PAYMENT', 'PAYMENT',
  'Payment to a supplier (role BANK)', 'AMOUNT'),
 ('PETTY_CASH_EXPENSE', 'Petty cash disbursement', 'PAYMENT', 'PAYMENT',
  'Expense paid from petty cash (roles EXPENSE, PETTY_CASH)', 'AMOUNT'),
 ('PETTY_CASH_REPLENISHMENT', 'Petty cash reimbursement', 'PAYMENT', 'PAYMENT',
  'Replenishment of the petty cash fund (roles BANK, PETTY_CASH)', 'AMOUNT'),
 ('MISC_RECEIPT', 'Miscellaneous receipt', 'RECEIPT', 'RECEIPT',
  'Other income received (roles BANK, INCOME)', 'AMOUNT'),
 ('MISC_PAYMENT', 'Miscellaneous payment', 'PAYMENT', 'PAYMENT',
  'Other expense paid by bank (roles BANK, EXPENSE)', 'AMOUNT'),
 ('BANK_TRANSFER', 'Bank transfer', 'TREASURY', 'PAYMENT',
  'Transfer between own bank accounts (roles FROM_BANK, TO_BANK)', 'AMOUNT');
