-- =====================================================================================
-- iNXT BrokerVerse - V400 Period-end: FX revaluation runs and year-end closing records.
-- =====================================================================================

-- One revaluation run per company and accounting period (idempotency key).
create table fx_revaluation_run (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    period_id          bigint         not null references per_period (id),
    period_name        varchar(20)    not null,
    revaluation_date   date           not null,
    gain_loss_account  varchar(30)    not null,
    auto_reverse       boolean        not null default false,
    reversal_date      date,
    status             varchar(20)    not null,
    journal_batch_no   varchar(40),
    reversal_batch_no  varchar(40),
    total_gain         numeric(19, 2) not null default 0,
    total_loss         numeric(19, 2) not null default 0,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_fx_reval_period unique (company_id, period_id),
    constraint ck_fx_reval_status check (status in ('POSTED', 'REVERSED'))
);
create index ix_fx_reval_company on fx_revaluation_run (company_id, revaluation_date);

create table fx_revaluation_line (
    id             bigint generated by default as identity primary key,
    run_id         bigint         not null references fx_revaluation_run (id),
    line_no        integer        not null,
    branch_id      bigint         not null references org_branch (id),
    account_id     bigint         not null references coa_account (id),
    account_code   varchar(30)    not null,
    currency       varchar(3)     not null,
    fc_balance     numeric(19, 2) not null,
    booked_base    numeric(19, 2) not null,
    closing_rate   numeric(19, 8) not null,
    revalued_base  numeric(19, 2) not null,
    difference     numeric(19, 2) not null,
    posted         boolean        not null default true,
    constraint uq_fx_reval_line unique (run_id, line_no)
);
create index ix_fx_reval_line_run on fx_revaluation_line (run_id);

-- Year-end closing: one record per closed fiscal year.
create table yec_year_end_close (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    fiscal_year_id            bigint         not null references per_fiscal_year (id),
    year_code                 integer        not null,
    closing_date              date           not null,
    net_result                numeric(19, 2) not null,
    retained_earnings_account varchar(30)    not null,
    closing_batches           varchar(1000),
    next_year_code            integer,
    status                    varchar(20)    not null,
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_year_end_close unique (fiscal_year_id),
    constraint ck_year_end_status check (status in ('CLOSED'))
);
create index ix_year_end_company on yec_year_end_close (company_id);
