-- =====================================================================================
-- iNXT BrokerVerse - V420 Actuarial reserves / period-end technical provisions:
-- reserve parameters per line of business (effective dated, maker-checker), takaful
-- settings per company, valuation runs with their reserve lines, policy-level UPR and
-- takaful surplus detail. See docs/modules/ACTUARIAL_RESERVES.md.
-- =====================================================================================

-- Reserve parameters of one line of business, effective from a date (maker-checker).
create table rsv_parameter (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    business_line         varchar(20)    not null,
    effective_from        date           not null,
    ibnr_method           varchar(20)    not null,
    ibnr_rate             numeric(19, 8) not null default 0,
    triangle_basis        varchar(20)    not null default 'INCURRED',
    development_period    varchar(20)    not null default 'YEAR',
    accident_periods      integer        not null default 5,
    mfad_pct              numeric(19, 8) not null default 0,
    ulae_pct              numeric(19, 8) not null default 0,
    expected_loss_ratio   numeric(19, 8) not null default 0,
    treaty_commission_pct numeric(19, 8) not null default 0,
    fac_commission_pct    numeric(19, 8) not null default 0,
    remarks               varchar(300),
    record_status         varchar(30)    not null,
    authorized_by         varchar(50),
    authorized_at         timestamptz,
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint rsv_parameter_uq unique (company_id, business_line, effective_from),
    constraint rsv_parameter_method_ck check (ibnr_method in ('RATE', 'CHAIN_LADDER')),
    constraint rsv_parameter_basis_ck check (triangle_basis in ('PAID', 'INCURRED')),
    constraint rsv_parameter_period_ck check (development_period in ('YEAR', 'QUARTER')),
    constraint rsv_parameter_periods_ck check (accident_periods between 2 and 20),
    constraint rsv_parameter_pct_ck check (ibnr_rate >= 0 and mfad_pct >= 0 and ulae_pct >= 0
        and expected_loss_ratio >= 0 and treaty_commission_pct between 0 and 100
        and fac_commission_pct between 0 and 100)
);
create index ix_rsv_parameter_lookup on rsv_parameter (company_id, business_line, effective_from);

-- Takaful (surplus / Mudharabah) settings: optional per company.
create table rsv_takaful_setting (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    enabled               boolean        not null default false,
    product_codes         varchar(500),
    participant_share_pct numeric(19, 8) not null default 0,
    tax_pct               numeric(19, 8) not null default 0,
    cost_center           varchar(20),
    record_status         varchar(30)    not null,
    authorized_by         varchar(50),
    authorized_at         timestamptz,
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint rsv_takaful_setting_uq unique (company_id),
    constraint rsv_takaful_setting_pct_ck check (participant_share_pct between 0 and 100
        and tax_pct between 0 and 100)
);

-- One valuation run per company and valuation (month-end) date; cancelled runs are kept.
create table rsv_valuation_run (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    valuation_date    date           not null,
    period_name       varchar(20)    not null,
    status            varchar(20)    not null,
    base_currency     varchar(3)     not null,
    previous_run_id   bigint references rsv_valuation_run (id),
    calculated_at     timestamptz    not null,
    remarks           varchar(1000),
    submitted_by      varchar(50),
    submitted_at      timestamptz,
    approved_by       varchar(50),
    approved_at       timestamptz,
    rejection_reason  varchar(300),
    posted_by         varchar(50),
    posted_at         timestamptz,
    journal_count     integer        not null default 0,
    cancelled_by      varchar(50),
    cancelled_at      timestamptz,
    cancel_reason     varchar(300),
    cancel_date       date,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint rsv_valuation_run_status_ck check (status in
        ('PREVIEW', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'CANCELLED'))
);
-- Idempotency: at most one live (not cancelled) run per company and valuation date.
create unique index rsv_valuation_run_live_uq on rsv_valuation_run (company_id, valuation_date)
    where status <> 'CANCELLED';
create index ix_rsv_valuation_run_company on rsv_valuation_run (company_id, valuation_date);

-- Reserve balances of a run per reserve type, branch, line of business, product and channel.
create table rsv_run_line (
    id             bigint generated by default as identity primary key,
    run_id         bigint         not null references rsv_valuation_run (id),
    reserve_type   varchar(20)    not null,
    branch_id      bigint         not null references org_branch (id),
    business_line  varchar(20)    not null,
    product_code   varchar(20)    not null,
    source_type    varchar(10)    not null,
    gross_amount   numeric(19, 2) not null,
    ri_amount      numeric(19, 2) not null,
    base_amount    numeric(19, 2),
    rate           numeric(19, 8),
    method         varchar(20),
    constraint rsv_run_line_type_ck check (reserve_type in
        ('UPR', 'DAC', 'OSLR', 'IBNR', 'ULAE', 'MFAD', 'PDR'))
);
create index ix_rsv_run_line_run on rsv_run_line (run_id, reserve_type);

-- Policy-level UPR of a run (one row per premium transaction), PGIBR072 drill-down.
create table rsv_upr_detail (
    id                   bigint generated by default as identity primary key,
    run_id               bigint         not null references rsv_valuation_run (id),
    policy_id            bigint         not null,
    endorsement_no       integer        not null,
    document_no          varchar(50)    not null,
    kind                 varchar(20)    not null,
    branch_id            bigint         not null references org_branch (id),
    business_line        varchar(20)    not null,
    product_code         varchar(20)    not null,
    source_type          varchar(10)    not null,
    upr_basis            varchar(20)    not null,
    cover_from           date           not null,
    cover_to             date           not null,
    approval_date        date           not null,
    total_units          integer        not null,
    earned_units         integer        not null,
    unearned_units       integer        not null,
    premium              numeric(19, 2) not null,
    commission           numeric(19, 2) not null,
    treaty_premium       numeric(19, 2) not null,
    fac_premium          numeric(19, 2) not null,
    ri_commission        numeric(19, 2) not null,
    unearned_premium     numeric(19, 2) not null,
    unearned_commission  numeric(19, 2) not null,
    treaty_upr           numeric(19, 2) not null,
    fac_upr              numeric(19, 2) not null,
    unearned_ri_comm     numeric(19, 2) not null,
    constraint rsv_upr_detail_uq unique (run_id, policy_id, endorsement_no)
);
create index ix_rsv_upr_detail_run on rsv_upr_detail (run_id, business_line);

-- Takaful surplus of policies expiring in the valuation month (PGIBR074).
create table rsv_takaful_line (
    id                bigint generated by default as identity primary key,
    run_id            bigint         not null references rsv_valuation_run (id),
    policy_id         bigint         not null,
    policy_no         varchar(40)    not null,
    insured_name      varchar(200)   not null,
    branch_id         bigint         not null references org_branch (id),
    business_line     varchar(20)    not null,
    product_code      varchar(20)    not null,
    source_type       varchar(10)    not null,
    expiry_date       date           not null,
    gross_premium     numeric(19, 2) not null,
    discount          numeric(19, 2) not null,
    loading           numeric(19, 2) not null,
    commission        numeric(19, 2) not null,
    claims            numeric(19, 2) not null,
    applicable        numeric(19, 2) not null,
    retakaful         numeric(19, 2) not null,
    tax               numeric(19, 2) not null,
    payable           numeric(19, 2) not null,
    constraint rsv_takaful_line_uq unique (run_id, policy_id)
);
create index ix_rsv_takaful_line_run on rsv_takaful_line (run_id);

-- Accounting events added by actuarial reserving (UPR_PROVISION, DAC_PROVISION and
-- IBNR_PROVISION exist since V3). OSLR is booked by claims (CLAIM_RESERVE) and its
-- reinsurers' share by reinsurance (RI_RESERVE_SHARE), so reserving does not post it.
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('CLAIM_MARGIN_PROVISION', 'ULAE and risk margin provision', 'PROVISION', 'PROVISION',
  'Change in the ULAE provision and the margin for adverse deviation (gross and reinsurers share)',
  'ULAE_CHANGE,MFAD_CHANGE,RI_MFAD_CHANGE'),
 ('PREMIUM_DEFICIENCY_PROVISION', 'Premium deficiency reserve', 'PROVISION', 'PROVISION',
  'Change in the premium deficiency reserve from the liability adequacy test', 'PDR_CHANGE');

-- Scheduled monthly valuation run: manual only until an administrator enables a schedule.
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RESERVES_AUTO_RUN_COMPANIES', '', 'CODE_LIST', 'OPERATIONS',
     'Company codes for which the monthly reserve valuation job prepares a run (blank = none)',
     null, null, now(), 'SYSTEM');
