-- =====================================================================================
-- iNXT BrokerVerse - V500 Payables, payments, petty cash and PDC issued
-- Company bank accounts and cheque books, supplier invoices (AP), payment vouchers with
-- open-item allocations, post-dated cheques issued (register + status history) and
-- imprest petty cash (funds, disbursements, reimbursements).
-- =====================================================================================

-- ---------- Company bank accounts (shared with receivables / bank reconciliation) -----
create table pay_bank_account (
    id                        bigint generated by default as identity primary key,
    version                   bigint       not null default 0,
    company_id                bigint       not null references org_company (id),
    code                      varchar(20)  not null,
    name                      varchar(120) not null,
    bank_party_code           varchar(30),
    bank_name                 varchar(120) not null,
    account_no                varchar(40)  not null,
    currency                  varchar(3)   not null references cur_currency (code),
    gl_account_code           varchar(30)  not null,
    pdc_clearing_account_code varchar(30),
    branch_id                 bigint references org_branch (id),
    notification_format       varchar(20)  not null default 'FIXED_WIDTH'
        check (notification_format in ('FIXED_WIDTH', 'CSV')),
    record_status             varchar(30)  not null,
    authorized_by             varchar(50),
    authorized_at             timestamptz,
    created_at                timestamptz  not null,
    created_by                varchar(50)  not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_bank_account_code unique (company_id, code),
    constraint uq_bank_account_gl unique (company_id, gl_account_code)
);

create table pay_cheque_book (
    id              bigint generated by default as identity primary key,
    version         bigint      not null default 0,
    bank_account_id bigint      not null references pay_bank_account (id),
    first_no        bigint      not null,
    last_no         bigint      not null,
    next_no         bigint      not null,
    received_on     date        not null,
    status          varchar(20) not null check (status in ('ACTIVE', 'EXHAUSTED', 'CANCELLED')),
    created_at      timestamptz not null,
    created_by      varchar(50) not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_cheque_range check (first_no > 0 and first_no <= last_no
        and next_no >= first_no and next_no <= last_no + 1)
);
create index ix_cheque_book_account on pay_cheque_book (bank_account_id, status);

-- ---------- Supplier invoices (accounts payable) ------------------------------------------
create table pay_supplier_invoice (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    branch_id           bigint         not null references org_branch (id),
    document_no         varchar(40)    not null,
    party_id            bigint         not null references pty_party (id),
    party_code          varchar(30)    not null,
    supplier_invoice_no varchar(40)    not null,
    invoice_date        date           not null,
    due_date            date           not null,
    currency            varchar(3)     not null,
    vat_applicable      boolean        not null,
    wht_rate            numeric(7, 4)  not null default 0,
    net_amount          numeric(19, 2) not null,
    vat_amount          numeric(19, 2) not null,
    wht_amount          numeric(19, 2) not null,
    payable_amount      numeric(19, 2) not null check (payable_amount > 0),
    base_payable_amount numeric(19, 2),
    narration           varchar(250),
    status              varchar(20)    not null
        check (status in ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CANCELLED')),
    submitted_by        varchar(50),
    submitted_at        timestamptz,
    approved_by         varchar(50),
    approved_at         timestamptz,
    status_reason       varchar(200),
    open_item_id        bigint references sl_open_item (id),
    journal_batch_nos   varchar(400),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_supplier_invoice_doc unique (company_id, document_no),
    constraint ck_invoice_dates check (due_date >= invoice_date)
);
create index ix_supplier_invoice_party on pay_supplier_invoice (company_id, party_id, supplier_invoice_no);
create index ix_supplier_invoice_status on pay_supplier_invoice (company_id, status, invoice_date);

create table pay_supplier_invoice_line (
    id                   bigint generated by default as identity primary key,
    invoice_id           bigint         not null references pay_supplier_invoice (id),
    line_no              integer        not null,
    expense_account_code varchar(30)    not null,
    cost_center          varchar(20),
    description          varchar(200)   not null,
    net_amount           numeric(19, 2) not null check (net_amount > 0),
    vat_amount           numeric(19, 2) not null,
    wht_amount           numeric(19, 2) not null,
    constraint uq_invoice_line unique (invoice_id, line_no)
);

-- ---------- Payment vouchers ---------------------------------------------------------------
create table pay_voucher (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    branch_id       bigint         not null references org_branch (id),
    voucher_no      varchar(40)    not null,
    party_id        bigint         not null references pty_party (id),
    party_code      varchar(30)    not null,
    payee_name      varchar(200)   not null,
    category        varchar(20)    not null
        check (category in ('SUPPLIER', 'COMMISSION', 'CLAIM', 'REINSURANCE', 'PREMIUM_REFUND')),
    payment_mode    varchar(20)    not null check (payment_mode in ('CHEQUE', 'BANK_TRANSFER', 'PDC')),
    bank_account_id bigint         not null references pay_bank_account (id),
    voucher_date    date           not null,
    cheque_no       varchar(20),
    cheque_date     date,
    currency        varchar(3)     not null,
    amount          numeric(19, 2) not null check (amount > 0),
    base_amount     numeric(19, 2),
    department      varchar(20),
    narration       varchar(250),
    status          varchar(20)    not null
        check (status in ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CANCELLED', 'VOIDED')),
    submitted_by    varchar(50),
    submitted_at    timestamptz,
    approved_by     varchar(50),
    approved_at     timestamptz,
    status_reason   varchar(200),
    journal_batch_no varchar(40),
    open_item_id    bigint references sl_open_item (id),
    presented_on    date,
    voided_on       date,
    void_batch_no   varchar(40),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_voucher_no unique (company_id, voucher_no),
    constraint ck_voucher_cheque_date check (cheque_date is null or cheque_date >= voucher_date)
);
create index ix_voucher_party on pay_voucher (company_id, party_id, voucher_date);
create index ix_voucher_status on pay_voucher (company_id, status, voucher_date);
create index ix_voucher_bank on pay_voucher (bank_account_id, payment_mode, voucher_date);

create table pay_voucher_allocation (
    id            bigint generated by default as identity primary key,
    voucher_id    bigint         not null references pay_voucher (id),
    open_item_id  bigint         not null references sl_open_item (id),
    document_type varchar(30)    not null,
    document_no   varchar(40)    not null,
    document_date date           not null,
    due_date      date           not null,
    amount        numeric(19, 2) not null check (amount > 0),
    constraint uq_voucher_item unique (voucher_id, open_item_id)
);
create index ix_allocation_item on pay_voucher_allocation (open_item_id);

-- ---------- Post-dated cheques issued -------------------------------------------------------
create table pay_pdc_issued (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    branch_id             bigint         not null references org_branch (id),
    voucher_id            bigint         not null references pay_voucher (id),
    bank_account_id       bigint         not null references pay_bank_account (id),
    party_id              bigint         not null references pty_party (id),
    party_code            varchar(30)    not null,
    payee_name            varchar(200)   not null,
    cheque_no             varchar(20)    not null,
    cheque_date           date           not null,
    issue_date            date           not null,
    currency              varchar(3)     not null,
    amount                numeric(19, 2) not null check (amount > 0),
    base_amount           numeric(19, 2) not null,
    department            varchar(20),
    status                varchar(20)    not null
        check (status in ('ISSUED', 'DUE', 'PRESENTED', 'CLEARED', 'CANCELLED', 'REPLACED')),
    presented_on          date,
    presentation_batch_no varchar(40),
    cleared_on            date,
    cancelled_on          date,
    cancel_batch_no       varchar(40),
    replaced_on           date,
    replaces_id           bigint references pay_pdc_issued (id),
    replaced_by_id        bigint references pay_pdc_issued (id),
    remarks               varchar(200),
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_pdc_cheque unique (bank_account_id, cheque_no)
);
create index ix_pdc_issued_status on pay_pdc_issued (company_id, status, cheque_date);
create index ix_pdc_issued_issue on pay_pdc_issued (company_id, issue_date);

create table pay_pdc_event (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    pdc_id      bigint       not null references pay_pdc_issued (id),
    event_date  date         not null,
    from_status varchar(20),
    to_status   varchar(20)  not null,
    batch_no    varchar(40),
    remarks     varchar(200),
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create index ix_pdc_event_pdc on pay_pdc_event (pdc_id, event_date);

-- ---------- Petty cash (imprest) --------------------------------------------------------------
create table pay_petty_cash_fund (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    branch_id                 bigint         not null references org_branch (id),
    code                      varchar(20)    not null,
    name                      varchar(120)   not null,
    custodian                 varchar(120)   not null,
    gl_account_code           varchar(30)    not null,
    replenish_bank_account_id bigint         not null references pay_bank_account (id),
    currency                  varchar(3)     not null,
    imprest_amount            numeric(19, 2) not null check (imprest_amount > 0),
    cash_balance              numeric(19, 2) not null default 0,
    established_on            date,
    record_status             varchar(30)    not null,
    authorized_by             varchar(50),
    authorized_at             timestamptz,
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_petty_cash_fund unique (company_id, code),
    constraint ck_petty_cash_balance check (cash_balance >= 0 and cash_balance <= imprest_amount)
);

create table pay_petty_cash_reimbursement (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    fund_id          bigint         not null references pay_petty_cash_fund (id),
    branch_id        bigint         not null references org_branch (id),
    document_no      varchar(40)    not null,
    claim_date       date           not null,
    bank_account_id  bigint         not null references pay_bank_account (id),
    amount           numeric(19, 2) not null check (amount > 0),
    narration        varchar(250),
    status           varchar(20)    not null check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    approved_by      varchar(50),
    approved_at      timestamptz,
    status_reason    varchar(200),
    journal_batch_no varchar(40),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_petty_cash_reimbursement unique (company_id, document_no)
);
create index ix_pcr_fund on pay_petty_cash_reimbursement (fund_id, claim_date);

create table pay_petty_cash_disbursement (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    company_id           bigint         not null references org_company (id),
    fund_id              bigint         not null references pay_petty_cash_fund (id),
    branch_id            bigint         not null references org_branch (id),
    document_no          varchar(40)    not null,
    disbursement_date    date           not null,
    payee                varchar(120)   not null,
    expense_account_code varchar(30)    not null,
    cost_center          varchar(20),
    description          varchar(200)   not null,
    receipt_ref          varchar(40),
    amount               numeric(19, 2) not null check (amount > 0),
    status               varchar(20)    not null check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')),
    approved_by          varchar(50),
    approved_at          timestamptz,
    status_reason        varchar(200),
    journal_batch_no     varchar(40),
    reimbursement_id     bigint references pay_petty_cash_reimbursement (id),
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_petty_cash_disbursement unique (company_id, document_no)
);
create index ix_pcd_fund on pay_petty_cash_disbursement (fund_id, status, disbursement_date);
create index ix_pcd_reimbursement on pay_petty_cash_disbursement (reimbursement_id);

-- ---------- Accounting events -------------------------------------------------------------------
-- A post-dated cheque is accounted for in two steps (see IssuedPdcService):
--   issue    : the party's payment event (SUPPLIER_PAYMENT, CLAIM_PAYMENT...) with role BANK set to
--              the bank account's PDC-issued clearing account (Dr payable / Cr PDC clearing);
--   maturity : PDC_ISSUED_PRESENTED on the presentation date (Dr PDC clearing / Cr bank).
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('PDC_ISSUED_PRESENTED', 'Issued PDC presented', 'PAYMENT', 'PAYMENT',
  'Post-dated cheque issued has matured and was presented: clears the PDC liability against the bank (roles PDC_CLEARING, BANK)',
  'AMOUNT');
