-- =====================================================================================
-- iNXT BrokerVerse - V550 Receivables: official receipts (collections), bank deposit slips,
-- post-dated cheques received and bank reconciliation.
--
-- Banks are identified by their GL bank account code (postable accounts of a bank/cash
-- category, e.g. 1111); this module keeps no bank master of its own.
-- =====================================================================================

create table rcv_deposit_slip (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    slip_no           varchar(40)    not null,
    slip_date         date           not null,
    bank_account_code varchar(30)    not null,
    currency          varchar(3)     not null,
    total_amount      numeric(19, 2) not null default 0,
    receipt_count     integer        not null default 0,
    status            varchar(20)    not null
        check (status in ('PREPARED', 'DEPOSITED', 'CANCELLED')),
    deposited_on      date,
    deposited_by      varchar(50),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_deposit_slip_no unique (company_id, slip_no)
);
create index ix_deposit_slip_bank on rcv_deposit_slip (company_id, bank_account_code, slip_date);

create table rcv_receipt (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    branch_id           bigint         not null references org_branch (id),
    receipt_no          varchar(40)    not null,
    receipt_date        date           not null,
    payer_type          varchar(20)    not null
        check (payer_type in ('POLICYHOLDER', 'INTERMEDIARY', 'REINSURER', 'OTHER')),
    party_id            bigint references pty_party (id),
    party_code          varchar(30),
    payer_name          varchar(200)   not null,
    department          varchar(20),
    mode                varchar(20)    not null
        check (mode in ('CASH', 'CHEQUE', 'BANK_TRANSFER', 'CARD', 'PDC')),
    instrument_no       varchar(40),
    instrument_date     date,
    drawee_bank         varchar(120),
    currency            varchar(3)     not null,
    exchange_rate       numeric(19, 8) not null,
    amount              numeric(19, 2) not null check (amount > 0),
    base_amount         numeric(19, 2) not null check (base_amount >= 0),
    applied_amount      numeric(19, 2) not null default 0,
    bank_account_code   varchar(30)    not null,
    income_account_code varchar(30),
    allocation_method   varchar(10)    not null check (allocation_method in ('MANUAL', 'FIFO', 'NONE')),
    narration           varchar(250),
    status              varchar(20)    not null
        check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'BOUNCED')),
    approved_by         varchar(50),
    approved_at         timestamptz,
    journal_batch_no    varchar(40),
    credit_item_id      bigint references sl_open_item (id),
    reversal_date       date,
    reversal_reason     varchar(200),
    reversed_by         varchar(50),
    deposit_status      varchar(20)    not null
        check (deposit_status in ('NOT_REQUIRED', 'UNDEPOSITED', 'IN_SLIP', 'DEPOSITED')),
    deposit_slip_id     bigint references rcv_deposit_slip (id),
    deposited_on        date,
    pdc_id              bigint,
    application_count   integer        not null default 0,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_receipt_no unique (company_id, receipt_no),
    constraint ck_receipt_applied check (applied_amount >= 0 and applied_amount <= amount),
    constraint ck_receipt_party check (payer_type = 'OTHER' or party_id is not null),
    constraint ck_receipt_income check (payer_type <> 'OTHER' or income_account_code is not null)
);
create index ix_receipt_date on rcv_receipt (company_id, receipt_date);
create index ix_receipt_party on rcv_receipt (company_id, party_id);
create index ix_receipt_status on rcv_receipt (company_id, status);
create index ix_receipt_deposit on rcv_receipt (company_id, bank_account_code, deposit_status);
create index ix_receipt_slip on rcv_receipt (deposit_slip_id);

create table rcv_receipt_allocation (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    receipt_id    bigint         not null references rcv_receipt (id),
    debit_item_id bigint         not null references sl_open_item (id),
    document_no   varchar(40)    not null,
    amount        numeric(19, 2) not null check (amount > 0),
    match_id      bigint,
    applied_on    date,
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create index ix_allocation_receipt on rcv_receipt_allocation (receipt_id);
create index ix_rcv_allocation_item on rcv_receipt_allocation (debit_item_id);

create table rcv_pdc (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    pdc_no            varchar(40)    not null,
    received_date     date           not null,
    party_id          bigint         not null references pty_party (id),
    party_code        varchar(30)    not null,
    payer_name        varchar(200)   not null,
    department        varchar(20),
    cheque_no         varchar(40)    not null,
    cheque_date       date           not null,
    drawee_bank       varchar(120)   not null,
    currency          varchar(3)     not null,
    exchange_rate     numeric(19, 8) not null,
    amount            numeric(19, 2) not null check (amount > 0),
    base_amount       numeric(19, 2) not null check (base_amount >= 0),
    bank_account_code varchar(30)    not null,
    debit_item_id     bigint references sl_open_item (id),
    narration         varchar(250),
    status            varchar(20)    not null
        check (status in ('ON_HAND', 'DUE', 'DEPOSITED', 'CLEARED', 'BOUNCED', 'RETURNED', 'REPLACED')),
    status_date       date           not null,
    receipt_id        bigint references rcv_receipt (id),
    replaced_by_id    bigint references rcv_pdc (id),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_pdc_no unique (company_id, pdc_no),
    constraint ck_pdc_cheque_date check (cheque_date >= received_date)
);
create index ix_pdc_status on rcv_pdc (company_id, status, cheque_date);
create index ix_pdc_party on rcv_pdc (company_id, party_id);
alter table rcv_receipt add constraint fk_receipt_pdc foreign key (pdc_id) references rcv_pdc (id);

create table rcv_pdc_event (
    id          bigint generated by default as identity primary key,
    version     bigint       not null default 0,
    pdc_id      bigint       not null references rcv_pdc (id),
    from_status varchar(20),
    to_status   varchar(20)  not null,
    event_date  date         not null,
    remarks     varchar(250),
    receipt_no  varchar(40),
    created_at  timestamptz  not null,
    created_by  varchar(50)  not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create index ix_rcv_pdc_event_pdc on rcv_pdc_event (pdc_id, event_date);

create table brs_statement (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    bank_account_code varchar(30)    not null,
    statement_ref     varchar(60)    not null,
    period_from       date           not null,
    period_to         date           not null,
    opening_balance   numeric(19, 2) not null,
    closing_balance   numeric(19, 2) not null,
    total_debit       numeric(19, 2) not null,
    total_credit      numeric(19, 2) not null,
    line_count        integer        not null,
    file_name         varchar(200),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_statement_ref unique (company_id, bank_account_code, statement_ref),
    constraint ck_statement_period check (period_to >= period_from)
);
create index ix_statement_bank on brs_statement (company_id, bank_account_code, period_to);

create table brs_match (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    bank_account_code varchar(30)    not null,
    method            varchar(10)    not null check (method in ('AUTO', 'MANUAL')),
    match_date        date           not null,
    amount            numeric(19, 2) not null,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create index ix_brs_match_bank on brs_match (company_id, bank_account_code, match_date);

create table brs_statement_line (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    statement_id      bigint         not null references brs_statement (id),
    company_id        bigint         not null references org_company (id),
    bank_account_code varchar(30)    not null,
    line_no           integer        not null,
    value_date        date           not null,
    description       varchar(250),
    reference         varchar(60),
    debit             numeric(19, 2) not null default 0 check (debit >= 0),
    credit            numeric(19, 2) not null default 0 check (credit >= 0),
    balance           numeric(19, 2) not null,
    match_id          bigint references brs_match (id),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_statement_line unique (statement_id, line_no),
    constraint ck_statement_line_amount check ((debit > 0 and credit = 0) or (credit > 0 and debit = 0))
);
create index ix_statement_line_bank on brs_statement_line (company_id, bank_account_code, value_date);
create index ix_statement_line_match on brs_statement_line (match_id);

-- Book (ledger) side of a match; a ledger entry can be reconciled only once.
create table brs_match_book (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    match_id        bigint         not null references brs_match (id),
    ledger_entry_id bigint         not null references gl_ledger_entry (id),
    amount          numeric(19, 2) not null,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_match_book_entry unique (ledger_entry_id)
);
create index ix_match_book_match on brs_match_book (match_id);

create table brs_reconciliation (
    id                       bigint generated by default as identity primary key,
    version                  bigint         not null default 0,
    company_id               bigint         not null references org_company (id),
    bank_account_code        varchar(30)    not null,
    as_of_date               date           not null,
    book_balance             numeric(19, 2) not null,
    book_debits_not_in_bank  numeric(19, 2) not null,
    book_credits_not_in_bank numeric(19, 2) not null,
    bank_debits_not_in_book  numeric(19, 2) not null,
    bank_credits_not_in_book numeric(19, 2) not null,
    computed_bank_balance    numeric(19, 2) not null,
    statement_balance        numeric(19, 2) not null,
    difference               numeric(19, 2) not null,
    status                   varchar(20)    not null check (status in ('IN_PROGRESS', 'FINALIZED')),
    finalized_by             varchar(50),
    finalized_at             timestamptz,
    created_at               timestamptz    not null,
    created_by               varchar(50)    not null,
    updated_at               timestamptz,
    updated_by               varchar(50),
    constraint uq_reconciliation unique (company_id, bank_account_code, as_of_date)
);

-- Applying money previously held on account (unapplied collections) to a debit note.
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('UNAPPLIED_APPLICATION', 'Application of unapplied collection', 'RECEIPT', 'RECEIPT',
  'Money held on account (premium deposit) applied to a debit note of the payer', 'AMOUNT');
