-- =====================================================================================
-- iNXT BrokerVerse - V551 Bank statement layouts and matching rules (BRD-5 FRBS 3.3.x,
-- wave A1-GL).
--   FRBS 3.3.1  an .xlsx / .ods statement of cash-in-bank transactions is imported with the
--               column mapping of its bank account and triggers the auto reconciliation, AQ08;
--   FRBS 3.3.2  matching rules per bank account: CHECK_NO_AND_AMOUNT (exact cheque number and
--               amount) runs before the standard rules.
-- Bank accounts are referenced by their GL account code, as bank statements are.
-- =====================================================================================
create table brs_statement_layout (
    id                 bigint generated by default as identity primary key,
    version            bigint       not null default 0,
    company_id         bigint       not null references org_company (id),
    bank_account_code  varchar(30)  not null,
    name               varchar(120) not null,
    date_column        varchar(60)  not null,
    description_column varchar(60),
    reference_column   varchar(60),
    debit_column       varchar(60),
    credit_column      varchar(60),
    amount_column      varchar(60),
    balance_column     varchar(60),
    date_pattern       varchar(20)  not null default 'yyyy-MM-dd',
    created_at         timestamptz  not null,
    created_by         varchar(50)  not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_brs_statement_layout unique (company_id, bank_account_code),
    constraint ck_brs_layout_amounts check (amount_column is not null
        or (debit_column is not null and credit_column is not null))
);

create table brs_match_rule (
    id                bigint generated by default as identity primary key,
    version           bigint       not null default 0,
    company_id        bigint       not null references org_company (id),
    bank_account_code varchar(30)  not null,
    rule_code         varchar(30)  not null,
    priority          integer      not null,
    active            boolean      not null default true,
    created_at        timestamptz  not null,
    created_by        varchar(50)  not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_brs_match_rule unique (company_id, bank_account_code, rule_code),
    constraint ck_brs_match_rule_code check (rule_code in ('CHECK_NO_AND_AMOUNT', 'STANDARD'))
);
