-- =====================================================================================
-- iNXT BrokerVerse - V600 Budgets, inter-company relationships/transactions and consolidation.
-- =====================================================================================

-- ---------- Budgets ------------------------------------------------------------------
create table bud_budget (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    company_id       bigint       not null references org_company (id),
    fiscal_year      integer      not null,
    version_no       integer      not null,
    version_type     varchar(10)  not null,
    name             varchar(120) not null,
    currency         varchar(3)   not null,
    status           varchar(20)  not null,
    based_on_id      bigint references bud_budget (id),
    submitted_by     varchar(50),
    submitted_at     timestamptz,
    approved_by      varchar(50),
    approved_at      timestamptz,
    rejection_reason varchar(200),
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_budget_version unique (company_id, fiscal_year, version_no),
    constraint ck_budget_type check (version_type in ('ORIGINAL', 'REVISED')),
    constraint ck_budget_status check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'SUPERSEDED'))
);
create index ix_budget_company_year on bud_budget (company_id, fiscal_year, status);

create table bud_budget_line (
    id           bigint generated by default as identity primary key,
    budget_id    bigint      not null references bud_budget (id),
    account_id   bigint      not null references coa_account (id),
    account_code varchar(30) not null,
    cost_center  varchar(20)
);
create index ix_budget_line_budget on bud_budget_line (budget_id);
create unique index uq_budget_line_key on bud_budget_line (budget_id, account_code, coalesce(cost_center, ''));

-- Monthly amounts (period 1..12 of the fiscal year), natural sign (income and expense positive).
create table bud_budget_amount (
    line_id   bigint         not null references bud_budget_line (id),
    period_no integer        not null check (period_no between 1 and 12),
    amount    numeric(19, 2) not null,
    primary key (line_id, period_no)
);

-- ---------- Inter-company ---------------------------------------------------------------
-- One row per company pair: the due-from / due-to accounts each company uses for the other.
create table ic_relationship (
    id                 bigint generated by default as identity primary key,
    version            bigint      not null default 0,
    company_a_id       bigint      not null references org_company (id),
    company_b_id       bigint      not null references org_company (id),
    a_due_from_account varchar(30) not null,
    a_due_to_account   varchar(30) not null,
    b_due_from_account varchar(30) not null,
    b_due_to_account   varchar(30) not null,
    active             boolean     not null default true,
    created_at         timestamptz not null,
    created_by         varchar(50) not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_ic_pair unique (company_a_id, company_b_id),
    constraint ck_ic_pair check (company_a_id <> company_b_id)
);

create table ic_transaction (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    ic_reference         varchar(40)    not null unique,
    relationship_id      bigint         not null references ic_relationship (id),
    transaction_type     varchar(12)    not null,
    creditor_company_id  bigint         not null references org_company (id),
    debtor_company_id    bigint         not null references org_company (id),
    value_date           date           not null,
    currency             varchar(3)     not null,
    amount               numeric(19, 2) not null check (amount > 0),
    creditor_account     varchar(30)    not null,
    debtor_account       varchar(30)    not null,
    narration            varchar(250)   not null,
    creditor_batch_no    varchar(40)    not null,
    debtor_batch_no      varchar(40)    not null,
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_ic_type check (transaction_type in ('CHARGE', 'SETTLEMENT'))
);
create index ix_ic_txn_relationship on ic_transaction (relationship_id, value_date);

-- ---------- Consolidation ---------------------------------------------------------------
create table con_group (
    id                     bigint generated by default as identity primary key,
    version                bigint       not null default 0,
    code                   varchar(20)  not null unique,
    name                   varchar(150) not null,
    parent_company_id      bigint       not null references org_company (id),
    currency               varchar(3)   not null,
    cta_account            varchar(30)  not null,
    nci_account            varchar(30)  not null,
    goodwill_account       varchar(30)  not null,
    active                 boolean      not null default true,
    created_at             timestamptz  not null,
    created_by             varchar(50)  not null,
    updated_at             timestamptz,
    updated_by             varchar(50)
);

create table con_group_member (
    id                  bigint generated by default as identity primary key,
    group_id            bigint        not null references con_group (id),
    company_id          bigint        not null references org_company (id),
    ownership_pct       numeric(7, 4) not null check (ownership_pct > 0 and ownership_pct <= 100),
    investment_account  varchar(30),
    equity_accounts     varchar(200),
    constraint uq_group_member unique (group_id, company_id)
);

create table con_run (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    group_id     bigint         not null references con_group (id),
    run_no       varchar(40)    not null unique,
    as_of_date   date           not null,
    currency     varchar(3)     not null,
    status       varchar(20)    not null,
    total_debit  numeric(19, 2) not null,
    total_credit numeric(19, 2) not null,
    finalized_by varchar(50),
    finalized_at timestamptz,
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_con_run_status check (status in ('DRAFT', 'FINAL', 'CANCELLED'))
);
create index ix_con_run_group on con_run (group_id, as_of_date, status);

create table con_run_line (
    id            bigint generated by default as identity primary key,
    run_id        bigint         not null references con_run (id),
    line_no       integer        not null,
    line_type     varchar(20)    not null,
    rule_code     varchar(30),
    company_id    bigint references org_company (id),
    account_code  varchar(30)    not null,
    account_name  varchar(150)   not null,
    account_class varchar(20)    not null,
    local_amount  numeric(19, 2) not null,
    rate          numeric(19, 8) not null,
    amount        numeric(19, 2) not null,
    description   varchar(250),
    constraint uq_con_run_line unique (run_id, line_no),
    constraint ck_con_line_type check (line_type in ('TRANSLATED', 'CTA', 'ELIMINATION'))
);
create index ix_con_run_line_run on con_run_line (run_id);

-- ---------- Permissions -----------------------------------------------------------------
-- Accountants prepare budgets (maker); finance managers approve them (checker).
insert into sec_role_permission (role_id, permission)
select id, 'BUDGET_MANAGE' from sec_role where code = 'ACCOUNTANT'
on conflict do nothing;
