-- =====================================================================================
-- iNXT FinVerse - V650 Finance / MIS reports support objects
-- Financial Statement Format master used by the MIS Balance Sheet and Income & Expense
-- statements (FIN-MIS-*). A built-in format "STANDARD" (derived from account report groups)
-- is always available and needs no rows here; client specific formats map GL account code
-- ranges to numbered statement lines with schedule references.
-- =====================================================================================

create table fin_statement_format (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    code           varchar(20)  not null,
    description    varchar(120) not null,
    statement_type varchar(2)   not null check (statement_type in ('BS', 'IE')),
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_fin_format unique (company_id, code)
);

create table fin_statement_format_line (
    id           bigint generated by default as identity primary key,
    format_id    bigint       not null references fin_statement_format (id),
    line_no      integer      not null,
    caption      varchar(150) not null,
    line_type    varchar(10)  not null check (line_type in ('HEADING', 'ACCOUNTS', 'RESULT', 'TOTAL')),
    schedule_ref varchar(10),
    account_from varchar(30),
    account_to   varchar(30),
    sign         smallint     not null default 1 check (sign in (1, -1)),
    total_terms  varchar(200),
    constraint uq_fin_format_line unique (format_id, line_no),
    constraint ck_fin_format_accounts
        check (line_type <> 'ACCOUNTS' or (account_from is not null and account_to is not null)),
    constraint ck_fin_format_total check (line_type <> 'TOTAL' or total_terms is not null)
);

-- Voucher listings, day books and the missing voucher number list scan batches by date.
create index ix_batch_company_date on jnl_batch (company_id, value_date, batch_no);
-- Sub-ledger (party) ledgers read party postings by date.
create index ix_ledger_party_date on gl_ledger_entry (company_id, party_code, value_date)
    where party_code is not null;
