-- =====================================================================================
-- iNXT BrokerVerse - V652 Account schedule engine (finreport, BRD-5 wave A1-FRBS)
--   FRBS 3.2.0, Appendix A II-IV (GARD bank-format schedules, subsidiaries accounting, schedules
--   and aging); BDOI report list #9, #45, #46 (docs/requirements/BDOI_REPORT_LIST.md);
--   docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md sections 10 and 12.1.
--
--   * fin_schedule_def       one definition per schedule: the accounts (code prefixes or report
--                            groups), the grouping (account, party, document, cost centre, branch,
--                            business line), the currency, the natural side, the basis (balance or
--                            period movement), optional ageing (up to 8 buckets), a comparative
--                            period (previous month / previous year) and a commentary column
--   * fin_schedule_column    the measures shown, in order
--   * fin_statement_comment  commentary per company, schedule, month and row (variance analysis
--                            with commentary, Appendix A II-45)
--
-- The definitions below are drafts: BDOI has given titles only, so every layout is TO_CONFIRM
-- (AQ05) and the account selectors point at the demo chart until FRBS uploads the real chart
-- (FRBS 2.3.1, AQ01). They are configuration, maintained on the Account Schedules screen; no code
-- refers to an account code. No foreign key to broking tables (design section 4).
-- =====================================================================================

create table fin_schedule_def (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    code             varchar(40)   not null,
    name             varchar(200)  not null,
    family           varchar(20)   not null
        constraint fin_ck_schedule_family check (family in ('GARD', 'SUBSIDIARIES', 'SCHEDULE',
            'AGING', 'OTHER')),
    source_ref       varchar(80),
    description      varchar(500),
    selector_kind    varchar(20)   not null
        constraint fin_ck_schedule_selector check (selector_kind in ('ACCOUNT_PREFIX', 'REPORT_GROUP')),
    account_selector varchar(500)  not null,
    grouping_key     varchar(20)   not null
        constraint fin_ck_schedule_grouping check (grouping_key in ('ACCOUNT', 'PARTY', 'DOCUMENT',
            'COST_CENTER', 'BRANCH', 'BUSINESS_LINE')),
    currency         varchar(3),
    balance_side     varchar(6)    not null
        constraint fin_ck_schedule_side check (balance_side in ('DEBIT', 'CREDIT')),
    basis            varchar(10)   not null
        constraint fin_ck_schedule_basis check (basis in ('BALANCE', 'MOVEMENT')),
    ageing           boolean       not null default false,
    ageing_slots     varchar(60),
    comparative      varchar(20)   not null default 'NONE'
        constraint fin_ck_schedule_comparative check (comparative in ('NONE', 'PREVIOUS_MONTH',
            'PREVIOUS_YEAR')),
    commentary       boolean       not null default false,
    board_document   boolean       not null default false,
    layout_status    varchar(20)   not null default 'TO_CONFIRM'
        constraint fin_ck_schedule_layout check (layout_status in ('TO_CONFIRM', 'CONFIRMED')),
    active           boolean       not null default true,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint fin_uq_schedule_code unique (code),
    constraint fin_ck_schedule_ageing check (not ageing or ageing_slots is not null),
    constraint fin_ck_schedule_ageing_basis check (not ageing or basis = 'BALANCE')
);

create table fin_schedule_column (
    id          bigint generated by default as identity primary key,
    schedule_id bigint       not null references fin_schedule_def (id) on delete cascade,
    seq         integer      not null,
    measure     varchar(20)  not null
        constraint fin_ck_schedule_measure check (measure in ('OPENING', 'DEBITS', 'CREDITS',
            'MOVEMENT', 'CLOSING', 'COMPARATIVE', 'VARIANCE', 'VARIANCE_PCT')),
    label       varchar(60)  not null,
    constraint fin_uq_schedule_column unique (schedule_id, measure)
);
create index ix_fin_schedule_column on fin_schedule_column (schedule_id, seq);

create table fin_statement_comment (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    schedule_code varchar(40)   not null,
    period        varchar(7)    not null
        constraint fin_ck_comment_period check (period ~ '^[0-9]{4}-[0-9]{2}$'),
    row_key       varchar(120)  not null,
    comment_text  varchar(1000) not null,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint fin_uq_statement_comment unique (company_id, schedule_code, period, row_key)
);

-- ---------- Draft definitions of the BDOI report pack (layouts to confirm, AQ05) ----------------
create temporary table fin_schedule_seed (
    code varchar(40), name varchar(200), family varchar(20), source_ref varchar(80),
    selector varchar(500), grouping_key varchar(20), currency varchar(3), side varchar(6),
    basis varchar(10), slots varchar(60), comparative varchar(20), commentary boolean,
    board boolean, measures varchar(200), seq integer
) on commit drop;

insert into fin_schedule_seed values
 -- II. GARD - BDO Unibank bank format (schedules 3-45)
 ('GARD-CASH', 'Schedule of Cash and Cash Equivalents', 'GARD', 'App. A II (cash)', '11',
  'ACCOUNT', null, 'DEBIT', 'BALANCE', null, 'NONE', false, true, 'OPENING,DEBITS,CREDITS,CLOSING', 1),
 ('GARD-OPEX', 'Schedule of Operating Expenses', 'GARD', 'App. A II (operating expenses)', '56',
  'ACCOUNT', null, 'DEBIT', 'MOVEMENT', null, 'NONE', false, true, 'MOVEMENT,CLOSING', 2),
 ('GARD-OTHER-INCOME', 'Schedule of Other Income', 'GARD', 'App. A II (other income)',
  '4110,4120,4130,4131,47', 'ACCOUNT', null, 'CREDIT', 'MOVEMENT', null, 'NONE', false, true,
  'MOVEMENT,CLOSING', 3),
 ('GARD-FX', 'Schedule of Foreign Exchange Gain / (Loss)', 'GARD', 'App. A II (FX gain / loss)',
  '46', 'ACCOUNT', null, 'CREDIT', 'MOVEMENT', null, 'NONE', false, true, 'MOVEMENT,CLOSING', 4),
 ('GARD-MISC-ASSETS', 'Schedule of Miscellaneous Assets', 'GARD', 'App. A II (misc. assets)', '16',
  'ACCOUNT', null, 'DEBIT', 'BALANCE', null, 'NONE', false, true, 'OPENING,DEBITS,CREDITS,CLOSING', 5),
 ('GARD-ACCRUED', 'Schedule of Accrued Expenses and Taxes Payable', 'GARD',
  'App. A II (accrued expenses and taxes)', '2502,2503,2504,2505,2506,2507,2508,2509', 'ACCOUNT',
  null, 'CREDIT', 'BALANCE', null, 'NONE', false, true, 'OPENING,DEBITS,CREDITS,CLOSING', 6),
 ('GARD-VARIANCE-SIE', 'Variance Analysis - Statement of Income and Expenses (Month on Month)',
  'GARD', 'App. A II-45', '4,5', 'ACCOUNT', null, 'CREDIT', 'MOVEMENT', null, 'PREVIOUS_MONTH',
  true, true, 'MOVEMENT,COMPARATIVE,VARIANCE,VARIANCE_PCT', 7),
 -- III. Subsidiaries accounting
 ('SUBS-SIE-YOY', 'FS Analysis - Statement of Income and Expenses (Year on Year)', 'SUBSIDIARIES',
  'App. A III (FS analysis SIE)', '4,5', 'ACCOUNT', null, 'CREDIT', 'BALANCE', null,
  'PREVIOUS_YEAR', true, true, 'CLOSING,COMPARATIVE,VARIANCE,VARIANCE_PCT', 8),
 ('SUBS-SOC-MOM', 'FS Analysis - Statement of Condition (Month on Month)', 'SUBSIDIARIES',
  'App. A III (FS analysis SOC)', '1,2,3', 'ACCOUNT', null, 'DEBIT', 'BALANCE', null,
  'PREVIOUS_MONTH', true, true, 'CLOSING,COMPARATIVE,VARIANCE,VARIANCE_PCT', 9),
 -- IV. Schedules and aging
 ('SCH-COMMISSION-INCOME', 'Schedule of Commission Income', 'SCHEDULE', 'App. A IV; report list #9',
  '4101,44', 'ACCOUNT', null, 'CREDIT', 'MOVEMENT', null, 'NONE', false, false, 'MOVEMENT,CLOSING', 10),
 ('SCH-PR-PHP', 'Schedule of Receivable from Insurance Companies Clients - Peso', 'AGING',
  'App. C; report list #45', '1210', 'PARTY', 'PHP', 'DEBIT', 'BALANCE', '30,90,180,365,730',
  'NONE', false, false, 'CLOSING', 11),
 ('SCH-PR-USD', 'Schedule of Receivable from Insurance Companies Clients - USD', 'AGING',
  'App. C; report list #46', '1210', 'PARTY', 'USD', 'DEBIT', 'BALANCE', '30,90,180,365,730',
  'NONE', false, false, 'CLOSING', 12),
 ('SCH-PR-2307', 'Schedule of Premiums Receivable 2307', 'AGING', 'App. A IV-32', '1211', 'PARTY',
  null, 'DEBIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false, 'CLOSING', 13),
 ('SCH-COMM-RECEIVABLE', 'Schedule of Commission Receivables', 'AGING', 'App. A IV; App. C', '1220',
  'PARTY', null, 'DEBIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false, 'CLOSING', 14),
 ('SCH-AR-BIR', 'Schedule of AR-BIR (Tax Credit, on Commission, on Incentives, on Hand)', 'SCHEDULE',
  'App. A IV-6 to IV-8', '1602,1610,1611,1612', 'ACCOUNT', null, 'DEBIT', 'BALANCE', null, 'NONE',
  false, false, 'OPENING,DEBITS,CREDITS,CLOSING', 15),
 ('SCH-AR-BIR-INSURER', 'Schedule of AR-BIR per Insurer', 'AGING', 'App. A IV (BIR per insurer)',
  '1610,1611', 'PARTY', null, 'DEBIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false,
  'CLOSING', 16),
 ('SCH-AR-INSURER-REFUND', 'Schedule of AR Insurer''s Refund', 'AGING', 'App. C', '1225', 'PARTY',
  null, 'DEBIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false, 'CLOSING', 17),
 ('SCH-AR-OFFICERS', 'Schedule of AR Officers and Employees (Advances)', 'AGING',
  'App. A IV (AR officers)', '1604', 'PARTY', null, 'DEBIT', 'BALANCE', '30,90,180,365,730', 'NONE',
  false, false, 'CLOSING', 18),
 ('SCH-PREPAID', 'Schedule of Prepaid Expenses', 'SCHEDULE', 'App. A IV (prepaid)', '1601', 'ACCOUNT',
  null, 'DEBIT', 'BALANCE', null, 'NONE', false, false, 'OPENING,DEBITS,CREDITS,CLOSING', 19),
 ('SCH-FFE', 'Schedule of Furniture, Fixtures and Equipment', 'SCHEDULE', 'App. A IV (FFE)', '17',
  'ACCOUNT', null, 'DEBIT', 'BALANCE', null, 'NONE', false, false, 'OPENING,DEBITS,CREDITS,CLOSING', 20),
 ('SCH-PAY-INSURERS', 'Schedule of Payable to Insurance Companies', 'AGING', 'App. C',
  '2210,2211', 'PARTY', null, 'CREDIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false,
  'CLOSING', 21),
 ('SCH-AP-REFUND-INS', 'Schedule of A/P Refund from Insurer', 'AGING', 'App. C', '2217', 'PARTY',
  null, 'CREDIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false, 'CLOSING', 22),
 ('SCH-AP-OTHERS', 'Schedule of AP - Others Current', 'AGING', 'App. A IV-18/19',
  '2205,2215,2216', 'PARTY', null, 'CREDIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false,
  'CLOSING', 23),
 ('SCH-AP-OFFICERS', 'Schedule of AP - Officers and Employees', 'AGING', 'App. A IV (AP officers)',
  '2260', 'PARTY', null, 'CREDIT', 'BALANCE', '30,90,180,365,730', 'NONE', false, false, 'CLOSING', 24),
 ('SCH-STALE-CHECKS', 'Schedule of Miscellaneous Liability - Stale Checks', 'AGING',
  'App. B; DIS 3.27.1', '2240', 'PARTY', null, 'CREDIT', 'BALANCE', '30,90,180,365,730', 'NONE',
  false, false, 'CLOSING', 25),
 ('SCH-CHECKS-OUTSTANDING', 'Schedule of Checks and Other Cash Items (Outstanding Checks)', 'AGING',
  'App. A IV (checks and other cash items)', '2241', 'DOCUMENT', null, 'CREDIT', 'BALANCE',
  '30,60,90,120,150,180,365', 'NONE', false, false, 'CLOSING', 26),
 ('SCH-SERVICE-FEE-PAYABLE', 'Schedule of Service Fee Payable', 'SCHEDULE', 'App. A VI; FRBS 2.10',
  '2250', 'PARTY', null, 'CREDIT', 'BALANCE', null, 'NONE', false, false,
  'OPENING,DEBITS,CREDITS,CLOSING', 27),
 ('SCH-EXPENSE-CC', 'Schedule of Expenses per Cost Centre', 'SCHEDULE',
  'App. A IV (expense grouping); report list #10', '5', 'COST_CENTER', null, 'DEBIT', 'MOVEMENT',
  null, 'NONE', false, false, 'MOVEMENT,CLOSING', 28);

insert into fin_schedule_def (code, name, family, source_ref, description, selector_kind,
    account_selector, grouping_key, currency, balance_side, basis, ageing, ageing_slots, comparative,
    commentary, board_document, layout_status, active, created_at, created_by)
select s.code, s.name, s.family, s.source_ref,
       'Draft definition seeded from the BDOI report pack; layout to confirm with FRBS (AQ05).',
       'ACCOUNT_PREFIX', s.selector, s.grouping_key, s.currency, s.side, s.basis, s.slots is not null,
       s.slots, s.comparative, s.commentary, s.board, 'TO_CONFIRM', true, now(), 'SYSTEM'
from fin_schedule_seed s
order by s.seq;

insert into fin_schedule_column (schedule_id, seq, measure, label)
select d.id, m.ord * 10, m.measure,
       case m.measure
           when 'OPENING' then 'Opening balance'
           when 'DEBITS' then 'Debits'
           when 'CREDITS' then 'Credits'
           when 'MOVEMENT' then case when s.basis = 'MOVEMENT' then 'This period' else 'Movement' end
           when 'CLOSING' then case when s.basis = 'MOVEMENT' then 'Year to date' else 'Balance' end
           when 'COMPARATIVE' then case s.comparative when 'PREVIOUS_YEAR' then 'Previous year'
                                                      else 'Previous month' end
           when 'VARIANCE' then 'Variance'
           else 'Variance %'
       end
from fin_schedule_seed s
join fin_schedule_def d on d.code = s.code
cross join lateral unnest(string_to_array(s.measures, ',')) with ordinality as m(measure, ord);
