-- =====================================================================================
-- iNXT BrokerVerse - V660 Fixed assets: categories, asset register, movements (additions,
-- disposals, inter-branch transfers) and monthly depreciation runs.
-- GL accounts are configured per category; postings go through the accounting engine.
-- =====================================================================================

create table fa_category (
    id                               bigint generated by default as identity primary key,
    version                          bigint        not null default 0,
    company_id                       bigint        not null references org_company (id),
    code                             varchar(20)   not null,
    name                             varchar(120)  not null,
    asset_account                    varchar(30)   not null,
    accumulated_depreciation_account varchar(30)   not null,
    depreciation_expense_account     varchar(30)   not null,
    depreciation_method              varchar(20)   not null
        check (depreciation_method in ('STRAIGHT_LINE', 'DECLINING_BALANCE')),
    useful_life_months               integer       not null check (useful_life_months > 0),
    residual_percent                 numeric(7, 4) not null default 0
        check (residual_percent >= 0 and residual_percent < 100),
    record_status                    varchar(30)   not null,
    authorized_by                    varchar(50),
    authorized_at                    timestamptz,
    created_at                       timestamptz   not null,
    created_by                       varchar(50)   not null,
    updated_at                       timestamptz,
    updated_by                       varchar(50),
    constraint uq_fa_category unique (company_id, code)
);

create table fa_asset (
    id                               bigint generated by default as identity primary key,
    version                          bigint         not null default 0,
    company_id                       bigint         not null references org_company (id),
    branch_id                        bigint         not null references org_branch (id),
    category_id                      bigint         not null references fa_category (id),
    tag_no                           varchar(30)    not null,
    description                      varchar(200)   not null,
    cost_center                      varchar(20),
    supplier_code                    varchar(30),
    acquisition_date                 date           not null,
    acquisition_cost                 numeric(19, 2) not null check (acquisition_cost > 0),
    residual_value                   numeric(19, 2) not null default 0 check (residual_value >= 0),
    depreciation_method              varchar(20)    not null
        check (depreciation_method in ('STRAIGHT_LINE', 'DECLINING_BALANCE')),
    useful_life_months               integer        not null check (useful_life_months > 0),
    location                         varchar(120),
    custodian                        varchar(120),
    settlement_account               varchar(30),
    take_on                          boolean        not null default false,
    capitalization_date              date           not null,
    opening_accumulated_depreciation numeric(19, 2) not null default 0,
    opening_months                   integer        not null default 0,
    accumulated_depreciation         numeric(19, 2) not null default 0,
    months_depreciated               integer        not null default 0,
    last_depreciation_period         varchar(7),
    status                           varchar(30)    not null
        check (status in ('PENDING_CAPITALIZATION', 'ACTIVE', 'FULLY_DEPRECIATED', 'DISPOSED', 'TRANSFERRED')),
    capitalization_batch_no          varchar(40),
    disposal_date                    date,
    record_status                    varchar(30)    not null,
    authorized_by                    varchar(50),
    authorized_at                    timestamptz,
    created_at                       timestamptz    not null,
    created_by                       varchar(50)    not null,
    updated_at                       timestamptz,
    updated_by                       varchar(50),
    constraint uq_fa_asset_tag unique (company_id, tag_no),
    constraint ck_fa_residual check (residual_value < acquisition_cost),
    constraint ck_fa_accumulated check (accumulated_depreciation >= 0
        and accumulated_depreciation <= acquisition_cost)
);
create index ix_fa_asset_category on fa_asset (company_id, category_id);
create index ix_fa_asset_branch on fa_asset (company_id, branch_id, status);

create table fa_movement (
    id                       bigint generated by default as identity primary key,
    version                  bigint         not null default 0,
    company_id               bigint         not null references org_company (id),
    asset_id                 bigint         not null references fa_asset (id),
    movement_type            varchar(20)    not null check (movement_type in ('ADDITION', 'DISPOSAL', 'TRANSFER')),
    movement_date            date           not null,
    from_branch_id           bigint references org_branch (id),
    to_branch_id             bigint references org_branch (id),
    cost                     numeric(19, 2) not null,
    accumulated_depreciation numeric(19, 2) not null,
    net_book_value           numeric(19, 2) not null,
    proceeds                 numeric(19, 2) not null default 0,
    gain_loss                numeric(19, 2) not null default 0,
    reference                varchar(60),
    remarks                  varchar(250),
    batch_no                 varchar(40),
    created_at               timestamptz    not null,
    created_by               varchar(50)    not null,
    updated_at               timestamptz,
    updated_by               varchar(50)
);
create index ix_fa_movement_date on fa_movement (company_id, movement_date);
create index ix_fa_movement_asset on fa_movement (asset_id);

create table fa_depreciation_run (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    period             varchar(7)     not null,
    period_end         date           not null,
    asset_count        integer        not null,
    total_depreciation numeric(19, 2) not null,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_fa_run_period unique (company_id, period)
);

create table fa_depreciation_line (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    run_id               bigint         not null references fa_depreciation_run (id),
    asset_id             bigint         not null references fa_asset (id),
    branch_id            bigint         not null references org_branch (id),
    months               integer        not null check (months > 0),
    amount               numeric(19, 2) not null check (amount > 0),
    accumulated_after    numeric(19, 2) not null,
    net_book_value_after numeric(19, 2) not null,
    batch_no             varchar(40),
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50)
);
create index ix_fa_line_run on fa_depreciation_line (run_id);
create index ix_fa_line_asset on fa_depreciation_line (asset_id);

-- Accounting events. "@ROLE" accounts come from the asset category (ASSET, ACCUM_DEPRECIATION,
-- DEPRECIATION_EXPENSE) or the transaction (SETTLEMENT = bank or supplier payable, BANK).
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('ASSET_ACQUISITION', 'Fixed asset capitalized', 'PAYMENT', 'PAYMENT',
  'Asset capitalized at cost (roles ASSET, SETTLEMENT = bank or supplier payable)', 'COST'),
 ('ASSET_TAKE_ON', 'Fixed asset opening balance', 'PROVISION', 'OPENING',
  'Existing asset taken on with its accumulated depreciation (roles ASSET, ACCUM_DEPRECIATION)',
  'COST,ACCUMULATED_DEPRECIATION,NET_BOOK_VALUE'),
 ('ASSET_DEPRECIATION', 'Monthly depreciation', 'PROVISION', 'PROVISION',
  'Depreciation charge of a period (roles DEPRECIATION_EXPENSE, ACCUM_DEPRECIATION)', 'DEPRECIATION'),
 ('ASSET_DISPOSAL', 'Fixed asset disposal', 'RECEIPT', 'RECEIPT',
  'Derecognition with sale proceeds and gain or loss (roles ASSET, ACCUM_DEPRECIATION, BANK)',
  'COST,ACCUMULATED_DEPRECIATION,PROCEEDS,GAIN,LOSS'),
 ('ASSET_TRANSFER', 'Inter-branch asset transfer', 'PROVISION', 'PROVISION',
  'Receiving branch positive, sending branch negative amounts (roles ASSET, ACCUM_DEPRECIATION)',
  'COST,ACCUMULATED_DEPRECIATION,NET_BOOK_VALUE');
