-- =====================================================================================
-- iNXT FinVerse - V670 Investment portfolio: portfolios (classification + GL accounts),
-- holdings, month-end accrual / amortization runs and the holding transaction history.
-- =====================================================================================

create table inv_portfolio (
    id                       bigint generated by default as identity primary key,
    version                  bigint       not null default 0,
    company_id               bigint       not null references org_company (id),
    code                     varchar(20)  not null,
    name                     varchar(120) not null,
    classification           varchar(20)  not null
        check (classification in ('AMORTIZED_COST', 'FVOCI', 'FVPL')),
    investment_account       varchar(30)  not null,
    accrued_interest_account varchar(30)  not null,
    interest_income_account  varchar(30)  not null,
    realized_gain_account    varchar(30)  not null,
    fair_value_account       varchar(30),
    record_status            varchar(30)  not null,
    authorized_by            varchar(50),
    authorized_at            timestamptz,
    created_at               timestamptz  not null,
    created_by               varchar(50)  not null,
    updated_at               timestamptz,
    updated_by               varchar(50),
    constraint uq_inv_portfolio unique (company_id, code),
    constraint ck_inv_fair_value_account check (classification = 'AMORTIZED_COST' or fair_value_account is not null)
);

create table inv_holding (
    id                    bigint generated by default as identity primary key,
    version               bigint         not null default 0,
    company_id            bigint         not null references org_company (id),
    branch_id             bigint         not null references org_branch (id),
    portfolio_id          bigint         not null references inv_portfolio (id),
    holding_no            varchar(40)    not null,
    instrument_type       varchar(20)    not null
        check (instrument_type in ('TIME_DEPOSIT', 'TREASURY_BILL', 'GOVERNMENT_BOND', 'CORPORATE_BOND', 'EQUITY')),
    security_code         varchar(40),
    description           varchar(200)   not null,
    issuer_code           varchar(30)    not null,
    custodian             varchar(120),
    currency              varchar(3)     not null,
    face_value            numeric(19, 2) not null check (face_value > 0),
    purchase_price        numeric(19, 2) not null check (purchase_price > 0),
    purchased_interest    numeric(19, 2) not null default 0 check (purchased_interest >= 0),
    trade_date            date           not null,
    settlement_date       date           not null,
    maturity_date         date,
    coupon_rate           numeric(19, 8) not null default 0 check (coupon_rate >= 0),
    coupon_frequency      varchar(20)    not null,
    day_count             varchar(20)    not null check (day_count in ('ACT_365', 'THIRTY_360')),
    amortization_method   varchar(20)    not null
        check (amortization_method in ('EFFECTIVE_INTEREST', 'STRAIGHT_LINE', 'NONE')),
    effective_rate        numeric(19, 8),
    security_deposit      boolean        not null default false,
    bank_account          varchar(30)    not null,
    take_on               boolean        not null default false,
    take_on_date          date,
    amortized_cost        numeric(19, 2) not null default 0,
    accrued_interest      numeric(19, 2) not null default 0,
    fair_value_adjustment numeric(19, 2) not null default 0,
    fair_value            numeric(19, 2),
    fair_value_date       date,
    last_accrual_date     date,
    last_amortization_date date,
    status                varchar(20)    not null check (status in ('PENDING_APPROVAL', 'ACTIVE', 'MATURED', 'SOLD')),
    closed_date           date,
    purchase_batch_no     varchar(40),
    record_status         varchar(30)    not null,
    authorized_by         varchar(50),
    authorized_at         timestamptz,
    created_at            timestamptz    not null,
    created_by            varchar(50)    not null,
    updated_at            timestamptz,
    updated_by            varchar(50),
    constraint uq_inv_holding_no unique (company_id, holding_no),
    constraint ck_inv_dates check (settlement_date >= trade_date
        and (maturity_date is null or maturity_date > settlement_date))
);
create index ix_inv_holding_portfolio on inv_holding (company_id, portfolio_id, status);
create index ix_inv_holding_maturity on inv_holding (company_id, maturity_date);

create table inv_run (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    company_id   bigint         not null references org_company (id),
    run_type     varchar(20)    not null check (run_type in ('ACCRUAL', 'AMORTIZATION')),
    period       varchar(7)     not null,
    period_end   date           not null,
    holding_count integer       not null,
    total_amount numeric(19, 2) not null,
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_inv_run unique (company_id, run_type, period)
);

create table inv_transaction (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    holding_id        bigint         not null references inv_holding (id),
    run_id            bigint references inv_run (id),
    txn_type          varchar(20)    not null check (txn_type in
        ('PURCHASE', 'TAKE_ON', 'ACCRUAL', 'AMORTIZATION', 'COUPON', 'FAIR_VALUE', 'MATURITY', 'SALE')),
    txn_date          date           not null,
    from_date         date,
    days              integer        not null default 0,
    amount            numeric(19, 2) not null,
    cash_amount       numeric(19, 2) not null default 0,
    final_tax         numeric(19, 2) not null default 0,
    gain_loss         numeric(19, 2) not null default 0,
    carrying_after    numeric(19, 2) not null,
    accrued_after     numeric(19, 2) not null,
    batch_no          varchar(40),
    remarks           varchar(250),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create index ix_inv_txn_holding on inv_transaction (holding_id, txn_date);
create index ix_inv_txn_date on inv_transaction (company_id, txn_type, txn_date);

-- Accounting events. "@ROLE" accounts come from the portfolio (INVESTMENT, ACCRUED_INTEREST,
-- INTEREST_INCOME, REALIZED_GAIN, FAIR_VALUE) or the holding's settlement bank (BANK).
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('INVESTMENT_PURCHASE', 'Investment purchase', 'TREASURY', 'INVESTMENT',
  'Purchase at clean cost plus purchased accrued interest (roles INVESTMENT, ACCRUED_INTEREST, BANK)',
  'COST,PURCHASED_INTEREST,TOTAL'),
 ('INVESTMENT_TAKE_ON', 'Investment opening balance', 'TREASURY', 'OPENING',
  'Existing holding taken on at amortized cost and accrued interest (roles INVESTMENT, ACCRUED_INTEREST)',
  'CARRYING_AMOUNT,ACCRUED_INTEREST,TOTAL'),
 ('INVESTMENT_INTEREST_ACCRUAL', 'Investment interest accrual', 'TREASURY', 'INVESTMENT',
  'Coupon interest accrued (roles ACCRUED_INTEREST, INTEREST_INCOME)', 'INTEREST'),
 ('INVESTMENT_AMORTIZATION', 'Premium / discount amortization', 'TREASURY', 'INVESTMENT',
  'Discount accretion (positive) or premium amortization (negative) (roles INVESTMENT, INTEREST_INCOME)',
  'AMORTIZATION'),
 ('INVESTMENT_INTEREST_RECEIPT', 'Coupon / interest received', 'TREASURY', 'INVESTMENT',
  'Interest received net of final tax, relieving accrued interest (roles BANK, ACCRUED_INTEREST, INTEREST_INCOME)',
  'CASH,FINAL_TAX,ACCRUED_INTEREST,INCOME_ADJUSTMENT'),
 ('INVESTMENT_MATURITY', 'Investment maturity', 'TREASURY', 'INVESTMENT',
  'Redemption at maturity (roles BANK, INVESTMENT, ACCRUED_INTEREST, FAIR_VALUE, REALIZED_GAIN)',
  'PROCEEDS,FINAL_TAX,FV_RESERVE,CARRYING_AMOUNT,ACCRUED_INTEREST,REALIZED_GAIN'),
 ('INVESTMENT_SALE', 'Investment sale', 'TREASURY', 'INVESTMENT',
  'Sale before maturity with realized gain or loss (roles BANK, INVESTMENT, ACCRUED_INTEREST, FAIR_VALUE, REALIZED_GAIN)',
  'PROCEEDS,FINAL_TAX,FV_RESERVE,CARRYING_AMOUNT,ACCRUED_INTEREST,REALIZED_GAIN'),
 ('INVESTMENT_FAIR_VALUE', 'Investment fair value change', 'TREASURY', 'REVALUATION',
  'Fair value remeasurement of FVOCI (to equity) or FVPL (to profit or loss) holdings (roles INVESTMENT, FAIR_VALUE)',
  'FAIR_VALUE_CHANGE');
