-- =====================================================================================
-- iNXT BrokerVerse - V700 Tax & Statutory Reporting (Philippine BIR and Insurance Commission)
--
--   * tax_code             tax codes and ATCs with rates and GL accounts (maker-checker)
--   * tax_form             filing calendar: BIR / LGU / BFP forms, frequency, due rule and the
--                          GL accounts cleared by the remittance (maker-checker)
--   * tax_party_profile    TIN, registered name, VAT treatment and default ATC of a party
--                          (additive: the party master is not altered) (maker-checker)
--   * tax_return (+ line)  return per form and period, DRAFT -> FILED -> PAID (or CANCELLED)
--   * tax_remittance       payment of a return and the TAX_REMITTANCE journal that cleared it
--   * tax_2307_*           BIR Form 2307 certificates per payee and quarter, grouped in batches
--   * tax_ic_line_item     Insurance Commission schedule line <-> account range / report group
--                          mapping, with the RBC factor for the RBC summary (maker-checker)
--
-- Index and constraint names carry the tax_ / ix_tax_ prefix (names are schema-global).
-- =====================================================================================

create table tax_code (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    code            varchar(20)    not null,
    name            varchar(150)   not null,
    tax_type        varchar(20)    not null
        constraint tax_ck_code_type check (tax_type in ('VAT_OUTPUT', 'VAT_INPUT', 'VAT_ZERO_RATED',
            'VAT_EXEMPT', 'PREMIUM_TAX', 'DST', 'LGT', 'FST', 'EWT')),
    atc             varchar(10),
    payee_class     varchar(12)
        constraint tax_ck_code_payee check (payee_class in ('INDIVIDUAL', 'CORPORATE')),
    rate            numeric(19, 8) not null
        constraint tax_ck_code_rate check (rate >= 0 and rate <= 100),
    gl_account_code varchar(30)    not null,
    income_nature   varchar(200),
    effective_from  date           not null,
    effective_to    date,
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint tax_uq_code unique (company_id, code),
    constraint tax_ck_code_dates check (effective_to is null or effective_to >= effective_from),
    constraint tax_ck_code_atc check (tax_type <> 'EWT' or atc is not null)
);
create index ix_tax_code_type on tax_code (company_id, tax_type);

create table tax_form (
    id                   bigint generated by default as identity primary key,
    version              bigint        not null default 0,
    company_id           bigint        not null references org_company (id),
    code                 varchar(20)   not null,
    name                 varchar(150)  not null,
    authority            varchar(10)   not null
        constraint tax_ck_form_authority check (authority in ('BIR', 'LGU', 'BFP')),
    frequency            varchar(30)   not null
        constraint tax_ck_form_frequency check (frequency in ('MONTHLY', 'QUARTERLY',
            'MONTHLY_EXCEPT_QUARTER_END', 'ANNUAL')),
    worksheet            varchar(20)   not null
        constraint tax_ck_form_worksheet check (worksheet in ('VAT', 'EWT', 'DST', 'PREMIUM_TAX',
            'LGT', 'FST', 'NONE')),
    due_months_after     integer       not null
        constraint tax_ck_form_months check (due_months_after between 0 and 12),
    due_day              integer       not null
        constraint tax_ck_form_day check (due_day between 1 and 31),
    payable_account_code varchar(30),
    credit_account_code  varchar(30),
    track_filing         boolean       not null default true,
    effective_from       date          not null,
    record_status        varchar(30)   not null,
    authorized_by        varchar(50),
    authorized_at        timestamptz,
    created_at           timestamptz   not null,
    created_by           varchar(50)   not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint tax_uq_form unique (company_id, code),
    constraint tax_ck_form_tracked check (not track_filing
        or (worksheet <> 'NONE' and payable_account_code is not null))
);

create table tax_party_profile (
    id                 bigint generated by default as identity primary key,
    version            bigint       not null default 0,
    company_id         bigint       not null references org_company (id),
    party_id           bigint       not null references pty_party (id),
    party_code         varchar(30)  not null,
    tin                varchar(9)   not null
        constraint tax_ck_profile_tin check (tin ~ '^[0-9]{9}$'),
    branch_code        varchar(5)   not null default '000'
        constraint tax_ck_profile_branch check (branch_code ~ '^[0-9]{3,5}$'),
    payee_class        varchar(12)  not null
        constraint tax_ck_profile_payee check (payee_class in ('INDIVIDUAL', 'CORPORATE')),
    registered_name    varchar(200) not null,
    last_name          varchar(60),
    first_name         varchar(60),
    middle_name        varchar(60),
    registered_address varchar(300),
    zip_code           varchar(10),
    vat_treatment      varchar(12)  not null default 'REGULAR'
        constraint tax_ck_profile_vat check (vat_treatment in ('REGULAR', 'ZERO_RATED', 'EXEMPT')),
    default_atc_code   varchar(20),
    record_status      varchar(30)  not null,
    authorized_by      varchar(50),
    authorized_at      timestamptz,
    created_at         timestamptz  not null,
    created_by         varchar(50)  not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint tax_uq_party_profile unique (company_id, party_id),
    constraint tax_ck_profile_names check (payee_class = 'CORPORATE'
        or (last_name is not null and first_name is not null))
);
create index ix_tax_profile_code on tax_party_profile (company_id, party_code);

create table tax_return (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    return_no        varchar(40)    not null,
    form_code        varchar(20)    not null,
    worksheet        varchar(20)    not null,
    period_start     date           not null,
    period_end       date           not null,
    due_date         date           not null,
    tax_base         numeric(19, 2) not null,
    tax_due          numeric(19, 2) not null,
    tax_credits      numeric(19, 2) not null,
    amount_payable   numeric(19, 2) not null
        constraint tax_ck_return_payable check (amount_payable >= 0),
    excess_credit    numeric(19, 2) not null
        constraint tax_ck_return_excess check (excess_credit >= 0),
    status           varchar(12)    not null
        constraint tax_ck_return_status check (status in ('DRAFT', 'FILED', 'PAID', 'CANCELLED')),
    prepared_by      varchar(50)    not null,
    prepared_at      timestamptz    not null,
    filed_by         varchar(50),
    filed_at         timestamptz,
    filed_on         date,
    filing_reference varchar(60),
    status_reason    varchar(200),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint tax_uq_return_no unique (company_id, return_no),
    constraint tax_ck_return_period check (period_end >= period_start)
);
create unique index tax_uq_return_period on tax_return (company_id, form_code, period_start)
    where status <> 'CANCELLED';
create index ix_tax_return_due on tax_return (company_id, status, due_date);

create table tax_return_line (
    id          bigint generated by default as identity primary key,
    return_id   bigint         not null references tax_return (id),
    line_no     integer        not null,
    line_code   varchar(40)    not null,
    description varchar(200)   not null,
    base_amount numeric(19, 2),
    amount      numeric(19, 2) not null,
    constraint tax_uq_return_line unique (return_id, line_no)
);

create table tax_remittance (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    return_id           bigint         not null references tax_return (id),
    form_code           varchar(20)    not null,
    period_start        date           not null,
    period_end          date           not null,
    due_date            date           not null,
    paid_on             date           not null,
    amount              numeric(19, 2) not null
        constraint tax_ck_remit_amount check (amount >= 0),
    payable_cleared     numeric(19, 2) not null,
    credit_applied      numeric(19, 2) not null,
    bank_account_code   varchar(30),
    payment_reference   varchar(60)    not null,
    journal_batch_no    varchar(40),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint tax_uq_remittance_return unique (return_id)
);
create index ix_tax_remittance_paid on tax_remittance (company_id, paid_on);

create table tax_2307_batch (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    batch_no          varchar(40)    not null,
    period_start      date           not null,
    period_end        date           not null,
    certificate_count integer        not null,
    total_income      numeric(19, 2) not null,
    total_tax         numeric(19, 2) not null,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint tax_uq_2307_batch unique (company_id, batch_no)
);

create table tax_2307_certificate (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    batch_id           bigint         not null references tax_2307_batch (id),
    certificate_no     varchar(40)    not null,
    party_code         varchar(30)    not null,
    payee_tin          varchar(9)     not null,
    payee_branch_code  varchar(5)     not null,
    payee_name         varchar(200)   not null,
    payee_address      varchar(300),
    payee_zip          varchar(10),
    payor_tin          varchar(9)     not null,
    payor_branch_code  varchar(5)     not null,
    payor_name         varchar(200)   not null,
    payor_address      varchar(300),
    period_start       date           not null,
    period_end         date           not null,
    total_income       numeric(19, 2) not null,
    total_tax          numeric(19, 2) not null,
    status             varchar(12)    not null
        constraint tax_ck_2307_status check (status in ('ISSUED', 'CANCELLED')),
    status_reason      varchar(200),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint tax_uq_2307_no unique (company_id, certificate_no)
);
create unique index tax_uq_2307_payee on tax_2307_certificate (company_id, party_code, period_start)
    where status = 'ISSUED';
create index ix_tax_2307_batch on tax_2307_certificate (batch_id);

create table tax_2307_line (
    id             bigint generated by default as identity primary key,
    certificate_id bigint         not null references tax_2307_certificate (id),
    line_no        integer        not null,
    atc            varchar(10)    not null,
    income_nature  varchar(200)   not null,
    month1_amount  numeric(19, 2) not null,
    month2_amount  numeric(19, 2) not null,
    month3_amount  numeric(19, 2) not null,
    total_amount   numeric(19, 2) not null,
    tax_withheld   numeric(19, 2) not null,
    constraint tax_uq_2307_line unique (certificate_id, line_no)
);

create table tax_ic_line_item (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    schedule       varchar(20)    not null
        constraint tax_ck_ic_schedule check (schedule in ('PREMIUMS', 'LOSSES', 'COMMISSIONS',
            'NET_WORTH', 'RBC', 'RESERVES', 'INVESTMENTS')),
    line_code      varchar(30)    not null,
    description    varchar(200)   not null,
    line_order     integer        not null,
    account_from   varchar(30),
    account_to     varchar(30),
    report_group   varchar(100),
    normal_balance varchar(6)     not null
        constraint tax_ck_ic_balance check (normal_balance in ('DEBIT', 'CREDIT')),
    sign_factor    integer        not null
        constraint tax_ck_ic_sign check (sign_factor in (1, -1)),
    measure        varchar(10)    not null
        constraint tax_ck_ic_measure check (measure in ('BALANCE', 'MOVEMENT')),
    rbc_factor     numeric(19, 8)
        constraint tax_ck_ic_factor check (rbc_factor is null or (rbc_factor >= 0 and rbc_factor <= 100)),
    record_status  varchar(30)    not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint tax_uq_ic_line unique (company_id, schedule, line_code),
    constraint tax_ck_ic_source check ((account_from is not null and account_to is not null
        and account_from <= account_to) or report_group is not null)
);
create index ix_tax_ic_schedule on tax_ic_line_item (company_id, schedule, line_order);

-- Remittance of a filed return: clears the tax payable (role TAX_PAYABLE), applies credits such
-- as input VAT (role TAX_CREDIT) and pays the balance from the bank (role BANK).
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('TAX_REMITTANCE', 'Tax remittance', 'PAYMENT', 'PAYMENT',
  'Payment of a filed tax return (roles TAX_PAYABLE, TAX_CREDIT, BANK)',
  'TAX_PAYABLE,TAX_CREDIT,AMOUNT');

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by) values
    ('TAX_RETURN_DUE', 'Tax return due soon',
     'A tracked tax return (BIR, LGU or BFP) falls due within the threshold days and is not yet filed and paid.',
     'TAX', 'MEDIUM', null, 15, now(), 'SYSTEM'),
    ('TAX_RETURN_OVERDUE', 'Tax return overdue',
     'The due date of a tracked tax return has passed and the return is not paid (penalties and interest accrue).',
     'TAX', 'HIGH', null, null, now(), 'SYSTEM');

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('TAX_RDO_CODE', '050', 'STRING', 'TAX',
     'BIR Revenue District Office code of the withholding agent, printed on the SLS/SLP/QAP exports',
     null, null, now(), 'SYSTEM'),
    ('IC_RBC_HURDLE_PERCENT', '100', 'INTEGER', 'TAX',
     'Minimum risk-based capital ratio (percent) required by the Insurance Commission; the IC-RBC summary flags a shortfall',
     1, 1000, now(), 'SYSTEM');
