-- =====================================================================================
-- iNXT BrokerVerse - V702 Received creditable withholding tax certificates (BRD-5 A1-FRBS)
--   DIS 2.11.0-2.11.2 (CWT received from insurers on commission and incentives), FRBS 3.2.0
--   Appendix A VII (SAWT), OQ41 / AQ16; docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md
--   sections 2.1, 6 (row 14) and 12.1.
--
--   * tax_certificate_received       one register of the BIR 2307 certificates BDOI receives from
--                                    the withholding agents (insurers), shared by Disbursement
--                                    tagging (DIS 2.11), Commission (CMRID.015) and the SAWT. A
--                                    recorded certificate posts TAX_CWT_CERT_RECEIVED (AR-BIR on
--                                    commission / incentives to AR-BIR on hand); a cancellation
--                                    posts the same event with negative amounts.
--   * tax_certificate_received_line  the income payments of a certificate by ATC and kind
--                                    (COMMISSION / INCENTIVE) with the tax withheld
--
-- The source (DV, remittance batch, commission certificate) is a plain reference: tax does not
-- depend on disbursement (design 2.1). No foreign key to broking tables.
-- =====================================================================================

create table tax_certificate_received (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    certificate_no   varchar(40)    not null,
    agent_code       varchar(30)    not null,
    agent_name       varchar(200)   not null,
    agent_tin        varchar(20),
    period_from      date           not null,
    period_to        date           not null,
    received_on      date           not null,
    source_module    varchar(30),
    source_ref       varchar(80),
    status           varchar(20)    not null
        constraint tax_ck_received_status check (status in ('RECORDED', 'CANCELLED')),
    income_total     numeric(19, 2) not null,
    tax_total        numeric(19, 2) not null,
    journal_batch_no varchar(40),
    cancel_journal_no varchar(40),
    cancel_reason    varchar(250),
    remarks          varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint tax_ck_received_period check (period_to >= period_from)
);
create unique index tax_uq_received_certificate on tax_certificate_received (company_id, agent_code, certificate_no)
    where status <> 'CANCELLED';
create index ix_tax_received_period on tax_certificate_received (company_id, period_to);
create index ix_tax_received_source on tax_certificate_received (source_module, source_ref);

create table tax_certificate_received_line (
    certificate_id bigint         not null references tax_certificate_received (id),
    line_no        integer        not null,
    kind           varchar(12)    not null
        constraint tax_ck_received_kind check (kind in ('COMMISSION', 'INCENTIVE')),
    atc            varchar(10)    not null,
    income_nature  varchar(200),
    income         numeric(19, 2) not null
        constraint tax_ck_received_income check (income >= 0),
    tax            numeric(19, 2) not null
        constraint tax_ck_received_tax check (tax > 0),
    primary key (certificate_id, line_no)
);
