-- =====================================================================================
-- iNXT BrokerVerse - V751 Workflow engine: stage / transition definitions, work cases,
-- status history, queues and SLA.
--   BRNB.022/115 (stages, allowed transitions, status history with user and time),
--   BRNB.080 (assign / re-assign workload), BRNB.096 (Marketing submissions trigger Processing),
--   BRNB.097 (separate workflows per transaction type).
--   Seeded workflows: NB_QUOTATION, NB_PROPOSAL, NB_ACCOUNT
--   (docs/architecture/BROKING_ARCHITECTURE.md section 4).
-- =====================================================================================
create table wf_stage (
    id               bigint generated by default as identity primary key,
    workflow_code    varchar(40)  not null,
    stage_code       varchar(40)  not null,
    name             varchar(120) not null,
    -- Permission of the team that works cases in this stage; null = no work queue (e.g. BOOKED).
    owner_permission varchar(50),
    sla_hours        integer,
    initial          boolean      not null default false,
    terminal         boolean      not null default false,
    sort_order       integer      not null,
    constraint uq_wf_stage unique (workflow_code, stage_code),
    constraint ck_wf_stage_sla check (sla_hours is null or sla_hours > 0)
);

create table wf_transition (
    id            bigint generated by default as identity primary key,
    workflow_code varchar(40)  not null,
    from_stage    varchar(40)  not null,
    action        varchar(40)  not null,
    to_stage      varchar(40)  not null,
    label         varchar(80)  not null,
    -- Comma separated permissions; holding any one of them allows the action.
    permission    varchar(200) not null,
    -- Generic transitions have no side effect and may be run from the generic workflow API.
    generic       boolean      not null default false,
    -- When set, a reason from this list of values is mandatory.
    reason_lov    varchar(40)  references lov_type (code),
    sort_order    integer      not null default 0,
    constraint uq_wf_transition unique (workflow_code, from_stage, action),
    constraint fk_wf_transition_from foreign key (workflow_code, from_stage)
        references wf_stage (workflow_code, stage_code),
    constraint fk_wf_transition_to foreign key (workflow_code, to_stage)
        references wf_stage (workflow_code, stage_code)
);

create table wf_case (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    company_id       bigint       not null references org_company (id),
    workflow_code    varchar(40)  not null,
    entity_type      varchar(60)  not null,
    entity_id        varchar(60)  not null,
    reference        varchar(60)  not null,
    title            varchar(200) not null,
    link             varchar(300),
    originating_unit varchar(60),
    stage_code       varchar(40)  not null,
    stage_entered_at timestamptz  not null,
    due_at           timestamptz,
    assignee         varchar(50),
    closed           boolean      not null default false,
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_wf_case_entity unique (entity_type, entity_id),
    constraint fk_wf_case_stage foreign key (workflow_code, stage_code)
        references wf_stage (workflow_code, stage_code)
);
create index ix_wf_case_queue on wf_case (company_id, workflow_code, stage_code, closed);
create index ix_wf_case_assignee on wf_case (lower(assignee), closed);
create index ix_wf_case_reference on wf_case (reference);
create index ix_wf_case_due on wf_case (due_at) where closed = false;

-- Insert-only status history (BRNB.022: timestamp, responsible user or system action).
create table wf_case_history (
    id          bigint generated by default as identity primary key,
    case_id     bigint        not null references wf_case (id),
    from_stage  varchar(40),
    to_stage    varchar(40)   not null,
    action      varchar(40)   not null,
    reason_code varchar(40),
    comment     varchar(1000),
    actor       varchar(50)   not null,
    automatic   boolean       not null default false,
    occurred_at timestamptz   not null
);
create index ix_wf_history_case on wf_case_history (case_id, id);
create index ix_wf_history_time on wf_case_history (occurred_at);

-- ---------- NB_QUOTATION: package quotation ------------------------------------------
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('NB_QUOTATION', 'DRAFT', 'Draft', 'QUOTE_MAINTAIN', 24, true, false, 10),
       ('NB_QUOTATION', 'FOR_REVIEW', 'For review', 'QUOTE_APPROVE', 8, false, false, 20),
       ('NB_QUOTATION', 'APPROVED', 'Approved', 'QUOTE_MAINTAIN', 24, false, false, 30),
       ('NB_QUOTATION', 'SENT_TO_CLIENT', 'Sent to client', 'QUOTE_MAINTAIN', 168, false, false, 40),
       ('NB_QUOTATION', 'ACCEPTED', 'Accepted by client', 'QUOTE_MAINTAIN', 24, false, false, 50),
       ('NB_QUOTATION', 'CONVERTED', 'Account created', null, null, false, true, 60),
       ('NB_QUOTATION', 'NOT_PROCEEDED', 'Not proceeded', null, null, false, true, 70),
       ('NB_QUOTATION', 'VOIDED', 'Voided', null, null, false, true, 80);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_QUOTATION', 'DRAFT', 'submit', 'FOR_REVIEW', 'Submit for review', 'QUOTE_MAINTAIN', false, null, 10),
       ('NB_QUOTATION', 'FOR_REVIEW', 'approve', 'APPROVED', 'Approve', 'QUOTE_APPROVE', false, null, 10),
       ('NB_QUOTATION', 'FOR_REVIEW', 'return', 'DRAFT', 'Return to maker', 'QUOTE_APPROVE', true, 'RETURN_REASON', 20),
       ('NB_QUOTATION', 'APPROVED', 'send', 'SENT_TO_CLIENT', 'Send to client', 'QUOTE_MAINTAIN', false, null, 10),
       ('NB_QUOTATION', 'SENT_TO_CLIENT', 'accept', 'ACCEPTED', 'Record acceptance', 'QUOTE_MAINTAIN', false, null, 10),
       ('NB_QUOTATION', 'SENT_TO_CLIENT', 'decline', 'NOT_PROCEEDED', 'Client declined', 'QUOTE_MAINTAIN', true, null, 20),
       ('NB_QUOTATION', 'ACCEPTED', 'create_accounts', 'CONVERTED', 'Create accounts', 'QUOTE_MAINTAIN', false, null, 10),
       ('NB_QUOTATION', 'DRAFT', 'void', 'VOIDED', 'Void', 'QUOTE_MAINTAIN', true, 'VOID_REASON', 90),
       ('NB_QUOTATION', 'FOR_REVIEW', 'void', 'VOIDED', 'Void', 'QUOTE_MAINTAIN,QUOTE_APPROVE', true, 'VOID_REASON', 90);

-- ---------- NB_PROPOSAL: non-package Proposal Request (PRF) --------------------------
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('NB_PROPOSAL', 'DRAFT', 'Draft PRF', 'PROPOSAL_REQUEST', 24, true, false, 10),
       ('NB_PROPOSAL', 'FOR_MKT_APPROVAL', 'For Marketing approval', 'PROPOSAL_APPROVE', 8, false, false, 20),
       ('NB_PROPOSAL', 'WITH_TSU', 'Received by TSU', 'TSU_PROCESS', 8, false, false, 30),
       ('NB_PROPOSAL', 'QS_PREPARATION', 'Quotation slip in preparation', 'TSU_PROCESS', 24, false, false, 40),
       ('NB_PROPOSAL', 'QS_FOR_APPROVAL', 'Quotation slip for approval', 'TSU_APPROVE', 8, false, false, 50),
       ('NB_PROPOSAL', 'QS_SENT', 'Awaiting insurer terms', 'TSU_PROCESS', 72, false, false, 60),
       ('NB_PROPOSAL', 'TERMS_RECEIVED', 'Insurer terms received', 'TSU_PROCESS', 24, false, false, 70),
       ('NB_PROPOSAL', 'PS_FOR_APPROVAL', 'Proposal slip for approval', 'TSU_APPROVE', 8, false, false, 80),
       ('NB_PROPOSAL', 'PS_RELEASED', 'Proposal slip released to Marketing', 'PROPOSAL_REQUEST', 24, false, false, 90),
       ('NB_PROPOSAL', 'SENT_TO_CLIENT', 'Sent to client', 'PROPOSAL_REQUEST', 168, false, false, 100),
       ('NB_PROPOSAL', 'ACCEPTED', 'Accepted by client', 'PROPOSAL_REQUEST', 24, false, false, 110),
       ('NB_PROPOSAL', 'CONVERTED', 'Account created', null, null, false, true, 120),
       ('NB_PROPOSAL', 'NOT_PROCEEDED', 'Not proceeded', null, null, false, true, 130),
       ('NB_PROPOSAL', 'VOIDED', 'Voided', null, null, false, true, 140);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_PROPOSAL', 'DRAFT', 'submit', 'FOR_MKT_APPROVAL', 'Submit for approval', 'PROPOSAL_REQUEST', false, null, 10),
       ('NB_PROPOSAL', 'FOR_MKT_APPROVAL', 'approve', 'WITH_TSU', 'Approve and send to TSU', 'PROPOSAL_APPROVE', false, null, 10),
       ('NB_PROPOSAL', 'FOR_MKT_APPROVAL', 'return', 'DRAFT', 'Return to Account Officer', 'PROPOSAL_APPROVE', true, 'RETURN_REASON', 20),
       ('NB_PROPOSAL', 'WITH_TSU', 'prepare_qs', 'QS_PREPARATION', 'Accept and prepare quotation slip', 'TSU_PROCESS', true, null, 10),
       ('NB_PROPOSAL', 'WITH_TSU', 'return', 'DRAFT', 'Return to Marketing', 'TSU_PROCESS', true, 'RETURN_REASON', 20),
       ('NB_PROPOSAL', 'QS_PREPARATION', 'submit_qs', 'QS_FOR_APPROVAL', 'Submit quotation slip', 'TSU_PROCESS', false, null, 10),
       ('NB_PROPOSAL', 'QS_FOR_APPROVAL', 'approve_qs', 'QS_SENT', 'Approve and send to insurers', 'TSU_APPROVE', false, null, 10),
       ('NB_PROPOSAL', 'QS_FOR_APPROVAL', 'return', 'QS_PREPARATION', 'Return for correction', 'TSU_APPROVE', true, 'RETURN_REASON', 20),
       ('NB_PROPOSAL', 'QS_SENT', 'terms_complete', 'TERMS_RECEIVED', 'Insurer terms complete', 'TSU_PROCESS', false, null, 10),
       ('NB_PROPOSAL', 'TERMS_RECEIVED', 'submit_ps', 'PS_FOR_APPROVAL', 'Submit proposal slip', 'TSU_PROCESS', false, null, 10),
       ('NB_PROPOSAL', 'PS_FOR_APPROVAL', 'approve_ps', 'PS_RELEASED', 'Approve and release to Marketing', 'TSU_APPROVE', false, null, 10),
       ('NB_PROPOSAL', 'PS_FOR_APPROVAL', 'return', 'TERMS_RECEIVED', 'Return for correction', 'TSU_APPROVE', true, 'RETURN_REASON', 20),
       ('NB_PROPOSAL', 'PS_RELEASED', 'send_to_client', 'SENT_TO_CLIENT', 'Send to client', 'PROPOSAL_REQUEST', false, null, 10),
       ('NB_PROPOSAL', 'SENT_TO_CLIENT', 'accept', 'ACCEPTED', 'Record acceptance', 'PROPOSAL_REQUEST', false, null, 10),
       ('NB_PROPOSAL', 'SENT_TO_CLIENT', 'decline', 'NOT_PROCEEDED', 'Client declined', 'PROPOSAL_REQUEST', true, null, 20),
       ('NB_PROPOSAL', 'ACCEPTED', 'create_accounts', 'CONVERTED', 'Create accounts', 'PROPOSAL_REQUEST', false, null, 10),
       ('NB_PROPOSAL', 'DRAFT', 'void', 'VOIDED', 'Void', 'PROPOSAL_REQUEST', true, 'VOID_REASON', 90),
       ('NB_PROPOSAL', 'FOR_MKT_APPROVAL', 'void', 'VOIDED', 'Void', 'PROPOSAL_REQUEST,PROPOSAL_APPROVE', true, 'VOID_REASON', 90),
       ('NB_PROPOSAL', 'WITH_TSU', 'void', 'VOIDED', 'Void', 'PROPOSAL_REQUEST,TSU_PROCESS', true, 'VOID_REASON', 90);

-- ---------- NB_ACCOUNT: account from creation to booking -----------------------------
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('NB_ACCOUNT', 'DRAFT', 'Draft', 'ACCOUNT_MAINTAIN', 24, true, false, 10),
       ('NB_ACCOUNT', 'SUBMITTED', 'Submitted to Processing', 'ACCOUNT_PROCESS', 8, false, false, 20),
       ('NB_ACCOUNT', 'RETURNED_TO_MARKETING', 'Returned to Marketing', 'ACCOUNT_MAINTAIN', 24, false, false, 30),
       ('NB_ACCOUNT', 'AWAITING_PAYMENT', 'Awaiting payment / confirmation', 'BILLING_MANAGE', 72, false, false, 40),
       ('NB_ACCOUNT', 'READY_FOR_PLACEMENT', 'Ready for placement', 'PLACEMENT_MANAGE', 8, false, false, 50),
       ('NB_ACCOUNT', 'PLACED', 'Placed with insurer', 'EPOLICY_MANAGE', 72, false, false, 60),
       ('NB_ACCOUNT', 'RETURNED_BY_INSURER', 'Returned by insurer', 'PLACEMENT_MANAGE', 8, false, false, 70),
       ('NB_ACCOUNT', 'PLACEMENT_CANCELLED', 'Placement cancelled', null, null, false, false, 80),
       ('NB_ACCOUNT', 'POLICY_ISSUED', 'Policy issued - for booking', 'BOOKING_PROCESS', 24, false, false, 90),
       ('NB_ACCOUNT', 'BOOKED', 'Booked', null, null, false, false, 100),
       ('NB_ACCOUNT', 'CANCELLED', 'Cancelled (after issuance)', null, null, false, true, 110),
       ('NB_ACCOUNT', 'VOIDED', 'Voided (internal reversal)', null, null, false, true, 120);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_ACCOUNT', 'DRAFT', 'submit', 'SUBMITTED', 'Submit to Processing', 'ACCOUNT_MAINTAIN', false, null, 10),
       ('NB_ACCOUNT', 'SUBMITTED', 'validate', 'AWAITING_PAYMENT', 'Validate', 'ACCOUNT_PROCESS', false, null, 10),
       ('NB_ACCOUNT', 'SUBMITTED', 'direct_booking', 'POLICY_ISSUED', 'Direct booking (policy already issued)', 'ACCOUNT_PROCESS', false, null, 20),
       ('NB_ACCOUNT', 'SUBMITTED', 'return', 'RETURNED_TO_MARKETING', 'Return to Marketing', 'ACCOUNT_PROCESS', true, 'RETURN_REASON', 30),
       ('NB_ACCOUNT', 'RETURNED_TO_MARKETING', 'resubmit', 'SUBMITTED', 'Resubmit to Processing', 'ACCOUNT_MAINTAIN', false, null, 10),
       ('NB_ACCOUNT', 'AWAITING_PAYMENT', 'payment_confirmed', 'READY_FOR_PLACEMENT', 'Confirm payment / client confirmation', 'BILLING_MANAGE', false, null, 10),
       ('NB_ACCOUNT', 'AWAITING_PAYMENT', 'return', 'RETURNED_TO_MARKETING', 'Return to Marketing', 'BILLING_MANAGE,ACCOUNT_PROCESS', true, 'RETURN_REASON', 20),
       ('NB_ACCOUNT', 'READY_FOR_PLACEMENT', 'place', 'PLACED', 'Send placement to insurer', 'PLACEMENT_MANAGE', false, null, 10),
       ('NB_ACCOUNT', 'READY_FOR_PLACEMENT', 'direct_booking', 'POLICY_ISSUED', 'Direct booking (policy already issued)', 'PLACEMENT_MANAGE', false, null, 20),
       ('NB_ACCOUNT', 'READY_FOR_PLACEMENT', 'return', 'RETURNED_TO_MARKETING', 'Return to Marketing', 'PLACEMENT_MANAGE', true, 'RETURN_REASON', 30),
       ('NB_ACCOUNT', 'READY_FOR_PLACEMENT', 'cancel_placement', 'PLACEMENT_CANCELLED', 'Cancel placement', 'PLACEMENT_MANAGE', false, 'CANCELLATION_REASON', 90),
       ('NB_ACCOUNT', 'PLACED', 'policy_received', 'POLICY_ISSUED', 'E-policy received', 'EPOLICY_MANAGE', false, null, 10),
       ('NB_ACCOUNT', 'PLACED', 'insurer_return', 'RETURNED_BY_INSURER', 'Returned by insurer', 'PLACEMENT_MANAGE', false, 'RETURN_REASON', 20),
       ('NB_ACCOUNT', 'PLACED', 'cancel_placement', 'PLACEMENT_CANCELLED', 'Cancel placement', 'PLACEMENT_MANAGE', false, 'CANCELLATION_REASON', 90),
       ('NB_ACCOUNT', 'RETURNED_BY_INSURER', 'resubmit', 'READY_FOR_PLACEMENT', 'Resubmit for placement', 'PLACEMENT_MANAGE', false, null, 10),
       ('NB_ACCOUNT', 'RETURNED_BY_INSURER', 'return', 'RETURNED_TO_MARKETING', 'Return to Marketing', 'PLACEMENT_MANAGE', true, 'RETURN_REASON', 20),
       ('NB_ACCOUNT', 'RETURNED_BY_INSURER', 'cancel_placement', 'PLACEMENT_CANCELLED', 'Cancel placement', 'PLACEMENT_MANAGE', false, 'CANCELLATION_REASON', 90),
       ('NB_ACCOUNT', 'PLACEMENT_CANCELLED', 'reactivate', 'READY_FOR_PLACEMENT', 'Reactivate', 'ACCOUNT_MAINTAIN,PLACEMENT_MANAGE', false, null, 10),
       ('NB_ACCOUNT', 'POLICY_ISSUED', 'book', 'BOOKED', 'Book', 'BOOKING_PROCESS', false, null, 10),
       ('NB_ACCOUNT', 'BOOKED', 'cancel', 'CANCELLED', 'Cancel booking', 'BOOKING_ADJUST', false, 'CANCELLATION_REASON', 10),
       ('NB_ACCOUNT', 'DRAFT', 'void', 'VOIDED', 'Void', 'ACCOUNT_MAINTAIN', true, 'VOID_REASON', 90),
       ('NB_ACCOUNT', 'SUBMITTED', 'void', 'VOIDED', 'Void', 'ACCOUNT_MAINTAIN,ACCOUNT_PROCESS', true, 'VOID_REASON', 90),
       ('NB_ACCOUNT', 'RETURNED_TO_MARKETING', 'void', 'VOIDED', 'Void', 'ACCOUNT_MAINTAIN', true, 'VOID_REASON', 90);

-- Work item SLA breach (evaluated by the daily alert checks).
insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
                                threshold_days, created_at, created_by)
values ('WORK_SLA_BREACH', 'Work item overdue',
        'A broking work item (quotation, proposal request or account) has stayed in its stage beyond the stage SLA',
        'WORKFLOW', 'MEDIUM', null, null, now(), 'SYSTEM');
