-- =====================================================================================
-- iNXT BrokerVerse - V752 Bulk processing framework: upload jobs and their rows.
--   BRNB.024/025 (bulk update via file, per-row validation, error report, summary),
--   BRNB.039 (standard template, valid rows processed, failed rows reported),
--   BRNB.064 (list sanitisation), BRNB.036 (bulk booking).
-- =====================================================================================
create table bulk_job (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    job_no         varchar(30)  not null unique,
    handler_code   varchar(40)  not null,
    file_name      varchar(255) not null,
    parameters     text,
    status         varchar(20)  not null,
    total_rows     integer      not null default 0,
    valid_rows     integer      not null default 0,
    invalid_rows   integer      not null default 0,
    committed_rows integer      not null default 0,
    failed_rows    integer      not null default 0,
    completed_at   timestamptz,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_bulk_job_status check (status in ('VALIDATED', 'COMPLETED', 'CANCELLED'))
);
create index ix_bulk_job_handler on bulk_job (company_id, handler_code, created_at);

create table bulk_row (
    id         bigint generated by default as identity primary key,
    job_id     bigint        not null references bulk_job (id),
    row_no     integer       not null,
    data       text          not null,
    status     varchar(20)   not null,
    messages   varchar(2000),
    result_ref varchar(100),
    constraint uq_bulk_row unique (job_id, row_no),
    constraint ck_bulk_row_status check (status in ('VALID', 'INVALID', 'COMMITTED', 'FAILED'))
);
create index ix_bulk_row_job_status on bulk_row (job_id, status);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('BULK_MAX_ROWS', '5000', 'INTEGER', 'BULK',
     'Maximum number of data rows in one bulk upload file', 10, 50000, now(), 'SYSTEM');
