-- =====================================================================================
-- iNXT BrokerVerse - V753 Messaging: outbound e-mail outbox with send log, protected
-- attachments and in-app notifications.
--   BRNB.008 (communications recorded: recipient, time, content), BRNB.013/035 (password
--   protected outbound documents, password sent separately), BRNB.015 (notifications),
--   BRNB.078 / BRNB.100b (successful and unsuccessful sends with reason).
-- =====================================================================================
create table msg_outbound (
    id                bigint generated by default as identity primary key,
    version           bigint        not null default 0,
    company_id        bigint        references org_company (id),
    channel           varchar(10)   not null default 'EMAIL',
    purpose           varchar(40)   not null,
    recipients        varchar(1000) not null,
    cc                varchar(1000),
    subject           varchar(300)  not null,
    body              text          not null,
    status            varchar(20)   not null,
    attempts          integer       not null default 0,
    last_error        varchar(1000),
    sent_at           timestamptz,
    simulated         boolean       not null default false,
    entity_type       varchar(60),
    entity_id         varchar(60),
    reference         varchar(60),
    password_for_id   bigint        references msg_outbound (id),
    created_at        timestamptz   not null,
    created_by        varchar(50)   not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_msg_outbound_status check (status in ('QUEUED', 'SENT', 'FAILED', 'CANCELLED'))
);
create index ix_msg_outbound_status on msg_outbound (status, created_at);
create index ix_msg_outbound_entity on msg_outbound (entity_type, entity_id);
create index ix_msg_outbound_reference on msg_outbound (reference);
create index ix_msg_outbound_created on msg_outbound (created_at);

create table msg_outbound_attachment (
    id          bigint generated by default as identity primary key,
    message_id  bigint       not null references msg_outbound (id),
    file_name   varchar(255) not null,
    mime_type   varchar(100) not null,
    size_bytes  bigint       not null,
    sha256      varchar(64)  not null,
    protected   boolean      not null,
    content     bytea        not null
);
create index ix_msg_attachment_message on msg_outbound_attachment (message_id);

create table msg_notification (
    id          bigint generated by default as identity primary key,
    recipient   varchar(50)   not null,
    title       varchar(200)  not null,
    body        varchar(1000),
    link        varchar(300),
    entity_type varchar(60),
    entity_id   varchar(60),
    created_at  timestamptz   not null,
    read_at     timestamptz
);
create index ix_msg_notification_recipient on msg_notification (lower(recipient), read_at, created_at);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('MAIL_FROM_ADDRESS', 'no-reply@bdoi.example.ph', 'STRING', 'MESSAGING',
     'From address of e-mails sent by BrokerVerse (quotations, slips, e-policies, invoices)', null,
     null, now(), 'SYSTEM'),
    ('MAIL_MAX_ATTEMPTS', '3', 'INTEGER', 'MESSAGING',
     'Delivery attempts before an e-mail is marked failed', 1, 10, now(), 'SYSTEM');
