-- =====================================================================================
-- iNXT BrokerVerse - V754 Versioned document templates for generated documents
-- (quotations, quotation / proposal / placement slips, hold cover, insurance advice,
-- e-mails). BRNB.004: shared templates with dynamic fields, template versioning.
-- Placeholders: {{name}}; the generating module supplies the values.
-- =====================================================================================
create table doc_template (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    code           varchar(40)   not null,
    version_no     integer       not null,
    title          varchar(200)  not null,
    body           text          not null,
    effective_from date          not null,
    active         boolean       not null default true,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_doc_template unique (code, version_no)
);

insert into doc_template (code, version_no, title, body, effective_from, created_at, created_by)
values
('QUOTATION_LETTER', 1, 'Insurance quotation',
 'Dear {{clientName}},

Thank you for considering BDO Insurance and Reinsurance Brokers, Inc. We are pleased to present our quotation {{reference}} for {{productName}}.

The quotation is valid until {{validUntil}}. To proceed, reply to this e-mail confirming your acceptance; your Account Officer will guide you through the next steps.', date '2020-01-01', now(), 'SYSTEM'),
('QUOTATION_TERMS', 1, 'Terms and conditions',
 'This quotation is subject to the terms, conditions, warranties and exclusions of the insurer''s standard policy wording and to the information supplied by the client being complete and correct. Cover starts only after acceptance, payment or insurer confirmation as applicable. Premium includes Documentary Stamp Tax, Value Added Tax / Premium Tax, Fire Service Tax and Local Government Tax where applicable.', date '2020-01-01', now(), 'SYSTEM'),
('QUOTATION_SLIP', 1, 'Quotation slip',
 'BDO Insurance and Reinsurance Brokers, Inc. requests your best terms for the risk described below, reference {{reference}}. Please reply with premium rate, deductibles, conditions and validity on or before {{replyBy}}.', date '2020-01-01', now(), 'SYSTEM'),
('PROPOSAL_SLIP', 1, 'Proposal slip',
 'Based on the terms received from the insurers approached, we propose the following cover for {{clientName}}, reference {{reference}}. The recommended insurer and terms are shown below; all other terms and conditions are as per the quotation slip.', date '2020-01-01', now(), 'SYSTEM'),
('PLACEMENT_SLIP', 1, 'Placement slip',
 'Please place the following risk(s) under reference {{reference}} and issue the policy / policies accordingly. Kindly send the e-policy to BDOI quoting our Account Reference Number.', date '2020-01-01', now(), 'SYSTEM'),
('HOLD_COVER_REQUEST', 1, 'Request for hold cover',
 'Please hold cover the risk below for thirty (30) days from {{startDate}} under reference {{reference}} while the placement is being completed. Kindly confirm the hold cover and your reference number.', date '2020-01-01', now(), 'SYSTEM'),
('INSURANCE_ADVICE', 1, 'Insurance advice',
 'This is to advise that the property / unit described below, mortgaged to {{mortgagee}}, is insured with {{insurerName}} under policy {{policyNo}} for the period {{periodFrom}} to {{periodTo}}, with {{mortgagee}} as mortgagee / loss payee.', date '2020-01-01', now(), 'SYSTEM'),
('EPOLICY_EMAIL', 1, 'Your e-policy',
 'Dear {{clientName}},

Attached is your e-policy {{policyNo}} issued by {{insurerName}} (our reference {{reference}}). The document is password protected; the password is sent to you in a separate e-mail.

Thank you for insuring through BDO Insurance and Reinsurance Brokers, Inc.', date '2020-01-01', now(), 'SYSTEM'),
('SERVICE_INVOICE_NOTE', 1, 'Service invoice',
 'Service invoice for brokerage services rendered on the placement(s) listed, reference {{reference}}. Please settle within {{creditDays}} days.', date '2020-01-01', now(), 'SYSTEM');
