-- =====================================================================================
-- iNXT BrokerVerse - V756 Word renditions of generated documents (client requirement 16;
-- BRNB.004 document generation).
-- Every PDF composed by DocumentComposer is recorded with the SHA-256 of its bytes and the
-- document content (DocumentSpec as JSON) and date, so the same document can be downloaded
-- again as Word with identical content: the client presents the PDF it holds and receives
-- its Word copy. Documents that are not composed (BIR 2307 form, merged print batches,
-- password-protected e-mail attachments) have no rendition and stay PDF only.
-- =====================================================================================
create table doc_rendition (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    sha256      varchar(64)   not null,
    title       varchar(200)  not null,
    reference   varchar(200),
    doc_date    date          not null,
    spec        text          not null,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_doc_rendition_sha256 unique (sha256)
);

comment on table doc_rendition is
    'Content of each composed PDF by SHA-256, for its Word copy (client requirement 16)';
