-- =====================================================================================
-- iNXT BrokerVerse - V761 Operations invoice ledger (opsledger).
--   One row per booked invoice or endorsement invoice copied from booking (BRNB.027), with its
--   components and their outstanding balances, insurer shares (ADJID.027), every movement
--   (RMTID.038, ADJID.024), status history (RMTID.032), locks (RMTID.040) and cumulative
--   adjustments (ADJID.028); the flow-in framework (BRQID.004/005); the default Disbursement
--   queue (OQ02); the in-system extract repository (RMTID.001, OQ17) and the hand-offs of the
--   default port adapters.
--   Design: docs/architecture/OPERATIONS_DESIGN.md sections 3 and 4.1.
--   No foreign keys to V8xx tables: invoice no., ARN, client, insurer and account id are plain
--   values (V760-V789 run before booking V870 on a fresh database).
-- =====================================================================================

create table ops_invoice (
    id                 bigint generated by default as identity primary key,
    version            bigint        not null default 0,
    company_id         bigint        not null references org_company (id),
    branch_id          bigint        not null references org_branch (id),
    invoice_no         varchar(40)   not null unique,
    arn                varchar(30)   not null,
    account_id         bigint,
    kind               varchar(20)   not null,
    endorsement_no     varchar(40),
    parent_invoice_no  varchar(40),
    policy_no          varchar(60),
    policy_year        integer       not null default 1,
    pn_nos             varchar(500),
    client_code        varchar(30)   not null,
    assured_name       varchar(250)  not null,
    payor_name         varchar(250),
    insurer_code       varchar(30)   not null,
    currency           varchar(3)    not null,
    booking_date       date          not null,
    inception_date     date          not null,
    expiry_date        date          not null,
    risk_code          varchar(20),
    product_line       varchar(30),
    segment            varchar(40),
    ao_username        varchar(50),
    sales_unit         varchar(20),
    cost_center        varchar(20),
    gross_premium      numeric(19, 2) not null,
    commission         numeric(19, 2) not null,
    vat_on_commission  numeric(19, 2) not null,
    wtax_rate          numeric(9, 4)  not null,
    dp_flag            boolean       not null default false,
    cwt_flag           boolean       not null default false,
    incentive_eligible boolean       not null default false,
    payment_status     varchar(20)   not null,
    remittance_status  varchar(30)   not null,
    hold_flag          boolean       not null default false,
    pending_neg_adj    boolean       not null default false,
    written_off        boolean       not null default false,
    cancelled          boolean       not null default false,
    estimated          boolean       not null default false,
    lock_owner         varchar(30),
    lock_reason        varchar(200),
    locked_at          timestamptz,
    locked_by          varchar(50),
    feed_source        varchar(20)   not null,
    created_at         timestamptz   not null,
    created_by         varchar(50)   not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_ops_invoice_kind check (kind in ('BOOKING', 'ENDORSEMENT_PLUS', 'ENDORSEMENT_MINUS', 'CANCELLATION')),
    constraint ck_ops_invoice_payment check (payment_status in ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'NOT_APPLICABLE')),
    constraint ck_ops_invoice_remittance check (remittance_status in ('UNPROCESSED', 'UNAPPLIED_PAYMENT',
        'WITH_OUTSTANDING_BALANCE', 'REVIEW_IN_PROCESS', 'REQUESTED_FOR_HOLD', 'APPROVED',
        'PARTIALLY_REMITTED', 'FULLY_REMITTED', 'NOT_APPLICABLE')),
    constraint ck_ops_invoice_lock check ((lock_owner is null) = (locked_at is null)),
    constraint ck_ops_invoice_period check (expiry_date >= inception_date)
);
create index ix_ops_invoice_arn on ops_invoice (arn);
create index ix_ops_invoice_company_booking on ops_invoice (company_id, booking_date);
create index ix_ops_invoice_insurer on ops_invoice (company_id, insurer_code, remittance_status);
create index ix_ops_invoice_client on ops_invoice (company_id, client_code);
create index ix_ops_invoice_payment on ops_invoice (company_id, payment_status);
create index ix_ops_invoice_flags on ops_invoice (company_id)
    where hold_flag or pending_neg_adj or written_off or lock_owner is not null;
create index ix_ops_invoice_policy on ops_invoice (policy_no);

create table ops_invoice_share (
    invoice_id  bigint        not null references ops_invoice (id),
    share_index integer       not null,
    insurer_code varchar(30)  not null,
    share_pct   numeric(9, 4) not null check (share_pct > 0 and share_pct <= 100),
    lead        boolean       not null,
    primary key (invoice_id, share_index)
);
create index ix_ops_invoice_share_insurer on ops_invoice_share (insurer_code);

create table ops_invoice_component (
    id          bigint generated by default as identity primary key,
    version     bigint         not null default 0,
    invoice_id  bigint         not null references ops_invoice (id),
    component   varchar(20)    not null,
    booked      numeric(19, 2) not null default 0,
    applied     numeric(19, 2) not null default 0,
    reversed    numeric(19, 2) not null default 0,
    remitted    numeric(19, 2) not null default 0,
    adjusted    numeric(19, 2) not null default 0,
    written_off numeric(19, 2) not null default 0,
    balance     numeric(19, 2) not null default 0,
    created_at  timestamptz    not null,
    created_by  varchar(50)    not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint uq_ops_invoice_component unique (invoice_id, component),
    constraint ck_ops_invoice_component check (component in ('BASIC', 'DST', 'PREMIUM_TAX_VAT', 'LGT',
        'FST', 'OTHER', 'DTIP', 'COMMISSION', 'COMMISSION_VAT', 'WTAX', 'PR2307')),
    constraint ck_ops_invoice_component_balance check (
        balance = booked + adjusted - applied + reversed - remitted - written_off)
);

create table ops_invoice_movement (
    id               bigint generated by default as identity primary key,
    invoice_id       bigint         not null references ops_invoice (id),
    movement_type    varchar(20)    not null,
    component        varchar(20)    not null,
    amount           numeric(19, 2) not null,
    source_module    varchar(30)    not null,
    source_ref       varchar(80)    not null,
    ar_no            varchar(40),
    or_no            varchar(40),
    batch_no         varchar(40),
    value_date       date           not null,
    journal_batch_no varchar(40),
    remarks          varchar(250),
    posted_at        timestamptz    not null,
    posted_by        varchar(50)    not null,
    constraint uq_ops_invoice_movement unique (source_module, source_ref, invoice_id, component, movement_type),
    constraint ck_ops_invoice_movement_type check (movement_type in ('BOOKED', 'APPLIED', 'UNAPPLIED',
        'REMITTED', 'ADJUSTED', 'WRITE_OFF', 'DP_REVERSAL', 'CWT_RECLASS', 'MIN_BAL'))
);
create index ix_ops_invoice_movement_invoice on ops_invoice_movement (invoice_id, posted_at);
create index ix_ops_invoice_movement_ref on ops_invoice_movement (ar_no);

create table ops_invoice_status_change (
    id          bigint generated by default as identity primary key,
    invoice_id  bigint       not null references ops_invoice (id),
    field       varchar(30)  not null,
    from_value  varchar(40),
    to_value    varchar(40),
    module      varchar(30)  not null,
    reason      varchar(250),
    changed_at  timestamptz  not null,
    changed_by  varchar(50)  not null
);
create index ix_ops_invoice_status_change on ops_invoice_status_change (invoice_id, changed_at);

create table ops_invoice_adjustment_total (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    original_invoice_no varchar(40)    not null unique,
    original_premium    numeric(19, 2) not null,
    original_dtip       numeric(19, 2) not null,
    original_commission numeric(19, 2) not null,
    adjusted_premium    numeric(19, 2) not null default 0,
    adjusted_dtip       numeric(19, 2) not null default 0,
    adjusted_commission numeric(19, 2) not null default 0,
    adjustment_count    integer        not null default 0,
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);

-- ---------- Flow-in framework (BRQID.004/005) ----------------------------------------------
create table ops_flow_in_feed (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    code           varchar(40)  not null unique,
    name           varchar(120) not null,
    partner_system varchar(30)  not null,
    direction      varchar(10)  not null check (direction in ('INBOUND', 'OUTBOUND')),
    transport      varchar(20)  not null check (transport in ('MANUAL_UPLOAD', 'FILE_DROP', 'IN_APP', 'API', 'SFTP')),
    owner_module   varchar(30)  not null,
    cron           varchar(60)  not null default '-',
    active         boolean      not null default true,
    description    varchar(300),
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);

create table ops_flow_in_run (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    feed_code     varchar(40)   not null references ops_flow_in_feed (code),
    run_no        varchar(30)   not null unique,
    trigger_type  varchar(20)   not null check (trigger_type in ('SCHEDULED', 'MANUAL', 'UPLOAD', 'EVENT', 'REPLAY')),
    status        varchar(20)   not null check (status in ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    started_at    timestamptz   not null,
    ended_at      timestamptz,
    read_count    integer       not null default 0,
    ok_count      integer       not null default 0,
    duplicate_count integer     not null default 0,
    failed_count  integer       not null default 0,
    file_name     varchar(255),
    file_sha256   varchar(64),
    message       varchar(1000),
    error_detail  text,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create index ix_ops_flow_in_run_feed on ops_flow_in_run (feed_code, started_at);

create table ops_flow_in_record (
    id              bigint generated by default as identity primary key,
    feed_code       varchar(40)   not null references ops_flow_in_feed (code),
    run_id          bigint        not null references ops_flow_in_run (id),
    idempotency_key varchar(120)  not null,
    payload_hash    varchar(64)   not null,
    status          varchar(20)   not null check (status in ('ACCEPTED', 'FAILED')),
    reference       varchar(100),
    message         varchar(500),
    received_at     timestamptz   not null,
    constraint uq_ops_flow_in_record unique (feed_code, idempotency_key)
);
create index ix_ops_flow_in_record_run on ops_flow_in_record (run_id);

insert into ops_flow_in_feed (code, name, partner_system, direction, transport, owner_module, description,
    created_at, created_by) values
    ('OPS_INVOICE_FEED', 'Booked invoices from booking', 'BOOKING', 'INBOUND', 'IN_APP', 'OPSLEDGER',
     'Every booked invoice, endorsement and cancellation copied into the invoice ledger (event, replay)', now(), 'SYSTEM'),
    ('COLLECTION_CHECK_PICKUP', 'Checks for pick-up', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'CASHIERING',
     'Checks tagged for pick-up by Collection (CSHID.009, OQ01/OQ13)', now(), 'SYSTEM'),
    ('COLLECTION_CWT2307', 'BIR 2307 tags', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'CASHIERING',
     'BIR 2307 reversal tags and certificates from Marketing Collection (CSHID.026, MKTID.013)', now(), 'SYSTEM'),
    ('COLLECTION_COMMISSION_PAYMENT', 'Commission payment details', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'CASHIERING',
     'Commission payment details for commission ORs (CSHID.007)', now(), 'SYSTEM'),
    ('COLLECTION_HOLD', 'Remittance holds', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'REMITTANCE',
     'Hold information from Marketing / Collection (RMTID.021, MKTID.003)', now(), 'SYSTEM'),
    ('COLLECTION_SPECIAL_REMIT', 'Special remittance requests', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'REMITTANCE',
     'Special remittance requests (RMTID.030, MKTID.009)', now(), 'SYSTEM'),
    ('COLLECTION_DP_LIST', 'Direct payment lists', 'COLLECTION', 'INBOUND', 'MANUAL_UPLOAD', 'COMMISSION',
     'Direct payment lists of HO and branches (CMRID.001, OQ38)', now(), 'SYSTEM'),
    ('COLLECTION_DP_RETURNED', 'Returned direct payment accounts', 'COLLECTION', 'OUTBOUND', 'IN_APP', 'COMMISSION',
     'Direct payment accounts rejected by the insurer, returned to Collection (CMRID.009)', now(), 'SYSTEM'),
    ('COLLECTION_REFUND', 'Refunds to clients', 'COLLECTION', 'OUTBOUND', 'IN_APP', 'CASHIERING',
     'Refund dispositions handed to Collection / Disbursement (CSHID.024)', now(), 'SYSTEM'),
    ('DISBURSEMENT_REQUEST', 'Payment requests to Disbursement', 'DISBURSEMENT', 'OUTBOUND', 'IN_APP', 'OPSLEDGER',
     'Remittance payment requests, refunds, 2307 reports and pass-on (RMTID.011, DBMID.001, OQ02)', now(), 'SYSTEM'),
    ('DISBURSEMENT_STATUS', 'Disbursement status and DV numbers', 'DISBURSEMENT', 'INBOUND', 'IN_APP', 'OPSLEDGER',
     'DV number and payment status of the requests (RMTID.019, OQ02)', now(), 'SYSTEM'),
    ('INSURER_REMIT_OR', 'Insurer OR schedules', 'INSURER', 'INBOUND', 'MANUAL_UPLOAD', 'REMITTANCE',
     'Insurer-populated remittance schedules with OR numbers (RMTID.012/013)', now(), 'SYSTEM'),
    ('INSURER_PRODUCTION', 'Insurer production reports', 'INSURER', 'INBOUND', 'MANUAL_UPLOAD', 'PRODRECON',
     'Insurer production reports and feedback (PRCID.009/010)', now(), 'SYSTEM'),
    ('INSURER_DP_RESPONSE', 'Insurer direct payment responses', 'INSURER', 'INBOUND', 'MANUAL_UPLOAD', 'COMMISSION',
     'Insurer approval or rejection of direct payment commission billings (CMRID.009)', now(), 'SYSTEM');

-- ---------- Default Disbursement queue (DisbursementGateway default adapter, OQ02) ----------
create table ops_disbursement_request (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    company_id   bigint         not null references org_company (id),
    request_no   varchar(30)    not null unique,
    request_type varchar(20)    not null check (request_type in ('REMITTANCE', 'REFUND', 'CWT2307', 'PASS_ON')),
    source_module varchar(30)   not null,
    source_ref   varchar(80)    not null,
    payee_code   varchar(30)    not null,
    payee_name   varchar(250),
    currency     varchar(3)     not null,
    amount       numeric(19, 2) not null check (amount > 0),
    description  varchar(500),
    status       varchar(20)    not null check (status in ('SENT', 'ACKNOWLEDGED', 'DV_ASSIGNED', 'PAID', 'RETURNED')),
    dv_no        varchar(40),
    sent_at      timestamptz    not null,
    acknowledged_at timestamptz,
    dv_assigned_at  timestamptz,
    paid_at      timestamptz,
    returned_at  timestamptz,
    return_reason varchar(250),
    attachment_ref varchar(80),
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_ops_disbursement_source unique (source_module, source_ref)
);
create index ix_ops_disbursement_status on ops_disbursement_request (company_id, status);

-- ---------- In-system extract repository (FileDropPort default adapter, OQ17) --------------
create table ops_extract_file (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    company_id   bigint        not null references org_company (id),
    folder       varchar(120)  not null,
    file_name    varchar(255)  not null,
    content_type varchar(100)  not null,
    size_bytes   bigint        not null,
    sha256       varchar(64)   not null,
    content      bytea         not null,
    source_module varchar(30)  not null,
    source_ref   varchar(80),
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_ops_extract_file unique (company_id, folder, file_name)
);

-- ---------- Hand-offs of the default port adapters ------------------------------------------
create table ops_handoff (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    company_id   bigint         not null references org_company (id),
    port         varchar(40)    not null,
    source_module varchar(30)   not null,
    source_ref   varchar(80)    not null,
    reference    varchar(80),
    amount       numeric(19, 2),
    currency     varchar(3),
    summary      varchar(500)   not null,
    payload      text,
    status       varchar(20)    not null check (status in ('OPEN', 'CLOSED')),
    closed_at    timestamptz,
    closed_by    varchar(50),
    closing_note varchar(250),
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_ops_handoff unique (port, source_module, source_ref)
);
create index ix_ops_handoff_open on ops_handoff (company_id, status);
