-- =====================================================================================
-- iNXT BrokerVerse - V762 Platform extensions for Operations (OPERATIONS_DESIGN section 2):
--   * bulk: SHA-256 of the uploaded file (duplicate upload block, CSHID.008, PRCID.010),
--     handler outcome categories per row and reprocessing of failed rows (BRQID.006);
--   * report: archive of report runs and exports with a view / export split (CSHID.017/018);
--   * messaging: notification preferences per user and event (RMTID.034).
--   The BOOK exchange rate type (CSHID.012-014) is an enum value of currency.domain.RateType;
--   cur_exchange_rate.rate_type needs no change.
-- =====================================================================================

-- ---------- Bulk --------------------------------------------------------------------------
alter table bulk_job
    add column file_sha256     varchar(64),
    add column reprocess_count integer not null default 0;
create index ix_bulk_job_sha256 on bulk_job (company_id, handler_code, file_sha256);

alter table bulk_row
    add column outcome  varchar(40),
    add column attempts integer not null default 0;
create index ix_bulk_row_outcome on bulk_row (job_id, outcome);

-- ---------- Report run archive -----------------------------------------------------------
create table report_run (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    report_code  varchar(40)   not null,
    title        varchar(200)  not null,
    category     varchar(40)   not null,
    parameters   varchar(2000),
    action       varchar(10)   not null check (action in ('VIEW', 'EXPORT')),
    format       varchar(10),
    row_count    integer       not null default 0,
    file_name    varchar(255),
    content_type varchar(100),
    size_bytes   bigint,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_report_run_file check (action = 'VIEW' or format is not null)
);
create index ix_report_run_code on report_run (report_code, created_at);
create index ix_report_run_creator on report_run (created_by, created_at);

create table report_run_file (
    run_id  bigint primary key references report_run (id),
    content bytea  not null
);

-- ---------- Notification preferences ------------------------------------------------------
create table msg_notification_event (
    code          varchar(40)  primary key,
    name          varchar(120) not null,
    module        varchar(30)  not null,
    description   varchar(300),
    default_in_app boolean     not null default true,
    default_email  boolean     not null default false,
    sort_order    integer      not null default 0
);

create table msg_notification_preference (
    id         bigint generated by default as identity primary key,
    version    bigint       not null default 0,
    username   varchar(50)  not null,
    event_code varchar(40)  not null references msg_notification_event (code),
    in_app     boolean      not null,
    email      boolean      not null,
    created_at timestamptz  not null,
    created_by varchar(50)  not null,
    updated_at timestamptz,
    updated_by varchar(50),
    constraint uq_msg_notification_preference unique (username, event_code)
);

insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('OPS_INVOICE_LOCKED', 'Invoice locked or released', 'OPSLEDGER',
     'An invoice you work on was locked by another team or released (RMTID.040)', true, false, 10),
    ('OPS_FLOW_IN_FAILED', 'Interface run failed', 'OPSLEDGER',
     'A flow-in or flow-out run failed or had failed records (BRQID.005)', true, true, 20),
    ('OPS_DISBURSEMENT_STATUS', 'Disbursement status', 'OPSLEDGER',
     'A payment request was acknowledged, received its DV number, was paid or returned (RMTID.019)', true, false, 30),
    ('REMIT_EXTRACTION_DONE', 'Remittance extraction completed', 'REMITTANCE',
     'A scheduled or manual remittance extraction finished (RMTID.001/034)', true, true, 40),
    ('REMIT_BATCH_FOR_APPROVAL', 'Remittance batch for approval', 'REMITTANCE',
     'A remittance batch was submitted for approval (RMTID.034)', true, true, 50),
    ('REMIT_BATCH_DECIDED', 'Remittance batch approved or returned', 'REMITTANCE',
     'A remittance batch you prepared was approved or returned (RMTID.034)', true, false, 60),
    ('REMIT_NEG_ADJ_PENDING', 'Negative adjustment on a remittance invoice', 'REMITTANCE',
     'A negative adjustment was requested on an invoice in remittance (RMTID.020/035)', true, true, 70),
    ('HOLD_EXPIRING', 'Remittance hold expiring', 'REMITTANCE',
     'A remittance hold reaches its hold date (RMTID.021)', true, false, 80),
    ('CASH_APPROVAL_REQUEST', 'Cashiering approval request', 'CASHIERING',
     'A receipt cancellation, reinstatement or disposition waits for approval (CSHID.001-005/024)', true, false, 90),
    ('RECON_FEEDBACK_UPLOADED', 'Insurer reconciliation feedback', 'PRODRECON',
     'An insurer production feedback was uploaded and matched (PRCID.009/022)', true, false, 100),
    ('ADJ_REQUEST_STATUS', 'Endorsement request status', 'ADJUSTMENT',
     'An endorsement request you raised was returned, approved or posted (ADJID.005/007)', true, false, 110),
    ('DP_FEEDBACK_OVERDUE', 'Direct payment feedback overdue', 'COMMISSION',
     'An insurer has not answered a direct payment billing in time (CMRID.011)', true, true, 120);
