-- =====================================================================================
-- iNXT BrokerVerse - V763 Cashiering (Operations BRD-2, OPERATIONS_DESIGN 4.2)
--   Requirements: docs/requirements/BDOI_OPS_BRD_SPEC.md
--     CSHID.001-009  AR / OR, series, cancellation, reinstatement, payment files, PDC, pick-up
--     CSHID.010-016  search log, accounting, series control, minimal balances
--     CSHID.019      batch printing
--     CSHID.020-025  matching, application, pre-booked, unapplied payments and dispositions
--     CSHID.026/027, MKTID.010/013, DBMID.001  BIR 2307 tagging, validation and routing
--   Keys of other Operations / NB modules (invoice no., ARN, client, insurer) are plain values:
--   no foreign key to a V8xx table (OPERATIONS_DESIGN section 3).
-- =====================================================================================

-- ---------- Receipt series (CSHID.006/015, OQ05) ----------------------------------------------
create table csh_receipt_series (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    branch_id      bigint       not null references org_branch (id),
    kind           varchar(2)   not null check (kind in ('AR', 'OR')),
    atp_no         varchar(40),
    prefix         varchar(20)  not null,
    from_no        bigint       not null check (from_no > 0),
    to_no          bigint       not null,
    next_no        bigint       not null,
    warn_at        integer      not null default 0 check (warn_at >= 0),
    record_status  varchar(30)  not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_csh_series_range check (to_no >= from_no and next_no between from_no and to_no + 1),
    constraint uq_csh_series_prefix unique (company_id, prefix, from_no)
);
create index ix_csh_series_branch on csh_receipt_series (company_id, branch_id, kind);

-- ---------- Receipts: AR and OR (CSHID.001/002) ----------------------------------------------
create table csh_receipt (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    receipt_no        varchar(40)    not null,
    kind              varchar(2)     not null check (kind in ('AR', 'OR')),
    receipt_class     varchar(30)    not null,
    series_id         bigint         references csh_receipt_series (id),
    receipt_date      date           not null,
    payor_code        varchar(30),
    payor_name        varchar(250)   not null,
    assured_name      varchar(250),
    sales_unit        varchar(40),
    currency          varchar(3)     not null,
    book_rate         numeric(19, 2) not null,
    amount            numeric(19, 2) not null check (amount >= 0),
    base_amount       numeric(19, 2) not null,
    gross             numeric(19, 2) not null default 0,
    vat               numeric(19, 2) not null default 0,
    wtax              numeric(19, 2) not null default 0,
    applied_amount    numeric(19, 2) not null default 0,
    payment_mode      varchar(20)    not null,
    check_no          varchar(40),
    check_bank        varchar(60),
    check_date        date,
    certificate_ref   varchar(60),
    source            varchar(20)    not null,
    source_module     varchar(30),
    source_ref        varchar(80),
    status            varchar(20)    not null check (status in ('ISSUED', 'CANCELLED', 'REINSTATED')),
    reinstated_amount numeric(19, 2),
    printed_count     integer        not null default 0,
    last_printed_at   timestamptz,
    journal_batch_no  varchar(40),
    remarks           varchar(250),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_csh_receipt_no unique (receipt_no),
    constraint uq_csh_receipt_source unique (company_id, source_module, source_ref),
    constraint ck_csh_receipt_mode check (payment_mode in ('CASH', 'CHECK', 'BILLS_PAYMENT', 'TRADE', 'CLPC',
        'PDC', 'DIRECT_CREDIT', 'ADA', 'CREDIT_TO_ACCOUNT', 'NON_CASH')),
    constraint ck_csh_receipt_source check (source in ('OTC', 'UPLOAD', 'PDC', 'PICKUP', 'SETTLEMENT',
        'COMMISSION_UPLOAD', 'CWT', 'REINSTATEMENT'))
);
create index ix_csh_receipt_company on csh_receipt (company_id, receipt_date);
create index ix_csh_receipt_payor on csh_receipt (company_id, lower(payor_name));
create index ix_csh_receipt_payor_code on csh_receipt (payor_code);

-- OR lines: one per invoice or commission item (CSHID.007 consolidation per insurer and certificate)
create table csh_receipt_line (
    receipt_id   bigint         not null references csh_receipt (id),
    line_no      integer        not null,
    invoice_no   varchar(40),
    insurer_code varchar(30),
    gross        numeric(19, 2) not null,
    vat          numeric(19, 2) not null,
    wtax         numeric(19, 2) not null,
    net          numeric(19, 2) not null,
    description  varchar(250),
    primary key (receipt_id, line_no)
);
create index ix_csh_receipt_line_invoice on csh_receipt_line (invoice_no);

-- Cancellation and reinstatement transactions (CSHID.001-005, workflow OPS_RECEIPT_ACTION)
create table csh_receipt_action (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    receipt_id       bigint         not null references csh_receipt (id),
    transaction_no   varchar(30)    not null unique,
    action           varchar(20)    not null check (action in ('CANCEL', 'REINSTATE_FULL', 'REINSTATE_PARTIAL')),
    reason_code      varchar(40)    not null,
    reason_text      varchar(250),
    amount           numeric(19, 2) not null check (amount >= 0),
    invoice_no       varchar(40),
    document_no      varchar(40),
    payor_name       varchar(250),
    account_officer  varchar(50),
    unit_head        varchar(100),
    team_leader      varchar(100),
    stage            varchar(20)    not null,
    approved_by      varchar(50),
    approved_at      timestamptz,
    journal_batch_no varchar(40),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_csh_receipt_action_receipt on csh_receipt_action (receipt_id);

-- ---------- Payments received (CSHID.008/020) -------------------------------------------------
create table csh_payment (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    branch_id        bigint         not null references org_branch (id),
    payment_no       varchar(30)    not null unique,
    channel          varchar(20)    not null check (channel in ('OTC', 'BILLS_PAYMENT', 'TRADE', 'CLPC', 'PDC',
        'DIRECT_CREDIT', 'PICKUP', 'CWT')),
    batch_ref        varchar(40),
    source_key       varchar(120)   not null,
    row_no           integer,
    reference        varchar(80),
    other_refs       varchar(300),
    payor_name       varchar(250)   not null,
    assured_name     varchar(250),
    amount           numeric(19, 2) not null check (amount > 0),
    currency         varchar(3)     not null,
    value_date       date           not null,
    paid_time        varchar(10),
    late_deposit     boolean        not null default false,
    payment_mode     varchar(20)    not null,
    check_no         varchar(40),
    check_bank       varchar(60),
    match_category   varchar(30)    not null check (match_category in ('APPLIED', 'PREBOOKED', 'UNAPPLIED_NO_MATCH',
        'EXCESS', 'CANCELLED_REFERENCE')),
    matched_ref      varchar(40),
    receipt_id       bigint         references csh_receipt (id),
    applied_amount   numeric(19, 2) not null default 0,
    unapplied_amount numeric(19, 2) not null default 0,
    message          varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_csh_payment_source unique (company_id, channel, source_key)
);
create index ix_csh_payment_batch on csh_payment (batch_ref);
create index ix_csh_payment_category on csh_payment (company_id, match_category, value_date);

-- ---------- Unapplied payments and dispositions (CSHID.024/025, workflow OPS_DISPOSITION) -----
create table csh_unapplied (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    branch_id        bigint         not null references org_branch (id),
    reference        varchar(30)    not null unique,
    origin           varchar(30)    not null check (origin in ('NO_MATCH', 'EXCESS', 'CANCELLED_REFERENCE',
        'ADJUSTMENT', 'CANCELLATION', 'DP_REINSTATE', 'REMITTANCE_RETURN', 'REAPPLY', 'PREBOOKED', 'OTHER')),
    receipt_id       bigint         references csh_receipt (id),
    payment_id       bigint         references csh_payment (id),
    invoice_no       varchar(40),
    client_code      varchar(30),
    payor_name       varchar(250),
    sales_unit       varchar(40),
    currency         varchar(3)     not null,
    amount           numeric(19, 2) not null check (amount > 0),
    balance          numeric(19, 2) not null check (balance >= 0),
    stage            varchar(20)    not null,
    disposition_hint varchar(40),
    source_module    varchar(30)    not null,
    source_ref       varchar(80)    not null,
    remarks          varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_csh_unapplied_source unique (company_id, source_module, source_ref),
    constraint ck_csh_unapplied_balance check (balance <= amount)
);
create index ix_csh_unapplied_stage on csh_unapplied (company_id, stage);
create index ix_csh_unapplied_client on csh_unapplied (client_code);

create table csh_disposition_type_rule (
    type_code         varchar(40)  primary key,
    action            varchar(20)  not null check (action in ('APPLY', 'DST_APPLY', 'REFUND', 'RECLASS', 'TRANSFER',
        'MANUAL')),
    requires_approval boolean      not null,
    description       varchar(250) not null
);

create table csh_disposition (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    unapplied_id            bigint         not null references csh_unapplied (id),
    disposition_type        varchar(40)    not null references csh_disposition_type_rule (type_code),
    action                  varchar(20)    not null,
    amount                  numeric(19, 2) not null check (amount > 0),
    target_invoice_no       varchar(40),
    target_client_code      varchar(30),
    target_unit             varchar(40),
    previous_client_code    varchar(30),
    previous_unit           varchar(40),
    payee_name              varchar(250),
    remarks                 varchar(250),
    status                  varchar(20)    not null check (status in ('MONITORING', 'FOR_APPROVAL', 'IN_PROCESS',
        'COMPLETED', 'FOR_REVERSAL', 'REVERSED', 'WITHDRAWN')),
    approved_by             varchar(50),
    approved_at             timestamptz,
    completed_at            timestamptz,
    application_id          bigint,
    disbursement_request_no varchar(30),
    journal_batch_no        varchar(40),
    reversal_reason         varchar(250),
    reversal_requested_by   varchar(50),
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50)
);
create index ix_csh_disposition_unapplied on csh_disposition (unapplied_id);

-- ---------- Applications per component (CSHID.020/022) ----------------------------------------
create table csh_application (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    invoice_no          varchar(40)    not null,
    arn                 varchar(30)    not null,
    client_code         varchar(30)    not null,
    receipt_id          bigint         references csh_receipt (id),
    unapplied_id        bigint         references csh_unapplied (id),
    source              varchar(20)    not null check (source in ('PAYMENT', 'PREBOOKED', 'DISPOSITION', 'REINSTATEMENT',
        'REAPPLY', 'AUTOMATCH', 'CWT')),
    source_ref          varchar(80),
    amount              numeric(19, 2) not null check (amount > 0),
    realized_commission numeric(19, 2) not null default 0,
    realized_vat        numeric(19, 2) not null default 0,
    value_date          date           not null,
    status              varchar(10)    not null check (status in ('ACTIVE', 'REVERSED')),
    reversed_at         timestamptz,
    reversal_ref        varchar(80),
    reversal_reason     varchar(250),
    journal_batch_no    varchar(40),
    reversal_journal_no varchar(40),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50)
);
create index ix_csh_application_invoice on csh_application (invoice_no, status);
create index ix_csh_application_arn on csh_application (company_id, arn);
create index ix_csh_application_receipt on csh_application (receipt_id);

create table csh_application_line (
    application_id bigint         not null references csh_application (id),
    seq            integer        not null,
    component      varchar(20)    not null,
    amount         numeric(19, 2) not null,
    primary key (application_id, seq)
);

alter table csh_disposition
    add constraint fk_csh_disposition_application foreign key (application_id) references csh_application (id);

-- ---------- Pre-booked payments (CSHID.020, OQ12) ---------------------------------------------
create table csh_prebooked (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    payment_id     bigint         not null unique references csh_payment (id),
    receipt_id     bigint         not null references csh_receipt (id),
    reference      varchar(80)    not null,
    arn            varchar(30)    not null,
    amount         numeric(19, 2) not null check (amount > 0),
    currency       varchar(3)     not null,
    first_seen     date           not null,
    last_rematch   timestamptz,
    rematch_count  integer        not null default 0,
    status         varchar(20)    not null check (status in ('OPEN', 'APPLIED', 'RELEASED')),
    resolved_at    timestamptz,
    application_id bigint         references csh_application (id),
    remarks        varchar(250),
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_csh_prebooked_open on csh_prebooked (company_id, status, arn);

-- ---------- PDC warehouse (CSHID.008 item 4) --------------------------------------------------
create table csh_pdc_item (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    company_id    bigint         not null references org_company (id),
    branch_id     bigint         not null references org_branch (id),
    warehouse_no  varchar(30)    not null unique,
    batch_ref     varchar(40),
    client_code   varchar(30),
    payor_name    varchar(250)   not null,
    reference     varchar(80)    not null,
    check_no      varchar(40)    not null,
    bank_code     varchar(30)    not null,
    check_branch  varchar(60),
    maturity_date date           not null,
    amount        numeric(19, 2) not null check (amount > 0),
    currency      varchar(3)     not null,
    segment       varchar(40),
    status        varchar(20)    not null check (status in ('WAREHOUSED', 'MATURED', 'APPLIED', 'RETURNED', 'REPLACED',
        'PULLED_OUT')),
    status_reason varchar(250),
    payment_id    bigint         references csh_payment (id),
    receipt_no    varchar(40),
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_csh_pdc_check unique (company_id, bank_code, check_no)
);
create index ix_csh_pdc_maturity on csh_pdc_item (company_id, status, maturity_date);

-- ---------- Check pick-up requests (CSHID.009, OQ13) -----------------------------------------
create table csh_pickup_request (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    branch_id      bigint         not null references org_branch (id),
    collection_ref varchar(40)    not null,
    reference      varchar(80)    not null,
    client_code    varchar(30),
    payor_name     varchar(250)   not null,
    assured_name   varchar(250),
    pickup_date    date           not null,
    requested_at   timestamptz    not null,
    requestor      varchar(100)   not null,
    amount         numeric(19, 2) not null check (amount > 0),
    currency       varchar(3)     not null,
    check_no       varchar(40),
    check_bank     varchar(60),
    status         varchar(20)    not null check (status in ('FOR_PICKUP', 'AR_PRINTED', 'CANCELLED')),
    receipt_no     varchar(40),
    payment_id     bigint         references csh_payment (id),
    printed_at     timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_csh_pickup_ref unique (company_id, collection_ref)
);
create index ix_csh_pickup_date on csh_pickup_request (company_id, status, pickup_date);

-- ---------- BIR 2307 (CSHID.026/027, MKTID.010/013, DBMID.001; workflow OPS_CWT_2307) ---------
create table csh_cwt_batch (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    company_id              bigint         not null references org_company (id),
    batch_no                varchar(30)    not null unique,
    insurer_code            varchar(30)    not null,
    tag_count               integer        not null,
    total_amount            numeric(19, 2) not null,
    status                  varchar(20)    not null check (status in ('REPORT_POSTED', 'WITH_DISBURSEMENT', 'RELEASED')),
    routed_at               timestamptz,
    disbursement_request_no varchar(30),
    released_at             timestamptz,
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50)
);

create table csh_cwt_tag (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    reference          varchar(30)    not null unique,
    invoice_no         varchar(40)    not null,
    arn                varchar(30)    not null,
    client_code        varchar(30)    not null,
    insurer_code       varchar(30)    not null,
    amount             numeric(19, 2) not null check (amount > 0),
    path               varchar(20)    not null check (path in ('CASH', 'CERTIFICATE')),
    certificate_no     varchar(60),
    period_from        date,
    period_to          date,
    cwt_copy_received  boolean        not null default false,
    remitted           boolean        not null default false,
    stage              varchar(20)    not null,
    batch_id           bigint         references csh_cwt_batch (id),
    receipt_no         varchar(40),
    reclass_journal_no varchar(40),
    offset_journal_no  varchar(40),
    remarks            varchar(250),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_csh_cwt_certificate check (path = 'CASH' or certificate_no is not null)
);
create index ix_csh_cwt_tag_stage on csh_cwt_tag (company_id, stage);
create index ix_csh_cwt_tag_invoice on csh_cwt_tag (invoice_no);

-- ---------- Minimal balances (CSHID.016, summary 5.f, OQ11) -----------------------------------
create table csh_minimal_balance_rule (
    kind                  varchar(20)    primary key check (kind in ('PREMIUM', 'EXCESS', 'COMMISSION')),
    max_amount            numeric(19, 2) not null check (max_amount >= 0),
    exclude_cwt           boolean        not null,
    exclude_dst           boolean        not null,
    exclude_whole_premium boolean        not null,
    action                varchar(20)    not null check (action in ('REVERSE', 'OVERAGES')),
    active                boolean        not null,
    description           varchar(250)   not null
);

create table csh_minimal_balance (
    id               bigint generated by default as identity primary key,
    company_id       bigint         not null references org_company (id),
    kind             varchar(20)    not null,
    subject_ref      varchar(40)    not null,
    invoice_no       varchar(40),
    client_code      varchar(30),
    sales_unit       varchar(40),
    amount           numeric(19, 2) not null,
    components       varchar(200),
    journal_batch_no varchar(40),
    swept_on         date           not null,
    swept_at         timestamptz    not null,
    swept_by         varchar(50)    not null,
    constraint uq_csh_minimal_balance unique (kind, subject_ref)
);
create index ix_csh_minimal_balance_date on csh_minimal_balance (company_id, swept_on);

-- ---------- Payment file layouts (CSHID.008, OQ03/OQ04) ----------------------------------------
create table csh_payment_file_layout (
    handler_code varchar(40)   primary key,
    kind         varchar(20)   not null check (kind in ('AUTO', 'DELIMITED', 'FIXED_WIDTH')),
    delimiter    varchar(1),
    fields       varchar(1000),
    description  varchar(250)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);

-- ---------- Commission payment details (CSHID.007, OQ49) ---------------------------------------
create table csh_commission_line (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    job_no          varchar(40)    not null,
    row_no          integer        not null,
    insurer_code    varchar(30)    not null,
    payee_name      varchar(250)   not null,
    certificate_ref varchar(60),
    payment_ref     varchar(60)    not null,
    invoice_no      varchar(40),
    gross           numeric(19, 2) not null,
    vat             numeric(19, 2) not null,
    wtax            numeric(19, 2) not null,
    payment_date    date           not null,
    status          varchar(20)    not null check (status in ('STAGED', 'ISSUED', 'REJECTED')),
    receipt_no      varchar(40),
    message         varchar(250),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_csh_commission_line unique (job_no, row_no)
);
create index ix_csh_commission_line_status on csh_commission_line (company_id, status);

-- ---------- Batch printing (CSHID.019) ---------------------------------------------------------
create table csh_print_batch (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    batch_no        varchar(30)  not null unique,
    criteria        varchar(250),
    requested_count integer      not null,
    printed_count   integer      not null,
    failed_count    integer      not null,
    status          varchar(20)  not null check (status in ('COMPLETED', 'PARTIAL', 'FAILED')),
    file_name       varchar(120),
    content         bytea,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);

create table csh_print_line (
    print_batch_id bigint       not null references csh_print_batch (id),
    line_no        integer      not null,
    receipt_id     bigint       not null references csh_receipt (id),
    receipt_no     varchar(40)  not null,
    status         varchar(10)  not null check (status in ('PRINTED', 'FAILED')),
    message        varchar(250),
    primary key (print_batch_id, line_no)
);

-- ---------- Logs: search (CSHID.010, OQ47), certificate of payment (report 19), re-application --
create table csh_search_log (
    id           bigint generated by default as identity primary key,
    company_id   bigint        not null,
    username     varchar(50)   not null,
    criteria     varchar(1000) not null,
    result_count bigint        not null,
    searched_at  timestamptz   not null
);
create index ix_csh_search_log_user on csh_search_log (username, searched_at);

create table csh_certificate_of_payment (
    id              bigint generated by default as identity primary key,
    company_id      bigint       not null references org_company (id),
    receipt_id      bigint       not null references csh_receipt (id),
    receipt_no      varchar(40)  not null,
    policy_no       varchar(60),
    requesting_unit varchar(60)  not null,
    issued_at       timestamptz  not null,
    issued_by       varchar(50)  not null
);

create table csh_reapplication (
    id              bigint generated by default as identity primary key,
    company_id      bigint         not null references org_company (id),
    invoice_no      varchar(40)    not null,
    source_module   varchar(30)    not null,
    source_ref      varchar(80)    not null,
    reason          varchar(250),
    unapplied       numeric(19, 2) not null,
    excess          numeric(19, 2) not null,
    receipt_nos     varchar(500),
    unapplied_ref   varchar(30),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    constraint uq_csh_reapplication unique (source_module, source_ref, invoice_no)
);
