-- =====================================================================================
-- iNXT BrokerVerse - V768 Cashiering batches of the legacy context (Data Migration BRD-13;
-- docs/architecture/DATA_MIGRATION_DESIGN.md sections 14.4 D, F and 24).
--   csh_legacy_batch / _line   reclassification of old unapplied payments to other income
--                              (kind INCOME_RECLASS: Cashiering user -> Cashiering team lead ->
--                              top management, BRID 5.5) and the reversal of legacy PR 2307
--                              balances against the insurer (kind PR2307_REVERSAL: requester ->
--                              approver, BRID 7.2). The maker never approves; a return needs a
--                              reason; each line posts in its own transaction.
--   Event OPS_UNAPPLIED_TO_INCOME   Dr unapplied collections (2205, or 2206 for a legacy unapplied
--                              payment: LG_AMOUNT) / Cr other income - unclaimed collections.
--   Legacy components (LG_) of the 2307 reclass and offset and of the minimal balance reversal, so
--   a legacy invoice posts on the legacy control accounts.
-- =====================================================================================

create table csh_legacy_batch (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    batch_no            varchar(20)    not null unique,
    kind                varchar(20)    not null,
    status              varchar(20)    not null,
    reason              varchar(500)   not null,
    currency            varchar(3)     not null,
    total               numeric(19, 2) not null default 0,
    line_count          integer        not null default 0,
    submitted_by        varchar(50),
    submitted_at        timestamptz,
    first_approved_by   varchar(50),
    first_approved_at   timestamptz,
    final_approved_by   varchar(50),
    final_approved_at   timestamptz,
    executed_at         timestamptz,
    posted_count        integer        not null default 0,
    failed_count        integer        not null default 0,
    return_reason       varchar(500),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint ck_csh_legacy_batch_kind check (kind in ('INCOME_RECLASS', 'PR2307_REVERSAL')),
    constraint ck_csh_legacy_batch_status check (status in ('DRAFT', 'FOR_APPROVAL', 'FOR_TOP_MANAGEMENT',
        'EXECUTED', 'CANCELLED'))
);
create index ix_csh_legacy_batch_status on csh_legacy_batch (company_id, kind, status);

create table csh_legacy_batch_line (
    id              bigint generated by default as identity primary key,
    batch_id        bigint         not null references csh_legacy_batch (id),
    line_no         integer        not null,
    unapplied_id    bigint,
    invoice_no      varchar(40),
    reference       varchar(40)    not null,
    ledger_context  varchar(10)    not null,
    amount          numeric(19, 2) not null,
    age_days        integer,
    reason          varchar(250),
    status          varchar(10)    not null default 'PENDING',
    journal_batch_no varchar(40),
    message         varchar(500),
    constraint uq_csh_legacy_batch_line unique (batch_id, line_no),
    constraint ck_csh_legacy_line_status check (status in ('PENDING', 'POSTED', 'FAILED')),
    constraint ck_csh_legacy_line_amount check (amount > 0)
);
create index ix_csh_legacy_line_unapplied on csh_legacy_batch_line (unapplied_id);

insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('OPS_UNAPPLIED_TO_INCOME', 'Unapplied payment reclassified to other income', 'RECEIPT', 'RECEIPT',
  'An old unapplied payment taken to other income - unclaimed collections after the approval of the '
  || 'Cashiering team lead and of top management (BRID 5.5): Dr unapplied collections (new or legacy) / '
  || 'Cr other income.',
  'AMOUNT,LG_AMOUNT')
on conflict (code) do nothing;

update acc_event_type
set amount_components = amount_components || ',LG_PR2307,LG_PR_BASIC,LG_PR_DST,LG_PR_PTX_VAT,LG_PR_LGT,LG_PR_FST,LG_PR_OTHER'
where code = 'OPS_CWT_RECLASS' and amount_components not like '%LG_PR2307%';

update acc_event_type
set amount_components = amount_components || ',LG_DTIP,LG_PR2307'
where code = 'OPS_CWT_DTIP_OFFSET' and amount_components not like '%LG_DTIP%';

update acc_event_type
set amount_components = amount_components || ',LG_PR_BASIC,LG_PR_DST,LG_PR_PTX_VAT,LG_PR_LGT,LG_PR_FST,LG_PR_OTHER'
where code = 'OPS_MINIMAL_BALANCE_REVERSAL' and amount_components not like '%LG_PR_BASIC%';

-- Closing transitions of an unapplied item taken to other income.
insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('OPS_DISPOSITION', 'UNAPPLIED', 'income_reclass', 'CLOSED', 'Reclassified to Other Income',
        'CASH_UPP_INCOME_APPROVE', false, null, 60),
       ('OPS_DISPOSITION', 'MONITORING', 'income_reclass', 'CLOSED', 'Reclassified to Other Income',
        'CASH_UPP_INCOME_APPROVE', false, null, 60)
on conflict do nothing;

-- Grants: the Cashiering user requests, the team lead approves first (top management, last, is
-- granted in V1080 where its role is created); the
-- legacy PR 2307 reversal is requested by the Cashiering user and approved by the team lead.
insert into sec_role_permission (role_id, permission)
select r.id, x.permission
from sec_role r
join (values ('CASHIER', 'CASH_UPP_INCOME_REQUEST'), ('CASHIER_TL', 'CASH_UPP_INCOME_REQUEST'),
             ('CASHIER', 'LEGACY_REVERSAL_REQUEST'), ('CASHIER_TL', 'LEGACY_REVERSAL_APPROVE'))
     as x(role_code, permission) on x.role_code = r.code
where not exists (select 1 from sec_role_permission p where p.role_id = r.id and p.permission = x.permission);

insert into sec_permission_action (permission, area, action)
values ('CASH_UPP_INCOME_REQUEST', 'CASHIERING', 'CREATE'),
       ('CASH_UPP_INCOME_APPROVE', 'CASHIERING', 'APPROVE'),
       ('LEGACY_REVERSAL_REQUEST', 'CASHIERING', 'CREATE'),
       ('LEGACY_REVERSAL_APPROVE', 'CASHIERING', 'APPROVE')
on conflict do nothing;
