-- =====================================================================================
-- iNXT BrokerVerse - V770 Remittance (BDOI Operations BRD-2, OPERATIONS_DESIGN 4.3)
--   * Extraction runs and per-invoice extraction tags (RMTID.001/003/004/005/006/014/017/020,
--     tags EXTRACTED / UNEXTRACTED_NOT_DUE / UNEXTRACTED_DUE / RETURNED);
--   * remittance batches RMB-<insurer>-<yyyy> and their lines (RMTID.002/007-011/019/029/036),
--     exclusions with reason, user and restore (RMTID.002 addendum), insurer OR details and
--     the OR vs paid PR exception status (RMTID.012/013/016), stored schedule and payment
--     request documents (RMTID.011);
--   * Marketing hold requests HLD-<yyyy> (RMTID.021/031, MKTID.002-007);
--   * special remittance requests SPR-<yyyy> (RMTID.030/033, MKTID.009);
--   * early-remittance incentive rules (RMTID.023; rates parked, OQ23);
--   * end-of-day extraction requests (RMTID.005; semantics parked, OQ18).
--   No foreign keys to V8xx tables: invoice no., ARN, client and insurer codes are plain values.
-- =====================================================================================

create table rem_extraction_run (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    run_no           varchar(30)    not null unique,
    trigger_type     varchar(20)    not null check (trigger_type in ('SCHEDULED', 'MANUAL', 'MANUAL_INVOICE',
                                                                     'EOD_QUEUE', 'SPECIAL')),
    insurer_code     varchar(30),
    remittance_type  varchar(20),
    invoice_no       varchar(40),
    business_date    date           not null,
    started_at       timestamptz    not null,
    ended_at         timestamptz,
    status           varchar(20)    not null check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
    examined_count   integer        not null default 0,
    extracted_count  integer        not null default 0,
    not_due_count    integer        not null default 0,
    due_count        integer        not null default 0,
    batch_count      integer        not null default 0,
    message          varchar(1000),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_rem_extraction_run_company on rem_extraction_run (company_id, id desc);

create table rem_extraction_tag (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    run_id           bigint         references rem_extraction_run (id),
    company_id       bigint         not null references org_company (id),
    invoice_no       varchar(40)    not null,
    insurer_code     varchar(30)    not null,
    remittance_type  varchar(20),
    tag              varchar(30)    not null check (tag in ('EXTRACTED', 'UNEXTRACTED_NOT_DUE',
                                                            'UNEXTRACTED_DUE', 'RETURNED')),
    reasons          varchar(200),
    remarks          varchar(500),
    paid_ar          numeric(19, 2) not null default 0,
    dtip_balance     numeric(19, 2) not null default 0,
    remittable       numeric(19, 2) not null default 0,
    batch_no         varchar(40),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_rem_extraction_tag_run on rem_extraction_tag (run_id);
create index ix_rem_extraction_tag_invoice on rem_extraction_tag (invoice_no, id desc);

create table rem_batch (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    company_id              bigint         not null references org_company (id),
    batch_no                varchar(40)    not null unique,
    insurer_code            varchar(30)    not null,
    remittance_type         varchar(20)    not null check (remittance_type in ('WITH_INCENTIVES', 'NORMAL_PHP',
                                                                                'NORMAL_USD', 'SPECIAL')),
    currency                varchar(3)     not null,
    run_id                  bigint         references rem_extraction_run (id),
    special_request_no      varchar(30),
    processor               varchar(50),
    stage                   varchar(30)    not null check (stage in ('REVIEW_IN_PROCESS', 'FOR_APPROVAL', 'ON_HOLD',
                                                                     'APPROVED', 'PARTIALLY_REMITTED',
                                                                     'FULLY_REMITTED', 'OR_RECEIVED', 'RETURNED')),
    line_count              integer        not null default 0,
    paid_ar                 numeric(19, 2) not null default 0,
    commission              numeric(19, 2) not null default 0,
    commission_vat          numeric(19, 2) not null default 0,
    wtax                    numeric(19, 2) not null default 0,
    dtip                    numeric(19, 2) not null default 0,
    incentive               numeric(19, 2) not null default 0,
    incentive_vat           numeric(19, 2) not null default 0,
    net_due                 numeric(19, 2) not null default 0,
    submitted_by            varchar(50),
    submitted_at            timestamptz,
    approved_by             varchar(50),
    approved_at             timestamptz,
    return_reason           varchar(250),
    disbursement_request_no varchar(30),
    disbursement_status     varchar(20),
    dv_no                   varchar(40),
    disbursed_amount        numeric(19, 2),
    commission_or_no        varchar(40),
    commission_or_status    varchar(20),
    incentive_or_no         varchar(40),
    incentive_or_status     varchar(20),
    or_message              varchar(500),
    schedule_sent_at        timestamptz,
    schedule_sent_by        varchar(50),
    extract_file_id         bigint,
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50)
);
create index ix_rem_batch_stage on rem_batch (company_id, stage);
create index ix_rem_batch_insurer on rem_batch (company_id, insurer_code, remittance_type);

create table rem_batch_line (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    batch_id                bigint         not null references rem_batch (id),
    invoice_no              varchar(40)    not null,
    arn                     varchar(30)    not null,
    endorsement_no          varchar(40),
    policy_no               varchar(60),
    client_code             varchar(30)    not null,
    assured_name            varchar(250)   not null,
    risk_code               varchar(20),
    product_line            varchar(30),
    segment                 varchar(40),
    inception_date          date           not null,
    expiry_date             date           not null,
    booking_date            date           not null,
    last_paid_on            date,
    prev_remittance_status  varchar(30)    not null,
    basic_premium           numeric(19, 2) not null default 0,
    paid_ar                 numeric(19, 2) not null,
    commission              numeric(19, 2) not null,
    commission_vat          numeric(19, 2) not null,
    wtax                    numeric(19, 2) not null,
    dtip                    numeric(19, 2) not null,
    incentive               numeric(19, 2) not null default 0,
    incentive_vat           numeric(19, 2) not null default 0,
    net_due                 numeric(19, 2) not null,
    excluded                boolean        not null default false,
    exclusion_reason        varchar(40),
    exclusion_comment       varchar(500),
    excluded_by             varchar(50),
    excluded_at             timestamptz,
    restored_by             varchar(50),
    restored_at             timestamptz,
    insurer_or_no           varchar(40),
    insurer_or_date         date,
    insurer_or_amount       numeric(19, 2),
    or_status               varchar(20)    check (or_status in ('MATCHED', 'AMOUNT_MISMATCH')),
    or_run_no               varchar(30),
    journal_batch_no        varchar(40),
    remitted_status         varchar(30),
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50),
    constraint uq_rem_batch_line unique (batch_id, invoice_no),
    constraint ck_rem_batch_line_exclusion check (not excluded or exclusion_reason is not null)
);
create index ix_rem_batch_line_invoice on rem_batch_line (invoice_no);
create index ix_rem_batch_line_or_run on rem_batch_line (or_run_no);

create table rem_batch_document (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    batch_id         bigint         not null references rem_batch (id),
    kind             varchar(30)    not null check (kind in ('SCHEDULE_PDF', 'SCHEDULE_XLSX',
                                                             'PAYMENT_REQUEST_PDF')),
    file_name        varchar(255)   not null,
    content_type     varchar(100)   not null,
    content          bytea          not null,
    template_version varchar(60),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_rem_batch_document unique (batch_id, kind)
);

create table rem_hold_request (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    company_id              bigint         not null references org_company (id),
    request_no              varchar(30)    not null unique,
    invoice_no              varchar(40)    not null,
    arn                     varchar(30)    not null,
    insurer_code            varchar(30)    not null,
    client_code             varchar(30)    not null,
    assured_name            varchar(250)   not null,
    reason_code             varchar(40)    not null,
    remarks                 varchar(500),
    hold_until              date           not null,
    requested_until         date,
    extension_count         integer        not null default 0,
    stage                   varchar(30)    not null check (stage in ('DRAFT', 'FOR_APPROVAL', 'ACTIVE',
                                                                     'EXTENSION_FOR_APPROVAL', 'CANCEL_FOR_APPROVAL',
                                                                     'RELEASED', 'REJECTED', 'CANCELLED')),
    source                  varchar(20)    not null check (source in ('SCREEN', 'COLLECTION_FEED')),
    requested_by            varchar(50)    not null,
    submitted_at            timestamptz,
    approved_by             varchar(50),
    approved_at             timestamptz,
    assigned_processor      varchar(50),
    prev_remittance_status  varchar(30),
    expiry_notified         boolean        not null default false,
    released_at             timestamptz,
    release_note            varchar(500),
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50)
);
create unique index uq_rem_hold_live on rem_hold_request (invoice_no)
    where stage in ('DRAFT', 'FOR_APPROVAL', 'ACTIVE', 'EXTENSION_FOR_APPROVAL', 'CANCEL_FOR_APPROVAL');
create index ix_rem_hold_stage on rem_hold_request (company_id, stage, hold_until);

create table rem_special_request (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    company_id              bigint         not null references org_company (id),
    request_no              varchar(30)    not null unique,
    invoice_no              varchar(40)    not null,
    arn                     varchar(30)    not null,
    insurer_code            varchar(30)    not null,
    client_code             varchar(30)    not null,
    assured_name            varchar(250)   not null,
    policy_no               varchar(60),
    segment                 varchar(40),
    condition_code          varchar(40)    not null,
    remarks                 varchar(500),
    stage                   varchar(30)    not null check (stage in ('REQUESTED', 'FOR_APPROVAL',
                                                                     'IN_PROCESS_REMITTANCE',
                                                                     'PUSHED_TO_DISBURSEMENT', 'REJECTED',
                                                                     'RETURNED')),
    source                  varchar(20)    not null check (source in ('SCREEN', 'COLLECTION_FEED')),
    requested_by            varchar(50)    not null,
    validation_note         varchar(500),
    approved_by             varchar(50),
    approved_at             timestamptz,
    rejected_reason         varchar(500),
    batch_no                varchar(40),
    pushed_at               timestamptz,
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50)
);
create unique index uq_rem_special_live on rem_special_request (invoice_no)
    where stage in ('REQUESTED', 'FOR_APPROVAL', 'IN_PROCESS_REMITTANCE');
create index ix_rem_special_stage on rem_special_request (company_id, stage);

create table rem_incentive_rule (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    insurer_code     varchar(30)    not null,
    product_line     varchar(30),
    segment          varchar(40),
    rate             numeric(9, 4)  not null check (rate > 0 and rate <= 100),
    window_days      integer        not null check (window_days between 1 and 366),
    basis            varchar(20)    not null check (basis in ('INCEPTION', 'BOOKING')),
    effective_from   date           not null,
    effective_to     date,
    active           boolean        not null default true,
    description      varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_rem_incentive_rule_period check (effective_to is null or effective_to >= effective_from)
);
create index ix_rem_incentive_rule on rem_incentive_rule (company_id, insurer_code, active);

create table rem_eod_request (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    invoice_no       varchar(40)    not null,
    requested_on     date           not null,
    requested_by     varchar(50)    not null,
    run_no           varchar(30),
    tag              varchar(30),
    processed_at     timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_rem_eod_request unique (invoice_no, requested_on)
);
create index ix_rem_eod_request_open on rem_eod_request (company_id, run_no);
