-- =====================================================================================
-- iNXT BrokerVerse - V772 Remittance changes of BRD-5 (A1-OPSX; ACCOUNTING_DISBURSEMENT_DESIGN
-- sections 6 rows 15-17 and 12.2):
--   DIS 3.29.2  CPC2 incentive per batch line from the catalog incentive criteria (code CPC2),
--               batch totals, event OPS_REMIT_CPC2 (event type seeded in V890)
--   DIS 3.29.1  early-incentive service invoice (booking type EARLY_INCENTIVE, V872) linked to
--               the batch, with the 2% withholding tax (parameter EARLY_INCENTIVE_WTAX_RATE, V890)
--   ACSL 2.9.2  remittance deductions confirmed by ACSL (workflow REM_DEDUCTION, V890), consumed by
--               the next batch of the insurer and capped at the amount payable, event
--               OPS_REMIT_DEDUCTION (seeded in V890)
--   DIS 2.20.0  cancellation of the DV of a batch: the batch returns to review with its postings
--               reversed and is sent again under a new cycle (workflow action dv_cancelled)
-- =====================================================================================

-- ---------- CPC2 per line and batch totals (DIS 3.29.2) ------------------------------------
alter table rem_batch_line
    add column cpc2          numeric(19, 2) not null default 0,
    add column cpc2_vat      numeric(19, 2) not null default 0,
    add column cpc2_code     varchar(30),
    add column cpc2_rate     numeric(9, 4);

alter table rem_batch
    add column cpc2              numeric(19, 2) not null default 0,
    add column cpc2_vat          numeric(19, 2) not null default 0,
    -- deductions applied in the current send cycle (ACSL 2.9.2)
    add column deduction_amount  numeric(19, 2) not null default 0,
    -- send cycle: 1 for the first payment request, +1 after each cancelled DV (DIS 2.20.0)
    add column send_cycle        integer        not null default 1,
    -- early-incentive service invoice (DIS 3.29.1)
    add column early_si_no       varchar(40),
    add column early_si_wtax     numeric(19, 2),
    -- last cancelled DV (DIS 2.20.0)
    add column cancelled_dv_no   varchar(40),
    add column cancel_reason     varchar(500),
    add column cancelled_at      timestamptz;

-- ---------- Remittance deductions (ACSL 2.9.2) ----------------------------------------------
create table rem_deduction (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    deduction_no       varchar(30)    not null unique,
    insurer_code       varchar(30)    not null,
    currency           varchar(3)     not null,
    source_type        varchar(30)    not null,
    source_ref         varchar(60)    not null,
    invoice_no         varchar(40),
    amount             numeric(19, 2) not null check (amount > 0),
    applied_amount     numeric(19, 2) not null default 0,
    confirmation_ref   varchar(100),
    confirmation_date  date,
    remarks            varchar(1000),
    stage              varchar(30)    not null check (stage in ('DRAFT', 'FOR_CONFIRMATION', 'CONFIRMED',
                                                                'APPLIED', 'CANCELLED')),
    submitted_by       varchar(50),
    submitted_at       timestamptz,
    confirmed_by       varchar(50),
    confirmed_at       timestamptz,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_rem_deduction_applied check (applied_amount >= 0 and applied_amount <= amount)
);
create index ix_rem_deduction_open on rem_deduction (company_id, insurer_code, currency, stage);

create table rem_deduction_application (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    deduction_id       bigint         not null references rem_deduction (id),
    batch_id           bigint         not null references rem_batch (id),
    batch_no           varchar(40)    not null,
    send_cycle         integer        not null,
    amount             numeric(19, 2) not null check (amount > 0),
    journal_batch_no   varchar(40),
    reversed           boolean        not null default false,
    reversed_at        timestamptz,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50)
);
create index ix_rem_deduction_app_batch on rem_deduction_application (batch_id);
create index ix_rem_deduction_app_deduction on rem_deduction_application (deduction_id);

-- Source of a deduction (the content waits for AQ23)
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('REMIT_DEDUCTION_SOURCE', 'Remittance deduction source',
        'What an insurer-confirmed remittance deduction settles (ACSL 2.9.2, AQ23)', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'REMIT_DEDUCTION_SOURCE', v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM',
       now(), now(), 'SYSTEM'
from (values
    ('AR_INSURER_REFUND', 'AR insurer''s refund (return premium after remittance)', 10),
    ('OVER_REMITTANCE', 'Over-remittance to the insurer', 20),
    ('OTHER', 'Other amount confirmed by the insurer', 90)
) as v(code, label, sort_order);

-- A deduction consumed by a batch whose DV is then cancelled is available again (DIS 2.20.0)
insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('REM_DEDUCTION', 'APPLIED', 'restore', 'CONFIRMED', 'Restored after a cancelled DV', 'REMIT_PROCESS', false, null, 20);

-- ---------- DV cancelled: the batch returns to review (DIS 2.20.0) ---------------------------
insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('OPS_REMITTANCE', 'APPROVED', 'dv_cancelled', 'REVIEW_IN_PROCESS', 'DV cancelled - back to review', 'DISB_PROCESS', false, null, 30),
       ('OPS_REMITTANCE', 'PARTIALLY_REMITTED', 'dv_cancelled', 'REVIEW_IN_PROCESS', 'DV cancelled - back to review', 'DISB_PROCESS', false, null, 30),
       ('OPS_REMITTANCE', 'FULLY_REMITTED', 'dv_cancelled', 'REVIEW_IN_PROCESS', 'DV cancelled - back to review', 'DISB_PROCESS', false, null, 30);
