-- =====================================================================================
-- iNXT BrokerVerse - V775 Production reconciliation (BDOI Operations BRD-2, PRCID.001-039;
-- docs/architecture/OPERATIONS_DESIGN.md section 4.4).
--   * prc_schedule        extraction schedule per insurer (PRCID.001, frequency parked OQ29)
--   * prc_cycle           one reconciliation cycle per insurer and production month (workflow OPS_RECON)
--   * prc_extract(_line)  production register extracts and their snapshot lines (PRCID.002-008/011/020)
--   * prc_upload          insurer upload attempts incl. blocked duplicates (PRCID.009/010/031/032)
--   * prc_item            one reconciliation item per booked invoice and / or insurer line:
--                         status bucket, both sides, discrepancies, feedback and disposition
--                         (PRCID.012-030/033)
--   Keys to the invoice ledger and other modules are plain values (OPERATIONS_DESIGN section 3).
-- =====================================================================================

create table prc_schedule (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    insurer_code    varchar(30)  not null,
    frequency       varchar(10)  not null check (frequency in ('MONTHLY', 'WEEKLY')),
    -- Day of the month (MONTHLY, 1-28) or of the week (WEEKLY, 1 = Monday ... 7 = Sunday).
    run_day         integer      not null check (run_day between 1 and 28),
    next_run_date   date         not null,
    auto_send       boolean      not null default false,
    recipients      varchar(500),
    active          boolean      not null default true,
    last_run_at     timestamptz,
    last_extract_no varchar(30),
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_prc_schedule unique (company_id, insurer_code)
);

create table prc_cycle (
    id               bigint generated by default as identity primary key,
    version          bigint       not null default 0,
    company_id       bigint       not null references org_company (id),
    cycle_no         varchar(60)  not null unique,
    insurer_code     varchar(30)  not null,
    production_month date         not null check (extract(day from production_month) = 1),
    stage            varchar(40)  not null,
    closed           boolean      not null default false,
    sent_at          timestamptz,
    last_upload_at   timestamptz,
    last_matched_at  timestamptz,
    closed_at        timestamptz,
    created_at       timestamptz  not null,
    created_by       varchar(50)  not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
-- One open cycle per insurer and month; a closed cycle leaves room for a new round.
create unique index uq_prc_cycle_open on prc_cycle (company_id, insurer_code, production_month)
    where closed = false;
create index ix_prc_cycle_board on prc_cycle (company_id, production_month, stage);

create table prc_extract (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    cycle_id     bigint       not null references prc_cycle (id),
    extract_no   varchar(30)  not null unique,
    trigger_type varchar(20)  not null check (trigger_type in ('SCHEDULED', 'MANUAL')),
    booking_from date         not null,
    booking_to   date         not null,
    file_name    varchar(200) not null,
    file_id      bigint       references ops_extract_file (id),
    sha256       varchar(64),
    row_count    integer      not null default 0,
    new_count    integer      not null default 0,
    sent_at      timestamptz,
    sent_by      varchar(50),
    message_id   bigint,
    recipients   varchar(500),
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_prc_extract_range check (booking_to >= booking_from)
);
create index ix_prc_extract_cycle on prc_extract (cycle_id);

-- Snapshot of the booked invoice as sent (Annex IV #5 Production Register).
create table prc_extract_line (
    id                bigint generated by default as identity primary key,
    extract_id        bigint         not null references prc_extract (id),
    line_no           integer        not null,
    invoice_no        varchar(40)    not null,
    arn               varchar(30)    not null,
    kind              varchar(20)    not null,
    insurer_code      varchar(30)    not null,
    booking_date      date           not null,
    inception_date    date           not null,
    expiry_date       date           not null,
    policy_no         varchar(60),
    endorsement_no    varchar(40),
    pn_nos            varchar(500),
    assured_name      varchar(250)   not null,
    client_code       varchar(30)    not null,
    risk_code         varchar(20),
    product_line      varchar(30),
    segment           varchar(40),
    ao_username       varchar(50),
    sales_unit        varchar(20),
    branch_id         bigint,
    currency          varchar(3)     not null,
    basic_premium     numeric(19, 2) not null,
    gross_commission  numeric(19, 2) not null,
    gross_premium     numeric(19, 2) not null,
    booked_vat        numeric(19, 2) not null,
    amount_paid       numeric(19, 2) not null,
    date_paid         date,
    ar_number         varchar(40),
    remittance_status varchar(30)    not null,
    estimated         boolean        not null default false,
    constraint uq_prc_extract_line unique (extract_id, line_no)
);
create index ix_prc_extract_line_invoice on prc_extract_line (invoice_no);

create table prc_upload (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    cycle_id         bigint        references prc_cycle (id),
    insurer_code     varchar(30),
    production_month date,
    file_name        varchar(255)  not null,
    sha256           varchar(64)   not null,
    attempt_no       integer       not null,
    status           varchar(20)   not null
        check (status in ('RECEIVED', 'PROCESSED', 'PARTIAL', 'FAILED', 'DUPLICATE_BLOCKED')),
    run_no           varchar(30),
    rows_read        integer       not null default 0,
    rows_accepted    integer       not null default 0,
    rows_failed      integer       not null default 0,
    message          varchar(1000),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_prc_upload_sha on prc_upload (sha256, status);
create index ix_prc_upload_cycle on prc_upload (company_id, insurer_code, production_month);

create table prc_item (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    cycle_id            bigint         not null references prc_cycle (id),
    status              varchar(30)    not null check (status in ('MATCHED', 'MATCHED_WITH_DISCREPANCY',
                            'BDOI_ONLY', 'UNMATCHED_PREBOOKED', 'UNMATCHED_NO_BOOKING')),
    -- BDOI side (booked invoice of the ledger)
    invoice_no          varchar(40),
    extract_line_id     bigint         references prc_extract_line (id),
    arn                 varchar(30),
    booking_date        date,
    ao_username         varchar(50),
    sales_unit          varchar(20),
    branch_id           bigint,
    segment             varchar(40),
    product_line        varchar(30),
    bdoi_policy_no      varchar(60),
    bdoi_reference_no   varchar(40),
    bdoi_pn_no          varchar(500),
    bdoi_period_from    date,
    bdoi_period_to      date,
    bdoi_assured_name   varchar(250),
    bdoi_commission     numeric(19, 2),
    bdoi_basic_premium  numeric(19, 2),
    bdoi_gross_premium  numeric(19, 2),
    -- Insurer side (row of the insurer's production report)
    upload_id           bigint         references prc_upload (id),
    ins_row_no          integer,
    ins_policy_no       varchar(60),
    ins_reference_no    varchar(40),
    ins_pn_no           varchar(500),
    ins_period_from     date,
    ins_period_to       date,
    ins_assured_name    varchar(250),
    ins_commission      numeric(19, 2),
    ins_basic_premium   numeric(19, 2),
    ins_gross_premium   numeric(19, 2),
    ins_incentive       numeric(19, 2),
    ins_remarks         varchar(500),
    in_original_extract boolean        not null default false,
    -- Result, feedback and disposition (PRCID.015/016/018/030/033)
    prebooked_arn       varchar(30),
    discrepancies       varchar(1000),
    match_method        varchar(10)    check (match_method in ('AUTO', 'MANUAL')),
    matched_at          timestamptz,
    matched_by          varchar(50),
    company_concerned   varchar(40),
    instruction         varchar(500),
    insurer_feedback    varchar(1000),
    marketing_feedback  varchar(1000),
    disposition         varchar(40),
    for_closure         boolean        not null default false,
    unbooked_status     varchar(20)    check (unbooked_status in ('OPEN', 'PREBOOKED', 'BOOKED', 'CLOSED')),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint ck_prc_item_side check (invoice_no is not null or upload_id is not null)
);
create unique index uq_prc_item_invoice on prc_item (cycle_id, invoice_no) where invoice_no is not null;
create index ix_prc_item_bucket on prc_item (cycle_id, status);
create index ix_prc_item_unbooked on prc_item (unbooked_status) where unbooked_status is not null;
create index ix_prc_item_ins_ref on prc_item (ins_reference_no);
create index ix_prc_item_ins_policy on prc_item (ins_policy_no);

-- ---------- Workflow OPS_RECON (OPERATIONS_DESIGN section 7) ------------------------------
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('OPS_RECON', 'EXTRACTED', 'Register extracted', 'RECON_SEND', 48, true, false, 10),
       ('OPS_RECON', 'SENT_TO_INSURER', 'Awaiting insurer feedback', 'RECON_PROCESS', null, false, false, 20),
       ('OPS_RECON', 'RECONCILING', 'Reconciling', 'RECON_PROCESS', null, false, false, 30),
       ('OPS_RECON', 'CLOSED', 'Closed', null, null, false, true, 40);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('OPS_RECON', 'EXTRACTED', 'send', 'SENT_TO_INSURER', 'Send to Insurer', 'RECON_SEND', false, null, 10),
       ('OPS_RECON', 'EXTRACTED', 'feedback_uploaded', 'RECONCILING', 'Insurer feedback uploaded', 'RECON_PROCESS', false, null, 20),
       ('OPS_RECON', 'SENT_TO_INSURER', 'resend', 'SENT_TO_INSURER', 'Resend to Insurer', 'RECON_SEND', false, null, 10),
       ('OPS_RECON', 'SENT_TO_INSURER', 'feedback_uploaded', 'RECONCILING', 'Insurer feedback uploaded', 'RECON_PROCESS', false, null, 20),
       ('OPS_RECON', 'RECONCILING', 'feedback_uploaded', 'RECONCILING', 'Insurer feedback uploaded', 'RECON_PROCESS', false, null, 10),
       ('OPS_RECON', 'RECONCILING', 'resend', 'RECONCILING', 'Resend to Insurer', 'RECON_SEND', false, null, 15),
       ('OPS_RECON', 'RECONCILING', 'close', 'CLOSED', 'Close Cycle', 'RECON_PROCESS', false, null, 20),
       ('OPS_RECON', 'RECONCILING', 'for_closure', 'CLOSED', 'Every item matched or for closure', 'RECON_PROCESS', false, null, 30);

-- ---------- Parameters (PRCID.022/027, OQ30) -------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('RECON_MATCH_KEYS', 'INVOICE_NO,POLICY_NO', 'CODE_LIST', 'OPERATIONS',
     'Keys pairing an insurer production line with a booked invoice, tried in order: INVOICE_NO, POLICY_NO, PN_NO (PRCID.022/027, OQ30)',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;

-- ---------- Cover letter of the production register (PRCID.003, template parked OQ29) --------
insert into doc_template (code, version_no, title, body, effective_from, created_at, created_by)
values ('PRODRECON_COVER_LETTER', 1, 'Production register for reconciliation',
 'Dear {{insurerName}},

Attached is the BDOI production register {{extractNo}} of the accounts booked with you from {{bookingFrom}} to {{bookingTo}} (production month {{productionMonth}}), {{rowCount}} account(s).

Please review the register and return it with your remarks in the Remarks column, together with any production of yours that is not in the register. The file is password protected; the password is sent in a separate e-mail.

Thank you.
BDO Insurance and Reinsurance Brokers, Inc. - Production Reconciliation', date '2020-01-01', now(), 'SYSTEM');
