-- =====================================================================================
-- iNXT BrokerVerse - V785 Commission receivables (BDOI Operations BRD-2, CMRID.001-015,
-- MKTID.012, RMTID.037; docs/architecture/OPERATIONS_DESIGN.md sections 4.6 and 5 rows 22-26).
--   * cmr_dp_list / cmr_dp_item   direct payment (DP) lists of HO and branches and their accounts:
--                                 consolidation, validation and sanitation, tags, insurer feedback,
--                                 commission OR, PR reversal (CMRID.001-013, MKTID.012)
--   * cmr_billing                 commission billing per insurer with the feedback SLA (workflow
--                                 OPS_DP_BILLING, CMRID.009/011/012)
--   * cmr_incentive_scheme(_tier) incentive schemes No Touch, Top Up, Motor Mania with tiers; seeded
--                                 empty (OQ39) (CMRID.003/005/006)
--   * cmr_incentive_run(_line)    computed runs, accrual and pass-on to branches
--   * cmr_certificate(_or)        BIR withholding certificates submitted to Comptrollership
--                                 (workflow OPS_BIR_CERT, CMRID.010/015)
--   Keys to the ledger and other modules are plain values (OPERATIONS_DESIGN section 3).
-- =====================================================================================

create table cmr_dp_list (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    company_id      bigint       not null references org_company (id),
    list_no         varchar(30)  not null unique,
    source          varchar(20)  not null check (source in ('BRANCH', 'HEAD_OFFICE', 'COLLECTION_FEED')),
    branch_code     varchar(60)  not null,
    submission_date date         not null,
    file_name       varchar(255),
    sha256          varchar(64),
    run_no          varchar(30),
    item_count      integer      not null default 0,
    valid_count     integer      not null default 0,
    excluded_count  integer      not null default 0,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50)
);
create index ix_cmr_dp_list_period on cmr_dp_list (company_id, submission_date);
create unique index uq_cmr_dp_list_file on cmr_dp_list (company_id, sha256) where sha256 is not null;

create table cmr_billing (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    billing_no       varchar(30)    not null unique,
    insurer_code     varchar(30)    not null,
    handler          varchar(50),
    stage            varchar(40)    not null,
    item_count       integer        not null default 0,
    total_commission numeric(19, 2) not null default 0,
    total_vat        numeric(19, 2) not null default 0,
    total_wtax       numeric(19, 2) not null default 0,
    total_net        numeric(19, 2) not null default 0,
    file_id          bigint         references ops_extract_file (id),
    file_name        varchar(255),
    sent_at          timestamptz,
    sla_due          date,
    overdue_alerted  boolean        not null default false,
    responded_at     timestamptz,
    message_id       bigint,
    recipients       varchar(500),
    or_no            varchar(40),
    or_status        varchar(20),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);
create index ix_cmr_billing_stage on cmr_billing (company_id, stage);
create index ix_cmr_billing_sla on cmr_billing (sla_due) where overdue_alerted = false;

create table cmr_dp_item (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    list_id           bigint         references cmr_dp_list (id),
    row_no            integer,
    invoice_no        varchar(40)    not null,
    policy_no         varchar(60),
    insurer_code      varchar(30),
    client_code       varchar(30),
    assured_name      varchar(250),
    branch_code       varchar(60),
    submitted_premium numeric(19, 2),
    premium           numeric(19, 2) not null default 0,
    commission        numeric(19, 2) not null default 0,
    commission_vat    numeric(19, 2) not null default 0,
    wtax              numeric(19, 2) not null default 0,
    net_commission    numeric(19, 2) not null default 0,
    tag               varchar(30)    not null check (tag in ('DP_FOR_CONFIRMATION', 'DP_FOR_BILLING', 'BILLED',
                          'APPROVED', 'REJECTED', 'COLLECTED', 'PR_REVERSED', 'EXCLUDED')),
    sanitation        varchar(20)    not null check (sanitation in ('VALID', 'DUPLICATE', 'INVALID', 'INCOMPLETE')),
    rule_results      varchar(2000),
    duplicate_of      bigint,
    remarks           varchar(500),
    billing_id        bigint         references cmr_billing (id),
    confirmed_by      varchar(50),
    confirmed_at      timestamptz,
    feedback_reason   varchar(40),
    feedback_comment  varchar(500),
    responded_at      timestamptz,
    returned_ref      varchar(40),
    or_no             varchar(40),
    collected_amount  numeric(19, 2),
    collected_on      date,
    pr_reversed_at    timestamptz,
    reversal_count    integer        not null default 0,
    reinstated_count  integer        not null default 0,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create index ix_cmr_dp_item_tag on cmr_dp_item (company_id, tag);
create index ix_cmr_dp_item_invoice on cmr_dp_item (invoice_no);
create index ix_cmr_dp_item_billing on cmr_dp_item (billing_id);
create index ix_cmr_dp_item_list on cmr_dp_item (list_id);

create table cmr_incentive_scheme (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    company_id     bigint       not null references org_company (id),
    code           varchar(30)  not null,
    name           varchar(120) not null,
    scheme_type    varchar(20)  not null check (scheme_type in ('NO_TOUCH', 'TOP_UP', 'MOTOR_MANIA', 'OTHER')),
    calculation    varchar(20)  not null check (calculation in ('TARGET_TIERED', 'FIXED_PER_POLICY')),
    period_type    varchar(20)  not null check (period_type in ('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'CUSTOM')),
    beneficiary    varchar(10)  not null check (beneficiary in ('BDOI', 'BRANCH')),
    insurer_code   varchar(30),
    segments       varchar(200),
    product_lines  varchar(200),
    effective_from date,
    effective_to   date,
    active         boolean      not null default false,
    description    varchar(500),
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_cmr_incentive_scheme unique (company_id, code)
);

create table cmr_incentive_tier (
    scheme_id         bigint         not null references cmr_incentive_scheme (id),
    tier_index        integer        not null,
    min_production    numeric(19, 2),
    rate_percent      numeric(9, 4),
    multiplier        numeric(9, 4),
    min_basic_premium numeric(19, 2),
    fixed_amount      numeric(19, 2),
    primary key (scheme_id, tier_index)
);

create table cmr_incentive_run (
    id                  bigint generated by default as identity primary key,
    version             bigint         not null default 0,
    company_id          bigint         not null references org_company (id),
    run_no              varchar(30)    not null unique,
    scheme_id           bigint         not null references cmr_incentive_scheme (id),
    period_from         date           not null,
    period_to           date           not null,
    status              varchar(20)    not null check (status in ('COMPUTED', 'POSTED', 'CANCELLED')),
    eligible_count      integer        not null default 0,
    eligible_production numeric(19, 2) not null default 0,
    excluded_count      integer        not null default 0,
    excluded_amount     numeric(19, 2) not null default 0,
    tier_applied        varchar(200),
    incentive_amount    numeric(19, 2) not null default 0,
    pass_on_amount      numeric(19, 2) not null default 0,
    posted_at           timestamptz,
    posted_by           varchar(50),
    journal_refs        varchar(1000),
    created_at          timestamptz    not null,
    created_by          varchar(50)    not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint ck_cmr_incentive_run_period check (period_to >= period_from)
);

create table cmr_incentive_run_line (
    id               bigint generated by default as identity primary key,
    run_id           bigint         not null references cmr_incentive_run (id),
    invoice_no       varchar(40)    not null,
    insurer_code     varchar(30)    not null,
    sales_unit       varchar(20),
    segment          varchar(40),
    product_line     varchar(30),
    basic_premium    numeric(19, 2) not null,
    gross_premium    numeric(19, 2) not null,
    excluded         boolean        not null default false,
    exclusion_reason varchar(40),
    incentive        numeric(19, 2) not null default 0
);
create index ix_cmr_incentive_run_line on cmr_incentive_run_line (run_id);

create table cmr_certificate (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    submission_no    varchar(30)    not null unique,
    insurer_code     varchar(30)    not null,
    certificate_form varchar(20)    not null,
    certificate_no   varchar(60)    not null,
    period_from      date           not null,
    period_to        date           not null,
    tax_withheld     numeric(19, 2) not null,
    stage            varchar(40)    not null,
    reject_reason    varchar(500),
    submitted_count  integer        not null default 1,
    decided_at       timestamptz,
    decided_by       varchar(50),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_cmr_certificate_period check (period_to >= period_from)
);
create index ix_cmr_certificate_stage on cmr_certificate (company_id, stage);

create table cmr_certificate_or (
    certificate_id bigint         not null references cmr_certificate (id),
    or_index       integer        not null,
    or_no          varchar(40)    not null,
    amount         numeric(19, 2) not null,
    primary key (certificate_id, or_index)
);

-- ---------- Workflow OPS_DP_BILLING (OPERATIONS_DESIGN section 7) -----------------------------
-- The item tags DP for confirmation / DP for billing precede the billing (CMRID.008/013); the
-- billing's work case starts when the confirmed accounts of an insurer are gathered for billing.
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('OPS_DP_BILLING', 'DP_FOR_BILLING', 'For billing', 'COMMREC_PROCESS', 48, true, false, 10),
       ('OPS_DP_BILLING', 'AWAITING_INSURER', 'Awaiting insurer feedback', 'COMMREC_PROCESS', null, false, false, 20),
       ('OPS_DP_BILLING', 'APPROVED', 'Approved by insurer - to collect', 'COMMREC_PROCESS', null, false, false, 30),
       ('OPS_DP_BILLING', 'COLLECTED', 'Commission collected', 'COMMREC_PROCESS', null, false, false, 40),
       ('OPS_DP_BILLING', 'CLOSED', 'Closed - PR reversed', null, null, false, true, 50),
       ('OPS_DP_BILLING', 'RETURNED_TO_COLLECTION', 'Rejected - returned to Collection', null, null, false, true, 60),
       ('OPS_DP_BILLING', 'CANCELLED', 'Cancelled', null, null, false, true, 70);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('OPS_DP_BILLING', 'DP_FOR_BILLING', 'bill', 'AWAITING_INSURER', 'Send Billing to Insurer', 'COMMREC_PROCESS', false, null, 10),
       ('OPS_DP_BILLING', 'DP_FOR_BILLING', 'cancel', 'CANCELLED', 'Cancel Billing', 'COMMREC_PROCESS,COMMREC_APPROVE', false, null, 90),
       ('OPS_DP_BILLING', 'AWAITING_INSURER', 'insurer_approved', 'APPROVED', 'Insurer approved', 'COMMREC_PROCESS', false, null, 10),
       ('OPS_DP_BILLING', 'AWAITING_INSURER', 'insurer_rejected', 'RETURNED_TO_COLLECTION', 'Insurer rejected', 'COMMREC_PROCESS', false, null, 20),
       ('OPS_DP_BILLING', 'APPROVED', 'collected', 'COLLECTED', 'Commission collected', 'COMMREC_PROCESS', false, null, 10),
       ('OPS_DP_BILLING', 'COLLECTED', 'pr_reversed', 'CLOSED', 'Premium receivable reversed', 'COMMREC_PROCESS', false, null, 10);

-- ---------- Workflow OPS_BIR_CERT (CMRID.015) ------------------------------------------------
insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('OPS_BIR_CERT', 'SUBMITTED', 'Submitted to Comptrollership', 'BIR_CERT_ACK', 72, true, false, 10),
       ('OPS_BIR_CERT', 'ACKNOWLEDGED', 'Acknowledged', null, null, false, true, 20),
       ('OPS_BIR_CERT', 'REJECTED', 'Rejected - to resubmit', 'BIR_CERT_SUBMIT', 48, false, false, 30);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('OPS_BIR_CERT', 'SUBMITTED', 'acknowledge', 'ACKNOWLEDGED', 'Acknowledge', 'BIR_CERT_ACK', false, null, 10),
       ('OPS_BIR_CERT', 'SUBMITTED', 'reject', 'REJECTED', 'Reject', 'BIR_CERT_ACK', false, null, 20),
       ('OPS_BIR_CERT', 'REJECTED', 'resubmit', 'SUBMITTED', 'Resubmit', 'BIR_CERT_SUBMIT', false, null, 10);

-- ---------- Accounting events (OPERATIONS_DESIGN section 5 rows 22-26; rules by Comptrollership, OQ07)
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('OPS_DP_PR_REVERSAL', 'Direct payment PR reversal', 'RECEIPT', 'RECEIPT',
  'MKTID.012: premium the client paid directly to the insurer - Dr due to insurer (DTIP) / Cr premium '
  || 'receivable by component. Posted only when DP_PR_REVERSAL_POSTING is on (booking posts no PR for '
  || 'direct payment invoices).',
  'DTIP,PR_BASIC,PR_DST,PR_PTX_VAT,PR_LGT,PR_FST,PR_OTHER'),
 ('OPS_DP_REINSTATE', 'Direct payment reinstatement', 'RECEIPT', 'RECEIPT',
  'CSHID.004 b: reverse of OPS_DP_PR_REVERSAL (negative amounts)',
  'DTIP,PR_BASIC,PR_DST,PR_PTX_VAT,PR_LGT,PR_FST,PR_OTHER'),
 ('OPS_DP_COMMISSION_COLLECT', 'Direct payment commission collected', 'RECEIPT', 'RECEIPT',
  'CMRID: commission of a direct payment invoice received from the insurer (role BANK) - Dr bank and '
  || 'creditable withholding tax / Cr commission receivable; realization of the unrealized commission and '
  || 'deferred output VAT when OPS_COMMISSION_REALIZATION is ON_COLLECTION',
  'CASH,CWT,COMMISSION_RECEIVABLE,REALIZED_COMMISSION,REALIZED_VAT'),
 ('OPS_INCENTIVE_ACCRUE', 'Incentive earned from insurer', 'COMMISSION', 'COMMISSION',
  'CMRID.005: target incentive earned - Dr incentive receivable (insurer) / Cr incentive income',
  'INCENTIVE'),
 ('OPS_INCENTIVE_PASS_ON', 'Incentive pass-on to branches', 'COMMISSION', 'COMMISSION',
  'CMRID.006: Motor Mania incentive passed on to branches - Dr incentive income / Cr due to branches, then '
  || 'Disbursement',
  'PASS_ON');

-- ---------- Parameters -----------------------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('DP_PR_REVERSAL_POSTING', 'false', 'BOOLEAN', 'OPERATIONS',
     'Post the GL entry of the direct payment PR reversal and reinstatement (OPS_DP_PR_REVERSAL / OPS_DP_REINSTATE). Off while booking posts no premium receivable for direct payment invoices; the ledger reversal is always recorded (MKTID.012, OQ07/OQ38)',
     null, null, now(), 'SYSTEM'),
    ('CMR_DP_COLLECTION_BANK', '', 'STRING', 'OPERATIONS',
     'GL bank account proposed for direct payment commission collections (role BANK of OPS_DP_COMMISSION_COLLECT)',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
