-- =====================================================================================
-- iNXT BrokerVerse - V787 Legacy direct payment PR reversal (Data Migration BRD-13; BRID 7.1;
-- docs/architecture/DATA_MIGRATION_DESIGN.md sections 14.4 E and 24).
--   cmr_dppr_batch / _line   legacy invoices the client paid directly to the insurer, uploaded
--                            (invoice no., amount, reason) or taken from the Collections "DP PR
--                            for reversal" tags; requested with LEGACY_REVERSAL_REQUEST, approved
--                            with LEGACY_REVERSAL_APPROVE (the maker never approves); each line
--                            reverses the open premium receivable and due to insurer in its own
--                            transaction, and its entry always posts for a legacy invoice.
--   Legacy components (LG_) of the direct payment events, so a legacy invoice posts on the legacy
--   control accounts.
-- =====================================================================================

create table cmr_dppr_batch (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    company_id      bigint         not null references org_company (id),
    batch_no        varchar(20)    not null unique,
    status          varchar(20)    not null,
    reason          varchar(500)   not null,
    total           numeric(19, 2) not null default 0,
    line_count      integer        not null default 0,
    submitted_by    varchar(50),
    submitted_at    timestamptz,
    approved_by     varchar(50),
    approved_at     timestamptz,
    executed_at     timestamptz,
    posted_count    integer        not null default 0,
    failed_count    integer        not null default 0,
    return_reason   varchar(500),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_cmr_dppr_batch_status check (status in ('DRAFT', 'FOR_APPROVAL', 'EXECUTED', 'CANCELLED'))
);

create table cmr_dppr_batch_line (
    id               bigint generated by default as identity primary key,
    batch_id         bigint         not null references cmr_dppr_batch (id),
    line_no          integer        not null,
    invoice_no       varchar(40)    not null,
    amount           numeric(19, 2) not null,
    reason           varchar(250),
    status           varchar(10)    not null default 'PENDING',
    journal_batch_no varchar(40),
    message          varchar(500),
    constraint uq_cmr_dppr_batch_line unique (batch_id, line_no),
    constraint ck_cmr_dppr_line_status check (status in ('PENDING', 'POSTED', 'FAILED'))
);

update acc_event_type
set amount_components = amount_components || ',LG_DTIP,LG_PR_BASIC,LG_PR_DST,LG_PR_PTX_VAT,LG_PR_LGT,LG_PR_FST,LG_PR_OTHER'
where code in ('OPS_DP_PR_REVERSAL', 'OPS_DP_REINSTATE') and amount_components not like '%LG_DTIP%';

update acc_event_type
set amount_components = amount_components || ',LG_COMMISSION_RECEIVABLE,LG_REALIZED_COMMISSION,LG_REALIZED_VAT'
where code = 'OPS_DP_COMMISSION_COLLECT' and amount_components not like '%LG_COMMISSION_RECEIVABLE%';

insert into sec_role_permission (role_id, permission)
select r.id, x.permission
from sec_role r
join (values ('COMMREC_HANDLER', 'LEGACY_REVERSAL_REQUEST'), ('COMMREC_TL', 'LEGACY_REVERSAL_APPROVE'))
     as x(role_code, permission) on x.role_code = r.code
where not exists (select 1 from sec_role_permission p where p.role_id = r.id and p.permission = x.permission);
