-- =====================================================================================
-- iNXT BrokerVerse - V790 Broking administration (nbadmin): user access requests with
-- approval, data retention rules and review runs, session policy parameters.
--   BRNB.085 / BRD 3.3.5, 3.4.2  profile creation and modification requests, approved by
--                                  the Approver (four eyes) before they are applied
--   BRNB.106 / NFR retention      retention rules (5 years online, 15 years archive) and the
--                                  monthly RETENTION_REVIEW job; archive / purge is parked
--   BRNB.040 / BRNB.082           inactivity and absolute session-end warnings
-- =====================================================================================

-- ---------- User access requests (BRNB.085) ----------------------------------------------
create table nba_access_request (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    request_no       varchar(30)   not null unique,
    request_type     varchar(20)   not null,
    username         varchar(50)   not null,
    full_name        varchar(120),
    email            varchar(120),
    role_codes       varchar(500),
    home_branch_id   bigint        references org_branch (id),
    justification    varchar(1000) not null,
    status           varchar(20)   not null,
    decided_by       varchar(50),
    decided_at       timestamptz,
    decision_comment varchar(1000),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_nba_access_type check (request_type in ('CREATE_USER', 'MODIFY_ROLES', 'DISABLE_USER', 'ENABLE_USER')),
    constraint ck_nba_access_status check (status in ('PENDING', 'APPROVED', 'REJECTED')),
    constraint ck_nba_access_decided check (status = 'PENDING' or (decided_by is not null and decided_at is not null))
);
create index ix_nba_access_status on nba_access_request (status, created_at);
create index ix_nba_access_username on nba_access_request (lower(username));

-- ---------- Data retention (BRNB.106) ------------------------------------------------------
create table nba_retention_rule (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    record_type   varchar(40)  not null,
    statuses      varchar(200) not null,
    years_online  integer      not null,
    years_archive integer      not null,
    action        varchar(20)  not null,
    active        boolean      not null default true,
    description   varchar(300) not null,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_nba_retention_rule unique (record_type, statuses),
    constraint ck_nba_retention_years check (years_online > 0 and years_archive >= 0),
    constraint ck_nba_retention_action check (action in ('REVIEW', 'ARCHIVE'))
);

-- Result of each review run per rule (counts only: nothing is ever deleted).
create table nba_retention_run (
    id                 bigint generated by default as identity primary key,
    rule_id            bigint      not null references nba_retention_rule (id),
    business_date      date        not null,
    cutoff_date        date        not null,
    eligible_count     bigint,
    provider_available boolean     not null,
    run_at             timestamptz not null,
    run_by             varchar(50) not null
);
create index ix_nba_retention_run_rule on nba_retention_run (rule_id, id desc);

-- NFR data retention: 5 years online, 15 years archive (Q39 open: periods per record type).
insert into nba_retention_rule (record_type, statuses, years_online, years_archive, action, active,
                                description, created_at, created_by)
values ('CLIENT', 'INACTIVE', 5, 15, 'ARCHIVE', true,
        'Inactive clients without activity for the online period', now(), 'SYSTEM'),
       ('CLIENT', 'PROSPECT', 5, 15, 'REVIEW', true,
        'Prospects never confirmed (dormant leads)', now(), 'SYSTEM'),
       ('QUOTATION', 'NOT_PROCEEDED,VOIDED', 5, 15, 'ARCHIVE', true,
        'Package quotations not proceeded or voided', now(), 'SYSTEM'),
       ('PROPOSAL', 'NOT_PROCEEDED,VOIDED', 5, 15, 'ARCHIVE', true,
        'Proposal requests (PRF) not proceeded or voided', now(), 'SYSTEM'),
       ('ACCOUNT', 'VOIDED,CANCELLED', 5, 15, 'ARCHIVE', true,
        'Accounts voided or cancelled after issuance', now(), 'SYSTEM');

-- ---------- Session policy (BRNB.040) ----------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('SESSION_IDLE_WARNING_MINUTES', '15', 'INTEGER', 'SECURITY',
     'Minutes of inactivity after which the web client warns that the session will sign out (BRNB.040)',
     1, 480, now(), 'SYSTEM'),
    ('SESSION_EXPIRY_WARNING_MINUTES', '30', 'INTEGER', 'SECURITY',
     'Minutes before the system-triggered (absolute) sign-out at which the web client warns the user (BRNB.040)',
     1, 240, now(), 'SYSTEM');
