-- =====================================================================================
-- iNXT BrokerVerse - V800 CRM: broking clients (prospect -> confirmed), KYC status and
-- contact details.
--   BRNB.029 (client code with minimum prospect data), BRNB.030/048 (create client,
--   unique client code), BRNB.090 (onboarding before new business), BRNB.101 (distinct
--   prospect and client identifiers, conversion keeps history), BRNB.110 (KYC review date).
-- =====================================================================================
create table crm_client (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    prospect_code    varchar(30)   not null,
    client_code      varchar(30),
    status           varchar(20)   not null,
    client_type      varchar(20)   not null,
    last_name        varchar(100),
    first_name       varchar(100),
    middle_name      varchar(100),
    suffix           varchar(20),
    corporate_name   varchar(200),
    display_name     varchar(250)  not null,
    birth_date       date,
    tin              varchar(20),
    id_type          varchar(40),
    id_number        varchar(60),
    email            varchar(120),
    mobile           varchar(30),
    phone            varchar(30),
    address_line     varchar(300),
    city             varchar(80),
    province         varchar(80),
    postal_code      varchar(10),
    market_segment   varchar(40),
    bank_client      boolean       not null default false,
    bank_cif         varchar(40),
    party_code       varchar(30),
    kyc_status       varchar(20)   not null default 'NOT_STARTED',
    kyc_verified_by  varchar(50),
    kyc_verified_at  timestamptz,
    kyc_review_due   date,
    confirmed_by     varchar(50),
    confirmed_at     timestamptz,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_crm_client_prospect unique (company_id, prospect_code),
    constraint uq_crm_client_code unique (company_id, client_code),
    constraint ck_crm_client_status check (status in ('PROSPECT', 'CONFIRMED', 'INACTIVE')),
    constraint ck_crm_client_type check (client_type in ('INDIVIDUAL', 'CORPORATE')),
    constraint ck_crm_client_kyc check (kyc_status in ('NOT_STARTED', 'PENDING', 'VERIFIED', 'EXPIRED')),
    constraint ck_crm_client_confirmed check (status <> 'CONFIRMED' or client_code is not null),
    constraint ck_crm_client_name check (
        (client_type = 'INDIVIDUAL' and last_name is not null and first_name is not null)
        or (client_type = 'CORPORATE' and corporate_name is not null))
);
create index ix_crm_client_name on crm_client (company_id, lower(display_name));
create index ix_crm_client_tin on crm_client (company_id, tin);
create index ix_crm_client_id on crm_client (company_id, id_type, id_number);
create index ix_crm_client_email on crm_client (company_id, lower(email));
create index ix_crm_client_mobile on crm_client (company_id, mobile);
create index ix_crm_client_kyc_due on crm_client (company_id, kyc_review_due);

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('ID_TYPE', 'Identification document', 'Type of government-issued ID of an individual client', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'ID_TYPE', v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values ('PASSPORT', 'Passport', 10), ('DRIVERS_LICENSE', 'Driver''s license', 20),
             ('UMID', 'UMID', 30), ('PHILSYS', 'PhilSys national ID', 40), ('SSS', 'SSS ID', 50),
             ('PRC', 'PRC ID', 60), ('POSTAL', 'Postal ID', 70), ('TIN_ID', 'TIN ID', 80),
             ('SEC_REG', 'SEC registration (corporate)', 90), ('DTI_REG', 'DTI registration (sole proprietor)', 100)
) as v(code, label, sort_order);
