-- =====================================================================================
-- iNXT BrokerVerse - V801 CRM: complete client master, onboarding workflow, KYC documents,
-- duplicate keys, tags and special instructions.
--   BRNB.029  minimum prospect data, completeness flag (CLIENT_MIN_FIELDS_* parameters)
--   BRNB.030/048/049  client master per BDO standard (profile fields, validation, drafts)
--   BRNB.032  duplicate keys (TIN, ID, e-mail, mobile, name + birth date, corporate name)
--   BRNB.090/101  onboarding workflow NB_CLIENT: prospect -> KYC review -> verified -> confirmed
--   BRNB.091  client tags and special instructions with history
--   BRNB.110  KYC review cycle by risk rating (KYC_REVIEW_MONTHS parameters)
-- =====================================================================================

-- ---------- Client master: profile, onboarding and duplicate keys --------------------
alter table crm_client
    add column nationality        varchar(40),
    add column civil_status       varchar(40),
    add column occupation         varchar(120),
    add column source_of_funds    varchar(40),
    add column risk_rating        varchar(40),
    add column onboarding_stage   varchar(40),
    add column kyc_submitted_by   varchar(50),
    add column kyc_submitted_at   timestamptz,
    add column deactivation_reason varchar(40),
    add column deactivation_note  varchar(500),
    add column deactivated_by     varchar(50),
    add column deactivated_at     timestamptz,
    -- Normalised duplicate-detection keys, maintained by the application (BRNB.032).
    add column id_key             varchar(110),
    add column mobile_key         varchar(20),
    add column name_key           varchar(260),
    add column corporate_key      varchar(260);

create index ix_crm_client_id_key on crm_client (company_id, id_key);
create index ix_crm_client_mobile_key on crm_client (company_id, mobile_key);
create index ix_crm_client_name_key on crm_client (company_id, name_key, birth_date);
create index ix_crm_client_corporate_key on crm_client (company_id, corporate_key);
create index ix_crm_client_status on crm_client (company_id, status, kyc_status);

-- ---------- KYC documents (BRNB.030/090): typed client attachments ------------------
create table crm_kyc_document (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    client_id      bigint       not null references crm_client (id),
    document_type  varchar(40)  not null,
    attachment_id  bigint       not null references doc_attachment (id),
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);
create index ix_crm_kyc_document_client on crm_kyc_document (client_id, document_type);

-- ---------- Tags and special instructions (BRNB.091) ---------------------------------
create table crm_client_tag (
    id          bigint generated by default as identity primary key,
    version     bigint      not null default 0,
    client_id   bigint      not null references crm_client (id),
    tag_code    varchar(40) not null,
    active      boolean     not null default true,
    removed_by  varchar(50),
    removed_at  timestamptz,
    created_at  timestamptz not null,
    created_by  varchar(50) not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create unique index uq_crm_client_tag_active on crm_client_tag (client_id, tag_code) where active;

create table crm_client_instruction (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    client_id        bigint        not null references crm_client (id),
    instruction_type varchar(40)   not null,
    instruction_text varchar(1000) not null,
    effective_from   date          not null,
    effective_to     date,
    active           boolean       not null default true,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_crm_instruction_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_crm_client_instruction on crm_client_instruction (client_id, active);

-- Insert-only change history of tags and instructions: who, when, from / to.
create table crm_client_note_history (
    id          bigint generated by default as identity primary key,
    client_id   bigint        not null references crm_client (id),
    item_kind   varchar(20)   not null,
    item_ref    varchar(60)   not null,
    action      varchar(20)   not null,
    from_value  varchar(1200),
    to_value    varchar(1200),
    actor       varchar(50)   not null,
    occurred_at timestamptz   not null,
    constraint ck_crm_note_kind check (item_kind in ('TAG', 'INSTRUCTION')),
    constraint ck_crm_note_action check (action in ('ADDED', 'CHANGED', 'REMOVED'))
);
create index ix_crm_note_history_client on crm_client_note_history (client_id, id);

-- ---------- Onboarding workflow NB_CLIENT (BRNB.090/101) ----------------------------
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('CLIENT_DEACTIVATION_REASON', 'Client deactivation reason', 'Why a client is deactivated', true, now(), 'SYSTEM');

insert into wf_stage (workflow_code, stage_code, name, owner_permission, sla_hours, initial, terminal, sort_order)
values ('NB_CLIENT', 'PROSPECT', 'Prospect - KYC documents to complete', 'CLIENT_MAINTAIN', 72, true, false, 10),
       ('NB_CLIENT', 'KYC_REVIEW', 'KYC for verification', 'CLIENT_APPROVE', 24, false, false, 20),
       ('NB_CLIENT', 'KYC_VERIFIED', 'KYC verified - to confirm', 'CLIENT_MAINTAIN', 24, false, false, 30),
       ('NB_CLIENT', 'CONFIRMED', 'Confirmed client', null, null, false, false, 40),
       ('NB_CLIENT', 'INACTIVE', 'Inactive', null, null, false, true, 50);

insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_CLIENT', 'PROSPECT', 'submit_kyc', 'KYC_REVIEW', 'Submit KYC for verification', 'CLIENT_MAINTAIN', false, null, 10),
       ('NB_CLIENT', 'KYC_REVIEW', 'verify_kyc', 'KYC_VERIFIED', 'Verify KYC', 'CLIENT_APPROVE', false, null, 10),
       ('NB_CLIENT', 'KYC_REVIEW', 'return', 'PROSPECT', 'Return to Account Officer', 'CLIENT_APPROVE', true, 'RETURN_REASON', 20),
       ('NB_CLIENT', 'KYC_VERIFIED', 'confirm', 'CONFIRMED', 'Confirm client', 'CLIENT_MAINTAIN,CLIENT_APPROVE', false, null, 10),
       ('NB_CLIENT', 'CONFIRMED', 'review_kyc', 'CONFIRMED', 'Record periodic KYC review', 'CLIENT_APPROVE', false, null, 10),
       ('NB_CLIENT', 'PROSPECT', 'deactivate', 'INACTIVE', 'Deactivate', 'CLIENT_MAINTAIN,CLIENT_APPROVE', false, 'CLIENT_DEACTIVATION_REASON', 90),
       ('NB_CLIENT', 'KYC_REVIEW', 'deactivate', 'INACTIVE', 'Deactivate', 'CLIENT_MAINTAIN,CLIENT_APPROVE', false, 'CLIENT_DEACTIVATION_REASON', 90),
       ('NB_CLIENT', 'KYC_VERIFIED', 'deactivate', 'INACTIVE', 'Deactivate', 'CLIENT_MAINTAIN,CLIENT_APPROVE', false, 'CLIENT_DEACTIVATION_REASON', 90),
       ('NB_CLIENT', 'CONFIRMED', 'deactivate', 'INACTIVE', 'Deactivate', 'CLIENT_MAINTAIN,CLIENT_APPROVE', false, 'CLIENT_DEACTIVATION_REASON', 90);

-- ---------- Lists of values of the client master ------------------------------------
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('NATIONALITY', 'Nationality', 'Nationality of an individual client', true, now(), 'SYSTEM'),
       ('CIVIL_STATUS', 'Civil status', 'Civil status of an individual client', true, now(), 'SYSTEM'),
       ('SOURCE_OF_FUNDS', 'Source of funds', 'Declared source of funds (KYC)', true, now(), 'SYSTEM'),
       ('KYC_RISK_RATING', 'KYC risk rating', 'Client risk rating; drives the periodic KYC review cycle (BRNB.110)', true, now(), 'SYSTEM'),
       ('CLIENT_TAG', 'Client tag', 'Controlled client tags shown as banners (BRNB.091)', true, now(), 'SYSTEM'),
       ('INSTRUCTION_TYPE', 'Special instruction type', 'Type of a client or account special instruction (BRNB.091)', true, now(), 'SYSTEM'),
       ('KYC_DOCS_INDIVIDUAL', 'KYC checklist - individual', 'Mandatory KYC documents of an individual client; codes are DOCUMENT_TYPE codes (BRNB.090, parked Q16)', true, now(), 'SYSTEM'),
       ('KYC_DOCS_CORPORATE', 'KYC checklist - corporate', 'Mandatory KYC documents of a corporate client; codes are DOCUMENT_TYPE codes (BRNB.090, parked Q16)', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('DOCUMENT_TYPE', 'KYC_FORM', 'Client information sheet / KYC form', 11),
    ('DOCUMENT_TYPE', 'PROOF_OF_ADDRESS', 'Proof of address', 21),
    ('DOCUMENT_TYPE', 'SEC_CERTIFICATE', 'SEC / DTI certificate of registration', 31),
    ('DOCUMENT_TYPE', 'GIS', 'General Information Sheet (GIS)', 32),
    ('DOCUMENT_TYPE', 'SECRETARY_CERTIFICATE', 'Secretary''s certificate / board resolution', 33),
    ('KYC_DOCS_INDIVIDUAL', 'KYC_FORM', 'Client information sheet / KYC form', 10),
    ('KYC_DOCS_INDIVIDUAL', 'VALID_ID', 'Valid ID', 20),
    ('KYC_DOCS_CORPORATE', 'KYC_FORM', 'Client information sheet / KYC form', 10),
    ('KYC_DOCS_CORPORATE', 'SEC_CERTIFICATE', 'SEC / DTI certificate of registration', 20),
    ('KYC_DOCS_CORPORATE', 'GIS', 'General Information Sheet (GIS)', 30),
    ('KYC_DOCS_CORPORATE', 'SECRETARY_CERTIFICATE', 'Secretary''s certificate / board resolution', 40),
    ('CLIENT_DEACTIVATION_REASON', 'DUPLICATE', 'Duplicate client record', 10),
    ('CLIENT_DEACTIVATION_REASON', 'CLIENT_REQUEST', 'Client request', 20),
    ('CLIENT_DEACTIVATION_REASON', 'DECEASED_DISSOLVED', 'Deceased / dissolved', 30),
    ('CLIENT_DEACTIVATION_REASON', 'NO_BUSINESS', 'No business relationship', 40),
    ('CLIENT_DEACTIVATION_REASON', 'COMPLIANCE', 'Compliance decision', 50),
    ('CLIENT_DEACTIVATION_REASON', 'OTHERS', 'Others (see comment)', 90),
    ('NATIONALITY', 'FILIPINO', 'Filipino', 10),
    ('NATIONALITY', 'AMERICAN', 'American', 20),
    ('NATIONALITY', 'CHINESE', 'Chinese', 30),
    ('NATIONALITY', 'JAPANESE', 'Japanese', 40),
    ('NATIONALITY', 'KOREAN', 'Korean', 50),
    ('NATIONALITY', 'OTHERS', 'Others', 90),
    ('CIVIL_STATUS', 'SINGLE', 'Single', 10),
    ('CIVIL_STATUS', 'MARRIED', 'Married', 20),
    ('CIVIL_STATUS', 'WIDOWED', 'Widowed', 30),
    ('CIVIL_STATUS', 'SEPARATED', 'Legally separated / annulled', 40),
    ('SOURCE_OF_FUNDS', 'SALARY', 'Salary / employment', 10),
    ('SOURCE_OF_FUNDS', 'BUSINESS', 'Business income', 20),
    ('SOURCE_OF_FUNDS', 'REMITTANCE', 'Remittance', 30),
    ('SOURCE_OF_FUNDS', 'INVESTMENT', 'Investments / savings', 40),
    ('SOURCE_OF_FUNDS', 'PENSION', 'Pension', 50),
    ('SOURCE_OF_FUNDS', 'OTHERS', 'Others', 90),
    ('KYC_RISK_RATING', 'LOW', 'Low', 10),
    ('KYC_RISK_RATING', 'STANDARD', 'Standard', 20),
    ('KYC_RISK_RATING', 'HIGH', 'High (enhanced due diligence)', 30),
    ('CLIENT_TAG', 'VIP', 'VIP client', 10),
    ('CLIENT_TAG', 'BANK_EMPLOYEE', 'BDO employee', 20),
    ('CLIENT_TAG', 'DO_NOT_CALL', 'Do not call', 30),
    ('CLIENT_TAG', 'WATCHLIST_REVIEW', 'Watchlist review', 40),
    ('CLIENT_TAG', 'PEP', 'Politically exposed person', 50),
    ('INSTRUCTION_TYPE', 'BILLING', 'Billing and payment', 10),
    ('INSTRUCTION_TYPE', 'COMMUNICATION', 'Communication preference', 20),
    ('INSTRUCTION_TYPE', 'DOCUMENT_DELIVERY', 'Document delivery', 30),
    ('INSTRUCTION_TYPE', 'SERVICING', 'Servicing / renewal', 40),
    ('INSTRUCTION_TYPE', 'COLLECTION', 'Collection', 50),
    ('INSTRUCTION_TYPE', 'OTHERS', 'Others', 90)
) as v(type_code, code, label, sort_order);

-- ---------- Business parameters ------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('CLIENT_MIN_AGE', '18', 'INTEGER', 'CRM',
     'Minimum age in years of an individual policyholder (BRNB.030)', 0, 100, now(), 'SYSTEM'),
    ('KYC_REVIEW_MONTHS', '36', 'INTEGER', 'CRM',
     'Months between periodic KYC reviews of standard and low risk clients (BRNB.110)', 1, 120, now(), 'SYSTEM'),
    ('KYC_REVIEW_MONTHS_HIGH_RISK', '12', 'INTEGER', 'CRM',
     'Months between periodic KYC reviews of high risk clients (BRNB.110)', 1, 120, now(), 'SYSTEM'),
    ('KYC_DUE_WINDOW_DAYS', '30', 'INTEGER', 'CRM',
     'Days ahead in which a KYC review is listed as coming due (BRNB.110)', 0, 365, now(), 'SYSTEM'),
    ('CLIENT_MIN_FIELDS_INDIVIDUAL', 'BIRTH_DATE,TIN,ID,CONTACT,ADDRESS,MARKET_SEGMENT', 'CODE_LIST', 'CRM',
     'Fields an individual client needs to be complete (BRNB.029). Codes: BIRTH_DATE, TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, NATIONALITY, SOURCE_OF_FUNDS, OCCUPATION',
     null, null, now(), 'SYSTEM'),
    ('CLIENT_MIN_FIELDS_CORPORATE', 'TIN,CONTACT,ADDRESS,MARKET_SEGMENT', 'CODE_LIST', 'CRM',
     'Fields a corporate client needs to be complete (BRNB.029). Codes: TIN, ID, CONTACT, ADDRESS, MARKET_SEGMENT, SOURCE_OF_FUNDS',
     null, null, now(), 'SYSTEM');
