-- =====================================================================================
-- iNXT BrokerVerse - V802 CRM: client payout accounts (CA / SA information), additive only.
--   MKT 2.25.0  the CA / SA information of an approved refund request is added to the client
--               record (Addendum 1: credit to account = payee name and BDO account number;
--               check = payee name)
--   MKT 2.25.1  no duplicate CA / SA information: one live row per (client, account number),
--               one live check payee per (client, payee name)
-- Written by payrequest through crm.service.ClientPayoutAccounts (ACCOUNTING_DISBURSEMENT_DESIGN
-- 12.2); the account-number format of BDO is to be confirmed (AQ19).
-- =====================================================================================

create table crm_client_payout_account (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    company_id    bigint       not null references org_company (id),
    client_id     bigint       not null references crm_client (id),
    client_code   varchar(30)  not null,
    mode          varchar(10)  not null,
    payee_name    varchar(250) not null,
    payee_key     varchar(250) not null,
    account_no    varchar(40),
    source_module varchar(30)  not null,
    source_ref    varchar(80)  not null,
    active        boolean      not null default true,
    deactivated_by varchar(50),
    deactivated_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_crm_payout_mode check (mode in ('CTA', 'CHECK')),
    constraint ck_crm_payout_account check ((mode = 'CTA') = (account_no is not null))
);

create index ix_crm_payout_client on crm_client_payout_account (client_id, active);
create unique index uq_crm_payout_account on crm_client_payout_account (client_id, account_no)
    where active and account_no is not null;
create unique index uq_crm_payout_check on crm_client_payout_account (client_id, payee_key)
    where active and mode = 'CHECK';
