-- =====================================================================================
-- iNXT BrokerVerse - V810 Catalog: product lines and cover types (Annex II), BDOI risk
-- products (Annex I risk codes, Appendix B Fire and Motor packages), minimum-field matrix
-- and mandatory document checklist per line or product.
--   BRNB.001 one product master keyed by BDOI risk code and product line / cover type
--   BRNB.002/003/093 product-specific (minimum) fields and validation rules
--   BRNB.026/111 mandatory documents per product (document checklist)
--   Parked Q01/Q02: BDOI has not shared the product matrix files (MTR08..MTR38, PAR01..PAR25)
--   nor the minimum fields per line; the attributes and rules seeded here are sensible
--   defaults, maintained on the Products screen under maker-checker until BDOI confirms.
-- Every catalog table is maker-checker master data (record_status, authorized_by/at).
-- =====================================================================================
create table cat_product_line (
    id              bigint generated by default as identity primary key,
    version         bigint       not null default 0,
    code            varchar(30)  not null unique,
    name            varchar(120) not null,
    risk_item_kind  varchar(20)  not null,
    rating_method   varchar(20)  not null,
    sort_order      integer      not null default 0,
    record_status   varchar(30)  not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz  not null,
    created_by      varchar(50)  not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_cat_line_kind check (risk_item_kind in ('VEHICLE', 'PROPERTY_LOCATION', 'PERSON', 'GENERIC')),
    constraint ck_cat_line_rating check (rating_method in ('PROPERTY', 'MOTOR', 'GENERIC'))
);

create table cat_cover_type (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    line_code     varchar(30)  not null references cat_product_line (code),
    code          varchar(30)  not null,
    name          varchar(120) not null,
    sort_order    integer      not null default 0,
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_cover_type unique (line_code, code)
);

-- BDOI risk product (risk code). Rates are percentages (12.5 = 12.5 %).
create table cat_product (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    code                    varchar(20)    not null unique,
    name                    varchar(200)   not null,
    line_code               varchar(30)    not null references cat_product_line (code),
    cover_type_code         varchar(30),
    packaged                boolean        not null default false,
    fleet_capable           boolean        not null default false,
    -- Comma separated MARKET_SEGMENT codes; null = every segment.
    market_segments         varchar(300),
    mortgage_applicable     boolean        not null default false,
    direct_payment_eligible boolean        not null default false,
    multi_year_allowed      boolean        not null default false,
    max_term_years          integer        not null default 1,
    ffy_eligible            boolean        not null default false,
    payment_gate            varchar(30)    not null,
    default_rate            numeric(19, 8),
    default_commission_rate numeric(19, 8) not null default 0,
    minimum_premium         numeric(19, 2) not null default 0,
    -- Package TSI limit: above it the risk is priced as non-package through TSU (BRNB.098).
    max_sum_insured         numeric(19, 2),
    tsu_involvement         varchar(20)    not null default 'BY_RULES',
    record_status           varchar(30)    not null,
    authorized_by           varchar(50),
    authorized_at           timestamptz,
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50),
    constraint fk_cat_product_cover foreign key (line_code, cover_type_code)
        references cat_cover_type (line_code, code),
    constraint ck_cat_product_gate check (payment_gate in ('PAID', 'CLIENT_CONFIRMATION')),
    constraint ck_cat_product_tsu check (tsu_involvement in ('ALWAYS', 'NEVER', 'BY_RULES')),
    constraint ck_cat_product_term check (max_term_years between 1 and 10
        and (multi_year_allowed or max_term_years = 1)),
    constraint ck_cat_product_amounts check (minimum_premium >= 0 and default_commission_rate >= 0
        and (max_sum_insured is null or max_sum_insured > 0))
);
create index ix_cat_product_line on cat_product (line_code);

-- Minimum-field matrix (BRNB.002/003/093): scope ALL (every product), LINE (product line code)
-- or PRODUCT (risk code). A PRODUCT row overrides the LINE / ALL row with the same target and
-- field key (e.g. required = false to relax a line rule). Field keys separated by '|' mean
-- "at least one of" (plate number or conduction sticker).
create table cat_field_rule (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    scope         varchar(10)  not null,
    scope_code    varchar(30)  not null,
    target        varchar(10)  not null,
    field_key     varchar(80)  not null,
    label         varchar(120) not null,
    required      boolean      not null default true,
    sort_order    integer      not null default 0,
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_field_rule unique (scope, scope_code, target, field_key),
    constraint ck_cat_field_scope check (scope in ('ALL', 'LINE', 'PRODUCT')),
    constraint ck_cat_field_target check (target in ('ACCOUNT', 'ITEM'))
);

-- Mandatory documents (document type LOV) per line or product, checked when an account is
-- submitted to Processing.
create table cat_document_rule (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    scope         varchar(10)  not null,
    scope_code    varchar(30)  not null,
    document_type varchar(40)  not null,
    required      boolean      not null default true,
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_document_rule unique (scope, scope_code, document_type),
    constraint ck_cat_document_scope check (scope in ('ALL', 'LINE', 'PRODUCT'))
);

-- ---------- Product lines (Annex II) -------------------------------------------------
insert into cat_product_line (code, name, risk_item_kind, rating_method, sort_order, record_status,
                              authorized_by, authorized_at, created_at, created_by)
select v.code, v.name, v.kind, v.rating, v.sort_order, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('PROPERTY', 'Property', 'PROPERTY_LOCATION', 'PROPERTY', 10),
    ('MOTOR', 'Motor', 'VEHICLE', 'MOTOR', 20),
    ('ENGINEERING', 'Engineering', 'GENERIC', 'GENERIC', 30),
    ('LIABILITY', 'Liability', 'GENERIC', 'GENERIC', 40),
    ('CRIME', 'Crime', 'GENERIC', 'GENERIC', 50),
    ('FLOATER', 'Property / Equipment Floater', 'GENERIC', 'GENERIC', 60),
    ('MARINE', 'Marine', 'GENERIC', 'GENERIC', 70),
    ('MARINE_HULL', 'Marine Hull', 'GENERIC', 'GENERIC', 80),
    ('AVIATION', 'Aviation', 'GENERIC', 'GENERIC', 90),
    ('PERSONAL_ACCIDENT', 'Personal Accident', 'PERSON', 'GENERIC', 100),
    ('ELECTRONIC_EQUIPMENT', 'Electronic Equipment', 'GENERIC', 'GENERIC', 110),
    ('OTHERS', 'Others / Miscellaneous', 'GENERIC', 'GENERIC', 120)
) as v(code, name, kind, rating, sort_order);

insert into cat_cover_type (line_code, code, name, sort_order, record_status, authorized_by,
                            authorized_at, created_at, created_by)
select v.line_code, v.code, v.name, v.sort_order, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('PROPERTY', 'FIRE_LIGHTNING', 'Fire and Lightning only', 10),
    ('PROPERTY', 'ALL_RISK', 'All-Risk', 20),
    ('PROPERTY', 'BROAD_NAMED_PERILS', 'Broad-Named Perils', 30),
    ('MOTOR', 'TPL_ONLY', 'TPL only (no loss / damage cover)', 10),
    ('MOTOR', 'COMPREHENSIVE', 'Comprehensive', 20),
    ('ENGINEERING', 'CAR', 'Contractor''s All Risk (CAR)', 10),
    ('ENGINEERING', 'EAR', 'Erection All Risk (EAR)', 20),
    ('LIABILITY', 'CGL', 'Comprehensive General Liability (CGL)', 10),
    ('LIABILITY', 'CPL', 'Comprehensive Personal Liability (CPL)', 20),
    ('LIABILITY', 'EMPLOYERS', 'Employer''s Liability', 30),
    ('LIABILITY', 'PRODUCTS', 'Products Liability', 40),
    ('LIABILITY', 'PROFESSIONAL', 'Professional Liability', 50),
    ('LIABILITY', 'DNO', 'Directors and Officers (D&O)', 60),
    ('LIABILITY', 'ENO', 'Errors and Omissions (E&O)', 70),
    ('LIABILITY', 'CYBER', 'Cyber Liability', 80),
    ('LIABILITY', 'CONTAMINATED_PRODUCTS', 'Contaminated Products', 90),
    ('LIABILITY', 'POLLUTION_LEGAL', 'Pollution Legal Liability', 100),
    ('LIABILITY', 'CONTRACTORS_POLLUTION', 'Contractor''s Pollution Liability', 110),
    ('CRIME', 'MSP', 'Money, Securities and Payroll (MSP)', 10),
    ('CRIME', 'FG', 'Fidelity Guarantee (FG)', 20),
    ('CRIME', 'MSP_FG', 'MSP + FG', 30),
    ('CRIME', 'DDD', 'Dishonesty, Disappearance and Destruction (DDD)', 40),
    ('CRIME', 'BBB', 'Bankers Blanket Bond (BBB)', 50),
    ('FLOATER', 'FLOATER', 'Property / Equipment Floater', 10),
    ('MARINE', 'INLAND', 'Inland', 10),
    ('MARINE', 'INTER_ISLAND', 'Inter-Island', 20),
    ('MARINE', 'IMPORT', 'Import', 30),
    ('MARINE', 'EXPORT', 'Export', 40),
    ('MARINE', 'COMBINED', 'Combinations (open cover)', 50),
    ('MARINE', 'PROJECT_CARGO', 'Project Cargo', 60),
    ('MARINE', 'CHARTERERS_LIABILITY', 'Charterer''s Liability', 70),
    ('MARINE', 'TERMINAL_OPERATORS', 'Terminal Operators Liability', 80),
    ('MARINE', 'FREIGHT_FORWARDERS', 'Freight Forwarder''s Liability', 90),
    ('MARINE', 'STOCK_THROUGHPUT', 'Stock Throughput', 100),
    ('MARINE', 'TRUST_RECEIPT', 'Trust Receipt', 110),
    ('MARINE_HULL', 'HULL_MACHINERY', 'Hull and Machinery', 10),
    ('MARINE_HULL', 'SHIP_REPAIRERS', 'Ship Repairer''s Liability', 20),
    ('MARINE_HULL', 'BUILDERS_RISK', 'Builder''s Risk', 30),
    ('MARINE_HULL', 'P_AND_I', 'Protection and Indemnity', 40),
    ('AVIATION', 'GENERAL_AVIATION', 'General Aviation', 10),
    ('AVIATION', 'DRONE', 'Drone', 20),
    ('AVIATION', 'AIRPORT_CONTRACTORS', 'Airport Contractor''s Liability', 30),
    ('AVIATION', 'AIRPORT_OWNERS', 'Airport Owner''s and Operator''s Liability', 40),
    ('AVIATION', 'AVIATION_PRODUCTS', 'Aviation Products Liability', 50),
    ('AVIATION', 'AVIATION_REFUELLERS', 'Aviation Refuellers Liability', 60),
    ('AVIATION', 'HANGAR_KEEPERS', 'Hangar Keepers Liability', 70),
    ('AVIATION', 'PILOT_LOSS_LICENSE', 'Pilot Loss of License', 80),
    ('PERSONAL_ACCIDENT', 'INDIVIDUAL_PA', 'Individual PA', 10),
    ('PERSONAL_ACCIDENT', 'GROUP_PA', 'Group PA', 20),
    ('PERSONAL_ACCIDENT', 'MARINE_PA', 'Marine PA', 30),
    ('PERSONAL_ACCIDENT', 'TRAVEL_PA', 'Travel PA', 40),
    ('ELECTRONIC_EQUIPMENT', 'EEI', 'Electronic Equipment Insurance', 10),
    ('OTHERS', 'S_AND_T', 'S&T', 10),
    ('OTHERS', 'PV', 'Political Violence (PV)', 20),
    ('OTHERS', 'TRADE_CREDIT', 'Trade Credit', 30),
    ('OTHERS', 'PARAMETRIC', 'Parametric', 40),
    ('OTHERS', 'GOLFERS', 'Golfer''s / Hole-in-One', 50),
    ('OTHERS', 'FINE_ARTS', 'Fine Arts', 60),
    ('OTHERS', 'JEWELERS_BLOCK', 'Jewelers Block', 70)
) as v(line_code, code, name, sort_order);

-- ---------- Risk products: Annex I (Other Lines, as of 22-Oct-2025) --------------------
-- Line / cover type mapping by risk code family (BDOI to confirm, Q01). Programs and packages
-- are package products; client-specific open policies are non-package (TSU).
insert into cat_product (code, name, line_code, cover_type_code, packaged, fleet_capable,
                         market_segments, mortgage_applicable, direct_payment_eligible,
                         multi_year_allowed, max_term_years, ffy_eligible, payment_gate,
                         default_rate, default_commission_rate, minimum_premium, record_status,
                         authorized_by, authorized_at, created_at, created_by)
select v.code, v.name, v.line_code, v.cover_code,
       v.name ilike '%program%' or v.name ilike '%package%' or v.code in ('CTP01', 'CTP02', 'PA001'),
       v.line_code = 'MOTOR', null, false, true, false, 1, false, 'CLIENT_CONFIRMATION',
       v.rate, v.commission, v.minimum, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('CAR00', 'BDOI Contractor''s All Risk', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR01', 'BDO/SM Employees', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR02', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group A)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR03', 'BDOI Mall Tenants and Consignors Contractor''s All', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR04', 'Non-SM, Non-BDO, Non-SM Tenants, Non-SM Consignors', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR05', 'SM and BDO Owned Construction Projects', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR06', 'Various Non-SM, Non-BDO, Non-SM Tenants and Non-SM Consignors', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR07', 'Next Asialand Inc', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR09', 'SM Owned Projects - CARI Open Cover - Php100M and below', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR10', 'Mall Tenants and/or Consignors - CARI Open Cover - Php100M and below', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR11', '2021 BDOI CAR Program - Group A (Php500M and below)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR12', '2021 Goldilocks Bakeshop Open CARI Program', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR13', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR14', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group C)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR15', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group D)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR16', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group E)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR17', 'BDOI Commercial Banking Insurance Program - CAR/EAR (Group F)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR18', '2021 BDOI CAR Program - Group B (more than Php500M up to Php1B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR19', '2021 BDOI CAR Program - Group C (more than Php1B up to Php2B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR20', '2021 BDOI CAR Program - Group D (more than Php2B up to Php3B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR21', '2021 BDOI CAR Program - Group E (more than Php3B up to Php4B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR22', '2021 BDOI CAR Program - Group E (more than Php4B up to Php5B)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR23', '2023 Contractors'' All Risks Insurance (CARI) - Demolition Works (PGA)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR24', '2023 BDOI CARI Open Cover (Php100M and below)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR25', '2023 BDOI Contractor''s All Risk Insurance Program', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR26', 'SM Contractors Erection All Risk (Open Cover - single and one-time declaration projects)', 'ENGINEERING', 'EAR', 0.35, 15, 2000),
    ('CAR27', '2024 BDOI CARI Program (SM Construction only)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CAR29', '2024 BDOI CAR Insurance Program - SM Owned Projects (Stronghold Insurance Co., Inc)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CARI', 'Contractors All Risk Insurance Package (Residential/Commercial - CLG)', 'ENGINEERING', 'CAR', 0.35, 15, 2000),
    ('CGL01', '2020 BDOI Service Contractor''s CGL Insurance Program', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL02', 'BDOI Mall Tenants and Consignors CGL Insurance Program', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL03', 'BDOI CGL Program - Business Permit and Premises / Operation', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL06', 'CGL Insurance Program for Prime Spots, Inc.', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL07', 'CGL Insurance Program - Non-SM, Non-BDO, Non-SM Tenants, Non-SM Consignors', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL08', 'CGL Insurance Program - Non-SM, Non-BDO, Non-SM Tenants, Non-SM Consignors (Installation/Dismantling/Demolition)', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CGL09', '2023 2GO Truckers CGL Insurance Program', 'LIABILITY', 'CGL', 0.25, 15, 1500),
    ('CTP01', 'Compulsory Third Party Liability', 'MOTOR', 'TPL_ONLY', null, 10, 0),
    ('CTP02', 'Compulsory Third Party Liability (Non-VAT)', 'MOTOR', 'TPL_ONLY', null, 10, 0),
    ('EEI01', 'BDOI Electronic Equipment Insurance with EAR Extension for Medical/Stationary Equipment', 'ELECTRONIC_EQUIPMENT', 'EEI', 0.50, 15, 2000),
    ('EEI03', 'BDOI Electronic Equipment Insurance - Mirani Group', 'ELECTRONIC_EQUIPMENT', 'EEI', 0.50, 15, 2000),
    ('EEI04', 'BDOI Electronic Equipment Insurance with EAR Extension for Mobile Equipment', 'ELECTRONIC_EQUIPMENT', 'EEI', 0.50, 15, 2000),
    ('EPF02', 'BDO Remedial Property Floater Program (Package 2)', 'FLOATER', 'FLOATER', 0.40, 15, 2000),
    ('EPF04', '2021 Orix Metro Leasing EFP', 'FLOATER', 'FLOATER', 0.40, 15, 2000),
    ('EPF05', 'BDOI EPF with Political Violence', 'FLOATER', 'FLOATER', 0.40, 15, 2000),
    ('GIP01', '2021 Golfer''s Insurance Package', 'OTHERS', 'GOLFERS', null, 15, 500),
    ('INL01', '2021 Inland Marine Insurance Program', 'MARINE', 'INLAND', 0.15, 15, 1000),
    ('INL02', '2021 Comprehensive Inland Transit (Non-2GO) Insurance Program', 'MARINE', 'INLAND', 0.15, 15, 1000),
    ('INL03', 'Inland Marine Insurance Program - Paramount', 'MARINE', 'INLAND', 0.15, 15, 1000),
    ('INL05', '2022 Comprehensive Inland Transit Insurance 2GO Program', 'MARINE', 'INLAND', 0.15, 15, 1000),
    ('INL06', 'Inland Marine Insurance Program - Cocogen', 'MARINE', 'INLAND', 0.15, 15, 1000),
    ('MOP02', 'Marine Open Policy - Axa', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP04', 'Marine Open Policy for SM Investments / SM Prime / SM Development and/or Banco De Oro', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP05', 'Marine Open Policy for BDOI Corporate Accounts', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MON05', 'Marine Open Policy for BDOI Corporate Accounts (Non-VAT)', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP06', 'BDOI Marine Open Policy and Trust Receipts per Declaration and Annualized', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP07', 'Marine Open Policy for Ramesh Trading Corp', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP08', 'Marine Open Policy for Agrotrade Integrated Ventures Corp', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP09', 'Marine Open Policy for San Fernando Eric Commercial Inc', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP10', 'Marine Open Policy for Travellers International Hotel Group', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP11', 'BDOI Marine Open Policy - Mercantile Insurance', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP12', 'Marine Open Policy for Seven Seas & Leisure and/or Pamalican Resort', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP13', 'Marine Open Policy for ERA1 Petroleum Corporation', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('MOP14', 'MOP for Micro Dragon', 'MARINE', 'COMBINED', 0.15, 15, 1000),
    ('PA001', 'Personal Accident Insurance Program for Clients of BDOI', 'PERSONAL_ACCIDENT', 'INDIVIDUAL_PA', 0.20, 20, 500),
    ('TRP01', 'Trust Receipt Program', 'MARINE', 'TRUST_RECEIPT', 0.15, 15, 1000),
    ('TRP02', 'Trust Receipt Program - Mercantile', 'MARINE', 'TRUST_RECEIPT', 0.15, 15, 1000),
    ('TRP03', 'Combank Leasing BBG Branches - Trust Receipt Program', 'MARINE', 'TRUST_RECEIPT', 0.15, 15, 1000)
) as v(code, name, line_code, cover_code, rate, commission, minimum);

-- ---------- Risk products: Appendix B Fire (PAR) and Motor (MTR) packages -------------
-- CBG Fire and Motor must be paid before placement (BRD 2.3.1). Mortgaged (bank loan)
-- risks; multi-year allowed (BRNB.112); Free First Year for motor (BRNB.113).
insert into cat_product (code, name, line_code, cover_type_code, packaged, fleet_capable,
                         market_segments, mortgage_applicable, direct_payment_eligible,
                         multi_year_allowed, max_term_years, ffy_eligible, payment_gate,
                         default_rate, default_commission_rate, minimum_premium, record_status,
                         authorized_by, authorized_at, created_at, created_by)
select v.code, v.name, v.line_code, v.cover_code, true, v.line_code = 'MOTOR', 'CBG,RETAIL', true,
       v.line_code = 'MOTOR', true, v.max_term, v.line_code = 'MOTOR', 'PAID', v.rate, v.commission,
       v.minimum, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('MTR08', 'Motor package MTR08 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR10', 'Motor package MTR10 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR12', 'Motor package MTR12 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR15', 'Motor package MTR15 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR22', 'Motor package MTR22 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR23', 'Motor package MTR23 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR24', 'Motor package MTR24 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR25', 'Motor package MTR25 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR26', 'Motor package MTR26 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR27', 'Motor package MTR27 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR28', 'Motor package MTR28 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR29', 'Motor package MTR29 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR31', 'Motor package MTR31 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR32', 'Motor package MTR32 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR34', 'Motor package MTR34 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR35', 'Motor package MTR35 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('MTR38', 'Motor package MTR38 (product matrix to be loaded)', 'MOTOR', 'COMPREHENSIVE', 1.30, 15, 5000, 3),
    ('PAR01', 'Property package PAR01 (product matrix to be loaded)', 'PROPERTY', 'FIRE_LIGHTNING', 0.25, 20, 1000, 5),
    ('PAR08', 'Property package PAR08 (product matrix to be loaded)', 'PROPERTY', 'FIRE_LIGHTNING', 0.25, 20, 1000, 5),
    ('PAR09', 'Property package PAR09 (product matrix to be loaded)', 'PROPERTY', 'ALL_RISK', 0.30, 20, 1000, 5),
    ('PAR13', 'Property package PAR13 (product matrix to be loaded)', 'PROPERTY', 'FIRE_LIGHTNING', 0.25, 20, 1000, 5),
    ('PAR19', 'Property package PAR19 (product matrix to be loaded)', 'PROPERTY', 'BROAD_NAMED_PERILS', 0.28, 20, 1000, 5),
    ('PAR25', 'Property package PAR25 (product matrix to be loaded)', 'PROPERTY', 'FIRE_LIGHTNING', 0.25, 20, 1000, 5)
) as v(code, name, line_code, cover_code, rate, commission, minimum, max_term);

-- Package TSI limits of the Fire and Motor packages (to confirm with the matrix files, Q01).
update cat_product set max_sum_insured = 20000000 where code like 'PAR%';
update cat_product set max_sum_insured = 5000000 where code like 'MTR%';

-- ---------- Minimum-field matrix defaults (parked Q01/Q02) -----------------------------
insert into cat_field_rule (scope, scope_code, target, field_key, label, required, sort_order,
                            record_status, authorized_by, authorized_at, created_at, created_by)
select v.scope, v.scope_code, v.target, v.field_key, v.label, true, v.sort_order, 'ACTIVE',
       'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('ALL', '*', 'ACCOUNT', 'clientId', 'Client', 10),
    ('ALL', '*', 'ACCOUNT', 'marketSegment', 'Market segment', 20),
    ('ALL', '*', 'ACCOUNT', 'periodFrom', 'Period from', 30),
    ('ALL', '*', 'ACCOUNT', 'periodTo', 'Period to', 40),
    ('ALL', '*', 'ACCOUNT', 'currency', 'Currency', 50),
    ('ALL', '*', 'ACCOUNT', 'items', 'At least one risk item', 60),
    ('ALL', '*', 'ITEM', 'sumInsured', 'Sum insured', 10),
    ('LINE', 'MOTOR', 'ITEM', 'plateNo|conductionSticker', 'Plate number or conduction sticker', 20),
    ('LINE', 'MOTOR', 'ITEM', 'engineNo', 'Engine / motor number', 30),
    ('LINE', 'MOTOR', 'ITEM', 'chassisNo', 'Chassis / serial number', 40),
    ('LINE', 'MOTOR', 'ITEM', 'make', 'Make', 50),
    ('LINE', 'MOTOR', 'ITEM', 'model', 'Model', 60),
    ('LINE', 'MOTOR', 'ITEM', 'yearModel', 'Year model', 70),
    ('LINE', 'PROPERTY', 'ITEM', 'address', 'Full address of risk', 20),
    ('LINE', 'PROPERTY', 'ITEM', 'city', 'City / municipality', 30),
    ('LINE', 'PROPERTY', 'ITEM', 'occupancy', 'Occupancy', 40),
    ('LINE', 'PROPERTY', 'ITEM', 'constructionClass', 'Construction class', 50),
    ('LINE', 'PROPERTY', 'ITEM', 'insuredItems', 'Items insured with sum insured', 60),
    ('LINE', 'PERSONAL_ACCIDENT', 'ITEM', 'personName', 'Insured person', 20),
    ('LINE', 'PERSONAL_ACCIDENT', 'ITEM', 'birthDate', 'Birth date', 30),
    ('LINE', 'ENGINEERING', 'ITEM', 'description', 'Project and site description', 20),
    ('LINE', 'LIABILITY', 'ITEM', 'description', 'Business / operations covered', 20),
    ('LINE', 'CRIME', 'ITEM', 'description', 'Cover description', 20),
    ('LINE', 'FLOATER', 'ITEM', 'description', 'Equipment / property description', 20),
    ('LINE', 'MARINE', 'ITEM', 'description', 'Cargo / voyage description', 20),
    ('LINE', 'MARINE_HULL', 'ITEM', 'description', 'Vessel', 20),
    ('LINE', 'AVIATION', 'ITEM', 'description', 'Aircraft / operation', 20),
    ('LINE', 'ELECTRONIC_EQUIPMENT', 'ITEM', 'description', 'Equipment description', 20),
    ('LINE', 'OTHERS', 'ITEM', 'description', 'Description of the risk', 20)
) as v(scope, scope_code, target, field_key, label, sort_order);

insert into cat_document_rule (scope, scope_code, document_type, required, record_status,
                               authorized_by, authorized_at, created_at, created_by)
values ('LINE', 'MOTOR', 'IDF', true, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('LINE', 'PERSONAL_ACCIDENT', 'VALID_ID', true, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM');
