-- =====================================================================================
-- iNXT BrokerVerse - V811 Catalog: insurer panel (profile, branches with LGT, placement
-- e-mail), commission rates per insurer x product, tax and rating tables (Appendix A).
--   Appendix A: DST 12.5 % (half-peso rounding up), premium tax, VAT, FST 2 % (fire),
--   VAT 12 % on commission, LGT by insurer branch, OD/Theft coverage factors (Q35),
--   short-period table, excess BI / PD limit tables.
--   Parked Q06: insurer channels other than e-mail (SFTP / API); Q43: premium tax basis.
-- Rates are percentages (12.5 = 12.5 %) and effective dated; they are never constants.
-- =====================================================================================
create table cat_insurer (
    id                  bigint generated by default as identity primary key,
    version             bigint       not null default 0,
    company_id          bigint       not null references org_company (id),
    party_code          varchar(30)  not null,
    name                varchar(200) not null,
    short_name          varchar(40),
    accreditation_no    varchar(40),
    accredited_until    date,
    placement_channel   varchar(10)  not null default 'EMAIL',
    -- Comma separated placement / underwriting mailboxes.
    placement_emails    varchar(500),
    default_credit_days integer      not null default 30,
    record_status       varchar(30)  not null,
    authorized_by       varchar(50),
    authorized_at       timestamptz,
    created_at          timestamptz  not null,
    created_by          varchar(50)  not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_cat_insurer unique (company_id, party_code),
    constraint ck_cat_insurer_channel check (placement_channel in ('EMAIL', 'SFTP', 'API')),
    constraint ck_cat_insurer_credit check (default_credit_days between 0 and 365)
);

-- Appendix A: "LGT value is dependent on the Insurer Branch".
create table cat_insurer_branch (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    insurer_id      bigint         not null references cat_insurer (id),
    code            varchar(20)    not null,
    name            varchar(120)   not null,
    city            varchar(80),
    lgt_rate        numeric(19, 8) not null default 0,
    placement_email varchar(120),
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_cat_insurer_branch unique (insurer_id, code),
    constraint ck_cat_insurer_branch_lgt check (lgt_rate between 0 and 100)
);

-- Commission per insurer and product (null product = every product of the insurer).
create table cat_commission_rate (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    insurer_code   varchar(30)    not null,
    product_code   varchar(20)    references cat_product (code),
    rate           numeric(19, 8) not null,
    effective_from date           not null,
    effective_to   date,
    record_status  varchar(30)    not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint fk_cat_commission_insurer foreign key (company_id, insurer_code)
        references cat_insurer (company_id, party_code),
    constraint ck_cat_commission_rate check (rate between 0 and 100),
    constraint ck_cat_commission_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_cat_commission_lookup on cat_commission_rate (company_id, insurer_code, product_code);

-- Taxes and rating factors by line (null line = every line; a line row overrides it).
create table cat_rate (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    rate_code      varchar(30)    not null,
    line_code      varchar(30)    references cat_product_line (code),
    rate           numeric(19, 8) not null,
    effective_from date           not null,
    effective_to   date,
    record_status  varchar(30)    not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_cat_rate_code check (rate_code in ('DST', 'PREMIUM_TAX', 'VAT_PREMIUM',
        'FIRE_SERVICE_TAX', 'VAT_COMMISSION', 'MOTOR_OD_ANNUAL', 'MOTOR_OD_MULTI_YEAR')),
    constraint ck_cat_rate_value check (rate between 0 and 100),
    constraint ck_cat_rate_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_cat_rate_lookup on cat_rate (rate_code, line_code);

-- Short-period (short-term) table: months covered -> % of the annual premium.
create table cat_short_period_rate (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    months_covered   integer        not null,
    percent_of_annual numeric(19, 8) not null,
    effective_from   date           not null,
    effective_to     date,
    record_status    varchar(30)    not null,
    authorized_by    varchar(50),
    authorized_at    timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_cat_short_months check (months_covered between 1 and 12),
    constraint ck_cat_short_pct check (percent_of_annual between 0 and 100),
    constraint ck_cat_short_dates check (effective_to is null or effective_to >= effective_from)
);

-- Motor excess Bodily Injury / Property Damage limits and their premium (Appendix A).
create table cat_motor_limit (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    coverage       varchar(2)     not null,
    limit_amount   numeric(19, 2) not null,
    premium        numeric(19, 2) not null,
    effective_from date           not null,
    effective_to   date,
    record_status  varchar(30)    not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_cat_motor_limit_cov check (coverage in ('BI', 'PD')),
    constraint ck_cat_motor_limit_amounts check (limit_amount > 0 and premium >= 0),
    constraint ck_cat_motor_limit_dates check (effective_to is null or effective_to >= effective_from)
);

-- ---------- Seeded rates: exactly as Appendix A reads (to confirm, Q35 / Q43) ----------
insert into cat_rate (rate_code, line_code, rate, effective_from, record_status, authorized_by,
                      authorized_at, created_at, created_by)
select v.rate_code, v.line_code, v.rate, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('DST', null, 12.5),
    ('VAT_COMMISSION', null, 12),
    ('VAT_PREMIUM', null, 12),
    -- Fire: Appendix A computes PTX 12 % of net premium instead of VAT, plus FST 2 %.
    ('VAT_PREMIUM', 'PROPERTY', 0),
    ('PREMIUM_TAX', 'PROPERTY', 12),
    ('FIRE_SERVICE_TAX', 'PROPERTY', 2),
    ('MOTOR_OD_ANNUAL', 'MOTOR', 90),
    ('MOTOR_OD_MULTI_YEAR', 'MOTOR', 81)
) as v(rate_code, line_code, rate);

insert into cat_short_period_rate (months_covered, percent_of_annual, effective_from, record_status,
                                   authorized_by, authorized_at, created_at, created_by)
select v.months, v.pct, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values (1, 20), (2, 30), (3, 40), (4, 50), (5, 60), (6, 70), (7, 75), (8, 80), (9, 85),
             (10, 90), (11, 95), (12, 100)) as v(months, pct);

insert into cat_motor_limit (coverage, limit_amount, premium, effective_from, record_status,
                             authorized_by, authorized_at, created_at, created_by)
select v.coverage, v.limit_amount, v.premium, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('BI', 50000, 170), ('BI', 100000, 285), ('BI', 200000, 460), ('BI', 300000, 600),
    ('BI', 500000, 850), ('BI', 750000, 1100), ('BI', 1000000, 1350),
    ('PD', 50000, 290), ('PD', 100000, 440), ('PD', 200000, 700), ('PD', 300000, 900),
    ('PD', 500000, 1200), ('PD', 750000, 1550), ('PD', 1000000, 1850)
) as v(coverage, limit_amount, premium);
