-- =====================================================================================
-- iNXT BrokerVerse - V812 Catalog: TSU routing rules and sales organisation.
--   BRNB.098 rule-based TSU involvement (package / non-package, fleet threshold, multiple
--            locations, TSI threshold, endorsement type). Parked Q04: exact criteria; the
--            defaults below are the ones agreed for the build and are maintained on screen.
--   BRNB.075/108 production statistics per region / department / team / account officer;
--            default cost center (dimension COST_CENTER) per team. Parked Q34/Q41.
-- =====================================================================================
create table cat_tsu_rule (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    code            varchar(30)    not null unique,
    description     varchar(200)   not null,
    -- PACKAGE, NON_PACKAGE or ANY.
    product_class   varchar(12)    not null default 'ANY',
    line_code       varchar(30)    references cat_product_line (code),
    min_fleet_units integer,
    min_locations   integer,
    -- The rule matches when the total sum insured is strictly above this amount.
    tsi_above       numeric(19, 2),
    endorsement_type varchar(40),
    priority        integer        not null default 100,
    record_status   varchar(30)    not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_cat_tsu_class check (product_class in ('PACKAGE', 'NON_PACKAGE', 'ANY')),
    constraint ck_cat_tsu_thresholds check ((min_fleet_units is null or min_fleet_units > 0)
        and (min_locations is null or min_locations > 0) and (tsi_above is null or tsi_above >= 0))
);

insert into cat_tsu_rule (code, description, product_class, min_fleet_units, min_locations,
                          tsi_above, priority, record_status, authorized_by, authorized_at,
                          created_at, created_by)
values ('NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'NON_PACKAGE',
        null, null, null, 10, 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'),
       ('FLEET_5', 'Motor fleet of 5 units or more', 'ANY', 5, null, null, 20, 'ACTIVE', 'SYSTEM',
        now(), now(), 'SYSTEM'),
       ('TSI_50M', 'Total sum insured above PHP 50,000,000', 'ANY', null, null, 50000000, 30,
        'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM');

-- Sales organisation: REGION -> DEPARTMENT -> TEAM, with account officers per team.
create table cat_sales_unit (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    company_id    bigint       not null references org_company (id),
    unit_level    varchar(12)  not null,
    code          varchar(20)  not null,
    name          varchar(120) not null,
    parent_code   varchar(20),
    cost_center   varchar(20),
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_sales_unit unique (company_id, code),
    constraint ck_cat_sales_level check (unit_level in ('REGION', 'DEPARTMENT', 'TEAM')),
    constraint ck_cat_sales_parent check (unit_level = 'REGION' or parent_code is not null)
);

create table cat_sales_officer (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    company_id    bigint       not null references org_company (id),
    team_code     varchar(20)  not null,
    username      varchar(50)  not null,
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_sales_officer unique (company_id, username),
    constraint fk_cat_sales_officer_team foreign key (company_id, team_code)
        references cat_sales_unit (company_id, code)
);
