-- =====================================================================================
-- iNXT BrokerVerse - V813 Catalog (Product Maintenance, BRD-3): product hierarchy, coverage /
-- peril master, clause library and typed field rules.
--   PMADD01  one reusable hierarchy LOB > Subline / Type > Subtype > Coverage / Peril; a packaged
--            product cannot be saved without its cover type (the check below); naming convention
--            of risk codes as a per-line pattern (values wait for PQ02)
--   PMADD02  clause library (warranties, clauses, exclusions, deductible wordings) referenced by
--            the insurer x coverage terms of a package version (V814)
--   BRPM.003/004  field rules typed REQUIRED / LOV / RANGE / PATTERN
--   Design: docs/architecture/PRODUCT_MAINTENANCE_DESIGN.md sections 4.1 and 9.1.
--   Coverage and clause seeds are defaults for the Motor and Property packages until BDOI shares
--   the product matrix (Q01, PQ02); they are maintained on the Coverages & Clauses screen under
--   maker-checker (PRODUCT_MAINTAIN / PRODUCT_AUTHORIZE).
-- =====================================================================================

-- ---------- Hierarchy: subtype under a cover type (depth at most 2, same line) ----------------
alter table cat_cover_type add column parent_code varchar(30);
alter table cat_cover_type add constraint fk_cat_cover_type_parent
    foreign key (line_code, parent_code) references cat_cover_type (line_code, code);
alter table cat_cover_type add constraint ck_cat_cover_type_parent
    check (parent_code is null or parent_code <> code);

-- Naming convention of new risk codes of a line, as a regular expression (PMADD01 AC3, PQ02).
alter table cat_product_line add column code_pattern varchar(120);

-- Every seeded packaged product has a cover type; from now on it is mandatory (PMADD01).
alter table cat_product add constraint ck_cat_product_package_cover
    check (not packaged or cover_type_code is not null);

-- ---------- Coverage / peril master (PMADD01) ---------------------------------------------------
create table cat_coverage (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    line_code     varchar(30)  not null references cat_product_line (code),
    code          varchar(30)  not null,
    name          varchar(150) not null,
    kind          varchar(20)  not null,
    basic         boolean      not null default false,
    sort_order    integer      not null default 0,
    record_status varchar(30)  not null,
    authorized_by varchar(50),
    authorized_at timestamptz,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_cat_coverage unique (line_code, code)
);

-- ---------- Clause library (PMADD02) -----------------------------------------------------------
create table cat_clause (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    code           varchar(30)  not null unique,
    kind           varchar(20)  not null,
    -- null = every line
    line_code      varchar(30)  references cat_product_line (code),
    title          varchar(200) not null,
    wording        text         not null,
    effective_from date         not null,
    effective_to   date,
    record_status  varchar(30)  not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_cat_clause_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_cat_clause_line on cat_clause (line_code);

-- ---------- Typed field rules (BRPM.004) --------------------------------------------------------
alter table cat_field_rule add column rule_type varchar(10) not null default 'REQUIRED';
alter table cat_field_rule add column lov_type varchar(40);
alter table cat_field_rule add column min_value numeric(19, 2);
alter table cat_field_rule add column max_value numeric(19, 2);
alter table cat_field_rule add column pattern varchar(200);
alter table cat_field_rule add constraint ck_cat_field_rule_type
    check (rule_type in ('REQUIRED', 'LOV', 'RANGE', 'PATTERN')
        and (rule_type <> 'LOV' or lov_type is not null)
        and (rule_type <> 'RANGE' or min_value is not null or max_value is not null)
        and (rule_type <> 'PATTERN' or pattern is not null)
        and (min_value is null or max_value is null or max_value >= min_value));

-- ---------- Default coverages of the Motor and Property packages (Q01, PQ02) -------------------
insert into cat_coverage (line_code, code, name, kind, basic, sort_order, record_status,
                          authorized_by, authorized_at, created_at, created_by)
select v.line_code, v.code, v.name, v.kind, v.basic, v.sort_order, 'ACTIVE', 'SYSTEM', now(), now(),
       'SYSTEM'
from (values
    ('MOTOR', 'OD_THEFT', 'Own Damage and Theft', 'COVERAGE', true, 10),
    ('MOTOR', 'EXCESS_BI', 'Excess Bodily Injury', 'COVERAGE', false, 20),
    ('MOTOR', 'PD', 'Third Party Property Damage', 'COVERAGE', false, 30),
    ('MOTOR', 'AON', 'Acts of Nature', 'EXTENSION', false, 40),
    ('MOTOR', 'AUTO_PA', 'Auto Personal Accident', 'EXTENSION', false, 50),
    ('MOTOR', 'RSCC', 'Riot, Strike and Civil Commotion', 'EXTENSION', false, 60),
    ('PROPERTY', 'FIRE_LIGHTNING', 'Fire and Lightning', 'PERIL', true, 10),
    ('PROPERTY', 'EARTHQUAKE', 'Earthquake Fire and Shock', 'PERIL', false, 20),
    ('PROPERTY', 'TYPHOON_FLOOD', 'Typhoon and Flood', 'PERIL', false, 30),
    ('PROPERTY', 'EXTENDED_COVERAGE', 'Extended Coverage', 'EXTENSION', false, 40),
    ('PROPERTY', 'RSMD', 'Riot, Strike and Malicious Damage', 'EXTENSION', false, 50)
) as v(line_code, code, name, kind, basic, sort_order);

insert into cat_clause (code, kind, line_code, title, wording, effective_from, record_status,
                        authorized_by, authorized_at, created_at, created_by)
select v.code, v.kind, v.line_code, v.title, v.wording, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(),
       now(), 'SYSTEM'
from (values
    ('MTR_ACCREDITED_REPAIR', 'CLAUSE', 'MOTOR', 'Accredited Repair Shop Clause',
     'Repairs are carried out by a repair shop accredited by the insurer, unless agreed otherwise in writing.'),
    ('MTR_DEPRECIATION', 'CLAUSE', 'MOTOR', 'Depreciation Waiver Clause',
     'No depreciation is applied to parts replaced in the first year of the vehicle.'),
    ('MTR_PARTICIPATION', 'DEDUCTIBLE_WORDING', 'MOTOR', 'Participation Fee',
     'The insured bears the participation fee stated in the schedule for each and every own damage claim.'),
    ('PAR_WARRANTY_EXT', 'WARRANTY', 'PROPERTY', 'Fire Extinguishing Appliances Warranty',
     'Warranted that the fire extinguishing appliances are kept in working order at all times.'),
    ('PAR_FLOOD_EXCL', 'EXCLUSION', 'PROPERTY', 'Flood Exclusion (basement)',
     'Loss or damage to property in basements caused by flood is excluded.'),
    ('GEN_SANCTIONS', 'EXCLUSION', null, 'Sanctions Limitation and Exclusion Clause',
     'No insurer is deemed to provide cover or pay a claim to the extent that doing so would expose it to any sanction.')
) as v(code, kind, line_code, title, wording);
