-- =====================================================================================
-- iNXT BrokerVerse - V814 Catalog (Product Maintenance, BRD-3): package product versions with
-- their rate scheme, coverages and insurer terms, the validation checkpoint, product lifecycle
-- and rate-scheme exceptions.
--   BRPM.006  expired / retired products are archived, never deleted (lifecycle_status)
--   BRPM.007  new business uses the latest released rate scheme; a non-current version or rate
--             needs an approved exception (cat_rate_scheme_exception); every transaction stores
--             the version (V821 / V831 / V871)
--   BRPM.017  package term: start, end and anniversary dates
--   PMADD01/02  package composition per version (coverages, insurers, insurer x coverage terms)
--   PMADD06   version checkpoint: submitted, validated or returned (never by the maker)
--   Design: docs/architecture/PRODUCT_MAINTENANCE_DESIGN.md sections 4.2, 5 and 9.1.
-- Backfill: every packaged product gets version 1 RELEASED from its current commercial columns,
-- effective 2020-01-01 and validated by SYSTEM, so that nothing changes for new business until
-- a version 2 is released. Manual item rates stay allowed on these backfilled versions
-- (manual_rate_allowed, PQ10); versions set up from now on lock the item rate to the scheme.
-- =====================================================================================

alter table cat_product add column lifecycle_status varchar(10) not null default 'ACTIVE';
alter table cat_product add constraint ck_cat_product_lifecycle
    check (lifecycle_status in ('ACTIVE', 'EXPIRED', 'RETIRED'));

create table cat_product_version (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    product_code            varchar(20)    not null references cat_product (code),
    version_no              integer        not null,
    status                  varchar(20)    not null,
    effective_from          date           not null,
    effective_to            date,
    package_start_date      date,
    package_end_date        date,
    anniversary_date        date,
    -- rate scheme (percentages: 12.5 = 12.5 %)
    default_rate            numeric(19, 8),
    minimum_premium         numeric(19, 2) not null default 0,
    default_commission_rate numeric(19, 8) not null default 0,
    max_sum_insured         numeric(19, 2),
    rating_basis_note       varchar(1000),
    manual_rate_allowed     boolean        not null default false,
    -- origin
    source_request_no       varchar(40),
    mancom_signoff_ref      varchar(60),
    change_summary          varchar(1000),
    -- checkpoint (PMADD06)
    submitted_by            varchar(50),
    submitted_at            timestamptz,
    validated_by            varchar(50),
    validated_at            timestamptz,
    validation_checklist    varchar(4000),
    test_premium            numeric(19, 2),
    returned_reason         varchar(500),
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50),
    constraint uq_cat_product_version unique (product_code, version_no),
    constraint ck_cat_product_version_status
        check (status in ('DRAFT', 'FOR_VALIDATION', 'RELEASED', 'SUPERSEDED', 'EXPIRED')),
    constraint ck_cat_product_version_no check (version_no >= 1),
    constraint ck_cat_product_version_dates check (
        (effective_to is null or effective_to >= effective_from - 1)
        and (package_end_date is null or package_start_date is null
             or package_end_date > package_start_date)),
    constraint ck_cat_product_version_amounts check (
        minimum_premium >= 0 and default_commission_rate between 0 and 100
        and (default_rate is null or default_rate between 0 and 100)
        and (max_sum_insured is null or max_sum_insured > 0))
);
-- One version being set up per product, and one open-ended released version (design 4.2).
create unique index uq_cat_product_version_open on cat_product_version (product_code)
    where status in ('DRAFT', 'FOR_VALIDATION');
create unique index uq_cat_product_version_current on cat_product_version (product_code)
    where status = 'RELEASED' and effective_to is null;
create index ix_cat_product_version_status on cat_product_version (status, package_end_date);

create table cat_package_coverage (
    id                 bigint generated by default as identity primary key,
    version_id         bigint         not null references cat_product_version (id) on delete cascade,
    coverage_code      varchar(30)    not null,
    included           boolean        not null default true,
    optional           boolean        not null default false,
    limit_amount       numeric(19, 2),
    sub_limit          numeric(19, 2),
    deductible_amount  numeric(19, 2),
    deductible_percent numeric(19, 8),
    deductible_text    varchar(500),
    sort_order         integer        not null default 0,
    constraint uq_cat_package_coverage unique (version_id, coverage_code)
);

create table cat_package_insurer (
    id                  bigint generated by default as identity primary key,
    version_id          bigint         not null references cat_product_version (id) on delete cascade,
    company_id          bigint         not null references org_company (id),
    insurer_code        varchar(30)    not null,
    role                varchar(20)    not null,
    share_percent       numeric(19, 8),
    rate                numeric(19, 8),
    minimum_premium     numeric(19, 2),
    default_branch_code varchar(20),
    constraint uq_cat_package_insurer unique (version_id, insurer_code),
    constraint fk_cat_package_insurer foreign key (company_id, insurer_code)
        references cat_insurer (company_id, party_code),
    constraint ck_cat_package_insurer_role check (role in ('LEAD', 'PARTICIPANT', 'PANEL')),
    constraint ck_cat_package_insurer_values check (
        (share_percent is null or share_percent > 0 and share_percent <= 100)
        and (rate is null or rate between 0 and 100)
        and (minimum_premium is null or minimum_premium >= 0))
);

create table cat_package_insurer_term (
    id                 bigint generated by default as identity primary key,
    version_id         bigint         not null references cat_product_version (id) on delete cascade,
    insurer_code       varchar(30)    not null,
    coverage_code      varchar(30)    not null,
    included           boolean        not null default true,
    limit_amount       numeric(19, 2),
    sub_limit          numeric(19, 2),
    deductible_amount  numeric(19, 2),
    deductible_percent numeric(19, 8),
    deductible_text    varchar(500),
    -- comma-separated cat_clause codes
    clause_codes       varchar(1000),
    remarks            varchar(1000),
    constraint uq_cat_package_insurer_term unique (version_id, insurer_code, coverage_code)
);

-- ---------- Rate-scheme exceptions (BRPM.007; maker-checker, decided by PRODUCT_AUTHORIZE) ----
create table cat_rate_scheme_exception (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    reference_no         varchar(30)    not null unique,
    product_code         varchar(20)    not null references cat_product (code),
    purpose              varchar(20)    not null,
    requested_version_no integer,
    requested_rate       numeric(19, 8),
    -- the transaction it is for: quotation number or ARN
    transaction_ref      varchar(40)    not null,
    reason               varchar(1000)  not null,
    valid_until          date           not null,
    record_status        varchar(30)    not null,
    authorized_by        varchar(50),
    authorized_at        timestamptz,
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint ck_cat_rse_purpose check (purpose in ('NEW_BUSINESS', 'RENEWAL', 'ENDORSEMENT')),
    constraint ck_cat_rse_request check (requested_version_no is not null or requested_rate is not null),
    constraint ck_cat_rse_rate check (requested_rate is null or requested_rate between 0 and 100)
);
create index ix_cat_rse_product on cat_rate_scheme_exception (product_code, transaction_ref);

-- ---------- Backfill: version 1 RELEASED of every packaged product ------------------------------
insert into cat_product_version (product_code, version_no, status, effective_from, default_rate,
    minimum_premium, default_commission_rate, max_sum_insured, manual_rate_allowed, change_summary,
    submitted_by, submitted_at, validated_by, validated_at, validation_checklist, created_at, created_by)
select p.code, 1, 'RELEASED', date '2020-01-01', p.default_rate, p.minimum_premium,
       p.default_commission_rate, p.max_sum_insured, true,
       'Initial version from the product master (Product Maintenance go-live)', 'SYSTEM', now(),
       'SYSTEM', now(), 'MIGRATED', now(), 'SYSTEM'
from cat_product p
where p.packaged;
