-- =====================================================================================
-- iNXT BrokerVerse - V815 Catalog (Product Maintenance, BRD-3): incentive criteria maintained on
-- the products matrix.
--   PMADD07  criteria (for example CPC2) with type, value / rule, applicable products and
--            effective dates; only active products and insurers; incomplete set-ups refused;
--            an active criterion is changed by end-dating it and authorising a successor row
--   PMADD08  activation / deactivation with history; a criterion whose product expired or was
--            retired is flagged for review (alert INCENTIVE_PRODUCT_INACTIVE), never deleted
--   Design: docs/architecture/PRODUCT_MAINTENANCE_DESIGN.md sections 4.3 and 9.1. The content
--   (definition of CPC2 and the other criteria) waits for PQ04 / Q33 / OQ39.
-- =====================================================================================

create table cat_incentive_criteria (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    code           varchar(30)    not null,
    name           varchar(150)   not null,
    incentive_type varchar(30)    not null,
    value_basis    varchar(20)    not null,
    value          numeric(19, 8),
    -- JSON object of rule parameters (minimum premium, period type ...), PQ04
    rule_params    varchar(2000),
    description    varchar(1000),
    successor_of   bigint references cat_incentive_criteria (id),
    effective_from date           not null,
    effective_to   date,
    record_status  varchar(30)    not null,
    authorized_by  varchar(50),
    authorized_at  timestamptz,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_cat_incentive_criteria unique (company_id, code, effective_from),
    constraint ck_cat_incentive_basis check (value_basis in ('RATE', 'FIXED_AMOUNT', 'RULE')
        and (value_basis = 'RULE' or value is not null)
        and (value is null or value >= 0)
        and (value_basis <> 'RATE' or value <= 100)),
    constraint ck_cat_incentive_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_cat_incentive_criteria_code on cat_incentive_criteria (company_id, code);

create table cat_incentive_criteria_product (
    id              bigint generated by default as identity primary key,
    criteria_id     bigint      not null references cat_incentive_criteria (id) on delete cascade,
    product_code    varchar(20) not null references cat_product (code),
    cover_type_code varchar(30),
    market_segment  varchar(40),
    source_channel  varchar(40),
    insurer_code    varchar(30)
);
create index ix_cat_incentive_product on cat_incentive_criteria_product (product_code);

-- Migrated booking incentive rules (V871) and criteria whose content is not yet defined.
insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'INCENTIVE_TYPE', 'MIGRATED', 'Migrated booking incentive rule', 95, null, date '2020-01-01',
       'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
where not exists (select 1 from lov_value where type_code = 'INCENTIVE_TYPE' and code = 'MIGRATED');

insert into alt_exception_code (code, name, description, module, severity, threshold_amount,
    threshold_days, created_at, created_by)
values ('INCENTIVE_PRODUCT_INACTIVE', 'Incentive criterion on an inactive product',
        'An active incentive criterion applies to a package that expired or was retired: review or deactivate it (PMADD08).',
        'PRODUCT_MAINTENANCE', 'MEDIUM', null, null, now(), 'SYSTEM');
