-- =====================================================================================
-- iNXT BrokerVerse - V816 Product Maintenance (BRD-3) package request process (`productmaint`):
-- package requests, negotiation rounds and insurer responses, comparative outputs, ManCom
-- sign-off and advisories; document types and document templates.
--   Requirements: docs/requirements/BDOI_PM_BRD_SPEC.md
--     BRPM.008       Package Request Form PKR-<yyyy> with client / programme, line, cover type,
--                    target product, reason, requested terms and target insurers
--     BRPM.009/021   Marketing approval, TSU TL recommendation, TSU TH approval (stages of the
--                    PM_PACKAGE_REQUEST work case, V755; the status mirrors the stage)
--     BRPM.010/012   negotiation rounds, quotation slip PQS-<yyyy> per round with four-eyes
--                    approval, send and resend log (messaging outbox)
--     BRPM.013, PMADD04  insurer responses per round with outcome (LOV PKG_RESPONSE_OUTCOME) and
--                    structured terms per coverage; every change kept in the history table
--     BRPM.014, PMADD03  one current MASTER comparative per request, client outputs derived from
--                    it with selected fields and insurers; file hash and template version
--     BRPM.015       requirements pack, ManCom sign-off (signed sheet optional, PQ07), hand-off to
--                    MBS, resulting catalog version
--     BRPM.016       advisories with recipient groups (LOV PKG_ADVISORY_GROUP) and documents
--     BRPM.005       templates PKG_REQUEST_FORM, PKG_QUOTATION_SLIP, PKG_COMPARATIVE, PKG_SLIP,
--                    PKG_ADVISORY, PKG_RENEWAL_ADVISORY (draft layouts until Q03)
--   Design: docs/architecture/PRODUCT_MAINTENANCE_DESIGN.md sections 3, 4.4, 7 and 8.
--   Client, insurer and product codes are plain values (a NEW request has no product until the
--   MBS set-up; the catalog version is referenced by product code and version number).
-- =====================================================================================

create table pm_request (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    request_no                varchar(30)    not null,
    request_type              varchar(20)    not null,
    scope                     varchar(20)    not null,
    title                     varchar(200)   not null,
    client_id                 bigint,
    client_code               varchar(30),
    client_name               varchar(250),
    line_code                 varchar(30)    not null,
    cover_type_code           varchar(30),
    target_product_code       varchar(20),
    base_version_no           integer,
    market_segments           varchar(200),
    reason                    varchar(40)    not null,
    reason_note               varchar(500),
    negotiation_required      boolean        not null default true,
    -- Requested terms as JSON: sections, coverages, rate scheme, dates, target insurers (BRPM.008).
    requested_terms           text           not null,
    recommendation            varchar(2000),
    -- Terms after negotiation (and requirements) as JSON: what the MBS set-up turns into a version.
    proposed_terms            text,
    chosen_insurers           varchar(300),
    package_end_date          date,
    scheme_rate               numeric(19, 8),
    status                    varchar(30)    not null,
    submitted_by              varchar(50),
    submitted_at              timestamptz,
    approved_by               varchar(50),
    approved_at               timestamptz,
    recommended_by            varchar(50),
    recommended_at            timestamptz,
    tsu_approved_by           varchar(50),
    tsu_approved_at           timestamptz,
    terms_final_by            varchar(50),
    terms_final_at            timestamptz,
    requirements_by           varchar(50),
    requirements_at           timestamptz,
    setup_by                  varchar(50),
    setup_at                  timestamptz,
    resulting_version_no      integer,
    released_at               timestamptz,
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_pm_request_no unique (request_no),
    constraint fk_pm_request_line foreign key (line_code) references cat_product_line (code),
    constraint ck_pm_request_type check (request_type in ('NEW', 'AMEND', 'UPDATE', 'RENEW',
        'RETIRE', 'REACTIVATE')),
    constraint ck_pm_request_scope check (scope in ('GENERIC', 'CLIENT_SPECIFIC')),
    constraint ck_pm_request_status check (status in ('DRAFT', 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW',
        'FOR_TSU_APPROVAL', 'NEGOTIATION', 'TERMS_REVIEW', 'FOR_MKT_REVIEW', 'REQUIREMENTS_PREP',
        'FOR_MANCOM', 'WITH_MBS', 'FOR_VALIDATION', 'RELEASED', 'RETIRED', 'NOT_PROCEEDED',
        'VOIDED')),
    constraint ck_pm_request_client check (scope = 'GENERIC' or client_code is not null)
);
create index ix_pm_request_company on pm_request (company_id, status);
create index ix_pm_request_product on pm_request (target_product_code, request_type, status);
create index ix_pm_request_creator on pm_request (company_id, lower(created_by), status);

-- BRPM.010/012, PMADD04: one quotation slip per negotiation round, n = 1, 2, ...
create table pm_negotiation_round (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    request_id       bigint         not null references pm_request (id),
    round_no         integer        not null,
    status           varchar(20)    not null,
    qs_no            varchar(30),
    qs_template      varchar(60),
    qs_notes         varchar(4000),
    reply_due        date,
    prepared_by      varchar(50),
    submitted_at     timestamptz,
    approved_by      varchar(50),
    approved_at      timestamptz,
    sent_at          timestamptz,
    locked           boolean        not null default false,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_pm_round unique (request_id, round_no),
    constraint uq_pm_round_qs unique (qs_no),
    constraint ck_pm_round_status check (status in ('PREPARATION', 'FOR_APPROVAL', 'SENT', 'CLOSED')),
    constraint ck_pm_round_no check (round_no >= 1)
);

create table pm_round_insurer (
    round_id      bigint      not null references pm_negotiation_round (id),
    insurer_index integer     not null,
    insurer_code  varchar(30) not null,
    primary key (round_id, insurer_index)
);

create table pm_insurer_response (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    round_id             bigint         not null references pm_negotiation_round (id),
    insurer_code         varchar(30)    not null,
    insurer_name         varchar(200)   not null,
    outcome              varchar(30)    not null,
    revision             integer        not null default 0,
    rate                 numeric(19, 8),
    minimum_premium      numeric(19, 2),
    -- Terms per coverage as JSON: included, limit, sub-limit, deductible, clause codes, remarks.
    terms                text           not null default '[]',
    conditions           varchar(2000),
    valid_until          date,
    remarks              varchar(1000),
    response_document_id bigint,
    responded_at         timestamptz,
    last_message_id      bigint,
    sends                integer        not null default 0,
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_pm_response unique (round_id, insurer_code),
    constraint ck_pm_response_rate check (rate is null or rate >= 0),
    constraint ck_pm_response_minimum check (minimum_premium is null or minimum_premium >= 0)
);

create table pm_insurer_response_history (
    id                   bigint generated by default as identity primary key,
    response_id          bigint         not null references pm_insurer_response (id),
    revision             integer        not null,
    outcome              varchar(30)    not null,
    rate                 numeric(19, 8),
    minimum_premium      numeric(19, 2),
    terms                text           not null,
    conditions           varchar(2000),
    valid_until          date,
    remarks              varchar(1000),
    response_document_id bigint,
    changed_by           varchar(50)    not null,
    changed_at           timestamptz    not null
);
create index ix_pm_response_history on pm_insurer_response_history (response_id, revision);

-- BRPM.014, PMADD03: stored comparative outputs. content = the compiled table (JSON) the files
-- are rendered from; a CLIENT output renders a selection of its MASTER's content.
create table pm_comparative_output (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    request_id       bigint         not null references pm_request (id),
    round_no         integer        not null,
    kind             varchar(10)    not null,
    parent_output_id bigint references pm_comparative_output (id),
    is_current       boolean        not null default true,
    title            varchar(200)   not null,
    fields           varchar(500)   not null,
    insurers         varchar(500)   not null,
    content          text           not null,
    template_version varchar(60)    not null,
    attachment_id    bigint,
    sha256           varchar(64)    not null,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_pm_output_kind check (kind in ('MASTER', 'CLIENT')),
    constraint ck_pm_output_parent check (kind = 'MASTER' or parent_output_id is not null)
);
create unique index uq_pm_output_current_master on pm_comparative_output (request_id)
    where kind = 'MASTER' and is_current;
create index ix_pm_output_request on pm_comparative_output (request_id, kind);

-- BRPM.015: ManCom sign-off decisions (a return is kept as well).
create table pm_signoff (
    id                         bigint generated by default as identity primary key,
    version                    bigint         not null default 0,
    request_id                 bigint         not null references pm_request (id),
    kind                       varchar(20)    not null,
    decision                   varchar(20)    not null,
    reference                  varchar(40)    not null,
    signed_by                  varchar(50)    not null,
    signed_at                  timestamptz    not null,
    comment                    varchar(1000),
    signed_sheet_attachment_id bigint,
    created_at                 timestamptz    not null,
    created_by                 varchar(50)    not null,
    updated_at                 timestamptz,
    updated_by                 varchar(50),
    constraint ck_pm_signoff_kind check (kind in ('MANCOM')),
    constraint ck_pm_signoff_decision check (decision in ('SIGNED', 'RETURNED'))
);
create index ix_pm_signoff_request on pm_signoff (request_id);

-- BRPM.016: advisories drafted on release / retirement and sent to the recipient groups.
create table pm_advisory (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    request_id       bigint references pm_request (id),
    product_code     varchar(20)    not null,
    version_no       integer,
    advisory_type    varchar(20)    not null,
    recipient_groups varchar(200)   not null,
    email_to         varchar(1000),
    subject          varchar(200)   not null,
    body             text           not null,
    template_version varchar(60),
    status           varchar(10)    not null,
    document_ids     varchar(300),
    message_ids      varchar(300),
    sent_by          varchar(50),
    sent_at          timestamptz,
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_pm_advisory_type check (advisory_type in ('PACKAGE_READY', 'PACKAGE_UPDATED',
        'RENEWAL', 'RETIREMENT')),
    constraint ck_pm_advisory_status check (status in ('DRAFT', 'SENT'))
);
create index ix_pm_advisory_company on pm_advisory (company_id, status);
create index ix_pm_advisory_request on pm_advisory (request_id);

-- Document types of the package request (list DOCUMENT_TYPE, V750; design section 8).
insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'DOCUMENT_TYPE', v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values ('PKG_REQUEST_FORM', 'Package request form', 81),
             ('PKG_QUOTATION_SLIP', 'Package quotation slip', 82),
             ('PKG_INSURER_RESPONSE', 'Insurer package terms', 83),
             ('PKG_COMPARATIVE', 'Package comparative table', 84),
             ('PKG_SLIP_SIGNED', 'Package slip (signed)', 85),
             ('MANCOM_SIGNOFF', 'ManCom sign-off', 86),
             ('PKG_ADVISORY', 'Package advisory', 87)) as v(code, label, sort_order)
where not exists (select 1 from lov_value x where x.type_code = 'DOCUMENT_TYPE' and x.code = v.code);

-- Document templates (BRPM.005; draft layouts until Q03). Placeholders {{name}}.
insert into doc_template (code, version_no, title, body, effective_from, created_at, created_by)
values
('PKG_REQUEST_FORM', 1, 'Package request form',
 'Package request {{reference}} ({{requestType}}) for {{title}}. The requested terms, coverages and target insurers are shown below. Marketing approval, TSU review and TSU Head approval are recorded in the request history.', date '2020-01-01', now(), 'SYSTEM'),
('PKG_QUOTATION_SLIP', 1, 'Package quotation slip',
 'BDO Insurance and Reinsurance Brokers, Inc. requests your best terms for the package programme described below, reference {{reference}} (round {{roundNo}}). Please reply with your rate, minimum premium, coverages, limits, deductibles, warranties and validity on or before {{replyBy}}.', date '2020-01-01', now(), 'SYSTEM'),
('PKG_COMPARATIVE', 1, 'Package comparative table',
 'Comparative table of the insurer terms received for package request {{reference}}, round {{roundNo}}. {{variant}}', date '2020-01-01', now(), 'SYSTEM'),
('PKG_SLIP', 1, 'Package slip',
 'Package slip for {{title}} under request {{reference}}. The negotiated package terms, rate scheme and computation basis below are submitted for ManCom sign-off and for set-up by Marketing Business Services.', date '2020-01-01', now(), 'SYSTEM'),
('PKG_ADVISORY', 1, 'Package advisory',
 'This is to advise that the package {{productCode}} - {{productName}} (version {{versionNo}}) is available for new business from {{effectiveFrom}}. The signed package slip and the ManCom sign-off are kept with request {{reference}} in BIBS.', date '2020-01-01', now(), 'SYSTEM'),
('PKG_RENEWAL_ADVISORY', 1, 'Package renewal advisory',
 'This is to advise that the package {{productCode}} - {{productName}} has been renewed (version {{versionNo}}) and applies to new business from {{effectiveFrom}}. The signed package slip and the ManCom sign-off are kept with request {{reference}} in BIBS.', date '2020-01-01', now(), 'SYSTEM');
