-- =====================================================================================
-- iNXT BrokerVerse - V820 Accounts: the risk record placed with an insurer, identified by
-- its Account Reference Number (ARN) from quotation to invoice.
--   BRNB.019 soft delete (void) of in-process accounts      BRNB.025/052/053/054 update
--   BRNB.029 confirmed client before processing             BRNB.050 multi-criteria search
--   BRNB.051/066 multi-value risk items, duplicate fall-out BRNB.102 ARN
--   BRNB.109 account contacts defaulted from the client     BRNB.111 direct booking
--   BRNB.112 multi-year (one policy number per year)        BRNB.113 Free First Year
--   BRNB.114 payment arrangement (direct payment)           BRD 1.1.7-1.1.9, 2.1.8-2.1.12
-- The status mirrors the NB_ACCOUNT work case (V751). Lifecycle columns (payment, placement,
-- hold cover, policy, booking, cancellation) are written by later modules through
-- account.service.AccountLifecycleService.
-- =====================================================================================
create table acc_account (
    id                        bigint generated by default as identity primary key,
    version                   bigint         not null default 0,
    company_id                bigint         not null references org_company (id),
    arn                       varchar(30)    not null,
    quotation_ref             varchar(40),
    proposal_ref              varchar(40),
    client_id                 bigint         not null references crm_client (id),
    client_code               varchar(30)    not null,
    client_name               varchar(250)   not null,
    product_code              varchar(20)    not null references cat_product (code),
    line_code                 varchar(30)    not null,
    cover_type_code           varchar(30),
    market_segment            varchar(40),
    source_channel            varchar(40),
    insurer_code              varchar(30),
    insurer_branch            varchar(20),
    period_from               date,
    period_to                 date,
    multi_year                boolean        not null default false,
    term_years                integer        not null default 1,
    currency                  varchar(3)     not null default 'PHP',
    total_sum_insured         numeric(19, 2) not null default 0,
    -- Premium breakdown stored from the Appendix A calculator (null until rated).
    rating_basis              varchar(20),
    net_premium               numeric(19, 2),
    dst                       numeric(19, 2),
    premium_tax               numeric(19, 2),
    vat                       numeric(19, 2),
    fst                       numeric(19, 2),
    lgt                       numeric(19, 2),
    total_charges             numeric(19, 2),
    gross_premium             numeric(19, 2),
    commission_rate           numeric(19, 8),
    commission                numeric(19, 2),
    vat_on_commission         numeric(19, 2),
    minimum_applied           boolean        not null default false,
    payment_arrangement       varchar(20)    not null default 'VIA_BDOI',
    direct_payment_tagged_by  varchar(50),
    direct_payment_tagged_at  timestamptz,
    mortgagee_bank            varchar(40),
    loan_application_no       varchar(40),
    ffy                       boolean        not null default false,
    ffy_start                 date,
    ffy_end                   date,
    ffy_cancelled_at          timestamptz,
    ffy_cancelled_by          varchar(50),
    ffy_cancel_reason         varchar(300),
    contact_name              varchar(200),
    contact_email             varchar(120),
    contact_mobile            varchar(30),
    contact_address           varchar(300),
    sales_region              varchar(20),
    sales_department          varchar(20),
    sales_team                varchar(20),
    account_officer           varchar(50),
    cost_center               varchar(20),
    status                    varchar(30)    not null,
    tsu_required              boolean        not null default false,
    tsu_rule                  varchar(30),
    tsu_cleared_by            varchar(50),
    tsu_cleared_at            timestamptz,
    direct_booking            boolean        not null default false,
    payment_status            varchar(20)    not null default 'UNPAID',
    payment_source            varchar(60),
    payment_confirmed_at      timestamptz,
    placement_slip_ref        varchar(40),
    placed_at                 timestamptz,
    insurer_ref               varchar(60),
    hold_cover_status         varchar(20),
    hold_cover_ref            varchar(60),
    hold_cover_date           date,
    policy_issue_date         date,
    epolicy_received          boolean        not null default false,
    booking_ref               varchar(40),
    booked_at                 date,
    incentive_flag            boolean        not null default false,
    cancelled_at              date,
    cancellation_reason       varchar(300),
    created_at                timestamptz    not null,
    created_by                varchar(50)    not null,
    updated_at                timestamptz,
    updated_by                varchar(50),
    constraint uq_acc_account_arn unique (arn),
    constraint ck_acc_status check (status in ('DRAFT', 'SUBMITTED', 'RETURNED_TO_MARKETING',
        'AWAITING_PAYMENT', 'READY_FOR_PLACEMENT', 'PLACED', 'RETURNED_BY_INSURER',
        'PLACEMENT_CANCELLED', 'POLICY_ISSUED', 'BOOKED', 'CANCELLED', 'VOIDED')),
    constraint ck_acc_payment_arrangement check (payment_arrangement in ('VIA_BDOI', 'DIRECT_TO_INSURER')),
    constraint ck_acc_payment_status check (payment_status in ('UNPAID', 'PAID', 'CLIENT_CONFIRMED', 'DIRECT')),
    constraint ck_acc_hold_cover check (hold_cover_status is null
        or hold_cover_status in ('REQUESTED', 'CONFIRMED', 'DECLINED', 'EXPIRED')),
    constraint ck_acc_period check (period_to is null or period_from is null or period_to > period_from),
    constraint ck_acc_term check (term_years between 1 and 10 and (multi_year or term_years = 1)),
    constraint ck_acc_ffy check (not ffy or (ffy_start is not null and ffy_end is not null))
);
create index ix_acc_account_company on acc_account (company_id, status);
create index ix_acc_account_client on acc_account (client_id);
create index ix_acc_account_product on acc_account (product_code);
create index ix_acc_account_insurer on acc_account (company_id, insurer_code);
create index ix_acc_account_officer on acc_account (company_id, lower(account_officer), status);
create index ix_acc_account_quotation on acc_account (quotation_ref);

-- Promissory note numbers (CLPC billing, BRNB.067): several per account.
create table acc_account_pn (
    account_id bigint      not null references acc_account (id),
    pn_index   integer     not null,
    pn_number  varchar(40) not null,
    primary key (account_id, pn_index)
);
create index ix_acc_pn_number on acc_account_pn (upper(pn_number));

-- Policy numbers: one per policy year of a multi-year account (BRNB.112).
create table acc_account_policy (
    account_id    bigint      not null references acc_account (id),
    year_index    integer     not null,
    policy_number varchar(60) not null,
    primary key (account_id, year_index)
);
create index ix_acc_policy_number on acc_account_policy (policy_number);

-- Risk items (BRNB.051). Vehicle identifiers are stored normalised (upper-case letters and
-- digits only) so the duplicate fall-out compares like with like.
create table acc_risk_item (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    account_id         bigint         not null references acc_account (id),
    item_no            integer        not null,
    kind               varchar(20)    not null,
    description        varchar(300),
    sum_insured        numeric(19, 2),
    rate               numeric(19, 8),
    premium            numeric(19, 2),
    bi_limit           numeric(19, 2),
    pd_limit           numeric(19, 2),
    plate_no           varchar(20),
    conduction_sticker varchar(20),
    engine_no          varchar(40),
    chassis_no         varchar(40),
    make               varchar(60),
    model              varchar(60),
    year_model         integer,
    body_type          varchar(40),
    colour             varchar(40),
    seating_capacity   integer,
    address            varchar(300),
    city               varchar(80),
    province           varchar(80),
    occupancy          varchar(40),
    construction_class varchar(40),
    location_key       varchar(400),
    person_name        varchar(200),
    birth_date         date,
    relationship       varchar(40),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint uq_acc_risk_item unique (account_id, item_no),
    constraint ck_acc_item_kind check (kind in ('VEHICLE', 'PROPERTY_LOCATION', 'PERSON', 'GENERIC')),
    constraint ck_acc_item_sum check (sum_insured is null or sum_insured >= 0)
);
create index ix_acc_item_plate on acc_risk_item (plate_no) where plate_no is not null;
create index ix_acc_item_conduction on acc_risk_item (conduction_sticker) where conduction_sticker is not null;
create index ix_acc_item_engine on acc_risk_item (engine_no) where engine_no is not null;
create index ix_acc_item_chassis on acc_risk_item (chassis_no) where chassis_no is not null;
create index ix_acc_item_location on acc_risk_item (location_key) where location_key is not null;

-- Items insured at a location of risk (building, contents...) with their sum insured.
create table acc_risk_item_detail (
    risk_item_id bigint         not null references acc_risk_item (id),
    detail_index integer        not null,
    description  varchar(200)   not null,
    sum_insured  numeric(19, 2) not null,
    primary key (risk_item_id, detail_index),
    constraint ck_acc_item_detail_sum check (sum_insured >= 0)
);

-- ---------- Lists of values for coded account fields ---------------------------------
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('VEHICLE_BODY_TYPE', 'Vehicle body type', 'Body type of an insured vehicle', true, now(), 'SYSTEM'),
       ('CONSTRUCTION_CLASS', 'Construction class', 'Construction class of a building (fire)', true, now(), 'SYSTEM'),
       ('OCCUPANCY', 'Occupancy', 'Occupancy of a location of risk (fire)', true, now(), 'SYSTEM'),
       ('MORTGAGEE_BANK', 'Mortgagee bank', 'Bank unit holding the mortgage (Insurance Advice, CLPC billing)', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('VEHICLE_BODY_TYPE', 'SEDAN', 'Sedan', 10),
    ('VEHICLE_BODY_TYPE', 'HATCHBACK', 'Hatchback', 20),
    ('VEHICLE_BODY_TYPE', 'SUV', 'SUV / AUV', 30),
    ('VEHICLE_BODY_TYPE', 'PICKUP', 'Pick-up', 40),
    ('VEHICLE_BODY_TYPE', 'VAN', 'Van', 50),
    ('VEHICLE_BODY_TYPE', 'TRUCK', 'Truck', 60),
    ('VEHICLE_BODY_TYPE', 'MOTORCYCLE', 'Motorcycle', 70),
    ('CONSTRUCTION_CLASS', 'CLASS_1', 'Class 1 - concrete / fire-resistive', 10),
    ('CONSTRUCTION_CLASS', 'CLASS_2', 'Class 2 - semi-concrete', 20),
    ('CONSTRUCTION_CLASS', 'CLASS_3', 'Class 3 - mixed materials', 30),
    ('CONSTRUCTION_CLASS', 'CLASS_4', 'Class 4 - light materials', 40),
    ('OCCUPANCY', 'DWELLING', 'Dwelling / residential', 10),
    ('OCCUPANCY', 'CONDOMINIUM', 'Condominium unit', 20),
    ('OCCUPANCY', 'OFFICE', 'Office', 30),
    ('OCCUPANCY', 'RETAIL', 'Retail / store', 40),
    ('OCCUPANCY', 'WAREHOUSE', 'Warehouse', 50),
    ('OCCUPANCY', 'FACTORY', 'Factory / industrial', 60),
    ('MORTGAGEE_BANK', 'BDO_HOME_LOANS', 'BDO Home Loans', 10),
    ('MORTGAGEE_BANK', 'BDO_AUTO_LOANS', 'BDO Auto Loans', 20),
    ('MORTGAGEE_BANK', 'BDO_COMMERCIAL', 'BDO Commercial Lending', 30),
    ('MORTGAGEE_BANK', 'BDO_LEASING', 'BDO Leasing and Finance', 40)
) as v(type_code, code, label, sort_order);

-- Direct booking needs the issued policy (BRNB.111): e-policy or policy copy document types
-- (V750). Free First Year cancellation reasons.
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('FFY_CANCEL_REASON', 'FFY cancellation reason', 'Why a Free First Year tag is cancelled', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'FFY_CANCEL_REASON', v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values ('LOAN_CANCELLED', 'Auto loan cancelled', 10), ('DEALER_WITHDREW', 'Dealer promo withdrawn', 20),
             ('TAGGED_IN_ERROR', 'Tagged in error', 30), ('OTHERS', 'Others (see comment)', 90)
) as v(code, label, sort_order);
