-- =====================================================================================
-- iNXT BrokerVerse - V823 Legacy policy headers as accounts (Data Migration BRD-13, wave DM1-C;
-- docs/architecture/DATA_MIGRATION_DESIGN.md sections 10, 14.5 and 15).
--   acc_account.origin MIGRATED   an in-force policy imported from a legacy system (P01)
--   acc_account_legacy            its legacy header: source system, legacy policy reference,
--                                 policy and cover numbers, the legacy package kept as given
--                                 (remapped at Renewal sanitation), legacy status and the
--                                 migration batch that loaded it (rollback per batch)
-- A separate table keeps acc_account (V820) unchanged for the other account flows.
-- =====================================================================================

alter table acc_account drop constraint ck_acc_origin;
alter table acc_account add constraint ck_acc_origin
    check (origin in ('QUOTATION', 'PROPOSAL', 'DIRECT', 'SUBMITTED_POLICY', 'EMPLOYEE_BENEFITS',
                      'RENEWAL', 'MIGRATED'));

create table acc_account_legacy (
    id                     bigint generated by default as identity primary key,
    account_id             bigint        not null unique references acc_account (id),
    version                bigint        not null default 0,
    company_id             bigint        not null references org_company (id),
    source_system          varchar(10)   not null,
    legacy_ref             varchar(80)   not null,
    policy_no              varchar(60)   not null,
    cover_no               varchar(40)   not null,
    cover_version          integer,
    legacy_client_no       varchar(80)   not null,
    legacy_package_code    varchar(20),
    legacy_package_version integer,
    legacy_status          varchar(20),
    assured_name           varchar(200),
    migration_batch        varchar(20)   not null,
    rolled_back_at         timestamptz,
    created_at             timestamptz   not null,
    created_by             varchar(50)   not null,
    updated_at             timestamptz,
    updated_by             varchar(50)
);
create unique index uq_acc_account_legacy_ref on acc_account_legacy (company_id, source_system, legacy_ref)
    where rolled_back_at is null;
create index ix_acc_account_legacy_policy on acc_account_legacy (company_id, policy_no);
create index ix_acc_account_legacy_cover on acc_account_legacy (company_id, cover_no);
create index ix_acc_account_origin on acc_account (company_id, origin);
