-- =====================================================================================
-- iNXT BrokerVerse - V830 Package quotations: request intake, quotations with versions,
-- approval, send, acceptance and conversion to accounts.
--   BRNB.041 request intake (manual capture, e-mail attached)   BRNB.023 HLS staging (parked, Q11)
--   BRNB.004 intake template version stamped on each quotation BRNB.020 versions (v1..vn), diff
--   BRNB.013/014/021/043 approval before send, protected PDF / XLSX to the client
--   BRNB.045 acceptance with the client's e-mail, accounts per accepted risk group
--   BRNB.024/028/042/063 bulk quotations and acceptances        BRNB.102 ARN at creation
--   MKTID.011 (Operations BRD) direct-payment flag at quotation, carried to the account
-- The status mirrors the NB_QUOTATION work case (V751). The versioned content (items, premium,
-- insurer, period, validity, direct payment) is kept as JSON per version in quo_version; the
-- quotation row holds the header and the figures of the current version for lists and search.
-- =====================================================================================

-- Staging table of quotation requests: captured by Marketing from an e-mail (the e-mail is
-- attached as document type REQUEST_EMAIL), uploaded in bulk (QUOTATION_REQUEST) or fed by a
-- source system through the port quotation.service.QuotationRequestSource (HLS, parked Q11).
create table quo_request (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    request_no      varchar(30)   not null,
    channel         varchar(40)   not null,
    external_ref    varchar(60),
    received_at     timestamptz   not null,
    client_id       bigint        references crm_client (id),
    prospect_name   varchar(250),
    prospect_email  varchar(120),
    prospect_mobile varchar(30),
    product_code    varchar(20)   references cat_product (code),
    market_segment  varchar(40),
    requested_cover varchar(2000),
    status          varchar(20)   not null,
    quotation_id    bigint,
    close_reason    varchar(300),
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_quo_request_no unique (request_no),
    constraint ck_quo_request_status check (status in ('NEW', 'QUOTED', 'CLOSED')),
    constraint ck_quo_request_party check (client_id is not null or prospect_name is not null)
);
create index ix_quo_request_company on quo_request (company_id, status);
-- A source system never delivers the same request twice.
create unique index uq_quo_request_external on quo_request (channel, external_ref)
    where external_ref is not null;

create table quo_quotation (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    quotation_no      varchar(30)    not null,
    arn               varchar(30)    not null,
    request_id        bigint         references quo_request (id),
    client_id         bigint         not null references crm_client (id),
    client_code       varchar(30)    not null,
    client_name       varchar(250)   not null,
    client_email      varchar(120),
    product_code      varchar(20)    not null references cat_product (code),
    line_code         varchar(30)    not null,
    market_segment    varchar(40),
    source_channel    varchar(40),
    insurer_code      varchar(30),
    insurer_branch    varchar(20),
    period_from       date,
    period_to         date,
    valid_until       date           not null,
    currency          varchar(3)     not null default 'PHP',
    -- MKTID.011: premium paid directly to the insurer; carried to the accounts.
    direct_payment    boolean        not null default false,
    -- BRNB.004: intake template (code and version) in force when the quotation was created.
    template_version  varchar(60)    not null,
    current_version   integer        not null default 1,
    -- false once the current version was submitted: the next change opens version n+1.
    version_open      boolean        not null default true,
    risk_groups       integer        not null default 1,
    total_sum_insured numeric(19, 2) not null default 0,
    net_premium       numeric(19, 2),
    gross_premium     numeric(19, 2),
    commission        numeric(19, 2),
    tsu_required      boolean        not null default false,
    tsu_reason        varchar(300),
    status            varchar(30)    not null,
    submitted_by      varchar(50),
    submitted_at      timestamptz,
    approved_by       varchar(50),
    approved_at       timestamptz,
    sent_at           timestamptz,
    accepted_at       timestamptz,
    accepted_groups   varchar(200),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_quo_quotation_no unique (quotation_no),
    constraint uq_quo_quotation_arn unique (arn),
    constraint ck_quo_status check (status in ('DRAFT', 'FOR_REVIEW', 'APPROVED', 'SENT_TO_CLIENT',
        'ACCEPTED', 'CONVERTED', 'NOT_PROCEEDED', 'VOIDED')),
    constraint ck_quo_period check (period_to is null or period_from is null or period_to > period_from),
    constraint ck_quo_groups check (risk_groups >= 1)
);
create index ix_quo_quotation_company on quo_quotation (company_id, status);
create index ix_quo_quotation_client on quo_quotation (client_id);
create index ix_quo_quotation_creator on quo_quotation (company_id, lower(created_by), status);
create index ix_quo_quotation_valid on quo_quotation (company_id, valid_until);

-- Accounts created from the quotation (one per accepted risk group), by ARN.
create table quo_quotation_account (
    quotation_id  bigint      not null references quo_quotation (id),
    account_index integer     not null,
    arn           varchar(30) not null,
    primary key (quotation_id, account_index)
);

-- BRNB.020: every version of the quotation content; submitted versions are frozen (read-only).
create table quo_version (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    quotation_id      bigint         not null references quo_quotation (id),
    version_no        integer        not null,
    content           text           not null,
    total_sum_insured numeric(19, 2) not null default 0,
    gross_premium     numeric(19, 2),
    frozen            boolean        not null default false,
    frozen_by         varchar(50),
    frozen_at         timestamptz,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_quo_version unique (quotation_id, version_no),
    constraint ck_quo_version_no check (version_no >= 1)
);

-- Revising an approved or sent quotation reopens it as a draft; the next change is version n+1
-- (BRNB.020). Business action of QuotationService, not a generic transition.
insert into wf_transition (workflow_code, from_stage, action, to_stage, label, permission, generic, reason_lov, sort_order)
values ('NB_QUOTATION', 'APPROVED', 'revise', 'DRAFT', 'Revise (new version)', 'QUOTE_MAINTAIN', false, null, 50),
       ('NB_QUOTATION', 'SENT_TO_CLIENT', 'revise', 'DRAFT', 'Revise (new version)', 'QUOTE_MAINTAIN', false, null, 50);

-- Document types of the quotation and proposal flows (list DOCUMENT_TYPE, V750).
insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'DOCUMENT_TYPE', v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values ('REQUEST_EMAIL', 'Quotation / proposal request e-mail', 45)) as v(code, label, sort_order);

-- Numbering prefixes stay configurable while the BDOI format is open (UX-1, Q15); validity and
-- the expiring window of the quotation list.
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('QUOTATION_NUMBER_PREFIX', 'QT', 'STRING', 'BROKING',
     'Prefix of package quotation numbers (<prefix>-<yyyy>-nnnnnn), shown as Proposal No. (UX-1)',
     null, null, now(), 'SYSTEM'),
    ('QUOTATION_REQUEST_PREFIX', 'REQ', 'STRING', 'BROKING',
     'Prefix of quotation request numbers (<prefix>-<yyyy>-nnnnnn), BRNB.041', null, null, now(), 'SYSTEM'),
    ('QUOTATION_VALIDITY_DAYS', '30', 'INTEGER', 'BROKING',
     'Default validity of a quotation in days from its creation (BRNB.043)', 1, 365, now(), 'SYSTEM'),
    ('QUOTATION_EXPIRING_DAYS', '7', 'INTEGER', 'BROKING',
     'Quotations whose validity ends within this many days are listed as expiring', 1, 90, now(), 'SYSTEM');

-- BRNB.106: accounts whose placement was cancelled are retention candidates too (the account
-- module now reports record type ACCOUNT through RetentionCandidateProvider).
update nba_retention_rule
   set statuses = 'VOIDED,CANCELLED,PLACEMENT_CANCELLED',
       description = 'Accounts voided, cancelled after issuance or with the placement cancelled'
 where record_type = 'ACCOUNT' and statuses = 'VOIDED,CANCELLED';
