-- =====================================================================================
-- iNXT BrokerVerse - V840 Non-package proposals: Proposal Request Form (PRF), TSU queue,
-- Quotation Slip, insurer responses, comparative table and Proposal Slip.
--   BRNB.005 PRF with risk details, attachments (mandatory-document checklist per product) and
--            requested insurers        BRNB.006 marketing reference PRF-<yyyy>, gap-free per year
--   BRNB.007 TSU queue: accept, return with reason, update, delete (void) in process only
--   BRNB.008 Quotation Slip QS-<yyyy> from template, insurer selection, approval, send log
--   BRNB.009 insurer responses per insurer, editable by TSU, with version history
--   BRNB.010 comparative table with recommended insurer (PDF / XLSX)
--   BRNB.013 protected documents     BRNB.014 approval before sending
--   BRNB.017 Proposal Slip PS-<yyyy> from the chosen insurer's terms, approval, release, archive
--   BRNB.098 TSU routing (catalog rules) BRNB.102 ARN at PRF creation     BRD 2.2
-- The status mirrors the NB_PROPOSAL work case (V751). Marketing approval is one stage (the
-- BRD's TL -> TH -> UH chain waits for Q05; the approver permission is configurable).
-- =====================================================================================
create table npk_proposal (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    prf_no            varchar(30)    not null,
    arn               varchar(30)    not null,
    client_id         bigint         not null references crm_client (id),
    client_code       varchar(30)    not null,
    client_name       varchar(250)   not null,
    client_email      varchar(120),
    product_code      varchar(20)    not null references cat_product (code),
    line_code         varchar(30)    not null,
    market_segment    varchar(40),
    source_channel    varchar(40),
    period_from       date,
    period_to         date,
    currency          varchar(3)     not null default 'PHP',
    -- Risk details as JSON: free-form sections (heading, text) and risk items with risk group.
    risk_details      text           not null,
    total_sum_insured numeric(19, 2) not null default 0,
    tsu_rule          varchar(30),
    tsu_reason        varchar(300),
    status            varchar(30)    not null,
    submitted_by      varchar(50),
    submitted_at      timestamptz,
    approved_by       varchar(50),
    approved_at       timestamptz,
    qs_no             varchar(30),
    qs_template       varchar(60),
    qs_reply_by       date,
    qs_submitted_by   varchar(50),
    qs_approved_by    varchar(50),
    qs_sent_at        timestamptz,
    terms_closed      boolean        not null default false,
    chosen_insurer    varchar(30),
    ps_no             varchar(30),
    ps_version        integer        not null default 0,
    ps_submitted_by   varchar(50),
    ps_approved_by    varchar(50),
    sent_at           timestamptz,
    accepted_at       timestamptz,
    accepted_groups   varchar(200),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_npk_proposal_prf unique (prf_no),
    constraint uq_npk_proposal_arn unique (arn),
    constraint ck_npk_status check (status in ('DRAFT', 'FOR_MKT_APPROVAL', 'WITH_TSU',
        'QS_PREPARATION', 'QS_FOR_APPROVAL', 'QS_SENT', 'TERMS_RECEIVED', 'PS_FOR_APPROVAL',
        'PS_RELEASED', 'SENT_TO_CLIENT', 'ACCEPTED', 'CONVERTED', 'NOT_PROCEEDED', 'VOIDED')),
    constraint ck_npk_period check (period_to is null or period_from is null or period_to > period_from)
);
create index ix_npk_proposal_company on npk_proposal (company_id, status);
create index ix_npk_proposal_client on npk_proposal (client_id);
create index ix_npk_proposal_creator on npk_proposal (company_id, lower(created_by), status);

-- Insurers requested by Marketing and selected by TSU for the Quotation Slip (BRNB.005/008).
create table npk_proposal_insurer (
    proposal_id   bigint      not null references npk_proposal (id),
    insurer_index integer     not null,
    insurer_code  varchar(30) not null,
    primary key (proposal_id, insurer_index)
);

-- Accounts created from the PRF (one per accepted risk group).
create table npk_proposal_account (
    proposal_id   bigint      not null references npk_proposal (id),
    account_index integer     not null,
    arn           varchar(30) not null,
    primary key (proposal_id, account_index)
);

-- BRNB.009: one response per insurer approached; each change is kept in the history table.
create table npk_insurer_response (
    id           bigint generated by default as identity primary key,
    version      bigint         not null default 0,
    proposal_id  bigint         not null references npk_proposal (id),
    insurer_code varchar(30)    not null,
    insurer_name varchar(200)   not null,
    status       varchar(20)    not null,
    revision     integer        not null default 0,
    premium      numeric(19, 2),
    rate         numeric(19, 8),
    deductibles  varchar(1000),
    conditions   varchar(2000),
    valid_until  date,
    remarks      varchar(1000),
    document_id  bigint,
    recommended  boolean        not null default false,
    responded_at timestamptz,
    created_at   timestamptz    not null,
    created_by   varchar(50)    not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_npk_response unique (proposal_id, insurer_code),
    constraint ck_npk_response_status check (status in ('PENDING', 'RECEIVED', 'DECLINED')),
    constraint ck_npk_response_premium check (premium is null or premium >= 0)
);

create table npk_insurer_response_history (
    id          bigint generated by default as identity primary key,
    response_id bigint         not null references npk_insurer_response (id),
    revision    integer        not null,
    status      varchar(20)    not null,
    premium     numeric(19, 2),
    rate        numeric(19, 8),
    deductibles varchar(1000),
    conditions  varchar(2000),
    valid_until date,
    remarks     varchar(1000),
    document_id bigint,
    recommended boolean        not null,
    changed_by  varchar(50)    not null,
    changed_at  timestamptz    not null
);
create index ix_npk_response_history on npk_insurer_response_history (response_id, revision);

-- Document types of the non-package flow (list DOCUMENT_TYPE, V750).
insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select 'DOCUMENT_TYPE', v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values ('QUOTATION_SLIP', 'Quotation slip', 51),
             ('INSURER_RESPONSE', 'Insurer response / terms', 52),
             ('COMPARATIVE_TABLE', 'Comparative table', 53),
             ('PROPOSAL_SLIP', 'Proposal slip', 54)) as v(code, label, sort_order);

-- Numbering prefixes (UX-1 / Q15 open) and the default reply time of a quotation slip.
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('PROPOSAL_NUMBER_PREFIX', 'PRF', 'STRING', 'BROKING',
     'Prefix of the PRF marketing reference (<prefix>-<yyyy>-nnnnnn), BRNB.006 (UX-1)', null, null, now(), 'SYSTEM'),
    ('QUOTATION_SLIP_PREFIX', 'QS', 'STRING', 'BROKING',
     'Prefix of quotation slip numbers (<prefix>-<yyyy>-nnnnnn), BRNB.008', null, null, now(), 'SYSTEM'),
    ('PROPOSAL_SLIP_PREFIX', 'PS', 'STRING', 'BROKING',
     'Prefix of proposal slip numbers (<prefix>-<yyyy>-nnnnnn), BRNB.017', null, null, now(), 'SYSTEM'),
    ('QUOTATION_SLIP_REPLY_DAYS', '5', 'INTEGER', 'BROKING',
     'Days given to insurers to reply to a quotation slip (BRNB.008)', 1, 60, now(), 'SYSTEM');
