-- =====================================================================================
-- iNXT BrokerVerse - V850 Placement: payment gate, CLPC billing and payment matching,
-- placement slips, hold cover and insurer returns (docs/architecture/BROKING_ARCHITECTURE.md,
-- placement module).
--   BRD 2.3.1 / BRNB.068 / BRNB.114  payment gate per segment (paid, client confirmation,
--                                    direct payment skips the gate)
--   BRNB.067  CLPC billing file (xlsx / ods) and payment report matching (PN / loan app no.)
--   BRNB.068  payment report matching on the ARN for the other segments
--   BRNB.069  placement slip PL-<yyyy> per insurer, versions kept for returns
--   BRNB.071  e-mail to the insurer (send log in msg_outbound)
--   BRNB.072 / BRNB.103  hold cover request, insurer confirmation, expiry monitor
--   BRNB.033 / 034 / 058 / 059  insurer returns and the return loop
--   BRNB.062 / BRD 2.1.16  cancel and reactivate placement
-- Account state changes go through account.service.AccountLifecycleService only; the tables
-- below hold the placement records and the evidence behind each gate decision. Placement never
-- records receipts or cash: the future Operations Cashiering module supplies confirmed receipt
-- applications through placement.service.PaymentConfirmationSource.
-- =====================================================================================

-- Payment gate rule per market segment and product line (BRD 2.3.1); the first active rule by
-- priority whose segment and line match (blank = any) applies. Direct-payment accounts skip the
-- gate (BRNB.114).
create table plc_payment_gate_rule (
    id             bigint generated by default as identity primary key,
    version        bigint       not null default 0,
    market_segment varchar(40),
    line_code      varchar(30)  references cat_product_line (code),
    gate_rule      varchar(30)  not null,
    priority       integer      not null,
    description    varchar(200) not null,
    active         boolean      not null default true,
    created_at     timestamptz  not null,
    created_by     varchar(50)  not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_plc_gate_rule check (gate_rule in ('PAYMENT_MATCHED', 'CLIENT_CONFIRMATION'))
);
create index ix_plc_gate_rule_priority on plc_payment_gate_rule (active, priority);

insert into plc_payment_gate_rule (market_segment, line_code, gate_rule, priority, description,
                                   created_at, created_by)
values ('CBG', 'PROPERTY', 'PAYMENT_MATCHED', 10,
        'CBG Fire: the premium must be matched as paid (CLPC billing or payment report)', now(), 'SYSTEM'),
       ('CBG', 'MOTOR', 'PAYMENT_MATCHED', 20,
        'CBG Motor: the premium must be matched as paid (payment report)', now(), 'SYSTEM'),
       (null, null, 'CLIENT_CONFIRMATION', 90,
        'Other lines: the client''s confirmation is recorded (document or confirmation with user and date)',
        now(), 'SYSTEM');

-- Evidence behind each payment gate decision: matched payment, recorded client confirmation or
-- direct payment. One row per source reference and account.
create table plc_payment_evidence (
    id             bigint generated by default as identity primary key,
    version        bigint         not null default 0,
    company_id     bigint         not null references org_company (id),
    account_id     bigint         not null references acc_account (id),
    arn            varchar(30)    not null,
    kind           varchar(30)    not null,
    source         varchar(30)    not null,
    reference      varchar(80)    not null,
    amount         numeric(19, 2),
    paid_on        date,
    channel        varchar(40),
    remarks        varchar(500),
    attachment_id  bigint,
    gate_opened    boolean        not null default false,
    created_at     timestamptz    not null,
    created_by     varchar(50)    not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_plc_evidence unique (arn, source, reference),
    constraint ck_plc_evidence_kind check (kind in ('PAYMENT', 'CLIENT_CONFIRMATION', 'DIRECT_PAYMENT'))
);
create index ix_plc_evidence_account on plc_payment_evidence (account_id);

-- CLPC billing batches (BRNB.067): CBG Fire accounts awaiting payment. Transport to CLPC is
-- parked (Q28): the file is downloaded and the payment report uploaded.
create table plc_billing_batch (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    company_id    bigint         not null references org_company (id),
    batch_no      varchar(30)    not null unique,
    billing_date  date           not null,
    status        varchar(20)    not null,
    item_count    integer        not null,
    total_premium numeric(19, 2) not null,
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_plc_batch_status check (status in ('GENERATED', 'REPORT_RECEIVED', 'CLOSED'))
);
create index ix_plc_batch_company on plc_billing_batch (company_id, billing_date);

create table plc_billing_item (
    id                  bigint generated by default as identity primary key,
    batch_id            bigint         not null references plc_billing_batch (id),
    line_no             integer        not null,
    account_id          bigint         not null references acc_account (id),
    arn                 varchar(30)    not null,
    pn_numbers          varchar(300),
    loan_application_no varchar(40),
    booking_date        date,
    borrower            varchar(250)   not null,
    originating_unit    varchar(40),
    premium             numeric(19, 2) not null,
    bdoi_location       varchar(40),
    amortised           boolean        not null,
    payment_status      varchar(20)    not null,
    constraint uq_plc_billing_item unique (batch_id, line_no),
    constraint ck_plc_item_status check (payment_status in ('BILLED', 'PAID', 'UNPAID'))
);
create index ix_plc_billing_item_account on plc_billing_item (account_id);

-- Payment reports (CLPC by PN / loan application no., other segments by ARN) and their match.
create table plc_payment_report (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    company_id   bigint        not null references org_company (id),
    report_no    varchar(30)   not null unique,
    kind         varchar(20)   not null,
    batch_id     bigint        references plc_billing_batch (id),
    file_name    varchar(255)  not null,
    status       varchar(20)   not null,
    confirmed_by varchar(50),
    confirmed_at timestamptz,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_plc_report_kind check (kind in ('CLPC', 'REFERENCE')),
    constraint ck_plc_report_status check (status in ('REVIEW', 'CONFIRMED', 'DISCARDED'))
);
create index ix_plc_report_company on plc_payment_report (company_id, created_at);

create table plc_payment_report_line (
    id               bigint generated by default as identity primary key,
    report_id        bigint         not null references plc_payment_report (id),
    row_no           integer        not null,
    reference        varchar(80)    not null,
    paid             boolean        not null,
    amount           numeric(19, 2),
    paid_on          date,
    match_status     varchar(20)    not null,
    account_id       bigint         references acc_account (id),
    arn              varchar(30),
    candidates       varchar(500),
    message          varchar(300),
    manually_matched boolean        not null default false,
    applied          boolean        not null default false,
    apply_message    varchar(300),
    constraint uq_plc_report_line unique (report_id, row_no),
    constraint ck_plc_line_status check (match_status in ('MATCHED', 'UNPAID', 'UNMATCHED', 'AMBIGUOUS'))
);
create index ix_plc_report_line_arn on plc_payment_report_line (arn);

-- Placement slips PL-<yyyy> per insurer and branch (BRNB.069). A regenerated slip keeps its
-- number with a new version; the old version is kept as SUPERSEDED.
create table plc_slip (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    slip_no          varchar(30)   not null,
    version_no       integer       not null,
    insurer_code     varchar(30)   not null,
    branch_code      varchar(20)   not null,
    status           varchar(20)   not null,
    template_version varchar(60)   not null,
    recipients       varchar(1000),
    sent_at          timestamptz,
    send_count       integer       not null default 0,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint uq_plc_slip unique (slip_no, version_no),
    constraint ck_plc_slip_status check (status in ('GENERATED', 'SENT', 'SUPERSEDED'))
);
create index ix_plc_slip_company on plc_slip (company_id, created_at);

create table plc_slip_account (
    slip_id    bigint      not null references plc_slip (id),
    line_index integer     not null,
    account_id bigint      not null references acc_account (id),
    arn        varchar(30) not null,
    primary key (slip_id, line_index)
);
create index ix_plc_slip_account_arn on plc_slip_account (arn);

create table plc_slip_file (
    id        bigint generated by default as identity primary key,
    slip_id   bigint       not null references plc_slip (id),
    format    varchar(10)  not null,
    file_name varchar(255) not null,
    sha256    varchar(64)  not null,
    content   bytea        not null,
    constraint uq_plc_slip_file unique (slip_id, format),
    constraint ck_plc_slip_file_format check (format in ('PDF', 'XLSX'))
);

-- Hold cover (BRNB.072/103): request, insurer confirmation, expiry.
create table plc_hold_cover (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    company_id   bigint       not null references org_company (id),
    account_id   bigint       not null references acc_account (id),
    arn          varchar(30)  not null,
    insurer_code varchar(30)  not null,
    status       varchar(20)  not null,
    start_date   date         not null,
    expiry_date  date         not null,
    insurer_ref  varchar(60),
    confirmed_on date,
    alerted_on   date,
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_plc_hold_cover_status check (status in ('REQUESTED', 'CONFIRMED', 'DECLINED', 'EXPIRED')),
    constraint ck_plc_hold_cover_dates check (expiry_date >= start_date)
);
create index ix_plc_hold_cover_account on plc_hold_cover (account_id);
create index ix_plc_hold_cover_expiry on plc_hold_cover (status, expiry_date);

-- Insurer returns (BRNB.034/059) and how each was resolved (return queue).
create table plc_insurer_return (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    company_id   bigint        not null references org_company (id),
    account_id   bigint        not null references acc_account (id),
    arn          varchar(30)   not null,
    insurer_code varchar(30),
    slip_no      varchar(30),
    reason_code  varchar(40)   not null,
    remarks      varchar(1000),
    resolution   varchar(30),
    resolved_at  timestamptz,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);
create index ix_plc_return_account on plc_insurer_return (account_id, resolved_at);

-- ---------- Parameters, lists of values, document types -------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('HOLD_COVER_DAYS', '30', 'INTEGER', 'PLACEMENT',
     'Days of hold cover requested from the insurer while the placement completes (BRNB.072)', 1, 90,
     now(), 'SYSTEM'),
    ('HOLD_COVER_ALERT_DAYS', '5', 'INTEGER', 'PLACEMENT',
     'Days before a hold cover expires when Processing is alerted (HOLD_COVER_EXPIRY job, BRNB.103)',
     0, 30, now(), 'SYSTEM');

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('CLIENT_CONFIRMATION_CHANNEL', 'Client confirmation channel',
        'How the client confirmed the placement of an Other Lines account (payment gate, BRD 2.3.1)',
        true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('CLIENT_CONFIRMATION_CHANNEL', 'EMAIL', 'E-mail from the client', 10),
    ('CLIENT_CONFIRMATION_CHANNEL', 'SIGNED_FORM', 'Signed confirmation form', 20),
    ('CLIENT_CONFIRMATION_CHANNEL', 'RECORDED_CALL', 'Recorded call', 30),
    ('CLIENT_CONFIRMATION_CHANNEL', 'OTHERS', 'Others (see remarks)', 90),
    ('DOCUMENT_TYPE', 'PAYMENT_CONFIRMATION', 'Payment / client confirmation', 72),
    ('DOCUMENT_TYPE', 'HOLD_COVER', 'Hold cover confirmation', 74),
    ('RETURN_REASON', 'INSURER_UNDERWRITING', 'Insurer underwriting review', 45)
) as v(type_code, code, label, sort_order);
