-- =====================================================================================
-- iNXT BrokerVerse - V860 Issuance: e-policy receipt and extraction review, document trigger
-- rules, Insurance Advice and encrypted e-policy dispatch
-- (docs/architecture/BROKING_ARCHITECTURE.md, issuance module).
--   BRNB.073  e-policy (PDF) received and matched to the account by ARN or policy number, single
--             or bulk upload with a match review (mailbox / SFTP reading parked, Q31)
--   BRNB.074 / BRNB.104  policy data extraction (PDF text with patterns per insurer; OCR parked,
--             Q24), review against the account, policy number update after confirmation
--   BRNB.105  document-type trigger rules (EPOLICY uploaded -> extraction review)
--   BRNB.060 / 070 / 095  Insurance Advice IA-<yyyy> for mortgaged accounts, trigger parameter,
--             register, protected sending
--   BRNB.035 / BRNB.077  e-policy sent to the client encrypted, password in a separate e-mail;
--             the dispatch report reads the messaging log (purpose EPOLICY)
-- The policy number reaches the account through account.service.AccountLifecycleService.
-- =====================================================================================

-- Extraction patterns per insurer and field (BRNB.104). A blank insurer is the default used when
-- the insurer has no pattern for the field. The first capture group is the value.
create table iss_extraction_pattern (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    insurer_code varchar(30),
    field        varchar(20)   not null,
    pattern      varchar(500)  not null,
    date_format  varchar(40),
    priority     integer       not null default 10,
    active       boolean       not null default true,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_iss_pattern_field check (field in ('POLICY_NUMBER', 'PERIOD_FROM', 'PERIOD_TO', 'PREMIUM'))
);
create index ix_iss_pattern_insurer on iss_extraction_pattern (insurer_code, field, priority);

insert into iss_extraction_pattern (insurer_code, field, pattern, date_format, priority, created_at, created_by)
values (null, 'POLICY_NUMBER', '(?i)policy\s*(?:no\.?|number|#)\s*[:#]?\s*([A-Z0-9][A-Z0-9/-]{3,39})', null, 10, now(), 'SYSTEM'),
       (null, 'PERIOD_FROM', '(?i)period\s+of\s+insurance\s*:?\s*(?:from\s+)?(\d{4}-\d{2}-\d{2}|\d{2}/\d{2}/\d{4})', 'MM/dd/yyyy', 10, now(), 'SYSTEM'),
       (null, 'PERIOD_TO', '(?i)period\s+of\s+insurance\s*:?\s*(?:from\s+)?(?:\d{4}-\d{2}-\d{2}|\d{2}/\d{2}/\d{4})\s*(?:to|-)\s*(\d{4}-\d{2}-\d{2}|\d{2}/\d{2}/\d{4})', 'MM/dd/yyyy', 10, now(), 'SYSTEM'),
       (null, 'PREMIUM', '(?i)(?:total|gross)\s+premium\s*:?\s*(?:PHP|P)?\s*([0-9][0-9,]*\.[0-9]{2})', null, 10, now(), 'SYSTEM');

-- Document triggers (BRNB.105): an uploaded document type starts a business action.
create table iss_document_trigger (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    document_type varchar(40)   not null,
    action        varchar(30)   not null,
    description   varchar(200)  not null,
    active        boolean       not null default true,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_iss_trigger unique (document_type, action),
    constraint ck_iss_trigger_action check (action in ('EXTRACTION_REVIEW'))
);

insert into iss_document_trigger (document_type, action, description, created_at, created_by)
values ('EPOLICY', 'EXTRACTION_REVIEW',
        'E-policy uploaded: extract the policy data and open an extraction review task (policy number update)',
        now(), 'SYSTEM');

-- E-policies received (BRNB.073) with the extracted data, the review and the dispatch.
create table iss_epolicy (
    id                       bigint generated by default as identity primary key,
    version                  bigint         not null default 0,
    company_id               bigint         not null references org_company (id),
    account_id               bigint         not null references acc_account (id),
    arn                      varchar(30)    not null,
    attachment_id            bigint         not null references doc_attachment (id),
    file_name                varchar(255)   not null,
    match_method             varchar(20)    not null,
    status                   varchar(20)    not null,
    extracted_policy_numbers varchar(500),
    extracted_period_from    date,
    extracted_period_to      date,
    extracted_premium        numeric(19, 2),
    extraction_note          varchar(500),
    policy_numbers           varchar(500),
    issue_date               date,
    reviewed_by              varchar(50),
    reviewed_at              timestamptz,
    reject_reason            varchar(40),
    dispatch_count           integer        not null default 0,
    dispatched_at            timestamptz,
    dispatched_to            varchar(500),
    created_at               timestamptz    not null,
    created_by               varchar(50)    not null,
    updated_at               timestamptz,
    updated_by               varchar(50),
    constraint ck_iss_epolicy_status check (status in ('RECEIVED', 'REVIEW', 'CONFIRMED', 'REJECTED')),
    constraint ck_iss_epolicy_match check (match_method in ('MANUAL', 'POLICY_NUMBER', 'FILE_NAME', 'CONTENT'))
);
create index ix_iss_epolicy_account on iss_epolicy (account_id);
create index ix_iss_epolicy_status on iss_epolicy (company_id, status);

-- Bulk e-policy upload with match review (BRNB.073): files are held until confirmed.
create table iss_upload_batch (
    id         bigint generated by default as identity primary key,
    version    bigint       not null default 0,
    company_id bigint       not null references org_company (id),
    status     varchar(20)  not null,
    file_count integer      not null,
    created_at timestamptz  not null,
    created_by varchar(50)  not null,
    updated_at timestamptz,
    updated_by varchar(50),
    constraint ck_iss_upload_status check (status in ('REVIEW', 'CONFIRMED', 'DISCARDED'))
);

create table iss_upload_item (
    id           bigint generated by default as identity primary key,
    batch_id     bigint        not null references iss_upload_batch (id),
    line_no      integer       not null,
    file_name    varchar(255)  not null,
    sha256       varchar(64)   not null,
    content      bytea         not null,
    arn          varchar(30),
    match_method varchar(20),
    message      varchar(300),
    included     boolean       not null default true,
    epolicy_id   bigint        references iss_epolicy (id),
    outcome      varchar(300),
    constraint uq_iss_upload_item unique (batch_id, line_no)
);

-- Insurance Advice IA-<yyyy> for mortgaged accounts (BRNB.060/070/095).
create table iss_insurance_advice (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    company_id       bigint        not null references org_company (id),
    ia_no            varchar(30)   not null unique,
    account_id       bigint        not null references acc_account (id),
    arn              varchar(30)   not null,
    client_id        bigint        not null,
    client_name      varchar(250)  not null,
    mortgagee_bank   varchar(40)   not null,
    insurer_code     varchar(30),
    policy_numbers   varchar(500),
    trigger_event    varchar(20)   not null,
    template_version varchar(60)   not null,
    status           varchar(20)   not null,
    file_name        varchar(255)  not null,
    sha256           varchar(64)   not null,
    content          bytea         not null,
    send_count       integer       not null default 0,
    last_sent_at     timestamptz,
    last_sent_to     varchar(500),
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_iss_ia_status check (status in ('GENERATED', 'SENT')),
    constraint ck_iss_ia_trigger check (trigger_event in ('MANUAL', 'ON_PLACEMENT', 'ON_POLICY_ISSUE'))
);
create index ix_iss_ia_account on iss_insurance_advice (account_id);
create index ix_iss_ia_client on iss_insurance_advice (client_id);
create index ix_iss_ia_company on iss_insurance_advice (company_id, created_at);

-- ---------- Parameters and lists of values -------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('IA_TRIGGER', 'ON_POLICY_ISSUE', 'STRING', 'ISSUANCE',
     'When the Insurance Advice of a mortgaged account is generated automatically: ON_POLICY_ISSUE, ON_PLACEMENT or MANUAL (BRNB.095, Q30)',
     null, null, now(), 'SYSTEM'),
    ('EPOLICY_PASSWORD_HINT', 'The password follows the BDOI standard; it is sent to you in a separate e-mail.',
     'STRING', 'ISSUANCE',
     'Text telling the client how the e-policy password is built (BRNB.077; the BDOI convention is parked, Q07)',
     null, null, now(), 'SYSTEM');

insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('EPOLICY_REJECT_REASON', 'E-policy rejection reason',
        'Why a received e-policy is rejected at extraction review (BRNB.104)', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(), now(), 'SYSTEM'
from (values
    ('EPOLICY_REJECT_REASON', 'WRONG_ACCOUNT', 'Belongs to another account', 10),
    ('EPOLICY_REJECT_REASON', 'WRONG_DOCUMENT', 'Not the issued policy', 20),
    ('EPOLICY_REJECT_REASON', 'DETAILS_MISMATCH', 'Details differ from the placement (insurer to correct)', 30),
    ('EPOLICY_REJECT_REASON', 'UNREADABLE', 'Unreadable or damaged file', 40),
    ('EPOLICY_REJECT_REASON', 'OTHERS', 'Others (see remarks)', 90),
    ('DOCUMENT_TYPE', 'INSURANCE_ADVICE', 'Insurance Advice', 76)
) as v(type_code, code, label, sort_order);
