-- =====================================================================================
-- iNXT BrokerVerse - V862 Policy Issuance: automatic sending of the Insurance Advice to the
-- recipient enrolled for its mortgagee bank (FR-NB-107; BRNB.060).
--   iss_advice_recipient   per mortgagee bank, and where needed per market segment, the
--                          recipient addresses (To / Cc) and the enrolment for automatic
--                          sending; effective-dated, maker-checker
--   iss_insurance_advice   send_mode (MANUAL or AUTOMATIC) of the last sending and the reason
--                          an automatic sending could not be made
-- =====================================================================================
create table iss_advice_recipient (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    company_id      bigint        not null references org_company (id),
    mortgagee_bank  varchar(40)   not null,
    market_segment  varchar(30),
    to_addresses    varchar(1000),
    cc_addresses    varchar(1000),
    auto_send       boolean       not null default false,
    effective_from  date          not null,
    effective_to    date,
    record_status   varchar(30)   not null,
    authorized_by   varchar(50),
    authorized_at   timestamptz,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_iss_advice_recipient_dates
        check (effective_to is null or effective_to >= effective_from)
);
create index ix_iss_advice_recipient on iss_advice_recipient (company_id, mortgagee_bank);

alter table iss_insurance_advice add column send_mode varchar(10)
    constraint ck_iss_ia_send_mode check (send_mode in ('MANUAL', 'AUTOMATIC'));
alter table iss_insurance_advice add column auto_send_failure varchar(300);
