-- =====================================================================================
-- iNXT BrokerVerse - V870 Booking: booked invoices, broker accounting, service invoices,
-- endorsements and cancellations (BRD-1 New Business, BRD 2.4).
--   BRNB.027/061 booking with GL entry and service invoice, atomic (rolls back as a whole)
--   BRNB.036     individual and batch booking, booking queue, end-of-day batch job
--   BRNB.038/111 direct booking (account reached POLICY_ISSUED through direct_booking)
--   BRNB.076     auto-book rules, idempotent booking key (ARN + transaction no.), endorsements
--   BRNB.081/094 negative endorsements and post-issuance cancellation
--   BRNB.097     New Business vs Renewal classification on the invoice
--   BRNB.100/100b service invoice types, triggers, owners, BIR numbering, dispatch
--   BRNB.107     incentive eligibility rules (content parked, Q33)
--   BRNB.108     cost center mandatory on every booked invoice
--   BRNB.112     multi-year: one invoice per policy year, commission recognised per year
-- The booked invoice is the upstream of the Operations invoice ledger (OPERATIONS_DESIGN 2.2).
-- ARN, client, insurer and account are stored as plain values (no foreign keys to other
-- broking modules' tables, which Operations copies by value too).
-- =====================================================================================

-- ---------- Booked invoices -----------------------------------------------------------
create table bkg_invoice (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    branch_id          bigint         not null references org_branch (id),
    invoice_no         varchar(40),
    arn                varchar(30)    not null,
    account_id         bigint         not null,
    transaction_no     varchar(40)    not null,
    kind               varchar(20)    not null,
    status             varchar(20)    not null,
    endorsement_no     varchar(40),
    parent_invoice_no  varchar(40),
    policy_year        integer        not null default 1,
    policy_no          varchar(60),
    client_id          bigint         not null,
    client_code        varchar(30)    not null,
    client_name        varchar(250)   not null,
    insurer_code       varchar(30)    not null,
    risk_code          varchar(20)    not null,
    line_code          varchar(30)    not null,
    market_segment     varchar(40),
    source_channel     varchar(40),
    account_officer    varchar(50),
    sales_unit         varchar(20),
    department         varchar(20),
    cost_center        varchar(20)    not null,
    currency           varchar(3)     not null,
    booking_date       date,
    inception_date     date           not null,
    expiry_date        date           not null,
    basic_premium      numeric(19, 2) not null default 0,
    dst                numeric(19, 2) not null default 0,
    premium_tax_vat    numeric(19, 2) not null default 0,
    lgt                numeric(19, 2) not null default 0,
    fst                numeric(19, 2) not null default 0,
    other_charges      numeric(19, 2) not null default 0,
    commission_rate    numeric(19, 8) not null default 0,
    commission         numeric(19, 2) not null default 0,
    vat_on_commission  numeric(19, 2) not null default 0,
    wtax_rate          numeric(19, 8) not null default 0,
    wtax_amount        numeric(19, 2) not null default 0,
    direct_payment     boolean        not null default false,
    cwt2_percent       boolean        not null default false,
    incentive_eligible boolean        not null default false,
    business_type      varchar(20)    not null default 'NEW_BUSINESS',
    booking_source     varchar(20)    not null,
    service_invoice_no varchar(40),
    booked_by          varchar(50),
    booked_at          timestamptz,
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    -- BRNB.076: a transaction of an account is booked once (idempotent booking key).
    constraint uq_bkg_invoice_key unique (arn, transaction_no),
    constraint uq_bkg_invoice_no unique (invoice_no),
    constraint ck_bkg_invoice_kind check (kind in ('BOOKING', 'ENDORSEMENT_PLUS', 'ENDORSEMENT_MINUS', 'CANCELLATION')),
    constraint ck_bkg_invoice_status check (status in ('SCHEDULED', 'BOOKED', 'CANCELLED')),
    constraint ck_bkg_invoice_booked check (status <> 'BOOKED' or (invoice_no is not null and booking_date is not null)),
    constraint ck_bkg_business_type check (business_type in ('NEW_BUSINESS', 'RENEWAL')),
    constraint ck_bkg_booking_source check (booking_source in ('INDIVIDUAL', 'BATCH', 'SCHEDULED', 'UPLOAD', 'ENDORSEMENT')),
    constraint ck_bkg_period check (expiry_date > inception_date)
);
create index ix_bkg_invoice_company on bkg_invoice (company_id, status, booking_date);
create index ix_bkg_invoice_arn on bkg_invoice (arn);
create index ix_bkg_invoice_client on bkg_invoice (client_id);
create index ix_bkg_invoice_insurer on bkg_invoice (company_id, insurer_code);

-- Insurer shares of an invoice (co-insurance; one insurer at 100 % otherwise).
create table bkg_invoice_share (
    invoice_id   bigint         not null references bkg_invoice (id),
    share_index  integer        not null,
    insurer_code varchar(30)    not null,
    share_pct    numeric(9, 4)  not null check (share_pct > 0 and share_pct <= 100),
    primary key (invoice_id, share_index)
);

-- Journal batches posted for an invoice (one per insurer share).
create table bkg_invoice_journal (
    invoice_id    bigint      not null references bkg_invoice (id),
    journal_index integer     not null,
    batch_no      varchar(40) not null,
    primary key (invoice_id, journal_index)
);

-- Open items recorded for an invoice: client PR, insurer DTIP, insurer commission receivable.
create table bkg_invoice_open_item (
    invoice_id   bigint      not null references bkg_invoice (id),
    item_index   integer     not null,
    open_item_id bigint      not null references sl_open_item (id),
    role         varchar(30) not null
        check (role in ('CLIENT_PREMIUM', 'INSURER_DTIP', 'INSURER_COMMISSION')),
    primary key (invoice_id, item_index)
);

-- ---------- Endorsements and cancellations (BRNB.076/081/094) -------------------------
create table bkg_endorsement (
    id                 bigint generated by default as identity primary key,
    version            bigint         not null default 0,
    company_id         bigint         not null references org_company (id),
    endorsement_no     varchar(40)    not null unique,
    arn                varchar(30)    not null,
    account_id         bigint         not null,
    endorsement_type   varchar(20)    not null
        check (endorsement_type in ('POSITIVE', 'NEGATIVE', 'NON_FINANCIAL', 'CANCELLATION')),
    cancellation_kind  varchar(20)
        check (cancellation_kind is null or cancellation_kind in ('FLAT', 'FLAT_RETAIN_DST', 'PARTIAL')),
    period_basis       varchar(20),
    effective_date     date           not null,
    policy_year        integer        not null default 1,
    sum_insured_change numeric(19, 2),
    rate_percent       numeric(19, 8),
    description        varchar(1000)  not null,
    reason_code        varchar(40),
    invoice_no         varchar(40),
    source_reference   varchar(80),
    created_at         timestamptz    not null,
    created_by         varchar(50)    not null,
    updated_at         timestamptz,
    updated_by         varchar(50),
    constraint ck_bkg_endt_cancel check ((endorsement_type = 'CANCELLATION') = (cancellation_kind is not null))
);
create index ix_bkg_endorsement_arn on bkg_endorsement (arn);
create unique index uq_bkg_endorsement_source on bkg_endorsement (company_id, source_reference)
    where source_reference is not null;

-- ---------- Booking queue and batch runs (BRNB.036) -----------------------------------
create table bkg_queue (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    arn           varchar(30)   not null,
    account_id    bigint        not null,
    status        varchar(20)   not null check (status in ('QUEUED', 'BOOKED', 'FAILED', 'REMOVED')),
    source        varchar(20)   not null check (source in ('MANUAL', 'AUTO', 'PLACEMENT', 'UPLOAD')),
    booking_date  date,
    cost_center   varchar(20),
    queued_by     varchar(50)   not null,
    queued_at     timestamptz   not null,
    last_error    varchar(1000),
    invoice_no    varchar(40),
    batch_run_no  varchar(40),
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create unique index uq_bkg_queue_active on bkg_queue (arn) where status = 'QUEUED';
create index ix_bkg_queue_company on bkg_queue (company_id, status);

create table bkg_batch_run (
    id            bigint generated by default as identity primary key,
    version       bigint       not null default 0,
    company_id    bigint       not null references org_company (id),
    run_no        varchar(40)  not null unique,
    trigger_type  varchar(20)  not null check (trigger_type in ('MANUAL', 'SCHEDULED', 'BOOK_NOW', 'UPLOAD')),
    business_date date         not null,
    started_by    varchar(50)  not null,
    started_at    timestamptz  not null,
    finished_at   timestamptz,
    booked_count  integer      not null default 0,
    failed_count  integer      not null default 0,
    created_at    timestamptz  not null,
    created_by    varchar(50)  not null,
    updated_at    timestamptz,
    updated_by    varchar(50)
);
create index ix_bkg_batch_run_company on bkg_batch_run (company_id, started_at);

create table bkg_batch_row (
    run_id     bigint        not null references bkg_batch_run (id),
    row_index  integer       not null,
    arn        varchar(30)   not null,
    outcome    varchar(10)   not null check (outcome in ('BOOKED', 'FAILED')),
    invoice_no varchar(40),
    message    varchar(1000),
    primary key (run_id, row_index)
);

-- ---------- Rules ----------------------------------------------------------------------
-- BRNB.076 auto-book rules: a matching account entering POLICY_ISSUED is queued for the next
-- batch; blank product / segment = any.
create table bkg_auto_book_rule (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    product_code   varchar(20),
    market_segment varchar(40),
    enabled        boolean       not null default true,
    description    varchar(300)  not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50)
);

-- BRNB.107 incentive eligibility rules (product, segment, channel, period). Seeded empty:
-- the qualification rules are parked (Q33).
create table bkg_incentive_rule (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    product_code   varchar(20),
    market_segment varchar(40),
    source_channel varchar(40),
    period_from    date          not null,
    period_to      date,
    active         boolean       not null default true,
    description    varchar(300)  not null,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint ck_bkg_incentive_period check (period_to is null or period_to >= period_from)
);

-- ---------- Service invoices (BRNB.100 / 100b) -------------------------------------------
create table bkg_si_type (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    code             varchar(40)   not null unique,
    name             varchar(120)  not null,
    recipient        varchar(20)   not null check (recipient in ('INSURER', 'INTERNAL')),
    trigger_type     varchar(20)   not null check (trigger_type in ('ON_BOOKING', 'ON_ENDORSEMENT', 'MANUAL')),
    owner_permission varchar(60),
    owner_username   varchar(50),
    template_code    varchar(40)   not null,
    active           boolean       not null default true,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);

create table bkg_service_invoice (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    si_no             varchar(40)    not null unique,
    type_code         varchar(40)    not null references bkg_si_type (code),
    kind              varchar(10)    not null check (kind in ('INVOICE', 'CREDIT')),
    invoice_no        varchar(40),
    arn               varchar(30),
    recipient_code    varchar(30)    not null,
    recipient_name    varchar(250)   not null,
    recipient_email   varchar(300),
    issue_date        date           not null,
    currency          varchar(3)     not null,
    commission        numeric(19, 2) not null,
    vat_on_commission numeric(19, 2) not null,
    wtax_amount       numeric(19, 2) not null,
    net_amount        numeric(19, 2) not null,
    template_code     varchar(40)    not null,
    template_version  integer        not null,
    document          bytea          not null,
    owner_username    varchar(50),
    owner_permission  varchar(60),
    message_id        bigint,
    dispatch_status   varchar(20)    not null
        check (dispatch_status in ('NOT_SENT', 'QUEUED', 'SENT', 'FAILED')),
    dispatch_error    varchar(1000),
    credit_of         varchar(40),
    remarks           varchar(500),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50)
);
create index ix_bkg_si_company on bkg_service_invoice (company_id, issue_date);
create index ix_bkg_si_invoice on bkg_service_invoice (invoice_no);
create index ix_bkg_si_credit on bkg_service_invoice (credit_of);

insert into bkg_si_type (code, name, recipient, trigger_type, owner_permission, template_code,
    created_at, created_by) values
    ('INSURER_COMMISSION', 'Commission invoice to insurer', 'INSURER', 'ON_BOOKING', 'BOOKING_PROCESS',
     'SERVICE_INVOICE_NOTE', now(), 'SYSTEM'),
    ('INSURER_COMMISSION_ENDT', 'Commission invoice to insurer - endorsement', 'INSURER', 'ON_ENDORSEMENT',
     'BOOKING_ADJUST', 'SERVICE_INVOICE_NOTE', now(), 'SYSTEM'),
    ('INTERNAL', 'Internal service invoice', 'INTERNAL', 'MANUAL', 'BOOKING_PROCESS',
     'SERVICE_INVOICE_NOTE', now(), 'SYSTEM');

-- ---------- Accounting event (rules are configured by Comptrollership; demo rule V988) --
insert into acc_event_type (code, name, category, journal_type, description, amount_components) values
 ('BROKER_BOOKING', 'Broker booking', 'PREMIUM', 'PREMIUM',
  'Booked invoice, endorsement or cancellation of a placed account (BRNB.027/076/081). Premium receivable '
  || 'by component from the client (party of the PR_ components) and due to the insurer; commission '
  || 'receivable from the insurer, unrealized (ON_COLLECTION) or realized (ON_BOOKING). Negative amounts '
  || 'reverse (return premium, cancellation).',
  'PR_BASIC,PR_DST,PR_PTX_VAT,PR_LGT,PR_FST,PR_OTHER,DTIP,COMMISSION_RECEIVABLE,UNREALIZED_COMMISSION,'
  || 'DEFERRED_OUTPUT_VAT,COMMISSION_INCOME,OUTPUT_VAT');

-- ---------- Business parameters -------------------------------------------------------------
insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('OPS_COMMISSION_REALIZATION', 'ON_COLLECTION', 'STRING', 'BOOKING',
     'When broker commission is realized: ON_COLLECTION (unrealized at booking, realized when premium is applied) or ON_BOOKING (commission income and output VAT at booking)',
     null, null, now(), 'SYSTEM'),
    ('BOOKING_WTAX_RATE', '10', 'DECIMAL', 'BOOKING',
     'Withholding tax rate (percent) the insurer withholds on the broker commission, printed on the booked invoice and service invoice',
     0, 100, now(), 'SYSTEM'),
    ('BOOKING_CWT2_SEGMENTS', '', 'CODE_LIST', 'BOOKING',
     'Market segments whose corporate clients withhold 2% creditable tax on premium (CWT 2% flag default; the booking screen can override it)',
     null, null, now(), 'SYSTEM')
on conflict (param_key) do nothing;
