-- =====================================================================================
-- iNXT BrokerVerse - V880 New Business reports and dashboard (nbreport, W4).
--   BRNB.012  NB dashboard: the landing page of the broking roles
--   BRNB.057  saved report variants (the dynamic report builder is parked, Q40)
--   BRNB.075  production statistics against targets per sales unit and period (targets are
--             demo values until BDOI supplies them, Q41)
--   BRNB.115  stalled accounts (parameter NB_STALLED_DAYS)
-- docs/architecture/BROKING_ARCHITECTURE.md section 16.
-- =====================================================================================

-- Production targets per sales unit (region, department, team or officer) and period, in PHP.
create table nbr_sales_target (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    unit_level        varchar(12)    not null,
    unit_code         varchar(50)    not null,
    period_from       date           not null,
    period_to         date           not null,
    target_count      integer        not null default 0,
    target_premium    numeric(19, 2) not null default 0,
    target_commission numeric(19, 2) not null default 0,
    currency          varchar(3)     not null default 'PHP',
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_nbr_sales_target unique (company_id, unit_level, unit_code, period_from),
    constraint ck_nbr_target_level check (unit_level in ('REGION', 'DEPARTMENT', 'TEAM', 'OFFICER')),
    constraint ck_nbr_target_period check (period_to >= period_from),
    constraint ck_nbr_target_values check (target_count >= 0 and target_premium >= 0
        and target_commission >= 0)
);
create index ix_nbr_sales_target_period on nbr_sales_target (company_id, period_from, period_to);

-- Saved report variants (BRNB.057): a user saves the parameters of a report under a name and
-- may share the variant with every user who may run the report.
create table nbr_report_variant (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    owner       varchar(50)   not null,
    report_code varchar(40)   not null,
    name        varchar(80)   not null,
    parameters  text          not null,
    shared      boolean       not null default false,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50)
);
create unique index uq_nbr_report_variant on nbr_report_variant (lower(owner), report_code, lower(name));
create index ix_nbr_report_variant_report on nbr_report_variant (report_code, shared);

insert into sys_parameter (param_key, param_value, value_type, category, description, min_value,
    max_value, created_at, created_by) values
    ('NB_STALLED_DAYS', '5', 'INTEGER', 'NB_REPORTS',
     'An open New Business account with no stage movement for this many days is reported as stalled (BRNB.115)',
     1, 90, now(), 'SYSTEM');

-- BRNB.012: the New Business dashboard replaces the finance executive dashboard as the landing
-- page of the broking team leaders and the approver; the executive dashboard stays with the
-- finance roles.
delete from sec_role_permission
 where permission = 'DASHBOARD_VIEW'
   and role_id in (select id from sec_role where code in ('MKT_TL', 'PROCESSING_TL', 'NB_APPROVER'));
