-- =====================================================================================
-- iNXT BrokerVerse - V891 Disbursement (BRD-5, wave A1-DSB): payee master and payment requests
--   DIS 2.2.0-2.2.8  payee master per party code: class (LOV PAYEE_CLASS), modes of payment,
--                    disbursement types, currency, default cost centre, source, workflow
--                    DISB_PAYEE (draft, authorisation, deactivation, reactivation); bank accounts
--                    per payee (dsb_payee_account); payee maintenance requests (dsb_payee_request)
--   DIS 2.4-2.6      payment requests from the gateway, uploads and manual encoding (dsb_request)
--   DIS 3.25.0-3.25.2 automatic classification, payee matching, requests without payee
-- Design: docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md section 5.1. Broking and
-- Operations tables are referenced by value only (party code, gateway request id).
-- =====================================================================================

create table dsb_payee (
    id                  bigint generated by default as identity primary key,
    version             bigint        not null default 0,
    company_id          bigint        not null references org_company (id),
    payee_code          varchar(30)   not null,
    payee_class         varchar(20)   not null,
    name                varchar(250)  not null,
    address             varchar(500),
    email               varchar(200),
    tin                 varchar(30),
    default_mode        varchar(20)   not null,
    allowed_modes       varchar(200)  not null,
    disbursement_types  varchar(300),
    currency            varchar(3)    not null,
    default_cost_center varchar(20),
    source              varchar(20)   not null,
    source_ref          varchar(80),
    stage               varchar(30)   not null,
    used                boolean       not null default false,
    remarks             varchar(500),
    created_at          timestamptz   not null,
    created_by          varchar(50)   not null,
    updated_at          timestamptz,
    updated_by          varchar(50),
    constraint uq_dsb_payee_code unique (company_id, payee_code),
    constraint ck_dsb_payee_mode check (default_mode in
        ('CTA', 'ATD', 'MC_DD', 'CREDIT_TICKET', 'TT', 'ONLINE_BANKING', 'CHECK')),
    constraint ck_dsb_payee_source check (source in ('MANUAL', 'UPLOAD', 'MIGRATION', 'REQUEST')),
    constraint ck_dsb_payee_stage check (stage in
        ('DRAFT', 'FOR_AUTHORIZATION', 'ACTIVE', 'FOR_DEACTIVATION', 'INACTIVE', 'FOR_REACTIVATION'))
);
create index ix_dsb_payee_stage on dsb_payee (company_id, stage);
create index ix_dsb_payee_name on dsb_payee (company_id, lower(name));

create table dsb_payee_account (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,
    payee_id        bigint        not null references dsb_payee (id) on delete cascade,
    bank_name       varchar(120)  not null,
    bank_branch     varchar(120),
    account_no      varchar(40)   not null,
    account_name    varchar(250)  not null,
    currency        varchar(3)    not null,
    mode            varchar(20)   not null,
    primary_account boolean       not null default false,
    active          boolean       not null default true,
    created_at      timestamptz   not null,
    created_by      varchar(50)   not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_dsb_payee_account_mode check (mode in ('CTA', 'TT', 'ONLINE_BANKING'))
);
create index ix_dsb_payee_account on dsb_payee_account (payee_id);
create index ix_dsb_payee_account_no on dsb_payee_account (account_no);

create table dsb_payee_request (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    company_id  bigint        not null references org_company (id),
    source      varchar(20)   not null,
    payee_code  varchar(30),
    payee_name  varchar(250)  not null,
    details     varchar(1000),
    source_ref  varchar(80),
    status      varchar(20)   not null,
    payee_id    bigint references dsb_payee (id),
    closed_by   varchar(50),
    closed_at   timestamptz,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint ck_dsb_payee_request_source check (source in ('RRF', 'DISBURSEMENT', 'NO_MATCH')),
    constraint ck_dsb_payee_request_status check (status in ('OPEN', 'DONE', 'CANCELLED'))
);
create index ix_dsb_payee_request_status on dsb_payee_request (company_id, status);

create table dsb_request (
    id                   bigint generated by default as identity primary key,
    version              bigint         not null default 0,
    company_id           bigint         not null references org_company (id),
    request_no           varchar(30)    not null,
    source               varchar(20)    not null,
    source_module        varchar(30)    not null,
    source_ref           varchar(80)    not null,
    rfp_no               varchar(40),
    disbursement_type    varchar(30)    not null,
    payee_class          varchar(20),
    payee_code           varchar(30)    not null,
    payee_name           varchar(250),
    payee_id             bigint references dsb_payee (id),
    currency             varchar(3)     not null,
    amount               numeric(19, 2) not null,
    purpose              varchar(500),
    received_at          timestamptz    not null,
    root_invoice_no      varchar(40),
    attachment_refs      varchar(1000),
    accounting_refs      varchar(1000),
    straight_to_approval boolean        not null default false,
    status               varchar(20)    not null,
    status_reason        varchar(250),
    gateway_request_id   bigint,
    upload_job_no        varchar(30),
    expense_account      varchar(30),
    cost_center          varchar(20),
    voucher_id           bigint,
    created_at           timestamptz    not null,
    created_by           varchar(50)    not null,
    updated_at           timestamptz,
    updated_by           varchar(50),
    constraint uq_dsb_request_no unique (request_no),
    constraint uq_dsb_request_source unique (source_module, source_ref),
    constraint ck_dsb_request_amount check (amount > 0),
    constraint ck_dsb_request_source check (source in ('GATEWAY', 'UPLOAD', 'ENCODED', 'PAYREQUEST')),
    constraint ck_dsb_request_status check (status in
        ('RECEIVED', 'NO_PAYEE', 'IN_VOUCHER', 'RELEASED', 'RETURNED', 'CANCELLED'))
);
create index ix_dsb_request_status on dsb_request (company_id, status, received_at);
create index ix_dsb_request_payee on dsb_request (company_id, payee_code);
create index ix_dsb_request_gateway on dsb_request (gateway_request_id);

-- One-time migration of the open requests of the in-app queue (design 12.2, OQ02): requests still
-- SENT or ACKNOWLEDGED become Disbursement requests waiting for their payee to be matched. On a
-- fresh database the queue is empty and nothing is copied.
insert into dsb_request (company_id, request_no, source, source_module, source_ref, rfp_no,
    disbursement_type, payee_class, payee_code, payee_name, currency, amount, purpose, received_at,
    root_invoice_no, attachment_refs, accounting_refs, straight_to_approval, status, status_reason,
    gateway_request_id, created_at, created_by)
select q.company_id, 'DSR-MIG-' || q.id, 'GATEWAY', q.source_module, q.source_ref, q.rfp_no,
       coalesce(q.disbursement_type, q.request_type), q.payee_class, q.payee_code, q.payee_name,
       q.currency, q.amount, q.description, q.sent_at, q.root_invoice_no, q.attachment_refs,
       q.accounting_refs, q.straight_to_approval, 'NO_PAYEE', 'Migrated from the in-app queue', q.id,
       now(), 'SYSTEM'
from ops_disbursement_request q
where q.status in ('SENT', 'ACKNOWLEDGED');
