-- =====================================================================================
-- iNXT BrokerVerse - V892 Disbursement (BRD-5, wave A1-DSB): vouchers, instruments, end of day,
-- tags, status edits and account funding
--   DIS 2.7.0-2.7.12  disbursement voucher (DV-<yyyy>-nnnnnn) with its editable proforma entry
--                     (dsb_voucher_line: from rule / edited / allocation), workflow DISB_VOUCHER
--   DIS 2.8.x, 3.26.x instrument per DV and mode (dsb_instrument) with its status history
--   DIS 2.8.5         status edits submitted for approval (workflow DISB_STATUS_EDIT)
--   DIS 2.10-2.11     OR / AR and CWT tags on the DV
--   DIS 2.16.x        end-of-day runs and their outputs (DCTF, checks, forms, reports)
--   DIS 2.17.x        funding of the main BDOIR account (workflow DISB_FUNDING)
--   DIS 2.19-2.21, 3.27.0 approval posting, cancellation and regularisation state
-- =====================================================================================

create table dsb_eod_run (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    run_no        varchar(30)   not null,
    business_date date          not null,
    status        varchar(20)   not null,
    vouchers      integer       not null default 0,
    checks        integer       not null default 0,
    credits       integer       not null default 0,
    forms         integer       not null default 0,
    reports       integer       not null default 0,
    emails        integer       not null default 0,
    message       varchar(1000),
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint uq_dsb_eod_run_no unique (run_no),
    constraint uq_dsb_eod_run_date unique (company_id, business_date),
    constraint ck_dsb_eod_run_status check (status in ('COMPLETED', 'CONFIRMED'))
);

create table dsb_eod_output (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    eod_run_id   bigint        not null references dsb_eod_run (id),
    kind         varchar(30)   not null,
    code         varchar(40)   not null,
    file_name    varchar(200)  not null,
    content_type varchar(100)  not null,
    content      bytea         not null,
    item_count   integer       not null default 0,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50)
);
create index ix_dsb_eod_output_run on dsb_eod_output (eod_run_id);

create table dsb_voucher (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint references org_branch (id),
    dv_no             varchar(30)    not null,
    request_id        bigint         not null references dsb_request (id),
    payee_id          bigint         not null references dsb_payee (id),
    payee_code        varchar(30)    not null,
    payee_name        varchar(250)   not null,
    payee_class       varchar(20)    not null,
    disbursement_type varchar(30)    not null,
    mode              varchar(20)    not null,
    bank_account_id   bigint references pay_bank_account (id),
    payee_account_id  bigint references dsb_payee_account (id),
    currency          varchar(3)     not null,
    exchange_rate     numeric(19, 8),
    gross             numeric(19, 2) not null,
    ewt               numeric(19, 2) not null default 0,
    net               numeric(19, 2) not null,
    purpose           varchar(500),
    root_invoice_no   varchar(40),
    value_date        date,
    cost_center       varchar(20),
    expense_account   varchar(30),
    stage             varchar(20)    not null,
    auto_created      boolean        not null default false,
    proforma_edited   boolean        not null default false,
    posting_status    varchar(20)    not null,
    posting_error     varchar(1000),
    journal_no        varchar(30),
    cancel_journal_no varchar(30),
    submitted_by      varchar(50),
    reviewed_by       varchar(50),
    approved_by       varchar(50),
    approved_at       timestamptz,
    cancel_reason     varchar(250),
    cancelled_by      varchar(50),
    cancelled_at      timestamptz,
    eod_run_id        bigint references dsb_eod_run (id),
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint uq_dsb_voucher_no unique (dv_no),
    constraint uq_dsb_voucher_request unique (request_id),
    constraint ck_dsb_voucher_stage check (stage in
        ('IN_PROCESS', 'FOR_REVIEW', 'FOR_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED')),
    constraint ck_dsb_voucher_mode check (mode in
        ('CTA', 'ATD', 'MC_DD', 'CREDIT_TICKET', 'TT', 'ONLINE_BANKING', 'CHECK')),
    constraint ck_dsb_voucher_posting check (posting_status in
        ('NOT_POSTED', 'POSTED', 'FAILED', 'REVERSED', 'REVERSAL_FAILED')),
    constraint ck_dsb_voucher_amounts check (gross > 0 and ewt >= 0 and net = gross - ewt)
);
create index ix_dsb_voucher_stage on dsb_voucher (company_id, stage);
create index ix_dsb_voucher_payee on dsb_voucher (company_id, payee_code);
create index ix_dsb_voucher_eod on dsb_voucher (eod_run_id);

alter table dsb_request
    add constraint fk_dsb_request_voucher foreign key (voucher_id) references dsb_voucher (id);

create table dsb_voucher_line (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    voucher_id    bigint         not null references dsb_voucher (id) on delete cascade,
    line_no       integer        not null,
    side          varchar(6)     not null,
    account_code  varchar(30)    not null,
    party_code    varchar(30),
    cost_center   varchar(20),
    business_line varchar(20),
    amount        numeric(19, 2) not null,
    component     varchar(30),
    origin        varchar(12)    not null,
    narration     varchar(250),
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_dsb_voucher_line_side check (side in ('DEBIT', 'CREDIT')),
    constraint ck_dsb_voucher_line_amount check (amount > 0),
    constraint ck_dsb_voucher_line_origin check (origin in ('RULE', 'EDITED', 'ALLOCATION'))
);
create index ix_dsb_voucher_line on dsb_voucher_line (voucher_id, line_no);

create table dsb_instrument (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    voucher_id      bigint         not null references dsb_voucher (id),
    mode            varchar(20)    not null,
    instrument_no   varchar(40),
    status          varchar(20)    not null,
    amount          numeric(19, 2) not null,
    currency        varchar(3)     not null,
    bank_account_id bigint references pay_bank_account (id),
    reference       varchar(80),
    printed_on      date,
    printed_at      timestamptz,
    released_at     timestamptz,
    released_to     varchar(250),
    emailed_at      timestamptz,
    received_at     timestamptz,
    credited_at     timestamptz,
    debited_at      timestamptz,
    negotiated_at   timestamptz,
    stale_at        timestamptz,
    cancelled_at    timestamptz,
    eod_run_id      bigint references dsb_eod_run (id),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint uq_dsb_instrument_voucher unique (voucher_id),
    constraint ck_dsb_instrument_status check (status in ('PENDING', 'PRINTED', 'RELEASED',
        'NEGOTIATED', 'STALE', 'CANCELLED', 'EMAILED', 'DEBITED', 'EXTRACTED', 'CREDITED',
        'RECEIVED', 'APPROVED'))
);
create index ix_dsb_instrument_status on dsb_instrument (mode, status);
create index ix_dsb_instrument_no on dsb_instrument (instrument_no);

create table dsb_instrument_event (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    instrument_id bigint        not null references dsb_instrument (id),
    from_status   varchar(20),
    to_status     varchar(20)   not null,
    source        varchar(10)   not null,
    note          varchar(500),
    file_ref      varchar(80),
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_dsb_instrument_event_source check (source in ('USER', 'SYSTEM', 'UPLOAD', 'JOB'))
);
create index ix_dsb_instrument_event on dsb_instrument_event (instrument_id, id);

create table dsb_voucher_tag (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    voucher_id      bigint         not null references dsb_voucher (id),
    kind            varchar(10)    not null,
    direction       varchar(10),
    doc_no          varchar(40),
    doc_date        date,
    received_on     date,
    released_on     date,
    period_from     date,
    period_to       date,
    amount          numeric(19, 2),
    certificate_ref varchar(60),
    remarks         varchar(500),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint ck_dsb_voucher_tag_kind check (kind in ('OR_AR', 'CWT')),
    constraint ck_dsb_voucher_tag_direction check (direction is null or direction in ('RECEIVED', 'RELEASED'))
);
create index ix_dsb_voucher_tag on dsb_voucher_tag (voucher_id);

create table dsb_status_edit (
    id            bigint generated by default as identity primary key,
    version       bigint        not null default 0,
    company_id    bigint        not null references org_company (id),
    instrument_id bigint        not null references dsb_instrument (id),
    from_status   varchar(20)   not null,
    to_status     varchar(20)   not null,
    reason        varchar(500)  not null,
    stage         varchar(20)   not null,
    decided_by    varchar(50),
    decided_at    timestamptz,
    created_at    timestamptz   not null,
    created_by    varchar(50)   not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint ck_dsb_status_edit_stage check (stage in ('REQUESTED', 'APPLIED', 'REJECTED'))
);
create index ix_dsb_status_edit on dsb_status_edit (company_id, stage);

create table dsb_funding_request (
    id                     bigint generated by default as identity primary key,
    version                bigint         not null default 0,
    company_id             bigint         not null references org_company (id),
    funding_no             varchar(30)    not null,
    source_bank_account_id bigint         not null references pay_bank_account (id),
    target_bank_account_id bigint         not null references pay_bank_account (id),
    amount                 numeric(19, 2) not null,
    currency               varchar(3)     not null,
    purpose                varchar(500)   not null,
    value_date             date           not null,
    stage                  varchar(20)    not null,
    verified_by            varchar(50),
    first_approver         varchar(50),
    second_approver        varchar(50),
    bob_reference          varchar(80),
    journal_no             varchar(30),
    created_at             timestamptz    not null,
    created_by             varchar(50)    not null,
    updated_at             timestamptz,
    updated_by             varchar(50),
    constraint uq_dsb_funding_no unique (funding_no),
    constraint ck_dsb_funding_amount check (amount > 0),
    constraint ck_dsb_funding_accounts check (source_bank_account_id <> target_bank_account_id),
    constraint ck_dsb_funding_stage check (stage in ('CREATED', 'FOR_VERIFICATION', 'FOR_APPROVAL_1',
        'FOR_APPROVAL_2', 'APPROVED', 'DECLINED', 'CANCELLED'))
);
create index ix_dsb_funding_stage on dsb_funding_request (company_id, stage);
