-- =====================================================================================
-- iNXT BrokerVerse - V894 Refund and cash-advance requests (payrequest, BRD-5 MKT 1.2-2.26).
--   MKT 1.2.0/1.10.0  refund requests (RRF, lines per AR) and requests for payment (RFP, cash
--                     advance) with the Appendix D fields
--   MKT 1.11.0        validation of refunds of cancelled policies by ACSL and Cashiering
--   MKT 1.19.0        cancellation of a disbursed check, routed for review and approval
--   MKT 2.23.0        one live refund per AR number (unique partial index)
--   MKT 2.24.0        approved requests sent to Disbursement through DisbursementGateway
--   Appendix D / AQ18 cash-advance liquidation, posted with event PRQ_CA_LIQUIDATION (V890)
-- Workflows PRQ_REFUND, PRQ_CASH_ADVANCE and PRQ_CHECK_CANCEL, the roles and the LOV types
-- REFUND_REASON, RRF_CATEGORY_A/B come from V890; ACCOUNTING_DISBURSEMENT_DESIGN 5.2.
-- =====================================================================================

create table prq_request (
    id                      bigint generated by default as identity primary key,
    version                 bigint         not null default 0,
    company_id              bigint         not null references org_company (id),
    branch_id               bigint         not null references org_branch (id),
    request_no              varchar(30)    not null unique,
    kind                    varchar(20)    not null,
    stage                   varchar(30)    not null,
    segment                 varchar(40),
    reference_text          varchar(80),
    request_date            date           not null,
    requesting_unit         varchar(60),
    payee_type              varchar(10)    not null,
    payee_code              varchar(30)    not null,
    payee_name              varchar(250)   not null,
    payment_mode            varchar(20)    not null,
    account_no              varchar(40),
    account_name            varchar(250),
    rfp_type                varchar(30),
    purpose                 varchar(500)   not null,
    currency                varchar(3)     not null,
    amount                  numeric(19, 2) not null,
    validation_required     boolean        not null default false,
    validation_round        integer        not null default 0,
    target_request_no       varchar(30),
    target_dv_no            varchar(40),
    check_no                varchar(40),
    cancel_reason           varchar(40),
    submitted_by            varchar(50),
    submitted_at            timestamptz,
    reviewed_by             varchar(50),
    reviewed_at             timestamptz,
    approved_by             varchar(50),
    approved_at             timestamptz,
    hr_approved_by          varchar(50),
    hr_approved_at          timestamptz,
    return_reason           varchar(40),
    return_comment          varchar(500),
    send_count              integer        not null default 0,
    disbursement_request_no varchar(30),
    disbursement_status     varchar(20),
    dv_no                   varchar(40),
    dv_status               varchar(30),
    instrument_status       varchar(30),
    disbursement_message    varchar(250),
    disbursed_at            timestamptz,
    handoff_ref             varchar(40),
    payout_recorded         boolean        not null default false,
    created_at              timestamptz    not null,
    created_by              varchar(50)    not null,
    updated_at              timestamptz,
    updated_by              varchar(50),
    constraint ck_prq_request_kind check (kind in ('REFUND', 'CASH_ADVANCE', 'CHECK_CANCELLATION')),
    constraint ck_prq_request_stage check (stage in ('DRAFT', 'PREPARING', 'FOR_VALIDATION', 'FOR_REVIEW',
        'FOR_APPROVAL', 'HR_APPROVAL', 'SENT_TO_DISBURSEMENT', 'DISBURSED', 'REQUESTED', 'SENT', 'CANCELLED')),
    constraint ck_prq_request_payee check (payee_type in ('CLIENT', 'EMPLOYEE')),
    constraint ck_prq_request_amount check (amount >= 0),
    constraint ck_prq_request_check check (kind <> 'CHECK_CANCELLATION' or target_request_no is not null)
);
create index ix_prq_request_stage on prq_request (company_id, stage, kind);
create index ix_prq_request_date on prq_request (company_id, request_date);
create index ix_prq_request_payee on prq_request (company_id, payee_code);
create index ix_prq_request_target on prq_request (target_request_no) where target_request_no is not null;
create index ix_prq_request_dv on prq_request (dv_no) where dv_no is not null;

-- Refund lines (Appendix D RRF): one AR per line; a live line blocks another refund of the same AR
create table prq_request_line (
    id               bigint generated by default as identity primary key,
    request_id       bigint         not null references prq_request (id),
    line_no          integer        not null,
    ar_no            varchar(40)    not null,
    client_code      varchar(30)    not null,
    assured_name     varchar(250)   not null,
    invoice_no       varchar(40),
    root_invoice_no  varchar(40),
    amount           numeric(19, 2) not null,
    reason_code      varchar(40)    not null,
    branch_unit      varchar(60),
    category_a       varchar(40),
    category_b       varchar(40),
    account_name     varchar(250),
    cancelled_policy boolean        not null default false,
    live             boolean        not null default true,
    constraint uq_prq_request_line unique (request_id, line_no),
    constraint ck_prq_request_line_amount check (amount > 0)
);
create unique index uq_prq_live_ar on prq_request_line (ar_no) where live;
create index ix_prq_request_line_invoice on prq_request_line (invoice_no);

-- Validation tasks of a refund of a cancelled policy (MKT 1.11.0), one per validator and line
create table prq_validation (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    request_id   bigint        not null references prq_request (id),
    round_no     integer       not null,
    line_no      integer       not null,
    validator    varchar(20)   not null,
    source_ref   varchar(80)   not null,
    status       varchar(20)   not null,
    ticket_ref   varchar(40),
    message      varchar(500),
    new_ar_no    varchar(40),
    remarks      varchar(500),
    completed_by varchar(50),
    completed_at timestamptz,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_prq_validation unique (request_id, round_no, line_no, validator),
    constraint uq_prq_validation_ref unique (validator, source_ref),
    constraint ck_prq_validation_validator check (validator in ('ACSL', 'CASHIERING')),
    constraint ck_prq_validation_status check (status in ('OPEN', 'DEFERRED', 'CONFIRMED', 'REJECTED'))
);

-- Cash-advance liquidation (Appendix D Liquidation Form; in scope if confirmed, AQ18)
create table prq_liquidation (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    request_id       bigint         not null unique references prq_request (id),
    liquidation_no   varchar(30)    not null unique,
    status           varchar(20)    not null,
    job_level        varchar(40),
    cost_center      varchar(20),
    remarks          varchar(500),
    total_expenses   numeric(19, 2) not null default 0,
    cash_advanced    numeric(19, 2) not null,
    over_short       numeric(19, 2) not null default 0,
    submitted_by     varchar(50),
    submitted_at     timestamptz,
    posted_by        varchar(50),
    posted_at        timestamptz,
    journal_batch_no varchar(40),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_prq_liquidation_status check (status in ('DRAFT', 'SUBMITTED', 'POSTED'))
);

create table prq_liquidation_line (
    id             bigint generated by default as identity primary key,
    liquidation_id bigint         not null references prq_liquidation (id),
    line_no        integer        not null,
    fieldwork_date date           not null,
    particulars    varchar(250)   not null,
    per_diem       numeric(19, 2) not null default 0,
    representation numeric(19, 2) not null default 0,
    transport      numeric(19, 2) not null default 0,
    lodging        numeric(19, 2) not null default 0,
    others         numeric(19, 2) not null default 0,
    constraint uq_prq_liquidation_line unique (liquidation_id, line_no),
    constraint ck_prq_liquidation_line check (per_diem >= 0 and representation >= 0 and transport >= 0
        and lodging >= 0 and others >= 0)
);

-- Expense and cash accounts of the liquidation event roles (@PER_DIEM ... @CASH), configured by
-- Comptrollership (GL accounts are never chosen in code; real accounts AQ02 / OQ07)
create table prq_liquidation_account (
    id           bigint generated by default as identity primary key,
    version      bigint       not null default 0,
    company_id   bigint       not null references org_company (id),
    account_role varchar(20)  not null,
    account_code varchar(30)  not null,
    created_at   timestamptz  not null,
    created_by   varchar(50)  not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint uq_prq_liquidation_account unique (company_id, account_role),
    constraint ck_prq_liquidation_role check (account_role in ('PER_DIEM', 'REPRESENTATION', 'TRANSPORT',
        'LODGING', 'OTHER', 'CASH'))
);

-- ---------- Lists of values of the request forms (Appendix D) --------------------------------
insert into lov_type (code, name, description, maintainable, created_at, created_by)
values ('PRQ_PAYMENT_MODE', 'Request payment mode',
        'Mode of payment on a refund or payment request (Appendix D: credit to CA / SA, check, ATD, inter-office, manager''s check, demand draft)',
        true, now(), 'SYSTEM'),
       ('PRQ_RFP_TYPE', 'Request for payment type',
        'Type of a request for payment (Appendix D RFP; cash advance is the type in scope, AQ18)', true, now(), 'SYSTEM');

insert into lov_value (type_code, code, label, sort_order, parent_code, effective_from, record_status,
                       authorized_by, authorized_at, created_at, created_by)
select v.type_code, v.code, v.label, v.sort_order, null, date '2020-01-01', 'ACTIVE', 'SYSTEM', now(),
       now(), 'SYSTEM'
from (values
    ('PRQ_PAYMENT_MODE', 'CTA', 'Credit to CA / SA', 10),
    ('PRQ_PAYMENT_MODE', 'CHECK', 'Check', 20),
    ('PRQ_PAYMENT_MODE', 'ATD', 'Authority to debit (ATD)', 30),
    ('PRQ_PAYMENT_MODE', 'INTER_OFFICE', 'Inter-office', 40),
    ('PRQ_PAYMENT_MODE', 'MANAGERS_CHECK', 'Manager''s check', 50),
    ('PRQ_PAYMENT_MODE', 'DEMAND_DRAFT', 'Demand draft', 60),
    ('PRQ_RFP_TYPE', 'CASH_ADVANCE', 'Cash advance', 10),
    ('PRQ_RFP_TYPE', 'PETTY_CASH', 'Petty cash replenishment (to confirm, AQ18)', 20),
    ('PRQ_RFP_TYPE', 'OTHERS', 'Others (specify in the purpose)', 90)
) as v(type_code, code, label, sort_order);

-- ---------- Notification event of request status changes (MKT 1.20.0, 2.26.0) ----------------
insert into msg_notification_event (code, name, module, description, default_in_app, default_email, sort_order) values
    ('PRQ_REQUEST_STATUS', 'Refund / cash advance request status', 'PAYREQUEST',
     'A refund, cash-advance or check-cancellation request was validated, returned, approved or disbursed (MKT 1.20.0, 2.26.0)',
     true, false, 300);
