-- =====================================================================================
-- iNXT BrokerVerse - V896 ACSL (Accounting Control and Sub-Ledger, BRD-5 ACSL 2.2-2.16).
--   ACSL 2.5.x/2.6.x  cases: investigations, account analysis requests (refund validation of
--                     payrequest, MKT 1.11.0), AR refund application, SL payment reversal requests
--   ACSL 2.7-2.15     correction entries (assign, draft, review, approve, post) with lines linked
--   ACSL 2.9.1        to the invoice family; the original posting is reversed, never changed
--   ACSL 2.4.0/2.13.1 insurer SOA uploads with their upload log and the SOA reconciliation per
--   ACSL 2.14.1       invoice (Outstanding, For remittance, Remitted, Cancelled, Direct billed,
--                     Not found; SOA balance and variances)
--   ACSL 2.13.2       GL-SL reconciliation per control account (job ACSL_GL_SL_RECON)
-- Workflows ACSL_CASE / ACSL_CORRECTION, LOV types ACSL_CASE_TYPE / ACSL_CORRECTION_KIND, the
-- alert ACSL_GLSL_DIFFERENCE and the roles come from V890; ACCOUNTING_DISBURSEMENT_DESIGN 5.3.
-- =====================================================================================

create table acsl_case (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    company_id       bigint         not null references org_company (id),
    case_no          varchar(30)    not null unique,
    case_type        varchar(30)    not null,
    stage            varchar(30)    not null,
    invoice_no       varchar(40),
    root_invoice_no  varchar(40),
    insurer_code     varchar(30),
    client_code      varchar(30),
    ar_no            varchar(40),
    currency         varchar(3),
    amount           numeric(19, 2),
    subject          varchar(250)   not null,
    details          varchar(2000),
    requester_module varchar(30),
    requester_ref    varchar(80),
    requested_by     varchar(50)    not null,
    findings         varchar(4000),
    outcome          varchar(20),
    result_remarks   varchar(1000),
    result_by        varchar(50),
    result_at        timestamptz,
    correction_id    bigint,
    reversal_ref     varchar(40),
    reversal_status  varchar(20),
    reversal_message varchar(500),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint ck_acsl_case_type check (case_type in ('INVESTIGATION', 'ANALYSIS_REQUEST', 'REFUND_APPLICATION',
        'PAYMENT_REVERSAL')),
    constraint ck_acsl_case_stage check (stage in ('RECEIVED', 'ASSIGNED', 'INVESTIGATING', 'RESULT_PROVIDED',
        'CORRECTION')),
    constraint ck_acsl_case_outcome check (outcome is null or outcome in ('CONFIRMED', 'REJECTED', 'NO_ACTION',
        'CORRECTION'))
);
create index ix_acsl_case_stage on acsl_case (company_id, stage, case_type);
create index ix_acsl_case_invoice on acsl_case (root_invoice_no);
create unique index uq_acsl_case_requester on acsl_case (requester_module, requester_ref)
    where requester_ref is not null;

create table acsl_correction (
    id                bigint generated by default as identity primary key,
    version           bigint         not null default 0,
    company_id        bigint         not null references org_company (id),
    branch_id         bigint         not null references org_branch (id),
    correction_no     varchar(30)    not null unique,
    case_id           bigint         references acsl_case (id),
    kind              varchar(20)    not null,
    stage             varchar(20)    not null,
    invoice_no        varchar(40),
    root_invoice_no   varchar(40),
    original_batch_no varchar(40),
    currency          varchar(3)     not null,
    description       varchar(500)   not null,
    submitted_by      varchar(50),
    submitted_at      timestamptz,
    reviewed_by       varchar(50),
    reviewed_at       timestamptz,
    approved_by       varchar(50),
    approved_at       timestamptz,
    return_comment    varchar(500),
    journal_batch_no  varchar(40),
    posted_at         timestamptz,
    open_items        integer        not null default 0,
    ledger_movements  integer        not null default 0,
    created_at        timestamptz    not null,
    created_by        varchar(50)    not null,
    updated_at        timestamptz,
    updated_by        varchar(50),
    constraint ck_acsl_correction_stage check (stage in ('ASSIGNED', 'DRAFT', 'FOR_REVIEW', 'FOR_APPROVAL',
        'POSTED', 'CANCELLED'))
);
create index ix_acsl_correction_stage on acsl_correction (company_id, stage);
create index ix_acsl_correction_invoice on acsl_correction (root_invoice_no);
alter table acsl_case add constraint fk_acsl_case_correction
    foreign key (correction_id) references acsl_correction (id);

create table acsl_correction_line (
    id                bigint generated by default as identity primary key,
    correction_id     bigint         not null references acsl_correction (id),
    line_no           integer        not null,
    account_code      varchar(30)    not null,
    side              varchar(6)     not null,
    amount            numeric(19, 2) not null,
    party_code        varchar(30),
    invoice_no        varchar(40),
    component         varchar(20),
    cost_center       varchar(20),
    business_line     varchar(20),
    narration         varchar(250),
    origin            varchar(10)    not null,
    original_batch_no varchar(40),
    original_line_no  integer,
    constraint ck_acsl_correction_line_side check (side in ('DEBIT', 'CREDIT')),
    constraint ck_acsl_correction_line_amount check (amount > 0),
    constraint ck_acsl_correction_line_origin check (origin in ('REVERSAL', 'REPOST', 'MANUAL'))
);
create index ix_acsl_correction_line on acsl_correction_line (correction_id, line_no);

-- Insurer SOA layouts (ACSL 2.4.0; the insurers' formats are not known yet, AQ21): the header of each
-- field in the insurer's file. insurer_code '*' is the standard ACSL template used when an insurer has
-- no layout of its own.
create table acsl_soa_layout (
    id               bigint generated by default as identity primary key,
    version          bigint        not null default 0,
    insurer_code     varchar(30)   not null unique,
    name             varchar(120)  not null,
    invoice_header   varchar(60)   not null,
    policy_header    varchar(60)   not null,
    assured_header   varchar(60)   not null,
    inception_header varchar(60)   not null,
    expiry_header    varchar(60)   not null,
    gross_header     varchar(60)   not null,
    balance_header   varchar(60)   not null,
    paid_header      varchar(60)   not null,
    active           boolean       not null default true,
    created_at       timestamptz   not null,
    created_by       varchar(50)   not null,
    updated_at       timestamptz,
    updated_by       varchar(50)
);

insert into acsl_soa_layout (insurer_code, name, invoice_header, policy_header, assured_header, inception_header,
    expiry_header, gross_header, balance_header, paid_header, created_at, created_by)
values ('*', 'Standard ACSL SOA template', 'Invoice No', 'Policy No', 'Assured', 'Inception Date', 'Expiry Date',
        'Gross Premium', 'Balance', 'Payments', now(), 'SYSTEM');

create table acsl_soa_upload (
    id           bigint generated by default as identity primary key,
    version      bigint        not null default 0,
    company_id   bigint        not null references org_company (id),
    upload_no    varchar(30)   not null unique,
    insurer_code varchar(30)   not null,
    period_from  date          not null,
    period_to    date          not null,
    file_name    varchar(250)  not null,
    sha256       varchar(64)   not null,
    layout_code  varchar(30)   not null,
    rows_read    integer       not null default 0,
    rows_loaded  integer       not null default 0,
    rows_failed  integer       not null default 0,
    last_run_id  bigint,
    created_at   timestamptz   not null,
    created_by   varchar(50)   not null,
    updated_at   timestamptz,
    updated_by   varchar(50),
    constraint ck_acsl_soa_period check (period_to >= period_from)
);
create index ix_acsl_soa_upload_insurer on acsl_soa_upload (company_id, insurer_code, period_to);
create unique index uq_acsl_soa_upload_file on acsl_soa_upload (company_id, insurer_code, sha256);

create table acsl_soa_line (
    id             bigint generated by default as identity primary key,
    upload_id      bigint         not null references acsl_soa_upload (id),
    row_no         integer        not null,
    status         varchar(10)    not null,
    error          varchar(500),
    invoice_no     varchar(40),
    policy_no      varchar(60),
    assured_name   varchar(250),
    inception_date date,
    expiry_date    date,
    gross_premium  numeric(19, 2),
    balance        numeric(19, 2),
    paid           numeric(19, 2),
    constraint uq_acsl_soa_line unique (upload_id, row_no),
    constraint ck_acsl_soa_line_status check (status in ('LOADED', 'FAILED'))
);

create table acsl_recon_run (
    id             bigint generated by default as identity primary key,
    upload_id      bigint        not null references acsl_soa_upload (id),
    run_no         integer       not null,
    run_at         timestamptz   not null,
    run_by         varchar(50)   not null,
    outstanding    integer       not null default 0,
    for_remittance integer       not null default 0,
    remitted       integer       not null default 0,
    cancelled      integer       not null default 0,
    direct_billed  integer       not null default 0,
    not_found      integer       not null default 0,
    with_variance  integer       not null default 0,
    constraint uq_acsl_recon_run unique (upload_id, run_no)
);
alter table acsl_soa_upload add constraint fk_acsl_soa_upload_run
    foreign key (last_run_id) references acsl_recon_run (id);

create table acsl_recon_result (
    id                   bigint generated by default as identity primary key,
    run_id               bigint         not null references acsl_recon_run (id),
    row_no               integer        not null,
    invoice_no           varchar(40),
    policy_no            varchar(60),
    assured_name         varchar(250),
    root_invoice_no      varchar(40),
    bucket               varchar(20)    not null,
    book_premium         numeric(19, 2),
    book_outstanding     numeric(19, 2),
    for_remittance       numeric(19, 2),
    remitted             numeric(19, 2),
    remittance_batch_no  varchar(40),
    remittance_date      date,
    pr2307_amount        numeric(19, 2),
    pr2307_batch_no      varchar(40),
    pr2307_date          date,
    cancellation_ref     varchar(40),
    direct_billed        boolean        not null default false,
    soa_premium          numeric(19, 2),
    soa_balance          numeric(19, 2),
    premium_variance     numeric(19, 2),
    outstanding_variance numeric(19, 2),
    constraint ck_acsl_recon_bucket check (bucket in ('OUTSTANDING', 'FOR_REMITTANCE', 'REMITTED', 'CANCELLED',
        'DIRECT_BILLED', 'NOT_FOUND'))
);
create index ix_acsl_recon_result_run on acsl_recon_result (run_id, bucket);

-- GL-SL reconciliation (ACSL 2.13.2). The sub-ledger behind a control account is configuration:
-- PARTY_LEDGER (default for every control account: the account's postings that carry a sub-ledger
-- party), OPEN_ITEMS (outstanding open items of the listed document types) or OPS_LEDGER (balance of
-- the listed Operations invoice components in the given currency).
create table acsl_glsl_control (
    id             bigint generated by default as identity primary key,
    version        bigint        not null default 0,
    company_id     bigint        not null references org_company (id),
    account_code   varchar(30)   not null,
    source         varchar(20)   not null,
    components     varchar(200),
    document_types varchar(200),
    currency       varchar(3),
    active         boolean       not null default true,
    created_at     timestamptz   not null,
    created_by     varchar(50)   not null,
    updated_at     timestamptz,
    updated_by     varchar(50),
    constraint uq_acsl_glsl_control unique (company_id, account_code),
    constraint ck_acsl_glsl_source check (source in ('PARTY_LEDGER', 'OPEN_ITEMS', 'OPS_LEDGER'))
);

create table acsl_glsl_run (
    id               bigint generated by default as identity primary key,
    company_id       bigint         not null references org_company (id),
    as_of            date           not null,
    run_at           timestamptz    not null,
    run_by           varchar(50)    not null,
    accounts         integer        not null,
    differences      integer        not null,
    total_difference numeric(19, 2) not null
);
create index ix_acsl_glsl_run on acsl_glsl_run (company_id, as_of);

create table acsl_glsl_recon (
    id           bigint generated by default as identity primary key,
    run_id       bigint         not null references acsl_glsl_run (id),
    account_code varchar(30)    not null,
    account_name varchar(200)   not null,
    source       varchar(20)    not null,
    gl_balance   numeric(19, 2) not null,
    sl_balance   numeric(19, 2) not null,
    difference   numeric(19, 2) not null
);
create index ix_acsl_glsl_recon_run on acsl_glsl_recon (run_id);
