-- =====================================================================================
-- iNXT BrokerVerse - V898 FRBS service fee (BRD-5 wave A1-FRBS)
--   FRBS 2.10.0-2.10.2, Appendix A VI (service fee = referrers' share, 2.5% / 1% of fully paid
--   commission net of taxes, per market segment); docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md
--   sections 5.4, 6 (row 20) and 7.3.
--
--   * frbs_service_fee_rule       rate per service-fee segment (LOV SERVICE_FEE_SEGMENT) and the
--                                 market segments (LOV MARKET_SEGMENT) it covers, base
--                                 COMMISSION_FULLY_PAID, commission net of the insurer's
--                                 withholding tax or not, effective dates (values AQ20)
--   * frbs_service_fee_recipient  payee of a sales unit (BDO branch / referrer), with the cost
--                                 centre charged by the accrual (5614 requires one)
--   * frbs_service_fee_run        SFR-<yyyy>-nnnnnn per company and period, workflow FRBS_SERVICE_FEE
--   * frbs_service_fee_line       one line per segment, unit and currency: base, rate, fee, the
--                                 accrual journal, the payout request through the Operations
--                                 DisbursementGateway (type SERVICE_FEE) and the RELEASED /
--                                 LIQUIDATED tags with their dates and liquidation report
--   * frbs_service_fee_item       the fully paid invoices of a line; an invoice is in one live run
--                                 only (uq_frbs_fee_item_live)
--
-- Invoices are referenced by number only (no foreign key to broking tables, design section 4).
-- =====================================================================================

create table frbs_service_fee_rule (
    id              bigint generated by default as identity primary key,
    version         bigint         not null default 0,
    segment         varchar(20)    not null,
    market_segments varchar(200)   not null,
    rate            numeric(9, 4)  not null
        constraint frbs_ck_rule_rate check (rate > 0 and rate <= 100),
    base            varchar(30)    not null default 'COMMISSION_FULLY_PAID'
        constraint frbs_ck_rule_base check (base in ('COMMISSION_FULLY_PAID')),
    net_of_wtax     boolean        not null default true,
    effective_from  date           not null,
    effective_to    date,
    active          boolean        not null default true,
    description     varchar(250),
    created_at      timestamptz    not null,
    created_by      varchar(50)    not null,
    updated_at      timestamptz,
    updated_by      varchar(50),
    constraint frbs_ck_rule_dates check (effective_to is null or effective_to >= effective_from)
);
create index ix_frbs_rule_segment on frbs_service_fee_rule (segment, effective_from);

create table frbs_service_fee_recipient (
    id          bigint generated by default as identity primary key,
    version     bigint        not null default 0,
    company_id  bigint        not null references org_company (id),
    sales_unit  varchar(20)   not null,
    payee_code  varchar(30)   not null,
    payee_name  varchar(250)  not null,
    cost_center varchar(20),
    active      boolean       not null default true,
    created_at  timestamptz   not null,
    created_by  varchar(50)   not null,
    updated_at  timestamptz,
    updated_by  varchar(50),
    constraint frbs_uq_recipient unique (company_id, sales_unit)
);

create table frbs_service_fee_run (
    id            bigint generated by default as identity primary key,
    version       bigint         not null default 0,
    company_id    bigint         not null references org_company (id),
    run_no        varchar(30)    not null,
    period_from   date           not null,
    period_to     date           not null,
    stage         varchar(20)    not null
        constraint frbs_ck_run_stage check (stage in ('COMPUTED', 'FOR_APPROVAL', 'APPROVED', 'RELEASED',
            'LIQUIDATED', 'CANCELLED')),
    invoice_count integer        not null default 0,
    fee_total     numeric(19, 2) not null default 0,
    computed_at   timestamptz    not null,
    submitted_by  varchar(50),
    submitted_at  timestamptz,
    approved_by   varchar(50),
    approved_at   timestamptz,
    created_at    timestamptz    not null,
    created_by    varchar(50)    not null,
    updated_at    timestamptz,
    updated_by    varchar(50),
    constraint frbs_uq_run_no unique (run_no),
    constraint frbs_ck_run_period check (period_to >= period_from)
);
create index ix_frbs_run_company on frbs_service_fee_run (company_id, stage, id);

create table frbs_service_fee_line (
    id               bigint generated by default as identity primary key,
    version          bigint         not null default 0,
    run_id           bigint         not null references frbs_service_fee_run (id),
    line_no          integer        not null,
    segment          varchar(20)    not null,
    sales_unit       varchar(20)    not null,
    payee_code       varchar(30)    not null,
    payee_name       varchar(250)   not null,
    cost_center      varchar(20),
    branch_id        bigint         not null,
    currency         varchar(3)     not null,
    rate             numeric(9, 4)  not null,
    invoice_count    integer        not null,
    commission       numeric(19, 2) not null,
    wtax             numeric(19, 2) not null,
    base             numeric(19, 2) not null,
    fee              numeric(19, 2) not null,
    status           varchar(20)    not null
        constraint frbs_ck_line_status check (status in ('COMPUTED', 'SENT', 'RETURNED', 'RELEASED',
            'LIQUIDATED', 'CANCELLED')),
    accrual_batch_no varchar(40),
    send_count       integer        not null default 0,
    request_no       varchar(30),
    gateway_status   varchar(20),
    dv_no            varchar(40),
    gateway_message  varchar(250),
    released_on      date,
    released_by      varchar(50),
    liquidated_on    date,
    liquidated_by    varchar(50),
    liquidation_ref  varchar(40),
    remarks          varchar(250),
    created_at       timestamptz    not null,
    created_by       varchar(50)    not null,
    updated_at       timestamptz,
    updated_by       varchar(50),
    constraint frbs_uq_line unique (run_id, line_no),
    constraint frbs_ck_line_amounts check (fee >= 0 and base >= 0)
);

create table frbs_service_fee_item (
    id              bigint generated by default as identity primary key,
    run_id          bigint         not null references frbs_service_fee_run (id),
    line_id         bigint         not null references frbs_service_fee_line (id),
    invoice_no      varchar(40)    not null,
    root_invoice_no varchar(40),
    client_code     varchar(30)    not null,
    assured_name    varchar(250)   not null,
    insurer_code    varchar(30)    not null,
    market_segment  varchar(40),
    paid_on         date           not null,
    commission      numeric(19, 2) not null,
    wtax            numeric(19, 2) not null,
    base            numeric(19, 2) not null,
    fee             numeric(19, 2) not null,
    live            boolean        not null default true
);
create unique index uq_frbs_fee_item_live on frbs_service_fee_item (invoice_no) where live;
create index ix_frbs_fee_item_line on frbs_service_fee_item (line_id);

-- ---------- Proposed rules (FRBS 2.10.0, Appendix A VI: 2.5% / 1%; to confirm, AQ20) ------------
insert into frbs_service_fee_rule (segment, market_segments, rate, base, net_of_wtax, effective_from,
    active, description, created_at, created_by) values
    ('CBG', 'CBG,RETAIL', 2.5000, 'COMMISSION_FULLY_PAID', true, date '2020-01-01', true,
     'Consumer banking referrals: 2.5% of fully paid commission net of taxes (AQ20)', now(), 'SYSTEM'),
    ('IBG', 'COMBANK,CORBANK,INSTITUTIONAL', 1.0000, 'COMMISSION_FULLY_PAID', true, date '2020-01-01',
     true, 'Institutional banking referrals: 1% of fully paid commission net of taxes (AQ20)', now(),
     'SYSTEM');
