-- =====================================================================================
-- iNXT BrokerVerse - V899 FRBS report pack catalogue (BRD-5 wave A1-FRBS)
--   FRBS 3.2.0, Appendix A (Comptrollership list of reports) and the FRBS / Government rows of
--   docs/requirements/BDOI_REPORT_LIST.md; docs/architecture/ACCOUNTING_DISBURSEMENT_DESIGN.md
--   sections 10 and 11.
--
--   * frbs_report_pack_entry  the report pack screen (Accounting Reports > Report Pack): the
--                             Appendix A groups in order with their reports (a report code, or the
--                             schedule engine GL-SCHEDULE with a schedule definition of V652), and
--                             whether BDOI asks for a Word document (board decks). Every entry is
--                             viewed and exported to Excel and PDF through the Report Centre.
--   * The FRBS roles read the government reports of the pack: TAX_VIEW is granted to
--     FRBS_PROCESSOR, FRBS_TL and FRBS_HEAD (V890 created the roles; V701 granted TAX_VIEW to the
--     finance roles only).
--
-- The accounting event types FRBS_SERVICE_FEE_ACCRUE and TAX_CWT_CERT_RECEIVED are seeded by V890
-- (design section 17) and are not inserted again.
-- =====================================================================================

create table frbs_report_pack_entry (
    id             bigint generated by default as identity primary key,
    group_code     varchar(20)   not null,
    group_name     varchar(80)   not null,
    group_seq      integer       not null,
    seq            integer       not null,
    report_code    varchar(40)   not null,
    schedule_code  varchar(40),
    title          varchar(200)  not null,
    source_ref     varchar(80),
    word_requested boolean       not null default false,
    constraint frbs_uq_pack_entry unique (group_code, seq)
);

insert into frbs_report_pack_entry (group_code, group_name, group_seq, seq, report_code, schedule_code,
    title, source_ref, word_requested) values
 -- I. End of day
 ('EOD', 'I. End of Day', 1, 1, 'FIN-MIS-BS', null, 'Statement of Condition', 'App. A I; list #1', false),
 ('EOD', 'I. End of Day', 1, 2, 'FIN-MIS-IE', null, 'Income Statement', 'App. A I; list #2', false),
 ('EOD', 'I. End of Day', 1, 3, 'FIN-TB-MAIN', null, 'Trial Balance', 'App. A I; list #3', false),
 ('EOD', 'I. End of Day', 1, 4, 'FIN-GL-DAYBOOK', null, 'Journal Entries', 'App. A I; list #4', false),
 ('EOD', 'I. End of Day', 1, 5, 'FIN-GL-SUBLEDGER-LC', null, 'Subsidiary Ledger', 'App. A I; list #5', false),
 -- II. GARD - BDO Unibank bank format
 ('GARD', 'II. GARD - Bank Format', 2, 1, 'GL-SCHEDULE', 'GARD-CASH', 'Schedule of Cash and Cash Equivalents', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 2, 'GL-SCHEDULE', 'GARD-OPEX', 'Schedule of Operating Expenses', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 3, 'GL-SCHEDULE', 'GARD-OTHER-INCOME', 'Schedule of Other Income', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 4, 'GL-SCHEDULE', 'GARD-FX', 'Schedule of Foreign Exchange Gain / (Loss)', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 5, 'GL-SCHEDULE', 'GARD-MISC-ASSETS', 'Schedule of Miscellaneous Assets', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 6, 'GL-SCHEDULE', 'GARD-ACCRUED', 'Schedule of Accrued Expenses and Taxes Payable', 'App. A II', true),
 ('GARD', 'II. GARD - Bank Format', 2, 7, 'GL-SCHEDULE', 'GARD-VARIANCE-SIE', 'Variance Analysis SIE with Commentary', 'App. A II-45', true),
 -- III. Subsidiaries accounting
 ('SUBS', 'III. Subsidiaries Accounting', 3, 1, 'GL-SCHEDULE', 'SUBS-SIE-YOY', 'FS Analysis SIE - Year on Year', 'App. A III', true),
 ('SUBS', 'III. Subsidiaries Accounting', 3, 2, 'GL-SCHEDULE', 'SUBS-SOC-MOM', 'FS Analysis SOC - Month on Month', 'App. A III', true),
 ('SUBS', 'III. Subsidiaries Accounting', 3, 3, 'GL-BVA', null, 'FS Analysis - Actual vs Budget', 'App. A III', true),
 -- IV. Schedules and aging
 ('SCH', 'IV. Schedules and Aging', 4, 1, 'GL-SCHEDULE', 'SCH-COMMISSION-INCOME', 'Schedule of Commission Income', 'App. A IV; list #9', false),
 ('SCH', 'IV. Schedules and Aging', 4, 2, 'GL-SCHEDULE', 'SCH-PR-PHP', 'Schedule of Receivable from Insurance Companies Clients - Peso', 'App. C; list #45', false),
 ('SCH', 'IV. Schedules and Aging', 4, 3, 'GL-SCHEDULE', 'SCH-PR-USD', 'Schedule of Receivable from Insurance Companies Clients - USD', 'App. C; list #46', false),
 ('SCH', 'IV. Schedules and Aging', 4, 4, 'GL-SCHEDULE', 'SCH-PR-2307', 'Schedule of Premiums Receivable 2307', 'App. A IV-32', false),
 ('SCH', 'IV. Schedules and Aging', 4, 5, 'GL-SCHEDULE', 'SCH-COMM-RECEIVABLE', 'Schedule of Commission Receivables', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 6, 'GL-SCHEDULE', 'SCH-AR-BIR', 'Schedule of AR-BIR', 'App. A IV-6 to IV-8', false),
 ('SCH', 'IV. Schedules and Aging', 4, 7, 'GL-SCHEDULE', 'SCH-AR-BIR-INSURER', 'Schedule of AR-BIR per Insurer', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 8, 'GL-SCHEDULE', 'SCH-AR-INSURER-REFUND', 'Schedule of AR Insurer''s Refund', 'App. C', false),
 ('SCH', 'IV. Schedules and Aging', 4, 9, 'GL-SCHEDULE', 'SCH-AR-OFFICERS', 'Schedule of AR Officers and Employees', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 10, 'GL-SCHEDULE', 'SCH-PREPAID', 'Schedule of Prepaid Expenses', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 11, 'GL-SCHEDULE', 'SCH-FFE', 'Schedule of Furniture, Fixtures and Equipment', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 12, 'GL-SCHEDULE', 'SCH-PAY-INSURERS', 'Schedule of Payable to Insurance Companies', 'App. C', false),
 ('SCH', 'IV. Schedules and Aging', 4, 13, 'GL-SCHEDULE', 'SCH-AP-REFUND-INS', 'Schedule of A/P Refund from Insurer', 'App. C', false),
 ('SCH', 'IV. Schedules and Aging', 4, 14, 'GL-SCHEDULE', 'SCH-AP-OTHERS', 'Schedule of AP - Others Current', 'App. A IV-18/19', false),
 ('SCH', 'IV. Schedules and Aging', 4, 15, 'GL-SCHEDULE', 'SCH-AP-OFFICERS', 'Schedule of AP - Officers and Employees', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 16, 'GL-SCHEDULE', 'SCH-STALE-CHECKS', 'Schedule of Stale Checks', 'App. B', false),
 ('SCH', 'IV. Schedules and Aging', 4, 17, 'GL-SCHEDULE', 'SCH-CHECKS-OUTSTANDING', 'Checks and Other Cash Items', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 18, 'GL-SCHEDULE', 'SCH-SERVICE-FEE-PAYABLE', 'Schedule of Service Fee Payable', 'App. A VI', false),
 ('SCH', 'IV. Schedules and Aging', 4, 19, 'GL-SCHEDULE', 'SCH-EXPENSE-CC', 'Schedule of Expenses per Cost Centre', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 20, 'FRBS-EXPENSE-GROUPING', null, 'Expense Allocation per Cost Centre', 'App. A IV; list #10', false),
 ('SCH', 'IV. Schedules and Aging', 4, 21, 'FRBS-GAP', null, 'GAP Report', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 22, 'FRBS-CASH-FLOW', null, 'Cash Flow Report', 'App. A IV', false),
 ('SCH', 'IV. Schedules and Aging', 4, 23, 'FIN-BRS-STMT', null, 'SA / CA Reconciliation', 'App. A IV; list #11-12', false),
 ('SCH', 'IV. Schedules and Aging', 4, 24, 'GL-FXREV', null, 'Revaluation Report', 'App. A IV; list #14', false),
 -- V. Performance / Mancom
 ('MANCOM', 'V. Performance / Mancom', 5, 1, 'FRBS-MANCOM-MARKET', null, 'Market Performance Summary', 'App. A V; list #15', true),
 ('MANCOM', 'V. Performance / Mancom', 5, 2, 'FRBS-BRANCH-PRODUCTION', null, 'Branch Production - Detailed', 'App. A V; list #16', false),
 ('MANCOM', 'V. Performance / Mancom', 5, 3, 'FRBS-BRANCH-PRODUCTION-SUM', null, 'Branch Production - Summary', 'App. A V; list #16', false),
 ('MANCOM', 'V. Performance / Mancom', 5, 4, 'FRBS-SUSTAINABILITY-PROD', null, 'Sustainability Report - Risk Management', 'List #169', false),
 -- VI. Service fee
 ('FEE', 'VI. Service Fee', 6, 1, 'FRBS-SERVICE-FEE', null, 'Service Fee Report - Summary', 'App. A VI; list #17', false),
 ('FEE', 'VI. Service Fee', 6, 2, 'FRBS-SERVICE-FEE-DETAIL', null, 'Service Fee Report - Details', 'App. A VI; list #17', false),
 -- VII. Government returns, alphalists and books of accounts
 ('GOV', 'VII. Government', 7, 1, 'TAX-VAT-2550Q', null, 'VAT Return 2550-Q', 'App. A VII; list #29', false),
 ('GOV', 'VII. Government', 7, 2, 'TAX-EWT-1601EQ', null, 'Expanded Withholding Tax 1601-EQ', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 3, 'TAX-QAP', null, 'Quarterly Alphalist of Payees', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 4, 'TAX-MAP', null, 'Monthly Alphalist of Payees', 'App. A VII; list #28', false),
 ('GOV', 'VII. Government', 7, 5, 'TAX-1604E', null, 'Annual Information Return 1604-E', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 6, 'TAX-SAWT', null, 'Summary Alphalist of Withholding Taxes', 'App. A VII; list #30', false),
 ('GOV', 'VII. Government', 7, 7, 'TAX-0619F', null, 'Final Withholding Tax Remittance 0619-F', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 8, 'TAX-1603', null, 'Fringe Benefit Tax 1603', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 9, 'TAX-1702Q', null, 'Quarterly Income Tax Return 1702-Q', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 10, 'TAX-1702', null, 'Annual Income Tax Return 1702', 'App. A VII', false),
 ('GOV', 'VII. Government', 7, 11, 'TAX-BOOK-GJ', null, 'Books of Accounts - General Journal', 'App. A VII; list #18', false),
 ('GOV', 'VII. Government', 7, 12, 'TAX-BOOK-PJ', null, 'Books of Accounts - Purchase Journal', 'App. A VII; list #19', false),
 ('GOV', 'VII. Government', 7, 13, 'TAX-BOOK-SJ', null, 'Books of Accounts - Sales Revenue Journal', 'App. A VII; list #20', false),
 ('GOV', 'VII. Government', 7, 14, 'TAX-BOOK-CRB', null, 'Books of Accounts - Cash Receipts', 'App. A VII; list #21', false),
 ('GOV', 'VII. Government', 7, 15, 'TAX-BOOK-CDB', null, 'Books of Accounts - Cash Disbursements', 'App. A VII; list #22', false),
 ('GOV', 'VII. Government', 7, 16, 'TAX-BOOK-SL', null, 'Books of Accounts - General Ledger by Class', 'App. A VII; list #23-27', false),
 ('GOV', 'VII. Government', 7, 17, 'IC-BROKER-ASBO', null, 'Broker''s Annual Statement of Business Operations', 'App. A VII; list #31', false);

-- ---------- Government reports of the pack for the FRBS roles --------------------------------
insert into sec_role_permission (role_id, permission)
select r.id, 'TAX_VIEW'
from sec_role r
where r.code in ('FRBS_PROCESSOR', 'FRBS_TL', 'FRBS_HEAD')
  and not exists (select 1 from sec_role_permission x where x.role_id = r.id and x.permission = 'TAX_VIEW');
