import { useQuery } from '@tanstack/react-query';
import { CHANNEL_STATUS_LABELS, renewalChannelsApi } from '@/api/renewalChannels';
import type { Delivery } from '@/api/renewalChannels';
import { Card } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { UserName } from '@/components/ui/UserName';
import { useCompanyId } from '@/context/workspaceContext';
import { formatDateTime } from '@/utils/format';

/**
 * The deliveries of a renewal account (FRRN.022.01, FRRN.023.02): each document handed to CCM or
 * MFT with its file name, CCM transaction reference, delivery status and who sent it.
 */
export function DeliveriesCard({ renewalRef }: Readonly<{ renewalRef: string }>) {
  const companyId = useCompanyId();
  const rows = useQuery({
    queryKey: ['renewal', 'deliveries', companyId, renewalRef],
    queryFn: () => renewalChannelsApi.deliveries(companyId, renewalRef),
  });
  if (!rows.isLoading && (rows.data ?? []).length === 0 && !rows.error) return null;
  return (
    <Card title="Deliveries" flush>
      <ErrorAlert error={rows.error} />
      <DataTable<Delivery>
        loading={rows.isLoading}
        rows={rows.data ?? []}
        rowKey={(d) => d.messageNo}
        emptyMessage="No delivery"
        columns={[
          { key: 'file', header: 'File Name', render: (d) => d.fileName ?? d.docKind },
          { key: 'channel', header: 'Channel', render: (d) => d.channel },
          {
            key: 'status',
            header: 'Delivery Status',
            kind: 'status',
            render: (d) => (
              <StatusBadge
                status={d.status}
                label={CHANNEL_STATUS_LABELS[d.status] ?? d.statusLabel}
              />
            ),
          },
          { key: 'ref', header: 'CCM Transaction Reference', render: (d) => d.externalRef ?? '' },
          {
            key: 'queued',
            header: 'Generated',
            kind: 'datetime',
            render: (d) => formatDateTime(d.queuedAt),
          },
          {
            key: 'sent',
            header: 'Sent',
            kind: 'datetime',
            render: (d) => formatDateTime(d.sentAt),
          },
          { key: 'by', header: 'Generated By', render: (d) => <UserName login={d.queuedBy} /> },
          { key: 'error', header: 'Error', render: (d) => d.error ?? '' },
        ]}
      />
    </Card>
  );
}
