import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileSpreadsheet } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { saveFile } from '@/api/client';
import { pmPlacementApi } from '@/api/pmPlacement';
import type { PlacementReport } from '@/api/pmPlacement';
import { useAuth } from '@/auth/authContext';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { DataTable } from '@/components/ui/DataTable';
import type { Column } from '@/components/ui/DataTable';
import { DefinitionGrid } from '@/components/ui/DefinitionGrid';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { PageHeader } from '@/components/ui/PageHeader';
import { PageFooter } from '@/components/ui/Pager';
import { RowActionMenu } from '@/components/ui/RowActionMenu';
import { useToast } from '@/components/ui/toastContext';
import { useCompanyId } from '@/context/workspaceContext';
import { formatDate, formatDateTime } from '@/utils/format';
import { PlacementPreviewDialog } from './PlacementPreviewDialog';
import { nextRunText, scheduleText } from './placementView';

/**
 * The repository of the Consolidated Placement Update Report (BDOI FRS FRPM.007.01): the reports
 * generated on the weekly schedule or on request, with File Name, Report Date, Reporting Period,
 * Generated Date/Time, Generated By and Records; each can be previewed and downloaded again.
 */
export default function PlacementReportsPage() {
  const companyId = useCompanyId();
  const { can } = useAuth();
  const toast = useToast();
  const queryClient = useQueryClient();
  const [page, setPage] = useState(0);
  const [previewId, setPreviewId] = useState<number | null>(null);
  const settings = useQuery({
    queryKey: ['pm-placement', 'settings'],
    queryFn: () => pmPlacementApi.settings(),
  });
  const reports = useQuery({
    queryKey: ['pm-placement', companyId, page],
    queryFn: () => pmPlacementApi.list(companyId, page),
  });
  const generate = useMutation({
    mutationFn: () => pmPlacementApi.generate(companyId),
    onSuccess: async (made) => {
      toast.success(`${made.fileName} generated with ${made.recordCount} request(s)`);
      await queryClient.invalidateQueries({ queryKey: ['pm-placement', companyId] });
    },
  });
  const download = useMutation({
    mutationFn: (id: number) => pmPlacementApi.file(id),
    onSuccess: (file) => saveFile(file.blob, file.fileName),
  });
  const columns: Column<PlacementReport>[] = [
    { key: 'file', header: 'File Name', render: (r) => r.fileName },
    { key: 'date', header: 'Report Date', render: (r) => formatDate(r.reportDate) },
    {
      key: 'period',
      header: 'Reporting Period',
      render: (r) => `${formatDate(r.periodFrom)} to ${formatDate(r.periodTo)}`,
    },
    { key: 'at', header: 'Generated Date/Time', render: (r) => formatDateTime(r.generatedAt) },
    { key: 'by', header: 'Generated By', render: (r) => r.generatedBy },
    { key: 'trigger', header: 'Run', render: (r) => r.trigger },
    { key: 'records', header: 'Records', numeric: true, render: (r) => r.recordCount },
    {
      key: 'actions',
      header: 'Actions',
      render: (r) => (
        <RowActionMenu
          label={r.fileName}
          actions={[
            { label: 'Preview', onSelect: () => setPreviewId(r.id) },
            { label: 'Download', onSelect: () => download.mutate(r.id) },
          ]}
        />
      ),
    },
  ];
  return (
    <div className="page">
      <PageHeader
        section="Product Maintenance"
        title="Placement Update Reports"
        description="Consolidated Placement Update Report of the quotation requests, generated weekly."
        actions={
          <>
            <Link className="btn btn-secondary" to="/reports/PM-REPORT-BUILDER">
              Report Builder
            </Link>
            {can('PKG_REPORT_VIEW') && (
              <Button
                icon={<FileSpreadsheet size={16} />}
                busy={generate.isPending}
                onClick={() => generate.mutate()}
              >
                Generate Now
              </Button>
            )}
          </>
        }
      />
      <ErrorAlert error={settings.error ?? reports.error ?? generate.error ?? download.error} />
      {settings.data && (
        <Card title="Schedule">
          <DefinitionGrid
            items={[
              { label: 'Schedule', value: scheduleText(settings.data) },
              { label: 'Next Run', value: nextRunText(settings.data) },
              {
                label: 'Scope',
                value:
                  settings.data.scope === 'QUOTATION'
                    ? 'Quotation requests'
                    : 'Quotation and package requests',
              },
            ]}
          />
        </Card>
      )}
      <Card title="Repository" flush>
        <DataTable
          columns={columns}
          rows={reports.data?.content ?? []}
          rowKey={(r) => r.id}
          loading={reports.isLoading}
          emptyMessage="No Placement Update Report has been generated yet"
        />
        <PageFooter data={reports.data} noun="reports" onPage={setPage} />
      </Card>
      {previewId !== null && (
        <PlacementPreviewDialog id={previewId} onClose={() => setPreviewId(null)} />
      )}
    </div>
  );
}
