import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { recurringApi } from '@/api/journalAutomation';
import type { Occurrence } from '@/api/journalAutomation';
import { DataTable } from '@/components/ui/DataTable';
import { ErrorAlert } from '@/components/ui/ErrorAlert';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { formatDate, formatDateTime } from '@/utils/format';

/** Generation history of a template: one row per occurrence with links to its journals. */
export function RecurringHistory({ templateId }: Readonly<{ templateId: number }>) {
  const history = useQuery({
    queryKey: ['recurring', templateId, 'occurrences'],
    queryFn: () => recurringApi.occurrences(templateId),
  });
  return (
    <>
      <ErrorAlert error={history.error} />
      <DataTable<Occurrence>
        loading={history.isLoading}
        rows={history.data ?? []}
        rowKey={(o) => o.occurrenceDate}
        emptyMessage="No journals generated yet."
        columns={[
          { key: 'd', header: 'Occurrence', render: (o) => formatDate(o.occurrenceDate) },
          {
            key: 'j',
            header: 'Journal',
            render: (o) => <Link to={`/gl/journals/${o.batchId}`}>{o.batchNo ?? o.batchId}</Link>,
          },
          {
            key: 's',
            header: 'Status',
            render: (o) =>
              o.batchStatus === undefined ? '' : <StatusBadge status={o.batchStatus} />,
          },
          {
            key: 'r',
            header: 'Reversal',
            render: (o) =>
              o.reversalBatchId === undefined ? (
                ''
              ) : (
                <Link to={`/gl/journals/${o.reversalBatchId}`}>{o.reversalBatchNo}</Link>
              ),
          },
          { key: 'b', header: 'Generated by', render: (o) => o.generatedBy },
          { key: 't', header: 'Generated', render: (o) => formatDateTime(o.generatedAt) },
        ]}
      />
    </>
  );
}
