// BIBS screenshot manifest, in sidebar order. The capture script numbers the files from this order,
// so add or move a screen here and every file is renumbered on the next run (old files are deleted).
// Fields: slug (file name), title, user (demo user, password Brokerverse@2026), path (route), and
// optional `open` ('first' opens the first record of the list at `path`), `click` (button name regex
// clicked after loading, e.g. to open a modal or run a report).
module.exports = [
  { slug: 'login', title: 'Sign in', user: null, path: '/login' },
  // Home
  { slug: 'nb-dashboard', title: 'New Business Dashboard (landing page)', user: 'mkttl', path: '/nb/dashboard' },
  { slug: 'my-work', title: 'My Work', user: 'ao', path: '/my-work' },
  // Client & Policy
  { slug: 'clients', title: 'Clients work list', user: 'ao', path: '/crm/clients' },
  { slug: 'client-record', title: 'Client record', user: 'ao', path: '/crm/clients', open: 'first' },
  { slug: 'new-client', title: 'New Client', user: 'ao', path: '/crm/clients/new' },
  { slug: 'kyc-reviews', title: 'KYC Reviews Due', user: 'ao', path: '/crm/kyc-reviews' },
  { slug: 'quotations', title: 'Quotations work list', user: 'ao', path: '/quotations' },
  { slug: 'quotation-record', title: 'Quotation record', user: 'ao', path: '/quotations', open: 'first' },
  { slug: 'new-quotation', title: 'New Quotation wizard', user: 'ao', path: '/quotations/new' },
  { slug: 'quotation-requests', title: 'Quotation Requests', user: 'ao', path: '/quotations/requests' },
  { slug: 'accounts', title: 'Accounts work list', user: 'ao', path: '/accounts' },
  { slug: 'account-record', title: 'Account record', user: 'ao', path: '/accounts', open: 'first' },
  { slug: 'new-account', title: 'New Account wizard', user: 'ao', path: '/accounts/new' },
  { slug: 'ffy-register', title: 'FFY Register', user: 'ao', path: '/accounts/ffy' },
  { slug: 'direct-payment', title: 'Direct Payment', user: 'ao', path: '/accounts/direct-payment' },
  { slug: 'proposal-requests', title: 'Proposal Requests', user: 'ao', path: '/proposals' },
  { slug: 'proposal-record', title: 'Proposal Request record', user: 'ao', path: '/proposals', open: 'first' },
  { slug: 'tsu-workbench', title: 'TSU Workbench', user: 'tsu', path: '/proposals/tsu' },
  { slug: 'placement-workbench', title: 'Placement Workbench', user: 'proc', path: '/placement' },
  { slug: 'placement-slips', title: 'Placement Slips', user: 'proc', path: '/placement/slips' },
  { slug: 'clpc-billing', title: 'CLPC Billing', user: 'proc', path: '/placement/billing' },
  { slug: 'issuance-workbench', title: 'Issuance Workbench', user: 'proc', path: '/issuance' },
  { slug: 'epolicy-upload', title: 'E-policy Upload', user: 'proc', path: '/issuance/upload' },
  { slug: 'insurance-advice', title: 'Insurance Advice', user: 'proc', path: '/issuance/insurance-advice' },
  { slug: 'epolicy-dispatch', title: 'E-policy Dispatch', user: 'epol', path: '/issuance/dispatch' },
  { slug: 'booking-workbench', title: 'Booking Workbench', user: 'proc', path: '/booking' },
  { slug: 'endorsements', title: 'Endorsements', user: 'adjust', path: '/booking/endorsements' },
  { slug: 'service-invoices', title: 'Service Invoices', user: 'proc', path: '/booking/service-invoices' },
  { slug: 'batch-runs', title: 'Batch Runs', user: 'proc', path: '/booking/batch-runs' },
  { slug: 'booking-setup', title: 'Booking Setup', user: 'proc', path: '/booking/setup' },
  { slug: 'adjustment-workbench', title: 'Adjustment Workbench', user: 'adjtl', path: '/adjustment' },
  { slug: 'adjustment-request', title: 'Endorsement Request record', user: 'adjtl', path: '/adjustment', open: 'first' },
  { slug: 'adjustment-new', title: 'New Adjustment Request', user: 'adjtl', path: '/adjustment/new' },
  { slug: 'adjustment-batches', title: 'Adjustment Posting Batches', user: 'adjtl', path: '/adjustment/batches' },
  { slug: 'products', title: 'Products', user: 'badmin', path: '/catalog/products' },
  { slug: 'insurers', title: 'Insurers', user: 'badmin', path: '/catalog/insurers' },
  { slug: 'rates-taxes', title: 'Rates & Taxes', user: 'badmin', path: '/catalog/rates' },
  { slug: 'sales-organisation', title: 'Sales Organisation', user: 'badmin', path: '/catalog/sales-organisation' },
  { slug: 'premium-calculator', title: 'Premium Calculator', user: 'ao', path: '/catalog/calculator' },
  { slug: 'bulk-processing', title: 'Bulk Processing', user: 'ao', path: '/bulk' },
  // Operations
  { slug: 'operations-home', title: 'Operations Home', user: 'remittl', path: '/operations' },
  { slug: 'invoice-search', title: 'Invoice Search', user: 'remittl', path: '/operations/invoices' },
  { slug: 'invoice-360', title: 'Invoice 360', user: 'remittl', path: '/operations/invoices', open: 'first' },
  { slug: 'disbursement-queue', title: 'Disbursement Queue', user: 'disb', path: '/operations/disbursements' },
  // Finance
  { slug: 'remittance-workbench', title: 'Remittance Workbench', user: 'remittl', path: '/remittance' },
  { slug: 'remittance-batches', title: 'Remittance Batches', user: 'remittl', path: '/remittance/batches' },
  { slug: 'remittance-batch', title: 'Remittance Batch record', user: 'remittl', path: '/remittance/batches', open: 'first' },
  { slug: 'remittance-holds', title: 'Remittance Holds', user: 'remittl', path: '/remittance/holds' },
  { slug: 'dtip-status', title: 'DTIP Status', user: 'remittl', path: '/remittance/dtip' },
  { slug: 'finance-dashboard', title: 'Finance executive dashboard', user: 'fmanager', path: '/' },
  { slug: 'gl-journals', title: 'GL Journals', user: 'fmanager', path: '/gl/journals' },
  // Reports
  { slug: 'nb-reports', title: 'New Business Reports', user: 'mkttl', path: '/nb/reports' },
  { slug: 'report-account-status', title: 'Account Status Report (run on screen)', user: 'mkttl', path: '/reports/NB-ACC-STATUS', click: '^run report$' },
  { slug: 'production-targets', title: 'Production Targets', user: 'badmin', path: '/nb/targets' },
  { slug: 'report-centre', title: 'Report Centre', user: 'mkttl', path: '/reports' },
  // Setup & Administration
  { slug: 'lists-of-values', title: 'Lists of Values', user: 'badmin', path: '/broking-setup/lists' },
  { slug: 'access-requests', title: 'Access Requests', user: 'badmin', path: '/broking-setup/access-requests' },
  { slug: 'access-request-modal', title: 'Modal (New Access Request)', user: 'badmin', path: '/broking-setup/access-requests', click: 'new request' },
  { slug: 'access-matrix', title: 'User Access Matrix', user: 'approver', path: '/broking-setup/access-matrix' },
  { slug: 'data-retention', title: 'Data Retention', user: 'approver', path: '/broking-setup/retention' },
  { slug: 'document-templates', title: 'Document Templates', user: 'approver', path: '/broking-setup/templates' },
  { slug: 'message-log', title: 'Message Log', user: 'badmin', path: '/broking-setup/messages' },
];
