// BIBS screenshot manifest, in sidebar order. The capture script numbers the files from this order,
// so add or move a screen here and every file is renumbered on the next run (old files are deleted).
// Fields: slug (file name), title, user (demo user, password Brokerverse@2026), path (route), and
// optional `open` ('first' opens the first record of the list at `path`), `click` (button name regex
// clicked after loading, e.g. to open a modal or run a report).
module.exports = [
  { slug: 'login', title: 'Sign in', user: null, path: '/login' },
  // Home
  { slug: 'nb-dashboard', title: 'New Business Dashboard (landing page)', user: 'mkttl', path: '/nb/dashboard' },
  { slug: 'my-work', title: 'My Work', user: 'ao', path: '/my-work' },
  // Client & Policy
  { slug: 'clients', title: 'Clients work list', user: 'ao', path: '/crm/clients' },
  { slug: 'client-record', title: 'Client record', user: 'ao', path: '/crm/clients', open: 'first' },
  { slug: 'new-client', title: 'New Client', user: 'ao', path: '/crm/clients/new' },
  { slug: 'kyc-reviews', title: 'KYC Reviews Due', user: 'ao', path: '/crm/kyc-reviews' },
  { slug: 'quotations', title: 'Quotations work list', user: 'ao', path: '/quotations' },
  { slug: 'quotation-record', title: 'Quotation record', user: 'ao', path: '/quotations', open: 'first' },
  { slug: 'new-quotation', title: 'New Quotation wizard', user: 'ao', path: '/quotations/new' },
  { slug: 'quotation-requests', title: 'Quotation Requests', user: 'ao', path: '/quotations/requests' },
  { slug: 'accounts', title: 'Accounts work list', user: 'ao', path: '/accounts' },
  { slug: 'account-record', title: 'Account record', user: 'ao', path: '/accounts', open: 'first' },
  { slug: 'new-account', title: 'New Account wizard', user: 'ao', path: '/accounts/new' },
  { slug: 'ffy-register', title: 'FFY Register', user: 'ao', path: '/accounts/ffy' },
  { slug: 'direct-payment', title: 'Direct Payment', user: 'ao', path: '/accounts/direct-payment' },
  { slug: 'proposal-requests', title: 'Proposal Requests', user: 'ao', path: '/proposals' },
  { slug: 'proposal-record', title: 'Proposal Request record', user: 'ao', path: '/proposals', open: 'first' },
  { slug: 'tsu-workbench', title: 'TSU Workbench', user: 'tsu', path: '/proposals/tsu' },
  { slug: 'placement-workbench', title: 'Placement Workbench', user: 'proc', path: '/placement' },
  { slug: 'placement-slips', title: 'Placement Slips', user: 'proc', path: '/placement/slips' },
  { slug: 'clpc-billing', title: 'CLPC Billing', user: 'proc', path: '/placement/billing' },
  { slug: 'issuance-workbench', title: 'Issuance Workbench', user: 'proc', path: '/issuance' },
  { slug: 'epolicy-upload', title: 'E-policy Upload', user: 'proc', path: '/issuance/upload' },
  { slug: 'insurance-advice', title: 'Insurance Advice', user: 'proc', path: '/issuance/insurance-advice' },
  { slug: 'epolicy-dispatch', title: 'E-policy Dispatch', user: 'epol', path: '/issuance/dispatch' },
  { slug: 'booking-workbench', title: 'Booking Workbench', user: 'proc', path: '/booking' },
  { slug: 'endorsements', title: 'Endorsements', user: 'adjust', path: '/booking/endorsements' },
  { slug: 'service-invoices', title: 'Service Invoices', user: 'proc', path: '/booking/service-invoices' },
  { slug: 'batch-runs', title: 'Batch Runs', user: 'proc', path: '/booking/batch-runs' },
  { slug: 'booking-setup', title: 'Booking Setup', user: 'proc', path: '/booking/setup' },
  { slug: 'adjustment-workbench', title: 'Adjustment Workbench', user: 'adjtl', path: '/adjustment' },
  { slug: 'adjustment-request', title: 'Endorsement Request record', user: 'adjtl', path: '/adjustment', open: 'first' },
  { slug: 'adjustment-new', title: 'New Adjustment Request', user: 'adjtl', path: '/adjustment/new' },
  { slug: 'adjustment-batches', title: 'Adjustment Posting Batches', user: 'adjtl', path: '/adjustment/batches' },
  { slug: 'prodrecon-workbench', title: 'Reconciliation Workbench', user: 'recon', path: '/prodrecon' },
  { slug: 'prodrecon-cycles', title: 'Reconciliation Cycles', user: 'recon', path: '/prodrecon/cycles' },
  { slug: 'prodrecon-cycle', title: 'Reconciliation Cycle record', user: 'recon', path: '/prodrecon/cycles', open: 'first' },
  { slug: 'prodrecon-extracts', title: 'Production Extracts', user: 'recon', path: '/prodrecon/extracts' },
  { slug: 'prodrecon-uploads', title: 'Insurer Feedback', user: 'recon', path: '/prodrecon/uploads' },
  { slug: 'prodrecon-unbooked', title: 'Unbooked Accounts', user: 'recon', path: '/prodrecon/unbooked' },
  { slug: 'product-maintenance-home', title: 'Product Maintenance Home', user: 'tsuhead', path: '/product-maintenance' },
  { slug: 'package-requests', title: 'Package Requests', user: 'tsu', path: '/product-maintenance/requests?tab=negotiation' },
  { slug: 'package-request', title: 'Package Request record', user: 'tsu', path: '/product-maintenance/requests?tab=negotiation', open: 'first' },
  { slug: 'package-request-new', title: 'New Package Request', user: 'ao', path: '/product-maintenance/requests/new' },
  { slug: 'package-tsu-workbench', title: 'TSU Workbench (packages)', user: 'tsulead', path: '/product-maintenance/tsu' },
  { slug: 'package-expiry', title: 'Package Expiry', user: 'tsu', path: '/product-maintenance/expiry' },
  { slug: 'products', title: 'Products', user: 'badmin', path: '/catalog/products' },
  { slug: 'product-record', title: 'Product record with versions', user: 'mbs', path: '/catalog/products/MTR12' },
  { slug: 'package-version', title: 'Package version editor', user: 'mbs', path: '/catalog/products/MTR12/versions/2' },
  { slug: 'validation-queue', title: 'Validation Queue', user: 'tsuhead', path: '/catalog/validation' },
  { slug: 'coverages-clauses', title: 'Coverages & Clauses', user: 'mbs', path: '/catalog/coverages' },
  { slug: 'incentive-criteria', title: 'Incentive Criteria', user: 'mbs', path: '/catalog/incentives' },
  { slug: 'insurers', title: 'Insurers', user: 'badmin', path: '/catalog/insurers' },
  { slug: 'rates-taxes', title: 'Rates & Taxes', user: 'badmin', path: '/catalog/rates' },
  { slug: 'sales-organisation', title: 'Sales Organisation', user: 'badmin', path: '/catalog/sales-organisation' },
  { slug: 'premium-calculator', title: 'Premium Calculator', user: 'ao', path: '/catalog/calculator' },
  { slug: 'bulk-processing', title: 'Bulk Processing', user: 'ao', path: '/bulk' },
  // Operations
  { slug: 'operations-home', title: 'Operations Home', user: 'remittl', path: '/operations' },
  { slug: 'invoice-search', title: 'Invoice Search', user: 'remittl', path: '/operations/invoices' },
  { slug: 'invoice-360', title: 'Invoice 360', user: 'remittl', path: '/operations/invoices', open: 'first' },
  { slug: 'disbursement-queue', title: 'Disbursement Queue', user: 'disb', path: '/operations/disbursements' },
  { slug: 'ops-interfaces', title: 'Interfaces (flow-in runs)', user: 'admin', path: '/operations/interfaces' },
  // Finance
  { slug: 'cashiering-workbench', title: 'Cashiering Workbench', user: 'cashier', path: '/cashiering' },
  { slug: 'receive-payment', title: 'Receive Payment', user: 'cashier', path: '/cashiering/receive' },
  { slug: 'cash-receipts', title: 'Receipts', user: 'cashier', path: '/cashiering/receipts' },
  { slug: 'cash-receipt', title: 'Receipt record', user: 'cashier', path: '/cashiering/receipts', open: 'first' },
  { slug: 'unapplied-payments', title: 'Unapplied Payments', user: 'cashtl', path: '/cashiering/unapplied' },
  { slug: 'unapplied-payment', title: 'Unapplied Payment record', user: 'cashtl', path: '/cashiering/unapplied', open: 'first' },
  { slug: 'prebooked-payments', title: 'Pre-booked Payments', user: 'cashier', path: '/cashiering/prebooked' },
  { slug: 'payment-uploads', title: 'Payment Uploads', user: 'cashier', path: '/cashiering/uploads' },
  { slug: 'pdc-warehouse', title: 'PDC Warehouse', user: 'cashier', path: '/cashiering/pdc' },
  { slug: 'check-pickup', title: 'Check Pick-up', user: 'cashier', path: '/cashiering/pickups' },
  { slug: 'bir-2307', title: 'BIR 2307', user: 'cashtl', path: '/cashiering/cwt' },
  { slug: 'receipt-series', title: 'Receipt Series', user: 'cashtl', path: '/cashiering/series' },
  { slug: 'remittance-workbench', title: 'Remittance Workbench', user: 'remittl', path: '/remittance' },
  { slug: 'remittance-extraction', title: 'Remittance Extraction', user: 'remit', path: '/remittance/extraction' },
  { slug: 'remittance-batches', title: 'Remittance Batches', user: 'remittl', path: '/remittance/batches' },
  { slug: 'remittance-batch', title: 'Remittance Batch record', user: 'remittl', path: '/remittance/batches', open: 'first' },
  { slug: 'remittance-insurer-or', title: 'Insurer OR Upload', user: 'remit', path: '/remittance/insurer-or' },
  { slug: 'remittance-holds', title: 'Remittance Holds', user: 'remittl', path: '/remittance/holds' },
  { slug: 'remittance-hold', title: 'Hold Request record', user: 'remittl', path: '/remittance/holds', open: 'first' },
  { slug: 'dtip-status', title: 'DTIP Status', user: 'remittl', path: '/remittance/dtip' },
  { slug: 'commission-workbench', title: 'Commission Workbench', user: 'commrec', path: '/commission' },
  { slug: 'commission-dp-lists', title: 'DP Lists', user: 'commrec', path: '/commission/dp/lists' },
  { slug: 'commission-dp-items', title: 'DP Accounts', user: 'commrec', path: '/commission/dp/items' },
  { slug: 'commission-dp-billings', title: 'DP Billings', user: 'commrec', path: '/commission/dp/billings' },
  { slug: 'commission-dp-billing', title: 'DP Billing record', user: 'commrec', path: '/commission/dp/billings', open: 'first' },
  { slug: 'commission-incentive-schemes', title: 'Incentive Schemes', user: 'commtl', path: '/commission/incentives/schemes' },
  { slug: 'commission-certificates', title: 'BIR Certificates', user: 'commrec', path: '/commission/certificates' },
  { slug: 'finance-dashboard', title: 'Finance executive dashboard', user: 'fmanager', path: '/' },
  { slug: 'gl-journals', title: 'GL Journals', user: 'fmanager', path: '/gl/journals' },
  { slug: 'gl-chart-upload', title: 'Chart Upload & Numbering (GL Team Lead)', user: 'gltl', path: '/gl/accounts/upload' },
  { slug: 'gl-close', title: 'GL Close & Cut-Off (GL Team Lead)', user: 'gltl', path: '/planning/gl-close' },
  // Reports
  { slug: 'nb-reports', title: 'New Business Reports', user: 'mkttl', path: '/nb/reports' },
  { slug: 'report-account-status', title: 'Account Status Report (run on screen)', user: 'mkttl', path: '/reports/NB-ACC-STATUS', click: '^run report$' },
  { slug: 'production-targets', title: 'Production Targets', user: 'badmin', path: '/nb/targets' },
  { slug: 'report-centre', title: 'Report Centre', user: 'mkttl', path: '/reports' },
  { slug: 'report-batch', title: 'Modal (Report Batch)', user: 'gltl', path: '/reports', click: '^report batch$' },
  // Setup & Administration
  { slug: 'lists-of-values', title: 'Lists of Values', user: 'badmin', path: '/broking-setup/lists' },
  { slug: 'access-requests', title: 'Access Requests', user: 'badmin', path: '/broking-setup/access-requests' },
  { slug: 'access-request-modal', title: 'Modal (New Access Request)', user: 'badmin', path: '/broking-setup/access-requests', click: 'new request' },
  { slug: 'access-matrix', title: 'User Access Matrix', user: 'approver', path: '/broking-setup/access-matrix' },
  { slug: 'data-retention', title: 'Data Retention', user: 'approver', path: '/broking-setup/retention' },
  { slug: 'document-templates', title: 'Document Templates', user: 'approver', path: '/broking-setup/templates' },
  { slug: 'message-log', title: 'Message Log', user: 'badmin', path: '/broking-setup/messages' },
  { slug: 'employees', title: 'Employees', user: 'fmanager', path: '/setup/employees' },
  { slug: 'cost-centre-rules', title: 'Cost-Centre Rules', user: 'fmanager', path: '/setup/cost-centre-rules' },
];
