-- =====================================================================================
-- iNXT BrokerVerse - V985 Seed non-package proposals (seed profile only): five PRFs of the V981
-- clients - a draft, one waiting for Marketing approval, one in the TSU queue, one with three
-- insurer responses (two terms, one declined) and its comparative table, and one accepted by the
-- client after its proposal slip - with consistent NB_PROPOSAL work cases and status history.
--   Numbers PRF-2026-9000nn, ARN-2026-9200nn, QS-2026-9000nn, PS-2026-9000nn.
-- =============================================================================================

-- PRF-2026-900001 CAR00 Pacific Harbor Logistics Inc.: DRAFT
insert into npk_proposal (company_id, prf_no, arn, client_id, client_code, client_name, client_email, product_code, line_code, market_segment, source_channel, period_from, period_to, currency, risk_details, total_sum_insured, tsu_rule, tsu_reason, status, submitted_by, submitted_at, approved_by, approved_at, qs_no, qs_template, qs_reply_by, qs_submitted_by, qs_approved_by, qs_sent_at, terms_closed, chosen_insurer, ps_no, ps_version, ps_submitted_by, ps_approved_by, sent_at, accepted_at, accepted_groups, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PRF-2026-900001', 'ARN-2026-920001', (select id from crm_client where client_code = 'CL-2026-000003'), 'CL-2026-000003', 'Pacific Harbor Logistics Inc.', 'treasury@pacificharbor.example', 'CAR00', 'ENGINEERING', 'CORBANK', 'EMAIL', date '2026-11-15', date '2027-11-15', 'PHP', '{"sections": [{"heading": "Project", "text": "Two-storey warehouse extension with mezzanine, steel frame, 14-month build"}, {"heading": "Contractor", "text": "Harbor Build Corp., 20 years in industrial works"}], "items": [{"riskGroup": 1, "data": {"description": "Contract works - warehouse extension, Pier 4", "sumInsured": 30000000, "rate": 0.35, "biLimit": null, "pdLimit": null, "vehicle": null, "location": null, "person": null}}]}', 30000000, 'NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'DRAFT', null, null, null, null, null, null, null, null, null, null, false, null, null, 0, null, null, null, null, null, timestamptz '2026-09-22T09:00:00+08', 'ao2');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900001'), 0, 'INS-MGIC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900001'), 1, 'INS-LAC');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'NB_PROPOSAL', 'ProposalRequest', (select id from npk_proposal where prf_no = 'PRF-2026-900001')::text, 'PRF-2026-900001', 'Pacific Harbor Logistics Inc. - CAR00', '/proposals/' || (select id from npk_proposal where prf_no = 'PRF-2026-900001'), 'CORBANK', 'DRAFT', timestamptz '2026-09-22T09:00:00+08', timestamptz '2026-09-23T09:00:00+08', 'ao2', false, timestamptz '2026-09-22T09:00:00+08', 'ao2');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900001'), null, 'DRAFT', 'start', null, null, 'ao2', false, timestamptz '2026-09-22T09:00:00+08');

-- PRF-2026-900002 EEI01 Luzon Agri-Industrial Corp.: FOR_MKT_APPROVAL
insert into npk_proposal (company_id, prf_no, arn, client_id, client_code, client_name, client_email, product_code, line_code, market_segment, source_channel, period_from, period_to, currency, risk_details, total_sum_insured, tsu_rule, tsu_reason, status, submitted_by, submitted_at, approved_by, approved_at, qs_no, qs_template, qs_reply_by, qs_submitted_by, qs_approved_by, qs_sent_at, terms_closed, chosen_insurer, ps_no, ps_version, ps_submitted_by, ps_approved_by, sent_at, accepted_at, accepted_groups, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PRF-2026-900002', 'ARN-2026-920002', (select id from crm_client where client_code = 'CL-2026-000004'), 'CL-2026-000004', 'Luzon Agri-Industrial Corp.', 'finance@luzonagri.example', 'EEI01', 'ELECTRONIC_EQUIPMENT', 'COMBANK', 'EMAIL', date '2026-10-15', date '2027-10-15', 'PHP', '{"sections": [{"heading": "Equipment", "text": "Process control systems and laboratory analysers of the feed mill"}, {"heading": "Loss history", "text": "No claims in the last 3 years"}], "items": [{"riskGroup": 1, "data": {"description": "Process control system and lab analysers, Santo Tomas plant", "sumInsured": 12000000, "rate": 0.5, "biLimit": null, "pdLimit": null, "vehicle": null, "location": null, "person": null}}]}', 12000000, 'NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'FOR_MKT_APPROVAL', 'ao2', timestamptz '2026-09-22T14:00:00+08', null, null, null, null, null, null, null, null, false, null, null, 0, null, null, null, null, null, timestamptz '2026-09-19T09:00:00+08', 'ao2');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900002'), 0, 'INS-MGIC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900002'), 1, 'INS-MPI');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'NB_PROPOSAL', 'ProposalRequest', (select id from npk_proposal where prf_no = 'PRF-2026-900002')::text, 'PRF-2026-900002', 'Luzon Agri-Industrial Corp. - EEI01', '/proposals/' || (select id from npk_proposal where prf_no = 'PRF-2026-900002'), 'COMBANK', 'FOR_MKT_APPROVAL', timestamptz '2026-09-22T14:00:00+08', timestamptz '2026-09-22T22:00:00+08', null, false, timestamptz '2026-09-19T09:00:00+08', 'ao2');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900002'), null, 'DRAFT', 'start', null, null, 'ao2', false, timestamptz '2026-09-19T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900002'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao2', false, timestamptz '2026-09-22T14:00:00+08');

-- PRF-2026-900003 CAR00 Bayside Builders Co.: WITH_TSU
insert into npk_proposal (company_id, prf_no, arn, client_id, client_code, client_name, client_email, product_code, line_code, market_segment, source_channel, period_from, period_to, currency, risk_details, total_sum_insured, tsu_rule, tsu_reason, status, submitted_by, submitted_at, approved_by, approved_at, qs_no, qs_template, qs_reply_by, qs_submitted_by, qs_approved_by, qs_sent_at, terms_closed, chosen_insurer, ps_no, ps_version, ps_submitted_by, ps_approved_by, sent_at, accepted_at, accepted_groups, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PRF-2026-900003', 'ARN-2026-920003', (select id from crm_client where prospect_code = 'PR-2026-000008'), 'PR-2026-000008', 'Bayside Builders Co.', 'admin@baysidebuilders.example', 'CAR00', 'ENGINEERING', 'COMBANK', 'EMAIL', date '2026-10-20', date '2027-12-20', 'PHP', '{"sections": [{"heading": "Project", "text": "Six-storey residential building, Paranaque, 26-month build"}, {"heading": "Requested cover", "text": "CAR with third-party liability of PHP 5,000,000"}], "items": [{"riskGroup": 1, "data": {"description": "Contract works - six-storey residential building", "sumInsured": 45000000, "rate": 0.35, "biLimit": null, "pdLimit": null, "vehicle": null, "location": null, "person": null}}]}', 45000000, 'NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'WITH_TSU', 'ao', timestamptz '2026-09-16T09:00:00+08', 'mkttl', timestamptz '2026-09-23T09:00:00+08', null, null, null, null, null, null, false, null, null, 0, null, null, null, null, null, timestamptz '2026-09-15T09:00:00+08', 'ao');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900003'), 0, 'INS-LAC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900003'), 1, 'INS-VMI');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900003'), 2, 'INS-MGIC');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'NB_PROPOSAL', 'ProposalRequest', (select id from npk_proposal where prf_no = 'PRF-2026-900003')::text, 'PRF-2026-900003', 'Bayside Builders Co. - CAR00', '/proposals/' || (select id from npk_proposal where prf_no = 'PRF-2026-900003'), 'COMBANK', 'WITH_TSU', timestamptz '2026-09-23T09:00:00+08', timestamptz '2026-09-23T17:00:00+08', null, false, timestamptz '2026-09-15T09:00:00+08', 'ao');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900003'), null, 'DRAFT', 'start', null, null, 'ao', false, timestamptz '2026-09-15T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900003'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao', false, timestamptz '2026-09-16T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900003'), 'FOR_MKT_APPROVAL', 'WITH_TSU', 'approve', null, 'Approved, please prioritise', 'mkttl', false, timestamptz '2026-09-23T09:00:00+08');

-- PRF-2026-900004 MOP05 Pacific Harbor Logistics Inc.: TERMS_RECEIVED
insert into npk_proposal (company_id, prf_no, arn, client_id, client_code, client_name, client_email, product_code, line_code, market_segment, source_channel, period_from, period_to, currency, risk_details, total_sum_insured, tsu_rule, tsu_reason, status, submitted_by, submitted_at, approved_by, approved_at, qs_no, qs_template, qs_reply_by, qs_submitted_by, qs_approved_by, qs_sent_at, terms_closed, chosen_insurer, ps_no, ps_version, ps_submitted_by, ps_approved_by, sent_at, accepted_at, accepted_groups, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PRF-2026-900004', 'ARN-2026-920004', (select id from crm_client where client_code = 'CL-2026-000003'), 'CL-2026-000003', 'Pacific Harbor Logistics Inc.', 'treasury@pacificharbor.example', 'MOP05', 'MARINE', 'CORBANK', 'EMAIL', date '2026-10-01', date '2027-10-01', 'PHP', '{"sections": [{"heading": "Cargo", "text": "Imported spare parts and consumer goods, estimated annual shipments PHP 80,000,000"}, {"heading": "Conveyance", "text": "Containerised sea freight, Asia to Manila"}], "items": [{"riskGroup": 1, "data": {"description": "Marine open policy - annual declared shipments", "sumInsured": 80000000, "rate": 0.15, "biLimit": null, "pdLimit": null, "vehicle": null, "location": null, "person": null}}]}', 80000000, 'NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'TERMS_RECEIVED', 'ao2', timestamptz '2026-09-04T09:00:00+08', 'mkttl', timestamptz '2026-09-04T14:00:00+08', 'QS-2026-900001', 'QUOTATION_SLIP v1', date '2026-09-10', 'tsu', 'tsulead', timestamptz '2026-09-06T09:00:00+08', false, null, null, 0, null, null, null, null, null, timestamptz '2026-09-03T09:00:00+08', 'ao2');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 0, 'INS-MGIC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 1, 'INS-LAC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 2, 'INS-VMI');
insert into npk_insurer_response (proposal_id, insurer_code, insurer_name, status, revision, premium, rate, deductibles, conditions, valid_until, remarks, recommended, responded_at, created_at, created_by, updated_at, updated_by)
values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'RECEIVED', 1, 128000.0, 0.16, 'PHP 25,000 each shipment', 'Institute Cargo Clauses (A), war and strikes', date '2026-10-15', null, false, timestamptz '2026-09-09T09:00:00+08', timestamptz '2026-09-06T09:00:00+08', 'tsulead', timestamptz '2026-09-09T09:00:00+08', 'tsu');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900004') and insurer_code = 'INS-MGIC'), 1, 'RECEIVED', 128000.0, 0.16, 'PHP 25,000 each shipment', 'Institute Cargo Clauses (A), war and strikes', date '2026-10-15', null, false, 'tsu', timestamptz '2026-09-09T10:00:00+08');
insert into npk_insurer_response (proposal_id, insurer_code, insurer_name, status, revision, premium, rate, deductibles, conditions, valid_until, remarks, recommended, responded_at, created_at, created_by, updated_at, updated_by)
values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 'INS-LAC', 'Luzon Assurance Co.', 'RECEIVED', 2, 118500.0, 0.148125, 'PHP 30,000 each shipment', 'Institute Cargo Clauses (A)', date '2026-10-20', 'Best terms, 10% loss-free discount applied', true, timestamptz '2026-09-09T09:00:00+08', timestamptz '2026-09-06T09:00:00+08', 'tsulead', timestamptz '2026-09-09T09:00:00+08', 'tsu');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900004') and insurer_code = 'INS-LAC'), 1, 'RECEIVED', 118500.0, 0.148125, 'PHP 30,000 each shipment', 'Institute Cargo Clauses (A)', date '2026-10-20', 'Best terms, 10% loss-free discount applied', false, 'tsu', timestamptz '2026-09-09T10:00:00+08');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900004') and insurer_code = 'INS-LAC'), 2, 'RECEIVED', 118500.0, 0.148125, 'PHP 30,000 each shipment', 'Institute Cargo Clauses (A)', date '2026-10-20', 'Best terms, 10% loss-free discount applied', true, 'tsu', timestamptz '2026-09-09T11:00:00+08');
insert into npk_insurer_response (proposal_id, insurer_code, insurer_name, status, revision, premium, rate, deductibles, conditions, valid_until, remarks, recommended, responded_at, created_at, created_by, updated_at, updated_by)
values ((select id from npk_proposal where prf_no = 'PRF-2026-900004'), 'INS-VMI', 'Visayas Mutual Insurance', 'DECLINED', 1, null, null, null, null, null, 'Capacity for marine cargo is full this quarter', false, timestamptz '2026-09-09T09:00:00+08', timestamptz '2026-09-06T09:00:00+08', 'tsulead', timestamptz '2026-09-09T09:00:00+08', 'tsu');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900004') and insurer_code = 'INS-VMI'), 1, 'DECLINED', null, null, null, null, null, 'Capacity for marine cargo is full this quarter', false, 'tsu', timestamptz '2026-09-09T10:00:00+08');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'NB_PROPOSAL', 'ProposalRequest', (select id from npk_proposal where prf_no = 'PRF-2026-900004')::text, 'PRF-2026-900004', 'Pacific Harbor Logistics Inc. - MOP05', '/proposals/' || (select id from npk_proposal where prf_no = 'PRF-2026-900004'), 'CORBANK', 'TERMS_RECEIVED', timestamptz '2026-09-12T16:00:00+08', timestamptz '2026-09-13T16:00:00+08', 'tsu', false, timestamptz '2026-09-03T09:00:00+08', 'ao2');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), null, 'DRAFT', 'start', null, null, 'ao2', false, timestamptz '2026-09-03T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao2', false, timestamptz '2026-09-04T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'FOR_MKT_APPROVAL', 'WITH_TSU', 'approve', null, null, 'mkttl', false, timestamptz '2026-09-04T14:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'WITH_TSU', 'QS_PREPARATION', 'prepare_qs', null, null, 'tsu', false, timestamptz '2026-09-05T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'QS_PREPARATION', 'QS_FOR_APPROVAL', 'submit_qs', null, null, 'tsu', false, timestamptz '2026-09-05T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'QS_FOR_APPROVAL', 'QS_SENT', 'approve_qs', null, null, 'tsulead', false, timestamptz '2026-09-06T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900004'), 'QS_SENT', 'TERMS_RECEIVED', 'terms_complete', null, null, 'tsu', false, timestamptz '2026-09-12T16:00:00+08');

-- PRF-2026-900005 EPF05 Luzon Agri-Industrial Corp.: ACCEPTED
insert into npk_proposal (company_id, prf_no, arn, client_id, client_code, client_name, client_email, product_code, line_code, market_segment, source_channel, period_from, period_to, currency, risk_details, total_sum_insured, tsu_rule, tsu_reason, status, submitted_by, submitted_at, approved_by, approved_at, qs_no, qs_template, qs_reply_by, qs_submitted_by, qs_approved_by, qs_sent_at, terms_closed, chosen_insurer, ps_no, ps_version, ps_submitted_by, ps_approved_by, sent_at, accepted_at, accepted_groups, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PRF-2026-900005', 'ARN-2026-920005', (select id from crm_client where client_code = 'CL-2026-000004'), 'CL-2026-000004', 'Luzon Agri-Industrial Corp.', 'finance@luzonagri.example', 'EPF05', 'FLOATER', 'COMBANK', 'EMAIL', date '2026-09-15', date '2027-09-15', 'PHP', '{"sections": [{"heading": "Equipment", "text": "Mobile loaders and forklifts, Batangas plant and depots"}, {"heading": "Requested cover", "text": "All risks including political violence"}], "items": [{"riskGroup": 1, "data": {"description": "Mobile plant and equipment floater - 12 units", "sumInsured": 20000000, "rate": 0.4, "biLimit": null, "pdLimit": null, "vehicle": null, "location": null, "person": null}}]}', 20000000, 'NON_PACKAGE', 'Non-package risks are priced by TSU with the insurers', 'ACCEPTED', 'ao2', timestamptz '2026-08-21T09:00:00+08', 'mkttl', timestamptz '2026-08-21T15:00:00+08', 'QS-2026-900002', 'QUOTATION_SLIP v1', date '2026-08-27', 'tsu', 'tsulead', timestamptz '2026-08-24T09:00:00+08', false, 'INS-MPI', 'PS-2026-900001', 1, 'tsu', 'tsulead', timestamptz '2026-08-31T09:00:00+08', timestamptz '2026-09-07T09:00:00+08', '1', timestamptz '2026-08-20T09:00:00+08', 'ao2');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900005'), 0, 'INS-MGIC');
insert into npk_proposal_insurer (proposal_id, insurer_index, insurer_code) values ((select id from npk_proposal where prf_no = 'PRF-2026-900005'), 1, 'INS-MPI');
insert into npk_insurer_response (proposal_id, insurer_code, insurer_name, status, revision, premium, rate, deductibles, conditions, valid_until, remarks, recommended, responded_at, created_at, created_by, updated_at, updated_by)
values ((select id from npk_proposal where prf_no = 'PRF-2026-900005'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'RECEIVED', 1, 82000.0, 0.41, 'PHP 20,000 each loss', 'Standard EPF wording, PV extension', date '2026-09-30', null, false, timestamptz '2026-08-27T09:00:00+08', timestamptz '2026-08-24T09:00:00+08', 'tsulead', timestamptz '2026-08-27T09:00:00+08', 'tsu');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900005') and insurer_code = 'INS-MGIC'), 1, 'RECEIVED', 82000.0, 0.41, 'PHP 20,000 each loss', 'Standard EPF wording, PV extension', date '2026-09-30', null, false, 'tsu', timestamptz '2026-08-27T10:00:00+08');
insert into npk_insurer_response (proposal_id, insurer_code, insurer_name, status, revision, premium, rate, deductibles, conditions, valid_until, remarks, recommended, responded_at, created_at, created_by, updated_at, updated_by)
values ((select id from npk_proposal where prf_no = 'PRF-2026-900005'), 'INS-MPI', 'Mindanao Pacific Insurance Inc.', 'RECEIVED', 2, 78500.0, 0.3925, 'PHP 25,000 each loss', 'Standard EPF wording, PV extension', date '2026-10-05', 'Recommended: lowest premium, same cover', true, timestamptz '2026-08-27T09:00:00+08', timestamptz '2026-08-24T09:00:00+08', 'tsulead', timestamptz '2026-08-27T09:00:00+08', 'tsu');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900005') and insurer_code = 'INS-MPI'), 1, 'RECEIVED', 78500.0, 0.3925, 'PHP 25,000 each loss', 'Standard EPF wording, PV extension', date '2026-10-05', 'Recommended: lowest premium, same cover', false, 'tsu', timestamptz '2026-08-27T10:00:00+08');
insert into npk_insurer_response_history (response_id, revision, status, premium, rate, deductibles, conditions, valid_until, remarks, recommended, changed_by, changed_at)
values ((select id from npk_insurer_response where proposal_id = (select id from npk_proposal where prf_no = 'PRF-2026-900005') and insurer_code = 'INS-MPI'), 2, 'RECEIVED', 78500.0, 0.3925, 'PHP 25,000 each loss', 'Standard EPF wording, PV extension', date '2026-10-05', 'Recommended: lowest premium, same cover', true, 'tsu', timestamptz '2026-08-27T11:00:00+08');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'NB_PROPOSAL', 'ProposalRequest', (select id from npk_proposal where prf_no = 'PRF-2026-900005')::text, 'PRF-2026-900005', 'Luzon Agri-Industrial Corp. - EPF05', '/proposals/' || (select id from npk_proposal where prf_no = 'PRF-2026-900005'), 'COMBANK', 'ACCEPTED', timestamptz '2026-09-07T09:00:00+08', timestamptz '2026-09-08T09:00:00+08', 'ao2', false, timestamptz '2026-08-20T09:00:00+08', 'ao2');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), null, 'DRAFT', 'start', null, null, 'ao2', false, timestamptz '2026-08-20T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao2', false, timestamptz '2026-08-21T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'FOR_MKT_APPROVAL', 'WITH_TSU', 'approve', null, null, 'mkttl', false, timestamptz '2026-08-21T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'WITH_TSU', 'QS_PREPARATION', 'prepare_qs', null, null, 'tsu', false, timestamptz '2026-08-22T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'QS_PREPARATION', 'QS_FOR_APPROVAL', 'submit_qs', null, null, 'tsu', false, timestamptz '2026-08-22T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'QS_FOR_APPROVAL', 'QS_SENT', 'approve_qs', null, null, 'tsulead', false, timestamptz '2026-08-24T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'QS_SENT', 'TERMS_RECEIVED', 'terms_complete', null, null, 'tsu', false, timestamptz '2026-08-28T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'TERMS_RECEIVED', 'PS_FOR_APPROVAL', 'submit_ps', null, null, 'tsu', false, timestamptz '2026-08-28T14:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'PS_FOR_APPROVAL', 'PS_RELEASED', 'approve_ps', null, null, 'tsulead', false, timestamptz '2026-08-29T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'PS_RELEASED', 'SENT_TO_CLIENT', 'send_to_client', null, 'Sent to finance@luzonagri.example', 'ao2', false, timestamptz '2026-08-31T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'ProposalRequest' and reference = 'PRF-2026-900005'), 'SENT_TO_CLIENT', 'ACCEPTED', 'accept', null, 'Client accepted Mindanao Pacific terms', 'ao2', false, timestamptz '2026-09-07T09:00:00+08');
