-- =====================================================================================
-- iNXT BrokerVerse - V997 Seed Product Maintenance package requests (seed profile only):
-- one request at each main stage of PM_PACKAGE_REQUEST with consistent work cases and history
-- (docs/architecture/PRODUCT_MAINTENANCE_DESIGN.md section 3). SEED DATA ONLY.
--   PKR-2026-900001 NEW generic programme           DRAFT
--   PKR-2026-900002 AMEND MTR10                      FOR_TSU_REVIEW
--   PKR-2026-900003 NEW client-specific (property)   NEGOTIATION: two rounds, "approved with
--                                                    changes", a counter-proposal and a decline
--   PKR-2026-900004 UPDATE MTR12                     FOR_MANCOM (requirements submitted)
--   PKR-2026-900005 RENEW MTR15, no negotiation      WITH_MBS (signed off)
--   PKR-2026-900006 AMEND PAR08                      RELEASED as version 2, advisory sent
--   Numbers PKR-2026-9000nn and PQS-2026-9000nn (outside the live sequences). The catalog
--   versions, including the package expiring in 45 days, are the catalog seed data (V996).
--   Documents (signed package slips, sign-off sheets) are uploaded in the application.
-- =====================================================================================
-- PKR-2026-900001 NEW generic SME Motor Fleet Programme: DRAFT
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900001', 'NEW', 'GENERIC', 'SME Motor Fleet Programme', null, null, null, 'MOTOR', 'COMPREHENSIVE', null, null, 'COMBANK', 'NEW_PROGRAMME', null, true, '{"sections": [{"heading": "Target market", "text": "SME fleets of 5 to 50 private vehicles, BDO Unibank commercial clients"}, {"heading": "Requested features", "text": "Free towing up to 50 km, 24/7 roadside assistance"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 3,000 each claim"}, {"coverageCode": "THEFT", "included": true, "optional": false}, {"coverageCode": "TPL_BI", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "TPL_PD", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "AON", "included": true, "optional": false, "deductibleText": "0.5% of sum insured"}], "scheme": {"defaultRate": 1.25, "minimumPremium": 5000, "commissionRate": 15, "maxSumInsured": 5000000}, "dates": {"effectiveFrom": "2027-01-01", "packageStartDate": "2027-01-01", "packageEndDate": "2027-12-31"}, "insurers": [{"insurerCode": "INS-MGIC", "terms": []}, {"insurerCode": "INS-LAC", "terms": []}, {"insurerCode": "INS-MPI", "terms": []}]}', null, null, null, date '2027-12-31', 1.25, 'DRAFT', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, timestamptz '2026-09-23T10:00:00+08', 'ao');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900001')::text, 'PKR-2026-900001', 'NEW new package - SME Motor Fleet Programme', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900001'), 'MOTOR', 'DRAFT', timestamptz '2026-09-23T10:00:00+08', null, 'ao', false, timestamptz '2026-09-23T10:00:00+08', 'ao');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900001'), null, 'DRAFT', 'start', null, null, 'ao', false, timestamptz '2026-09-23T10:00:00+08');

-- PKR-2026-900002 AMEND MTR10 (market competitiveness): FOR_TSU_REVIEW
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900002', 'AMEND', 'GENERIC', 'Motor package MTR10 - lower deductible', null, null, null, 'MOTOR', 'COMPREHENSIVE', 'MTR10', null, 'CBG,RETAIL', 'MARKET_COMPETITIVENESS', 'Competitor offers PHP 2,000 own damage deductible', true, '{"sections": [{"heading": "Change requested", "text": "Reduce own-damage deductible to PHP 2,000 and add flood cover as standard"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 2,000 each claim"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "PHP 5,000 each claim"}], "scheme": {"defaultRate": 1.35}, "dates": {"effectiveFrom": "2026-11-01", "packageStartDate": "2026-11-01", "packageEndDate": "2027-10-31"}, "insurers": [{"insurerCode": "INS-MGIC", "terms": []}, {"insurerCode": "INS-VMI", "terms": []}]}', null, null, null, date '2027-10-31', 1.35, 'FOR_TSU_REVIEW', 'ao', timestamptz '2026-09-18T15:00:00+08', 'mkttl', timestamptz '2026-09-21T10:00:00+08', null, null, null, null, null, null, null, null, null, null, null, null, timestamptz '2026-09-18T09:00:00+08', 'ao');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900002')::text, 'PKR-2026-900002', 'AMEND MTR10 - Motor package MTR10 - lower deductible', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900002'), 'MOTOR', 'FOR_TSU_REVIEW', timestamptz '2026-09-21T10:00:00+08', timestamptz '2026-09-21T10:00:00+08' + interval '24 hours', null, false, timestamptz '2026-09-18T09:00:00+08', 'ao');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900002'), null, 'DRAFT', 'start', null, null, 'ao', false, timestamptz '2026-09-18T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900002'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao', false, timestamptz '2026-09-18T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900002'), 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'approve', null, 'Approved for TSU review', 'mkttl', false, timestamptz '2026-09-21T10:00:00+08');

-- PKR-2026-900003 NEW client-specific property package, Pacific Harbor Logistics: NEGOTIATION, round 2
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900003', 'NEW', 'CLIENT_SPECIFIC', 'Pacific Harbor Warehouse Property Package', (select id from crm_client where client_code = 'CL-2026-000003'), 'CL-2026-000003', 'Pacific Harbor Logistics Inc.', 'PROPERTY', 'ALL_RISK', null, null, 'CORBANK', 'CLIENT_REQUIREMENT', null, true, '{"sections": [{"heading": "Client", "text": "Pacific Harbor Logistics Inc., 6 warehouses in Metro Manila and Batangas"}, {"heading": "Requested terms", "text": "All risks property cover for owned warehouses and stocks, sum insured PHP 450,000,000"}], "coverages": [{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 20,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}], "scheme": {"defaultRate": 0.22, "minimumPremium": 25000, "commissionRate": 20, "maxSumInsured": 450000000}, "dates": {"effectiveFrom": "2026-11-15", "packageStartDate": "2026-11-15", "packageEndDate": "2027-11-14"}, "insurers": [{"insurerCode": "INS-MGIC", "terms": []}, {"insurerCode": "INS-LAC", "terms": []}, {"insurerCode": "INS-VMI", "terms": []}]}', 'Approach the three panel insurers; client loss history is clean', null, null, date '2027-11-14', 0.22, 'NEGOTIATION', 'ao2', timestamptz '2026-09-01T14:00:00+08', 'mkttl', timestamptz '2026-09-02T09:00:00+08', 'tsulead', timestamptz '2026-09-03T10:00:00+08', 'tsuhead', timestamptz '2026-09-03T16:00:00+08', null, null, null, null, null, null, null, null, timestamptz '2026-09-01T09:00:00+08', 'ao2');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900003')::text, 'PKR-2026-900003', 'NEW new package - Pacific Harbor Warehouse Property Package', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900003'), 'PROPERTY', 'NEGOTIATION', timestamptz '2026-09-14T10:00:00+08', timestamptz '2026-09-14T10:00:00+08' + interval '120 hours', 'tsu', false, timestamptz '2026-09-01T09:00:00+08', 'ao2');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), null, 'DRAFT', 'start', null, null, 'ao2', false, timestamptz '2026-09-01T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao2', false, timestamptz '2026-09-01T14:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'approve', null, null, 'mkttl', false, timestamptz '2026-09-02T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), 'FOR_TSU_REVIEW', 'FOR_TSU_APPROVAL', 'recommend', null, 'Approach the three panel insurers; client loss history is clean', 'tsulead', false, timestamptz '2026-09-03T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), 'FOR_TSU_APPROVAL', 'NEGOTIATION', 'approve', null, null, 'tsuhead', false, timestamptz '2026-09-03T16:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900003'), 'NEGOTIATION', 'NEGOTIATION', 'revise_qs', null, 'Round 2: ask Luzon Assurance to improve the typhoon deductible', 'tsu', false, timestamptz '2026-09-14T10:00:00+08');
insert into pm_negotiation_round (request_id, round_no, status, qs_no, qs_template, qs_notes, reply_due, prepared_by, submitted_at, approved_by, approved_at, sent_at, locked, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900003'), 1, 'CLOSED', 'PQS-2026-900001', 'PKG_QUOTATION_SLIP v1', 'Terms as requested', date '2026-09-10', 'tsu', timestamptz '2026-09-04T09:00:00+08', 'tsulead', timestamptz '2026-09-04T15:00:00+08', timestamptz '2026-09-04T15:00:00+08', false, timestamptz '2026-09-04T09:00:00+08', 'tsu');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 0, 'INS-MGIC');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 1, 'INS-LAC');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 2, 'INS-VMI');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'APPROVED_WITH_CHANGES', 1, 0.24, 30000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2.5% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 25,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Warranted: sprinkler system maintained', date '2026-10-31', 'Rate 0.24% with EQ deductible 2.5%', timestamptz '2026-09-09T11:00:00+08', 1, timestamptz '2026-09-09T11:00:00+08', 'tsulead', timestamptz '2026-09-09T11:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-MGIC' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900001')), 1, 'APPROVED_WITH_CHANGES', 0.24, 30000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2.5% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 25,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Warranted: sprinkler system maintained', date '2026-10-31', 'Rate 0.24% with EQ deductible 2.5%', 'tsu', timestamptz '2026-09-09T11:00:00+08');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 'INS-LAC', 'Luzon Assurance Co.', 'COUNTER_PROPOSAL', 1, 0.21, 25000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "2% of loss, min PHP 50,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Typhoon deductible increased', date '2026-10-31', 'Lower rate but higher typhoon deductible', timestamptz '2026-09-10T09:00:00+08', 1, timestamptz '2026-09-10T09:00:00+08', 'tsulead', timestamptz '2026-09-10T09:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-LAC' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900001')), 1, 'COUNTER_PROPOSAL', 0.21, 25000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "2% of loss, min PHP 50,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Typhoon deductible increased', date '2026-10-31', 'Lower rate but higher typhoon deductible', 'tsu', timestamptz '2026-09-10T09:00:00+08');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900001'), 'INS-VMI', 'Visayas Mutual Insurance', 'DECLINED', 1, null, null, '[]', null, null, 'No capacity for Batangas accumulation', timestamptz '2026-09-08T16:00:00+08', 1, timestamptz '2026-09-08T16:00:00+08', 'tsulead', timestamptz '2026-09-08T16:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-VMI' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900001')), 1, 'DECLINED', null, null, '[]', null, null, 'No capacity for Batangas accumulation', 'tsu', timestamptz '2026-09-08T16:00:00+08');
insert into pm_negotiation_round (request_id, round_no, status, qs_no, qs_template, qs_notes, reply_due, prepared_by, submitted_at, approved_by, approved_at, sent_at, locked, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900003'), 2, 'SENT', 'PQS-2026-900002', 'PKG_QUOTATION_SLIP v1', 'Round 2: please improve the typhoon deductible to 1% of loss', date '2026-09-21', 'tsu', timestamptz '2026-09-14T10:30:00+08', 'tsulead', timestamptz '2026-09-14T15:00:00+08', timestamptz '2026-09-14T15:00:00+08', false, timestamptz '2026-09-14T10:30:00+08', 'tsu');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900002'), 0, 'INS-MGIC');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900002'), 1, 'INS-LAC');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900002'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'APPROVED_WITH_CHANGES', 1, 0.235, 30000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2.5% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 25,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Warranted: sprinkler system maintained', date '2026-11-15', 'Final: 0.235%', timestamptz '2026-09-18T10:00:00+08', 1, timestamptz '2026-09-18T10:00:00+08', 'tsulead', timestamptz '2026-09-18T10:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-MGIC' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900002')), 1, 'APPROVED_WITH_CHANGES', 0.235, 30000, '[{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2.5% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 25,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}]', 'Warranted: sprinkler system maintained', date '2026-11-15', 'Final: 0.235%', 'tsu', timestamptz '2026-09-18T10:00:00+08');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900002'), 'INS-LAC', 'Luzon Assurance Co.', 'PENDING', 0, null, null, '[]', null, null, null, null, 1, timestamptz '2026-09-14T15:00:00+08', 'tsulead', timestamptz '2026-09-14T15:00:00+08', 'tsulead');

-- PKR-2026-900004 UPDATE MTR12 (roadside assistance): FOR_MANCOM
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900004', 'UPDATE', 'GENERIC', 'Motor package MTR12 - roadside assistance', null, null, null, 'MOTOR', 'COMPREHENSIVE', 'MTR12', null, 'CBG,RETAIL', 'INSURER_TERMS_CHANGE', null, true, '{"sections": [{"heading": "Update", "text": "Add roadside assistance to the package wording"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 3,000 each claim"}, {"coverageCode": "THEFT", "included": true, "optional": false}, {"coverageCode": "TPL_BI", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "TPL_PD", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "AON", "included": true, "optional": false, "deductibleText": "0.5% of sum insured"}], "scheme": {"defaultRate": 1.3, "minimumPremium": 5000, "commissionRate": 15, "maxSumInsured": 5000000}, "dates": {"effectiveFrom": "2026-10-15", "packageStartDate": "2026-10-15", "packageEndDate": "2027-10-14"}, "insurers": [{"insurerCode": "INS-MGIC", "terms": []}]}', 'Mabuhay General offered roadside assistance at no extra premium', '{"sections": [{"heading": "Update", "text": "Add roadside assistance to the package wording"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 3,000 each claim"}, {"coverageCode": "THEFT", "included": true, "optional": false}, {"coverageCode": "TPL_BI", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "TPL_PD", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "AON", "included": true, "optional": false, "deductibleText": "0.5% of sum insured"}], "scheme": {"defaultRate": 1.3, "minimumPremium": 5000, "commissionRate": 15, "maxSumInsured": 5000000, "ratingBasisNote": "Sum insured x 1.30%, minimum PHP 5,000; AON 0.5%"}, "dates": {"effectiveFrom": "2026-10-15", "packageStartDate": "2026-10-15", "packageEndDate": "2027-10-14"}, "insurers": [{"insurerCode": "INS-MGIC", "role": "PANEL", "rate": 1.3, "minimumPremium": 5000, "terms": []}]}', 'INS-MGIC', date '2027-10-14', 1.3, 'FOR_MANCOM', 'tsu', timestamptz '2026-08-20T11:00:00+08', 'mkttl', timestamptz '2026-08-20T16:00:00+08', 'tsulead', timestamptz '2026-08-21T10:00:00+08', 'tsuhead', timestamptz '2026-08-21T15:00:00+08', 'tsu', timestamptz '2026-09-04T10:00:00+08', 'tsu', timestamptz '2026-09-22T09:00:00+08', null, null, null, null, timestamptz '2026-08-20T09:00:00+08', 'tsu');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900004')::text, 'PKR-2026-900004', 'UPDATE MTR12 - Motor package MTR12 - roadside assistance', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900004'), 'MOTOR', 'FOR_MANCOM', timestamptz '2026-09-22T09:00:00+08', timestamptz '2026-09-22T09:00:00+08' + interval '72 hours', null, false, timestamptz '2026-08-20T09:00:00+08', 'tsu');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), null, 'DRAFT', 'start', null, null, 'tsu', false, timestamptz '2026-08-20T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'tsu', false, timestamptz '2026-08-20T11:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'approve', null, null, 'mkttl', false, timestamptz '2026-08-20T16:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'FOR_TSU_REVIEW', 'FOR_TSU_APPROVAL', 'recommend', null, 'Mabuhay General offered roadside assistance at no extra premium', 'tsulead', false, timestamptz '2026-08-21T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'FOR_TSU_APPROVAL', 'NEGOTIATION', 'approve', null, null, 'tsuhead', false, timestamptz '2026-08-21T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'NEGOTIATION', 'TERMS_REVIEW', 'terms_final', null, null, 'tsu', false, timestamptz '2026-09-04T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'TERMS_REVIEW', 'REQUIREMENTS_PREP', 'skip_marketing_review', null, null, 'tsuhead', false, timestamptz '2026-09-07T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900004'), 'REQUIREMENTS_PREP', 'FOR_MANCOM', 'submit_requirements', null, 'Requirements pack with signed package slip', 'tsu', false, timestamptz '2026-09-22T09:00:00+08');
insert into pm_negotiation_round (request_id, round_no, status, qs_no, qs_template, qs_notes, reply_due, prepared_by, submitted_at, approved_by, approved_at, sent_at, locked, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900004'), 1, 'SENT', 'PQS-2026-900003', 'PKG_QUOTATION_SLIP v1', 'Terms as requested', date '2026-08-28', 'tsu', timestamptz '2026-08-24T09:00:00+08', 'tsulead', timestamptz '2026-08-24T14:00:00+08', timestamptz '2026-08-24T14:00:00+08', false, timestamptz '2026-08-24T09:00:00+08', 'tsu');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900003'), 0, 'INS-MGIC');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900003'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'ACCEPTED_AS_REQUESTED', 1, 1.3, 5000, '[]', 'Roadside assistance included', date '2026-12-31', null, timestamptz '2026-09-02T10:00:00+08', 1, timestamptz '2026-09-02T10:00:00+08', 'tsulead', timestamptz '2026-09-02T10:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-MGIC' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900003')), 1, 'ACCEPTED_AS_REQUESTED', 1.3, 5000, '[]', 'Roadside assistance included', date '2026-12-31', null, 'tsu', timestamptz '2026-09-02T10:00:00+08');

-- PKR-2026-900005 RENEW MTR15 on unchanged terms (no negotiation): WITH_MBS
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900005', 'RENEW', 'GENERIC', 'Motor package MTR15 renewal', null, null, null, 'MOTOR', 'COMPREHENSIVE', 'MTR15', null, 'CBG,RETAIL', 'PACKAGE_EXPIRY', 'Package ends on 2026-10-31', false, '{"sections": [{"heading": "Renewal", "text": "Renewal of MTR15 on the expiring terms"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 3,000 each claim"}, {"coverageCode": "THEFT", "included": true, "optional": false}, {"coverageCode": "TPL_BI", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "TPL_PD", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "AON", "included": true, "optional": false, "deductibleText": "0.5% of sum insured"}], "scheme": {"defaultRate": 1.3, "minimumPremium": 5000, "commissionRate": 15, "maxSumInsured": 5000000, "ratingBasisNote": "Sum insured x 1.30%, minimum PHP 5,000"}, "dates": {"effectiveFrom": "2026-11-01", "packageStartDate": "2026-11-01", "packageEndDate": "2027-10-31"}, "insurers": [{"insurerCode": "INS-LAC", "role": "PANEL", "rate": 1.3, "minimumPremium": 5000, "terms": []}]}', 'Renew on the same terms; no loss deterioration', '{"sections": [{"heading": "Renewal", "text": "Renewal of MTR15 on the expiring terms"}], "coverages": [{"coverageCode": "OWN_DAMAGE", "included": true, "optional": false, "deductibleText": "PHP 3,000 each claim"}, {"coverageCode": "THEFT", "included": true, "optional": false}, {"coverageCode": "TPL_BI", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "TPL_PD", "included": true, "optional": false, "limitAmount": 200000}, {"coverageCode": "AON", "included": true, "optional": false, "deductibleText": "0.5% of sum insured"}], "scheme": {"defaultRate": 1.3, "minimumPremium": 5000, "commissionRate": 15, "maxSumInsured": 5000000, "ratingBasisNote": "Sum insured x 1.30%, minimum PHP 5,000"}, "dates": {"effectiveFrom": "2026-11-01", "packageStartDate": "2026-11-01", "packageEndDate": "2027-10-31"}, "insurers": [{"insurerCode": "INS-LAC", "role": "PANEL", "rate": 1.3, "minimumPremium": 5000, "terms": []}]}', 'INS-LAC', date '2027-10-31', 1.3, 'WITH_MBS', 'tsu', timestamptz '2026-09-08T10:00:00+08', 'mkttl', timestamptz '2026-09-08T15:00:00+08', 'tsulead', timestamptz '2026-09-09T09:00:00+08', 'tsuhead', timestamptz '2026-09-09T14:00:00+08', null, null, null, null, null, null, null, null, timestamptz '2026-09-08T09:00:00+08', 'tsu');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900005')::text, 'PKR-2026-900005', 'RENEW MTR15 - Motor package MTR15 renewal', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900005'), 'MOTOR', 'WITH_MBS', timestamptz '2026-09-23T11:00:00+08', timestamptz '2026-09-23T11:00:00+08' + interval '48 hours', null, false, timestamptz '2026-09-08T09:00:00+08', 'tsu');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), null, 'DRAFT', 'start', null, null, 'tsu', false, timestamptz '2026-09-08T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'tsu', false, timestamptz '2026-09-08T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'approve', null, null, 'mkttl', false, timestamptz '2026-09-08T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), 'FOR_TSU_REVIEW', 'FOR_TSU_APPROVAL', 'recommend', null, 'Renew on the same terms; no loss deterioration', 'tsulead', false, timestamptz '2026-09-09T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), 'FOR_TSU_APPROVAL', 'FOR_MANCOM', 'approve_no_negotiation', null, null, 'tsuhead', false, timestamptz '2026-09-09T14:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900005'), 'FOR_MANCOM', 'WITH_MBS', 'signoff', null, 'Approved for renewal', 'mancom', false, timestamptz '2026-09-23T11:00:00+08');
insert into pm_signoff (request_id, kind, decision, reference, signed_by, signed_at, comment, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900005'), 'MANCOM', 'SIGNED', 'MC-PKR-2026-900005', 'mancom', timestamptz '2026-09-23T11:00:00+08', 'Approved for renewal', timestamptz '2026-09-23T11:00:00+08', 'mancom');

-- PKR-2026-900006 AMEND PAR08 home fire programme: RELEASED as version 2, advisory sent
insert into pm_request (company_id, request_no, request_type, scope, title, client_id, client_code, client_name, line_code, cover_type_code, target_product_code, base_version_no, market_segments, reason, reason_note, negotiation_required, requested_terms, recommendation, proposed_terms, chosen_insurers, package_end_date, scheme_rate, status, submitted_by, submitted_at, approved_by, approved_at, recommended_by, recommended_at, tsu_approved_by, tsu_approved_at, terms_final_by, terms_final_at, requirements_by, requirements_at, setup_by, setup_at, resulting_version_no, released_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PKR-2026-900006', 'AMEND', 'GENERIC', 'Home fire programme PAR08 - allied perils', null, null, null, 'PROPERTY', 'FIRE_LIGHTNING', 'PAR08', 1, 'CBG,RETAIL', 'MARKET_COMPETITIVENESS', null, true, '{"sections": [{"heading": "Target market", "text": "Homeowners with BDO housing loans, fire and allied perils"}], "coverages": [{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 20,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}], "scheme": {"defaultRate": 0.25, "minimumPremium": 1000, "commissionRate": 20, "maxSumInsured": 20000000, "ratingBasisNote": "Sum insured x 0.25%, minimum PHP 1,000"}, "dates": {"effectiveFrom": "2026-09-01", "packageStartDate": "2026-09-01", "packageEndDate": "2027-08-31", "anniversaryDate": "2027-09-01"}, "insurers": [{"insurerCode": "INS-MGIC", "terms": []}, {"insurerCode": "INS-MPI", "terms": []}]}', 'Allied perils at the current rate', '{"sections": [{"heading": "Target market", "text": "Homeowners with BDO housing loans, fire and allied perils"}], "coverages": [{"coverageCode": "FIRE_LIGHTNING", "included": true, "optional": false}, {"coverageCode": "EARTHQUAKE", "included": true, "optional": false, "deductibleText": "2% of value at risk"}, {"coverageCode": "TYPHOON_FLOOD", "included": true, "optional": false, "deductibleText": "1% of loss, min PHP 20,000"}, {"coverageCode": "RIOT_STRIKE", "included": true, "optional": false}], "scheme": {"defaultRate": 0.25, "minimumPremium": 1000, "commissionRate": 20, "maxSumInsured": 20000000, "ratingBasisNote": "Sum insured x 0.25%, minimum PHP 1,000"}, "dates": {"effectiveFrom": "2026-09-01", "packageStartDate": "2026-09-01", "packageEndDate": "2027-08-31", "anniversaryDate": "2027-09-01"}, "insurers": [{"insurerCode": "INS-MGIC", "role": "LEAD", "rate": 0.25, "minimumPremium": 1000, "terms": []}]}', 'INS-MGIC', date '2027-08-31', 0.25, 'RELEASED', 'ao', timestamptz '2026-07-01T11:00:00+08', 'mkttl', timestamptz '2026-07-01T16:00:00+08', 'tsulead', timestamptz '2026-07-02T10:00:00+08', 'tsuhead', timestamptz '2026-07-02T15:00:00+08', 'tsu', timestamptz '2026-07-20T10:00:00+08', 'tsu', timestamptz '2026-07-27T10:00:00+08', 'mbs', timestamptz '2026-08-05T10:00:00+08', 2, timestamptz '2026-08-07T15:00:00+08', timestamptz '2026-07-01T09:00:00+08', 'ao');
insert into wf_case (company_id, workflow_code, entity_type, entity_id, reference, title, link, originating_unit, stage_code, stage_entered_at, due_at, assignee, closed, created_at, created_by)
values ((select id from org_company where code = 'FVI'), 'PM_PACKAGE_REQUEST', 'PackageRequest', (select id from pm_request where request_no = 'PKR-2026-900006')::text, 'PKR-2026-900006', 'AMEND PAR08 - Home fire programme PAR08 - allied perils', '/product-maintenance/requests/' || (select id from pm_request where request_no = 'PKR-2026-900006'), 'PROPERTY', 'RELEASED', timestamptz '2026-08-07T15:00:00+08', null, null, true, timestamptz '2026-07-01T09:00:00+08', 'ao');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), null, 'DRAFT', 'start', null, null, 'ao', false, timestamptz '2026-07-01T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'DRAFT', 'FOR_MKT_APPROVAL', 'submit', null, null, 'ao', false, timestamptz '2026-07-01T11:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'FOR_MKT_APPROVAL', 'FOR_TSU_REVIEW', 'approve', null, null, 'mkttl', false, timestamptz '2026-07-01T16:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'FOR_TSU_REVIEW', 'FOR_TSU_APPROVAL', 'recommend', null, 'Allied perils at the current rate', 'tsulead', false, timestamptz '2026-07-02T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'FOR_TSU_APPROVAL', 'NEGOTIATION', 'approve', null, null, 'tsuhead', false, timestamptz '2026-07-02T15:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'NEGOTIATION', 'TERMS_REVIEW', 'terms_final', null, null, 'tsu', false, timestamptz '2026-07-20T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'TERMS_REVIEW', 'REQUIREMENTS_PREP', 'skip_marketing_review', null, null, 'tsuhead', false, timestamptz '2026-07-21T09:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'REQUIREMENTS_PREP', 'FOR_MANCOM', 'submit_requirements', null, null, 'tsu', false, timestamptz '2026-07-27T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'FOR_MANCOM', 'WITH_MBS', 'signoff', null, null, 'mancom', false, timestamptz '2026-08-03T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'WITH_MBS', 'FOR_VALIDATION', 'setup', null, 'Version 2 of PAR08', 'mbs', false, timestamptz '2026-08-05T10:00:00+08');
insert into wf_case_history (case_id, from_stage, to_stage, action, reason_code, comment, actor, automatic, occurred_at)
values ((select id from wf_case where entity_type = 'PackageRequest' and reference = 'PKR-2026-900006'), 'FOR_VALIDATION', 'RELEASED', 'version_released', null, 'Version 2 validated by badmin', 'badmin', true, timestamptz '2026-08-07T15:00:00+08');
insert into pm_negotiation_round (request_id, round_no, status, qs_no, qs_template, qs_notes, reply_due, prepared_by, submitted_at, approved_by, approved_at, sent_at, locked, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900006'), 1, 'SENT', 'PQS-2026-900004', 'PKG_QUOTATION_SLIP v1', 'Terms as requested', date '2026-07-10', 'tsu', timestamptz '2026-07-03T09:00:00+08', 'tsulead', timestamptz '2026-07-03T14:00:00+08', timestamptz '2026-07-03T14:00:00+08', true, timestamptz '2026-07-03T09:00:00+08', 'tsu');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900004'), 0, 'INS-MGIC');
insert into pm_round_insurer (round_id, insurer_index, insurer_code) values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900004'), 1, 'INS-MPI');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900004'), 'INS-MGIC', 'Mabuhay General Insurance Corp.', 'ACCEPTED_AS_REQUESTED', 1, 0.25, 1000, '[]', null, date '2026-12-31', 'Lead insurer', timestamptz '2026-07-09T10:00:00+08', 1, timestamptz '2026-07-09T10:00:00+08', 'tsulead', timestamptz '2026-07-09T10:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-MGIC' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900004')), 1, 'ACCEPTED_AS_REQUESTED', 0.25, 1000, '[]', null, date '2026-12-31', 'Lead insurer', 'tsu', timestamptz '2026-07-09T10:00:00+08');
insert into pm_insurer_response (round_id, insurer_code, insurer_name, outcome, revision, rate, minimum_premium, terms, conditions, valid_until, remarks, responded_at, sends, created_at, created_by, updated_at, updated_by)
values ((select id from pm_negotiation_round where qs_no = 'PQS-2026-900004'), 'INS-MPI', 'Mindanao Pacific Insurance Inc.', 'NO_RESPONSE', 1, null, null, '[]', null, null, 'No reply by the due date', timestamptz '2026-07-15T10:00:00+08', 1, timestamptz '2026-07-15T10:00:00+08', 'tsulead', timestamptz '2026-07-15T10:00:00+08', 'tsu');
insert into pm_insurer_response_history (response_id, revision, outcome, rate, minimum_premium, terms, conditions, valid_until, remarks, changed_by, changed_at)
values ((select id from pm_insurer_response where insurer_code = 'INS-MPI' and round_id = (select id from pm_negotiation_round where qs_no = 'PQS-2026-900004')), 1, 'NO_RESPONSE', null, null, '[]', null, null, 'No reply by the due date', 'tsu', timestamptz '2026-07-15T10:00:00+08');
insert into pm_signoff (request_id, kind, decision, reference, signed_by, signed_at, comment, created_at, created_by)
values ((select id from pm_request where request_no = 'PKR-2026-900006'), 'MANCOM', 'SIGNED', 'MC-PKR-2026-900006', 'mancom', timestamptz '2026-08-03T10:00:00+08', null, timestamptz '2026-08-03T10:00:00+08', 'mancom');
insert into pm_advisory (company_id, request_id, product_code, version_no, advisory_type, recipient_groups, subject, body, template_version, status, sent_by, sent_at, created_at, created_by)
values ((select id from org_company where code = 'FVI'), (select id from pm_request where request_no = 'PKR-2026-900006'), 'PAR08', 2, 'PACKAGE_UPDATED', 'MARKETING,TSU,MBS,OPERATIONS', 'Package advisory: PAR08 - Home fire programme PAR08 - allied perils', 'This is to advise that the package PAR08 - Home fire programme PAR08 - allied perils (version 2) is available for new business from 2026-09-01. The signed package slip and the ManCom sign-off are kept with request PKR-2026-900006 in BIBS.', 'PKG_ADVISORY v1', 'SENT', 'tsulead', timestamptz '2026-08-08T09:00:00+08', timestamptz '2026-08-07T15:00:00+08', 'SYSTEM');
