package com.iortatechnxt.brokerverse.submitted.seed;

import java.util.List;

/**
 * Rows of the seed policies (seed profile only): PN (empty when the source has none), segment,
 * business type, assured, insurer, days to expiry, sum insured, unit or location, plate (motor),
 * vehicle type or occupancy, and the mark (FFY, EMP for a group employee, NT for No Touch).
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals") // seed table: the codes repeat per row
final class SubmittedSeedRows {

  /** Seed rows. */
  static final List<SeedRow> ROWS =
      List.of(
          new SeedRow(
              "PN-MTR-26001",
              "CBG_MOTOR",
              "NB",
              "Andres Villanueva",
              "INS-MGIC",
              "55",
              "1450000",
              "2023 Toyota Vios 1.3 XLE",
              "NDA 1201",
              "Sedan",
              ""),
          new SeedRow(
              "PN-MTR-26002",
              "CBG_MOTOR",
              "NB",
              "Bea Soriano",
              "INS-LAC",
              "58",
              "980000",
              "2022 Honda City 1.5 V",
              "NDB 2202",
              "Sedan",
              ""),
          new SeedRow(
              "PN-MTR-26003",
              "CBG_MOTOR",
              "RB",
              "Carlo Mendoza",
              "INS-MGIC",
              "62",
              "720000",
              "2021 Mitsubishi Mirage G4",
              "NDC 3303",
              "Sedan",
              ""),
          new SeedRow(
              "PN-MTR-26004",
              "CBG_MOTOR",
              "NB",
              "Dina Ramos",
              "INS-LAC",
              "70",
              "1100000",
              "2022 Suzuki Ertiga GLX",
              "NDD 4404",
              "MPV",
              ""),
          new SeedRow(
              "PN-MTR-26005",
              "CBG_MOTOR",
              "NB",
              "Emilio Santos",
              "INS-MGIC",
              "45",
              "6500000",
              "2024 Toyota Land Cruiser Prado",
              "NDE 5505",
              "SUV",
              ""),
          new SeedRow(
              "PN-MTR-26006",
              "CBG_MOTOR",
              "NB",
              "Faye Aquino",
              "INS-LAC",
              "80",
              "1350000",
              "2023 Isuzu Traviz L",
              "NDF 6606",
              "Truck",
              ""),
          new SeedRow(
              "PN-MTR-26007",
              "CBG_MOTOR",
              "NB",
              "Gabriel Cruz",
              "INS-MGIC",
              "40",
              "890000",
              "2022 Nissan Almera VE",
              "NDG 7707",
              "Sedan",
              "FFY"),
          new SeedRow(
              "PN-MTR-26008",
              "CBG_MOTOR",
              "NB",
              "Hazel Lim",
              "INS-MGIC",
              "40",
              "1250000",
              "2023 Toyota Rush 1.5 G",
              "NDH 8808",
              "SUV",
              "NT"),
          new SeedRow(
              "PN-MTR-26009",
              "CBG_MOTOR",
              "NB",
              "Ivan Dela Cruz",
              "INS-MGIC",
              "41",
              "2100000",
              "2024 Ford Everest Trend",
              "NDI 9909",
              "SUV",
              "NT"),
          new SeedRow(
              "PN-MTR-26010",
              "CBG_MOTOR",
              "RB",
              "Jasmine Reyes",
              "INS-LAC",
              "90",
              "650000",
              "2020 Hyundai Accent 1.4",
              "NDJ 1010",
              "Sedan",
              "EMP"),
          new SeedRow(
              "PN-MTR-26011",
              "CBG_MOTOR",
              "NB",
              "Kevin Uy",
              "INS-MGIC",
              "75",
              "1500000",
              "2023 Mazda CX-5 FWD",
              "NDK 1111",
              "SUV",
              ""),
          new SeedRow(
              "PN-FIR-26001",
              "CBG_FIRE",
              "NB",
              "Kristine Bautista",
              "INS-VMI",
              "50",
              "6500000",
              "Lot 5 Blk 3 Palm Village, Makati City",
              "",
              "Residential",
              ""),
          new SeedRow(
              "PN-FIR-26002",
              "CBG_FIRE",
              "NB",
              "Leonardo Garcia",
              "INS-VMI",
              "65",
              "4800000",
              "12 Acacia St., Ayala Alabang, Muntinlupa City",
              "",
              "Residential",
              ""),
          new SeedRow(
              "PN-FIR-26003",
              "CBG_FIRE",
              "RB",
              "Marites Flores",
              "INS-MPI",
              "72",
              "3900000",
              "88 Mango Ave., Cebu City",
              "",
              "Commercial",
              ""),
          new SeedRow(
              "PN-FIR-26004",
              "CBG_FIRE",
              "NB",
              "Nestor Castillo",
              "INS-VMI",
              "85",
              "2500000",
              "7 Narra Rd., Matina, Davao City",
              "",
              "Residential",
              ""),
          new SeedRow(
              "PN-FIR-26005",
              "CBG_FIRE",
              "NB",
              "Olivia Navarro",
              "INS-MPI",
              "95",
              "9800000",
              "Unit 21B One Serendra, Taguig City",
              "",
              "Residential",
              ""),
          new SeedRow(
              "",
              "NONCBG_CORPORATE",
              "NB",
              "Pacific Harbor Logistics Inc.",
              "INS-MPI",
              "60",
              "45000000",
              "Warehouse 3, Harbor Road, Tondo, Manila",
              "",
              "Warehouse",
              ""),
          new SeedRow(
              "",
              "NONCBG_CORPORATE",
              "NB",
              "Sierra Agro Holdings Corp.",
              "INS-MPI",
              "75",
              "18000000",
              "Rice mill, Cabanatuan City, Nueva Ecija",
              "",
              "Industrial",
              ""),
          new SeedRow(
              "",
              "NONCBG_CORPORATE",
              "RB",
              "Metro Print Solutions Inc.",
              "INS-MPI",
              "100",
              "12500000",
              "Printing plant, Pasig City",
              "",
              "Industrial",
              ""),
          new SeedRow(
              "",
              "NONCBG_RETAIL",
              "NB",
              "Quintin Salazar",
              "INS-MGIC",
              "68",
              "850000",
              "Condominium unit, Mandaluyong City",
              "",
              "Residential",
              ""),
          new SeedRow(
              "",
              "NONCBG_RETAIL",
              "NB",
              "Rowena Tan",
              "INS-MGIC",
              "110",
              "1200000",
              "Townhouse, Antipolo City",
              "",
              "Residential",
              ""));

  private SubmittedSeedRows() {}

  /**
   * A seed policy.
   *
   * @param pn PN number, empty when the source has none
   * @param segment segment
   * @param businessType NB or RB
   * @param assured assured
   * @param insurer insurer
   * @param days days to expiry
   * @param sumInsured sum insured
   * @param unit unit or location
   * @param plate plate number (motor)
   * @param kind vehicle type or occupancy
   * @param mark FFY, EMP or NT
   */
  @SuppressWarnings("java:S107") // one seed row
  record SeedRow(
      String pn,
      String segment,
      String businessType,
      String assured,
      String insurer,
      String days,
      String sumInsured,
      String unit,
      String plate,
      String kind,
      String mark) {}
}
