package com.iortatechnxt.brokerverse.journal.service;

import com.iortatechnxt.brokerverse.common.security.CurrentUser;
import com.iortatechnxt.brokerverse.journal.domain.JournalBatch;
import com.iortatechnxt.brokerverse.journal.domain.JournalBatchRepository;
import com.iortatechnxt.brokerverse.journal.domain.JournalHeader;
import com.iortatechnxt.brokerverse.journal.domain.JournalStatus;
import com.iortatechnxt.brokerverse.security.service.UserDirectory;
import java.time.Clock;
import java.time.LocalDate;
import java.util.EnumSet;
import java.util.Optional;
import java.util.Set;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Posts journals generated by the accounting engine and period-end processes.
 *
 * <p>The business transaction that raised the event was itself authorized in its module (policy,
 * claim, receipt...), so its journal is validated and posted immediately. Idempotent on {@code
 * sourceModule + sourceReference}: replaying an event never double-posts.
 */
@Service
@Transactional
public class SystemJournalService {

  private static final Set<JournalStatus> DEAD_STATUSES =
      EnumSet.of(JournalStatus.CANCELLED, JournalStatus.REJECTED);

  private final JournalBatchRepository batches;
  private final JournalFactory factory;
  private final JournalValidator validator;
  private final PostingService posting;
  private final UserDirectory userDirectory;
  private final CurrentUser currentUser;
  private final Clock clock;

  /**
   * Creates the service.
   *
   * @param batches batch repository
   * @param factory journal factory
   * @param validator validator
   * @param posting posting engine
   * @param userDirectory user facts
   * @param currentUser current user
   * @param clock clock
   */
  public SystemJournalService(
      JournalBatchRepository batches,
      JournalFactory factory,
      JournalValidator validator,
      PostingService posting,
      UserDirectory userDirectory,
      CurrentUser currentUser,
      Clock clock) {
    this.batches = batches;
    this.factory = factory;
    this.validator = validator;
    this.posting = posting;
    this.userDirectory = userDirectory;
    this.currentUser = currentUser;
    this.clock = clock;
  }

  /**
   * Creates and immediately posts a system generated journal.
   *
   * @param request system journal
   * @return posted batch (the existing one when the source event was already posted)
   */
  public JournalBatch post(SystemJournalRequest request) {
    Optional<JournalBatch> existing =
        batches.findFirstByCompanyIdAndSourceModuleAndSourceReferenceAndStatusNotIn(
            request.companyId(), request.sourceModule(), request.sourceReference(), DEAD_STATUSES);
    if (existing.isPresent()) {
      return existing.get();
    }
    JournalHeader header =
        new JournalHeader(
            request.companyId(),
            request.branchId(),
            request.journalType(),
            LocalDate.now(clock),
            request.valueDate(),
            request.currency(),
            request.narration(),
            request.reference(),
            request.sourceModule(),
            request.sourceReference(),
            null);
    JournalBatch batch = factory.create(header, request.lines());
    String user = currentUser.username();
    validator.validate(batch, userDirectory.roleCodes(user));
    batch.submit(user, clock.instant());
    batch.authorize(user, clock.instant(), true);
    posting.post(batch, user);
    return batch;
  }
}
