package com.iortatechnxt.brokerverse.placement.api.dto;

import com.iortatechnxt.brokerverse.placement.domain.PlacementSlip;
import com.iortatechnxt.brokerverse.placement.domain.SlipAccount;
import java.time.Instant;
import java.util.List;

/**
 * A placement slip version (BRNB.069/071).
 *
 * @param id id
 * @param slipNo slip number
 * @param versionNo version
 * @param displayNo number with version
 * @param insurerCode insurer
 * @param branchCode insurer branch
 * @param status status
 * @param templateVersion template version used
 * @param recipients last recipients
 * @param sentAt last send
 * @param sendCount number of sends
 * @param createdAt generated at
 * @param createdBy generated by
 * @param accounts accounts on the slip
 */
public record SlipResponse(
    Long id,
    String slipNo,
    int versionNo,
    String displayNo,
    String insurerCode,
    String branchCode,
    String status,
    String templateVersion,
    String recipients,
    Instant sentAt,
    int sendCount,
    Instant createdAt,
    String createdBy,
    List<SlipAccount> accounts) {

  /**
   * Maps a slip.
   *
   * @param s slip
   * @return response
   */
  public static SlipResponse from(PlacementSlip s) {
    return new SlipResponse(
        s.getId(),
        s.getSlipNo(),
        s.getVersionNo(),
        s.displayNo(),
        s.getInsurerCode(),
        s.getBranchCode(),
        s.getStatus().name(),
        s.getTemplateVersion(),
        s.getRecipients(),
        s.getSentAt(),
        s.getSendCount(),
        s.getCreatedAt(),
        s.getCreatedBy(),
        s.getAccounts());
  }
}
