package com.iortatechnxt.brokerverse.booking.service;

import com.iortatechnxt.brokerverse.common.security.CurrentUser;
import com.iortatechnxt.brokerverse.storage.domain.FileOrigin;
import com.iortatechnxt.brokerverse.storage.service.FileOwnerAccess;
import com.iortatechnxt.brokerverse.storage.service.LegacyFileTable;
import com.iortatechnxt.brokerverse.storage.service.PermissionFileAccess;
import java.util.List;
import java.util.Set;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * The stored PDFs of service invoices (owner type {@value ServiceInvoiceDocument#OWNER_TYPE}):
 * opened by the booking team ({@code BOOKING_PROCESS}, {@code BOOKING_ADJUST}), as for the service
 * invoice screen; generated by the application only. Also declares {@code bkg_service_invoice} for
 * the copy of the PDFs kept in the database before ST1.
 */
@Configuration(proxyBeanMethods = false)
public class ServiceInvoiceFileStorage {

  /**
   * Who may open the files.
   *
   * @param currentUser current user
   * @return resolver
   */
  @Bean
  FileOwnerAccess serviceInvoiceFileAccess(CurrentUser currentUser) {
    return new PermissionFileAccess(
        Set.of(ServiceInvoiceDocument.OWNER_TYPE),
        List.of("BOOKING_PROCESS", "BOOKING_ADJUST"),
        currentUser);
  }

  /**
   * Service invoice PDFs kept in the database before ST1.
   *
   * @return table
   */
  @Bean
  static LegacyFileTable serviceInvoiceTable() {
    return new LegacyFileTable(
        "bkg_service_invoice",
        ServiceInvoiceDocument.OWNER_TYPE,
        FileOrigin.GENERATED,
        "select s.id as file_key, s.company_id, s.si_no as owner_id, '"
            + ServiceInvoiceDocument.RECORD_CLASS
            + "' as record_class, s.kind as document_type, s.si_no || '.pdf' as file_name,"
            + " 'application/pdf' as content_type, cast(null as varchar) as recorded_sha256,"
            + " s.document as content from bkg_service_invoice s where s.document is not null"
            + " and s.stored_file_id is null and s.id > ? order by s.id limit ?",
        "update bkg_service_invoice set stored_file_id = ? where id = ? and stored_file_id is null",
        "select count(*) as total, count(stored_file_id) as moved"
            + " from bkg_service_invoice where document is not null");
  }
}
